// Searchable database of stocks, ETFs, and crypto
export type AssetEntry = { ticker: string; name: string; sector: string; type: "stock" | "etf" | "crypto" };

export const assetDatabase: AssetEntry[] = [
  // Major Stocks - Technology
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", type: "stock" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology", type: "stock" },
  { ticker: "GOOGL", name: "Alphabet Inc.", sector: "Technology", type: "stock" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Technology", type: "stock" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Technology", type: "stock" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Technology", type: "stock" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Technology", type: "stock" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology", type: "stock" },
  { ticker: "INTC", name: "Intel Corporation", sector: "Technology", type: "stock" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", type: "stock" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology", type: "stock" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology", type: "stock" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", type: "stock" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology", type: "stock" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", type: "stock" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", type: "stock" },
  { ticker: "IBM", name: "IBM Corporation", sector: "Technology", type: "stock" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", type: "stock" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology", type: "stock" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology", type: "stock" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology", type: "stock" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology", type: "stock" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology", type: "stock" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology", type: "stock" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology", type: "stock" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology", type: "stock" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Technology", type: "stock" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology", type: "stock" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology", type: "stock" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology", type: "stock" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Technology", type: "stock" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology", type: "stock" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology", type: "stock" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", type: "stock" },
  { ticker: "SQ", name: "Block Inc.", sector: "Technology", type: "stock" },
  { ticker: "UBER", name: "Uber Technologies", sector: "Technology", type: "stock" },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Technology", type: "stock" },
  { ticker: "SPOT", name: "Spotify Technology", sector: "Technology", type: "stock" },
  { ticker: "COIN", name: "Coinbase Global", sector: "Technology", type: "stock" },
  { ticker: "RBLX", name: "Roblox Corporation", sector: "Technology", type: "stock" },
  { ticker: "U", name: "Unity Software", sector: "Technology", type: "stock" },
  { ticker: "TWLO", name: "Twilio Inc.", sector: "Technology", type: "stock" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", type: "stock" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ARM", name: "Arm Holdings", sector: "Technology", type: "stock" },
  // Consumer
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer", type: "stock" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer", type: "stock" },
  { ticker: "KO", name: "The Coca-Cola Company", sector: "Consumer", type: "stock" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer", type: "stock" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer", type: "stock" },
  { ticker: "DIS", name: "Walt Disney Company", sector: "Consumer", type: "stock" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer", type: "stock" },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer", type: "stock" },
  { ticker: "MCD", name: "McDonald's Corporation", sector: "Consumer", type: "stock" },
  { ticker: "SBUX", name: "Starbucks Corporation", sector: "Consumer", type: "stock" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer", type: "stock" },
  { ticker: "HD", name: "The Home Depot", sector: "Consumer", type: "stock" },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer", type: "stock" },
  { ticker: "EL", name: "Estée Lauder Companies", sector: "Consumer", type: "stock" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer", type: "stock" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer", type: "stock" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer", type: "stock" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer", type: "stock" },
  { ticker: "KHC", name: "Kraft Heinz Company", sector: "Consumer", type: "stock" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer", type: "stock" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer", type: "stock" },
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer", type: "stock" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer", type: "stock" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer", type: "stock" },
  // Finance
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc.", sector: "Finance", type: "stock" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Finance", type: "stock" },
  { ticker: "V", name: "Visa Inc.", sector: "Finance", type: "stock" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Finance", type: "stock" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Finance", type: "stock" },
  { ticker: "BAC", name: "Bank of America", sector: "Finance", type: "stock" },
  { ticker: "WFC", name: "Wells Fargo & Co.", sector: "Finance", type: "stock" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Finance", type: "stock" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Finance", type: "stock" },
  { ticker: "AXP", name: "American Express", sector: "Finance", type: "stock" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Finance", type: "stock" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Finance", type: "stock" },
  { ticker: "SPGI", name: "S&P Global", sector: "Finance", type: "stock" },
  { ticker: "CME", name: "CME Group", sector: "Finance", type: "stock" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Finance", type: "stock" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Finance", type: "stock" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Finance", type: "stock" },
  { ticker: "PYPL", name: "PayPal Holdings", sector: "Finance", type: "stock" },
  // Healthcare
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", type: "stock" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare", type: "stock" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "LLY", name: "Eli Lilly & Co.", sector: "Healthcare", type: "stock" },
  { ticker: "MRK", name: "Merck & Co.", sector: "Healthcare", type: "stock" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", type: "stock" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "stock" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "ZTS", name: "Zoetis Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare", type: "stock" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare", type: "stock" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare", type: "stock" },
  { ticker: "HUM", name: "Humana Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare", type: "stock" },
  // Energy
  { ticker: "XOM", name: "Exxon Mobil Corporation", sector: "Energy", type: "stock" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy", type: "stock" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Energy", type: "stock" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", type: "stock" },
  { ticker: "SLB", name: "Schlumberger Limited", sector: "Energy", type: "stock" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy", type: "stock" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", type: "stock" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", type: "stock" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", type: "stock" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", type: "stock" },
  { ticker: "ENB", name: "Enbridge Inc.", sector: "Energy", type: "stock" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy", type: "stock" },
  // Industrial
  { ticker: "BA", name: "Boeing Company", sector: "Industrial", type: "stock" },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrial", type: "stock" },
  { ticker: "GE", name: "General Electric", sector: "Industrial", type: "stock" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrial", type: "stock" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrial", type: "stock" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrial", type: "stock" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrial", type: "stock" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrial", type: "stock" },
  { ticker: "MMM", name: "3M Company", sector: "Industrial", type: "stock" },
  { ticker: "FDX", name: "FedEx Corporation", sector: "Industrial", type: "stock" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrial", type: "stock" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrial", type: "stock" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrial", type: "stock" },
  // Telecom & Utilities
  { ticker: "T", name: "AT&T Inc.", sector: "Telecom", type: "stock" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Telecom", type: "stock" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Telecom", type: "stock" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities", type: "stock" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", type: "stock" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", type: "stock" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", type: "stock" },
  // Real Estate
  { ticker: "AMT", name: "American Tower", sector: "Real Estate", type: "stock" },
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate", type: "stock" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate", type: "stock" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate", type: "stock" },
  // Materials
  { ticker: "LIN", name: "Linde plc", sector: "Materials", type: "stock" },
  { ticker: "APD", name: "Air Products & Chemicals", sector: "Materials", type: "stock" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", type: "stock" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", type: "stock" },
  { ticker: "NEM", name: "Newmont Corporation", sector: "Materials", type: "stock" },
  { ticker: "NUE", name: "Nucor Corporation", sector: "Materials", type: "stock" },
  // ETFs
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", sector: "Index", type: "etf" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", sector: "Technology", type: "etf" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", sector: "Index", type: "etf" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", sector: "Index", type: "etf" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", sector: "Index", type: "etf" },
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "Innovation", type: "etf" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR", sector: "Healthcare", type: "etf" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR", sector: "Consumer", type: "etf" },
  { ticker: "XLE", name: "Energy Select Sector SPDR", sector: "Energy", type: "etf" },
  { ticker: "XLF", name: "Financial Select Sector SPDR", sector: "Finance", type: "etf" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR", sector: "Industrial", type: "etf" },
  { ticker: "XLK", name: "Technology Select Sector SPDR", sector: "Technology", type: "etf" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR", sector: "Utilities", type: "etf" },
  { ticker: "VDE", name: "Vanguard Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "GDX", name: "VanEck Gold Miners ETF", sector: "Materials", type: "etf" },
  { ticker: "GLD", name: "SPDR Gold Shares", sector: "Commodities", type: "etf" },
  { ticker: "SLV", name: "iShares Silver Trust", sector: "Commodities", type: "etf" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF", sector: "Technology", type: "etf" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", sector: "Real Estate", type: "etf" },
  { ticker: "SCHD", name: "Schwab U.S. Dividend Equity ETF", sector: "Index", type: "etf" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial ETF", sector: "Index", type: "etf" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", sector: "International", type: "etf" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", sector: "International", type: "etf" },
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF", sector: "International", type: "etf" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", sector: "International", type: "etf" },
  { ticker: "AGG", name: "iShares Core US Aggregate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "KWEB", name: "KraneShares CSI China Internet ETF", sector: "International", type: "etf" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF", sector: "Technology", type: "etf" },
  // Crypto
  { ticker: "BTCUSD", name: "Bitcoin", sector: "Crypto", type: "crypto" },
  { ticker: "ETHUSD", name: "Ethereum", sector: "Crypto", type: "crypto" },
  { ticker: "SOLUSD", name: "Solana", sector: "Crypto", type: "crypto" },
  { ticker: "ADAUSD", name: "Cardano", sector: "Crypto", type: "crypto" },
  { ticker: "DOTUSD", name: "Polkadot", sector: "Crypto", type: "crypto" },
  { ticker: "AVAXUSD", name: "Avalanche", sector: "Crypto", type: "crypto" },
  { ticker: "LINKUSD", name: "Chainlink", sector: "Crypto", type: "crypto" },
  { ticker: "MATICUSD", name: "Polygon", sector: "Crypto", type: "crypto" },
  { ticker: "XRPUSD", name: "XRP", sector: "Crypto", type: "crypto" },
  { ticker: "DOGEUSD", name: "Dogecoin", sector: "Crypto", type: "crypto" },
  { ticker: "BNBUSD", name: "BNB", sector: "Crypto", type: "crypto" },
  { ticker: "TONUSD", name: "Toncoin", sector: "Crypto", type: "crypto" },
  { ticker: "TRXUSD", name: "TRON", sector: "Crypto", type: "crypto" },
  { ticker: "NEARUSD", name: "NEAR Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SUIUSD", name: "Sui", sector: "Crypto", type: "crypto" },
];

export function searchAssets(query: string): AssetEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return assetDatabase
    .filter((a) => a.ticker.toLowerCase().includes(q) || a.name.toLowerCase().includes(q) || a.sector.toLowerCase().includes(q))
    .slice(0, 12);
}
