import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "fr" | "pt";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    dashboard: "Dashboard", aiChat: "AI Chat", quiz: "Quiz", forum: "Forum", watchlists: "Watchlists", settings: "Settings",
    // Dashboard
    marketIntelligence: "Market Intelligence", aiCuratedAnalysis: "AI-curated analysis with trust scores and live market data",
    analyzeLink: "Analyze Link", analyze: "Analyze", analyzing: "Analyzing...",
    pasteUrl: "Paste any financial news article URL. AI will provide a trust/bias score (1-10), summary, and bias detection.",
    trustScore: "Trust Score", smartSummary: "Smart Summary", biasDetection: "Bias Detection",
    stockHeatmap: "S&P 500 Stock Heatmap",
    marketNewsFeed: "Market News Feed", autoRefresh: "Auto-refreshes",
    newsDisclaimer: "News provided by TradingView. For informational purposes only — not financial advice.",
    crypto: "Crypto", etfs: "ETFs",
    trustScoreDesc: "AI rates source credibility, author expertise, and citation quality on a 1-10 scale",
    smartSummaryDesc: "Get a concise summary highlighting key claims, data points, and conclusions",
    biasDetectionDesc: "Flags promotional language, missing disclosures, and potential conflicts of interest",
    pasteArticleUrl: "Paste article URL (e.g. https://cnbc.com/article/...)",
    source: "Source",
    summary: "Summary",
    potentialBiases: "Potential Biases",
    strengths: "Strengths",
    // AI Chat
    aiFinancialAdvisor: "AI Financial Advisor", poweredByAI: "Powered by AI · Educational use only",
    history: "History", newChat: "New Chat", chatHistory: "Chat History", noSavedChats: "No saved chats yet.",
    askAnything: "Ask anything about finance, investing, markets...",
    welcomeMessage: "Hello! I'm your AI financial advisor. Ask me anything about investing, markets, or portfolio strategies.",
    suggestETF: "What's the difference between ETFs and mutual funds?",
    suggestDiversify: "How should I diversify my portfolio?",
    suggestPE: "Explain P/E ratio and how to use it",
    suggestDCA: "What is dollar-cost averaging?",
    // Forum
    smartForum: "Smart Forum", discussInvestments: "Discuss investments with AI-powered fact-checking",
    newThread: "New Thread", createNewThread: "Create New Thread", threadTitle: "Thread title...",
    shareThoughts: "Share your thoughts...", postThread: "Post Thread", cancel: "Cancel",
    searchThreads: "Search threads...", factCheck: "Fact Check", writeComment: "Write a comment...",
    all: "All", general: "General", portfolios: "Portfolios", markets: "Markets", sectors: "Sectors",
    noCommentsYet: "No comments yet. Be the first!",
    moderationError: "Your post was flagged for inappropriate content. Please revise and try again.",
    tag: "Tag",
    // Watchlists
    trackStocks: "Track your favorite stocks and ETFs", newList: "New List",
    createNewWatchlist: "Create New Watchlist", watchlistName: "Watchlist name...", create: "Create",
    addStock: "Add Stock", searchStocksEtfs: "Search stocks, ETFs, crypto...", noStocksYet: "No stocks yet. Add some!",
    noWatchlistsYet: "No Watchlists Yet", createFirstWatchlist: "Create your first watchlist to start tracking stocks.",
    createWatchlist: "Create Watchlist", items: "items",
    startTypingSearch: "Start typing to search...", noResults: "No results found",
    // Quiz
    riskTolerance: "Risk Tolerance", riskToleranceSub: "How comfortable are you with market volatility?",
    conservative: "Conservative", conservativeDesc: "Prefer stability and capital preservation",
    moderate: "Moderate", moderateDesc: "Balanced growth with managed risk",
    aggressive: "Aggressive", aggressiveDesc: "Maximum growth, higher volatility",
    investmentTimeframe: "Investment Timeframe", investmentTimeframeSub: "When do you plan to use these funds?",
    shortTerm: "1-3 Years", shortTermDesc: "Short-term goals",
    mediumTerm: "3-7 Years", mediumTermDesc: "Medium-term planning",
    longTerm: "7+ Years", longTermDesc: "Long-term wealth building",
    profitGoals: "Profit Goals", profitGoalsSub: "What annual return are you targeting?",
    steadyIncome: "5% / year", steadyIncomeDesc: "Steady income",
    growthOriented: "10% / year", growthOrientedDesc: "Growth-oriented",
    aggressiveGrowth: "20%+ / year", aggressiveGrowthDesc: "Aggressive growth",
    investmentExperience: "Investment Experience", investmentExperienceSub: "How would you describe your investing background?",
    beginner: "Beginner", beginnerDesc: "New to investing",
    intermediate: "Intermediate", intermediateDesc: "Some experience",
    advanced: "Advanced", advancedDesc: "Experienced investor",
    sectorInterests: "Sector Interests", sectorInterestsSub: "Select sectors you're interested in (optional)",
    technology: "Technology", healthcare: "Healthcare", finance: "Finance", energy: "Energy", consumer: "Consumer", industrial: "Industrial",
    step: "Step", of: "of", back: "Back", continue: "Continue", generatePortfolio: "Generate Portfolio",
    yourPersonalizedPortfolio: "Your Personalized Portfolio", recommendedAllocations: "Recommended Allocations",
    bearCase: "Bear Case", baseCase: "Base Case", bullCase: "Bull Case", fiveYearReturn: "5-year return",
    expectedReturn: "Expected Return", riskLevel: "Risk Level", retakeQuiz: "Retake Quiz", buildThisPortfolio: "Build This Portfolio",
    // Settings
    profile: "Profile", displayName: "Display Name", changesSaveAuto: "Changes save automatically",
    email: "Email", emailCannotChange: "Email cannot be changed", username: "Username",
    anonymousMode: "Anonymous Mode", hideNameAvatar: "Hide your name and avatar in forum posts",
    appearAs: "You will appear as", anonymousTrader: "Anonymous Trader",
    language: "Language", selectLanguage: "Choose your preferred language",
    logOut: "Log Out", uploadPhoto: "Upload Photo", avatarRecommendation: "200×200px recommended. JPG, PNG",
    // Auth
    createAccount: "Create Account", logIn: "Log In", emailAddress: "Email address", password: "Password",
    alreadyHaveAccount: "Already have an account?", dontHaveAccount: "Don't have an account?",
    signUp: "Sign up", fillAllFields: "Please fill in all fields", passwordMin6: "Password must be at least 6 characters",
    chooseUsername: "Choose a username", usernameRequired: "Username is required", usernameMin3: "Username must be at least 3 characters",
    usernameTaken: "This username is already taken", usernameAvailable: "Username is available!",
    emailInUse: "This email is already registered.", switchToLogin: "Switch to Log In",
    invalidEmail: "Please enter a valid email address",
    // Stock Detail
    backToWatchlists: "Back to Watchlists", about: "About", technicalAnalysis: "Technical Analysis", recentNews: "Recent News",
    // Disclaimer
    notFinancialAdvice: "Not financial advice",
    disclaimerText: "AI analysis is for informational purposes only. Always consult qualified financial professionals before making investment decisions.",
    // Misc
    deleteThread: "Delete thread", deleteComment: "Delete comment",
    notifications: "Notifications", markAllRead: "Mark all read", noNotifications: "No new notifications",
    imageAttached: "Image attached", uploadImage: "Upload image",
  },
  es: {
    dashboard: "Panel", aiChat: "Chat IA", quiz: "Cuestionario", forum: "Foro", watchlists: "Listas", settings: "Ajustes",
    marketIntelligence: "Inteligencia de Mercado", aiCuratedAnalysis: "Análisis con IA, puntuaciones de confianza y datos en vivo",
    analyzeLink: "Analizar Enlace", analyze: "Analizar", analyzing: "Analizando...",
    pasteUrl: "Pega cualquier URL de artículo financiero. La IA proporcionará una puntuación de confianza (1-10), resumen y detección de sesgo.",
    trustScore: "Puntuación de Confianza", smartSummary: "Resumen Inteligente", biasDetection: "Detección de Sesgo",
    stockHeatmap: "Mapa de Calor S&P 500",
    marketNewsFeed: "Noticias del Mercado", autoRefresh: "Se actualiza automáticamente",
    newsDisclaimer: "Noticias proporcionadas por TradingView. Solo con fines informativos, no es asesoramiento financiero.",
    crypto: "Cripto", etfs: "ETFs",
    trustScoreDesc: "La IA califica la credibilidad de la fuente, experiencia del autor y calidad de citas en una escala de 1-10",
    smartSummaryDesc: "Obtén un resumen conciso destacando afirmaciones clave, datos y conclusiones",
    biasDetectionDesc: "Señala lenguaje promocional, divulgaciones faltantes y posibles conflictos de interés",
    pasteArticleUrl: "Pega la URL del artículo (ej. https://cnbc.com/article/...)",
    source: "Fuente", summary: "Resumen", potentialBiases: "Sesgos Potenciales", strengths: "Fortalezas",
    aiFinancialAdvisor: "Asesor Financiero IA", poweredByAI: "Con IA · Solo uso educativo",
    history: "Historial", newChat: "Nuevo Chat", chatHistory: "Historial de Chats", noSavedChats: "Sin chats guardados.",
    askAnything: "Pregunta sobre finanzas, inversiones, mercados...",
    welcomeMessage: "¡Hola! Soy tu asesor financiero IA. Pregúntame sobre inversiones, mercados o estrategias de portafolio.",
    suggestETF: "¿Cuál es la diferencia entre ETFs y fondos mutuos?",
    suggestDiversify: "¿Cómo debo diversificar mi portafolio?",
    suggestPE: "Explica el ratio P/E y cómo usarlo",
    suggestDCA: "¿Qué es el promedio de costo en dólares?",
    smartForum: "Foro Inteligente", discussInvestments: "Discute inversiones con verificación de hechos por IA",
    newThread: "Nuevo Tema", createNewThread: "Crear Nuevo Tema", threadTitle: "Título del tema...",
    shareThoughts: "Comparte tus ideas...", postThread: "Publicar", cancel: "Cancelar",
    searchThreads: "Buscar temas...", factCheck: "Verificar", writeComment: "Escribe un comentario...",
    all: "Todos", general: "General", portfolios: "Portafolios", markets: "Mercados", sectors: "Sectores",
    noCommentsYet: "Sin comentarios aún. ¡Sé el primero!",
    moderationError: "Tu publicación fue marcada por contenido inapropiado. Revisa e intenta de nuevo.",
    tag: "Etiqueta",
    trackStocks: "Sigue tus acciones y ETFs favoritos", newList: "Nueva Lista",
    createNewWatchlist: "Crear Nueva Lista", watchlistName: "Nombre de la lista...", create: "Crear",
    addStock: "Agregar", searchStocksEtfs: "Buscar acciones, ETFs, cripto...", noStocksYet: "Sin acciones aún. ¡Agrega algunas!",
    noWatchlistsYet: "Sin Listas Aún", createFirstWatchlist: "Crea tu primera lista para empezar.",
    createWatchlist: "Crear Lista", items: "elementos",
    startTypingSearch: "Escribe para buscar...", noResults: "Sin resultados",
    riskTolerance: "Tolerancia al Riesgo", riskToleranceSub: "¿Qué tan cómodo estás con la volatilidad del mercado?",
    conservative: "Conservador", conservativeDesc: "Prefiere estabilidad y preservación del capital",
    moderate: "Moderado", moderateDesc: "Crecimiento equilibrado con riesgo gestionado",
    aggressive: "Agresivo", aggressiveDesc: "Máximo crecimiento, mayor volatilidad",
    investmentTimeframe: "Plazo de Inversión", investmentTimeframeSub: "¿Cuándo planeas usar estos fondos?",
    shortTerm: "1-3 Años", shortTermDesc: "Metas a corto plazo",
    mediumTerm: "3-7 Años", mediumTermDesc: "Planificación a mediano plazo",
    longTerm: "7+ Años", longTermDesc: "Creación de riqueza a largo plazo",
    profitGoals: "Metas de Ganancia", profitGoalsSub: "¿Qué rendimiento anual buscas?",
    steadyIncome: "5% / año", steadyIncomeDesc: "Ingreso estable",
    growthOriented: "10% / año", growthOrientedDesc: "Orientado al crecimiento",
    aggressiveGrowth: "20%+ / año", aggressiveGrowthDesc: "Crecimiento agresivo",
    investmentExperience: "Experiencia en Inversión", investmentExperienceSub: "¿Cómo describirías tu experiencia inversora?",
    beginner: "Principiante", beginnerDesc: "Nuevo en inversiones",
    intermediate: "Intermedio", intermediateDesc: "Algo de experiencia",
    advanced: "Avanzado", advancedDesc: "Inversor experimentado",
    sectorInterests: "Intereses por Sector", sectorInterestsSub: "Selecciona los sectores que te interesan (opcional)",
    technology: "Tecnología", healthcare: "Salud", finance: "Finanzas", energy: "Energía", consumer: "Consumo", industrial: "Industrial",
    step: "Paso", of: "de", back: "Atrás", continue: "Continuar", generatePortfolio: "Generar Portafolio",
    yourPersonalizedPortfolio: "Tu Portafolio Personalizado", recommendedAllocations: "Asignaciones Recomendadas",
    bearCase: "Caso Pesimista", baseCase: "Caso Base", bullCase: "Caso Optimista", fiveYearReturn: "Retorno a 5 años",
    expectedReturn: "Retorno Esperado", riskLevel: "Nivel de Riesgo", retakeQuiz: "Reiniciar Quiz", buildThisPortfolio: "Crear Este Portafolio",
    profile: "Perfil", displayName: "Nombre", changesSaveAuto: "Los cambios se guardan automáticamente",
    email: "Correo", emailCannotChange: "El correo no se puede cambiar", username: "Usuario",
    anonymousMode: "Modo Anónimo", hideNameAvatar: "Oculta tu nombre y avatar en publicaciones del foro",
    appearAs: "Aparecerás como", anonymousTrader: "Trader Anónimo",
    language: "Idioma", selectLanguage: "Elige tu idioma preferido",
    logOut: "Cerrar Sesión", uploadPhoto: "Subir Foto", avatarRecommendation: "200×200px recomendado. JPG, PNG",
    createAccount: "Crear Cuenta", logIn: "Iniciar Sesión", emailAddress: "Correo electrónico", password: "Contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?", dontHaveAccount: "¿No tienes una cuenta?",
    signUp: "Regístrate", fillAllFields: "Completa todos los campos", passwordMin6: "La contraseña debe tener al menos 6 caracteres",
    chooseUsername: "Elige un nombre de usuario", usernameRequired: "El nombre de usuario es obligatorio", usernameMin3: "El nombre de usuario debe tener al menos 3 caracteres",
    usernameTaken: "Este nombre de usuario ya está en uso", usernameAvailable: "¡Nombre de usuario disponible!",
    emailInUse: "Este correo ya está registrado.", switchToLogin: "Ir a Iniciar Sesión",
    invalidEmail: "Por favor ingresa un correo electrónico válido",
    backToWatchlists: "Volver a Listas", about: "Acerca de", technicalAnalysis: "Análisis Técnico", recentNews: "Noticias Recientes",
    notFinancialAdvice: "No es asesoramiento financiero",
    disclaimerText: "El análisis con IA es solo informativo. Siempre consulta a profesionales financieros calificados antes de tomar decisiones de inversión.",
    deleteThread: "Eliminar tema", deleteComment: "Eliminar comentario",
    notifications: "Notificaciones", markAllRead: "Marcar todo leído", noNotifications: "Sin notificaciones nuevas",
    imageAttached: "Imagen adjunta", uploadImage: "Subir imagen",
  },
  fr: {
    dashboard: "Tableau de bord", aiChat: "Chat IA", quiz: "Quiz", forum: "Forum", watchlists: "Listes", settings: "Paramètres",
    marketIntelligence: "Intelligence de Marché", aiCuratedAnalysis: "Analyse IA avec scores de confiance et données en direct",
    analyzeLink: "Analyser le Lien", analyze: "Analyser", analyzing: "Analyse en cours...",
    pasteUrl: "Collez l'URL d'un article financier. L'IA fournira un score de confiance (1-10), un résumé et une détection de biais.",
    trustScore: "Score de Confiance", smartSummary: "Résumé Intelligent", biasDetection: "Détection de Biais",
    stockHeatmap: "Carte Thermique S&P 500",
    marketNewsFeed: "Fil d'Actualités du Marché", autoRefresh: "Mise à jour automatique",
    newsDisclaimer: "Actualités fournies par TradingView. À titre informatif uniquement — pas de conseil financier.",
    technology: "Technologie", finance: "Finance", healthcare: "Santé", energy: "Énergie", consumer: "Consommation", crypto: "Crypto", etfs: "ETFs",
    trustScoreDesc: "L'IA évalue la crédibilité de la source, l'expertise de l'auteur et la qualité des citations sur une échelle de 1-10",
    smartSummaryDesc: "Obtenez un résumé concis mettant en évidence les affirmations clés, les données et les conclusions",
    biasDetectionDesc: "Signale le langage promotionnel, les divulgations manquantes et les conflits d'intérêts potentiels",
    pasteArticleUrl: "Collez l'URL de l'article (ex. https://cnbc.com/article/...)",
    source: "Source", summary: "Résumé", potentialBiases: "Biais Potentiels", strengths: "Points Forts",
    aiFinancialAdvisor: "Conseiller Financier IA", poweredByAI: "Alimenté par IA · Usage éducatif uniquement",
    history: "Historique", newChat: "Nouveau Chat", chatHistory: "Historique des Chats", noSavedChats: "Aucun chat sauvegardé.",
    askAnything: "Posez vos questions sur la finance, l'investissement...",
    welcomeMessage: "Bonjour ! Je suis votre conseiller financier IA. Posez-moi des questions sur l'investissement, les marchés ou les stratégies de portefeuille.",
    suggestETF: "Quelle est la différence entre les ETF et les fonds communs ?",
    suggestDiversify: "Comment diversifier mon portefeuille ?",
    suggestPE: "Expliquez le ratio P/E et comment l'utiliser",
    suggestDCA: "Qu'est-ce que le dollar-cost averaging ?",
    smartForum: "Forum Intelligent", discussInvestments: "Discutez d'investissements avec vérification IA",
    newThread: "Nouveau Sujet", createNewThread: "Créer un Nouveau Sujet", threadTitle: "Titre du sujet...",
    shareThoughts: "Partagez vos idées...", postThread: "Publier", cancel: "Annuler",
    searchThreads: "Rechercher des sujets...", factCheck: "Vérifier", writeComment: "Écrire un commentaire...",
    all: "Tout", general: "Général", portfolios: "Portefeuilles", markets: "Marchés", sectors: "Secteurs",
    noCommentsYet: "Pas encore de commentaires. Soyez le premier !",
    moderationError: "Votre publication a été signalée pour contenu inapproprié. Veuillez la réviser.",
    tag: "Tag",
    trackStocks: "Suivez vos actions et ETFs favoris", newList: "Nouvelle Liste",
    createNewWatchlist: "Créer une Nouvelle Liste", watchlistName: "Nom de la liste...", create: "Créer",
    addStock: "Ajouter", searchStocksEtfs: "Rechercher actions, ETFs, crypto...", noStocksYet: "Pas encore d'actions. Ajoutez-en !",
    noWatchlistsYet: "Pas de Listes", createFirstWatchlist: "Créez votre première liste pour commencer.",
    createWatchlist: "Créer une Liste", items: "éléments",
    startTypingSearch: "Tapez pour rechercher...", noResults: "Aucun résultat",
    riskTolerance: "Tolérance au Risque", riskToleranceSub: "À quel point êtes-vous à l'aise avec la volatilité ?",
    conservative: "Conservateur", conservativeDesc: "Préfère la stabilité et la préservation du capital",
    moderate: "Modéré", moderateDesc: "Croissance équilibrée avec risque géré",
    aggressive: "Agressif", aggressiveDesc: "Croissance maximale, volatilité plus élevée",
    investmentTimeframe: "Horizon d'Investissement", investmentTimeframeSub: "Quand prévoyez-vous d'utiliser ces fonds ?",
    shortTerm: "1-3 Ans", shortTermDesc: "Objectifs à court terme",
    mediumTerm: "3-7 Ans", mediumTermDesc: "Planification à moyen terme",
    longTerm: "7+ Ans", longTermDesc: "Création de richesse à long terme",
    profitGoals: "Objectifs de Profit", profitGoalsSub: "Quel rendement annuel visez-vous ?",
    steadyIncome: "5% / an", steadyIncomeDesc: "Revenu stable",
    growthOriented: "10% / an", growthOrientedDesc: "Orienté croissance",
    aggressiveGrowth: "20%+ / an", aggressiveGrowthDesc: "Croissance agressive",
    investmentExperience: "Expérience d'Investissement", investmentExperienceSub: "Comment décririez-vous votre expérience ?",
    beginner: "Débutant", beginnerDesc: "Nouveau dans l'investissement",
    intermediate: "Intermédiaire", intermediateDesc: "Un peu d'expérience",
    advanced: "Avancé", advancedDesc: "Investisseur expérimenté",
    sectorInterests: "Intérêts Sectoriels", sectorInterestsSub: "Sélectionnez les secteurs qui vous intéressent (optionnel)",
    technology: "Technologie", healthcare: "Santé", finance: "Finance", energy: "Énergie", consumer: "Consommation", industrial: "Industrie",
    step: "Étape", of: "sur", back: "Retour", continue: "Continuer", generatePortfolio: "Générer le Portefeuille",
    yourPersonalizedPortfolio: "Votre Portefeuille Personnalisé", recommendedAllocations: "Allocations Recommandées",
    bearCase: "Cas Pessimiste", baseCase: "Cas de Base", bullCase: "Cas Optimiste", fiveYearReturn: "Rendement à 5 ans",
    expectedReturn: "Rendement Attendu", riskLevel: "Niveau de Risque", retakeQuiz: "Refaire le Quiz", buildThisPortfolio: "Créer ce Portefeuille",
    profile: "Profil", displayName: "Nom d'affichage", changesSaveAuto: "Les modifications sont enregistrées automatiquement",
    email: "E-mail", emailCannotChange: "L'e-mail ne peut pas être modifié", username: "Nom d'utilisateur",
    anonymousMode: "Mode Anonyme", hideNameAvatar: "Masquer votre nom et avatar dans les publications du forum",
    appearAs: "Vous apparaîtrez comme", anonymousTrader: "Trader Anonyme",
    language: "Langue", selectLanguage: "Choisissez votre langue préférée",
    logOut: "Déconnexion", uploadPhoto: "Télécharger une Photo", avatarRecommendation: "200×200px recommandé. JPG, PNG",
    createAccount: "Créer un Compte", logIn: "Se Connecter", emailAddress: "Adresse e-mail", password: "Mot de passe",
    alreadyHaveAccount: "Vous avez déjà un compte ?", dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire", fillAllFields: "Remplissez tous les champs", passwordMin6: "Le mot de passe doit contenir au moins 6 caractères",
    chooseUsername: "Choisissez un nom d'utilisateur", usernameRequired: "Le nom d'utilisateur est obligatoire", usernameMin3: "Le nom d'utilisateur doit contenir au moins 3 caractères",
    usernameTaken: "Ce nom d'utilisateur est déjà pris", usernameAvailable: "Nom d'utilisateur disponible !",
    emailInUse: "Cet e-mail est déjà enregistré.", switchToLogin: "Passer à la Connexion",
    invalidEmail: "Veuillez entrer une adresse e-mail valide",
    backToWatchlists: "Retour aux Listes", about: "À propos", technicalAnalysis: "Analyse Technique", recentNews: "Actualités Récentes",
    notFinancialAdvice: "Pas un conseil financier",
    disclaimerText: "L'analyse IA est uniquement à titre informatif. Consultez toujours des professionnels financiers qualifiés avant de prendre des décisions d'investissement.",
    deleteThread: "Supprimer le sujet", deleteComment: "Supprimer le commentaire",
    notifications: "Notifications", markAllRead: "Tout marquer lu", noNotifications: "Aucune nouvelle notification",
    imageAttached: "Image jointe", uploadImage: "Télécharger une image",
  },
  pt: {
    dashboard: "Painel", aiChat: "Chat IA", quiz: "Quiz", forum: "Fórum", watchlists: "Listas", settings: "Configurações",
    marketIntelligence: "Inteligência de Mercado", aiCuratedAnalysis: "Análise com IA, pontuações de confiança e dados ao vivo",
    analyzeLink: "Analisar Link", analyze: "Analisar", analyzing: "Analisando...",
    pasteUrl: "Cole qualquer URL de artigo financeiro. A IA fornecerá uma pontuação de confiança (1-10), resumo e detecção de viés.",
    trustScore: "Pontuação de Confiança", smartSummary: "Resumo Inteligente", biasDetection: "Detecção de Viés",
    stockHeatmap: "Mapa de Calor S&P 500",
    marketNewsFeed: "Feed de Notícias do Mercado", autoRefresh: "Atualiza automaticamente",
    newsDisclaimer: "Notícias fornecidas pela TradingView. Apenas para fins informativos — não é aconselhamento financeiro.",
    technology: "Tecnologia", finance: "Finanças", healthcare: "Saúde", energy: "Energia", consumer: "Consumo", crypto: "Cripto", etfs: "ETFs",
    trustScoreDesc: "A IA avalia a credibilidade da fonte, experiência do autor e qualidade das citações em uma escala de 1-10",
    smartSummaryDesc: "Obtenha um resumo conciso destacando afirmações chave, dados e conclusões",
    biasDetectionDesc: "Sinaliza linguagem promocional, divulgações ausentes e potenciais conflitos de interesse",
    pasteArticleUrl: "Cole a URL do artigo (ex. https://cnbc.com/article/...)",
    source: "Fonte", summary: "Resumo", potentialBiases: "Vieses Potenciais", strengths: "Pontos Fortes",
    aiFinancialAdvisor: "Consultor Financeiro IA", poweredByAI: "Com IA · Apenas uso educativo",
    history: "Histórico", newChat: "Novo Chat", chatHistory: "Histórico de Chats", noSavedChats: "Nenhum chat salvo.",
    askAnything: "Pergunte sobre finanças, investimentos, mercados...",
    welcomeMessage: "Olá! Sou seu consultor financeiro IA. Pergunte sobre investimentos, mercados ou estratégias de portfólio.",
    suggestETF: "Qual a diferença entre ETFs e fundos mútuos?",
    suggestDiversify: "Como devo diversificar meu portfólio?",
    suggestPE: "Explique o índice P/L e como usá-lo",
    suggestDCA: "O que é dollar-cost averaging?",
    smartForum: "Fórum Inteligente", discussInvestments: "Discuta investimentos com verificação de fatos por IA",
    newThread: "Novo Tópico", createNewThread: "Criar Novo Tópico", threadTitle: "Título do tópico...",
    shareThoughts: "Compartilhe suas ideias...", postThread: "Publicar", cancel: "Cancelar",
    searchThreads: "Buscar tópicos...", factCheck: "Verificar", writeComment: "Escreva um comentário...",
    all: "Todos", general: "Geral", portfolios: "Portfólios", markets: "Mercados", sectors: "Setores",
    noCommentsYet: "Sem comentários ainda. Seja o primeiro!",
    moderationError: "Sua publicação foi sinalizada por conteúdo inapropriado. Revise e tente novamente.",
    tag: "Tag",
    trackStocks: "Acompanhe suas ações e ETFs favoritos", newList: "Nova Lista",
    createNewWatchlist: "Criar Nova Lista", watchlistName: "Nome da lista...", create: "Criar",
    addStock: "Adicionar", searchStocksEtfs: "Buscar ações, ETFs, cripto...", noStocksYet: "Sem ações ainda. Adicione algumas!",
    noWatchlistsYet: "Sem Listas Ainda", createFirstWatchlist: "Crie sua primeira lista para começar.",
    createWatchlist: "Criar Lista", items: "itens",
    startTypingSearch: "Digite para buscar...", noResults: "Nenhum resultado encontrado",
    riskTolerance: "Tolerância ao Risco", riskToleranceSub: "Quão confortável você está com a volatilidade do mercado?",
    conservative: "Conservador", conservativeDesc: "Prefere estabilidade e preservação do capital",
    moderate: "Moderado", moderateDesc: "Crescimento equilibrado com risco gerenciado",
    aggressive: "Agressivo", aggressiveDesc: "Crescimento máximo, maior volatilidade",
    investmentTimeframe: "Prazo de Investimento", investmentTimeframeSub: "Quando planeja usar esses fundos?",
    shortTerm: "1-3 Anos", shortTermDesc: "Metas de curto prazo",
    mediumTerm: "3-7 Anos", mediumTermDesc: "Planejamento de médio prazo",
    longTerm: "7+ Anos", longTermDesc: "Criação de riqueza de longo prazo",
    profitGoals: "Metas de Lucro", profitGoalsSub: "Qual retorno anual você busca?",
    steadyIncome: "5% / ano", steadyIncomeDesc: "Renda estável",
    growthOriented: "10% / ano", growthOrientedDesc: "Orientado ao crescimento",
    aggressiveGrowth: "20%+ / ano", aggressiveGrowthDesc: "Crescimento agressivo",
    investmentExperience: "Experiência em Investimento", investmentExperienceSub: "Como você descreveria sua experiência?",
    beginner: "Iniciante", beginnerDesc: "Novo em investimentos",
    intermediate: "Intermediário", intermediateDesc: "Alguma experiência",
    advanced: "Avançado", advancedDesc: "Investidor experiente",
    sectorInterests: "Interesses por Setor", sectorInterestsSub: "Selecione os setores que te interessam (opcional)",
    technology: "Tecnologia", healthcare: "Saúde", finance: "Finanças", energy: "Energia", consumer: "Consumo", industrial: "Industrial",
    step: "Passo", of: "de", back: "Voltar", continue: "Continuar", generatePortfolio: "Gerar Portfólio",
    yourPersonalizedPortfolio: "Seu Portfólio Personalizado", recommendedAllocations: "Alocações Recomendadas",
    bearCase: "Caso Pessimista", baseCase: "Caso Base", bullCase: "Caso Otimista", fiveYearReturn: "Retorno em 5 anos",
    expectedReturn: "Retorno Esperado", riskLevel: "Nível de Risco", retakeQuiz: "Refazer Quiz", buildThisPortfolio: "Criar Este Portfólio",
    profile: "Perfil", displayName: "Nome de exibição", changesSaveAuto: "Alterações salvas automaticamente",
    email: "E-mail", emailCannotChange: "O e-mail não pode ser alterado", username: "Usuário",
    anonymousMode: "Modo Anônimo", hideNameAvatar: "Ocultar seu nome e avatar nas publicações do fórum",
    appearAs: "Você aparecerá como", anonymousTrader: "Trader Anônimo",
    language: "Idioma", selectLanguage: "Escolha seu idioma preferido",
    logOut: "Sair", uploadPhoto: "Enviar Foto", avatarRecommendation: "200×200px recomendado. JPG, PNG",
    createAccount: "Criar Conta", logIn: "Entrar", emailAddress: "Endereço de e-mail", password: "Senha",
    alreadyHaveAccount: "Já tem uma conta?", dontHaveAccount: "Não tem uma conta?",
    signUp: "Cadastrar-se", fillAllFields: "Preencha todos os campos", passwordMin6: "A senha deve ter pelo menos 6 caracteres",
    chooseUsername: "Escolha um nome de usuário", usernameRequired: "O nome de usuário é obrigatório", usernameMin3: "O nome de usuário deve ter pelo menos 3 caracteres",
    usernameTaken: "Este nome de usuário já está em uso", usernameAvailable: "Nome de usuário disponível!",
    emailInUse: "Este e-mail já está registrado.", switchToLogin: "Ir para Entrar",
    invalidEmail: "Por favor insira um endereço de e-mail válido",
    backToWatchlists: "Voltar às Listas", about: "Sobre", technicalAnalysis: "Análise Técnica", recentNews: "Notícias Recentes",
    notFinancialAdvice: "Não é aconselhamento financeiro",
    disclaimerText: "A análise com IA é apenas informativa. Sempre consulte profissionais financeiros qualificados antes de tomar decisões de investimento.",
    deleteThread: "Excluir tópico", deleteComment: "Excluir comentário",
    notifications: "Notificações", markAllRead: "Marcar tudo lido", noNotifications: "Sem novas notificações",
    imageAttached: "Imagem anexada", uploadImage: "Enviar imagem",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  pt: "Português",
};

type LanguageState = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageNames: Record<Language, string>;
};

const LanguageContext = createContext<LanguageState | null>(null);

export const LanguageProvider = ({ children, initialLanguage = "en" }: { children: ReactNode; initialLanguage?: Language }) => {
  const [language, setLanguage] = useState<Language>(initialLanguage);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
