import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "fr" | "pt" | "de" | "it";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    home: "Home", dashboard: "Dashboard", aiChat: "AI Chat", quiz: "Quiz", forum: "Media Pulse", watchlists: "Watchlists", settings: "Settings", news: "News", articleAnalyzer: "News", new: "NEW",
    // Landing
    landingBanner: "Limited time: Plus 40% OFF (€8.99) · Pro 36% OFF (€15.99)",
    heroBadge: "AI-Powered Bias Shield",
    heroTitleA: "Stop Trading on", heroTitleB: "Biased News.",
    heroSubtitle: "The first AI-powered shield for retail investors. Get instant Trust Scores, Bias Detection, and hidden insights on any financial article.",
    heroPlaceholder: "Paste a CNBC, Seeking Alpha, or Motley Fool link here to reveal the truth...",
    heroAnalyze: "Analyze",
    heroOr: "or",
    heroCreate: "Create Free Account",
    valueCardsTitle: "Three reasons traders are switching to PortAI",
    valueBiasTitle: "Bias Detection",
    valueBiasDesc: "Stop being manipulated by promotional language and hidden conflicts of interest.",
    valueFactTitle: "Fact Checking",
    valueFactDesc: "Spot the lies in news articles and forum claims with AI-powered verification.",
    valueGlobalTitle: "Global Coverage",
    valueGlobalDesc: "Full bias analysis available in 6 languages, across 10,000+ global assets.",
    techStackLabel: "Trusted infrastructure",
    supportingFeatures: "Supporting Features",
    supportingFeaturesSub: "Beyond the analyzer — everything else you get for free.",
    // Dashboard
    marketIntelligence: "Market Intelligence", aiCuratedAnalysis: "AI-curated analysis with trust scores and live market data",
    analyzeLink: "Analyze Link", analyze: "Analyze", analyzing: "Analyzing...",
    pasteUrl: "Paste any financial news article URL. AI will provide a trust/bias score (1-10), summary, and bias detection.",
    trustScore: "Trust Score", smartSummary: "Smart Summary", biasDetection: "Bias Detection",
    stockHeatmap: "S&P 500 Stock Heatmap",
    marketNewsFeed: "Market News Feed", autoRefresh: "Auto-refreshes",
    newsDisclaimer: "News sourced from Google News. For informational purposes only — not financial advice.",
    crypto: "Crypto", etfs: "ETFs",
    trustScoreDesc: "AI rates source credibility, author expertise, and citation quality on a 1-10 scale",
    smartSummaryDesc: "Get a concise summary highlighting key claims, data points, and conclusions",
    biasDetectionDesc: "Flags promotional language, missing disclosures, and potential conflicts of interest",
    pasteArticleUrl: "Paste article URL (e.g. https://cnbc.com/article/...)",
    source: "Source",
    summary: "Summary",
    potentialBiases: "Potential Biases",
    strengths: "Strengths",
    // AI Chat
    aiFinancialAdvisor: "AI Financial Advisor", poweredByAI: "Powered by AI · Educational use only",
    history: "History", newChat: "New Chat", chatHistory: "Chat History", noSavedChats: "No saved chats yet.",
    askAnything: "Ask anything about finance, investing, markets...",
    welcomeMessage: "Hello! I'm your AI financial advisor. Ask me anything about investing, markets, or portfolio strategies.",
    suggestETF: "What's the difference between ETFs and mutual funds?",
    suggestDiversify: "How should I diversify my portfolio?",
    suggestPE: "Explain P/E ratio and how to use it",
    suggestDCA: "What is dollar-cost averaging?",
    // Forum
    smartForum: "Smart Forum", discussInvestments: "Discuss investments with AI-powered fact-checking",
    newThread: "New Thread", createNewThread: "Create New Thread", threadTitle: "Thread title...",
    shareThoughts: "Share your thoughts...", postThread: "Post Thread", cancel: "Cancel",
    searchThreads: "Search threads...", factCheck: "Fact Check", writeComment: "Write a comment...",
    all: "All", general: "General", portfolios: "Portfolios", markets: "Markets", sectors: "Sectors",
    noCommentsYet: "No comments yet. Be the first!",
    moderationError: "Your post was flagged for inappropriate content. Please revise and try again.",
    tag: "Tag",
    // Watchlists
    trackStocks: "Track your favorite stocks and ETFs", newList: "New List",
    createNewWatchlist: "Create New Watchlist", watchlistName: "Watchlist name...", create: "Create",
    addStock: "Add Stock", searchStocksEtfs: "Search stocks, ETFs, crypto...", noStocksYet: "No stocks yet. Add some!",
    noWatchlistsYet: "No Watchlists Yet", createFirstWatchlist: "Create your first watchlist to start tracking stocks.",
    createWatchlist: "Create Watchlist", items: "items",
    startTypingSearch: "Start typing to search...", noResults: "No results found",
    // Quiz
    riskTolerance: "Risk Tolerance", riskToleranceSub: "How comfortable are you with market volatility?",
    conservative: "Conservative", conservativeDesc: "Prefer stability and capital preservation",
    moderate: "Moderate", moderateDesc: "Balanced growth with managed risk",
    aggressive: "Aggressive", aggressiveDesc: "Maximum growth, higher volatility",
    investmentTimeframe: "Investment Timeframe", investmentTimeframeSub: "When do you plan to use these funds?",
    shortTerm: "1-3 Years", shortTermDesc: "Short-term goals",
    mediumTerm: "3-7 Years", mediumTermDesc: "Medium-term planning",
    longTerm: "7+ Years", longTermDesc: "Long-term wealth building",
    profitGoals: "Profit Goals", profitGoalsSub: "What annual return are you targeting?",
    steadyIncome: "5% / year", steadyIncomeDesc: "Steady income",
    growthOriented: "10% / year", growthOrientedDesc: "Growth-oriented",
    aggressiveGrowth: "20%+ / year", aggressiveGrowthDesc: "Aggressive growth",
    investmentExperience: "Investment Experience", investmentExperienceSub: "How would you describe your investing background?",
    beginner: "Beginner", beginnerDesc: "New to investing",
    intermediate: "Intermediate", intermediateDesc: "Some experience",
    advanced: "Advanced", advancedDesc: "Experienced investor",
    sectorInterests: "Sector Interests", sectorInterestsSub: "Select sectors you're interested in (optional)",
    technology: "Technology", healthcare: "Healthcare", finance: "Finance", energy: "Energy", consumer: "Consumer", industrial: "Industrial",
    step: "Step", of: "of", back: "Back", continue: "Continue", generatePortfolio: "Generate Portfolio",
    yourPersonalizedPortfolio: "Your Personalized Portfolio", recommendedAllocations: "Recommended Allocations",
    bearCase: "Bear Case", baseCase: "Base Case", bullCase: "Bull Case", fiveYearReturn: "5-year return",
    expectedReturn: "Expected Return", riskLevel: "Risk Level", retakeQuiz: "Retake Quiz", buildThisPortfolio: "Build This Portfolio",
    // Settings
    profile: "Profile", displayName: "Display Name", changesSaveAuto: "Changes save automatically",
    email: "Email", emailCannotChange: "Email cannot be changed", username: "Username",
    anonymousMode: "Anonymous Mode", hideNameAvatar: "Hide your name and avatar in forum posts",
    appearAs: "You will appear as", anonymousTrader: "Anonymous Trader",
    language: "Language", selectLanguage: "Choose your preferred language",
    logOut: "Log Out", uploadPhoto: "Upload Photo", avatarRecommendation: "200×200px recommended. JPG, PNG",
    // Auth
    createAccount: "Create Account", logIn: "Log In", emailAddress: "Email address", password: "Password",
    alreadyHaveAccount: "Already have an account?", dontHaveAccount: "Don't have an account?",
    signUp: "Sign up", fillAllFields: "Please fill in all fields", passwordMin6: "Password must be at least 6 characters",
    chooseUsername: "Choose a username", usernameRequired: "Username is required", usernameMin3: "Username must be at least 3 characters",
    usernameTaken: "This username is already taken", usernameAvailable: "Username is available!",
    emailInUse: "This email is already registered.", switchToLogin: "Switch to Log In",
    invalidEmail: "Please enter a valid email address",
    // Stock Detail
    backToWatchlists: "Back to Watchlists", about: "About", technicalAnalysis: "Technical Analysis", recentNews: "Recent News",
    // Disclaimer
    notFinancialAdvice: "Not financial advice",
    disclaimerText: "AI analysis is for informational purposes only. Always consult qualified financial professionals before making investment decisions.",
    // Misc
    deleteThread: "Delete thread", deleteComment: "Delete comment",
    notifications: "Notifications", markAllRead: "Mark all read", noNotifications: "No new notifications",
    imageAttached: "Image attached", uploadImage: "Upload image",
    // Dashboard extras
    unlimited: "Unlimited", analysesRemainingToday: "analyses remaining today", noAnalysesRemainingToday: "No analyses remaining today",
    welcomePro: "Welcome to Pro! 🎉 All features are now unlocked.",
    analysisLimitTitle: "Analysis Limit Reached", analysisLimitDesc: "You've used all your free analyses today. Upgrade to Pro for unlimited analyses.",
    freeAnalysisUsedSingle: "You've used your free analysis for today.", freeAnalysesUsedMulti: "You've used all your free analyses for today.",
    quotaResets: "Your quota resets at midnight, or upgrade to Pro for unlimited analyses.",
    upgradeToPro: "Upgrade to Pro", clearLink: "Clear link", share: "Share", shareToX: "Share to X",
    proDeepDive: "Pro-Level Deep Dive",
    stakeholderMotives: "Stakeholder Motives", stakeholderMotivesDesc: "Identifies who benefits from this narrative — institutional positioning, recent insider trades, and analyst incentives.",
    omittedDataPoints: "Omitted Data Points", omittedDataPointsDesc: "Surfaces material context the article skips: contradicting filings, regulatory headlines, and historical baselines.",
    sentimentDivergence: "Sentiment Divergence", sentimentDivergenceDesc: "Compares the article's tone to social, options-flow, and peer-coverage signals to flag manufactured consensus.",
    unlockDeepDive: "Unlock Deep Dive with Pro",
    chooseMarket: "Choose a market", switchHeatmap: "Switch the heatmap to view a different global index.", active: "Active",
    notArticleDefault: "The link you provided doesn't appear to be a news article. Please paste a direct link to a written article.",
    upgradeYourPlan: "Upgrade your plan",
    upgradeChoose: "Choose Plus for the essentials, or Pro for the full experience.",
    plusEssentials: "Essentials for serious investors",
    plusFeatPlan: "Full investor quiz results & portfolio plan",
    plusFeatChat: "Unlimited AI chat & image analysis",
    plusFeatWatch: "Unlimited watchlists & stocks",
    plusFeatCompare: "Asset comparison charts (up to 12 simultaneously)",
    plusFeatHeatmaps: "Live sentiment heatmaps",
    plusFeatDeepDive: "AI Deep Dive (Hidden Angles)",
    plusFeatAlerts: "Custom price alerts",
    proSubtitle: "Everything in Plus, and more",
    proFeatEverything: "Everything in Plus",
    proFeatAnalyses: "Unlimited article & link analyses",
    proFeatFactCheck: "AI Fact Check on market claims",
    proFeatInstitutional: "Deep-Dive institutional analysis",
    proFeatRealtime: "Real-time bias alerts for your portfolio",
    proFeatPriority: "Priority AI speed (high-compute models)",
    bestValue: "Best value",
    upgradeToPlus: "Upgrade to Plus",
    maybeLater: "Maybe Later",
    off: "OFF",
    priceAlert: "Price Alert",
    priceAlertsFor: "Price Alerts for",
    signInForAlertsBody: "Please sign in to set price alerts.",
    proFeatureTitle: "Pro Feature",
    proFeatureBody: "Price alerts are available exclusively to Pro members. Upgrade to get notified the moment any asset hits your target price.",
    currentPriceLabel: "Current price",
    targetPriceLabel: "Target price ($)",
    targetPricePh: "e.g. 250.00",
    risesAbove: "Rises above",
    fallsBelow: "Falls below",
    setAlert: "Set Alert",
    settingDots: "Setting...",
    activeAlerts: "Active Alerts",
    loadingDots: "Loading...",
    noAlertsYet: "No alerts set yet.",
    alertTriggered: "Triggered",
    deleteAlertLabel: "Delete alert",
    alertsCheckNote: "Alerts are checked roughly every 5 minutes during market activity.",
    signInForAlertsToast: "Please sign in to set price alerts",
    alertsProToast: "Price alerts are a Pro feature. Upgrade to unlock.",
    enterValidPrice: "Enter a valid price greater than 0",
    alertCreateFailed: "Failed to create alert",
    alertRemovedToast: "Alert removed",
    setPriceAlert: "Set Price Alert",
    tourWelcomeTitle: "Welcome to PortAI 👋",
    tourWelcomeText: "Your AI shield against biased financial news. Let's show you around in 60 seconds.",
    tourStart: "Start Tour",
    tourNewsTitle: "News — Your Command Center",
    tourNewsText: "This is where you live. Browse curated financial news and paste any article URL to get an instant AI Trust Score, bias detection and smart summary.",
    tourAnalyzeTitle: "Detect Bias in Any Article",
    tourAnalyzeText: "Paste a financial article URL here. Our AI scores its trustworthiness, summarizes it and flags hidden agendas — in seconds.",
    tourForumTitle: "Live Media Bias Pulse",
    tourForumText: "See what the community is analyzing right now. Trending articles, red flags and hidden angles — all AI-validated.",
    tourChatTitle: "Your Personal AI Advisor",
    tourChatText: "Ask anything about stocks, ETFs, portfolio strategy or market trends. Available 24/7.",
    tourWatchTitle: "Track Your Stocks",
    tourWatchText: "Build custom watchlists for 10000+ stocks, ETFs and crypto with live prices and charts.",
    tourQuizTitle: "Find Your Investor Profile",
    tourQuizText: "5 quick questions and you'll get a personalized investor profile with stock picks tailored to your goals.",
    tourDoneTitle: "You're all set! 🚀",
    tourDoneText: "Start by pasting an article link to see the AI Trust Score in action.",
    tourGoToNews: "Go to News",
    tourSkip: "Skip Tour",
    tourFinish: "Finish",
    tourNext: "Next",
    cookieTitle: "We use cookies",
    cookieBody: "We use essential cookies to keep the platform running and optional cookies to improve your experience. You can customize your preferences below. Read our",
    privacyPolicyLink: "Privacy Policy",
    forDetails: "for details.",
    managePrefs: "Manage preferences",
    cookieEssential: "Essential",
    cookieEssentialDesc: "Required for the platform to function",
    cookieAnalytics: "Analytics",
    cookieAnalyticsDesc: "Help us understand how you use the platform",
    cookieFunctional: "Functional",
    cookieFunctionalDesc: "Remember your preferences and settings",
    savePrefs: "Save Preferences",
    acceptAll: "Accept All",
    rejectAll: "Reject All",
  },
  es: {
    home: "Inicio", dashboard: "Panel", aiChat: "Chat IA", quiz: "Cuestionario", forum: "Pulso Media", watchlists: "Listas", settings: "Ajustes", news: "Noticias", articleAnalyzer: "Noticias", new: "NUEVO",
    // Landing
    landingBanner: "Tiempo limitado: Plus 40% OFF (€8,99) · Pro 36% OFF (€15,99)",
    heroBadge: "Escudo IA contra el sesgo",
    heroTitleA: "Deja de operar con", heroTitleB: "noticias sesgadas.",
    heroSubtitle: "El primer escudo con IA para inversores minoristas. Obtén Puntuaciones de Confianza, detección de sesgo e información oculta de cualquier artículo financiero.",
    heroPlaceholder: "Pega un enlace de CNBC, Seeking Alpha o Motley Fool para descubrir la verdad...",
    heroAnalyze: "Analizar",
    heroOr: "o",
    heroCreate: "Crear cuenta gratis",
    valueCardsTitle: "Tres razones por las que los traders eligen PortAI",
    valueBiasTitle: "Detección de Sesgo",
    valueBiasDesc: "Deja de ser manipulado por lenguaje promocional y conflictos de interés ocultos.",
    valueFactTitle: "Verificación de Hechos",
    valueFactDesc: "Detecta mentiras en noticias y publicaciones con verificación impulsada por IA.",
    valueGlobalTitle: "Cobertura Global",
    valueGlobalDesc: "Análisis de sesgo en 6 idiomas y más de 10.000 activos globales.",
    techStackLabel: "Infraestructura confiable",
    supportingFeatures: "Funciones Complementarias",
    supportingFeaturesSub: "Más allá del analizador, todo lo demás incluido gratis.",
    marketIntelligence: "Inteligencia de Mercado", aiCuratedAnalysis: "Análisis con IA, puntuaciones de confianza y datos en vivo",
    analyzeLink: "Analizar Enlace", analyze: "Analizar", analyzing: "Analizando...",
    pasteUrl: "Pega cualquier URL de artículo financiero. La IA proporcionará una puntuación de confianza (1-10), resumen y detección de sesgo.",
    trustScore: "Puntuación de Confianza", smartSummary: "Resumen Inteligente", biasDetection: "Detección de Sesgo",
    stockHeatmap: "Mapa de Calor S&P 500",
    marketNewsFeed: "Noticias del Mercado", autoRefresh: "Se actualiza automáticamente",
    newsDisclaimer: "Noticias de Google News. Solo con fines informativos, no es asesoramiento financiero.",
    crypto: "Cripto", etfs: "ETFs",
    trustScoreDesc: "La IA califica la credibilidad de la fuente, experiencia del autor y calidad de citas en una escala de 1-10",
    smartSummaryDesc: "Obtén un resumen conciso destacando afirmaciones clave, datos y conclusiones",
    biasDetectionDesc: "Señala lenguaje promocional, divulgaciones faltantes y posibles conflictos de interés",
    pasteArticleUrl: "Pega la URL del artículo (ej. https://cnbc.com/article/...)",
    source: "Fuente", summary: "Resumen", potentialBiases: "Sesgos Potenciales", strengths: "Fortalezas",
    aiFinancialAdvisor: "Asesor Financiero IA", poweredByAI: "Con IA · Solo uso educativo",
    history: "Historial", newChat: "Nuevo Chat", chatHistory: "Historial de Chats", noSavedChats: "Sin chats guardados.",
    askAnything: "Pregunta sobre finanzas, inversiones, mercados...",
    welcomeMessage: "¡Hola! Soy tu asesor financiero IA. Pregúntame sobre inversiones, mercados o estrategias de portafolio.",
    suggestETF: "¿Cuál es la diferencia entre ETFs y fondos mutuos?",
    suggestDiversify: "¿Cómo debo diversificar mi portafolio?",
    suggestPE: "Explica el ratio P/E y cómo usarlo",
    suggestDCA: "¿Qué es el promedio de costo en dólares?",
    smartForum: "Foro Inteligente", discussInvestments: "Discute inversiones con verificación de hechos por IA",
    newThread: "Nuevo Tema", createNewThread: "Crear Nuevo Tema", threadTitle: "Título del tema...",
    shareThoughts: "Comparte tus ideas...", postThread: "Publicar", cancel: "Cancelar",
    searchThreads: "Buscar temas...", factCheck: "Verificar", writeComment: "Escribe un comentario...",
    all: "Todos", general: "General", portfolios: "Portafolios", markets: "Mercados", sectors: "Sectores",
    noCommentsYet: "Sin comentarios aún. ¡Sé el primero!",
    moderationError: "Tu publicación fue marcada por contenido inapropiado. Revisa e intenta de nuevo.",
    tag: "Etiqueta",
    trackStocks: "Sigue tus acciones y ETFs favoritos", newList: "Nueva Lista",
    createNewWatchlist: "Crear Nueva Lista", watchlistName: "Nombre de la lista...", create: "Crear",
    addStock: "Agregar", searchStocksEtfs: "Buscar acciones, ETFs, cripto...", noStocksYet: "Sin acciones aún. ¡Agrega algunas!",
    noWatchlistsYet: "Sin Listas Aún", createFirstWatchlist: "Crea tu primera lista para empezar.",
    createWatchlist: "Crear Lista", items: "elementos",
    startTypingSearch: "Escribe para buscar...", noResults: "Sin resultados",
    riskTolerance: "Tolerancia al Riesgo", riskToleranceSub: "¿Qué tan cómodo estás con la volatilidad del mercado?",
    conservative: "Conservador", conservativeDesc: "Prefiere estabilidad y preservación del capital",
    moderate: "Moderado", moderateDesc: "Crecimiento equilibrado con riesgo gestionado",
    aggressive: "Agresivo", aggressiveDesc: "Máximo crecimiento, mayor volatilidad",
    investmentTimeframe: "Plazo de Inversión", investmentTimeframeSub: "¿Cuándo planeas usar estos fondos?",
    shortTerm: "1-3 Años", shortTermDesc: "Metas a corto plazo",
    mediumTerm: "3-7 Años", mediumTermDesc: "Planificación a mediano plazo",
    longTerm: "7+ Años", longTermDesc: "Creación de riqueza a largo plazo",
    profitGoals: "Metas de Ganancia", profitGoalsSub: "¿Qué rendimiento anual buscas?",
    steadyIncome: "5% / año", steadyIncomeDesc: "Ingreso estable",
    growthOriented: "10% / año", growthOrientedDesc: "Orientado al crecimiento",
    aggressiveGrowth: "20%+ / año", aggressiveGrowthDesc: "Crecimiento agresivo",
    investmentExperience: "Experiencia en Inversión", investmentExperienceSub: "¿Cómo describirías tu experiencia inversora?",
    beginner: "Principiante", beginnerDesc: "Nuevo en inversiones",
    intermediate: "Intermedio", intermediateDesc: "Algo de experiencia",
    advanced: "Avanzado", advancedDesc: "Inversor experimentado",
    sectorInterests: "Intereses por Sector", sectorInterestsSub: "Selecciona los sectores que te interesan (opcional)",
    technology: "Tecnología", healthcare: "Salud", finance: "Finanzas", energy: "Energía", consumer: "Consumo", industrial: "Industrial",
    step: "Paso", of: "de", back: "Atrás", continue: "Continuar", generatePortfolio: "Generar Portafolio",
    yourPersonalizedPortfolio: "Tu Portafolio Personalizado", recommendedAllocations: "Asignaciones Recomendadas",
    bearCase: "Caso Pesimista", baseCase: "Caso Base", bullCase: "Caso Optimista", fiveYearReturn: "Retorno a 5 años",
    expectedReturn: "Retorno Esperado", riskLevel: "Nivel de Riesgo", retakeQuiz: "Reiniciar Quiz", buildThisPortfolio: "Crear Este Portafolio",
    profile: "Perfil", displayName: "Nombre", changesSaveAuto: "Los cambios se guardan automáticamente",
    email: "Correo", emailCannotChange: "El correo no se puede cambiar", username: "Usuario",
    anonymousMode: "Modo Anónimo", hideNameAvatar: "Oculta tu nombre y avatar en publicaciones del foro",
    appearAs: "Aparecerás como", anonymousTrader: "Trader Anónimo",
    language: "Idioma", selectLanguage: "Elige tu idioma preferido",
    logOut: "Cerrar Sesión", uploadPhoto: "Subir Foto", avatarRecommendation: "200×200px recomendado. JPG, PNG",
    createAccount: "Crear Cuenta", logIn: "Iniciar Sesión", emailAddress: "Correo electrónico", password: "Contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?", dontHaveAccount: "¿No tienes una cuenta?",
    signUp: "Regístrate", fillAllFields: "Completa todos los campos", passwordMin6: "La contraseña debe tener al menos 6 caracteres",
    chooseUsername: "Elige un nombre de usuario", usernameRequired: "El nombre de usuario es obligatorio", usernameMin3: "El nombre de usuario debe tener al menos 3 caracteres",
    usernameTaken: "Este nombre de usuario ya está en uso", usernameAvailable: "¡Nombre de usuario disponible!",
    emailInUse: "Este correo ya está registrado.", switchToLogin: "Ir a Iniciar Sesión",
    invalidEmail: "Por favor ingresa un correo electrónico válido",
    backToWatchlists: "Volver a Listas", about: "Acerca de", technicalAnalysis: "Análisis Técnico", recentNews: "Noticias Recientes",
    notFinancialAdvice: "No es asesoramiento financiero",
    disclaimerText: "El análisis con IA es solo informativo. Siempre consulta a profesionales financieros calificados antes de tomar decisiones de inversión.",
    deleteThread: "Eliminar tema", deleteComment: "Eliminar comentario",
    notifications: "Notificaciones", markAllRead: "Marcar todo leído", noNotifications: "Sin notificaciones nuevas",
    imageAttached: "Imagen adjunta", uploadImage: "Subir imagen",
    unlimited: "Ilimitado", analysesRemainingToday: "análisis restantes hoy", noAnalysesRemainingToday: "Sin análisis restantes hoy",
    welcomePro: "¡Bienvenido a Pro! 🎉 Todas las funciones desbloqueadas.",
    analysisLimitTitle: "Límite de análisis alcanzado", analysisLimitDesc: "Has usado todos tus análisis gratuitos de hoy. Actualiza a Pro para análisis ilimitados.",
    freeAnalysisUsedSingle: "Has usado tu análisis gratuito de hoy.", freeAnalysesUsedMulti: "Has usado todos tus análisis gratuitos de hoy.",
    quotaResets: "Tu cuota se reinicia a medianoche, o actualiza a Pro para análisis ilimitados.",
    upgradeToPro: "Actualizar a Pro", clearLink: "Borrar enlace", share: "Compartir", shareToX: "Compartir en X",
    proDeepDive: "Análisis Profundo Pro",
    stakeholderMotives: "Motivos de los implicados", stakeholderMotivesDesc: "Identifica quién se beneficia de esta narrativa: posicionamiento institucional, operaciones internas recientes e incentivos de analistas.",
    omittedDataPoints: "Datos omitidos", omittedDataPointsDesc: "Revela el contexto que el artículo omite: presentaciones contradictorias, titulares regulatorios y referencias históricas.",
    sentimentDivergence: "Divergencia de sentimiento", sentimentDivergenceDesc: "Compara el tono del artículo con señales sociales, flujo de opciones y cobertura de pares para detectar consenso fabricado.",
    unlockDeepDive: "Desbloquea el Análisis Profundo con Pro",
    chooseMarket: "Elige un mercado", switchHeatmap: "Cambia el mapa de calor para ver otro índice global.", active: "Activo",
    notArticleDefault: "El enlace que proporcionaste no parece ser un artículo de noticias. Por favor pega un enlace directo a un artículo escrito.",
    upgradeYourPlan: "Mejora tu plan",
    upgradeChoose: "Elige Plus para lo esencial, o Pro para la experiencia completa.",
    plusEssentials: "Lo esencial para inversores serios",
    plusFeatPlan: "Resultados completos del cuestionario y plan de cartera",
    plusFeatChat: "Chat IA y análisis de imágenes ilimitados",
    plusFeatWatch: "Listas y acciones ilimitadas",
    plusFeatCompare: "Comparación de activos (hasta 12 simultáneos)",
    plusFeatHeatmaps: "Mapas de calor de sentimiento en vivo",
    plusFeatDeepDive: "Análisis Profundo IA (Ángulos Ocultos)",
    plusFeatAlerts: "Alertas de precio personalizadas",
    proSubtitle: "Todo lo de Plus, y más",
    proFeatEverything: "Todo lo de Plus",
    proFeatAnalyses: "Análisis ilimitados de artículos y enlaces",
    proFeatFactCheck: "Verificación IA de afirmaciones de mercado",
    proFeatInstitutional: "Análisis institucional Deep-Dive",
    proFeatRealtime: "Alertas de sesgo en tiempo real para tu cartera",
    proFeatPriority: "Velocidad IA prioritaria (modelos de alta computación)",
    bestValue: "Mejor valor",
    upgradeToPlus: "Mejorar a Plus",
    maybeLater: "Quizás después",
    off: "DTO",
    priceAlert: "Alerta de Precio",
    priceAlertsFor: "Alertas de precio para",
    signInForAlertsBody: "Inicia sesión para configurar alertas de precio.",
    proFeatureTitle: "Función Pro",
    proFeatureBody: "Las alertas de precio están disponibles exclusivamente para miembros Pro. Mejora para recibir notificación cuando un activo alcance tu precio objetivo.",
    currentPriceLabel: "Precio actual",
    targetPriceLabel: "Precio objetivo ($)",
    targetPricePh: "ej. 250,00",
    risesAbove: "Sube por encima",
    fallsBelow: "Cae por debajo",
    setAlert: "Crear Alerta",
    settingDots: "Configurando...",
    activeAlerts: "Alertas Activas",
    loadingDots: "Cargando...",
    noAlertsYet: "Sin alertas aún.",
    alertTriggered: "Activada",
    deleteAlertLabel: "Eliminar alerta",
    alertsCheckNote: "Las alertas se revisan aproximadamente cada 5 minutos durante la actividad del mercado.",
    signInForAlertsToast: "Inicia sesión para configurar alertas",
    alertsProToast: "Las alertas son una función Pro. Mejora para desbloquear.",
    enterValidPrice: "Ingresa un precio válido mayor que 0",
    alertCreateFailed: "No se pudo crear la alerta",
    alertRemovedToast: "Alerta eliminada",
    setPriceAlert: "Crear Alerta de Precio",
    tourWelcomeTitle: "Bienvenido a PortAI 👋",
    tourWelcomeText: "Tu escudo IA contra noticias financieras sesgadas. Te mostramos todo en 60 segundos.",
    tourStart: "Iniciar Tour",
    tourNewsTitle: "Noticias — Tu Centro de Mando",
    tourNewsText: "Aquí vives. Explora noticias financieras curadas y pega cualquier URL para obtener Puntuación de Confianza, detección de sesgo y resumen inteligente al instante.",
    tourAnalyzeTitle: "Detecta Sesgo en Cualquier Artículo",
    tourAnalyzeText: "Pega aquí la URL de un artículo financiero. Nuestra IA puntúa la confianza, lo resume y señala agendas ocultas en segundos.",
    tourForumTitle: "Pulso de Sesgo Mediático en Vivo",
    tourForumText: "Ve qué analiza la comunidad ahora. Artículos en tendencia, alertas y ángulos ocultos — todo validado por IA.",
    tourChatTitle: "Tu Asesor Personal IA",
    tourChatText: "Pregunta sobre acciones, ETFs, estrategia de cartera o tendencias del mercado. Disponible 24/7.",
    tourWatchTitle: "Sigue tus Acciones",
    tourWatchText: "Crea listas personalizadas para más de 10.000 acciones, ETFs y criptos con precios y gráficos en vivo.",
    tourQuizTitle: "Descubre tu Perfil de Inversor",
    tourQuizText: "5 preguntas rápidas y obtendrás un perfil personalizado con selección de activos según tus metas.",
    tourDoneTitle: "¡Todo listo! 🚀",
    tourDoneText: "Empieza pegando un enlace de artículo para ver la Puntuación de Confianza en acción.",
    tourGoToNews: "Ir a Noticias",
    tourSkip: "Saltar Tour",
    tourFinish: "Finalizar",
    tourNext: "Siguiente",
    cookieTitle: "Usamos cookies",
    cookieBody: "Usamos cookies esenciales para que la plataforma funcione y opcionales para mejorar tu experiencia. Puedes personalizar tus preferencias abajo. Lee nuestra",
    privacyPolicyLink: "Política de Privacidad",
    forDetails: "para más detalles.",
    managePrefs: "Gestionar preferencias",
    cookieEssential: "Esenciales",
    cookieEssentialDesc: "Necesarias para que la plataforma funcione",
    cookieAnalytics: "Analíticas",
    cookieAnalyticsDesc: "Nos ayudan a entender cómo usas la plataforma",
    cookieFunctional: "Funcionales",
    cookieFunctionalDesc: "Recuerdan tus preferencias y ajustes",
    savePrefs: "Guardar Preferencias",
    acceptAll: "Aceptar Todas",
    rejectAll: "Rechazar Todas",
  },
  fr: {
    home: "Accueil", dashboard: "Tableau de bord", aiChat: "Chat IA", quiz: "Quiz", forum: "Pulse Média", watchlists: "Listes", settings: "Paramètres", news: "Actualités", articleAnalyzer: "Actualités", new: "NOUVEAU",
    // Landing
    landingBanner: "Durée limitée : Plus -40% (8,99 €) · Pro -36% (15,99 €)",
    heroBadge: "Bouclier IA contre les biais",
    heroTitleA: "Arrêtez de trader sur", heroTitleB: "des infos biaisées.",
    heroSubtitle: "Le premier bouclier IA pour les investisseurs particuliers. Obtenez des Scores de Confiance, une détection des biais et des insights cachés sur tout article financier.",
    heroPlaceholder: "Collez un lien CNBC, Seeking Alpha ou Motley Fool pour révéler la vérité...",
    heroAnalyze: "Analyser",
    heroOr: "ou",
    heroCreate: "Créer un compte gratuit",
    valueCardsTitle: "Trois raisons de passer à PortAI",
    valueBiasTitle: "Détection de Biais",
    valueBiasDesc: "Cessez d'être manipulé par le langage promotionnel et les conflits d'intérêts cachés.",
    valueFactTitle: "Vérification des Faits",
    valueFactDesc: "Repérez les mensonges dans les articles et les forums grâce à l'IA.",
    valueGlobalTitle: "Couverture Mondiale",
    valueGlobalDesc: "Analyse des biais en 6 langues, sur plus de 10 000 actifs mondiaux.",
    techStackLabel: "Infrastructure de confiance",
    supportingFeatures: "Fonctionnalités Complémentaires",
    supportingFeaturesSub: "Au-delà de l'analyseur — tout le reste, gratuitement.",
    marketIntelligence: "Intelligence de Marché", aiCuratedAnalysis: "Analyse IA avec scores de confiance et données en direct",
    analyzeLink: "Analyser le Lien", analyze: "Analyser", analyzing: "Analyse en cours...",
    pasteUrl: "Collez l'URL d'un article financier. L'IA fournira un score de confiance (1-10), un résumé et une détection de biais.",
    trustScore: "Score de Confiance", smartSummary: "Résumé Intelligent", biasDetection: "Détection de Biais",
    stockHeatmap: "Carte Thermique S&P 500",
    marketNewsFeed: "Fil d'Actualités du Marché", autoRefresh: "Mise à jour automatique",
    newsDisclaimer: "Actualités de Google News. À titre informatif uniquement — pas de conseil financier.",
    crypto: "Crypto", etfs: "ETFs",
    trustScoreDesc: "L'IA évalue la crédibilité de la source, l'expertise de l'auteur et la qualité des citations sur une échelle de 1-10",
    smartSummaryDesc: "Obtenez un résumé concis mettant en évidence les affirmations clés, les données et les conclusions",
    biasDetectionDesc: "Signale le langage promotionnel, les divulgations manquantes et les conflits d'intérêts potentiels",
    pasteArticleUrl: "Collez l'URL de l'article (ex. https://cnbc.com/article/...)",
    source: "Source", summary: "Résumé", potentialBiases: "Biais Potentiels", strengths: "Points Forts",
    aiFinancialAdvisor: "Conseiller Financier IA", poweredByAI: "Alimenté par IA · Usage éducatif uniquement",
    history: "Historique", newChat: "Nouveau Chat", chatHistory: "Historique des Chats", noSavedChats: "Aucun chat sauvegardé.",
    askAnything: "Posez vos questions sur la finance, l'investissement...",
    welcomeMessage: "Bonjour ! Je suis votre conseiller financier IA. Posez-moi des questions sur l'investissement, les marchés ou les stratégies de portefeuille.",
    suggestETF: "Quelle est la différence entre les ETF et les fonds communs ?",
    suggestDiversify: "Comment diversifier mon portefeuille ?",
    suggestPE: "Expliquez le ratio P/E et comment l'utiliser",
    suggestDCA: "Qu'est-ce que le dollar-cost averaging ?",
    smartForum: "Forum Intelligent", discussInvestments: "Discutez d'investissements avec vérification IA",
    newThread: "Nouveau Sujet", createNewThread: "Créer un Nouveau Sujet", threadTitle: "Titre du sujet...",
    shareThoughts: "Partagez vos idées...", postThread: "Publier", cancel: "Annuler",
    searchThreads: "Rechercher des sujets...", factCheck: "Vérifier", writeComment: "Écrire un commentaire...",
    all: "Tout", general: "Général", portfolios: "Portefeuilles", markets: "Marchés", sectors: "Secteurs",
    noCommentsYet: "Pas encore de commentaires. Soyez le premier !",
    moderationError: "Votre publication a été signalée pour contenu inapproprié. Veuillez la réviser.",
    tag: "Tag",
    trackStocks: "Suivez vos actions et ETFs favoris", newList: "Nouvelle Liste",
    createNewWatchlist: "Créer une Nouvelle Liste", watchlistName: "Nom de la liste...", create: "Créer",
    addStock: "Ajouter", searchStocksEtfs: "Rechercher actions, ETFs, crypto...", noStocksYet: "Pas encore d'actions. Ajoutez-en !",
    noWatchlistsYet: "Pas de Listes", createFirstWatchlist: "Créez votre première liste pour commencer.",
    createWatchlist: "Créer une Liste", items: "éléments",
    startTypingSearch: "Tapez pour rechercher...", noResults: "Aucun résultat",
    riskTolerance: "Tolérance au Risque", riskToleranceSub: "À quel point êtes-vous à l'aise avec la volatilité ?",
    conservative: "Conservateur", conservativeDesc: "Préfère la stabilité et la préservation du capital",
    moderate: "Modéré", moderateDesc: "Croissance équilibrée avec risque géré",
    aggressive: "Agressif", aggressiveDesc: "Croissance maximale, volatilité plus élevée",
    investmentTimeframe: "Horizon d'Investissement", investmentTimeframeSub: "Quand prévoyez-vous d'utiliser ces fonds ?",
    shortTerm: "1-3 Ans", shortTermDesc: "Objectifs à court terme",
    mediumTerm: "3-7 Ans", mediumTermDesc: "Planification à moyen terme",
    longTerm: "7+ Ans", longTermDesc: "Création de richesse à long terme",
    profitGoals: "Objectifs de Profit", profitGoalsSub: "Quel rendement annuel visez-vous ?",
    steadyIncome: "5% / an", steadyIncomeDesc: "Revenu stable",
    growthOriented: "10% / an", growthOrientedDesc: "Orienté croissance",
    aggressiveGrowth: "20%+ / an", aggressiveGrowthDesc: "Croissance agressive",
    investmentExperience: "Expérience d'Investissement", investmentExperienceSub: "Comment décririez-vous votre expérience ?",
    beginner: "Débutant", beginnerDesc: "Nouveau dans l'investissement",
    intermediate: "Intermédiaire", intermediateDesc: "Un peu d'expérience",
    advanced: "Avancé", advancedDesc: "Investisseur expérimenté",
    sectorInterests: "Intérêts Sectoriels", sectorInterestsSub: "Sélectionnez les secteurs qui vous intéressent (optionnel)",
    technology: "Technologie", healthcare: "Santé", finance: "Finance", energy: "Énergie", consumer: "Consommation", industrial: "Industrie",
    step: "Étape", of: "sur", back: "Retour", continue: "Continuer", generatePortfolio: "Générer le Portefeuille",
    yourPersonalizedPortfolio: "Votre Portefeuille Personnalisé", recommendedAllocations: "Allocations Recommandées",
    bearCase: "Cas Pessimiste", baseCase: "Cas de Base", bullCase: "Cas Optimiste", fiveYearReturn: "Rendement à 5 ans",
    expectedReturn: "Rendement Attendu", riskLevel: "Niveau de Risque", retakeQuiz: "Refaire le Quiz", buildThisPortfolio: "Créer ce Portefeuille",
    profile: "Profil", displayName: "Nom d'affichage", changesSaveAuto: "Les modifications sont enregistrées automatiquement",
    email: "E-mail", emailCannotChange: "L'e-mail ne peut pas être modifié", username: "Nom d'utilisateur",
    anonymousMode: "Mode Anonyme", hideNameAvatar: "Masquer votre nom et avatar dans les publications du forum",
    appearAs: "Vous apparaîtrez comme", anonymousTrader: "Trader Anonyme",
    language: "Langue", selectLanguage: "Choisissez votre langue préférée",
    logOut: "Déconnexion", uploadPhoto: "Télécharger une Photo", avatarRecommendation: "200×200px recommandé. JPG, PNG",
    createAccount: "Créer un Compte", logIn: "Se Connecter", emailAddress: "Adresse e-mail", password: "Mot de passe",
    alreadyHaveAccount: "Vous avez déjà un compte ?", dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire", fillAllFields: "Remplissez tous les champs", passwordMin6: "Le mot de passe doit contenir au moins 6 caractères",
    chooseUsername: "Choisissez un nom d'utilisateur", usernameRequired: "Le nom d'utilisateur est obligatoire", usernameMin3: "Le nom d'utilisateur doit contenir au moins 3 caractères",
    usernameTaken: "Ce nom d'utilisateur est déjà pris", usernameAvailable: "Nom d'utilisateur disponible !",
    emailInUse: "Cet e-mail est déjà enregistré.", switchToLogin: "Passer à la Connexion",
    invalidEmail: "Veuillez entrer une adresse e-mail valide",
    backToWatchlists: "Retour aux Listes", about: "À propos", technicalAnalysis: "Analyse Technique", recentNews: "Actualités Récentes",
    notFinancialAdvice: "Pas un conseil financier",
    disclaimerText: "L'analyse IA est uniquement à titre informatif. Consultez toujours des professionnels financiers qualifiés avant de prendre des décisions d'investissement.",
    deleteThread: "Supprimer le sujet", deleteComment: "Supprimer le commentaire",
    notifications: "Notifications", markAllRead: "Tout marquer lu", noNotifications: "Aucune nouvelle notification",
    imageAttached: "Image jointe", uploadImage: "Télécharger une image",
    unlimited: "Illimité", analysesRemainingToday: "analyses restantes aujourd'hui", noAnalysesRemainingToday: "Aucune analyse restante aujourd'hui",
    welcomePro: "Bienvenue dans Pro ! 🎉 Toutes les fonctionnalités sont débloquées.",
    analysisLimitTitle: "Limite d'analyses atteinte", analysisLimitDesc: "Vous avez utilisé toutes vos analyses gratuites pour aujourd'hui. Passez à Pro pour des analyses illimitées.",
    freeAnalysisUsedSingle: "Vous avez utilisé votre analyse gratuite pour aujourd'hui.", freeAnalysesUsedMulti: "Vous avez utilisé toutes vos analyses gratuites pour aujourd'hui.",
    quotaResets: "Votre quota se réinitialise à minuit, ou passez à Pro pour des analyses illimitées.",
    upgradeToPro: "Passer à Pro", clearLink: "Effacer le lien", share: "Partager", shareToX: "Partager sur X",
    proDeepDive: "Analyse Approfondie Pro",
    stakeholderMotives: "Motivations des parties prenantes", stakeholderMotivesDesc: "Identifie qui bénéficie de ce récit : positionnement institutionnel, opérations d'initiés récentes et incitations des analystes.",
    omittedDataPoints: "Données omises", omittedDataPointsDesc: "Met en lumière le contexte que l'article omet : déclarations contradictoires, actualités réglementaires et références historiques.",
    sentimentDivergence: "Divergence de sentiment", sentimentDivergenceDesc: "Compare le ton de l'article aux signaux sociaux, flux d'options et couverture des pairs pour détecter un consensus fabriqué.",
    unlockDeepDive: "Débloquez l'Analyse Approfondie avec Pro",
    chooseMarket: "Choisir un marché", switchHeatmap: "Changez la carte thermique pour voir un autre indice mondial.", active: "Actif",
    notArticleDefault: "Le lien fourni ne semble pas être un article d'actualité. Veuillez coller un lien direct vers un article écrit.",
    upgradeYourPlan: "Améliorez votre plan",
    upgradeChoose: "Choisissez Plus pour l'essentiel, ou Pro pour l'expérience complète.",
    plusEssentials: "L'essentiel pour les investisseurs sérieux",
    plusFeatPlan: "Résultats complets du quiz et plan de portefeuille",
    plusFeatChat: "Chat IA et analyse d'images illimités",
    plusFeatWatch: "Listes et actions illimitées",
    plusFeatCompare: "Comparaison d'actifs (jusqu'à 12 simultanément)",
    plusFeatHeatmaps: "Cartes thermiques de sentiment en direct",
    plusFeatDeepDive: "Analyse Approfondie IA (Angles Cachés)",
    plusFeatAlerts: "Alertes de prix personnalisées",
    proSubtitle: "Tout Plus, et plus encore",
    proFeatEverything: "Tout Plus",
    proFeatAnalyses: "Analyses illimitées d'articles et de liens",
    proFeatFactCheck: "Vérification IA des affirmations de marché",
    proFeatInstitutional: "Analyse institutionnelle approfondie",
    proFeatRealtime: "Alertes de biais en temps réel pour votre portefeuille",
    proFeatPriority: "Vitesse IA prioritaire (modèles haute performance)",
    bestValue: "Meilleur rapport",
    upgradeToPlus: "Passer à Plus",
    maybeLater: "Plus tard",
    off: "RÉDUC",
    priceAlert: "Alerte de Prix",
    priceAlertsFor: "Alertes de prix pour",
    signInForAlertsBody: "Connectez-vous pour configurer des alertes de prix.",
    proFeatureTitle: "Fonction Pro",
    proFeatureBody: "Les alertes de prix sont réservées aux membres Pro. Passez à Pro pour être notifié dès qu'un actif atteint votre prix cible.",
    currentPriceLabel: "Prix actuel",
    targetPriceLabel: "Prix cible ($)",
    targetPricePh: "ex. 250,00",
    risesAbove: "Monte au-dessus",
    fallsBelow: "Tombe en dessous",
    setAlert: "Créer l'alerte",
    settingDots: "Configuration...",
    activeAlerts: "Alertes Actives",
    loadingDots: "Chargement...",
    noAlertsYet: "Aucune alerte encore.",
    alertTriggered: "Déclenchée",
    deleteAlertLabel: "Supprimer l'alerte",
    alertsCheckNote: "Les alertes sont vérifiées environ toutes les 5 minutes pendant l'activité du marché.",
    signInForAlertsToast: "Connectez-vous pour configurer des alertes",
    alertsProToast: "Les alertes sont une fonction Pro. Passez à Pro pour les débloquer.",
    enterValidPrice: "Saisissez un prix valide supérieur à 0",
    alertCreateFailed: "Échec de la création de l'alerte",
    alertRemovedToast: "Alerte supprimée",
    setPriceAlert: "Créer une Alerte de Prix",
    tourWelcomeTitle: "Bienvenue sur PortAI 👋",
    tourWelcomeText: "Votre bouclier IA contre les news financières biaisées. Visite guidée en 60 secondes.",
    tourStart: "Commencer",
    tourNewsTitle: "Actualités — Votre Centre de Commande",
    tourNewsText: "C'est ici que vous vivez. Parcourez des actualités financières curées et collez une URL pour obtenir un Score de Confiance IA, détection de biais et résumé instantané.",
    tourAnalyzeTitle: "Détectez les Biais dans tout Article",
    tourAnalyzeText: "Collez ici l'URL d'un article financier. Notre IA évalue sa fiabilité, le résume et signale les agendas cachés — en quelques secondes.",
    tourForumTitle: "Pulse Médias en Direct",
    tourForumText: "Voyez ce que la communauté analyse en ce moment. Articles tendance, alertes et angles cachés — tous validés par IA.",
    tourChatTitle: "Votre Conseiller IA Personnel",
    tourChatText: "Posez vos questions sur les actions, ETFs, stratégie de portefeuille ou tendances du marché. Disponible 24/7.",
    tourWatchTitle: "Suivez vos Actions",
    tourWatchText: "Créez des listes personnalisées pour plus de 10 000 actions, ETFs et cryptos avec prix et graphiques en direct.",
    tourQuizTitle: "Trouvez votre Profil d'Investisseur",
    tourQuizText: "5 questions rapides et vous obtiendrez un profil personnalisé avec une sélection d'actifs adaptés à vos objectifs.",
    tourDoneTitle: "Tout est prêt ! 🚀",
    tourDoneText: "Commencez en collant un lien d'article pour voir le Score de Confiance en action.",
    tourGoToNews: "Aller aux Actualités",
    tourSkip: "Passer le Tour",
    tourFinish: "Terminer",
    tourNext: "Suivant",
    cookieTitle: "Nous utilisons des cookies",
    cookieBody: "Nous utilisons des cookies essentiels pour faire fonctionner la plateforme et des cookies optionnels pour améliorer votre expérience. Vous pouvez personnaliser vos préférences ci-dessous. Lisez notre",
    privacyPolicyLink: "Politique de Confidentialité",
    forDetails: "pour plus de détails.",
    managePrefs: "Gérer les préférences",
    cookieEssential: "Essentiels",
    cookieEssentialDesc: "Nécessaires au fonctionnement de la plateforme",
    cookieAnalytics: "Analytiques",
    cookieAnalyticsDesc: "Nous aident à comprendre comment vous utilisez la plateforme",
    cookieFunctional: "Fonctionnels",
    cookieFunctionalDesc: "Mémorisent vos préférences et paramètres",
    savePrefs: "Enregistrer les Préférences",
    acceptAll: "Tout Accepter",
    rejectAll: "Tout Refuser",
  },
  pt: {
    home: "Início", dashboard: "Painel", aiChat: "Chat IA", quiz: "Quiz", forum: "Pulso Media", watchlists: "Listas", settings: "Configurações", news: "Notícias", articleAnalyzer: "Notícias", new: "NOVO",
    // Landing
    landingBanner: "Por tempo limitado: Plus 40% OFF (€8,99) · Pro 36% OFF (€15,99)",
    heroBadge: "Escudo IA contra o viés",
    heroTitleA: "Pare de negociar com", heroTitleB: "notícias enviesadas.",
    heroSubtitle: "O primeiro escudo com IA para investidores de varejo. Obtenha Pontuações de Confiança, detecção de viés e insights ocultos de qualquer artigo financeiro.",
    heroPlaceholder: "Cole um link da CNBC, Seeking Alpha ou Motley Fool para revelar a verdade...",
    heroAnalyze: "Analisar",
    heroOr: "ou",
    heroCreate: "Criar conta grátis",
    valueCardsTitle: "Três motivos para os traders mudarem para o PortAI",
    valueBiasTitle: "Detecção de Viés",
    valueBiasDesc: "Pare de ser manipulado por linguagem promocional e conflitos de interesse ocultos.",
    valueFactTitle: "Verificação de Fatos",
    valueFactDesc: "Identifique mentiras em notícias e fóruns com verificação por IA.",
    valueGlobalTitle: "Cobertura Global",
    valueGlobalDesc: "Análise de viés em 6 idiomas e mais de 10.000 ativos globais.",
    techStackLabel: "Infraestrutura confiável",
    supportingFeatures: "Recursos Complementares",
    supportingFeaturesSub: "Além do analisador — tudo o mais, grátis.",
    marketIntelligence: "Inteligência de Mercado", aiCuratedAnalysis: "Análise com IA, pontuações de confiança e dados ao vivo",
    analyzeLink: "Analisar Link", analyze: "Analisar", analyzing: "Analisando...",
    pasteUrl: "Cole qualquer URL de artigo financeiro. A IA fornecerá uma pontuação de confiança (1-10), resumo e detecção de viés.",
    trustScore: "Pontuação de Confiança", smartSummary: "Resumo Inteligente", biasDetection: "Detecção de Viés",
    stockHeatmap: "Mapa de Calor S&P 500",
    marketNewsFeed: "Feed de Notícias do Mercado", autoRefresh: "Atualiza automaticamente",
    newsDisclaimer: "Notícias do Google News. Apenas para fins informativos — não é aconselhamento financeiro.",
    crypto: "Cripto", etfs: "ETFs",
    trustScoreDesc: "A IA avalia a credibilidade da fonte, experiência do autor e qualidade das citações em uma escala de 1-10",
    smartSummaryDesc: "Obtenha um resumo conciso destacando afirmações chave, dados e conclusões",
    biasDetectionDesc: "Sinaliza linguagem promocional, divulgações ausentes e potenciais conflitos de interesse",
    pasteArticleUrl: "Cole a URL do artigo (ex. https://cnbc.com/article/...)",
    source: "Fonte", summary: "Resumo", potentialBiases: "Vieses Potenciais", strengths: "Pontos Fortes",
    aiFinancialAdvisor: "Consultor Financeiro IA", poweredByAI: "Com IA · Apenas uso educativo",
    history: "Histórico", newChat: "Novo Chat", chatHistory: "Histórico de Chats", noSavedChats: "Nenhum chat salvo.",
    askAnything: "Pergunte sobre finanças, investimentos, mercados...",
    welcomeMessage: "Olá! Sou seu consultor financeiro IA. Pergunte sobre investimentos, mercados ou estratégias de portfólio.",
    suggestETF: "Qual a diferença entre ETFs e fundos mútuos?",
    suggestDiversify: "Como devo diversificar meu portfólio?",
    suggestPE: "Explique o índice P/L e como usá-lo",
    suggestDCA: "O que é dollar-cost averaging?",
    smartForum: "Fórum Inteligente", discussInvestments: "Discuta investimentos com verificação de fatos por IA",
    newThread: "Novo Tópico", createNewThread: "Criar Novo Tópico", threadTitle: "Título do tópico...",
    shareThoughts: "Compartilhe suas ideias...", postThread: "Publicar", cancel: "Cancelar",
    searchThreads: "Buscar tópicos...", factCheck: "Verificar", writeComment: "Escreva um comentário...",
    all: "Todos", general: "Geral", portfolios: "Portfólios", markets: "Mercados", sectors: "Setores",
    noCommentsYet: "Sem comentários ainda. Seja o primeiro!",
    moderationError: "Sua publicação foi sinalizada por conteúdo inapropriado. Revise e tente novamente.",
    tag: "Tag",
    trackStocks: "Acompanhe suas ações e ETFs favoritos", newList: "Nova Lista",
    createNewWatchlist: "Criar Nova Lista", watchlistName: "Nome da lista...", create: "Criar",
    addStock: "Adicionar", searchStocksEtfs: "Buscar ações, ETFs, cripto...", noStocksYet: "Sem ações ainda. Adicione algumas!",
    noWatchlistsYet: "Sem Listas Ainda", createFirstWatchlist: "Crie sua primeira lista para começar.",
    createWatchlist: "Criar Lista", items: "itens",
    startTypingSearch: "Digite para buscar...", noResults: "Nenhum resultado encontrado",
    riskTolerance: "Tolerância ao Risco", riskToleranceSub: "Quão confortável você está com a volatilidade do mercado?",
    conservative: "Conservador", conservativeDesc: "Prefere estabilidade e preservação do capital",
    moderate: "Moderado", moderateDesc: "Crescimento equilibrado com risco gerenciado",
    aggressive: "Agressivo", aggressiveDesc: "Crescimento máximo, maior volatilidade",
    investmentTimeframe: "Prazo de Investimento", investmentTimeframeSub: "Quando planeja usar esses fundos?",
    shortTerm: "1-3 Anos", shortTermDesc: "Metas de curto prazo",
    mediumTerm: "3-7 Anos", mediumTermDesc: "Planejamento de médio prazo",
    longTerm: "7+ Anos", longTermDesc: "Criação de riqueza de longo prazo",
    profitGoals: "Metas de Lucro", profitGoalsSub: "Qual retorno anual você busca?",
    steadyIncome: "5% / ano", steadyIncomeDesc: "Renda estável",
    growthOriented: "10% / ano", growthOrientedDesc: "Orientado ao crescimento",
    aggressiveGrowth: "20%+ / ano", aggressiveGrowthDesc: "Crescimento agressivo",
    investmentExperience: "Experiência em Investimento", investmentExperienceSub: "Como você descreveria sua experiência?",
    beginner: "Iniciante", beginnerDesc: "Novo em investimentos",
    intermediate: "Intermediário", intermediateDesc: "Alguma experiência",
    advanced: "Avançado", advancedDesc: "Investidor experiente",
    sectorInterests: "Interesses por Setor", sectorInterestsSub: "Selecione os setores que te interessam (opcional)",
    technology: "Tecnologia", healthcare: "Saúde", finance: "Finanças", energy: "Energia", consumer: "Consumo", industrial: "Industrial",
    step: "Passo", of: "de", back: "Voltar", continue: "Continuar", generatePortfolio: "Gerar Portfólio",
    yourPersonalizedPortfolio: "Seu Portfólio Personalizado", recommendedAllocations: "Alocações Recomendadas",
    bearCase: "Caso Pessimista", baseCase: "Caso Base", bullCase: "Caso Otimista", fiveYearReturn: "Retorno em 5 anos",
    expectedReturn: "Retorno Esperado", riskLevel: "Nível de Risco", retakeQuiz: "Refazer Quiz", buildThisPortfolio: "Criar Este Portfólio",
    profile: "Perfil", displayName: "Nome de exibição", changesSaveAuto: "Alterações salvas automaticamente",
    email: "E-mail", emailCannotChange: "O e-mail não pode ser alterado", username: "Usuário",
    anonymousMode: "Modo Anônimo", hideNameAvatar: "Ocultar seu nome e avatar nas publicações do fórum",
    appearAs: "Você aparecerá como", anonymousTrader: "Trader Anônimo",
    language: "Idioma", selectLanguage: "Escolha seu idioma preferido",
    logOut: "Sair", uploadPhoto: "Enviar Foto", avatarRecommendation: "200×200px recomendado. JPG, PNG",
    createAccount: "Criar Conta", logIn: "Entrar", emailAddress: "Endereço de e-mail", password: "Senha",
    alreadyHaveAccount: "Já tem uma conta?", dontHaveAccount: "Não tem uma conta?",
    signUp: "Cadastrar-se", fillAllFields: "Preencha todos os campos", passwordMin6: "A senha deve ter pelo menos 6 caracteres",
    chooseUsername: "Escolha um nome de usuário", usernameRequired: "O nome de usuário é obrigatório", usernameMin3: "O nome de usuário deve ter pelo menos 3 caracteres",
    usernameTaken: "Este nome de usuário já está em uso", usernameAvailable: "Nome de usuário disponível!",
    emailInUse: "Este e-mail já está registrado.", switchToLogin: "Ir para Entrar",
    invalidEmail: "Por favor insira um endereço de e-mail válido",
    backToWatchlists: "Voltar às Listas", about: "Sobre", technicalAnalysis: "Análise Técnica", recentNews: "Notícias Recentes",
    notFinancialAdvice: "Não é aconselhamento financeiro",
    disclaimerText: "A análise com IA é apenas informativa. Sempre consulte profissionais financeiros qualificados antes de tomar decisões de investimento.",
    deleteThread: "Excluir tópico", deleteComment: "Excluir comentário",
    notifications: "Notificações", markAllRead: "Marcar tudo lido", noNotifications: "Sem novas notificações",
    imageAttached: "Imagem anexada", uploadImage: "Enviar imagem",
    unlimited: "Ilimitado", analysesRemainingToday: "análises restantes hoje", noAnalysesRemainingToday: "Sem análises restantes hoje",
    welcomePro: "Bem-vindo ao Pro! 🎉 Todos os recursos foram desbloqueados.",
    analysisLimitTitle: "Limite de análises atingido", analysisLimitDesc: "Você usou todas as suas análises gratuitas hoje. Atualize para Pro para análises ilimitadas.",
    freeAnalysisUsedSingle: "Você usou sua análise gratuita de hoje.", freeAnalysesUsedMulti: "Você usou todas as suas análises gratuitas de hoje.",
    quotaResets: "Sua cota é redefinida à meia-noite, ou atualize para Pro para análises ilimitadas.",
    upgradeToPro: "Atualizar para Pro", clearLink: "Limpar link", share: "Compartilhar", shareToX: "Compartilhar no X",
    proDeepDive: "Análise Profunda Pro",
    stakeholderMotives: "Motivações dos envolvidos", stakeholderMotivesDesc: "Identifica quem se beneficia dessa narrativa: posicionamento institucional, negociações internas recentes e incentivos de analistas.",
    omittedDataPoints: "Dados omitidos", omittedDataPointsDesc: "Revela o contexto material que o artigo omite: registros contraditórios, manchetes regulatórias e referências históricas.",
    sentimentDivergence: "Divergência de sentimento", sentimentDivergenceDesc: "Compara o tom do artigo com sinais sociais, fluxo de opções e cobertura de pares para detectar consenso fabricado.",
    unlockDeepDive: "Desbloqueie a Análise Profunda com Pro",
    chooseMarket: "Escolha um mercado", switchHeatmap: "Mude o mapa de calor para ver outro índice global.", active: "Ativo",
    notArticleDefault: "O link fornecido não parece ser um artigo de notícias. Por favor, cole um link direto para um artigo escrito.",
    upgradeYourPlan: "Atualize seu plano",
    upgradeChoose: "Escolha Plus para o essencial, ou Pro para a experiência completa.",
    plusEssentials: "O essencial para investidores sérios",
    plusFeatPlan: "Resultados completos do quiz e plano de portfólio",
    plusFeatChat: "Chat IA e análise de imagens ilimitados",
    plusFeatWatch: "Listas e ações ilimitadas",
    plusFeatCompare: "Comparação de ativos (até 12 simultâneos)",
    plusFeatHeatmaps: "Mapas de calor de sentimento ao vivo",
    plusFeatDeepDive: "Análise Profunda IA (Ângulos Ocultos)",
    plusFeatAlerts: "Alertas de preço personalizados",
    proSubtitle: "Tudo do Plus, e mais",
    proFeatEverything: "Tudo do Plus",
    proFeatAnalyses: "Análises ilimitadas de artigos e links",
    proFeatFactCheck: "Verificação IA de afirmações de mercado",
    proFeatInstitutional: "Análise institucional Deep-Dive",
    proFeatRealtime: "Alertas de viés em tempo real para seu portfólio",
    proFeatPriority: "Velocidade IA prioritária (modelos de alta computação)",
    bestValue: "Melhor valor",
    upgradeToPlus: "Atualizar para Plus",
    maybeLater: "Talvez depois",
    off: "OFF",
    priceAlert: "Alerta de Preço",
    priceAlertsFor: "Alertas de preço para",
    signInForAlertsBody: "Faça login para configurar alertas de preço.",
    proFeatureTitle: "Recurso Pro",
    proFeatureBody: "Os alertas de preço são exclusivos para membros Pro. Atualize para ser notificado quando um ativo atingir seu preço alvo.",
    currentPriceLabel: "Preço atual",
    targetPriceLabel: "Preço alvo ($)",
    targetPricePh: "ex. 250,00",
    risesAbove: "Subir acima",
    fallsBelow: "Cair abaixo",
    setAlert: "Criar Alerta",
    settingDots: "Configurando...",
    activeAlerts: "Alertas Ativos",
    loadingDots: "Carregando...",
    noAlertsYet: "Sem alertas ainda.",
    alertTriggered: "Disparado",
    deleteAlertLabel: "Excluir alerta",
    alertsCheckNote: "Os alertas são verificados aproximadamente a cada 5 minutos durante a atividade do mercado.",
    signInForAlertsToast: "Faça login para configurar alertas",
    alertsProToast: "Alertas são um recurso Pro. Atualize para desbloquear.",
    enterValidPrice: "Digite um preço válido maior que 0",
    alertCreateFailed: "Falha ao criar alerta",
    alertRemovedToast: "Alerta removido",
    setPriceAlert: "Criar Alerta de Preço",
    tourWelcomeTitle: "Bem-vindo ao PortAI 👋",
    tourWelcomeText: "Seu escudo IA contra notícias financeiras enviesadas. Mostramos tudo em 60 segundos.",
    tourStart: "Iniciar Tour",
    tourNewsTitle: "Notícias — Seu Centro de Comando",
    tourNewsText: "É aqui que você vive. Navegue por notícias financeiras curadas e cole qualquer URL para obter Pontuação de Confiança IA, detecção de viés e resumo inteligente instantâneo.",
    tourAnalyzeTitle: "Detecte Viés em Qualquer Artigo",
    tourAnalyzeText: "Cole aqui a URL de um artigo financeiro. Nossa IA pontua a confiabilidade, resume e sinaliza agendas ocultas em segundos.",
    tourForumTitle: "Pulso de Viés da Mídia ao Vivo",
    tourForumText: "Veja o que a comunidade está analisando agora. Artigos em alta, alertas e ângulos ocultos — todos validados por IA.",
    tourChatTitle: "Seu Consultor IA Pessoal",
    tourChatText: "Pergunte sobre ações, ETFs, estratégia de portfólio ou tendências de mercado. Disponível 24/7.",
    tourWatchTitle: "Acompanhe suas Ações",
    tourWatchText: "Crie listas personalizadas para mais de 10.000 ações, ETFs e criptos com preços e gráficos ao vivo.",
    tourQuizTitle: "Descubra seu Perfil de Investidor",
    tourQuizText: "5 perguntas rápidas e você terá um perfil personalizado com seleção de ativos adaptada aos seus objetivos.",
    tourDoneTitle: "Tudo pronto! 🚀",
    tourDoneText: "Comece colando um link de artigo para ver a Pontuação de Confiança em ação.",
    tourGoToNews: "Ir para Notícias",
    tourSkip: "Pular Tour",
    tourFinish: "Concluir",
    tourNext: "Próximo",
    cookieTitle: "Usamos cookies",
    cookieBody: "Usamos cookies essenciais para a plataforma funcionar e cookies opcionais para melhorar sua experiência. Você pode personalizar suas preferências abaixo. Leia nossa",
    privacyPolicyLink: "Política de Privacidade",
    forDetails: "para detalhes.",
    managePrefs: "Gerenciar preferências",
    cookieEssential: "Essenciais",
    cookieEssentialDesc: "Necessários para a plataforma funcionar",
    cookieAnalytics: "Analíticos",
    cookieAnalyticsDesc: "Nos ajudam a entender como você usa a plataforma",
    cookieFunctional: "Funcionais",
    cookieFunctionalDesc: "Lembram suas preferências e configurações",
    savePrefs: "Salvar Preferências",
    acceptAll: "Aceitar Todos",
    rejectAll: "Rejeitar Todos",
  },
  de: {
    home: "Startseite", dashboard: "Dashboard", aiChat: "KI-Chat", quiz: "Quiz", forum: "Medien-Puls", watchlists: "Beobachtungslisten", settings: "Einstellungen", news: "Nachrichten", articleAnalyzer: "Nachrichten", new: "NEU",
    // Landing
    landingBanner: "Nur kurze Zeit: Plus 40% RABATT (8,99 €) · Pro 36% RABATT (15,99 €)",
    heroBadge: "KI-Schild gegen Voreingenommenheit",
    heroTitleA: "Schluss mit Trades auf", heroTitleB: "voreingenommenen News.",
    heroSubtitle: "Der erste KI-Schild für Privatanleger. Erhalten Sie sofortige Trust-Scores, Bias-Erkennung und versteckte Erkenntnisse zu jedem Finanzartikel.",
    heroPlaceholder: "Fügen Sie einen CNBC-, Seeking-Alpha- oder Motley-Fool-Link ein, um die Wahrheit zu enthüllen...",
    heroAnalyze: "Analysieren",
    heroOr: "oder",
    heroCreate: "Kostenloses Konto erstellen",
    valueCardsTitle: "Drei Gründe, warum Trader zu PortAI wechseln",
    valueBiasTitle: "Bias-Erkennung",
    valueBiasDesc: "Lassen Sie sich nicht länger von Werbesprache und versteckten Interessenkonflikten manipulieren.",
    valueFactTitle: "Faktencheck",
    valueFactDesc: "Erkennen Sie Lügen in Nachrichten und Forenbeiträgen durch KI-gestützte Verifizierung.",
    valueGlobalTitle: "Globale Abdeckung",
    valueGlobalDesc: "Vollständige Bias-Analyse in 6 Sprachen und über 10.000 globalen Assets.",
    techStackLabel: "Vertrauenswürdige Infrastruktur",
    supportingFeatures: "Ergänzende Funktionen",
    supportingFeaturesSub: "Über den Analysator hinaus — alles Weitere kostenlos.",
    marketIntelligence: "Marktintelligenz", aiCuratedAnalysis: "KI-kuratierte Analyse mit Vertrauenswerten und Live-Marktdaten",
    analyzeLink: "Link analysieren", analyze: "Analysieren", analyzing: "Analyse läuft...",
    pasteUrl: "Fügen Sie eine URL eines Finanzartikels ein. Die KI liefert einen Vertrauenswert (1-10), eine Zusammenfassung und eine Bias-Erkennung.",
    trustScore: "Vertrauenswert", smartSummary: "Intelligente Zusammenfassung", biasDetection: "Bias-Erkennung",
    stockHeatmap: "S&P 500 Heatmap",
    marketNewsFeed: "Marktnachrichten", autoRefresh: "Automatische Aktualisierung",
    newsDisclaimer: "Nachrichten von Google News. Nur zu Informationszwecken — keine Finanzberatung.",
    crypto: "Krypto", etfs: "ETFs",
    trustScoreDesc: "Die KI bewertet Quellglaubwürdigkeit, Autorenexpertise und Zitierqualität auf einer Skala von 1-10",
    smartSummaryDesc: "Erhalten Sie eine prägnante Zusammenfassung mit wichtigen Aussagen, Daten und Schlussfolgerungen",
    biasDetectionDesc: "Erkennt werbliche Sprache, fehlende Offenlegungen und potenzielle Interessenkonflikte",
    pasteArticleUrl: "Artikel-URL einfügen (z.B. https://cnbc.com/article/...)",
    source: "Quelle", summary: "Zusammenfassung", potentialBiases: "Potenzielle Verzerrungen", strengths: "Stärken",
    aiFinancialAdvisor: "KI-Finanzberater", poweredByAI: "KI-gestützt · Nur für Bildungszwecke",
    history: "Verlauf", newChat: "Neuer Chat", chatHistory: "Chatverlauf", noSavedChats: "Keine gespeicherten Chats.",
    askAnything: "Fragen Sie alles über Finanzen, Investitionen, Märkte...",
    welcomeMessage: "Hallo! Ich bin Ihr KI-Finanzberater. Fragen Sie mich zu Investitionen, Märkten oder Portfoliostrategien.",
    suggestETF: "Was ist der Unterschied zwischen ETFs und Investmentfonds?",
    suggestDiversify: "Wie sollte ich mein Portfolio diversifizieren?",
    suggestPE: "Erklären Sie das KGV und wie man es nutzt",
    suggestDCA: "Was ist Dollar-Cost-Averaging?",
    smartForum: "Intelligentes Forum", discussInvestments: "Diskutieren Sie Investitionen mit KI-Faktenprüfung",
    newThread: "Neues Thema", createNewThread: "Neues Thema erstellen", threadTitle: "Thementitel...",
    shareThoughts: "Teilen Sie Ihre Gedanken...", postThread: "Veröffentlichen", cancel: "Abbrechen",
    searchThreads: "Themen suchen...", factCheck: "Faktencheck", writeComment: "Kommentar schreiben...",
    all: "Alle", general: "Allgemein", portfolios: "Portfolios", markets: "Märkte", sectors: "Sektoren",
    noCommentsYet: "Noch keine Kommentare. Seien Sie der Erste!",
    moderationError: "Ihr Beitrag wurde wegen unangemessenen Inhalts markiert. Bitte überarbeiten Sie ihn.",
    tag: "Tag",
    trackStocks: "Verfolgen Sie Ihre Lieblingsaktien und ETFs", newList: "Neue Liste",
    createNewWatchlist: "Neue Beobachtungsliste erstellen", watchlistName: "Listenname...", create: "Erstellen",
    addStock: "Hinzufügen", searchStocksEtfs: "Aktien, ETFs, Krypto suchen...", noStocksYet: "Noch keine Aktien. Fügen Sie welche hinzu!",
    noWatchlistsYet: "Noch keine Listen", createFirstWatchlist: "Erstellen Sie Ihre erste Liste.",
    createWatchlist: "Liste erstellen", items: "Einträge",
    startTypingSearch: "Tippen Sie zum Suchen...", noResults: "Keine Ergebnisse gefunden",
    riskTolerance: "Risikotoleranz", riskToleranceSub: "Wie wohl fühlen Sie sich mit Marktvolatilität?",
    conservative: "Konservativ", conservativeDesc: "Bevorzugt Stabilität und Kapitalerhalt",
    moderate: "Moderat", moderateDesc: "Ausgewogenes Wachstum mit kontrolliertem Risiko",
    aggressive: "Aggressiv", aggressiveDesc: "Maximales Wachstum, höhere Volatilität",
    investmentTimeframe: "Anlagezeitraum", investmentTimeframeSub: "Wann planen Sie, diese Mittel zu nutzen?",
    shortTerm: "1-3 Jahre", shortTermDesc: "Kurzfristige Ziele",
    mediumTerm: "3-7 Jahre", mediumTermDesc: "Mittelfristige Planung",
    longTerm: "7+ Jahre", longTermDesc: "Langfristiger Vermögensaufbau",
    profitGoals: "Renditeziele", profitGoalsSub: "Welche jährliche Rendite streben Sie an?",
    steadyIncome: "5% / Jahr", steadyIncomeDesc: "Stabiles Einkommen",
    growthOriented: "10% / Jahr", growthOrientedDesc: "Wachstumsorientiert",
    aggressiveGrowth: "20%+ / Jahr", aggressiveGrowthDesc: "Aggressives Wachstum",
    investmentExperience: "Anlageerfahrung", investmentExperienceSub: "Wie würden Sie Ihre Erfahrung beschreiben?",
    beginner: "Anfänger", beginnerDesc: "Neu beim Investieren",
    intermediate: "Fortgeschritten", intermediateDesc: "Etwas Erfahrung",
    advanced: "Experte", advancedDesc: "Erfahrener Anleger",
    sectorInterests: "Brancheninteressen", sectorInterestsSub: "Wählen Sie Branchen, die Sie interessieren (optional)",
    technology: "Technologie", healthcare: "Gesundheit", finance: "Finanzen", energy: "Energie", consumer: "Konsum", industrial: "Industrie",
    step: "Schritt", of: "von", back: "Zurück", continue: "Weiter", generatePortfolio: "Portfolio generieren",
    yourPersonalizedPortfolio: "Ihr personalisiertes Portfolio", recommendedAllocations: "Empfohlene Allokationen",
    bearCase: "Pessimistisch", baseCase: "Basisszenario", bullCase: "Optimistisch", fiveYearReturn: "5-Jahres-Rendite",
    expectedReturn: "Erwartete Rendite", riskLevel: "Risikoniveau", retakeQuiz: "Quiz wiederholen", buildThisPortfolio: "Dieses Portfolio erstellen",
    profile: "Profil", displayName: "Anzeigename", changesSaveAuto: "Änderungen werden automatisch gespeichert",
    email: "E-Mail", emailCannotChange: "E-Mail kann nicht geändert werden", username: "Benutzername",
    anonymousMode: "Anonymer Modus", hideNameAvatar: "Name und Avatar in Forenbeiträgen verbergen",
    appearAs: "Sie erscheinen als", anonymousTrader: "Anonymer Trader",
    language: "Sprache", selectLanguage: "Wählen Sie Ihre bevorzugte Sprache",
    logOut: "Abmelden", uploadPhoto: "Foto hochladen", avatarRecommendation: "200×200px empfohlen. JPG, PNG",
    createAccount: "Konto erstellen", logIn: "Anmelden", emailAddress: "E-Mail-Adresse", password: "Passwort",
    alreadyHaveAccount: "Haben Sie bereits ein Konto?", dontHaveAccount: "Haben Sie noch kein Konto?",
    signUp: "Registrieren", fillAllFields: "Bitte füllen Sie alle Felder aus", passwordMin6: "Passwort muss mindestens 6 Zeichen lang sein",
    chooseUsername: "Benutzernamen wählen", usernameRequired: "Benutzername ist erforderlich", usernameMin3: "Benutzername muss mindestens 3 Zeichen lang sein",
    usernameTaken: "Dieser Benutzername ist bereits vergeben", usernameAvailable: "Benutzername verfügbar!",
    emailInUse: "Diese E-Mail ist bereits registriert.", switchToLogin: "Zur Anmeldung wechseln",
    invalidEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    backToWatchlists: "Zurück zu Listen", about: "Über", technicalAnalysis: "Technische Analyse", recentNews: "Aktuelle Nachrichten",
    notFinancialAdvice: "Keine Finanzberatung",
    disclaimerText: "Die KI-Analyse dient nur zu Informationszwecken. Konsultieren Sie immer qualifizierte Finanzfachleute, bevor Sie Anlageentscheidungen treffen.",
    deleteThread: "Thema löschen", deleteComment: "Kommentar löschen",
    notifications: "Benachrichtigungen", markAllRead: "Alle als gelesen markieren", noNotifications: "Keine neuen Benachrichtigungen",
    imageAttached: "Bild angehängt", uploadImage: "Bild hochladen",
    unlimited: "Unbegrenzt", analysesRemainingToday: "Analysen heute übrig", noAnalysesRemainingToday: "Keine Analysen mehr heute",
    welcomePro: "Willkommen bei Pro! 🎉 Alle Funktionen sind freigeschaltet.",
    analysisLimitTitle: "Analyselimit erreicht", analysisLimitDesc: "Du hast heute alle kostenlosen Analysen verbraucht. Upgrade auf Pro für unbegrenzte Analysen.",
    freeAnalysisUsedSingle: "Du hast deine kostenlose Analyse für heute verbraucht.", freeAnalysesUsedMulti: "Du hast alle kostenlosen Analysen für heute verbraucht.",
    quotaResets: "Dein Kontingent wird um Mitternacht zurückgesetzt, oder upgrade auf Pro für unbegrenzte Analysen.",
    upgradeToPro: "Auf Pro upgraden", clearLink: "Link löschen", share: "Teilen", shareToX: "Auf X teilen",
    proDeepDive: "Pro-Tiefenanalyse",
    stakeholderMotives: "Interessen der Beteiligten", stakeholderMotivesDesc: "Identifiziert, wer von dieser Erzählung profitiert — institutionelle Positionierung, jüngste Insider-Transaktionen und Analysten-Anreize.",
    omittedDataPoints: "Ausgelassene Daten", omittedDataPointsDesc: "Zeigt wesentlichen Kontext, den der Artikel auslässt: widersprüchliche Einreichungen, regulatorische Schlagzeilen und historische Vergleichswerte.",
    sentimentDivergence: "Sentiment-Divergenz", sentimentDivergenceDesc: "Vergleicht den Ton des Artikels mit sozialen Signalen, Optionsfluss und Peer-Berichterstattung, um künstlichen Konsens zu erkennen.",
    unlockDeepDive: "Tiefenanalyse mit Pro freischalten",
    chooseMarket: "Markt wählen", switchHeatmap: "Wechsle die Heatmap, um einen anderen globalen Index anzuzeigen.", active: "Aktiv",
    notArticleDefault: "Der angegebene Link scheint kein Nachrichtenartikel zu sein. Bitte füge einen direkten Link zu einem geschriebenen Artikel ein.",
    upgradeYourPlan: "Plan upgraden",
    upgradeChoose: "Wählen Sie Plus für die Essentials oder Pro für das volle Erlebnis.",
    plusEssentials: "Das Wesentliche für ernsthafte Anleger",
    plusFeatPlan: "Vollständige Quiz-Ergebnisse und Portfolio-Plan",
    plusFeatChat: "Unbegrenzter KI-Chat & Bildanalyse",
    plusFeatWatch: "Unbegrenzte Watchlists & Aktien",
    plusFeatCompare: "Asset-Vergleichscharts (bis zu 12 gleichzeitig)",
    plusFeatHeatmaps: "Live-Sentiment-Heatmaps",
    plusFeatDeepDive: "KI-Tiefenanalyse (versteckte Aspekte)",
    plusFeatAlerts: "Individuelle Preisalarme",
    proSubtitle: "Alles aus Plus und mehr",
    proFeatEverything: "Alles aus Plus",
    proFeatAnalyses: "Unbegrenzte Artikel- und Link-Analysen",
    proFeatFactCheck: "KI-Faktencheck zu Marktaussagen",
    proFeatInstitutional: "Institutionelle Tiefenanalyse",
    proFeatRealtime: "Echtzeit-Bias-Alarme für Ihr Portfolio",
    proFeatPriority: "Prioritäre KI-Geschwindigkeit (High-Compute-Modelle)",
    bestValue: "Bestes Angebot",
    upgradeToPlus: "Auf Plus upgraden",
    maybeLater: "Vielleicht später",
    off: "RABATT",
    priceAlert: "Preisalarm",
    priceAlertsFor: "Preisalarme für",
    signInForAlertsBody: "Bitte melden Sie sich an, um Preisalarme einzurichten.",
    proFeatureTitle: "Pro-Funktion",
    proFeatureBody: "Preisalarme sind exklusiv für Pro-Mitglieder. Upgrade, um benachrichtigt zu werden, sobald ein Asset Ihren Zielpreis erreicht.",
    currentPriceLabel: "Aktueller Preis",
    targetPriceLabel: "Zielpreis ($)",
    targetPricePh: "z.B. 250,00",
    risesAbove: "Steigt über",
    fallsBelow: "Fällt unter",
    setAlert: "Alarm setzen",
    settingDots: "Wird gesetzt...",
    activeAlerts: "Aktive Alarme",
    loadingDots: "Lädt...",
    noAlertsYet: "Noch keine Alarme.",
    alertTriggered: "Ausgelöst",
    deleteAlertLabel: "Alarm löschen",
    alertsCheckNote: "Alarme werden während der Marktaktivität etwa alle 5 Minuten geprüft.",
    signInForAlertsToast: "Bitte anmelden, um Alarme einzurichten",
    alertsProToast: "Alarme sind eine Pro-Funktion. Upgrade zum Freischalten.",
    enterValidPrice: "Gib einen gültigen Preis größer als 0 ein",
    alertCreateFailed: "Alarm konnte nicht erstellt werden",
    alertRemovedToast: "Alarm entfernt",
    setPriceAlert: "Preisalarm einrichten",
    tourWelcomeTitle: "Willkommen bei PortAI 👋",
    tourWelcomeText: "Dein KI-Schild gegen voreingenommene Finanznachrichten. Tour in 60 Sekunden.",
    tourStart: "Tour starten",
    tourNewsTitle: "News — Deine Kommandozentrale",
    tourNewsText: "Hier lebst du. Durchsuche kuratierte Finanznachrichten und füge eine URL ein, um sofort einen KI-Vertrauenswert, Bias-Erkennung und intelligente Zusammenfassung zu erhalten.",
    tourAnalyzeTitle: "Bias in jedem Artikel erkennen",
    tourAnalyzeText: "Füge hier eine Finanzartikel-URL ein. Unsere KI bewertet die Glaubwürdigkeit, fasst zusammen und markiert versteckte Agenden — in Sekunden.",
    tourForumTitle: "Live-Medien-Bias-Puls",
    tourForumText: "Sieh, was die Community gerade analysiert. Trending Artikel, Warnsignale und versteckte Aspekte — KI-validiert.",
    tourChatTitle: "Dein persönlicher KI-Berater",
    tourChatText: "Frag alles zu Aktien, ETFs, Portfolio-Strategie oder Markttrends. 24/7 verfügbar.",
    tourWatchTitle: "Aktien verfolgen",
    tourWatchText: "Erstelle individuelle Watchlists für 10.000+ Aktien, ETFs und Kryptos mit Live-Preisen und Charts.",
    tourQuizTitle: "Finde dein Anlegerprofil",
    tourQuizText: "5 schnelle Fragen und du erhältst ein personalisiertes Anlegerprofil mit auf deine Ziele zugeschnittenen Aktientipps.",
    tourDoneTitle: "Alles bereit! 🚀",
    tourDoneText: "Beginne, indem du einen Artikel-Link einfügst, um den KI-Vertrauenswert in Aktion zu sehen.",
    tourGoToNews: "Zu News",
    tourSkip: "Tour überspringen",
    tourFinish: "Fertig",
    tourNext: "Weiter",
    cookieTitle: "Wir verwenden Cookies",
    cookieBody: "Wir verwenden essentielle Cookies, damit die Plattform funktioniert, und optionale Cookies, um Ihre Erfahrung zu verbessern. Sie können Ihre Präferenzen unten anpassen. Lesen Sie unsere",
    privacyPolicyLink: "Datenschutzerklärung",
    forDetails: "für Details.",
    managePrefs: "Präferenzen verwalten",
    cookieEssential: "Essentiell",
    cookieEssentialDesc: "Erforderlich für die Plattformfunktion",
    cookieAnalytics: "Analyse",
    cookieAnalyticsDesc: "Helfen uns zu verstehen, wie Sie die Plattform nutzen",
    cookieFunctional: "Funktional",
    cookieFunctionalDesc: "Merken sich Ihre Präferenzen und Einstellungen",
    savePrefs: "Präferenzen speichern",
    acceptAll: "Alle akzeptieren",
    rejectAll: "Alle ablehnen",
  },
  it: {
    home: "Home", dashboard: "Dashboard", aiChat: "Chat IA", quiz: "Quiz", forum: "Polso Media", watchlists: "Liste", settings: "Impostazioni", news: "Notizie", articleAnalyzer: "Notizie", new: "NUOVO",
    // Landing
    landingBanner: "Tempo limitato: Plus 40% OFF (€8,99) · Pro 36% OFF (€15,99)",
    heroBadge: "Scudo IA anti-bias",
    heroTitleA: "Smetti di operare su", heroTitleB: "notizie distorte.",
    heroSubtitle: "Il primo scudo IA per gli investitori al dettaglio. Ottieni Trust Score, rilevamento dei bias e insight nascosti su qualsiasi articolo finanziario.",
    heroPlaceholder: "Incolla un link di CNBC, Seeking Alpha o Motley Fool per scoprire la verità...",
    heroAnalyze: "Analizza",
    heroOr: "oppure",
    heroCreate: "Crea account gratuito",
    valueCardsTitle: "Tre motivi per cui i trader scelgono PortAI",
    valueBiasTitle: "Rilevamento Bias",
    valueBiasDesc: "Smetti di essere manipolato da linguaggio promozionale e conflitti di interesse nascosti.",
    valueFactTitle: "Fact Checking",
    valueFactDesc: "Individua le bugie in notizie e post grazie alla verifica IA.",
    valueGlobalTitle: "Copertura Globale",
    valueGlobalDesc: "Analisi del bias in 6 lingue, su oltre 10.000 asset globali.",
    techStackLabel: "Infrastruttura affidabile",
    supportingFeatures: "Funzioni Complementari",
    supportingFeaturesSub: "Oltre all'analizzatore — tutto il resto, gratis.",
    marketIntelligence: "Intelligenza di Mercato", aiCuratedAnalysis: "Analisi IA con punteggi di fiducia e dati di mercato in tempo reale",
    analyzeLink: "Analizza Link", analyze: "Analizza", analyzing: "Analisi in corso...",
    pasteUrl: "Incolla l'URL di un articolo finanziario. L'IA fornirà un punteggio di fiducia (1-10), un riepilogo e il rilevamento dei bias.",
    trustScore: "Punteggio di Fiducia", smartSummary: "Riepilogo Intelligente", biasDetection: "Rilevamento Bias",
    stockHeatmap: "Mappa Termica S&P 500",
    marketNewsFeed: "Notizie di Mercato", autoRefresh: "Aggiornamento automatico",
    newsDisclaimer: "Notizie da Google News. Solo a scopo informativo — non è consulenza finanziaria.",
    crypto: "Cripto", etfs: "ETF",
    trustScoreDesc: "L'IA valuta credibilità della fonte, esperienza dell'autore e qualità delle citazioni su una scala da 1 a 10",
    smartSummaryDesc: "Ottieni un riepilogo conciso con affermazioni chiave, dati e conclusioni",
    biasDetectionDesc: "Segnala linguaggio promozionale, divulgazioni mancanti e potenziali conflitti di interesse",
    pasteArticleUrl: "Incolla l'URL dell'articolo (es. https://cnbc.com/article/...)",
    source: "Fonte", summary: "Riepilogo", potentialBiases: "Bias Potenziali", strengths: "Punti di Forza",
    aiFinancialAdvisor: "Consulente Finanziario IA", poweredByAI: "Alimentato dall'IA · Solo uso educativo",
    history: "Cronologia", newChat: "Nuova Chat", chatHistory: "Cronologia Chat", noSavedChats: "Nessuna chat salvata.",
    askAnything: "Chiedi qualsiasi cosa su finanza, investimenti, mercati...",
    welcomeMessage: "Ciao! Sono il tuo consulente finanziario IA. Chiedimi di investimenti, mercati o strategie di portafoglio.",
    suggestETF: "Qual è la differenza tra ETF e fondi comuni?",
    suggestDiversify: "Come dovrei diversificare il mio portafoglio?",
    suggestPE: "Spiega il rapporto P/E e come usarlo",
    suggestDCA: "Cos'è il dollar-cost averaging?",
    smartForum: "Forum Intelligente", discussInvestments: "Discuti investimenti con verifica dei fatti tramite IA",
    newThread: "Nuovo Tema", createNewThread: "Crea Nuovo Tema", threadTitle: "Titolo del tema...",
    shareThoughts: "Condividi i tuoi pensieri...", postThread: "Pubblica", cancel: "Annulla",
    searchThreads: "Cerca temi...", factCheck: "Verifica", writeComment: "Scrivi un commento...",
    all: "Tutti", general: "Generale", portfolios: "Portafogli", markets: "Mercati", sectors: "Settori",
    noCommentsYet: "Nessun commento ancora. Sii il primo!",
    moderationError: "Il tuo post è stato segnalato per contenuto inappropriato. Rivedi e riprova.",
    tag: "Tag",
    trackStocks: "Segui le tue azioni e ETF preferiti", newList: "Nuova Lista",
    createNewWatchlist: "Crea Nuova Lista", watchlistName: "Nome della lista...", create: "Crea",
    addStock: "Aggiungi", searchStocksEtfs: "Cerca azioni, ETF, cripto...", noStocksYet: "Nessuna azione ancora. Aggiungine alcune!",
    noWatchlistsYet: "Nessuna Lista Ancora", createFirstWatchlist: "Crea la tua prima lista per iniziare.",
    createWatchlist: "Crea Lista", items: "elementi",
    startTypingSearch: "Digita per cercare...", noResults: "Nessun risultato trovato",
    riskTolerance: "Tolleranza al Rischio", riskToleranceSub: "Quanto sei a tuo agio con la volatilità del mercato?",
    conservative: "Conservativo", conservativeDesc: "Preferisce stabilità e preservazione del capitale",
    moderate: "Moderato", moderateDesc: "Crescita equilibrata con rischio gestito",
    aggressive: "Aggressivo", aggressiveDesc: "Crescita massima, maggiore volatilità",
    investmentTimeframe: "Orizzonte di Investimento", investmentTimeframeSub: "Quando prevedi di utilizzare questi fondi?",
    shortTerm: "1-3 Anni", shortTermDesc: "Obiettivi a breve termine",
    mediumTerm: "3-7 Anni", mediumTermDesc: "Pianificazione a medio termine",
    longTerm: "7+ Anni", longTermDesc: "Creazione di ricchezza a lungo termine",
    profitGoals: "Obiettivi di Profitto", profitGoalsSub: "Quale rendimento annuale punti a ottenere?",
    steadyIncome: "5% / anno", steadyIncomeDesc: "Reddito stabile",
    growthOriented: "10% / anno", growthOrientedDesc: "Orientato alla crescita",
    aggressiveGrowth: "20%+ / anno", aggressiveGrowthDesc: "Crescita aggressiva",
    investmentExperience: "Esperienza di Investimento", investmentExperienceSub: "Come descriveresti la tua esperienza?",
    beginner: "Principiante", beginnerDesc: "Nuovo negli investimenti",
    intermediate: "Intermedio", intermediateDesc: "Un po' di esperienza",
    advanced: "Avanzato", advancedDesc: "Investitore esperto",
    sectorInterests: "Interessi per Settore", sectorInterestsSub: "Seleziona i settori che ti interessano (opzionale)",
    technology: "Tecnologia", healthcare: "Sanità", finance: "Finanza", energy: "Energia", consumer: "Consumo", industrial: "Industria",
    step: "Passo", of: "di", back: "Indietro", continue: "Continua", generatePortfolio: "Genera Portafoglio",
    yourPersonalizedPortfolio: "Il Tuo Portafoglio Personalizzato", recommendedAllocations: "Allocazioni Raccomandate",
    bearCase: "Caso Pessimista", baseCase: "Caso Base", bullCase: "Caso Ottimista", fiveYearReturn: "Rendimento a 5 anni",
    expectedReturn: "Rendimento Atteso", riskLevel: "Livello di Rischio", retakeQuiz: "Ripeti Quiz", buildThisPortfolio: "Crea Questo Portafoglio",
    profile: "Profilo", displayName: "Nome visualizzato", changesSaveAuto: "Le modifiche vengono salvate automaticamente",
    email: "E-mail", emailCannotChange: "L'e-mail non può essere modificata", username: "Nome utente",
    anonymousMode: "Modalità Anonima", hideNameAvatar: "Nascondi nome e avatar nei post del forum",
    appearAs: "Apparirai come", anonymousTrader: "Trader Anonimo",
    language: "Lingua", selectLanguage: "Scegli la tua lingua preferita",
    logOut: "Esci", uploadPhoto: "Carica Foto", avatarRecommendation: "200×200px consigliati. JPG, PNG",
    createAccount: "Crea Account", logIn: "Accedi", emailAddress: "Indirizzo e-mail", password: "Password",
    alreadyHaveAccount: "Hai già un account?", dontHaveAccount: "Non hai un account?",
    signUp: "Registrati", fillAllFields: "Compila tutti i campi", passwordMin6: "La password deve avere almeno 6 caratteri",
    chooseUsername: "Scegli un nome utente", usernameRequired: "Il nome utente è obbligatorio", usernameMin3: "Il nome utente deve avere almeno 3 caratteri",
    usernameTaken: "Questo nome utente è già in uso", usernameAvailable: "Nome utente disponibile!",
    emailInUse: "Questa e-mail è già registrata.", switchToLogin: "Vai all'accesso",
    invalidEmail: "Inserisci un indirizzo e-mail valido",
    backToWatchlists: "Torna alle Liste", about: "Informazioni", technicalAnalysis: "Analisi Tecnica", recentNews: "Notizie Recenti",
    notFinancialAdvice: "Non è consulenza finanziaria",
    disclaimerText: "L'analisi IA è solo a scopo informativo. Consulta sempre professionisti finanziari qualificati prima di prendere decisioni di investimento.",
    deleteThread: "Elimina tema", deleteComment: "Elimina commento",
    notifications: "Notifiche", markAllRead: "Segna tutto come letto", noNotifications: "Nessuna nuova notifica",
    imageAttached: "Immagine allegata", uploadImage: "Carica immagine",
    unlimited: "Illimitato", analysesRemainingToday: "analisi rimanenti oggi", noAnalysesRemainingToday: "Nessuna analisi rimanente oggi",
    welcomePro: "Benvenuto in Pro! 🎉 Tutte le funzionalità sono sbloccate.",
    analysisLimitTitle: "Limite di analisi raggiunto", analysisLimitDesc: "Hai usato tutte le tue analisi gratuite di oggi. Passa a Pro per analisi illimitate.",
    freeAnalysisUsedSingle: "Hai usato la tua analisi gratuita di oggi.", freeAnalysesUsedMulti: "Hai usato tutte le tue analisi gratuite di oggi.",
    quotaResets: "La tua quota si reimposta a mezzanotte, oppure passa a Pro per analisi illimitate.",
    upgradeToPro: "Passa a Pro", clearLink: "Cancella link", share: "Condividi", shareToX: "Condividi su X",
    proDeepDive: "Analisi Approfondita Pro",
    stakeholderMotives: "Motivazioni degli stakeholder", stakeholderMotivesDesc: "Identifica chi beneficia di questa narrazione: posizionamento istituzionale, recenti operazioni di insider e incentivi degli analisti.",
    omittedDataPoints: "Dati omessi", omittedDataPointsDesc: "Mette in luce il contesto materiale che l'articolo omette: dichiarazioni contraddittorie, titoli normativi e riferimenti storici.",
    sentimentDivergence: "Divergenza di sentiment", sentimentDivergenceDesc: "Confronta il tono dell'articolo con segnali social, flusso di opzioni e copertura dei pari per rilevare consenso fabbricato.",
    unlockDeepDive: "Sblocca l'Analisi Approfondita con Pro",
    chooseMarket: "Scegli un mercato", switchHeatmap: "Cambia la heatmap per vedere un altro indice globale.", active: "Attivo",
    notArticleDefault: "Il link fornito non sembra essere un articolo di notizie. Per favore incolla un link diretto a un articolo scritto.",
    upgradeYourPlan: "Aggiorna il tuo piano",
    upgradeChoose: "Scegli Plus per l'essenziale, o Pro per l'esperienza completa.",
    plusEssentials: "L'essenziale per investitori seri",
    plusFeatPlan: "Risultati completi del quiz e piano di portafoglio",
    plusFeatChat: "Chat IA e analisi immagini illimitate",
    plusFeatWatch: "Liste e azioni illimitate",
    plusFeatCompare: "Confronto asset (fino a 12 simultanei)",
    plusFeatHeatmaps: "Mappe termiche di sentiment in tempo reale",
    plusFeatDeepDive: "Analisi Approfondita IA (Angolazioni Nascoste)",
    plusFeatAlerts: "Avvisi di prezzo personalizzati",
    proSubtitle: "Tutto Plus, e molto altro",
    proFeatEverything: "Tutto Plus",
    proFeatAnalyses: "Analisi illimitate di articoli e link",
    proFeatFactCheck: "Verifica IA delle affermazioni di mercato",
    proFeatInstitutional: "Analisi istituzionale Deep-Dive",
    proFeatRealtime: "Avvisi di bias in tempo reale per il portafoglio",
    proFeatPriority: "Velocità IA prioritaria (modelli ad alta potenza)",
    bestValue: "Miglior valore",
    upgradeToPlus: "Passa a Plus",
    maybeLater: "Forse dopo",
    off: "SCONTO",
    priceAlert: "Avviso di Prezzo",
    priceAlertsFor: "Avvisi di prezzo per",
    signInForAlertsBody: "Accedi per impostare avvisi di prezzo.",
    proFeatureTitle: "Funzione Pro",
    proFeatureBody: "Gli avvisi di prezzo sono riservati ai membri Pro. Passa a Pro per ricevere notifiche quando un asset raggiunge il tuo prezzo target.",
    currentPriceLabel: "Prezzo attuale",
    targetPriceLabel: "Prezzo target ($)",
    targetPricePh: "es. 250,00",
    risesAbove: "Sale sopra",
    fallsBelow: "Scende sotto",
    setAlert: "Imposta Avviso",
    settingDots: "Impostazione...",
    activeAlerts: "Avvisi Attivi",
    loadingDots: "Caricamento...",
    noAlertsYet: "Nessun avviso ancora.",
    alertTriggered: "Attivato",
    deleteAlertLabel: "Elimina avviso",
    alertsCheckNote: "Gli avvisi vengono verificati circa ogni 5 minuti durante l'attività di mercato.",
    signInForAlertsToast: "Accedi per impostare avvisi",
    alertsProToast: "Gli avvisi sono una funzione Pro. Aggiorna per sbloccarli.",
    enterValidPrice: "Inserisci un prezzo valido maggiore di 0",
    alertCreateFailed: "Creazione avviso fallita",
    alertRemovedToast: "Avviso rimosso",
    setPriceAlert: "Imposta Avviso di Prezzo",
    tourWelcomeTitle: "Benvenuto su PortAI 👋",
    tourWelcomeText: "Il tuo scudo IA contro le notizie finanziarie distorte. Tour in 60 secondi.",
    tourStart: "Inizia il Tour",
    tourNewsTitle: "Notizie — Il Tuo Centro di Comando",
    tourNewsText: "Qui vivi. Sfoglia notizie finanziarie curate e incolla qualsiasi URL per ottenere subito Trust Score IA, rilevamento bias e riepilogo intelligente.",
    tourAnalyzeTitle: "Rileva Bias in Qualsiasi Articolo",
    tourAnalyzeText: "Incolla qui l'URL di un articolo finanziario. La nostra IA ne valuta l'affidabilità, lo riepiloga e segnala agende nascoste in pochi secondi.",
    tourForumTitle: "Polso Bias dei Media in Tempo Reale",
    tourForumText: "Vedi cosa la community sta analizzando ora. Articoli di tendenza, segnali e angolazioni nascoste — tutti validati dall'IA.",
    tourChatTitle: "Il Tuo Consulente IA Personale",
    tourChatText: "Chiedi qualsiasi cosa su azioni, ETF, strategia di portafoglio o tendenze di mercato. Disponibile 24/7.",
    tourWatchTitle: "Segui le tue Azioni",
    tourWatchText: "Crea liste personalizzate per oltre 10.000 azioni, ETF e cripto con prezzi e grafici in tempo reale.",
    tourQuizTitle: "Trova il tuo Profilo di Investitore",
    tourQuizText: "5 domande veloci e otterrai un profilo personalizzato con selezione di asset su misura per i tuoi obiettivi.",
    tourDoneTitle: "Tutto pronto! 🚀",
    tourDoneText: "Inizia incollando un link di articolo per vedere il Trust Score IA in azione.",
    tourGoToNews: "Vai alle Notizie",
    tourSkip: "Salta Tour",
    tourFinish: "Fine",
    tourNext: "Avanti",
    cookieTitle: "Usiamo i cookie",
    cookieBody: "Usiamo cookie essenziali per il funzionamento della piattaforma e cookie opzionali per migliorare la tua esperienza. Puoi personalizzare le preferenze qui sotto. Leggi la nostra",
    privacyPolicyLink: "Informativa sulla Privacy",
    forDetails: "per i dettagli.",
    managePrefs: "Gestisci preferenze",
    cookieEssential: "Essenziali",
    cookieEssentialDesc: "Necessari per il funzionamento della piattaforma",
    cookieAnalytics: "Analitici",
    cookieAnalyticsDesc: "Ci aiutano a capire come usi la piattaforma",
    cookieFunctional: "Funzionali",
    cookieFunctionalDesc: "Ricordano le tue preferenze e impostazioni",
    savePrefs: "Salva Preferenze",
    acceptAll: "Accetta Tutti",
    rejectAll: "Rifiuta Tutti",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  pt: "Português",
  de: "Deutsch",
  it: "Italiano",
};

type LanguageState = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageNames: Record<Language, string>;
};

const LanguageContext = createContext<LanguageState | null>(null);

const LANG_STORAGE_KEY = "portai.language";
const isValidLanguage = (v: unknown): v is Language =>
  typeof v === "string" && ["en", "es", "fr", "pt", "de", "it"].includes(v);

export const LanguageProvider = ({ children, initialLanguage = "en" }: { children: ReactNode; initialLanguage?: Language }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem(LANG_STORAGE_KEY);
      if (isValidLanguage(stored)) return stored;
    }
    return initialLanguage;
  });
  const [hasUserChanged, setHasUserChanged] = useState(() => {
    if (typeof window !== "undefined") {
      return isValidLanguage(localStorage.getItem(LANG_STORAGE_KEY));
    }
    return false;
  });

  // Sync from DB on load, but don't override manual/stored user choice
  React.useEffect(() => {
    if (!hasUserChanged) {
      setLanguageState(initialLanguage as Language);
    }
  }, [initialLanguage]);

  const setLanguage = (lang: Language) => {
    setHasUserChanged(true);
    setLanguageState(lang);
    try { localStorage.setItem(LANG_STORAGE_KEY, lang); } catch {}
  };


  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
