import { AssetEntry } from "./types";

export const additionalCrypto: AssetEntry[] = [
  // Layer 1s
  { ticker: "HNTUSDT", name: "Helium", sector: "Crypto", type: "crypto" },
  { ticker: "CFXUSDT", name: "Conflux", sector: "Crypto", type: "crypto" },
  { ticker: "KAIASD", name: "Kaia", sector: "Crypto", type: "crypto" },
  { ticker: "BEAMUSD", name: "Beam", sector: "Crypto", type: "crypto" },
  { ticker: "COREUSD", name: "Core DAO", sector: "Crypto", type: "crypto" },
  { ticker: "CELOUSD", name: "Celo", sector: "Crypto", type: "crypto" },
  { ticker: "CKBUSD", name: "Nervos Network", sector: "Crypto", type: "crypto" },
  { ticker: "IOTXUSD", name: "IoTeX", sector: "Crypto", type: "crypto" },
  { ticker: "SCUSD", name: "Siacoin", sector: "Crypto", type: "crypto" },
  { ticker: "ARUSD", name: "Arweave", sector: "Crypto", type: "crypto" },
  { ticker: "GNOUSD", name: "Gnosis", sector: "Crypto", type: "crypto" },
  { ticker: "RADUSD", name: "Radicle", sector: "Crypto", type: "crypto" },
  { ticker: "METISUSD", name: "Metis", sector: "Crypto", type: "crypto" },
  { ticker: "MANTUSD", name: "Mantle", sector: "Crypto", type: "crypto" },
  { ticker: "MNTUSD", name: "Mantle Token", sector: "Crypto", type: "crypto" },
  { ticker: "TUSDUSD", name: "TrueUSD", sector: "Crypto", type: "crypto" },
  { ticker: "ZKSYNUSD", name: "zkSync", sector: "Crypto", type: "crypto" },
  { ticker: "STRRUSD", name: "Starknet", sector: "Crypto", type: "crypto" },
  { ticker: "SCROLLUSD", name: "Scroll", sector: "Crypto", type: "crypto" },
  { ticker: "LINEAUSD", name: "Linea", sector: "Crypto", type: "crypto" },

  // DeFi
  { ticker: "DYDXUSD", name: "dYdX", sector: "Crypto", type: "crypto" },
  { ticker: "GMXUSD", name: "GMX", sector: "Crypto", type: "crypto" },
  { ticker: "1INCHUSD", name: "1inch Network", sector: "Crypto", type: "crypto" },
  { ticker: "BALUSD", name: "Balancer", sector: "Crypto", type: "crypto" },
  { ticker: "SUSHIUSD", name: "SushiSwap", sector: "Crypto", type: "crypto" },
  { ticker: "YFIUSD", name: "yearn.finance", sector: "Crypto", type: "crypto" },
  { ticker: "ALPHASD", name: "Alpha Venture DAO", sector: "Crypto", type: "crypto" },
  { ticker: "CAKEUSD", name: "PancakeSwap", sector: "Crypto", type: "crypto" },
  { ticker: "RAYDIUMUSD", name: "Raydium", sector: "Crypto", type: "crypto" },
  { ticker: "ORCAUSD", name: "Orca", sector: "Crypto", type: "crypto" },
  { ticker: "MORPHOUSD", name: "Morpho", sector: "Crypto", type: "crypto" },
  { ticker: "ETHFIUSD", name: "ether.fi", sector: "Crypto", type: "crypto" },
  { ticker: "RSWETHUSD", name: "Restaked Swell ETH", sector: "Crypto", type: "crypto" },
  { ticker: "OSMOSD", name: "Osmosis", sector: "Crypto", type: "crypto" },
  { ticker: "JUPUSD2", name: "Jupiter DEX", sector: "Crypto", type: "crypto" },
  { ticker: "AEROUSD", name: "Aerodrome Finance", sector: "Crypto", type: "crypto" },
  { ticker: "VELOUSD", name: "Velodrome Finance", sector: "Crypto", type: "crypto" },

  // Gaming / Metaverse
  { ticker: "IMXUSD", name: "Immutable X", sector: "Crypto", type: "crypto" },
  { ticker: "RONUSD", name: "Ronin", sector: "Crypto", type: "crypto" },
  { ticker: "WAXPUSD", name: "WAX", sector: "Crypto", type: "crypto" },
  { ticker: "YGGUSDT", name: "Yield Guild Games", sector: "Crypto", type: "crypto" },
  { ticker: "MAGICUSD", name: "MAGIC", sector: "Crypto", type: "crypto" },
  { ticker: "PRIMEUSD", name: "Echelon Prime", sector: "Crypto", type: "crypto" },
  { ticker: "PIXELUSD", name: "Pixels", sector: "Crypto", type: "crypto" },
  { ticker: "PORTALUSD", name: "Portal", sector: "Crypto", type: "crypto" },
  { ticker: "XAIUSD", name: "Xai", sector: "Crypto", type: "crypto" },
  { ticker: "BOMEUSDT", name: "BOOK OF MEME", sector: "Crypto", type: "crypto" },

  // AI Crypto
  { ticker: "TAOUSD", name: "Bittensor", sector: "Crypto", type: "crypto" },
  { ticker: "AGIUSD", name: "SingularityNET", sector: "Crypto", type: "crypto" },
  { ticker: "AKTUSD", name: "Akash Network", sector: "Crypto", type: "crypto" },
  { ticker: "RNDRAUSD", name: "Render (AI)", sector: "Crypto", type: "crypto" },
  { ticker: "NMRUSD", name: "Numeraire", sector: "Crypto", type: "crypto" },
  { ticker: "AIOZUSD", name: "AIOZ Network", sector: "Crypto", type: "crypto" },
  { ticker: "PHAUSD", name: "Phala Network", sector: "Crypto", type: "crypto" },
  { ticker: "ABORUSD", name: "Arbor Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARKMSD", name: "Arkham", sector: "Crypto", type: "crypto" },
  { ticker: "WLDUSD", name: "Worldcoin", sector: "Crypto", type: "crypto" },
  { ticker: "IOSD", name: "io.net", sector: "Crypto", type: "crypto" },
  { ticker: "NOSANAUSD", name: "Nosana", sector: "Crypto", type: "crypto" },

  // Memecoins (additional)
  { ticker: "MEMEUSD", name: "Memecoin", sector: "Crypto", type: "crypto" },
  { ticker: "BRETTUSD", name: "Brett", sector: "Crypto", type: "crypto" },
  { ticker: "MOGUSDT", name: "Mog Coin", sector: "Crypto", type: "crypto" },
  { ticker: "NEIROUSD", name: "Neiro", sector: "Crypto", type: "crypto" },
  { ticker: "TURBUSD", name: "Turbo", sector: "Crypto", type: "crypto" },
  { ticker: "POPCATUSD", name: "Popcat", sector: "Crypto", type: "crypto" },
  { ticker: "MYROSD", name: "Myro", sector: "Crypto", type: "crypto" },
  { ticker: "GIGAUSD", name: "GIGA", sector: "Crypto", type: "crypto" },
  { ticker: "WENUSD", name: "WEN", sector: "Crypto", type: "crypto" },
  { ticker: "MEWUSD", name: "cat in a dogs world", sector: "Crypto", type: "crypto" },
  { ticker: "PONKEUSD", name: "PONKE", sector: "Crypto", type: "crypto" },
  { ticker: "TREMUSD", name: "TRUMP", sector: "Crypto", type: "crypto" },
  { ticker: "MELANIAUSD", name: "MELANIA", sector: "Crypto", type: "crypto" },
  { ticker: "AIDOGUSD", name: "AiDoge", sector: "Crypto", type: "crypto" },

  // Infrastructure / Oracle
  { ticker: "BANDUSD", name: "Band Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "APIIUSD", name: "API3", sector: "Crypto", type: "crypto" },
  { ticker: "DIAUSD", name: "DIA", sector: "Crypto", type: "crypto" },
  { ticker: "TLMUSD", name: "Alien Worlds", sector: "Crypto", type: "crypto" },
  { ticker: "CTSIUSD", name: "Cartesi", sector: "Crypto", type: "crypto" },
  { ticker: "CELRUSD", name: "Celer Network", sector: "Crypto", type: "crypto" },
  { ticker: "STGUSD", name: "Stargate Finance", sector: "Crypto", type: "crypto" },
  { ticker: "ZROUSD", name: "LayerZero", sector: "Crypto", type: "crypto" },
  { ticker: "WOOSD", name: "WOO Network", sector: "Crypto", type: "crypto" },
  { ticker: "ZETAUSD", name: "ZetaChain", sector: "Crypto", type: "crypto" },
  { ticker: "POLYXUSD", name: "Polymesh", sector: "Crypto", type: "crypto" },
  { ticker: "FLRUSD", name: "Flare", sector: "Crypto", type: "crypto" },

  // Privacy / Storage
  { ticker: "OXENUSD", name: "Oxen", sector: "Crypto", type: "crypto" },
  { ticker: "NYMUSD", name: "Nym", sector: "Crypto", type: "crypto" },
  { ticker: "STORJUSD", name: "Storj", sector: "Crypto", type: "crypto" },
  { ticker: "BNTUSD", name: "Bancor", sector: "Crypto", type: "crypto" },
  { ticker: "LSKUSD", name: "Lisk", sector: "Crypto", type: "crypto" },
  { ticker: "ANKRUSD", name: "Ankr", sector: "Crypto", type: "crypto" },
  { ticker: "SKLUSD", name: "SKALE Network", sector: "Crypto", type: "crypto" },
  { ticker: "TFUELUSD", name: "Theta Fuel", sector: "Crypto", type: "crypto" },
  { ticker: "COTIUSD", name: "COTI", sector: "Crypto", type: "crypto" },
  { ticker: "RVNUSD", name: "Ravencoin", sector: "Crypto", type: "crypto" },

  // Exchange tokens
  { ticker: "OKBUSD", name: "OKB", sector: "Crypto", type: "crypto" },
  { ticker: "LEOUSD", name: "UNUS SED LEO", sector: "Crypto", type: "crypto" },
  { ticker: "CROUSD", name: "Cronos", sector: "Crypto", type: "crypto" },
  { ticker: "KUCSUSD", name: "KuCoin Token", sector: "Crypto", type: "crypto" },
  { ticker: "GTUSD", name: "Gate Token", sector: "Crypto", type: "crypto" },
  { ticker: "MXUSD", name: "MX Token", sector: "Crypto", type: "crypto" },
  { ticker: "HTUSD", name: "Huobi Token", sector: "Crypto", type: "crypto" },

  // RWA (Real World Assets)
  { ticker: "RWASUSD", name: "RWA Finance", sector: "Crypto", type: "crypto" },
  { ticker: "POLYUSD", name: "Polymath", sector: "Crypto", type: "crypto" },
  { ticker: "PROPCUSD", name: "Propchain", sector: "Crypto", type: "crypto" },
  { ticker: "CFGUSD", name: "Centrifuge", sector: "Crypto", type: "crypto" },
  { ticker: "MPLKUSD", name: "Maple Finance", sector: "Crypto", type: "crypto" },
  { ticker: "TRUEFIUSD", name: "TrueFi", sector: "Crypto", type: "crypto" },

  // Social / Creator
  { ticker: "MASKUSD", name: "Mask Network", sector: "Crypto", type: "crypto" },
  { ticker: "LENSUSD", name: "Lens Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "DESOUSD", name: "Decentralized Social", sector: "Crypto", type: "crypto" },
  { ticker: "GALUSD", name: "Galxe", sector: "Crypto", type: "crypto" },
  { ticker: "HOOKSD", name: "Hooked Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "EDUVUSD", name: "Open Campus", sector: "Crypto", type: "crypto" },

  // Stablecoins / Payment
  { ticker: "USDTUSD", name: "Tether", sector: "Crypto", type: "crypto" },
  { ticker: "USDCUSD", name: "USD Coin", sector: "Crypto", type: "crypto" },
  { ticker: "DAIUSD", name: "Dai", sector: "Crypto", type: "crypto" },
  { ticker: "FRAXUSD", name: "Frax", sector: "Crypto", type: "crypto" },
  { ticker: "LUSDSD", name: "Liquity USD", sector: "Crypto", type: "crypto" },
  { ticker: "PAXGUSD", name: "PAX Gold", sector: "Crypto", type: "crypto" },
  { ticker: "PYUSDUSD", name: "PayPal USD", sector: "Crypto", type: "crypto" },

  // Additional L2 / Scaling
  { ticker: "POLYGONUSD", name: "Polygon zkEVM", sector: "Crypto", type: "crypto" },
  { ticker: "BASEUSD", name: "Base", sector: "Crypto", type: "crypto" },
  { ticker: "BLOUSD", name: "Blobscriptions", sector: "Crypto", type: "crypto" },
  { ticker: "LOOPUSD", name: "Loopring", sector: "Crypto", type: "crypto" },
  { ticker: "BOBA_USD", name: "Boba Network", sector: "Crypto", type: "crypto" },

  // Misc
  { ticker: "CHZUSD", name: "Chiliz", sector: "Crypto", type: "crypto" },
  { ticker: "APEUSDT", name: "ApeCoin", sector: "Crypto", type: "crypto" },
  { ticker: "BLURUSD", name: "Blur", sector: "Crypto", type: "crypto" },
  { ticker: "RAREUSD", name: "SuperRare", sector: "Crypto", type: "crypto" },
  { ticker: "LOOKSSD", name: "LooksRare", sector: "Crypto", type: "crypto" },
  { ticker: "X2Y2USD", name: "X2Y2", sector: "Crypto", type: "crypto" },
  { ticker: "RPLUSD", name: "Rocket Pool", sector: "Crypto", type: "crypto" },
  { ticker: "SSVUSD", name: "SSV Network", sector: "Crypto", type: "crypto" },
  { ticker: "OETHUSD", name: "Origin Ether", sector: "Crypto", type: "crypto" },
  { ticker: "PRISMAUSD", name: "Prisma Finance", sector: "Crypto", type: "crypto" },
  { ticker: "SAFEUSD", name: "Safe", sector: "Crypto", type: "crypto" },
  { ticker: "ENUSD", name: "Enjin Coin v2", sector: "Crypto", type: "crypto" },
  { ticker: "AUDIOUSD", name: "Audius", sector: "Crypto", type: "crypto" },
  { ticker: "LIVEPEERUSD", name: "Livepeer", sector: "Crypto", type: "crypto" },
  { ticker: "BATUSD", name: "Basic Attention Token", sector: "Crypto", type: "crypto" },
  { ticker: "POWRUSD", name: "Power Ledger", sector: "Crypto", type: "crypto" },
  { ticker: "OCEANV2USD", name: "ASI Alliance", sector: "Crypto", type: "crypto" },
  { ticker: "SXPUSD", name: "Solar", sector: "Crypto", type: "crypto" },
  { ticker: "REQSD", name: "Request", sector: "Crypto", type: "crypto" },
  { ticker: "NMRUSD2", name: "Numerai", sector: "Crypto", type: "crypto" },
];
