import { AssetEntry } from "./types";

export const additionalStocks: AssetEntry[] = [
  // Semiconductors
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", type: "stock" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology", type: "stock" },
  { ticker: "QRVO", name: "Qorvo Inc.", sector: "Technology", type: "stock" },
  { ticker: "WOLF", name: "Wolfspeed Inc.", sector: "Technology", type: "stock" },
  { ticker: "CRUS", name: "Cirrus Logic", sector: "Technology", type: "stock" },
  { ticker: "MPWR", name: "Monolithic Power Systems", sector: "Technology", type: "stock" },
  { ticker: "ACLS", name: "Axcelis Technologies", sector: "Technology", type: "stock" },
  { ticker: "RMBS", name: "Rambus Inc.", sector: "Technology", type: "stock" },
  { ticker: "SMTC", name: "Semtech Corporation", sector: "Technology", type: "stock" },
  { ticker: "LSCC", name: "Lattice Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ALGM", name: "Allegro MicroSystems", sector: "Technology", type: "stock" },
  { ticker: "AMKR", name: "Amkor Technology", sector: "Technology", type: "stock" },
  { ticker: "DIOD", name: "Diodes Incorporated", sector: "Technology", type: "stock" },
  { ticker: "SITM", name: "SiTime Corporation", sector: "Technology", type: "stock" },

  // Software / SaaS
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology", type: "stock" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology", type: "stock" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Technology", type: "stock" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Technology", type: "stock" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology", type: "stock" },
  { ticker: "MDB", name: "MongoDB Inc.", sector: "Technology", type: "stock" },
  { ticker: "HUBS", name: "HubSpot Inc.", sector: "Technology", type: "stock" },
  { ticker: "BILL", name: "BILL Holdings", sector: "Technology", type: "stock" },
  { ticker: "OKTA", name: "Okta Inc.", sector: "Technology", type: "stock" },
  { ticker: "WDAY", name: "Workday Inc.", sector: "Technology", type: "stock" },
  { ticker: "VEEV", name: "Veeva Systems", sector: "Technology", type: "stock" },
  { ticker: "TTD", name: "The Trade Desk", sector: "Technology", type: "stock" },
  { ticker: "U", name: "Unity Software", sector: "Technology", type: "stock" },
  { ticker: "TWLO", name: "Twilio Inc.", sector: "Technology", type: "stock" },
  { ticker: "ZI", name: "ZoomInfo Technologies", sector: "Technology", type: "stock" },
  { ticker: "CFLT", name: "Confluent Inc.", sector: "Technology", type: "stock" },
  { ticker: "PATH", name: "UiPath Inc.", sector: "Technology", type: "stock" },
  { ticker: "ESTC", name: "Elastic N.V.", sector: "Technology", type: "stock" },
  { ticker: "MNDY", name: "monday.com Ltd.", sector: "Technology", type: "stock" },
  { ticker: "PCOR", name: "Procore Technologies", sector: "Technology", type: "stock" },
  { ticker: "GTLB", name: "GitLab Inc.", sector: "Technology", type: "stock" },
  { ticker: "DOCN", name: "DigitalOcean Holdings", sector: "Technology", type: "stock" },
  { ticker: "BRZE", name: "Braze Inc.", sector: "Technology", type: "stock" },
  { ticker: "SMAR", name: "Smartsheet Inc.", sector: "Technology", type: "stock" },
  { ticker: "ALTR", name: "Altair Engineering", sector: "Technology", type: "stock" },
  { ticker: "PD", name: "PagerDuty Inc.", sector: "Technology", type: "stock" },

  // AI / Data
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology", type: "stock" },
  { ticker: "AI", name: "C3.ai Inc.", sector: "Technology", type: "stock" },
  { ticker: "BBAI", name: "BigBear.ai Holdings", sector: "Technology", type: "stock" },
  { ticker: "SOUN", name: "SoundHound AI", sector: "Technology", type: "stock" },
  { ticker: "UPST", name: "Upstart Holdings", sector: "Technology", type: "stock" },
  { ticker: "ASAN", name: "Asana Inc.", sector: "Technology", type: "stock" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology", type: "stock" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "Technology", type: "stock" },

  // Aerospace & Defense
  { ticker: "LMT", name: "Lockheed Martin", sector: "Defense", type: "stock" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Defense", type: "stock" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Defense", type: "stock" },
  { ticker: "GD", name: "General Dynamics", sector: "Defense", type: "stock" },
  { ticker: "LHX", name: "L3Harris Technologies", sector: "Defense", type: "stock" },
  { ticker: "TDG", name: "TransDigm Group", sector: "Defense", type: "stock" },
  { ticker: "HWM", name: "Howmet Aerospace", sector: "Defense", type: "stock" },
  { ticker: "HEI", name: "HEICO Corporation", sector: "Defense", type: "stock" },
  { ticker: "TXT", name: "Textron Inc.", sector: "Defense", type: "stock" },
  { ticker: "AXON", name: "Axon Enterprise", sector: "Defense", type: "stock" },

  // Biotech / Pharma (additional)
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "SGEN", name: "Seagen Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "EXAS", name: "Exact Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "HALO", name: "Halozyme Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "INCY", name: "Incyte Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "BMRN", name: "BioMarin Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "ARGX", name: "argenx SE", sector: "Healthcare", type: "stock" },
  { ticker: "PCVX", name: "Vaxcyte Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "RPRX", name: "Royalty Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "SWTX", name: "SpringWorks Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "IONS", name: "Ionis Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "NBIX", name: "Neurocrine Biosciences", sector: "Healthcare", type: "stock" },
  { ticker: "INSM", name: "Insmed Incorporated", sector: "Healthcare", type: "stock" },
  { ticker: "NTRA", name: "Natera Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "TWST", name: "Twist Bioscience", sector: "Healthcare", type: "stock" },

  // Healthcare / Med Devices
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "stock" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "ZBH", name: "Zimmer Biomet", sector: "Healthcare", type: "stock" },
  { ticker: "HOLX", name: "Hologic Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare", type: "stock" },
  { ticker: "DXCM", name: "DexCom Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "PODD", name: "Insulet Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "RVMD", name: "Revolution Medicines", sector: "Healthcare", type: "stock" },
  { ticker: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare", type: "stock" },

  // Financial Services (additional)
  { ticker: "COIN", name: "Coinbase Global", sector: "Financial", type: "stock" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Financial", type: "stock" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Financial", type: "stock" },
  { ticker: "AFRM", name: "Affirm Holdings", sector: "Financial", type: "stock" },
  { ticker: "NU", name: "Nu Holdings", sector: "Financial", type: "stock" },
  { ticker: "MELI", name: "MercadoLibre", sector: "Financial", type: "stock" },
  { ticker: "TOST", name: "Toast Inc.", sector: "Financial", type: "stock" },
  { ticker: "FIS", name: "Fidelity National Information Services", sector: "Financial", type: "stock" },
  { ticker: "FISV", name: "Fiserv Inc.", sector: "Financial", type: "stock" },
  { ticker: "GPN", name: "Global Payments", sector: "Financial", type: "stock" },
  { ticker: "WEX", name: "WEX Inc.", sector: "Financial", type: "stock" },
  { ticker: "LPLA", name: "LPL Financial Holdings", sector: "Financial", type: "stock" },
  { ticker: "RJF", name: "Raymond James Financial", sector: "Financial", type: "stock" },
  { ticker: "MKTX", name: "MarketAxess Holdings", sector: "Financial", type: "stock" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Financial", type: "stock" },

  // Energy (additional)
  { ticker: "FSLR", name: "First Solar", sector: "Energy", type: "stock" },
  { ticker: "ENPH", name: "Enphase Energy", sector: "Energy", type: "stock" },
  { ticker: "SEDG", name: "SolarEdge Technologies", sector: "Energy", type: "stock" },
  { ticker: "RUN", name: "Sunrun Inc.", sector: "Energy", type: "stock" },
  { ticker: "PLUG", name: "Plug Power", sector: "Energy", type: "stock" },
  { ticker: "NOVA", name: "Sunnova Energy", sector: "Energy", type: "stock" },
  { ticker: "OKE", name: "ONEOK Inc.", sector: "Energy", type: "stock" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy", type: "stock" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy", type: "stock" },
  { ticker: "ET", name: "Energy Transfer", sector: "Energy", type: "stock" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", type: "stock" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", type: "stock" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", type: "stock" },
  { ticker: "CTRA", name: "Coterra Energy", sector: "Energy", type: "stock" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy", type: "stock" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", type: "stock" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", type: "stock" },
  { ticker: "APA", name: "APA Corporation", sector: "Energy", type: "stock" },
  { ticker: "HAL", name: "Halliburton Company", sector: "Energy", type: "stock" },
  { ticker: "SLB", name: "Schlumberger Limited", sector: "Energy", type: "stock" },

  // Consumer / Retail (additional)
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer", type: "stock" },
  { ticker: "DECK", name: "Deckers Outdoor", sector: "Consumer", type: "stock" },
  { ticker: "ON", name: "On Holding", sector: "Consumer", type: "stock" },
  { ticker: "CROX", name: "Crocs Inc.", sector: "Consumer", type: "stock" },
  { ticker: "BIRK", name: "Birkenstock Holding", sector: "Consumer", type: "stock" },
  { ticker: "SHAK", name: "Shake Shack", sector: "Consumer", type: "stock" },
  { ticker: "CAVA", name: "CAVA Group", sector: "Consumer", type: "stock" },
  { ticker: "WINGSTOP", name: "Wingstop Inc.", sector: "Consumer", type: "stock" },
  { ticker: "DPZ", name: "Domino's Pizza", sector: "Consumer", type: "stock" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer", type: "stock" },
  { ticker: "DASH", name: "DoorDash Inc.", sector: "Consumer", type: "stock" },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Consumer", type: "stock" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer", type: "stock" },
  { ticker: "EXPE", name: "Expedia Group", sector: "Consumer", type: "stock" },
  { ticker: "UBER", name: "Uber Technologies", sector: "Consumer", type: "stock" },
  { ticker: "LYFT", name: "Lyft Inc.", sector: "Consumer", type: "stock" },
  { ticker: "GRAB", name: "Grab Holdings", sector: "Consumer", type: "stock" },
  { ticker: "CPNG", name: "Coupang Inc.", sector: "Consumer", type: "stock" },
  { ticker: "SE", name: "Sea Limited", sector: "Consumer", type: "stock" },
  { ticker: "GLBE", name: "Global-e Online", sector: "Consumer", type: "stock" },
  { ticker: "ETSY", name: "Etsy Inc.", sector: "Consumer", type: "stock" },
  { ticker: "W", name: "Wayfair Inc.", sector: "Consumer", type: "stock" },
  { ticker: "CHWY", name: "Chewy Inc.", sector: "Consumer", type: "stock" },
  { ticker: "RVLV", name: "Revolve Group", sector: "Consumer", type: "stock" },
  { ticker: "ELF", name: "e.l.f. Beauty", sector: "Consumer", type: "stock" },

  // Industrials
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrial", type: "stock" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrial", type: "stock" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrial", type: "stock" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrial", type: "stock" },
  { ticker: "ETN", name: "Eaton Corporation", sector: "Industrial", type: "stock" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrial", type: "stock" },
  { ticker: "GEV", name: "GE Vernova", sector: "Industrial", type: "stock" },
  { ticker: "MMM", name: "3M Company", sector: "Industrial", type: "stock" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrial", type: "stock" },
  { ticker: "PH", name: "Parker-Hannifin", sector: "Industrial", type: "stock" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrial", type: "stock" },
  { ticker: "CMI", name: "Cummins Inc.", sector: "Industrial", type: "stock" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrial", type: "stock" },
  { ticker: "URI", name: "United Rentals", sector: "Industrial", type: "stock" },
  { ticker: "FAST", name: "Fastenal Company", sector: "Industrial", type: "stock" },
  { ticker: "FTV", name: "Fortive Corporation", sector: "Industrial", type: "stock" },
  { ticker: "AME", name: "AMETEK Inc.", sector: "Industrial", type: "stock" },
  { ticker: "DOV", name: "Dover Corporation", sector: "Industrial", type: "stock" },
  { ticker: "XYL", name: "Xylem Inc.", sector: "Industrial", type: "stock" },
  { ticker: "WAB", name: "Westinghouse Air Brake Technologies", sector: "Industrial", type: "stock" },

  // Materials
  { ticker: "LIN", name: "Linde plc", sector: "Materials", type: "stock" },
  { ticker: "APD", name: "Air Products & Chemicals", sector: "Materials", type: "stock" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", type: "stock" },
  { ticker: "ECL", name: "Ecolab Inc.", sector: "Materials", type: "stock" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", type: "stock" },
  { ticker: "NEM", name: "Newmont Corporation", sector: "Materials", type: "stock" },
  { ticker: "NUE", name: "Nucor Corporation", sector: "Materials", type: "stock" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials", type: "stock" },
  { ticker: "CLF", name: "Cleveland-Cliffs", sector: "Materials", type: "stock" },
  { ticker: "AA", name: "Alcoa Corporation", sector: "Materials", type: "stock" },
  { ticker: "VMC", name: "Vulcan Materials", sector: "Materials", type: "stock" },
  { ticker: "MLM", name: "Martin Marietta Materials", sector: "Materials", type: "stock" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials", type: "stock" },
  { ticker: "ALB", name: "Albemarle Corporation", sector: "Materials", type: "stock" },
  { ticker: "BALL", name: "Ball Corporation", sector: "Materials", type: "stock" },

  // Utilities
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities", type: "stock" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities", type: "stock" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", type: "stock" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", type: "stock" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", type: "stock" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", type: "stock" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities", type: "stock" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities", type: "stock" },
  { ticker: "EXC", name: "Exelon Corporation", sector: "Utilities", type: "stock" },
  { ticker: "CEG", name: "Constellation Energy", sector: "Utilities", type: "stock" },
  { ticker: "VST", name: "Vistra Corp", sector: "Utilities", type: "stock" },
  { ticker: "PCG", name: "PG&E Corporation", sector: "Utilities", type: "stock" },

  // Telecom
  { ticker: "T", name: "AT&T Inc.", sector: "Telecom", type: "stock" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Telecom", type: "stock" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Telecom", type: "stock" },
  { ticker: "AMT", name: "American Tower", sector: "Telecom", type: "stock" },
  { ticker: "CCI", name: "Crown Castle International", sector: "Telecom", type: "stock" },
  { ticker: "SBAC", name: "SBA Communications", sector: "Telecom", type: "stock" },

  // REITs
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate", type: "stock" },
  { ticker: "O", name: "Realty Income Corporation", sector: "Real Estate", type: "stock" },
  { ticker: "WELL", name: "Welltower Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "DLR", name: "Digital Realty Trust", sector: "Real Estate", type: "stock" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "AVB", name: "AvalonBay Communities", sector: "Real Estate", type: "stock" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate", type: "stock" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate", type: "stock" },
  { ticker: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate", type: "stock" },

  // International Stocks - Europe
  { ticker: "ASML", name: "ASML Holding", sector: "Technology", type: "stock" },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", type: "stock" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", type: "stock" },
  { ticker: "SPOT", name: "Spotify Technology", sector: "Technology", type: "stock" },
  { ticker: "ARM", name: "Arm Holdings", sector: "Technology", type: "stock" },
  { ticker: "NVO", name: "Novo Nordisk", sector: "Healthcare", type: "stock" },
  { ticker: "AZN", name: "AstraZeneca", sector: "Healthcare", type: "stock" },
  { ticker: "GSK", name: "GSK plc", sector: "Healthcare", type: "stock" },
  { ticker: "SNY", name: "Sanofi SA", sector: "Healthcare", type: "stock" },
  { ticker: "SHEL", name: "Shell plc", sector: "Energy", type: "stock" },
  { ticker: "BP", name: "BP plc", sector: "Energy", type: "stock" },
  { ticker: "TTE", name: "TotalEnergies SE", sector: "Energy", type: "stock" },
  { ticker: "EQNR", name: "Equinor ASA", sector: "Energy", type: "stock" },
  { ticker: "UL", name: "Unilever plc", sector: "Consumer", type: "stock" },
  { ticker: "DEO", name: "Diageo plc", sector: "Consumer", type: "stock" },
  { ticker: "RACE", name: "Ferrari N.V.", sector: "Consumer", type: "stock" },
  { ticker: "LVMUY", name: "LVMH Moët Hennessy", sector: "Consumer", type: "stock" },
  { ticker: "HESAY", name: "Hermès International", sector: "Consumer", type: "stock" },
  { ticker: "PPRUY", name: "Kering SA", sector: "Consumer", type: "stock" },
  { ticker: "BUD", name: "Anheuser-Busch InBev", sector: "Consumer", type: "stock" },
  { ticker: "RIO", name: "Rio Tinto Group", sector: "Materials", type: "stock" },
  { ticker: "BHP", name: "BHP Group", sector: "Materials", type: "stock" },
  { ticker: "VALE", name: "Vale S.A.", sector: "Materials", type: "stock" },
  { ticker: "NXPI", name: "NXP Semiconductors", sector: "Technology", type: "stock" },
  { ticker: "STM", name: "STMicroelectronics", sector: "Technology", type: "stock" },
  { ticker: "SIE.DE", name: "Siemens AG", sector: "Industrial", type: "stock" },
  { ticker: "ALV.DE", name: "Allianz SE", sector: "Financial", type: "stock" },
  { ticker: "BAS.DE", name: "BASF SE", sector: "Materials", type: "stock" },
  { ticker: "DTE.DE", name: "Deutsche Telekom", sector: "Telecom", type: "stock" },
  { ticker: "AIR.PA", name: "Airbus SE", sector: "Defense", type: "stock" },
  { ticker: "OR.PA", name: "L'Oréal SA", sector: "Consumer", type: "stock" },
  { ticker: "SAN.PA", name: "Sanofi SA (Paris)", sector: "Healthcare", type: "stock" },
  { ticker: "MC.PA", name: "LVMH (Paris)", sector: "Consumer", type: "stock" },
  { ticker: "NESN.SW", name: "Nestlé SA", sector: "Consumer", type: "stock" },
  { ticker: "ROG.SW", name: "Roche Holding", sector: "Healthcare", type: "stock" },
  { ticker: "NOVN.SW", name: "Novartis AG", sector: "Healthcare", type: "stock" },
  { ticker: "ULVR.L", name: "Unilever (London)", sector: "Consumer", type: "stock" },
  { ticker: "HSBA.L", name: "HSBC Holdings", sector: "Financial", type: "stock" },
  { ticker: "AZN.L", name: "AstraZeneca (London)", sector: "Healthcare", type: "stock" },
  { ticker: "BARC.L", name: "Barclays PLC", sector: "Financial", type: "stock" },

  // International Stocks - IBEX 35 (Spain)
  { ticker: "SAN.MC", name: "Banco Santander", sector: "Financial", type: "stock" },
  { ticker: "BBVA.MC", name: "Banco Bilbao Vizcaya Argentaria", sector: "Financial", type: "stock" },
  { ticker: "TEF.MC", name: "Telefónica", sector: "Telecom", type: "stock" },
  { ticker: "IBE.MC", name: "Iberdrola", sector: "Utilities", type: "stock" },
  { ticker: "REP.MC", name: "Repsol", sector: "Energy", type: "stock" },
  { ticker: "AMS.MC", name: "Amadeus IT Group", sector: "Technology", type: "stock" },
  { ticker: "CABK.MC", name: "CaixaBank", sector: "Financial", type: "stock" },
  { ticker: "FER.MC", name: "Ferrovial", sector: "Industrial", type: "stock" },
  { ticker: "ENG.MC", name: "Enagás", sector: "Energy", type: "stock" },
  { ticker: "GRF.MC", name: "Grifols", sector: "Healthcare", type: "stock" },
  { ticker: "MAP.MC", name: "MAPFRE", sector: "Financial", type: "stock" },
  { ticker: "ACS.MC", name: "ACS Actividades", sector: "Industrial", type: "stock" },
  { ticker: "CLNX.MC", name: "Cellnex Telecom", sector: "Telecom", type: "stock" },
  { ticker: "MRL.MC", name: "Merlin Properties", sector: "Real Estate", type: "stock" },
  { ticker: "LOG.MC", name: "Logista", sector: "Industrial", type: "stock" },

  // International Stocks - Asia
  { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", sector: "Technology", type: "stock" },
  { ticker: "BABA", name: "Alibaba Group", sector: "Technology", type: "stock" },
  { ticker: "JD", name: "JD.com", sector: "Consumer", type: "stock" },
  { ticker: "PDD", name: "PDD Holdings (Temu)", sector: "Consumer", type: "stock" },
  { ticker: "BIDU", name: "Baidu Inc.", sector: "Technology", type: "stock" },
  { ticker: "NIO", name: "NIO Inc.", sector: "Consumer", type: "stock" },
  { ticker: "XPEV", name: "XPeng Inc.", sector: "Consumer", type: "stock" },
  { ticker: "LI", name: "Li Auto Inc.", sector: "Consumer", type: "stock" },
  { ticker: "NTES", name: "NetEase Inc.", sector: "Technology", type: "stock" },
  { ticker: "BILI", name: "Bilibili Inc.", sector: "Technology", type: "stock" },
  { ticker: "TME", name: "Tencent Music Entertainment", sector: "Technology", type: "stock" },
  { ticker: "WB", name: "Weibo Corporation", sector: "Technology", type: "stock" },
  { ticker: "ZTO", name: "ZTO Express", sector: "Industrial", type: "stock" },
  { ticker: "FUTU", name: "Futu Holdings", sector: "Financial", type: "stock" },
  { ticker: "TIGR", name: "UP Fintech Holding", sector: "Financial", type: "stock" },
  { ticker: "7203.T", name: "Toyota Motor Corporation", sector: "Consumer", type: "stock" },
  { ticker: "6758.T", name: "Sony Group Corporation", sector: "Technology", type: "stock" },
  { ticker: "9984.T", name: "SoftBank Group", sector: "Technology", type: "stock" },
  { ticker: "6861.T", name: "Keyence Corporation", sector: "Technology", type: "stock" },
  { ticker: "8306.T", name: "Mitsubishi UFJ Financial", sector: "Financial", type: "stock" },
  { ticker: "005930.KS", name: "Samsung Electronics", sector: "Technology", type: "stock" },
  { ticker: "000660.KS", name: "SK Hynix", sector: "Technology", type: "stock" },
  { ticker: "035420.KS", name: "NAVER Corporation", sector: "Technology", type: "stock" },
  { ticker: "035720.KS", name: "Kakao Corp", sector: "Technology", type: "stock" },
  { ticker: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", type: "stock" },
  { ticker: "TCS.NS", name: "Tata Consultancy Services", sector: "Technology", type: "stock" },
  { ticker: "INFY", name: "Infosys Limited", sector: "Technology", type: "stock" },
  { ticker: "HDB", name: "HDFC Bank", sector: "Financial", type: "stock" },
  { ticker: "WIT", name: "Wipro Limited", sector: "Technology", type: "stock" },

  // LATAM Stocks
  { ticker: "ITUB", name: "Itaú Unibanco", sector: "Financial", type: "stock" },
  { ticker: "BBD", name: "Banco Bradesco", sector: "Financial", type: "stock" },
  { ticker: "PBR", name: "Petrobras", sector: "Energy", type: "stock" },
  { ticker: "AMX", name: "América Móvil", sector: "Telecom", type: "stock" },
  { ticker: "BSMX", name: "Banco Santander México", sector: "Financial", type: "stock" },
  { ticker: "CEMEX", name: "CEMEX SAB", sector: "Materials", type: "stock" },
  { ticker: "SQM", name: "Sociedad Química y Minera de Chile", sector: "Materials", type: "stock" },
  { ticker: "VIST", name: "Vista Energy", sector: "Energy", type: "stock" },
  { ticker: "GGAL", name: "Grupo Financiero Galicia", sector: "Financial", type: "stock" },
  { ticker: "CRESY", name: "Cresud SACIF", sector: "Consumer", type: "stock" },

  // EV / Auto (additional)
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer", type: "stock" },
  { ticker: "RIVN", name: "Rivian Automotive", sector: "Consumer", type: "stock" },
  { ticker: "LCID", name: "Lucid Group", sector: "Consumer", type: "stock" },
  { ticker: "GM", name: "General Motors", sector: "Consumer", type: "stock" },
  { ticker: "F", name: "Ford Motor Company", sector: "Consumer", type: "stock" },
  { ticker: "TM", name: "Toyota Motor", sector: "Consumer", type: "stock" },
  { ticker: "HMC", name: "Honda Motor", sector: "Consumer", type: "stock" },
  { ticker: "STLA", name: "Stellantis N.V.", sector: "Consumer", type: "stock" },

  // Media / Entertainment
  { ticker: "DIS", name: "Walt Disney Company", sector: "Entertainment", type: "stock" },
  { ticker: "CMCSA", name: "Comcast Corporation", sector: "Entertainment", type: "stock" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Entertainment", type: "stock" },
  { ticker: "PARA", name: "Paramount Global", sector: "Entertainment", type: "stock" },
  { ticker: "ROKU", name: "Roku Inc.", sector: "Entertainment", type: "stock" },
  { ticker: "RBLX", name: "Roblox Corporation", sector: "Entertainment", type: "stock" },
  { ticker: "EA", name: "Electronic Arts", sector: "Entertainment", type: "stock" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Entertainment", type: "stock" },
  { ticker: "ATVI", name: "Activision Blizzard", sector: "Entertainment", type: "stock" },
  { ticker: "LYV", name: "Live Nation Entertainment", sector: "Entertainment", type: "stock" },
  { ticker: "IMAX", name: "IMAX Corporation", sector: "Entertainment", type: "stock" },
  { ticker: "MSGS", name: "Madison Square Garden Sports", sector: "Entertainment", type: "stock" },

  // Cannabis
  { ticker: "TLRY", name: "Tilray Brands", sector: "Cannabis", type: "stock" },
  { ticker: "CGC", name: "Canopy Growth", sector: "Cannabis", type: "stock" },
  { ticker: "ACB", name: "Aurora Cannabis", sector: "Cannabis", type: "stock" },
  { ticker: "SNDL", name: "SNDL Inc.", sector: "Cannabis", type: "stock" },

  // Space
  { ticker: "RKLB", name: "Rocket Lab USA", sector: "Aerospace", type: "stock" },
  { ticker: "LUNR", name: "Intuitive Machines", sector: "Aerospace", type: "stock" },
  { ticker: "ASTS", name: "AST SpaceMobile", sector: "Aerospace", type: "stock" },
  { ticker: "SPCE", name: "Virgin Galactic", sector: "Aerospace", type: "stock" },
  { ticker: "RDW", name: "Redwire Corporation", sector: "Aerospace", type: "stock" },

  // Insurance
  { ticker: "BRK.B", name: "Berkshire Hathaway", sector: "Financial", type: "stock" },
  { ticker: "AIG", name: "American International Group", sector: "Financial", type: "stock" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Financial", type: "stock" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Financial", type: "stock" },
  { ticker: "ALL", name: "Allstate Corporation", sector: "Financial", type: "stock" },
  { ticker: "TRV", name: "Travelers Companies", sector: "Financial", type: "stock" },
  { ticker: "PGR", name: "Progressive Corporation", sector: "Financial", type: "stock" },
  { ticker: "CB", name: "Chubb Limited", sector: "Financial", type: "stock" },
  { ticker: "AFL", name: "Aflac Incorporated", sector: "Financial", type: "stock" },
  { ticker: "CINF", name: "Cincinnati Financial", sector: "Financial", type: "stock" },

  // Food & Beverage
  { ticker: "KO", name: "Coca-Cola Company", sector: "Consumer", type: "stock" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer", type: "stock" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer", type: "stock" },
  { ticker: "CELH", name: "Celsius Holdings", sector: "Consumer", type: "stock" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer", type: "stock" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer", type: "stock" },
  { ticker: "TAP", name: "Molson Coors Beverage", sector: "Consumer", type: "stock" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer", type: "stock" },
  { ticker: "K", name: "Kellanova", sector: "Consumer", type: "stock" },
  { ticker: "HSY", name: "Hershey Company", sector: "Consumer", type: "stock" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer", type: "stock" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer", type: "stock" },
  { ticker: "SJM", name: "J.M. Smucker Company", sector: "Consumer", type: "stock" },
  { ticker: "CAG", name: "Conagra Brands", sector: "Consumer", type: "stock" },
  { ticker: "TSN", name: "Tyson Foods", sector: "Consumer", type: "stock" },

  // Miscellaneous Large-Cap
  { ticker: "V", name: "Visa Inc.", sector: "Financial", type: "stock" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financial", type: "stock" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare", type: "stock" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", type: "stock" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer", type: "stock" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer", type: "stock" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer", type: "stock" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer", type: "stock" },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer", type: "stock" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer", type: "stock" },
  { ticker: "SBUX", name: "Starbucks Corporation", sector: "Consumer", type: "stock" },
  { ticker: "MCD", name: "McDonald's Corporation", sector: "Consumer", type: "stock" },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer", type: "stock" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "LLY", name: "Eli Lilly and Company", sector: "Healthcare", type: "stock" },
  { ticker: "MRK", name: "Merck & Co.", sector: "Healthcare", type: "stock" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", type: "stock" },
];
