import { AssetEntry } from "./types";

export const bulkUSStocks: AssetEntry[] = [
  { ticker: "ABBV", name: "AbbVie", sector: "Healthcare", type: "stock" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", type: "stock" },
  { ticker: "AMGN", name: "Amgen", sector: "Healthcare", type: "stock" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "REGN", name: "Regeneron", sector: "Healthcare", type: "stock" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "stock" },
  { ticker: "ZTS", name: "Zoetis", sector: "Healthcare", type: "stock" },
  { ticker: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "DXCM", name: "DexCom", sector: "Healthcare", type: "stock" },
  { ticker: "IQV", name: "IQVIA Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Healthcare", type: "stock" },
  { ticker: "MTD", name: "Mettler-Toledo", sector: "Healthcare", type: "stock" },
  { ticker: "WAT", name: "Waters Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "A", name: "Agilent Technologies", sector: "Healthcare", type: "stock" },
  { ticker: "BIO", name: "Bio-Rad Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "PKI", name: "PerkinElmer", sector: "Healthcare", type: "stock" },
  { ticker: "HOLX", name: "Hologic", sector: "Healthcare", type: "stock" },
  { ticker: "STE", name: "STERIS", sector: "Healthcare", type: "stock" },
  { ticker: "TFX", name: "Teleflex", sector: "Healthcare", type: "stock" },
  { ticker: "PODD", name: "Insulet", sector: "Healthcare", type: "stock" },
  { ticker: "SWAV", name: "Shockwave Medical", sector: "Healthcare", type: "stock" },
  { ticker: "RVMD", name: "Revolution Medicines", sector: "Healthcare", type: "stock" },
  { ticker: "PCVX", name: "Vaxcyte", sector: "Healthcare", type: "stock" },
  { ticker: "RXRX", name: "Recursion Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "DAWN", name: "Day One Biopharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "SMMT", name: "Summit Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "SRRK", name: "Scholar Rock", sector: "Healthcare", type: "stock" },
  { ticker: "JANX", name: "Janux Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "HRMY", name: "Harmony Biosciences", sector: "Healthcare", type: "stock" },
  { ticker: "CORT", name: "Corcept Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "EXAS", name: "Exact Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "DNLI", name: "Denali Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "ARWR", name: "Arrowhead Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "RARE", name: "Ultragenyx Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "IONS", name: "Ionis Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "SRPT", name: "Sarepta Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "NBIX", name: "Neurocrine Biosciences", sector: "Healthcare", type: "stock" },
  { ticker: "UTHR", name: "United Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "HALO", name: "Halozyme Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "TGTX", name: "TG Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "IMVT", name: "Immunovant", sector: "Healthcare", type: "stock" },
  { ticker: "ARVN", name: "Arvinas", sector: "Healthcare", type: "stock" },
  { ticker: "KRTX", name: "Karuna Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "BHVN", name: "Biohaven", sector: "Healthcare", type: "stock" },
  { ticker: "FOLD", name: "Amicus Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "MYOV", name: "Myovant Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "MRTX", name: "Mirati Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "RCKT", name: "Rocket Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "CAT", name: "Caterpillar", sector: "Industrials", type: "stock" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials", type: "stock" },
  { ticker: "UNP", name: "Union Pacific", sector: "Industrials", type: "stock" },
  { ticker: "HON", name: "Honeywell", sector: "Industrials", type: "stock" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials", type: "stock" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrials", type: "stock" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials", type: "stock" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrials", type: "stock" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrials", type: "stock" },
  { ticker: "BA", name: "Boeing", sector: "Industrials", type: "stock" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials", type: "stock" },
  { ticker: "MMM", name: "3M Company", sector: "Industrials", type: "stock" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials", type: "stock" },
  { ticker: "ETN", name: "Eaton Corporation", sector: "Industrials", type: "stock" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials", type: "stock" },
  { ticker: "PH", name: "Parker-Hannifin", sector: "Industrials", type: "stock" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrials", type: "stock" },
  { ticker: "DOV", name: "Dover Corporation", sector: "Industrials", type: "stock" },
  { ticker: "IR", name: "Ingersoll Rand", sector: "Industrials", type: "stock" },
  { ticker: "FTV", name: "Fortive Corporation", sector: "Industrials", type: "stock" },
  { ticker: "AME", name: "AMETEK", sector: "Industrials", type: "stock" },
  { ticker: "OTIS", name: "Otis Worldwide", sector: "Industrials", type: "stock" },
  { ticker: "CARR", name: "Carrier Global", sector: "Industrials", type: "stock" },
  { ticker: "XYL", name: "Xylem", sector: "Industrials", type: "stock" },
  { ticker: "IEX", name: "IDEX Corporation", sector: "Industrials", type: "stock" },
  { ticker: "NDSN", name: "Nordson", sector: "Industrials", type: "stock" },
  { ticker: "RBC", name: "RBC Bearings", sector: "Industrials", type: "stock" },
  { ticker: "WMS", name: "Advanced Drainage", sector: "Industrials", type: "stock" },
  { ticker: "GNRC", name: "Generac Holdings", sector: "Industrials", type: "stock" },
  { ticker: "TT", name: "Trane Technologies", sector: "Industrials", type: "stock" },
  { ticker: "WSO", name: "Watsco", sector: "Industrials", type: "stock" },
  { ticker: "FAST", name: "Fastenal", sector: "Industrials", type: "stock" },
  { ticker: "ODFL", name: "Old Dominion Freight", sector: "Industrials", type: "stock" },
  { ticker: "SAIA", name: "Saia Inc", sector: "Industrials", type: "stock" },
  { ticker: "JBHT", name: "J.B. Hunt Transport", sector: "Industrials", type: "stock" },
  { ticker: "WERN", name: "Werner Enterprises", sector: "Industrials", type: "stock" },
  { ticker: "LSTR", name: "Landstar System", sector: "Industrials", type: "stock" },
  { ticker: "CHRW", name: "C.H. Robinson", sector: "Industrials", type: "stock" },
  { ticker: "EXPD", name: "Expeditors International", sector: "Industrials", type: "stock" },
  { ticker: "MATX", name: "Matson", sector: "Industrials", type: "stock" },
  { ticker: "HUBG", name: "Hub Group", sector: "Industrials", type: "stock" },
  { ticker: "XPO", name: "XPO Inc", sector: "Industrials", type: "stock" },
  { ticker: "GXO", name: "GXO Logistics", sector: "Industrials", type: "stock" },
  { ticker: "R", name: "Ryder System", sector: "Industrials", type: "stock" },
  { ticker: "PCAR", name: "PACCAR", sector: "Industrials", type: "stock" },
  { ticker: "CMI", name: "Cummins", sector: "Industrials", type: "stock" },
  { ticker: "OSK", name: "Oshkosh", sector: "Industrials", type: "stock" },
  { ticker: "TTC", name: "Toro Company", sector: "Industrials", type: "stock" },
  { ticker: "SWK", name: "Stanley Black & Decker", sector: "Industrials", type: "stock" },
  { ticker: "ALLE", name: "Allegion", sector: "Industrials", type: "stock" },
  { ticker: "AOS", name: "A.O. Smith", sector: "Industrials", type: "stock" },
  { ticker: "MAS", name: "Masco Corporation", sector: "Industrials", type: "stock" },
  { ticker: "XOM", name: "Exxon Mobil", sector: "Energy", type: "stock" },
  { ticker: "CVX", name: "Chevron", sector: "Energy", type: "stock" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", type: "stock" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy", type: "stock" },
  { ticker: "PXD", name: "Pioneer Natural Resources", sector: "Energy", type: "stock" },
  { ticker: "SLB", name: "Schlumberger", sector: "Energy", type: "stock" },
  { ticker: "HAL", name: "Halliburton", sector: "Energy", type: "stock" },
  { ticker: "BKR", name: "Baker Hughes", sector: "Energy", type: "stock" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", type: "stock" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", type: "stock" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", type: "stock" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", type: "stock" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy", type: "stock" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", type: "stock" },
  { ticker: "HES", name: "Hess Corporation", sector: "Energy", type: "stock" },
  { ticker: "MRO", name: "Marathon Oil", sector: "Energy", type: "stock" },
  { ticker: "APA", name: "APA Corporation", sector: "Energy", type: "stock" },
  { ticker: "CTRA", name: "Coterra Energy", sector: "Energy", type: "stock" },
  { ticker: "OVV", name: "Ovintiv", sector: "Energy", type: "stock" },
  { ticker: "EQT", name: "EQT Corporation", sector: "Energy", type: "stock" },
  { ticker: "AR", name: "Antero Resources", sector: "Energy", type: "stock" },
  { ticker: "RRC", name: "Range Resources", sector: "Energy", type: "stock" },
  { ticker: "SWN", name: "Southwestern Energy", sector: "Energy", type: "stock" },
  { ticker: "CHK", name: "Chesapeake Energy", sector: "Energy", type: "stock" },
  { ticker: "CNX", name: "CNX Resources", sector: "Energy", type: "stock" },
  { ticker: "MGY", name: "Magnolia Oil & Gas", sector: "Energy", type: "stock" },
  { ticker: "CHRD", name: "Chord Energy", sector: "Energy", type: "stock" },
  { ticker: "MTDR", name: "Matador Resources", sector: "Energy", type: "stock" },
  { ticker: "SM", name: "SM Energy", sector: "Energy", type: "stock" },
  { ticker: "TRGP", name: "Targa Resources", sector: "Energy", type: "stock" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy", type: "stock" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy", type: "stock" },
  { ticker: "OKE", name: "ONEOK", sector: "Energy", type: "stock" },
  { ticker: "ET", name: "Energy Transfer", sector: "Energy", type: "stock" },
  { ticker: "EPD", name: "Enterprise Products", sector: "Energy", type: "stock" },
  { ticker: "MPLX", name: "MPLX", sector: "Energy", type: "stock" },
  { ticker: "PAA", name: "Plains All American", sector: "Energy", type: "stock" },
  { ticker: "DKL", name: "Delek Logistics", sector: "Energy", type: "stock" },
  { ticker: "LIN", name: "Linde", sector: "Materials", type: "stock" },
  { ticker: "APD", name: "Air Products", sector: "Materials", type: "stock" },
  { ticker: "ECL", name: "Ecolab", sector: "Materials", type: "stock" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", type: "stock" },
  { ticker: "DD", name: "DuPont de Nemours", sector: "Materials", type: "stock" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials", type: "stock" },
  { ticker: "NUE", name: "Nucor", sector: "Materials", type: "stock" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials", type: "stock" },
  { ticker: "CLF", name: "Cleveland-Cliffs", sector: "Materials", type: "stock" },
  { ticker: "RS", name: "Reliance Steel", sector: "Materials", type: "stock" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", type: "stock" },
  { ticker: "NEM", name: "Newmont", sector: "Materials", type: "stock" },
  { ticker: "GOLD", name: "Barrick Gold", sector: "Materials", type: "stock" },
  { ticker: "AEM", name: "Agnico Eagle", sector: "Materials", type: "stock" },
  { ticker: "FNV", name: "Franco-Nevada", sector: "Materials", type: "stock" },
  { ticker: "WPM", name: "Wheaton Precious Metals", sector: "Materials", type: "stock" },
  { ticker: "RGLD", name: "Royal Gold", sector: "Materials", type: "stock" },
  { ticker: "KGC", name: "Kinross Gold", sector: "Materials", type: "stock" },
  { ticker: "AGI", name: "Alamos Gold", sector: "Materials", type: "stock" },
  { ticker: "EGO", name: "Eldorado Gold", sector: "Materials", type: "stock" },
  { ticker: "BHP", name: "BHP Group", sector: "Materials", type: "stock" },
  { ticker: "RIO", name: "Rio Tinto", sector: "Materials", type: "stock" },
  { ticker: "VALE", name: "Vale SA", sector: "Materials", type: "stock" },
  { ticker: "SCCO", name: "Southern Copper", sector: "Materials", type: "stock" },
  { ticker: "TECK", name: "Teck Resources", sector: "Materials", type: "stock" },
  { ticker: "CCJ", name: "Cameco", sector: "Materials", type: "stock" },
  { ticker: "LEU", name: "Centrus Energy", sector: "Materials", type: "stock" },
  { ticker: "MP", name: "MP Materials", sector: "Materials", type: "stock" },
  { ticker: "LAC", name: "Lithium Americas", sector: "Materials", type: "stock" },
  { ticker: "ALB", name: "Albemarle", sector: "Materials", type: "stock" },
  { ticker: "SQM", name: "Sociedad Química", sector: "Materials", type: "stock" },
  { ticker: "LTHM", name: "Livent", sector: "Materials", type: "stock" },
  { ticker: "VMC", name: "Vulcan Materials", sector: "Materials", type: "stock" },
  { ticker: "MLM", name: "Martin Marietta", sector: "Materials", type: "stock" },
  { ticker: "EXP", name: "Eagle Materials", sector: "Materials", type: "stock" },
  { ticker: "ITE", name: "Summit Materials", sector: "Materials", type: "stock" },
  { ticker: "CX", name: "CEMEX", sector: "Materials", type: "stock" },
  { ticker: "BCC", name: "Boise Cascade", sector: "Materials", type: "stock" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities", type: "stock" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities", type: "stock" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", type: "stock" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", type: "stock" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", type: "stock" },
  { ticker: "SRE", name: "Sempra", sector: "Utilities", type: "stock" },
  { ticker: "EXC", name: "Exelon", sector: "Utilities", type: "stock" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", type: "stock" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities", type: "stock" },
  { ticker: "WEC", name: "WEC Energy", sector: "Utilities", type: "stock" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities", type: "stock" },
  { ticker: "AEE", name: "Ameren", sector: "Utilities", type: "stock" },
  { ticker: "CMS", name: "CMS Energy", sector: "Utilities", type: "stock" },
  { ticker: "DTE", name: "DTE Energy", sector: "Utilities", type: "stock" },
  { ticker: "PPL", name: "PPL Corporation", sector: "Utilities", type: "stock" },
  { ticker: "FE", name: "FirstEnergy", sector: "Utilities", type: "stock" },
  { ticker: "ETR", name: "Entergy", sector: "Utilities", type: "stock" },
  { ticker: "EIX", name: "Edison International", sector: "Utilities", type: "stock" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities", type: "stock" },
  { ticker: "WTRG", name: "Essential Utilities", sector: "Utilities", type: "stock" },
  { ticker: "SJW", name: "SJW Group", sector: "Utilities", type: "stock" },
  { ticker: "MSEX", name: "Middlesex Water", sector: "Utilities", type: "stock" },
  { ticker: "YORW", name: "York Water", sector: "Utilities", type: "stock" },
  { ticker: "CWT", name: "California Water", sector: "Utilities", type: "stock" },
  { ticker: "NWN", name: "Northwest Natural", sector: "Utilities", type: "stock" },
  { ticker: "SR", name: "Spire", sector: "Utilities", type: "stock" },
  { ticker: "NJR", name: "New Jersey Resources", sector: "Utilities", type: "stock" },
  { ticker: "SWX", name: "Southwest Gas", sector: "Utilities", type: "stock" },
  { ticker: "OGS", name: "ONE Gas", sector: "Utilities", type: "stock" },
  { ticker: "NI", name: "NiSource", sector: "Utilities", type: "stock" },
  { ticker: "PLD", name: "Prologis", sector: "Real Estate", type: "stock" },
  { ticker: "AMT", name: "American Tower", sector: "Real Estate", type: "stock" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate", type: "stock" },
  { ticker: "EQIX", name: "Equinix", sector: "Real Estate", type: "stock" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate", type: "stock" },
  { ticker: "SPG", name: "Simon Property", sector: "Real Estate", type: "stock" },
  { ticker: "WELL", name: "Welltower", sector: "Real Estate", type: "stock" },
  { ticker: "DLR", name: "Digital Realty", sector: "Real Estate", type: "stock" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate", type: "stock" },
  { ticker: "AVB", name: "AvalonBay", sector: "Real Estate", type: "stock" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate", type: "stock" },
  { ticker: "ESS", name: "Essex Property", sector: "Real Estate", type: "stock" },
  { ticker: "MAA", name: "Mid-America Apartment", sector: "Real Estate", type: "stock" },
  { ticker: "UDR", name: "UDR Inc", sector: "Real Estate", type: "stock" },
  { ticker: "CPT", name: "Camden Property", sector: "Real Estate", type: "stock" },
  { ticker: "KIM", name: "Kimco Realty", sector: "Real Estate", type: "stock" },
  { ticker: "REG", name: "Regency Centers", sector: "Real Estate", type: "stock" },
  { ticker: "FRT", name: "Federal Realty", sector: "Real Estate", type: "stock" },
  { ticker: "HST", name: "Host Hotels", sector: "Real Estate", type: "stock" },
  { ticker: "RHP", name: "Ryman Hospitality", sector: "Real Estate", type: "stock" },
  { ticker: "PK", name: "Park Hotels", sector: "Real Estate", type: "stock" },
  { ticker: "APLE", name: "Apple Hospitality", sector: "Real Estate", type: "stock" },
  { ticker: "SHO", name: "Sunstone Hotel", sector: "Real Estate", type: "stock" },
  { ticker: "GLPI", name: "Gaming Leisure", sector: "Real Estate", type: "stock" },
  { ticker: "VICI", name: "VICI Properties", sector: "Real Estate", type: "stock" },
  { ticker: "EXR", name: "Extra Space Storage", sector: "Real Estate", type: "stock" },
  { ticker: "CUBE", name: "CubeSmart", sector: "Real Estate", type: "stock" },
  { ticker: "LSI", name: "Life Storage", sector: "Real Estate", type: "stock" },
  { ticker: "NSA", name: "National Storage", sector: "Real Estate", type: "stock" },
  { ticker: "STOR", name: "Store Capital", sector: "Real Estate", type: "stock" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer", type: "stock" },
  { ticker: "KO", name: "Coca-Cola", sector: "Consumer", type: "stock" },
  { ticker: "PEP", name: "PepsiCo", sector: "Consumer", type: "stock" },
  { ticker: "COST", name: "Costco", sector: "Consumer", type: "stock" },
  { ticker: "WMT", name: "Walmart", sector: "Consumer", type: "stock" },
  { ticker: "TGT", name: "Target", sector: "Consumer", type: "stock" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer", type: "stock" },
  { ticker: "LOW", name: "Lowe's", sector: "Consumer", type: "stock" },
  { ticker: "MCD", name: "McDonald's", sector: "Consumer", type: "stock" },
  { ticker: "SBUX", name: "Starbucks", sector: "Consumer", type: "stock" },
  { ticker: "NKE", name: "Nike", sector: "Consumer", type: "stock" },
  { ticker: "LULU", name: "Lululemon", sector: "Consumer", type: "stock" },
  { ticker: "EL", name: "Estée Lauder", sector: "Consumer", type: "stock" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer", type: "stock" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer", type: "stock" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer", type: "stock" },
  { ticker: "CLX", name: "Clorox", sector: "Consumer", type: "stock" },
  { ticker: "SJM", name: "J.M. Smucker", sector: "Consumer", type: "stock" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer", type: "stock" },
  { ticker: "K", name: "Kellogg's", sector: "Consumer", type: "stock" },
  { ticker: "HSY", name: "Hershey", sector: "Consumer", type: "stock" },
  { ticker: "MDLZ", name: "Mondelez", sector: "Consumer", type: "stock" },
  { ticker: "KHC", name: "Kraft Heinz", sector: "Consumer", type: "stock" },
  { ticker: "CAG", name: "Conagra Brands", sector: "Consumer", type: "stock" },
  { ticker: "CPB", name: "Campbell Soup", sector: "Consumer", type: "stock" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer", type: "stock" },
  { ticker: "TSN", name: "Tyson Foods", sector: "Consumer", type: "stock" },
  { ticker: "BG", name: "Bunge", sector: "Consumer", type: "stock" },
  { ticker: "ADM", name: "Archer-Daniels-Midland", sector: "Consumer", type: "stock" },
  { ticker: "FDP", name: "Fresh Del Monte", sector: "Consumer", type: "stock" },
  { ticker: "DOLE", name: "Dole", sector: "Consumer", type: "stock" },
  { ticker: "USFD", name: "US Foods", sector: "Consumer", type: "stock" },
  { ticker: "SYY", name: "Sysco", sector: "Consumer", type: "stock" },
  { ticker: "PFGC", name: "Performance Food", sector: "Consumer", type: "stock" },
  { ticker: "FIVE", name: "Five Below", sector: "Consumer", type: "stock" },
  { ticker: "DG", name: "Dollar General", sector: "Consumer", type: "stock" },
  { ticker: "DLTR", name: "Dollar Tree", sector: "Consumer", type: "stock" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer", type: "stock" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer", type: "stock" },
  { ticker: "BURL", name: "Burlington Stores", sector: "Consumer", type: "stock" },
  { ticker: "GPS", name: "Gap", sector: "Consumer", type: "stock" },
  { ticker: "ANF", name: "Abercrombie & Fitch", sector: "Consumer", type: "stock" },
  { ticker: "AEO", name: "American Eagle", sector: "Consumer", type: "stock" },
  { ticker: "URBN", name: "Urban Outfitters", sector: "Consumer", type: "stock" },
  { ticker: "RL", name: "Ralph Lauren", sector: "Consumer", type: "stock" },
  { ticker: "PVH", name: "PVH Corp", sector: "Consumer", type: "stock" },
  { ticker: "TPR", name: "Tapestry", sector: "Consumer", type: "stock" },
  { ticker: "CPRI", name: "Capri Holdings", sector: "Consumer", type: "stock" },
  { ticker: "HBI", name: "Hanesbrands", sector: "Consumer", type: "stock" },
  { ticker: "GIII", name: "G-III Apparel", sector: "Consumer", type: "stock" },
  { ticker: "OXM", name: "Oxford Industries", sector: "Consumer", type: "stock" },
  { ticker: "VFC", name: "VF Corporation", sector: "Consumer", type: "stock" },
  { ticker: "UAA", name: "Under Armour", sector: "Consumer", type: "stock" },
  { ticker: "COLM", name: "Columbia Sportswear", sector: "Consumer", type: "stock" },
  { ticker: "WWW", name: "Wolverine World Wide", sector: "Consumer", type: "stock" },
  { ticker: "CAL", name: "Caleres", sector: "Consumer", type: "stock" },
  { ticker: "FL", name: "Foot Locker", sector: "Consumer", type: "stock" },
  { ticker: "GPC", name: "Genuine Parts", sector: "Consumer", type: "stock" },
  { ticker: "AZO", name: "AutoZone", sector: "Consumer", type: "stock" },
  { ticker: "AAP", name: "Advance Auto Parts", sector: "Consumer", type: "stock" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer", type: "stock" },
  { ticker: "KMX", name: "CarMax", sector: "Consumer", type: "stock" },
  { ticker: "CVNA", name: "Carvana", sector: "Consumer", type: "stock" },
  { ticker: "AN", name: "AutoNation", sector: "Consumer", type: "stock" },
  { ticker: "LAD", name: "Lithia Motors", sector: "Consumer", type: "stock" },
  { ticker: "PAG", name: "Penske Automotive", sector: "Consumer", type: "stock" },
  { ticker: "SAH", name: "Sonic Automotive", sector: "Consumer", type: "stock" },
  { ticker: "ABG", name: "Asbury Automotive", sector: "Consumer", type: "stock" },
  { ticker: "AAPL", name: "Apple", sector: "Technology", type: "stock" },
  { ticker: "MSFT", name: "Microsoft", sector: "Technology", type: "stock" },
  { ticker: "NVDA", name: "NVIDIA", sector: "Technology", type: "stock" },
  { ticker: "GOOGL", name: "Alphabet Class A", sector: "Technology", type: "stock" },
  { ticker: "META", name: "Meta Platforms", sector: "Technology", type: "stock" },
  { ticker: "AVGO", name: "Broadcom", sector: "Technology", type: "stock" },
  { ticker: "ORCL", name: "Oracle", sector: "Technology", type: "stock" },
  { ticker: "CRM", name: "Salesforce", sector: "Technology", type: "stock" },
  { ticker: "ACN", name: "Accenture", sector: "Technology", type: "stock" },
  { ticker: "ADBE", name: "Adobe", sector: "Technology", type: "stock" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology", type: "stock" },
  { ticker: "INTC", name: "Intel", sector: "Technology", type: "stock" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", type: "stock" },
  { ticker: "QCOM", name: "Qualcomm", sector: "Technology", type: "stock" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology", type: "stock" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology", type: "stock" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology", type: "stock" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology", type: "stock" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology", type: "stock" },
  { ticker: "NXPI", name: "NXP Semiconductors", sector: "Technology", type: "stock" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", type: "stock" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology", type: "stock" },
  { ticker: "QRVO", name: "Qorvo", sector: "Technology", type: "stock" },
  { ticker: "MPWR", name: "Monolithic Power", sector: "Technology", type: "stock" },
  { ticker: "ENPH", name: "Enphase Energy", sector: "Technology", type: "stock" },
  { ticker: "SEDG", name: "SolarEdge Technologies", sector: "Technology", type: "stock" },
  { ticker: "FSLR", name: "First Solar", sector: "Technology", type: "stock" },
  { ticker: "WOLF", name: "Wolfspeed", sector: "Technology", type: "stock" },
  { ticker: "MBLY", name: "Mobileye", sector: "Technology", type: "stock" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "Technology", type: "stock" },
  { ticker: "DELL", name: "Dell Technologies", sector: "Technology", type: "stock" },
  { ticker: "HPQ", name: "HP Inc", sector: "Technology", type: "stock" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", type: "stock" },
  { ticker: "NTAP", name: "NetApp", sector: "Technology", type: "stock" },
  { ticker: "PSTG", name: "Pure Storage", sector: "Technology", type: "stock" },
  { ticker: "WDC", name: "Western Digital", sector: "Technology", type: "stock" },
  { ticker: "STX", name: "Seagate Technology", sector: "Technology", type: "stock" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", type: "stock" },
  { ticker: "JNPR", name: "Juniper Networks", sector: "Technology", type: "stock" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology", type: "stock" },
  { ticker: "FFIV", name: "F5 Inc", sector: "Technology", type: "stock" },
  { ticker: "UI", name: "Ubiquiti", sector: "Technology", type: "stock" },
  { ticker: "CALX", name: "Calix", sector: "Technology", type: "stock" },
  { ticker: "CIEN", name: "Ciena", sector: "Technology", type: "stock" },
  { ticker: "INFN", name: "Infinera", sector: "Technology", type: "stock" },
  { ticker: "LITE", name: "Lumentum", sector: "Technology", type: "stock" },
  { ticker: "VIAV", name: "Viavi Solutions", sector: "Technology", type: "stock" },
  { ticker: "NOW", name: "ServiceNow", sector: "Technology", type: "stock" },
  { ticker: "WDAY", name: "Workday", sector: "Technology", type: "stock" },
  { ticker: "VEEV", name: "Veeva Systems", sector: "Technology", type: "stock" },
  { ticker: "PAYC", name: "Paycom Software", sector: "Technology", type: "stock" },
  { ticker: "PAYX", name: "Paychex", sector: "Technology", type: "stock" },
  { ticker: "ADP", name: "Automatic Data Processing", sector: "Technology", type: "stock" },
  { ticker: "FIS", name: "Fidelity National", sector: "Technology", type: "stock" },
  { ticker: "FISV", name: "Fiserv", sector: "Technology", type: "stock" },
  { ticker: "GPN", name: "Global Payments", sector: "Technology", type: "stock" },
  { ticker: "JKHY", name: "Jack Henry", sector: "Technology", type: "stock" },
  { ticker: "WU", name: "Western Union", sector: "Technology", type: "stock" },
  { ticker: "VRSN", name: "VeriSign", sector: "Technology", type: "stock" },
  { ticker: "GDDY", name: "GoDaddy", sector: "Technology", type: "stock" },
  { ticker: "ZM", name: "Zoom Video", sector: "Technology", type: "stock" },
  { ticker: "DBX", name: "Dropbox", sector: "Technology", type: "stock" },
  { ticker: "BOX", name: "Box Inc", sector: "Technology", type: "stock" },
  { ticker: "SUMO", name: "Sumo Logic", sector: "Technology", type: "stock" },
  { ticker: "NEWR", name: "New Relic", sector: "Technology", type: "stock" },
  { ticker: "SPT", name: "Sprout Social", sector: "Technology", type: "stock" },
  { ticker: "HCP", name: "HashiCorp", sector: "Technology", type: "stock" },
  { ticker: "SNOW", name: "Snowflake", sector: "Technology", type: "stock" },
  { ticker: "PLTR", name: "Palantir", sector: "Technology", type: "stock" },
  { ticker: "AI", name: "C3.ai", sector: "Technology", type: "stock" },
  { ticker: "BBAI", name: "BigBear.ai", sector: "Technology", type: "stock" },
  { ticker: "PRGS", name: "Progress Software", sector: "Technology", type: "stock" },
  { ticker: "MANH", name: "Manhattan Associates", sector: "Technology", type: "stock" },
  { ticker: "FICO", name: "Fair Isaac", sector: "Technology", type: "stock" },
  { ticker: "TYL", name: "Tyler Technologies", sector: "Technology", type: "stock" },
  { ticker: "GWRE", name: "Guidewire Software", sector: "Technology", type: "stock" },
  { ticker: "PCTY", name: "Paylocity", sector: "Technology", type: "stock" },
  { ticker: "GOOG", name: "Alphabet Class C", sector: "Communication", type: "stock" },
  { ticker: "DIS", name: "Walt Disney", sector: "Communication", type: "stock" },
  { ticker: "CMCSA", name: "Comcast", sector: "Communication", type: "stock" },
  { ticker: "NFLX", name: "Netflix", sector: "Communication", type: "stock" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Communication", type: "stock" },
  { ticker: "VZ", name: "Verizon", sector: "Communication", type: "stock" },
  { ticker: "T", name: "AT&T", sector: "Communication", type: "stock" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication", type: "stock" },
  { ticker: "PARA", name: "Paramount Global", sector: "Communication", type: "stock" },
  { ticker: "WBD", name: "Warner Bros Discovery", sector: "Communication", type: "stock" },
  { ticker: "FOX", name: "Fox Corporation", sector: "Communication", type: "stock" },
  { ticker: "FOXA", name: "Fox Corporation Class A", sector: "Communication", type: "stock" },
  { ticker: "NWSA", name: "News Corporation", sector: "Communication", type: "stock" },
  { ticker: "IPG", name: "Interpublic", sector: "Communication", type: "stock" },
  { ticker: "OMC", name: "Omnicom Group", sector: "Communication", type: "stock" },
  { ticker: "MGNI", name: "Magnite", sector: "Communication", type: "stock" },
  { ticker: "PUBM", name: "PubMatic", sector: "Communication", type: "stock" },
  { ticker: "DSP", name: "Viant Technology", sector: "Communication", type: "stock" },
  { ticker: "ZETA", name: "Zeta Global", sector: "Communication", type: "stock" },
  { ticker: "CARG", name: "CarGurus", sector: "Communication", type: "stock" },
  { ticker: "ANGI", name: "Angi Inc", sector: "Communication", type: "stock" },
  { ticker: "YELP", name: "Yelp", sector: "Communication", type: "stock" },
  { ticker: "TRIP", name: "Tripadvisor", sector: "Communication", type: "stock" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Communication", type: "stock" },
  { ticker: "EXPE", name: "Expedia Group", sector: "Communication", type: "stock" },
  { ticker: "ABNB", name: "Airbnb", sector: "Communication", type: "stock" },
  { ticker: "MMYT", name: "MakeMyTrip", sector: "Communication", type: "stock" },
  { ticker: "TCOM", name: "Trip.com", sector: "Communication", type: "stock" },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Finance", type: "stock" },
  { ticker: "BAC", name: "Bank of America", sector: "Finance", type: "stock" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Finance", type: "stock" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Finance", type: "stock" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Finance", type: "stock" },
  { ticker: "C", name: "Citigroup", sector: "Finance", type: "stock" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Finance", type: "stock" },
  { ticker: "BLK", name: "BlackRock", sector: "Finance", type: "stock" },
  { ticker: "SPGI", name: "S&P Global", sector: "Finance", type: "stock" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Finance", type: "stock" },
  { ticker: "CME", name: "CME Group", sector: "Finance", type: "stock" },
  { ticker: "NDAQ", name: "Nasdaq", sector: "Finance", type: "stock" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Finance", type: "stock" },
  { ticker: "MCO", name: "Moody's", sector: "Finance", type: "stock" },
  { ticker: "MSCI", name: "MSCI", sector: "Finance", type: "stock" },
  { ticker: "FDS", name: "FactSet", sector: "Finance", type: "stock" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Finance", type: "stock" },
  { ticker: "TRV", name: "Travelers", sector: "Finance", type: "stock" },
  { ticker: "ALL", name: "Allstate", sector: "Finance", type: "stock" },
  { ticker: "PGR", name: "Progressive", sector: "Finance", type: "stock" },
  { ticker: "MET", name: "MetLife", sector: "Finance", type: "stock" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Finance", type: "stock" },
  { ticker: "AIG", name: "American International", sector: "Finance", type: "stock" },
  { ticker: "ACGL", name: "Arch Capital", sector: "Finance", type: "stock" },
  { ticker: "CINF", name: "Cincinnati Financial", sector: "Finance", type: "stock" },
  { ticker: "L", name: "Loews", sector: "Finance", type: "stock" },
  { ticker: "GL", name: "Globe Life", sector: "Finance", type: "stock" },
  { ticker: "MMC", name: "Marsh McLennan", sector: "Finance", type: "stock" },
  { ticker: "AON", name: "Aon", sector: "Finance", type: "stock" },
  { ticker: "BRO", name: "Brown & Brown", sector: "Finance", type: "stock" },
  { ticker: "AJG", name: "Arthur J. Gallagher", sector: "Finance", type: "stock" },
  { ticker: "WTW", name: "Willis Towers Watson", sector: "Finance", type: "stock" },
  { ticker: "V", name: "Visa", sector: "Finance", type: "stock" },
  { ticker: "MA", name: "Mastercard", sector: "Finance", type: "stock" },
  { ticker: "AXP", name: "American Express", sector: "Finance", type: "stock" },
  { ticker: "DFS", name: "Discover Financial", sector: "Finance", type: "stock" },
  { ticker: "SYF", name: "Synchrony Financial", sector: "Finance", type: "stock" },
  { ticker: "ALLY", name: "Ally Financial", sector: "Finance", type: "stock" },
  { ticker: "COF", name: "Capital One", sector: "Finance", type: "stock" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Finance", type: "stock" },
  { ticker: "PNC", name: "PNC Financial", sector: "Finance", type: "stock" },
  { ticker: "TFC", name: "Truist Financial", sector: "Finance", type: "stock" },
  { ticker: "MTB", name: "M&T Bank", sector: "Finance", type: "stock" },
  { ticker: "FITB", name: "Fifth Third", sector: "Finance", type: "stock" },
  { ticker: "BK", name: "BNY Mellon", sector: "Finance", type: "stock" },
  { ticker: "STT", name: "State Street", sector: "Finance", type: "stock" },
  { ticker: "NTRS", name: "Northern Trust", sector: "Finance", type: "stock" },
  { ticker: "MKTX", name: "MarketAxess", sector: "Finance", type: "stock" },
  { ticker: "LPLA", name: "LPL Financial", sector: "Finance", type: "stock" },
  { ticker: "RJF", name: "Raymond James", sector: "Finance", type: "stock" },
  { ticker: "SF", name: "Stifel Financial", sector: "Finance", type: "stock" },
  { ticker: "JEF", name: "Jefferies Financial", sector: "Finance", type: "stock" },
  { ticker: "IBKR", name: "Interactive Brokers", sector: "Finance", type: "stock" },
  { ticker: "VIRT", name: "Virtu Financial", sector: "Finance", type: "stock" },
  { ticker: "SNEX", name: "StoneX Group", sector: "Finance", type: "stock" },
  { ticker: "TROW", name: "T. Rowe Price", sector: "Finance", type: "stock" },
  { ticker: "BEN", name: "Franklin Resources", sector: "Finance", type: "stock" },
  { ticker: "IVZ", name: "Invesco", sector: "Finance", type: "stock" },
  { ticker: "WDR", name: "Waddell & Reed", sector: "Finance", type: "stock" },
  { ticker: "AMG", name: "Affiliated Managers", sector: "Finance", type: "stock" },
  { ticker: "APAM", name: "Artisan Partners", sector: "Finance", type: "stock" },
  { ticker: "VCTR", name: "Victory Capital", sector: "Finance", type: "stock" },
];
