import { AssetEntry } from "./types";

export const crypto: AssetEntry[] = [
  { ticker: "BTCUSD", name: "Bitcoin", sector: "Crypto", type: "crypto" },
  { ticker: "ETHUSD", name: "Ethereum", sector: "Crypto", type: "crypto" },
  { ticker: "SOLUSD", name: "Solana", sector: "Crypto", type: "crypto" },
  { ticker: "ADAUSD", name: "Cardano", sector: "Crypto", type: "crypto" },
  { ticker: "DOTUSD", name: "Polkadot", sector: "Crypto", type: "crypto" },
  { ticker: "AVAXUSD", name: "Avalanche", sector: "Crypto", type: "crypto" },
  { ticker: "LINKUSD", name: "Chainlink", sector: "Crypto", type: "crypto" },
  { ticker: "MATICUSD", name: "Polygon", sector: "Crypto", type: "crypto" },
  { ticker: "XRPUSD", name: "XRP", sector: "Crypto", type: "crypto" },
  { ticker: "DOGEUSD", name: "Dogecoin", sector: "Crypto", type: "crypto" },
  { ticker: "BNBUSD", name: "BNB", sector: "Crypto", type: "crypto" },
  { ticker: "TONUSD", name: "Toncoin", sector: "Crypto", type: "crypto" },
  { ticker: "TRXUSD", name: "TRON", sector: "Crypto", type: "crypto" },
  { ticker: "NEARUSD", name: "NEAR Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SUIUSD", name: "Sui", sector: "Crypto", type: "crypto" },
  { ticker: "UNIUSD", name: "Uniswap", sector: "Crypto", type: "crypto" },
  { ticker: "AAVEUSD", name: "Aave", sector: "Crypto", type: "crypto" },
  { ticker: "ATOMUSD", name: "Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "XLMUSD", name: "Stellar", sector: "Crypto", type: "crypto" },
  { ticker: "ALGOUSD", name: "Algorand", sector: "Crypto", type: "crypto" },
  { ticker: "ICPUSD", name: "Internet Computer", sector: "Crypto", type: "crypto" },
  { ticker: "FILUSD", name: "Filecoin", sector: "Crypto", type: "crypto" },
  { ticker: "APTUSD", name: "Aptos", sector: "Crypto", type: "crypto" },
  { ticker: "ARBUSD", name: "Arbitrum", sector: "Crypto", type: "crypto" },
  { ticker: "OPUSD", name: "Optimism", sector: "Crypto", type: "crypto" },
  { ticker: "LTCUSD", name: "Litecoin", sector: "Crypto", type: "crypto" },
  { ticker: "BCHUSD", name: "Bitcoin Cash", sector: "Crypto", type: "crypto" },
  { ticker: "ETCUSD", name: "Ethereum Classic", sector: "Crypto", type: "crypto" },
  { ticker: "HBARUSD", name: "Hedera", sector: "Crypto", type: "crypto" },
  { ticker: "VETUSD", name: "VeChain", sector: "Crypto", type: "crypto" },
  { ticker: "FTMUSD", name: "Fantom", sector: "Crypto", type: "crypto" },
  { ticker: "SANDUSD", name: "The Sandbox", sector: "Crypto", type: "crypto" },
  { ticker: "MANAUSD", name: "Decentraland", sector: "Crypto", type: "crypto" },
  { ticker: "AXSUSD", name: "Axie Infinity", sector: "Crypto", type: "crypto" },
  { ticker: "GALAUSD", name: "Gala", sector: "Crypto", type: "crypto" },
  { ticker: "ENJUSD", name: "Enjin Coin", sector: "Crypto", type: "crypto" },
  { ticker: "GRTUSD", name: "The Graph", sector: "Crypto", type: "crypto" },
  { ticker: "MKRUSD", name: "Maker", sector: "Crypto", type: "crypto" },
  { ticker: "COMPUSD", name: "Compound", sector: "Crypto", type: "crypto" },
  { ticker: "SNXUSD", name: "Synthetix", sector: "Crypto", type: "crypto" },
  { ticker: "CRVUSD", name: "Curve DAO", sector: "Crypto", type: "crypto" },
  { ticker: "LDOUSD", name: "Lido DAO", sector: "Crypto", type: "crypto" },
  { ticker: "INJUSD", name: "Injective", sector: "Crypto", type: "crypto" },
  { ticker: "SEIUSD", name: "Sei", sector: "Crypto", type: "crypto" },
  { ticker: "TIAUSD", name: "Celestia", sector: "Crypto", type: "crypto" },
  { ticker: "PYTHUSD", name: "Pyth Network", sector: "Crypto", type: "crypto" },
  { ticker: "JITOZUSD", name: "Jito", sector: "Crypto", type: "crypto" },
  { ticker: "JUPUSD", name: "Jupiter", sector: "Crypto", type: "crypto" },
  { ticker: "WUSD", name: "Wormhole", sector: "Crypto", type: "crypto" },
  { ticker: "STXUSD", name: "Stacks", sector: "Crypto", type: "crypto" },
  { ticker: "RUNEUSD", name: "THORChain", sector: "Crypto", type: "crypto" },
  { ticker: "PEPEUSD", name: "Pepe", sector: "Crypto", type: "crypto" },
  { ticker: "SHIBUSD", name: "Shiba Inu", sector: "Crypto", type: "crypto" },
  { ticker: "FLOKUSD", name: "Floki", sector: "Crypto", type: "crypto" },
  { ticker: "WIFUSD", name: "dogwifhat", sector: "Crypto", type: "crypto" },
  { ticker: "BONKUSD", name: "Bonk", sector: "Crypto", type: "crypto" },
  { ticker: "RENDERUSD", name: "Render", sector: "Crypto", type: "crypto" },
  { ticker: "FETUSD", name: "Fetch.ai", sector: "Crypto", type: "crypto" },
  { ticker: "OCEANUSD", name: "Ocean Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "THETAUSD", name: "Theta Network", sector: "Crypto", type: "crypto" },
  { ticker: "KASUSD", name: "Kaspa", sector: "Crypto", type: "crypto" },
  { ticker: "QNTUSD", name: "Quant", sector: "Crypto", type: "crypto" },
  { ticker: "EGLDUSD", name: "MultiversX", sector: "Crypto", type: "crypto" },
  { ticker: "ROSEUSD", name: "Oasis Network", sector: "Crypto", type: "crypto" },
  { ticker: "MINAUSD", name: "Mina Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FLOWUSD", name: "Flow", sector: "Crypto", type: "crypto" },
  { ticker: "ZILUSD", name: "Zilliqa", sector: "Crypto", type: "crypto" },
  { ticker: "IOTAUSD", name: "IOTA", sector: "Crypto", type: "crypto" },
  { ticker: "XTZUSD", name: "Tezos", sector: "Crypto", type: "crypto" },
  { ticker: "EOSUSD", name: "EOS", sector: "Crypto", type: "crypto" },
  { ticker: "NEOUSD", name: "NEO", sector: "Crypto", type: "crypto" },
  { ticker: "XMRUSD", name: "Monero", sector: "Crypto", type: "crypto" },
  { ticker: "ZECUSD", name: "Zcash", sector: "Crypto", type: "crypto" },
  { ticker: "DASHUSD", name: "Dash", sector: "Crypto", type: "crypto" },
  { ticker: "ONDOUSD", name: "Ondo Finance", sector: "Crypto", type: "crypto" },
  { ticker: "PENDLEUSD", name: "Pendle", sector: "Crypto", type: "crypto" },
  { ticker: "ENAUSD", name: "Ethena", sector: "Crypto", type: "crypto" },
  { ticker: "EIGENUSD", name: "EigenLayer", sector: "Crypto", type: "crypto" },
  { ticker: "MODEUSD", name: "Mode Network", sector: "Crypto", type: "crypto" },
  { ticker: "BLASTUSD", name: "Blast", sector: "Crypto", type: "crypto" },
];
