import { AssetEntry } from "./types";

const mexicoStocks: AssetEntry[] = [
  { ticker: "AMXL.MX", name: "América Móvil", sector: "Telecom", type: "stock" },
  { ticker: "FEMSAUBD.MX", name: "FEMSA", sector: "Consumer", type: "stock" },
  { ticker: "WALMEX.MX", name: "Walmart de México", sector: "Consumer", type: "stock" },
  { ticker: "GFNORTEO.MX", name: "Banorte", sector: "Finance", type: "stock" },
  { ticker: "TLEVISACPO.MX", name: "Televisa", sector: "Communication", type: "stock" },
  { ticker: "CEMEXCPO.MX", name: "CEMEX", sector: "Materials", type: "stock" },
  { ticker: "BIMBOA.MX", name: "Grupo Bimbo", sector: "Consumer", type: "stock" },
  { ticker: "GMEXICOB.MX", name: "Grupo México", sector: "Materials", type: "stock" },
  { ticker: "ALPEKA.MX", name: "Alpek", sector: "Materials", type: "stock" },
  { ticker: "GRUMAB.MX", name: "Gruma", sector: "Consumer", type: "stock" },
  { ticker: "ALSEA.MX", name: "Alsea", sector: "Consumer", type: "stock" },
  { ticker: "OMAB.MX", name: "OMA", sector: "Industrials", type: "stock" },
  { ticker: "GAPB.MX", name: "GAP", sector: "Industrials", type: "stock" },
  { ticker: "ASURB.MX", name: "ASUR", sector: "Industrials", type: "stock" },
  { ticker: "KIMBERA.MX", name: "Kimberly-Clark Mx", sector: "Consumer", type: "stock" },
  { ticker: "LIVEPOLC-1.MX", name: "Liverpool", sector: "Consumer", type: "stock" },
  { ticker: "ELEKTRA.MX", name: "Elektra", sector: "Consumer", type: "stock" },
  { ticker: "MEGACPO.MX", name: "Megacable", sector: "Communication", type: "stock" },
  { ticker: "PINFRA.MX", name: "PINFRA", sector: "Industrials", type: "stock" },
  { ticker: "GCARSOA1.MX", name: "Grupo Carso", sector: "Industrials", type: "stock" },
  { ticker: "AC.MX", name: "Arca Continental", sector: "Consumer", type: "stock" },
  { ticker: "ORBIA.MX", name: "Orbia", sector: "Materials", type: "stock" },
  { ticker: "PE&OLES.MX", name: "Peñoles", sector: "Materials", type: "stock" },
  { ticker: "SITESB-1.MX", name: "Sites", sector: "Communication", type: "stock" },
  { ticker: "GENTERA.MX", name: "Gentera", sector: "Finance", type: "stock" },
  { ticker: "BOLSAA.MX", name: "Bolsa Mexicana", sector: "Finance", type: "stock" },
  { ticker: "CABORSA.MX", name: "Cabo", sector: "Finance", type: "stock" },
  { ticker: "RA.MX", name: "Regional", sector: "Finance", type: "stock" },
  { ticker: "Q.MX", name: "Qualitas", sector: "Finance", type: "stock" },
  { ticker: "ABORSA.MX", name: "ABM", sector: "Finance", type: "stock" },
];

const brazilStocks: AssetEntry[] = [
  { ticker: "PETR4.SA", name: "Petrobras PN", sector: "Energy", type: "stock" },
  { ticker: "VALE3.SA", name: "Vale", sector: "Materials", type: "stock" },
  { ticker: "ITUB4.SA", name: "Itaú Unibanco", sector: "Finance", type: "stock" },
  { ticker: "BBDC4.SA", name: "Bradesco", sector: "Finance", type: "stock" },
  { ticker: "ABEV3.SA", name: "Ambev", sector: "Consumer", type: "stock" },
  { ticker: "B3SA3.SA", name: "B3", sector: "Finance", type: "stock" },
  { ticker: "WEGE3.SA", name: "WEG", sector: "Industrials", type: "stock" },
  { ticker: "RENT3.SA", name: "Localiza", sector: "Consumer", type: "stock" },
  { ticker: "BBAS3.SA", name: "Banco do Brasil", sector: "Finance", type: "stock" },
  { ticker: "SUZB3.SA", name: "Suzano", sector: "Materials", type: "stock" },
  { ticker: "JBSS3.SA", name: "JBS", sector: "Consumer", type: "stock" },
  { ticker: "RAIL3.SA", name: "Rumo", sector: "Industrials", type: "stock" },
  { ticker: "HAPV3.SA", name: "Hapvida", sector: "Healthcare", type: "stock" },
  { ticker: "RDOR3.SA", name: "Rede D'Or", sector: "Healthcare", type: "stock" },
  { ticker: "LREN3.SA", name: "Lojas Renner", sector: "Consumer", type: "stock" },
  { ticker: "GGBR4.SA", name: "Gerdau", sector: "Materials", type: "stock" },
  { ticker: "CSNA3.SA", name: "CSN", sector: "Materials", type: "stock" },
  { ticker: "MGLU3.SA", name: "Magazine Luiza", sector: "Consumer", type: "stock" },
  { ticker: "TOTS3.SA", name: "TOTVS", sector: "Technology", type: "stock" },
  { ticker: "CIEL3.SA", name: "Cielo", sector: "Technology", type: "stock" },
  { ticker: "SBSP3.SA", name: "Sabesp", sector: "Utilities", type: "stock" },
  { ticker: "CMIG4.SA", name: "CEMIG", sector: "Utilities", type: "stock" },
  { ticker: "ELET3.SA", name: "Eletrobras", sector: "Utilities", type: "stock" },
  { ticker: "TAEE11.SA", name: "Taesa", sector: "Utilities", type: "stock" },
  { ticker: "CCRO3.SA", name: "CCR", sector: "Industrials", type: "stock" },
  { ticker: "EQTL3.SA", name: "Equatorial", sector: "Utilities", type: "stock" },
  { ticker: "VIVT3.SA", name: "Telefônica Brasil", sector: "Telecom", type: "stock" },
  { ticker: "KLBN11.SA", name: "Klabin", sector: "Materials", type: "stock" },
  { ticker: "CYRE3.SA", name: "Cyrela", sector: "Real Estate", type: "stock" },
  { ticker: "MRVE3.SA", name: "MRV", sector: "Real Estate", type: "stock" },
  { ticker: "PRIO3.SA", name: "PRIO", sector: "Energy", type: "stock" },
  { ticker: "CSAN3.SA", name: "Cosan", sector: "Energy", type: "stock" },
  { ticker: "AMER3.SA", name: "Americanas", sector: "Consumer", type: "stock" },
  { ticker: "EMBR3.SA", name: "Embraer", sector: "Industrials", type: "stock" },
  { ticker: "AZUL4.SA", name: "Azul", sector: "Industrials", type: "stock" },
  { ticker: "COGN3.SA", name: "Cogna", sector: "Consumer", type: "stock" },
  { ticker: "YDUQ3.SA", name: "Yduqs", sector: "Consumer", type: "stock" },
  { ticker: "NTCO3.SA", name: "Natura", sector: "Consumer", type: "stock" },
  { ticker: "BRFS3.SA", name: "BRF", sector: "Consumer", type: "stock" },
  { ticker: "MRFG3.SA", name: "Marfrig", sector: "Consumer", type: "stock" },
];

const south_africaStocks: AssetEntry[] = [
  { ticker: "NPN.JO", name: "Naspers", sector: "Technology", type: "stock" },
  { ticker: "SOL.JO", name: "Sasol", sector: "Energy", type: "stock" },
  { ticker: "SBK.JO", name: "Standard Bank", sector: "Finance", type: "stock" },
  { ticker: "FSR.JO", name: "FirstRand", sector: "Finance", type: "stock" },
  { ticker: "AGL.JO", name: "Anglo American Plc", sector: "Materials", type: "stock" },
  { ticker: "BHP.JO", name: "BHP Group", sector: "Materials", type: "stock" },
  { ticker: "GLN.JO", name: "Glencore", sector: "Materials", type: "stock" },
  { ticker: "AMS.JO", name: "Anglo American Platinum", sector: "Materials", type: "stock" },
  { ticker: "IMP.JO", name: "Impala Platinum", sector: "Materials", type: "stock" },
  { ticker: "SSW.JO", name: "Sibanye-Stillwater", sector: "Materials", type: "stock" },
  { ticker: "MTN.JO", name: "MTN Group", sector: "Telecom", type: "stock" },
  { ticker: "VOD.JO", name: "Vodacom Group", sector: "Telecom", type: "stock" },
  { ticker: "SHP.JO", name: "Shoprite", sector: "Consumer", type: "stock" },
  { ticker: "BTI.JO", name: "British American Tobacco", sector: "Consumer", type: "stock" },
  { ticker: "ABG.JO", name: "Absa Group", sector: "Finance", type: "stock" },
  { ticker: "NED.JO", name: "Nedbank", sector: "Finance", type: "stock" },
  { ticker: "CPI.JO", name: "Capitec", sector: "Finance", type: "stock" },
  { ticker: "DSY.JO", name: "Discovery", sector: "Finance", type: "stock" },
  { ticker: "SLM.JO", name: "Sanlam", sector: "Finance", type: "stock" },
  { ticker: "INP.JO", name: "Investec", sector: "Finance", type: "stock" },
  { ticker: "BID.JO", name: "Bid Corp", sector: "Consumer", type: "stock" },
  { ticker: "CFR.JO", name: "Richemont", sector: "Consumer", type: "stock" },
  { ticker: "MNP.JO", name: "Mondi", sector: "Materials", type: "stock" },
  { ticker: "REM.JO", name: "Remgro", sector: "Industrials", type: "stock" },
  { ticker: "APN.JO", name: "Aspen Pharmacare", sector: "Healthcare", type: "stock" },
  { ticker: "MCG.JO", name: "MultiChoice", sector: "Communication", type: "stock" },
  { ticker: "TBS.JO", name: "Tiger Brands", sector: "Consumer", type: "stock" },
  { ticker: "PIK.JO", name: "Pick n Pay", sector: "Consumer", type: "stock" },
  { ticker: "WHL.JO", name: "Woolworths", sector: "Consumer", type: "stock" },
  { ticker: "MRP.JO", name: "Mr Price", sector: "Consumer", type: "stock" },
];

const thailandStocks: AssetEntry[] = [
  { ticker: "PTT.BK", name: "PTT PCL", sector: "Energy", type: "stock" },
  { ticker: "ADVANC.BK", name: "AIS", sector: "Telecom", type: "stock" },
  { ticker: "SCB.BK", name: "SCB X", sector: "Finance", type: "stock" },
  { ticker: "KBANK.BK", name: "Kasikornbank", sector: "Finance", type: "stock" },
  { ticker: "BBL.BK", name: "Bangkok Bank", sector: "Finance", type: "stock" },
  { ticker: "SCC.BK", name: "Siam Cement", sector: "Materials", type: "stock" },
  { ticker: "CPALL.BK", name: "CP ALL", sector: "Consumer", type: "stock" },
  { ticker: "CPF.BK", name: "CP Foods", sector: "Consumer", type: "stock" },
  { ticker: "BDMS.BK", name: "Bangkok Dusit Medical", sector: "Healthcare", type: "stock" },
  { ticker: "DELTA.BK", name: "Delta Electronics", sector: "Technology", type: "stock" },
  { ticker: "GULF.BK", name: "Gulf Energy", sector: "Utilities", type: "stock" },
  { ticker: "MINT.BK", name: "Minor International", sector: "Consumer", type: "stock" },
  { ticker: "AOT.BK", name: "Airports of Thailand", sector: "Industrials", type: "stock" },
  { ticker: "BEM.BK", name: "BEM", sector: "Industrials", type: "stock" },
  { ticker: "BTS.BK", name: "BTS Group", sector: "Industrials", type: "stock" },
  { ticker: "PTTGC.BK", name: "PTTGC", sector: "Materials", type: "stock" },
  { ticker: "IRPC.BK", name: "IRPC", sector: "Energy", type: "stock" },
  { ticker: "TOP.BK", name: "Thai Oil", sector: "Energy", type: "stock" },
  { ticker: "BANPU.BK", name: "Banpu", sector: "Energy", type: "stock" },
  { ticker: "BGRIM.BK", name: "B.Grimm Power", sector: "Utilities", type: "stock" },
  { ticker: "CPN.BK", name: "Central Pattana", sector: "Real Estate", type: "stock" },
  { ticker: "LH.BK", name: "Land & Houses", sector: "Real Estate", type: "stock" },
  { ticker: "TRUE.BK", name: "True Corporation", sector: "Telecom", type: "stock" },
  { ticker: "DTAC.BK", name: "DTAC", sector: "Telecom", type: "stock" },
  { ticker: "KTB.BK", name: "Krungthai Bank", sector: "Finance", type: "stock" },
  { ticker: "TTB.BK", name: "TMBThanachart", sector: "Finance", type: "stock" },
  { ticker: "TISCO.BK", name: "TISCO", sector: "Finance", type: "stock" },
  { ticker: "BH.BK", name: "Bumrungrad Hospital", sector: "Healthcare", type: "stock" },
  { ticker: "HMPRO.BK", name: "HomePro", sector: "Consumer", type: "stock" },
  { ticker: "SAWAD.BK", name: "Srisawad", sector: "Finance", type: "stock" },
];

const indonesiaStocks: AssetEntry[] = [
  { ticker: "BBCA.JK", name: "Bank Central Asia", sector: "Finance", type: "stock" },
  { ticker: "BBRI.JK", name: "Bank Rakyat", sector: "Finance", type: "stock" },
  { ticker: "BMRI.JK", name: "Bank Mandiri", sector: "Finance", type: "stock" },
  { ticker: "TLKM.JK", name: "Telkom Indonesia", sector: "Telecom", type: "stock" },
  { ticker: "ASII.JK", name: "Astra International", sector: "Industrials", type: "stock" },
  { ticker: "UNVR.JK", name: "Unilever Indonesia", sector: "Consumer", type: "stock" },
  { ticker: "HMSP.JK", name: "HM Sampoerna", sector: "Consumer", type: "stock" },
  { ticker: "GGRM.JK", name: "Gudang Garam", sector: "Consumer", type: "stock" },
  { ticker: "ICBP.JK", name: "Indofood CBP", sector: "Consumer", type: "stock" },
  { ticker: "INDF.JK", name: "Indofood", sector: "Consumer", type: "stock" },
  { ticker: "KLBF.JK", name: "Kalbe Farma", sector: "Healthcare", type: "stock" },
  { ticker: "PGAS.JK", name: "PGN", sector: "Energy", type: "stock" },
  { ticker: "ADRO.JK", name: "Adaro Energy", sector: "Energy", type: "stock" },
  { ticker: "PTBA.JK", name: "Bukit Asam", sector: "Energy", type: "stock" },
  { ticker: "ANTM.JK", name: "Aneka Tambang", sector: "Materials", type: "stock" },
  { ticker: "INCO.JK", name: "Vale Indonesia", sector: "Materials", type: "stock" },
  { ticker: "CPIN.JK", name: "Charoen Pokphand", sector: "Consumer", type: "stock" },
  { ticker: "SMGR.JK", name: "Semen Indonesia", sector: "Materials", type: "stock" },
  { ticker: "UNTR.JK", name: "United Tractors", sector: "Industrials", type: "stock" },
  { ticker: "BBNI.JK", name: "Bank Negara", sector: "Finance", type: "stock" },
  { ticker: "EXCL.JK", name: "XL Axiata", sector: "Telecom", type: "stock" },
  { ticker: "ISAT.JK", name: "Indosat", sector: "Telecom", type: "stock" },
  { ticker: "JSMR.JK", name: "Jasa Marga", sector: "Industrials", type: "stock" },
  { ticker: "WIKA.JK", name: "Wijaya Karya", sector: "Industrials", type: "stock" },
  { ticker: "PTPP.JK", name: "PP Persero", sector: "Industrials", type: "stock" },
  { ticker: "MDKA.JK", name: "Merdeka Copper", sector: "Materials", type: "stock" },
  { ticker: "ACES.JK", name: "Ace Hardware ID", sector: "Consumer", type: "stock" },
  { ticker: "MAPI.JK", name: "Mitra Adiperkasa", sector: "Consumer", type: "stock" },
  { ticker: "EMTK.JK", name: "Elang Mahkota", sector: "Communication", type: "stock" },
  { ticker: "TOWR.JK", name: "Sarana Menara", sector: "Telecom", type: "stock" },
];

const malaysiaStocks: AssetEntry[] = [
  { ticker: "MBBM.KL", name: "Maybank", sector: "Finance", type: "stock" },
  { ticker: "PBBANK.KL", name: "Public Bank", sector: "Finance", type: "stock" },
  { ticker: "CIMB.KL", name: "CIMB Group", sector: "Finance", type: "stock" },
  { ticker: "TENAGA.KL", name: "Tenaga Nasional", sector: "Utilities", type: "stock" },
  { ticker: "PCHEM.KL", name: "Petronas Chemicals", sector: "Materials", type: "stock" },
  { ticker: "IHH.KL", name: "IHH Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "AXIATA.KL", name: "Axiata Group", sector: "Telecom", type: "stock" },
  { ticker: "DIGI.KL", name: "CelcomDigi", sector: "Telecom", type: "stock" },
  { ticker: "HLBANK.KL", name: "Hong Leong Bank", sector: "Finance", type: "stock" },
  { ticker: "RHBBANK.KL", name: "RHB Bank", sector: "Finance", type: "stock" },
  { ticker: "GENM.KL", name: "Genting Malaysia", sector: "Consumer", type: "stock" },
  { ticker: "GENTING.KL", name: "Genting", sector: "Consumer", type: "stock" },
  { ticker: "PMETAL.KL", name: "Press Metal", sector: "Materials", type: "stock" },
  { ticker: "TOPGLOV.KL", name: "Top Glove", sector: "Healthcare", type: "stock" },
  { ticker: "HARTA.KL", name: "Hartalega", sector: "Healthcare", type: "stock" },
  { ticker: "KLK.KL", name: "Kuala Lumpur Kepong", sector: "Consumer", type: "stock" },
  { ticker: "IOI.KL", name: "IOI Corporation", sector: "Consumer", type: "stock" },
  { ticker: "SIMEPLT.KL", name: "Sime Darby Plantation", sector: "Consumer", type: "stock" },
  { ticker: "SIME.KL", name: "Sime Darby", sector: "Industrials", type: "stock" },
  { ticker: "MISC.KL", name: "MISC", sector: "Industrials", type: "stock" },
  { ticker: "PETDAG.KL", name: "Petronas Dagangan", sector: "Energy", type: "stock" },
  { ticker: "DIALOG.KL", name: "Dialog Group", sector: "Energy", type: "stock" },
  { ticker: "NESTLE.KL", name: "Nestlé Malaysia", sector: "Consumer", type: "stock" },
  { ticker: "QLRES.KL", name: "QL Resources", sector: "Consumer", type: "stock" },
  { ticker: "PPB.KL", name: "PPB Group", sector: "Consumer", type: "stock" },
  { ticker: "MRDIY.KL", name: "MR DIY Group", sector: "Consumer", type: "stock" },
  { ticker: "GAMUDA.KL", name: "Gamuda", sector: "Industrials", type: "stock" },
  { ticker: "YTLPOWR.KL", name: "YTL Power", sector: "Utilities", type: "stock" },
  { ticker: "AMBANK.KL", name: "AmBank Group", sector: "Finance", type: "stock" },
  { ticker: "PETGAS.KL", name: "Petronas Gas", sector: "Utilities", type: "stock" },
];

const philippinesStocks: AssetEntry[] = [
  { ticker: "SM.PS", name: "SM Investments", sector: "Industrials", type: "stock" },
  { ticker: "BDO.PS", name: "BDO Unibank", sector: "Finance", type: "stock" },
  { ticker: "BPI.PS", name: "Bank of the Philippine Islands", sector: "Finance", type: "stock" },
  { ticker: "TEL.PS", name: "PLDT", sector: "Telecom", type: "stock" },
  { ticker: "AC.PS", name: "Ayala Corporation", sector: "Industrials", type: "stock" },
  { ticker: "ALI.PS", name: "Ayala Land", sector: "Real Estate", type: "stock" },
  { ticker: "JFC.PS", name: "Jollibee Foods", sector: "Consumer", type: "stock" },
  { ticker: "URC.PS", name: "Universal Robina", sector: "Consumer", type: "stock" },
  { ticker: "MER.PS", name: "Meralco", sector: "Utilities", type: "stock" },
  { ticker: "GLO.PS", name: "Globe Telecom", sector: "Telecom", type: "stock" },
  { ticker: "SMPH.PS", name: "SM Prime Holdings", sector: "Real Estate", type: "stock" },
  { ticker: "MBT.PS", name: "Metrobank", sector: "Finance", type: "stock" },
  { ticker: "SECB.PS", name: "Security Bank", sector: "Finance", type: "stock" },
  { ticker: "AGI.PS", name: "Alliance Global", sector: "Industrials", type: "stock" },
  { ticker: "MEG.PS", name: "Megaworld", sector: "Real Estate", type: "stock" },
  { ticker: "RLC.PS", name: "Robinsons Land", sector: "Real Estate", type: "stock" },
  { ticker: "ICT.PS", name: "International Container", sector: "Industrials", type: "stock" },
  { ticker: "PGOLD.PS", name: "Puregold", sector: "Consumer", type: "stock" },
  { ticker: "MPI.PS", name: "Metro Pacific", sector: "Industrials", type: "stock" },
  { ticker: "DMC.PS", name: "DMCI Holdings", sector: "Industrials", type: "stock" },
];

const vietnamStocks: AssetEntry[] = [
  { ticker: "VNM.VN", name: "Vinamilk", sector: "Consumer", type: "stock" },
  { ticker: "VCB.VN", name: "Vietcombank", sector: "Finance", type: "stock" },
  { ticker: "VIC.VN", name: "Vingroup", sector: "Real Estate", type: "stock" },
  { ticker: "VHM.VN", name: "Vinhomes", sector: "Real Estate", type: "stock" },
  { ticker: "HPG.VN", name: "Hoa Phat Group", sector: "Materials", type: "stock" },
  { ticker: "FPT.VN", name: "FPT Corporation", sector: "Technology", type: "stock" },
  { ticker: "MSN.VN", name: "Masan Group", sector: "Consumer", type: "stock" },
  { ticker: "MBB.VN", name: "MB Bank", sector: "Finance", type: "stock" },
  { ticker: "TCB.VN", name: "Techcombank", sector: "Finance", type: "stock" },
  { ticker: "VPB.VN", name: "VPBank", sector: "Finance", type: "stock" },
  { ticker: "BID.VN", name: "BIDV", sector: "Finance", type: "stock" },
  { ticker: "CTG.VN", name: "VietinBank", sector: "Finance", type: "stock" },
  { ticker: "VRE.VN", name: "Vincom Retail", sector: "Real Estate", type: "stock" },
  { ticker: "GAS.VN", name: "PV Gas", sector: "Energy", type: "stock" },
  { ticker: "PLX.VN", name: "Petrolimex", sector: "Energy", type: "stock" },
  { ticker: "SAB.VN", name: "Sabeco", sector: "Consumer", type: "stock" },
  { ticker: "ACB.VN", name: "Asia Commercial Bank", sector: "Finance", type: "stock" },
  { ticker: "STB.VN", name: "Sacombank", sector: "Finance", type: "stock" },
  { ticker: "POW.VN", name: "PV Power", sector: "Utilities", type: "stock" },
  { ticker: "REE.VN", name: "REE Corp", sector: "Industrials", type: "stock" },
];

const turkeyStocks: AssetEntry[] = [
  { ticker: "THYAO.IS", name: "Turkish Airlines", sector: "Industrials", type: "stock" },
  { ticker: "GARAN.IS", name: "Garanti BBVA", sector: "Finance", type: "stock" },
  { ticker: "AKBNK.IS", name: "Akbank", sector: "Finance", type: "stock" },
  { ticker: "YKBNK.IS", name: "Yapı Kredi", sector: "Finance", type: "stock" },
  { ticker: "ISCTR.IS", name: "İş Bankası", sector: "Finance", type: "stock" },
  { ticker: "HALKB.IS", name: "Halkbank", sector: "Finance", type: "stock" },
  { ticker: "VAKBN.IS", name: "Vakıfbank", sector: "Finance", type: "stock" },
  { ticker: "SISE.IS", name: "Şişecam", sector: "Materials", type: "stock" },
  { ticker: "EREGL.IS", name: "Ereğli Demir Çelik", sector: "Materials", type: "stock" },
  { ticker: "KRDMD.IS", name: "Kardemir", sector: "Materials", type: "stock" },
  { ticker: "TUPRS.IS", name: "Tüpraş", sector: "Energy", type: "stock" },
  { ticker: "PETKM.IS", name: "Petkim", sector: "Materials", type: "stock" },
  { ticker: "ASELS.IS", name: "ASELSAN", sector: "Technology", type: "stock" },
  { ticker: "BIMAS.IS", name: "BİM", sector: "Consumer", type: "stock" },
  { ticker: "MGROS.IS", name: "Migros", sector: "Consumer", type: "stock" },
  { ticker: "TCELL.IS", name: "Turkcell", sector: "Telecom", type: "stock" },
  { ticker: "TAVHL.IS", name: "TAV Airports", sector: "Industrials", type: "stock" },
  { ticker: "KOZAL.IS", name: "Koza Altın", sector: "Materials", type: "stock" },
  { ticker: "SAHOL.IS", name: "Sabancı Holding", sector: "Industrials", type: "stock" },
  { ticker: "KCHOL.IS", name: "Koç Holding", sector: "Industrials", type: "stock" },
];

const polandStocks: AssetEntry[] = [
  { ticker: "PKO.WA", name: "PKO Bank Polski", sector: "Finance", type: "stock" },
  { ticker: "PZU.WA", name: "PZU", sector: "Finance", type: "stock" },
  { ticker: "PKN.WA", name: "PKN Orlen", sector: "Energy", type: "stock" },
  { ticker: "PEO.WA", name: "Pekao", sector: "Finance", type: "stock" },
  { ticker: "KGH.WA", name: "KGHM", sector: "Materials", type: "stock" },
  { ticker: "DNP.WA", name: "Dino Polska", sector: "Consumer", type: "stock" },
  { ticker: "CDR.WA", name: "CD Projekt", sector: "Technology", type: "stock" },
  { ticker: "SPL.WA", name: "Santander Polska", sector: "Finance", type: "stock" },
  { ticker: "ALE.WA", name: "Allegro", sector: "Technology", type: "stock" },
  { ticker: "LPP.WA", name: "LPP", sector: "Consumer", type: "stock" },
  { ticker: "MBK.WA", name: "mBank", sector: "Finance", type: "stock" },
  { ticker: "CCC.WA", name: "CCC", sector: "Consumer", type: "stock" },
  { ticker: "PGE.WA", name: "PGE", sector: "Utilities", type: "stock" },
  { ticker: "TPE.WA", name: "Tauron Polska", sector: "Utilities", type: "stock" },
  { ticker: "JSW.WA", name: "JSW", sector: "Energy", type: "stock" },
  { ticker: "KRU.WA", name: "Kruk", sector: "Finance", type: "stock" },
  { ticker: "CPS.WA", name: "Cyfrowy Polsat", sector: "Communication", type: "stock" },
  { ticker: "OPL.WA", name: "Orange Polska", sector: "Telecom", type: "stock" },
  { ticker: "MIL.WA", name: "Bank Millennium", sector: "Finance", type: "stock" },
  { ticker: "PCO.WA", name: "Pepco Group", sector: "Consumer", type: "stock" },
];

const saudi_arabiaStocks: AssetEntry[] = [
  { ticker: "2222.SR", name: "Saudi Aramco", sector: "Energy", type: "stock" },
  { ticker: "1180.SR", name: "Al Rajhi Bank", sector: "Finance", type: "stock" },
  { ticker: "2010.SR", name: "SABIC", sector: "Materials", type: "stock" },
  { ticker: "1010.SR", name: "Riyad Bank", sector: "Finance", type: "stock" },
  { ticker: "7010.SR", name: "STC", sector: "Telecom", type: "stock" },
  { ticker: "1150.SR", name: "Alinma Bank", sector: "Finance", type: "stock" },
  { ticker: "2350.SR", name: "Saudi Kayan", sector: "Materials", type: "stock" },
  { ticker: "1120.SR", name: "Al Rajhi REIT", sector: "Real Estate", type: "stock" },
  { ticker: "2380.SR", name: "SAFCO", sector: "Materials", type: "stock" },
  { ticker: "3010.SR", name: "Almarai", sector: "Consumer", type: "stock" },
  { ticker: "2310.SR", name: "Sipchem", sector: "Materials", type: "stock" },
  { ticker: "1211.SR", name: "Ma'aden", sector: "Materials", type: "stock" },
  { ticker: "2060.SR", name: "NCCI", sector: "Finance", type: "stock" },
  { ticker: "4030.SR", name: "Jarir", sector: "Consumer", type: "stock" },
  { ticker: "2280.SR", name: "Almarai Dairy", sector: "Consumer", type: "stock" },
  { ticker: "1050.SR", name: "Saudi Investment Bank", sector: "Finance", type: "stock" },
  { ticker: "2020.SR", name: "SABIC Agri-Nutrients", sector: "Materials", type: "stock" },
  { ticker: "6010.SR", name: "Mobily", sector: "Telecom", type: "stock" },
  { ticker: "4190.SR", name: "Jahez", sector: "Technology", type: "stock" },
  { ticker: "2050.SR", name: "Savola Group", sector: "Consumer", type: "stock" },
];

const uaeStocks: AssetEntry[] = [
  { ticker: "FAB.AE", name: "First Abu Dhabi Bank", sector: "Finance", type: "stock" },
  { ticker: "ETISALAT.AE", name: "Etisalat", sector: "Telecom", type: "stock" },
  { ticker: "EMAAR.AE", name: "Emaar Properties", sector: "Real Estate", type: "stock" },
  { ticker: "DU.AE", name: "Emirates Integrated", sector: "Telecom", type: "stock" },
  { ticker: "DIB.AE", name: "Dubai Islamic Bank", sector: "Finance", type: "stock" },
  { ticker: "ADNOCDIST.AE", name: "ADNOC Distribution", sector: "Energy", type: "stock" },
  { ticker: "DAMAC.AE", name: "Damac Properties", sector: "Real Estate", type: "stock" },
  { ticker: "ALDAR.AE", name: "Aldar Properties", sector: "Real Estate", type: "stock" },
  { ticker: "ADIB.AE", name: "Abu Dhabi Islamic Bank", sector: "Finance", type: "stock" },
  { ticker: "DFM.AE", name: "Dubai Financial Market", sector: "Finance", type: "stock" },
  { ticker: "EMAARDEV.AE", name: "Emaar Development", sector: "Real Estate", type: "stock" },
  { ticker: "TABREED.AE", name: "Tabreed", sector: "Utilities", type: "stock" },
  { ticker: "CBD.AE", name: "Commercial Bank of Dubai", sector: "Finance", type: "stock" },
  { ticker: "DANA.AE", name: "Dana Gas", sector: "Energy", type: "stock" },
  { ticker: "AIRARABIA.AE", name: "Air Arabia", sector: "Industrials", type: "stock" },
  { ticker: "LULU.AE", name: "Lulu Retail", sector: "Consumer", type: "stock" },
];

const taiwanStocks: AssetEntry[] = [
  { ticker: "2330.TW", name: "TSMC", sector: "Technology", type: "stock" },
  { ticker: "2317.TW", name: "Hon Hai Precision", sector: "Technology", type: "stock" },
  { ticker: "2454.TW", name: "MediaTek", sector: "Technology", type: "stock" },
  { ticker: "2308.TW", name: "Delta Electronics", sector: "Technology", type: "stock" },
  { ticker: "2882.TW", name: "Cathay Financial", sector: "Finance", type: "stock" },
  { ticker: "2891.TW", name: "CTBC Financial", sector: "Finance", type: "stock" },
  { ticker: "2881.TW", name: "Fubon Financial", sector: "Finance", type: "stock" },
  { ticker: "2886.TW", name: "Mega Financial", sector: "Finance", type: "stock" },
  { ticker: "1301.TW", name: "Formosa Plastics", sector: "Materials", type: "stock" },
  { ticker: "1303.TW", name: "Nan Ya Plastics", sector: "Materials", type: "stock" },
  { ticker: "2002.TW", name: "China Steel", sector: "Materials", type: "stock" },
  { ticker: "3711.TW", name: "ASE Technology", sector: "Technology", type: "stock" },
  { ticker: "2412.TW", name: "Chunghwa Telecom", sector: "Telecom", type: "stock" },
  { ticker: "2303.TW", name: "United Microelectronics", sector: "Technology", type: "stock" },
  { ticker: "3008.TW", name: "Largan Precision", sector: "Technology", type: "stock" },
  { ticker: "2884.TW", name: "E.SUN Financial", sector: "Finance", type: "stock" },
  { ticker: "2357.TW", name: "ASUS", sector: "Technology", type: "stock" },
  { ticker: "2382.TW", name: "Quanta Computer", sector: "Technology", type: "stock" },
  { ticker: "2912.TW", name: "Uni-President", sector: "Consumer", type: "stock" },
  { ticker: "1326.TW", name: "Formosa Chemicals", sector: "Materials", type: "stock" },
  { ticker: "6505.TW", name: "Formosa Petrochemical", sector: "Energy", type: "stock" },
  { ticker: "2207.TW", name: "Hotai Motor", sector: "Consumer", type: "stock" },
  { ticker: "5880.TW", name: "Taiwan Cooperative", sector: "Finance", type: "stock" },
  { ticker: "2801.TW", name: "Chang Hwa Bank", sector: "Finance", type: "stock" },
  { ticker: "2880.TW", name: "Hua Nan Financial", sector: "Finance", type: "stock" },
  { ticker: "5871.TW", name: "Chailease", sector: "Finance", type: "stock" },
  { ticker: "2609.TW", name: "Yang Ming Marine", sector: "Industrials", type: "stock" },
  { ticker: "2615.TW", name: "Wan Hai Lines", sector: "Industrials", type: "stock" },
  { ticker: "1216.TW", name: "Uni-President Enterprises", sector: "Consumer", type: "stock" },
  { ticker: "2395.TW", name: "Advantech", sector: "Technology", type: "stock" },
];

const chileStocks: AssetEntry[] = [
  { ticker: "SQM-B.SN", name: "SQM", sector: "Materials", type: "stock" },
  { ticker: "BSANTANDER.SN", name: "Banco Santander Chile", sector: "Finance", type: "stock" },
  { ticker: "FALABELLA.SN", name: "Falabella", sector: "Consumer", type: "stock" },
  { ticker: "CENCOSUD.SN", name: "Cencosud", sector: "Consumer", type: "stock" },
  { ticker: "COPEC.SN", name: "Empresas Copec", sector: "Energy", type: "stock" },
  { ticker: "ENELAM.SN", name: "Enel Américas", sector: "Utilities", type: "stock" },
  { ticker: "BCI.SN", name: "BCI", sector: "Finance", type: "stock" },
  { ticker: "CCU.SN", name: "CCU", sector: "Consumer", type: "stock" },
  { ticker: "CMPC.SN", name: "CMPC", sector: "Materials", type: "stock" },
  { ticker: "CAP.SN", name: "CAP", sector: "Materials", type: "stock" },
  { ticker: "COLBUN.SN", name: "Colbún", sector: "Utilities", type: "stock" },
  { ticker: "ILC.SN", name: "ILC", sector: "Finance", type: "stock" },
  { ticker: "LTDA.SN", name: "Parque Arauco", sector: "Real Estate", type: "stock" },
  { ticker: "VAPORES.SN", name: "CSAV", sector: "Industrials", type: "stock" },
  { ticker: "ENELCHILE.SN", name: "Enel Chile", sector: "Utilities", type: "stock" },
  { ticker: "RIPLEY.SN", name: "Ripley", sector: "Consumer", type: "stock" },
];

const colombiaStocks: AssetEntry[] = [
  { ticker: "PFBCOLOM.CL", name: "Bancolombia", sector: "Finance", type: "stock" },
  { ticker: "ECOPETROL.CL", name: "Ecopetrol", sector: "Energy", type: "stock" },
  { ticker: "ISA.CL", name: "ISA", sector: "Utilities", type: "stock" },
  { ticker: "NUTRESA.CL", name: "Nutresa", sector: "Consumer", type: "stock" },
  { ticker: "GRUPOARGOS.CL", name: "Grupo Argos", sector: "Industrials", type: "stock" },
  { ticker: "CEMARGOS.CL", name: "Cementos Argos", sector: "Materials", type: "stock" },
  { ticker: "PFGRUPSURA.CL", name: "Grupo Sura", sector: "Finance", type: "stock" },
  { ticker: "PFAVAL.CL", name: "Grupo Aval", sector: "Finance", type: "stock" },
  { ticker: "CELSIA.CL", name: "Celsia", sector: "Utilities", type: "stock" },
  { ticker: "ETB.CL", name: "ETB", sector: "Telecom", type: "stock" },
];

const egyptStocks: AssetEntry[] = [
  { ticker: "COMI.CA", name: "Commercial International Bank", sector: "Finance", type: "stock" },
  { ticker: "HRHO.CA", name: "Hermes Holding", sector: "Finance", type: "stock" },
  { ticker: "TMGH.CA", name: "Talaat Moustafa Group", sector: "Real Estate", type: "stock" },
  { ticker: "SWDY.CA", name: "Elsewedy Electric", sector: "Industrials", type: "stock" },
  { ticker: "EAST.CA", name: "Eastern Company", sector: "Consumer", type: "stock" },
  { ticker: "OCDI.CA", name: "Orascom Development", sector: "Real Estate", type: "stock" },
  { ticker: "FWRY.CA", name: "Fawry", sector: "Technology", type: "stock" },
  { ticker: "EKHO.CA", name: "EK Holding", sector: "Consumer", type: "stock" },
  { ticker: "ORWE.CA", name: "Oriental Weavers", sector: "Consumer", type: "stock" },
  { ticker: "ESRS.CA", name: "Ezz Steel", sector: "Materials", type: "stock" },
];

const nigeriaStocks: AssetEntry[] = [
  { ticker: "DANGCEM.LG", name: "Dangote Cement", sector: "Materials", type: "stock" },
  { ticker: "MTNN.LG", name: "MTN Nigeria", sector: "Telecom", type: "stock" },
  { ticker: "AIRTELAFRI.LG", name: "Airtel Africa", sector: "Telecom", type: "stock" },
  { ticker: "BUACEMENT.LG", name: "BUA Cement", sector: "Materials", type: "stock" },
  { ticker: "ZENITHBANK.LG", name: "Zenith Bank", sector: "Finance", type: "stock" },
  { ticker: "GTCO.LG", name: "GTBank", sector: "Finance", type: "stock" },
  { ticker: "FBNH.LG", name: "FBN Holdings", sector: "Finance", type: "stock" },
  { ticker: "ACCESSCORP.LG", name: "Access Bank", sector: "Finance", type: "stock" },
  { ticker: "STANBIC.LG", name: "Stanbic IBTC", sector: "Finance", type: "stock" },
  { ticker: "NESTLE.LG", name: "Nestlé Nigeria", sector: "Consumer", type: "stock" },
  { ticker: "BUAFOODS.LG", name: "BUA Foods", sector: "Consumer", type: "stock" },
  { ticker: "SEPLAT.LG", name: "Seplat Energy", sector: "Energy", type: "stock" },
];

const kenyaStocks: AssetEntry[] = [
  { ticker: "SCOM.NR", name: "Safaricom", sector: "Telecom", type: "stock" },
  { ticker: "EQTY.NR", name: "Equity Group", sector: "Finance", type: "stock" },
  { ticker: "KCB.NR", name: "KCB Group", sector: "Finance", type: "stock" },
  { ticker: "COOP.NR", name: "Co-operative Bank", sector: "Finance", type: "stock" },
  { ticker: "BAT.NR", name: "BAT Kenya", sector: "Consumer", type: "stock" },
  { ticker: "EABL.NR", name: "EABL", sector: "Consumer", type: "stock" },
  { ticker: "ABSA.NR", name: "Absa Bank Kenya", sector: "Finance", type: "stock" },
  { ticker: "SBIC.NR", name: "Stanbic Holdings", sector: "Finance", type: "stock" },
];

export const emergingMarketStocks: AssetEntry[] = [
  ...mexicoStocks,
  ...brazilStocks,
  ...south_africaStocks,
  ...thailandStocks,
  ...indonesiaStocks,
  ...malaysiaStocks,
  ...philippinesStocks,
  ...vietnamStocks,
  ...turkeyStocks,
  ...polandStocks,
  ...saudi_arabiaStocks,
  ...uaeStocks,
  ...taiwanStocks,
  ...chileStocks,
  ...colombiaStocks,
  ...egyptStocks,
  ...nigeriaStocks,
  ...kenyaStocks,
];
