import { AssetEntry } from "./types";

export const etfs: AssetEntry[] = [
  // US Broad Market
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", sector: "Index", type: "etf" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", sector: "Technology", type: "etf" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", sector: "Index", type: "etf" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", sector: "Index", type: "etf" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", sector: "Index", type: "etf" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial ETF", sector: "Index", type: "etf" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", sector: "Index", type: "etf" },
  { ticker: "RSP", name: "Invesco S&P 500 Equal Weight ETF", sector: "Index", type: "etf" },
  { ticker: "MDY", name: "SPDR S&P MidCap 400 ETF", sector: "Index", type: "etf" },
  { ticker: "IJR", name: "iShares Core S&P Small-Cap ETF", sector: "Index", type: "etf" },
  { ticker: "IWF", name: "iShares Russell 1000 Growth ETF", sector: "Index", type: "etf" },
  { ticker: "IWD", name: "iShares Russell 1000 Value ETF", sector: "Index", type: "etf" },
  { ticker: "VUG", name: "Vanguard Growth ETF", sector: "Index", type: "etf" },
  { ticker: "VTV", name: "Vanguard Value ETF", sector: "Index", type: "etf" },
  { ticker: "SCHD", name: "Schwab U.S. Dividend Equity ETF", sector: "Index", type: "etf" },
  { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", sector: "Index", type: "etf" },
  { ticker: "DVY", name: "iShares Select Dividend ETF", sector: "Index", type: "etf" },
  { ticker: "SDY", name: "SPDR S&P Dividend ETF", sector: "Index", type: "etf" },
  { ticker: "NOBL", name: "ProShares S&P 500 Dividend Aristocrats", sector: "Index", type: "etf" },
  { ticker: "MTUM", name: "iShares MSCI USA Momentum Factor ETF", sector: "Index", type: "etf" },
  { ticker: "QUAL", name: "iShares MSCI USA Quality Factor ETF", sector: "Index", type: "etf" },
  { ticker: "VLUE", name: "iShares MSCI USA Value Factor ETF", sector: "Index", type: "etf" },
  { ticker: "SIZE", name: "iShares MSCI USA Size Factor ETF", sector: "Index", type: "etf" },
  // Sector ETFs
  { ticker: "XLV", name: "Health Care Select Sector SPDR", sector: "Healthcare", type: "etf" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR", sector: "Consumer", type: "etf" },
  { ticker: "XLE", name: "Energy Select Sector SPDR", sector: "Energy", type: "etf" },
  { ticker: "XLF", name: "Financial Select Sector SPDR", sector: "Finance", type: "etf" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR", sector: "Industrial", type: "etf" },
  { ticker: "XLK", name: "Technology Select Sector SPDR", sector: "Technology", type: "etf" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR", sector: "Utilities", type: "etf" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR", sector: "Consumer", type: "etf" },
  { ticker: "XLC", name: "Communication Services Select Sector SPDR", sector: "Telecom", type: "etf" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR", sector: "Real Estate", type: "etf" },
  { ticker: "XLB", name: "Materials Select Sector SPDR", sector: "Materials", type: "etf" },
  { ticker: "VDE", name: "Vanguard Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "VFH", name: "Vanguard Financials ETF", sector: "Finance", type: "etf" },
  { ticker: "VHT", name: "Vanguard Health Care ETF", sector: "Healthcare", type: "etf" },
  { ticker: "VGT", name: "Vanguard Information Technology ETF", sector: "Technology", type: "etf" },
  { ticker: "VIS", name: "Vanguard Industrials ETF", sector: "Industrial", type: "etf" },
  { ticker: "VAW", name: "Vanguard Materials ETF", sector: "Materials", type: "etf" },
  { ticker: "VCR", name: "Vanguard Consumer Discretionary ETF", sector: "Consumer", type: "etf" },
  { ticker: "VDC", name: "Vanguard Consumer Staples ETF", sector: "Consumer", type: "etf" },
  { ticker: "VPU", name: "Vanguard Utilities ETF", sector: "Utilities", type: "etf" },
  // Thematic / Innovation
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "Innovation", type: "etf" },
  { ticker: "ARKW", name: "ARK Next Generation Internet ETF", sector: "Innovation", type: "etf" },
  { ticker: "ARKG", name: "ARK Genomic Revolution ETF", sector: "Healthcare", type: "etf" },
  { ticker: "ARKF", name: "ARK Fintech Innovation ETF", sector: "Finance", type: "etf" },
  { ticker: "ARKQ", name: "ARK Autonomous Tech & Robotics ETF", sector: "Technology", type: "etf" },
  { ticker: "BOTZ", name: "Global X Robotics & AI ETF", sector: "Technology", type: "etf" },
  { ticker: "AIQ", name: "Global X Artificial Intelligence ETF", sector: "Technology", type: "etf" },
  { ticker: "DRIV", name: "Global X Autonomous & Electric Vehicles ETF", sector: "Technology", type: "etf" },
  { ticker: "HERO", name: "Global X Video Games & Esports ETF", sector: "Technology", type: "etf" },
  { ticker: "CLOU", name: "Global X Cloud Computing ETF", sector: "Technology", type: "etf" },
  { ticker: "BUG", name: "Global X Cybersecurity ETF", sector: "Technology", type: "etf" },
  { ticker: "FINX", name: "Global X FinTech ETF", sector: "Finance", type: "etf" },
  { ticker: "LIT", name: "Global X Lithium & Battery Tech ETF", sector: "Materials", type: "etf" },
  { ticker: "ICLN", name: "iShares Global Clean Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "TAN", name: "Invesco Solar ETF", sector: "Energy", type: "etf" },
  { ticker: "FAN", name: "First Trust Global Wind Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "QCLN", name: "First Trust NASDAQ Clean Edge Green Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "PBW", name: "Invesco WilderHill Clean Energy ETF", sector: "Energy", type: "etf" },
  // Semiconductor
  { ticker: "SOXX", name: "iShares Semiconductor ETF", sector: "Technology", type: "etf" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF", sector: "Technology", type: "etf" },
  { ticker: "PSI", name: "Invesco Semiconductors ETF", sector: "Technology", type: "etf" },
  // Fixed Income
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "AGG", name: "iShares Core US Aggregate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "TIP", name: "iShares TIPS Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "VCSH", name: "Vanguard Short-Term Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "VGSH", name: "Vanguard Short-Term Treasury ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "VGIT", name: "Vanguard Intermediate-Term Treasury ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "BNDX", name: "Vanguard Total International Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "EMB", name: "iShares JP Morgan USD Emerging Markets Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "MUB", name: "iShares National Muni Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "VTEB", name: "Vanguard Tax-Exempt Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "SPTL", name: "SPDR Portfolio Long Term Treasury ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "SPLB", name: "SPDR Portfolio Long Term Corporate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "FLOT", name: "iShares Floating Rate Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "SGOV", name: "iShares 0-3 Month Treasury Bond ETF", sector: "Fixed Income", type: "etf" },
  { ticker: "BIL", name: "SPDR Bloomberg 1-3 Month T-Bill ETF", sector: "Fixed Income", type: "etf" },
  // Commodities
  { ticker: "GLD", name: "SPDR Gold Shares", sector: "Commodities", type: "etf" },
  { ticker: "SLV", name: "iShares Silver Trust", sector: "Commodities", type: "etf" },
  { ticker: "GDX", name: "VanEck Gold Miners ETF", sector: "Materials", type: "etf" },
  { ticker: "GDXJ", name: "VanEck Junior Gold Miners ETF", sector: "Materials", type: "etf" },
  { ticker: "IAU", name: "iShares Gold Trust", sector: "Commodities", type: "etf" },
  { ticker: "PPLT", name: "abrdn Physical Platinum Shares ETF", sector: "Commodities", type: "etf" },
  { ticker: "PALL", name: "abrdn Physical Palladium Shares ETF", sector: "Commodities", type: "etf" },
  { ticker: "USO", name: "United States Oil Fund", sector: "Commodities", type: "etf" },
  { ticker: "UNG", name: "United States Natural Gas Fund", sector: "Commodities", type: "etf" },
  { ticker: "DBA", name: "Invesco DB Agriculture Fund", sector: "Commodities", type: "etf" },
  { ticker: "DBC", name: "Invesco DB Commodity Index Tracking Fund", sector: "Commodities", type: "etf" },
  { ticker: "PDBC", name: "Invesco Optimum Yield Diversified Commodity ETF", sector: "Commodities", type: "etf" },
  { ticker: "WEAT", name: "Teucrium Wheat Fund", sector: "Commodities", type: "etf" },
  { ticker: "CORN", name: "Teucrium Corn Fund", sector: "Commodities", type: "etf" },
  { ticker: "CPER", name: "United States Copper Index Fund", sector: "Commodities", type: "etf" },
  // International
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", sector: "International", type: "etf" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", sector: "International", type: "etf" },
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF", sector: "International", type: "etf" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", sector: "International", type: "etf" },
  { ticker: "KWEB", name: "KraneShares CSI China Internet ETF", sector: "International", type: "etf" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF", sector: "International", type: "etf" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF", sector: "International", type: "etf" },
  { ticker: "EWJ", name: "iShares MSCI Japan ETF", sector: "International", type: "etf" },
  { ticker: "EWG", name: "iShares MSCI Germany ETF", sector: "International", type: "etf" },
  { ticker: "EWU", name: "iShares MSCI United Kingdom ETF", sector: "International", type: "etf" },
  { ticker: "EWZ", name: "iShares MSCI Brazil ETF", sector: "International", type: "etf" },
  { ticker: "EWY", name: "iShares MSCI South Korea ETF", sector: "International", type: "etf" },
  { ticker: "EWT", name: "iShares MSCI Taiwan ETF", sector: "International", type: "etf" },
  { ticker: "INDA", name: "iShares MSCI India ETF", sector: "International", type: "etf" },
  { ticker: "EWA", name: "iShares MSCI Australia ETF", sector: "International", type: "etf" },
  { ticker: "EWC", name: "iShares MSCI Canada ETF", sector: "International", type: "etf" },
  { ticker: "EWH", name: "iShares MSCI Hong Kong ETF", sector: "International", type: "etf" },
  { ticker: "EWS", name: "iShares MSCI Singapore ETF", sector: "International", type: "etf" },
  { ticker: "EWP", name: "iShares MSCI Spain ETF", sector: "International", type: "etf" },
  { ticker: "EWI", name: "iShares MSCI Italy ETF", sector: "International", type: "etf" },
  { ticker: "EWQ", name: "iShares MSCI France ETF", sector: "International", type: "etf" },
  { ticker: "EWL", name: "iShares MSCI Switzerland ETF", sector: "International", type: "etf" },
  { ticker: "EWN", name: "iShares MSCI Netherlands ETF", sector: "International", type: "etf" },
  { ticker: "MCHI", name: "iShares MSCI China ETF", sector: "International", type: "etf" },
  { ticker: "FXI", name: "iShares China Large-Cap ETF", sector: "International", type: "etf" },
  { ticker: "VPL", name: "Vanguard FTSE Pacific ETF", sector: "International", type: "etf" },
  { ticker: "VGK", name: "Vanguard FTSE Europe ETF", sector: "International", type: "etf" },
  // Real Estate
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", sector: "Real Estate", type: "etf" },
  { ticker: "IYR", name: "iShares U.S. Real Estate ETF", sector: "Real Estate", type: "etf" },
  { ticker: "SCHH", name: "Schwab U.S. REIT ETF", sector: "Real Estate", type: "etf" },
  { ticker: "RWR", name: "SPDR Dow Jones REIT ETF", sector: "Real Estate", type: "etf" },
  // Leveraged & Inverse
  { ticker: "TQQQ", name: "ProShares UltraPro QQQ", sector: "Leveraged", type: "etf" },
  { ticker: "SQQQ", name: "ProShares UltraPro Short QQQ", sector: "Leveraged", type: "etf" },
  { ticker: "UPRO", name: "ProShares UltraPro S&P 500", sector: "Leveraged", type: "etf" },
  { ticker: "SPXU", name: "ProShares UltraPro Short S&P 500", sector: "Leveraged", type: "etf" },
  { ticker: "SOXL", name: "Direxion Daily Semiconductor Bull 3X", sector: "Leveraged", type: "etf" },
  { ticker: "SOXS", name: "Direxion Daily Semiconductor Bear 3X", sector: "Leveraged", type: "etf" },
  { ticker: "LABU", name: "Direxion Daily S&P Biotech Bull 3X", sector: "Leveraged", type: "etf" },
  { ticker: "LABD", name: "Direxion Daily S&P Biotech Bear 3X", sector: "Leveraged", type: "etf" },
  { ticker: "TNA", name: "Direxion Daily Small Cap Bull 3X", sector: "Leveraged", type: "etf" },
  { ticker: "TZA", name: "Direxion Daily Small Cap Bear 3X", sector: "Leveraged", type: "etf" },
  { ticker: "UVXY", name: "ProShares Ultra VIX Short-Term Futures ETF", sector: "Volatility", type: "etf" },
  { ticker: "SVXY", name: "ProShares Short VIX Short-Term Futures ETF", sector: "Volatility", type: "etf" },
  // Income / Covered Call
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", sector: "Income", type: "etf" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", sector: "Income", type: "etf" },
  { ticker: "QYLD", name: "Global X NASDAQ 100 Covered Call ETF", sector: "Income", type: "etf" },
  { ticker: "XYLD", name: "Global X S&P 500 Covered Call ETF", sector: "Income", type: "etf" },
  { ticker: "DIVO", name: "Amplify CWP Enhanced Dividend Income ETF", sector: "Income", type: "etf" },
  // Crypto-related ETFs
  { ticker: "BITO", name: "ProShares Bitcoin Strategy ETF", sector: "Crypto", type: "etf" },
  { ticker: "IBIT", name: "iShares Bitcoin Trust ETF", sector: "Crypto", type: "etf" },
  { ticker: "FBTC", name: "Fidelity Wise Origin Bitcoin Fund", sector: "Crypto", type: "etf" },
  { ticker: "ETHE", name: "Grayscale Ethereum Trust", sector: "Crypto", type: "etf" },
  { ticker: "GBTC", name: "Grayscale Bitcoin Trust", sector: "Crypto", type: "etf" },
];
