import type { AssetEntry } from "./types";


export const expansionExtra: AssetEntry[] = [
  { ticker: "CELH", name: "Celsius Holdings", sector: "Consumer", type: "stock" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer", type: "stock" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer", type: "stock" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer", type: "stock" },
  { ticker: "SAM", name: "Boston Beer", sector: "Consumer", type: "stock" },
  { ticker: "BF-B", name: "Brown-Forman", sector: "Consumer", type: "stock" },
  { ticker: "TAP", name: "Molson Coors", sector: "Consumer", type: "stock" },
  { ticker: "DEO", name: "Diageo ADR", sector: "Consumer", type: "stock" },
  { ticker: "BUD", name: "Anheuser-Busch InBev", sector: "Consumer", type: "stock" },
  { ticker: "KHC", name: "Kraft Heinz", sector: "Consumer", type: "stock" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer", type: "stock" },
  { ticker: "K", name: "Kellogg", sector: "Consumer", type: "stock" },
  { ticker: "HSY", name: "Hershey", sector: "Consumer", type: "stock" },
  { ticker: "MDLZ", name: "Mondelez", sector: "Consumer", type: "stock" },
  { ticker: "CPB", name: "Campbell Soup", sector: "Consumer", type: "stock" },
  { ticker: "SJM", name: "J.M. Smucker", sector: "Consumer", type: "stock" },
  { ticker: "MKC", name: "McCormick", sector: "Consumer", type: "stock" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer", type: "stock" },
  { ticker: "CAG", name: "Conagra Brands", sector: "Consumer", type: "stock" },
  { ticker: "TSN", name: "Tyson Foods", sector: "Consumer", type: "stock" },
  { ticker: "PPC", name: "Pilgrims Pride", sector: "Consumer", type: "stock" },
  { ticker: "CALM", name: "Cal-Maine Foods", sector: "Consumer", type: "stock" },
  { ticker: "POST", name: "Post Holdings", sector: "Consumer", type: "stock" },
  { ticker: "THS", name: "TreeHouse Foods", sector: "Consumer", type: "stock" },
  { ticker: "CLX", name: "Clorox", sector: "Consumer", type: "stock" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer", type: "stock" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer", type: "stock" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer", type: "stock" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer", type: "stock" },
  { ticker: "EL", name: "Estee Lauder", sector: "Consumer", type: "stock" },
  { ticker: "COTY", name: "Coty", sector: "Consumer", type: "stock" },
  { ticker: "HELE", name: "Helen of Troy", sector: "Consumer", type: "stock" },
  { ticker: "ENR", name: "Energizer", sector: "Consumer", type: "stock" },
  { ticker: "SPB", name: "Spectrum Brands", sector: "Consumer", type: "stock" },
  { ticker: "NWL", name: "Newell Brands", sector: "Consumer", type: "stock" },
  { ticker: "HAS", name: "Hasbro", sector: "Consumer", type: "stock" },
  { ticker: "MAT", name: "Mattel", sector: "Consumer", type: "stock" },
  { ticker: "FNKO", name: "Funko", sector: "Consumer", type: "stock" },
  { ticker: "PRPL", name: "Purple Innovation", sector: "Consumer", type: "stock" },
  { ticker: "LOVE", name: "Lovesac", sector: "Consumer", type: "stock" },
  { ticker: "RH", name: "RH", sector: "Consumer", type: "stock" },
  { ticker: "WSM", name: "Williams-Sonoma", sector: "Consumer", type: "stock" },
  { ticker: "ETSY", name: "Etsy", sector: "Consumer", type: "stock" },
  { ticker: "W", name: "Wayfair", sector: "Consumer", type: "stock" },
  { ticker: "CHWY", name: "Chewy", sector: "Consumer", type: "stock" },
  { ticker: "WOOF", name: "Petco", sector: "Consumer", type: "stock" },
  { ticker: "BARK", name: "BARK Inc", sector: "Consumer", type: "stock" },
  { ticker: "FRPT", name: "Freshpet", sector: "Consumer", type: "stock" },
  { ticker: "SFM", name: "Sprouts Farmers Market", sector: "Consumer", type: "stock" },
  { ticker: "ACI", name: "Albertsons", sector: "Consumer", type: "stock" },
  { ticker: "KR", name: "Kroger", sector: "Consumer", type: "stock" },
  { ticker: "WMT", name: "Walmart", sector: "Consumer", type: "stock" },
  { ticker: "COST", name: "Costco", sector: "Consumer", type: "stock" },
  { ticker: "TGT", name: "Target", sector: "Consumer", type: "stock" },
  { ticker: "DG", name: "Dollar General", sector: "Consumer", type: "stock" },
  { ticker: "DLTR", name: "Dollar Tree", sector: "Consumer", type: "stock" },
  { ticker: "FIVE", name: "Five Below", sector: "Consumer", type: "stock" },
  { ticker: "OLLI", name: "Ollie's Bargain", sector: "Consumer", type: "stock" },
  { ticker: "BJ", name: "BJ's Wholesale", sector: "Consumer", type: "stock" },
  { ticker: "PSMT", name: "PriceSmart", sector: "Consumer", type: "stock" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer", type: "stock" },
  { ticker: "LOW", name: "Lowe's", sector: "Consumer", type: "stock" },
  { ticker: "TSCO", name: "Tractor Supply", sector: "Consumer", type: "stock" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer", type: "stock" },
  { ticker: "AZO", name: "AutoZone", sector: "Consumer", type: "stock" },
  { ticker: "AAP", name: "Advance Auto Parts", sector: "Consumer", type: "stock" },
  { ticker: "GPC", name: "Genuine Parts", sector: "Consumer", type: "stock" },
  { ticker: "LKQ", name: "LKQ Corporation", sector: "Consumer", type: "stock" },
  { ticker: "POOL", name: "Pool Corporation", sector: "Consumer", type: "stock" },
  { ticker: "WSO", name: "Watsco", sector: "Consumer", type: "stock" },
  { ticker: "SWK", name: "Stanley Black & Decker", sector: "Industrials", type: "stock" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials", type: "stock" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials", type: "stock" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrials", type: "stock" },
  { ticker: "AME", name: "AMETEK", sector: "Industrials", type: "stock" },
  { ticker: "NDSN", name: "Nordson", sector: "Industrials", type: "stock" },
  { ticker: "PH", name: "Parker-Hannifin", sector: "Industrials", type: "stock" },
  { ticker: "DOV", name: "Dover", sector: "Industrials", type: "stock" },
  { ticker: "ROP", name: "Roper Technologies", sector: "Industrials", type: "stock" },
  { ticker: "IR", name: "Ingersoll Rand", sector: "Industrials", type: "stock" },
  { ticker: "FTV", name: "Fortive", sector: "Industrials", type: "stock" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials", type: "stock" },
  { ticker: "HON", name: "Honeywell", sector: "Industrials", type: "stock" },
  { ticker: "MMM", name: "3M", sector: "Industrials", type: "stock" },
  { ticker: "CAT", name: "Caterpillar", sector: "Industrials", type: "stock" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials", type: "stock" },
  { ticker: "AGCO", name: "AGCO Corporation", sector: "Industrials", type: "stock" },
  { ticker: "CNHI", name: "CNH Industrial", sector: "Industrials", type: "stock" },
  { ticker: "TTC", name: "Toro Company", sector: "Industrials", type: "stock" },
  { ticker: "SNA", name: "Snap-on", sector: "Industrials", type: "stock" },
  { ticker: "GWW", name: "W.W. Grainger", sector: "Industrials", type: "stock" },
  { ticker: "FAST", name: "Fastenal", sector: "Industrials", type: "stock" },
  { ticker: "MSM", name: "MSC Industrial", sector: "Industrials", type: "stock" },
  { ticker: "AIT", name: "Applied Industrial", sector: "Industrials", type: "stock" },
  { ticker: "WCC", name: "WESCO International", sector: "Industrials", type: "stock" },
  { ticker: "ETN", name: "Eaton Corporation", sector: "Industrials", type: "stock" },
  { ticker: "APH", name: "Amphenol", sector: "Technology", type: "stock" },
  { ticker: "TEL", name: "TE Connectivity", sector: "Technology", type: "stock" },
  { ticker: "GLW", name: "Corning", sector: "Technology", type: "stock" },
  { ticker: "JCI", name: "Johnson Controls", sector: "Industrials", type: "stock" },
  { ticker: "TT", name: "Trane Technologies", sector: "Industrials", type: "stock" },
  { ticker: "LII", name: "Lennox International", sector: "Industrials", type: "stock" },
  { ticker: "CARR", name: "Carrier Global", sector: "Industrials", type: "stock" },
  { ticker: "GNRC", name: "Generac", sector: "Industrials", type: "stock" },
  { ticker: "AOS", name: "A. O. Smith", sector: "Industrials", type: "stock" },
  { ticker: "MAS", name: "Masco", sector: "Industrials", type: "stock" },
  { ticker: "FBHS", name: "Fortune Brands", sector: "Industrials", type: "stock" },
  { ticker: "OC", name: "Owens Corning", sector: "Materials", type: "stock" },
  { ticker: "VMC", name: "Vulcan Materials", sector: "Materials", type: "stock" },
  { ticker: "MLM", name: "Martin Marietta", sector: "Materials", type: "stock" },
  { ticker: "EXP", name: "Eagle Materials", sector: "Materials", type: "stock" },
  { ticker: "SUM", name: "Summit Materials", sector: "Materials", type: "stock" },
  { ticker: "APG", name: "APi Group", sector: "Industrials", type: "stock" },
  { ticker: "AAON", name: "AAON Inc", sector: "Industrials", type: "stock" },
  { ticker: "WMS", name: "Advanced Drainage", sector: "Industrials", type: "stock" },
  { ticker: "SITE", name: "SiteOne Landscape", sector: "Industrials", type: "stock" },
  { ticker: "BLDR", name: "Builders FirstSource", sector: "Industrials", type: "stock" },
  { ticker: "BLD", name: "TopBuild", sector: "Industrials", type: "stock" },
  { ticker: "TREX", name: "Trex Company", sector: "Materials", type: "stock" },
  { ticker: "AZEK", name: "AZEK Company", sector: "Materials", type: "stock" },
  { ticker: "AWI", name: "Armstrong World", sector: "Materials", type: "stock" },
  { ticker: "FND", name: "Floor & Decor", sector: "Consumer", type: "stock" },
  { ticker: "LL", name: "LL Flooring", sector: "Consumer", type: "stock" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", type: "stock" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials", type: "stock" },
  { ticker: "RPM", name: "RPM International", sector: "Materials", type: "stock" },
  { ticker: "ECL", name: "Ecolab", sector: "Materials", type: "stock" },
  { ticker: "ALB", name: "Albemarle", sector: "Materials", type: "stock" },
  { ticker: "LTHM", name: "Livent", sector: "Materials", type: "stock" },
  { ticker: "LAC", name: "Lithium Americas", sector: "Materials", type: "stock" },
  { ticker: "MP", name: "MP Materials", sector: "Materials", type: "stock" },
  { ticker: "GOLD", name: "Barrick Gold", sector: "Mining", type: "stock" },
  { ticker: "NEM", name: "Newmont", sector: "Mining", type: "stock" },
  { ticker: "FNV", name: "Franco-Nevada", sector: "Mining", type: "stock" },
  { ticker: "WPM", name: "Wheaton Precious Metals", sector: "Mining", type: "stock" },
  { ticker: "AEM", name: "Agnico Eagle", sector: "Mining", type: "stock" },
  { ticker: "KGC", name: "Kinross Gold", sector: "Mining", type: "stock" },
  { ticker: "RGLD", name: "Royal Gold", sector: "Mining", type: "stock" },
  { ticker: "PAAS", name: "Pan American Silver", sector: "Mining", type: "stock" },
  { ticker: "AG", name: "First Majestic Silver", sector: "Mining", type: "stock" },
  { ticker: "CDE", name: "Coeur Mining", sector: "Mining", type: "stock" },
  { ticker: "HL", name: "Hecla Mining", sector: "Mining", type: "stock" },
  { ticker: "BTG", name: "B2Gold", sector: "Mining", type: "stock" },
  { ticker: "EGO", name: "Eldorado Gold", sector: "Mining", type: "stock" },
  { ticker: "TECK", name: "Teck Resources", sector: "Mining", type: "stock" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Mining", type: "stock" },
  { ticker: "SCCO", name: "Southern Copper", sector: "Mining", type: "stock" },
  { ticker: "CLF", name: "Cleveland-Cliffs", sector: "Mining", type: "stock" },
  { ticker: "X", name: "United States Steel", sector: "Materials", type: "stock" },
  { ticker: "NUE", name: "Nucor", sector: "Materials", type: "stock" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials", type: "stock" },
  { ticker: "RS", name: "Reliance Steel", sector: "Materials", type: "stock" },
  { ticker: "CMC", name: "Commercial Metals", sector: "Materials", type: "stock" },
  { ticker: "ATI", name: "ATI Inc", sector: "Materials", type: "stock" },
  { ticker: "HAYW", name: "Haynes International", sector: "Materials", type: "stock" },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Finance", type: "stock" },
  { ticker: "BAC", name: "Bank of America", sector: "Finance", type: "stock" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Finance", type: "stock" },
  { ticker: "C", name: "Citigroup", sector: "Finance", type: "stock" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Finance", type: "stock" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Finance", type: "stock" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Finance", type: "stock" },
  { ticker: "BLK", name: "BlackRock", sector: "Finance", type: "stock" },
  { ticker: "BX", name: "Blackstone", sector: "Finance", type: "stock" },
  { ticker: "KKR", name: "KKR & Co", sector: "Finance", type: "stock" },
  { ticker: "APO", name: "Apollo Global", sector: "Finance", type: "stock" },
  { ticker: "CG", name: "Carlyle Group", sector: "Finance", type: "stock" },
  { ticker: "ARES", name: "Ares Management", sector: "Finance", type: "stock" },
  { ticker: "OWL", name: "Blue Owl Capital", sector: "Finance", type: "stock" },
  { ticker: "AMP", name: "Ameriprise Financial", sector: "Finance", type: "stock" },
  { ticker: "RJF", name: "Raymond James", sector: "Finance", type: "stock" },
  { ticker: "LPLA", name: "LPL Financial", sector: "Finance", type: "stock" },
  { ticker: "IBKR", name: "Interactive Brokers", sector: "Finance", type: "stock" },
  { ticker: "MKTX", name: "MarketAxess", sector: "Finance", type: "stock" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Finance", type: "stock" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Finance", type: "stock" },
  { ticker: "CME", name: "CME Group", sector: "Finance", type: "stock" },
  { ticker: "NDAQ", name: "Nasdaq", sector: "Finance", type: "stock" },
  { ticker: "FIS", name: "Fidelity National", sector: "Finance", type: "stock" },
  { ticker: "FISV", name: "Fiserv", sector: "Finance", type: "stock" },
  { ticker: "GPN", name: "Global Payments", sector: "Finance", type: "stock" },
  { ticker: "PYPL", name: "PayPal", sector: "Finance", type: "stock" },
  { ticker: "SQ", name: "Block Inc", sector: "Finance", type: "stock" },
  { ticker: "V", name: "Visa", sector: "Finance", type: "stock" },
  { ticker: "MA", name: "Mastercard", sector: "Finance", type: "stock" },
  { ticker: "AXP", name: "American Express", sector: "Finance", type: "stock" },
  { ticker: "DFS", name: "Discover Financial", sector: "Finance", type: "stock" },
  { ticker: "COF", name: "Capital One", sector: "Finance", type: "stock" },
  { ticker: "SYF", name: "Synchrony Financial", sector: "Finance", type: "stock" },
  { ticker: "ALLY", name: "Ally Financial", sector: "Finance", type: "stock" },
  { ticker: "LC", name: "LendingClub", sector: "Finance", type: "stock" },
  { ticker: "WU", name: "Western Union", sector: "Finance", type: "stock" },
  { ticker: "VIRT", name: "Virtu Financial", sector: "Finance", type: "stock" },
  { ticker: "TW", name: "Tradeweb Markets", sector: "Finance", type: "stock" },
  { ticker: "EVR", name: "Evercore", sector: "Finance", type: "stock" },
  { ticker: "HLI", name: "Houlihan Lokey", sector: "Finance", type: "stock" },
  { ticker: "PJT", name: "PJT Partners", sector: "Finance", type: "stock" },
  { ticker: "LAZ", name: "Lazard", sector: "Finance", type: "stock" },
  { ticker: "MC", name: "Moelis & Company", sector: "Finance", type: "stock" },
  { ticker: "ALL", name: "Allstate", sector: "Finance", type: "stock" },
  { ticker: "PGR", name: "Progressive", sector: "Finance", type: "stock" },
  { ticker: "TRV", name: "Travelers", sector: "Finance", type: "stock" },
  { ticker: "CB", name: "Chubb", sector: "Finance", type: "stock" },
  { ticker: "AIG", name: "AIG", sector: "Finance", type: "stock" },
  { ticker: "MET", name: "MetLife", sector: "Finance", type: "stock" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Finance", type: "stock" },
  { ticker: "AFL", name: "Aflac", sector: "Finance", type: "stock" },
  { ticker: "GL", name: "Globe Life", sector: "Finance", type: "stock" },
  { ticker: "UNM", name: "Unum Group", sector: "Finance", type: "stock" },
  { ticker: "LNC", name: "Lincoln National", sector: "Finance", type: "stock" },
  { ticker: "CINF", name: "Cincinnati Financial", sector: "Finance", type: "stock" },
  { ticker: "RE", name: "Everest Re Group", sector: "Finance", type: "stock" },
  { ticker: "RNR", name: "RenaissanceRe", sector: "Finance", type: "stock" },
  { ticker: "ACGL", name: "Arch Capital", sector: "Finance", type: "stock" },
  { ticker: "WRB", name: "Berkley", sector: "Finance", type: "stock" },
  { ticker: "MCY", name: "Mercury General", sector: "Finance", type: "stock" },
  { ticker: "HIG", name: "Hartford Financial", sector: "Finance", type: "stock" },
  { ticker: "BRO", name: "Brown & Brown", sector: "Finance", type: "stock" },
  { ticker: "AON", name: "Aon", sector: "Finance", type: "stock" },
  { ticker: "MMC", name: "Marsh & McLennan", sector: "Finance", type: "stock" },
  { ticker: "AJG", name: "Arthur J. Gallagher", sector: "Finance", type: "stock" },
  { ticker: "WTW", name: "Willis Towers Watson", sector: "Finance", type: "stock" },
  { ticker: "MSFT", name: "Microsoft", sector: "Technology", type: "stock" },
  { ticker: "AAPL", name: "Apple", sector: "Technology", type: "stock" },
  { ticker: "GOOGL", name: "Alphabet", sector: "Technology", type: "stock" },
  { ticker: "META", name: "Meta Platforms", sector: "Technology", type: "stock" },
  { ticker: "AMZN", name: "Amazon", sector: "Technology", type: "stock" },
  { ticker: "NVDA", name: "NVIDIA", sector: "Technology", type: "stock" },
  { ticker: "TSM", name: "TSMC ADR", sector: "Technology", type: "stock" },
  { ticker: "AVGO", name: "Broadcom", sector: "Technology", type: "stock" },
  { ticker: "ORCL", name: "Oracle", sector: "Technology", type: "stock" },
  { ticker: "CRM", name: "Salesforce", sector: "Technology", type: "stock" },
  { ticker: "ADBE", name: "Adobe", sector: "Technology", type: "stock" },
  { ticker: "INTU", name: "Intuit", sector: "Technology", type: "stock" },
  { ticker: "NOW", name: "ServiceNow", sector: "Technology", type: "stock" },
  { ticker: "TEAM", name: "Atlassian", sector: "Technology", type: "stock" },
  { ticker: "CDNS", name: "Cadence Design", sector: "Technology", type: "stock" },
  { ticker: "SNPS", name: "Synopsys", sector: "Technology", type: "stock" },
  { ticker: "ANSS", name: "ANSYS", sector: "Technology", type: "stock" },
  { ticker: "KEYS", name: "Keysight Technologies", sector: "Technology", type: "stock" },
  { ticker: "TER", name: "Teradyne", sector: "Technology", type: "stock" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology", type: "stock" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology", type: "stock" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology", type: "stock" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", type: "stock" },
  { ticker: "QCOM", name: "Qualcomm", sector: "Technology", type: "stock" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", type: "stock" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology", type: "stock" },
  { ticker: "NXPI", name: "NXP Semiconductors", sector: "Technology", type: "stock" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology", type: "stock" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology", type: "stock" },
  { ticker: "QRVO", name: "Qorvo", sector: "Technology", type: "stock" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology", type: "stock" },
  { ticker: "INTC", name: "Intel", sector: "Technology", type: "stock" },
  { ticker: "AMD", name: "AMD", sector: "Technology", type: "stock" },
  { ticker: "ARM", name: "Arm Holdings", sector: "Technology", type: "stock" },
  { ticker: "WOLF", name: "Wolfspeed", sector: "Technology", type: "stock" },
  { ticker: "ACLS", name: "Axcelis Technologies", sector: "Technology", type: "stock" },
  { ticker: "AEHR", name: "Aehr Test Systems", sector: "Technology", type: "stock" },
  { ticker: "FORM", name: "FormFactor", sector: "Technology", type: "stock" },
  { ticker: "MKSI", name: "MKS Instruments", sector: "Technology", type: "stock" },
  { ticker: "ENTG", name: "Entegris", sector: "Technology", type: "stock" },
  { ticker: "CRUS", name: "Cirrus Logic", sector: "Technology", type: "stock" },
  { ticker: "SLAB", name: "Silicon Laboratories", sector: "Technology", type: "stock" },
  { ticker: "MPWR", name: "Monolithic Power", sector: "Technology", type: "stock" },
  { ticker: "RMBS", name: "Rambus", sector: "Technology", type: "stock" },
  { ticker: "ONTO", name: "Onto Innovation", sector: "Technology", type: "stock" },
  { ticker: "COHR", name: "Coherent", sector: "Technology", type: "stock" },
  { ticker: "LITE", name: "Lumentum", sector: "Technology", type: "stock" },
  { ticker: "IIVI", name: "II-VI", sector: "Technology", type: "stock" },
  { ticker: "CIEN", name: "Ciena", sector: "Technology", type: "stock" },
  { ticker: "VIAV", name: "Viavi Solutions", sector: "Technology", type: "stock" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", type: "stock" },
  { ticker: "JNPR", name: "Juniper Networks", sector: "Technology", type: "stock" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology", type: "stock" },
  { ticker: "FFIV", name: "F5 Networks", sector: "Technology", type: "stock" },
  { ticker: "NTCT", name: "NetScout Systems", sector: "Technology", type: "stock" },
  { ticker: "CALX", name: "Calix", sector: "Technology", type: "stock" },
  { ticker: "ASAN", name: "Asana", sector: "Technology", type: "stock" },
  { ticker: "FROG", name: "JFrog", sector: "Technology", type: "stock" },
  { ticker: "MNDY", name: "monday.com", sector: "Technology", type: "stock" },
  { ticker: "ZM", name: "Zoom Video", sector: "Technology", type: "stock" },
  { ticker: "DOCU", name: "DocuSign", sector: "Technology", type: "stock" },
  { ticker: "BOX", name: "Box", sector: "Technology", type: "stock" },
  { ticker: "DBX", name: "Dropbox", sector: "Technology", type: "stock" },
  { ticker: "OKTA", name: "Okta", sector: "Technology", type: "stock" },
  { ticker: "TENB", name: "Tenable", sector: "Technology", type: "stock" },
  { ticker: "RPD", name: "Rapid7", sector: "Technology", type: "stock" },
  { ticker: "CYBR", name: "CyberArk", sector: "Technology", type: "stock" },
  { ticker: "QLYS", name: "Qualys", sector: "Technology", type: "stock" },
  { ticker: "VRNS", name: "Varonis Systems", sector: "Technology", type: "stock" },
  { ticker: "S", name: "SentinelOne", sector: "Technology", type: "stock" },
  { ticker: "AKAM", name: "Akamai Technologies", sector: "Technology", type: "stock" },
  { ticker: "FSLY", name: "Fastly", sector: "Technology", type: "stock" },
  { ticker: "SPT", name: "Sprout Social", sector: "Technology", type: "stock" },
  { ticker: "TWST", name: "Twist Bioscience", sector: "Healthcare", type: "stock" },
  { ticker: "CRSP", name: "CRISPR Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "NTLA", name: "Intellia Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "EDIT", name: "Editas Medicine", sector: "Healthcare", type: "stock" },
  { ticker: "BEAM", name: "Beam Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "VERV", name: "Verve Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "PCVX", name: "Vaxcyte", sector: "Healthcare", type: "stock" },
  { ticker: "MRNA", name: "Moderna", sector: "Healthcare", type: "stock" },
  { ticker: "BNTX", name: "BioNTech", sector: "Healthcare", type: "stock" },
  { ticker: "PFE", name: "Pfizer", sector: "Healthcare", type: "stock" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", type: "stock" },
  { ticker: "LLY", name: "Eli Lilly", sector: "Healthcare", type: "stock" },
  { ticker: "ABBV", name: "AbbVie", sector: "Healthcare", type: "stock" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", type: "stock" },
  { ticker: "MRK", name: "Merck", sector: "Healthcare", type: "stock" },
  { ticker: "AMGN", name: "Amgen", sector: "Healthcare", type: "stock" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "REGN", name: "Regeneron", sector: "Healthcare", type: "stock" },
  { ticker: "VRTX", name: "Vertex", sector: "Healthcare", type: "stock" },
  { ticker: "BIIB", name: "Biogen", sector: "Healthcare", type: "stock" },
  { ticker: "ALNY", name: "Alnylam", sector: "Healthcare", type: "stock" },
  { ticker: "SGEN", name: "Seagen", sector: "Healthcare", type: "stock" },
  { ticker: "EXAS", name: "Exact Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "NTRA", name: "Natera", sector: "Healthcare", type: "stock" },
  { ticker: "GH", name: "Guardant Health", sector: "Healthcare", type: "stock" },
  { ticker: "SDGR", name: "Schrodinger", sector: "Healthcare", type: "stock" },
  { ticker: "RXRX", name: "Recursion Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "DNA", name: "Ginkgo Bioworks", sector: "Healthcare", type: "stock" },
  { ticker: "EVTL", name: "Vertical Aerospace", sector: "Industrials", type: "stock" },
  { ticker: "JOBY", name: "Joby Aviation", sector: "Industrials", type: "stock" },
  { ticker: "ACHR", name: "Archer Aviation", sector: "Industrials", type: "stock" },
  { ticker: "LILM", name: "Lilium", sector: "Industrials", type: "stock" },
  { ticker: "BLDE", name: "Blade Air Mobility", sector: "Industrials", type: "stock" },
  { ticker: "BA", name: "Boeing", sector: "Industrials", type: "stock" },
  { ticker: "EADSY", name: "Airbus ADR", sector: "Industrials", type: "stock" },
  { ticker: "ERJ", name: "Embraer", sector: "Industrials", type: "stock" },
  { ticker: "SPR", name: "Spirit AeroSystems", sector: "Industrials", type: "stock" },
  { ticker: "HXL", name: "Hexcel", sector: "Materials", type: "stock" },
  { ticker: "TGI", name: "Triumph Group", sector: "Industrials", type: "stock" },
  { ticker: "KTOS", name: "Kratos Defense", sector: "Industrials", type: "stock" },
  { ticker: "AVAV", name: "AeroVironment", sector: "Industrials", type: "stock" },
  { ticker: "BWXT", name: "BWX Technologies", sector: "Industrials", type: "stock" },
  { ticker: "CW", name: "Curtiss-Wright", sector: "Industrials", type: "stock" },
  { ticker: "HEI", name: "HEICO", sector: "Industrials", type: "stock" },
  { ticker: "AXON", name: "Axon Enterprise", sector: "Industrials", type: "stock" },
  { ticker: "CGNX", name: "Cognex", sector: "Technology", type: "stock" },
  { ticker: "TYL", name: "Tyler Technologies", sector: "Technology", type: "stock" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Technology", type: "stock" },
  { ticker: "FI", name: "Fiserv", sector: "Technology", type: "stock" },
  { ticker: "IT", name: "Gartner", sector: "Technology", type: "stock" },
  { ticker: "EPAM", name: "EPAM Systems", sector: "Technology", type: "stock" },
  { ticker: "GLOB", name: "Globant", sector: "Technology", type: "stock" },
  { ticker: "PAYC", name: "Paycom Software", sector: "Technology", type: "stock" },
  { ticker: "PCTY", name: "Paylocity", sector: "Technology", type: "stock" },
  { ticker: "PAYX", name: "Paychex", sector: "Technology", type: "stock" },
  { ticker: "ADP", name: "ADP", sector: "Technology", type: "stock" },
  { ticker: "CDAY", name: "Ceridian HCM", sector: "Technology", type: "stock" },
  { ticker: "WEX", name: "WEX Inc", sector: "Technology", type: "stock" },
  { ticker: "FLYW", name: "Flywire", sector: "Technology", type: "stock" },
  { ticker: "FOUR", name: "Shift4 Payments", sector: "Technology", type: "stock" },
  { ticker: "TOST", name: "Toast", sector: "Technology", type: "stock" },
  { ticker: "SHC", name: "Sotera Health", sector: "Healthcare", type: "stock" },
  { ticker: "AZTA", name: "Azenta", sector: "Healthcare", type: "stock" },
  { ticker: "BIO", name: "Bio-Rad Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "TECH", name: "Bio-Techne", sector: "Healthcare", type: "stock" },
  { ticker: "RGEN", name: "Repligen", sector: "Healthcare", type: "stock" },
  { ticker: "TFX", name: "Teleflex", sector: "Healthcare", type: "stock" },
  { ticker: "HOLX", name: "Hologic", sector: "Healthcare", type: "stock" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare", type: "stock" },
  { ticker: "XRAY", name: "Dentsply Sirona", sector: "Healthcare", type: "stock" },
  { ticker: "HSIC", name: "Henry Schein", sector: "Healthcare", type: "stock" },
  { ticker: "PDCO", name: "Patterson Companies", sector: "Healthcare", type: "stock" },
  { ticker: "OMI", name: "Owens & Minor", sector: "Healthcare", type: "stock" },
  { ticker: "MCK", name: "McKesson", sector: "Healthcare", type: "stock" },
  { ticker: "ABC", name: "AmerisourceBergen", sector: "Healthcare", type: "stock" },
  { ticker: "CAH", name: "Cardinal Health", sector: "Healthcare", type: "stock" },
  { ticker: "APPN", name: "Appian", sector: "Technology", type: "stock" },
  { ticker: "PEGA", name: "Pegasystems", sector: "Technology", type: "stock" },
  { ticker: "BSY", name: "Bentley Systems", sector: "Technology", type: "stock" },
  { ticker: "PTC", name: "PTC", sector: "Technology", type: "stock" },
  { ticker: "ALTR", name: "Altair Engineering", sector: "Technology", type: "stock" },
  { ticker: "DSGX", name: "Descartes Systems", sector: "Technology", type: "stock" },
  { ticker: "MANH", name: "Manhattan Associates", sector: "Technology", type: "stock" },
  { ticker: "FIVE9", name: "Five9", sector: "Technology", type: "stock" },
  { ticker: "NICE", name: "NICE", sector: "Technology", type: "stock" },
  { ticker: "CCSI", name: "Consensus Cloud", sector: "Technology", type: "stock" },
  { ticker: "DCT", name: "Duck Creek Technologies", sector: "Technology", type: "stock" },
  { ticker: "QTWO", name: "Q2 Holdings", sector: "Technology", type: "stock" },
  { ticker: "NCNO", name: "nCino", sector: "Technology", type: "stock" },
  { ticker: "ALKT", name: "Alkami Technology", sector: "Technology", type: "stock" },
  { ticker: "PRFT", name: "Perficient", sector: "Technology", type: "stock" },
  { ticker: "TASK", name: "TaskUs", sector: "Technology", type: "stock" },
  { ticker: "TTEC", name: "TTEC Holdings", sector: "Technology", type: "stock" },
  { ticker: "CNXC", name: "Concentrix", sector: "Technology", type: "stock" },
  { ticker: "ACN", name: "Accenture", sector: "Technology", type: "stock" },
  { ticker: "IBM", name: "IBM", sector: "Technology", type: "stock" },
  { ticker: "CTSH", name: "Cognizant", sector: "Technology", type: "stock" },
  { ticker: "DXC", name: "DXC Technology", sector: "Technology", type: "stock" },
  { ticker: "LDOS", name: "Leidos", sector: "Technology", type: "stock" },
  { ticker: "SAIC", name: "SAIC", sector: "Technology", type: "stock" },
  { ticker: "BAH", name: "Booz Allen Hamilton", sector: "Technology", type: "stock" },
  { ticker: "CACI", name: "CACI International", sector: "Technology", type: "stock" },
  { ticker: "GOOG", name: "Alphabet Class C", sector: "Technology", type: "stock" },
];
