import type { AssetEntry } from "./types";

// Expansion 4: Additional mid-caps, emerging markets, and global assets to reach 10,000+
export const expansion4: AssetEntry[] = [
  // === US Small/Mid Caps ===
  { ticker: "BILL", name: "Bill Holdings", sector: "Technology", type: "stock" },
  { ticker: "GTLB", name: "GitLab", sector: "Technology", type: "stock" },
  { ticker: "BRZE", name: "Braze", sector: "Technology", type: "stock" },
  { ticker: "CFLT", name: "Confluent", sector: "Technology", type: "stock" },
  { ticker: "ESTC", name: "Elastic", sector: "Technology", type: "stock" },
  { ticker: "FRSH", name: "Freshworks", sector: "Technology", type: "stock" },
  { ticker: "JAMF", name: "Jamf Holding", sector: "Technology", type: "stock" },
  { ticker: "KARO", name: "Karooooo", sector: "Technology", type: "stock" },
  { ticker: "LSPD", name: "Lightspeed Commerce", sector: "Technology", type: "stock" },
  { ticker: "MNDY", name: "Monday.com", sector: "Technology", type: "stock" },
  { ticker: "NCNO", name: "nCino", sector: "Technology", type: "stock" },
  { ticker: "QLYS", name: "Qualys", sector: "Technology", type: "stock" },
  { ticker: "RBRK", name: "Rubrik", sector: "Technology", type: "stock" },
  { ticker: "SEMR", name: "Semrush Holdings", sector: "Technology", type: "stock" },
  { ticker: "TOST", name: "Toast", sector: "Technology", type: "stock" },
  { ticker: "WK", name: "Workiva", sector: "Technology", type: "stock" },
  { ticker: "XPEL", name: "XPEL", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "YEXT", name: "Yext", sector: "Technology", type: "stock" },
  { ticker: "ZI", name: "ZoomInfo Technologies", sector: "Technology", type: "stock" },
  { ticker: "ZETA", name: "Zeta Global", sector: "Technology", type: "stock" },
  { ticker: "APPF", name: "AppFolio", sector: "Technology", type: "stock" },
  { ticker: "CWAN", name: "Clearwater Analytics", sector: "Technology", type: "stock" },
  { ticker: "DLO", name: "DLocal", sector: "Financials", type: "stock" },
  { ticker: "FLYW", name: "Flywire", sector: "Financials", type: "stock" },
  { ticker: "FOUR", name: "Shift4 Payments", sector: "Financials", type: "stock" },
  { ticker: "GENI", name: "Genius Sports", sector: "Technology", type: "stock" },
  { ticker: "HIMS", name: "Hims & Hers Health", sector: "Healthcare", type: "stock" },
  { ticker: "INTA", name: "Intapp", sector: "Technology", type: "stock" },
  { ticker: "KNF", name: "Knife River", sector: "Industrials", type: "stock" },
  { ticker: "KVYO", name: "Klaviyo", sector: "Technology", type: "stock" },
  { ticker: "LITE", name: "Lumentum Holdings", sector: "Technology", type: "stock" },
  { ticker: "MARA", name: "Marathon Digital", sector: "Technology", type: "stock" },
  { ticker: "NUVB", name: "Nuvation Bio", sector: "Healthcare", type: "stock" },
  { ticker: "OLPX", name: "Olaplex Holdings", sector: "Consumer Staples", type: "stock" },
  { ticker: "PAYO", name: "Payoneer Global", sector: "Financials", type: "stock" },
  { ticker: "PCVX", name: "Vaxcyte", sector: "Healthcare", type: "stock" },
  { ticker: "RELY", name: "Remitly Global", sector: "Financials", type: "stock" },
  { ticker: "RXRX", name: "Recursion Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "SDGR", name: "Schrödinger", sector: "Healthcare", type: "stock" },
  { ticker: "SOUN", name: "SoundHound AI", sector: "Technology", type: "stock" },
  { ticker: "SPSC", name: "SPS Commerce", sector: "Technology", type: "stock" },
  { ticker: "STEP", name: "StepStone Group", sector: "Financials", type: "stock" },
  { ticker: "TASK", name: "TaskUs", sector: "Technology", type: "stock" },
  { ticker: "VERX", name: "Vertex Inc", sector: "Technology", type: "stock" },
  { ticker: "VNET", name: "VNET Group", sector: "Technology", type: "stock" },
  { ticker: "WFRD", name: "Weatherford Intl", sector: "Energy", type: "stock" },
  { ticker: "XRX", name: "Xerox Holdings", sector: "Technology", type: "stock" },
  { ticker: "YORW", name: "York Water", sector: "Utilities", type: "stock" },
  { ticker: "ZENV", name: "Zenvia", sector: "Technology", type: "stock" },
  { ticker: "AAON", name: "AAON Inc", sector: "Industrials", type: "stock" },

  // === Mexico (BMV) ===
  { ticker: "FEMSAUBD.MX", name: "FEMSA", sector: "Consumer Staples", type: "stock" },
  { ticker: "GFNORTEO.MX", name: "Grupo Financiero Banorte", sector: "Financials", type: "stock" },
  { ticker: "CEMEXCPO.MX", name: "CEMEX", sector: "Materials", type: "stock" },
  { ticker: "WALMEX.MX", name: "Walmart de México", sector: "Consumer Staples", type: "stock" },
  { ticker: "GMEXICOB.MX", name: "Grupo México", sector: "Materials", type: "stock" },
  { ticker: "TLOVISACPO.MX", name: "Televisa", sector: "Communication", type: "stock" },
  { ticker: "KIMBERA.MX", name: "Kimberly-Clark de México", sector: "Consumer Staples", type: "stock" },
  { ticker: "BIMBOA.MX", name: "Grupo Bimbo", sector: "Consumer Staples", type: "stock" },
  { ticker: "AC.MX", name: "Arca Continental", sector: "Consumer Staples", type: "stock" },
  { ticker: "ALSEA.MX", name: "Alsea", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "GRUMAB.MX", name: "Gruma", sector: "Consumer Staples", type: "stock" },
  { ticker: "LIVEPOLC-1.MX", name: "El Puerto de Liverpool", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "MEGACPO.MX", name: "Megacable Holdings", sector: "Communication", type: "stock" },
  { ticker: "OMAB.MX", name: "OMA Aeropuertos", sector: "Industrials", type: "stock" },
  { ticker: "PINFRA.MX", name: "Pinfra", sector: "Industrials", type: "stock" },
  { ticker: "GCARSOA1.MX", name: "Grupo Carso", sector: "Industrials", type: "stock" },
  { ticker: "ELEKTRA.MX", name: "Grupo Elektra", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "CABORCRB.MX", name: "Cementos Moctezuma", sector: "Materials", type: "stock" },
  { ticker: "ASURB.MX", name: "ASUR Aeropuertos", sector: "Industrials", type: "stock" },
  { ticker: "GAPB.MX", name: "GAP Aeropuertos", sector: "Industrials", type: "stock" },

  // === South Africa (JSE) ===
  { ticker: "NPN.JO", name: "Naspers", sector: "Technology", type: "stock" },
  { ticker: "PRX.JO", name: "Prosus", sector: "Technology", type: "stock" },
  { ticker: "AGL.JO", name: "Anglo American Platinum", sector: "Materials", type: "stock" },
  { ticker: "BHP.JO", name: "BHP Group JSE", sector: "Materials", type: "stock" },
  { ticker: "SOL.JO", name: "Sasol", sector: "Energy", type: "stock" },
  { ticker: "SBK.JO", name: "Standard Bank Group", sector: "Financials", type: "stock" },
  { ticker: "FSR.JO", name: "FirstRand", sector: "Financials", type: "stock" },
  { ticker: "NED.JO", name: "Nedbank Group", sector: "Financials", type: "stock" },
  { ticker: "ABG.JO", name: "Absa Group", sector: "Financials", type: "stock" },
  { ticker: "CPI.JO", name: "Capitec Bank", sector: "Financials", type: "stock" },
  { ticker: "SHP.JO", name: "Shoprite Holdings", sector: "Consumer Staples", type: "stock" },
  { ticker: "SLM.JO", name: "Sanlam", sector: "Financials", type: "stock" },
  { ticker: "DSY.JO", name: "Discovery", sector: "Financials", type: "stock" },
  { ticker: "MTN.JO", name: "MTN Group", sector: "Communication", type: "stock" },
  { ticker: "VOD.JO", name: "Vodacom Group", sector: "Communication", type: "stock" },
  { ticker: "AMS.JO", name: "Anglo American", sector: "Materials", type: "stock" },
  { ticker: "BID.JO", name: "Bid Corporation", sector: "Consumer Staples", type: "stock" },
  { ticker: "MRP.JO", name: "Mr Price Group", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "WHL.JO", name: "Woolworths Holdings", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "TFG.JO", name: "The Foschini Group", sector: "Consumer Discretionary", type: "stock" },

  // === Southeast Asia ===
  { ticker: "BBCA.JK", name: "Bank Central Asia", sector: "Financials", type: "stock" },
  { ticker: "BBRI.JK", name: "Bank Rakyat Indonesia", sector: "Financials", type: "stock" },
  { ticker: "BMRI.JK", name: "Bank Mandiri", sector: "Financials", type: "stock" },
  { ticker: "TLKM.JK", name: "Telkom Indonesia", sector: "Communication", type: "stock" },
  { ticker: "ASII.JK", name: "Astra International", sector: "Industrials", type: "stock" },
  { ticker: "UNVR.JK", name: "Unilever Indonesia", sector: "Consumer Staples", type: "stock" },
  { ticker: "ICBP.JK", name: "Indofood CBP", sector: "Consumer Staples", type: "stock" },
  { ticker: "KLBF.JK", name: "Kalbe Farma", sector: "Healthcare", type: "stock" },
  { ticker: "CPIN.JK", name: "Charoen Pokphand Indonesia", sector: "Consumer Staples", type: "stock" },
  { ticker: "EMTK.JK", name: "Elang Mahkota Teknologi", sector: "Technology", type: "stock" },
  { ticker: "PGAS.JK", name: "Perusahaan Gas Negara", sector: "Utilities", type: "stock" },
  { ticker: "EXCL.JK", name: "XL Axiata", sector: "Communication", type: "stock" },
  { ticker: "INDF.JK", name: "Indofood Sukses Makmur", sector: "Consumer Staples", type: "stock" },
  { ticker: "GGRM.JK", name: "Gudang Garam", sector: "Consumer Staples", type: "stock" },
  { ticker: "HMSP.JK", name: "HM Sampoerna", sector: "Consumer Staples", type: "stock" },
  { ticker: "SMGR.JK", name: "Semen Indonesia", sector: "Materials", type: "stock" },
  { ticker: "PTBA.JK", name: "Bukit Asam", sector: "Energy", type: "stock" },
  { ticker: "ADRO.JK", name: "Adaro Energy", sector: "Energy", type: "stock" },
  { ticker: "ANTM.JK", name: "Aneka Tambang", sector: "Materials", type: "stock" },
  { ticker: "MDKA.JK", name: "Merdeka Copper Gold", sector: "Materials", type: "stock" },

  // === Thailand (SET) ===
  { ticker: "PTT.BK", name: "PTT Public Company", sector: "Energy", type: "stock" },
  { ticker: "AOT.BK", name: "Airports of Thailand", sector: "Industrials", type: "stock" },
  { ticker: "ADVANC.BK", name: "Advanced Info Service", sector: "Communication", type: "stock" },
  { ticker: "CPALL.BK", name: "CP ALL", sector: "Consumer Staples", type: "stock" },
  { ticker: "SCC.BK", name: "Siam Cement Group", sector: "Materials", type: "stock" },
  { ticker: "BDMS.BK", name: "Bangkok Dusit Medical", sector: "Healthcare", type: "stock" },
  { ticker: "KBANK.BK", name: "Kasikornbank", sector: "Financials", type: "stock" },
  { ticker: "SCB.BK", name: "SCB X", sector: "Financials", type: "stock" },
  { ticker: "MINT.BK", name: "Minor International", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "BH.BK", name: "Bumrungrad Hospital", sector: "Healthcare", type: "stock" },
  { ticker: "GULF.BK", name: "Gulf Energy Development", sector: "Utilities", type: "stock" },
  { ticker: "TRUE.BK", name: "True Corporation", sector: "Communication", type: "stock" },
  { ticker: "CBG.BK", name: "Carabao Group", sector: "Consumer Staples", type: "stock" },
  { ticker: "GPSC.BK", name: "Global Power Synergy", sector: "Utilities", type: "stock" },
  { ticker: "BGRIM.BK", name: "B.Grimm Power", sector: "Utilities", type: "stock" },

  // === Malaysia (KLSE) ===
  { ticker: "1155.KL", name: "Malayan Banking (Maybank)", sector: "Financials", type: "stock" },
  { ticker: "1295.KL", name: "Public Bank Berhad", sector: "Financials", type: "stock" },
  { ticker: "6888.KL", name: "Axiata Group", sector: "Communication", type: "stock" },
  { ticker: "4707.KL", name: "Nestlé Malaysia", sector: "Consumer Staples", type: "stock" },
  { ticker: "3182.KL", name: "Genting Berhad", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "4863.KL", name: "Telekom Malaysia", sector: "Communication", type: "stock" },
  { ticker: "5347.KL", name: "Tenaga Nasional", sector: "Utilities", type: "stock" },
  { ticker: "1023.KL", name: "CIMB Group", sector: "Financials", type: "stock" },
  { ticker: "5183.KL", name: "Petronas Chemicals", sector: "Materials", type: "stock" },
  { ticker: "6012.KL", name: "Maxis Berhad", sector: "Communication", type: "stock" },
  { ticker: "5225.KL", name: "IHH Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "4197.KL", name: "Sime Darby", sector: "Industrials", type: "stock" },
  { ticker: "5168.KL", name: "Hartalega Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "7084.KL", name: "QL Resources", sector: "Consumer Staples", type: "stock" },
  { ticker: "6947.KL", name: "DiGi.Com", sector: "Communication", type: "stock" },

  // === Philippines (PSE) ===
  { ticker: "SM.PS", name: "SM Investments", sector: "Financials", type: "stock" },
  { ticker: "BDO.PS", name: "BDO Unibank", sector: "Financials", type: "stock" },
  { ticker: "TEL.PS", name: "PLDT", sector: "Communication", type: "stock" },
  { ticker: "JFC.PS", name: "Jollibee Foods", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "ALI.PS", name: "Ayala Land", sector: "Real Estate", type: "stock" },
  { ticker: "AC.PS", name: "Ayala Corporation", sector: "Industrials", type: "stock" },
  { ticker: "BPI.PS", name: "Bank of the Philippine Islands", sector: "Financials", type: "stock" },
  { ticker: "MBT.PS", name: "Metropolitan Bank & Trust", sector: "Financials", type: "stock" },
  { ticker: "GLO.PS", name: "Globe Telecom", sector: "Communication", type: "stock" },
  { ticker: "MER.PS", name: "Manila Electric", sector: "Utilities", type: "stock" },
  { ticker: "URC.PS", name: "Universal Robina", sector: "Consumer Staples", type: "stock" },
  { ticker: "SMPH.PS", name: "SM Prime Holdings", sector: "Real Estate", type: "stock" },
  { ticker: "ICT.PS", name: "International Container Terminal", sector: "Industrials", type: "stock" },
  { ticker: "MONDE.PS", name: "Monde Nissin", sector: "Consumer Staples", type: "stock" },
  { ticker: "RLC.PS", name: "Robinsons Land", sector: "Real Estate", type: "stock" },

  // === Vietnam ===
  { ticker: "VNM.VN", name: "Vinamilk", sector: "Consumer Staples", type: "stock" },
  { ticker: "VCB.VN", name: "Vietcombank", sector: "Financials", type: "stock" },
  { ticker: "VHM.VN", name: "Vinhomes", sector: "Real Estate", type: "stock" },
  { ticker: "VIC.VN", name: "Vingroup", sector: "Industrials", type: "stock" },
  { ticker: "HPG.VN", name: "Hoa Phat Group", sector: "Materials", type: "stock" },
  { ticker: "TCB.VN", name: "Techcombank", sector: "Financials", type: "stock" },
  { ticker: "MBB.VN", name: "MB Bank", sector: "Financials", type: "stock" },
  { ticker: "FPT.VN", name: "FPT Corporation", sector: "Technology", type: "stock" },
  { ticker: "MWG.VN", name: "Mobile World Group", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "VRE.VN", name: "Vincom Retail", sector: "Real Estate", type: "stock" },

  // === Colombia ===
  { ticker: "PFBCOLOM.CL", name: "Bancolombia", sector: "Financials", type: "stock" },
  { ticker: "ECOPETROL.CL", name: "Ecopetrol", sector: "Energy", type: "stock" },
  { ticker: "ISA.CL", name: "ISA Interconexión Eléctrica", sector: "Utilities", type: "stock" },
  { ticker: "NUTRESA.CL", name: "Grupo Nutresa", sector: "Consumer Staples", type: "stock" },
  { ticker: "CELSIA.CL", name: "Celsia", sector: "Utilities", type: "stock" },

  // === Peru ===
  { ticker: "BVN", name: "Compañía de Minas Buenaventura", sector: "Materials", type: "stock" },
  { ticker: "SCCO", name: "Southern Copper", sector: "Materials", type: "stock" },
  { ticker: "BAP", name: "Credicorp", sector: "Financials", type: "stock" },

  // === More European Mid-Caps ===
  { ticker: "KNEBV.HE", name: "Kone Oyj", sector: "Industrials", type: "stock" },
  { ticker: "ORNBV.HE", name: "Orion Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "KESKOB.HE", name: "Kesko Oyj", sector: "Consumer Staples", type: "stock" },
  { ticker: "METSB.HE", name: "Metsä Board", sector: "Materials", type: "stock" },
  { ticker: "WRT1V.HE", name: "Wärtsilä", sector: "Industrials", type: "stock" },
  { ticker: "NESTE.HE", name: "Neste Oyj", sector: "Energy", type: "stock" },
  { ticker: "STERV.HE", name: "Stora Enso", sector: "Materials", type: "stock" },
  { ticker: "CGCBV.HE", name: "Cargotec", sector: "Industrials", type: "stock" },
  { ticker: "TIETO.HE", name: "TietoEVRY", sector: "Technology", type: "stock" },
  { ticker: "OUT1V.HE", name: "Outokumpu", sector: "Materials", type: "stock" },

  // === Norway (OSE) ===
  { ticker: "EQNR.OL", name: "Equinor ASA", sector: "Energy", type: "stock" },
  { ticker: "DNB.OL", name: "DNB Bank ASA", sector: "Financials", type: "stock" },
  { ticker: "TEL.OL", name: "Telenor ASA", sector: "Communication", type: "stock" },
  { ticker: "MOWI.OL", name: "Mowi ASA", sector: "Consumer Staples", type: "stock" },
  { ticker: "YAR.OL", name: "Yara International", sector: "Materials", type: "stock" },
  { ticker: "ORK.OL", name: "Orkla ASA", sector: "Consumer Staples", type: "stock" },
  { ticker: "SALM.OL", name: "SalMar ASA", sector: "Consumer Staples", type: "stock" },
  { ticker: "AKER.OL", name: "Aker ASA", sector: "Industrials", type: "stock" },
  { ticker: "SUBC.OL", name: "Subsea 7", sector: "Energy", type: "stock" },
  { ticker: "AKRBP.OL", name: "Aker BP ASA", sector: "Energy", type: "stock" },

  // === Denmark (CPH) ===
  { ticker: "NOVO-B.CO", name: "Novo Nordisk", sector: "Healthcare", type: "stock" },
  { ticker: "MAERSK-B.CO", name: "A.P. Møller-Mærsk", sector: "Industrials", type: "stock" },
  { ticker: "CARL-B.CO", name: "Carlsberg", sector: "Consumer Staples", type: "stock" },
  { ticker: "VWS.CO", name: "Vestas Wind Systems", sector: "Industrials", type: "stock" },
  { ticker: "COLO-B.CO", name: "Coloplast", sector: "Healthcare", type: "stock" },
  { ticker: "DEMANT.CO", name: "Demant", sector: "Healthcare", type: "stock" },
  { ticker: "GN.CO", name: "GN Store Nord", sector: "Healthcare", type: "stock" },
  { ticker: "PNDORA.CO", name: "Pandora", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "DSV.CO", name: "DSV A/S", sector: "Industrials", type: "stock" },
  { ticker: "AMBU-B.CO", name: "Ambu", sector: "Healthcare", type: "stock" },

  // === Poland (WSE) ===
  { ticker: "PKO.WA", name: "PKO Bank Polski", sector: "Financials", type: "stock" },
  { ticker: "PEO.WA", name: "Bank Pekao", sector: "Financials", type: "stock" },
  { ticker: "PKN.WA", name: "PKN Orlen", sector: "Energy", type: "stock" },
  { ticker: "PZU.WA", name: "PZU Group", sector: "Financials", type: "stock" },
  { ticker: "DNP.WA", name: "DINO Polska", sector: "Consumer Staples", type: "stock" },
  { ticker: "KGH.WA", name: "KGHM Polska Miedź", sector: "Materials", type: "stock" },
  { ticker: "CDR.WA", name: "CD Projekt", sector: "Technology", type: "stock" },
  { ticker: "ALE.WA", name: "Allegro.eu", sector: "Technology", type: "stock" },
  { ticker: "LPP.WA", name: "LPP SA", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "SPL.WA", name: "Santander Bank Polska", sector: "Financials", type: "stock" },

  // === Turkey (BIST) ===
  { ticker: "THYAO.IS", name: "Turkish Airlines", sector: "Industrials", type: "stock" },
  { ticker: "GARAN.IS", name: "Garanti BBVA", sector: "Financials", type: "stock" },
  { ticker: "AKBNK.IS", name: "Akbank", sector: "Financials", type: "stock" },
  { ticker: "EREGL.IS", name: "Ereğli Demir Çelik", sector: "Materials", type: "stock" },
  { ticker: "BIMAS.IS", name: "BİM Birleşik Mağazalar", sector: "Consumer Staples", type: "stock" },
  { ticker: "SISE.IS", name: "Şişecam", sector: "Materials", type: "stock" },
  { ticker: "TUPRS.IS", name: "Tüpraş", sector: "Energy", type: "stock" },
  { ticker: "ASELS.IS", name: "Aselsan", sector: "Industrials", type: "stock" },
  { ticker: "KCHOL.IS", name: "Koç Holding", sector: "Industrials", type: "stock" },
  { ticker: "SAHOL.IS", name: "Sabancı Holding", sector: "Industrials", type: "stock" },

  // === Austria (VIE) ===
  { ticker: "VOE.VI", name: "Voestalpine", sector: "Materials", type: "stock" },
  { ticker: "OMV.VI", name: "OMV AG", sector: "Energy", type: "stock" },
  { ticker: "EBS.VI", name: "Erste Group Bank", sector: "Financials", type: "stock" },
  { ticker: "RBI.VI", name: "Raiffeisen Bank International", sector: "Financials", type: "stock" },
  { ticker: "VIG.VI", name: "Vienna Insurance Group", sector: "Financials", type: "stock" },

  // === Czech Republic ===
  { ticker: "CEZ.PR", name: "CEZ Group", sector: "Utilities", type: "stock" },
  { ticker: "KOMB.PR", name: "Komerční banka", sector: "Financials", type: "stock" },

  // === Greece (ATHEX) ===
  { ticker: "ALPHA.AT", name: "Alpha Services and Holdings", sector: "Financials", type: "stock" },
  { ticker: "ETE.AT", name: "National Bank of Greece", sector: "Financials", type: "stock" },
  { ticker: "EUROB.AT", name: "Eurobank Ergasias", sector: "Financials", type: "stock" },
  { ticker: "HTO.AT", name: "Hellenic Telecommunications", sector: "Communication", type: "stock" },
  { ticker: "OPAP.AT", name: "OPAP SA", sector: "Consumer Discretionary", type: "stock" },

  // === Taiwan (TWSE) ===
  { ticker: "2330.TW", name: "TSMC", sector: "Technology", type: "stock" },
  { ticker: "2317.TW", name: "Hon Hai Precision", sector: "Technology", type: "stock" },
  { ticker: "2454.TW", name: "MediaTek", sector: "Technology", type: "stock" },
  { ticker: "2882.TW", name: "Cathay Financial", sector: "Financials", type: "stock" },
  { ticker: "2881.TW", name: "Fubon Financial", sector: "Financials", type: "stock" },
  { ticker: "1301.TW", name: "Formosa Plastics", sector: "Materials", type: "stock" },
  { ticker: "2308.TW", name: "Delta Electronics", sector: "Technology", type: "stock" },
  { ticker: "2412.TW", name: "Chunghwa Telecom", sector: "Communication", type: "stock" },
  { ticker: "2886.TW", name: "Mega Financial", sector: "Financials", type: "stock" },
  { ticker: "3711.TW", name: "ASE Technology", sector: "Technology", type: "stock" },

  // === More US Healthcare ===
  { ticker: "ACAD", name: "Acadia Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "AXSM", name: "Axsome Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "BMRN", name: "BioMarin Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "CORT", name: "Corcept Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "DAWN", name: "Day One Biopharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "FOLD", name: "Amicus Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "GMED", name: "Globus Medical", sector: "Healthcare", type: "stock" },
  { ticker: "HALO", name: "Halozyme Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "IONS", name: "Ionis Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "KRYS", name: "Krystal Biotech", sector: "Healthcare", type: "stock" },
  { ticker: "LEGN", name: "Legend Biotech", sector: "Healthcare", type: "stock" },
  { ticker: "MEDP", name: "Medpace Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "NBIX", name: "Neurocrine Biosciences", sector: "Healthcare", type: "stock" },
  { ticker: "PRCT", name: "PROCEPT BioRobotics", sector: "Healthcare", type: "stock" },

  // === More US Industrials ===
  { ticker: "AIT", name: "Applied Industrial Technologies", sector: "Industrials", type: "stock" },
  { ticker: "BWXT", name: "BWX Technologies", sector: "Industrials", type: "stock" },
  { ticker: "CSWI", name: "CSW Industrials", sector: "Industrials", type: "stock" },
  { ticker: "EAF", name: "GrafTech International", sector: "Industrials", type: "stock" },
  { ticker: "ESAB", name: "ESAB Corporation", sector: "Industrials", type: "stock" },
  { ticker: "FBIN", name: "Fortune Brands Innovations", sector: "Industrials", type: "stock" },
  { ticker: "GGG", name: "Graco Inc", sector: "Industrials", type: "stock" },
  { ticker: "HEI", name: "HEICO Corporation", sector: "Industrials", type: "stock" },
  { ticker: "ITT", name: "ITT Inc", sector: "Industrials", type: "stock" },
  { ticker: "MIDD", name: "The Middleby Corporation", sector: "Industrials", type: "stock" },
  { ticker: "NDSN", name: "Nordson Corporation", sector: "Industrials", type: "stock" },
  { ticker: "RBC", name: "RBC Bearings", sector: "Industrials", type: "stock" },
  { ticker: "SSD", name: "Simpson Manufacturing", sector: "Industrials", type: "stock" },
  { ticker: "TTC", name: "The Toro Company", sector: "Industrials", type: "stock" },
  { ticker: "WSC", name: "WillScot Holdings", sector: "Industrials", type: "stock" },

  // === More US Consumer ===
  { ticker: "BOOT", name: "Boot Barn Holdings", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "CAVA", name: "CAVA Group", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "DKS", name: "Dick's Sporting Goods", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "ELF", name: "e.l.f. Beauty", sector: "Consumer Staples", type: "stock" },
  { ticker: "FIGS", name: "FIGS Inc", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "GIII", name: "G-III Apparel Group", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "ONON", name: "On Holding", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "SHAK", name: "Shake Shack", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "TXRH", name: "Texas Roadhouse", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "WING", name: "Wingstop", sector: "Consumer Discretionary", type: "stock" },
  { ticker: "WOOF", name: "Petco Health and Wellness", sector: "Consumer Discretionary", type: "stock" },

  // === More US Energy ===
  { ticker: "AROC", name: "Archrock Inc", sector: "Energy", type: "stock" },
  { ticker: "CTRA", name: "Coterra Energy", sector: "Energy", type: "stock" },
  { ticker: "DINO", name: "HF Sinclair", sector: "Energy", type: "stock" },
  { ticker: "ERF", name: "Enerplus Corporation", sector: "Energy", type: "stock" },
  { ticker: "GPOR", name: "Gulfport Energy", sector: "Energy", type: "stock" },
  { ticker: "HP", name: "Helmerich & Payne", sector: "Energy", type: "stock" },
  { ticker: "MGY", name: "Magnolia Oil & Gas", sector: "Energy", type: "stock" },
  { ticker: "MTDR", name: "Matador Resources", sector: "Energy", type: "stock" },
  { ticker: "NOG", name: "Northern Oil and Gas", sector: "Energy", type: "stock" },
  { ticker: "OVV", name: "Ovintiv Inc", sector: "Energy", type: "stock" },
  { ticker: "PTEN", name: "Patterson-UTI Energy", sector: "Energy", type: "stock" },
  { ticker: "SM", name: "SM Energy", sector: "Energy", type: "stock" },

  // === More US Financials ===
  { ticker: "ALLY", name: "Ally Financial", sector: "Financials", type: "stock" },
  { ticker: "CACC", name: "Credit Acceptance Corp", sector: "Financials", type: "stock" },
  { ticker: "EWBC", name: "East West Bancorp", sector: "Financials", type: "stock" },
  { ticker: "FNF", name: "Fidelity National Financial", sector: "Financials", type: "stock" },
  { ticker: "GBCI", name: "Glacier Bancorp", sector: "Financials", type: "stock" },
  { ticker: "HIG", name: "The Hartford Financial", sector: "Financials", type: "stock" },
  { ticker: "IBKR", name: "Interactive Brokers", sector: "Financials", type: "stock" },
  { ticker: "KNSL", name: "Kinsale Capital Group", sector: "Financials", type: "stock" },
  { ticker: "LPLA", name: "LPL Financial", sector: "Financials", type: "stock" },
  { ticker: "MKTX", name: "MarketAxess Holdings", sector: "Financials", type: "stock" },
  { ticker: "PIPR", name: "Piper Sandler", sector: "Financials", type: "stock" },
  { ticker: "RJF", name: "Raymond James Financial", sector: "Financials", type: "stock" },
  { ticker: "SEIC", name: "SEI Investments", sector: "Financials", type: "stock" },
  { ticker: "TROW", name: "T. Rowe Price Group", sector: "Financials", type: "stock" },
  { ticker: "WBS", name: "Webster Financial", sector: "Financials", type: "stock" },

  // === More US REITs ===
  { ticker: "CUBE", name: "CubeSmart", sector: "Real Estate", type: "stock" },
  { ticker: "EXR", name: "Extra Space Storage", sector: "Real Estate", type: "stock" },
  { ticker: "INVH", name: "Invitation Homes", sector: "Real Estate", type: "stock" },
  { ticker: "KRC", name: "Kilroy Realty", sector: "Real Estate", type: "stock" },
  { ticker: "LSI", name: "Life Storage", sector: "Real Estate", type: "stock" },
  { ticker: "NNN", name: "NNN REIT", sector: "Real Estate", type: "stock" },
  { ticker: "PEAK", name: "Healthpeak Properties", sector: "Real Estate", type: "stock" },
  { ticker: "REXR", name: "Rexford Industrial Realty", sector: "Real Estate", type: "stock" },
  { ticker: "SUI", name: "Sun Communities", sector: "Real Estate", type: "stock" },
  { ticker: "TRNO", name: "Terreno Realty", sector: "Real Estate", type: "stock" },

  // === More US Utilities ===
  { ticker: "AES", name: "AES Corporation", sector: "Utilities", type: "stock" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities", type: "stock" },
  { ticker: "CMS", name: "CMS Energy", sector: "Utilities", type: "stock" },
  { ticker: "EVRG", name: "Evergy", sector: "Utilities", type: "stock" },
  { ticker: "LNT", name: "Alliant Energy", sector: "Utilities", type: "stock" },
  { ticker: "NRG", name: "NRG Energy", sector: "Utilities", type: "stock" },
  { ticker: "OGE", name: "OGE Energy", sector: "Utilities", type: "stock" },
  { ticker: "PNW", name: "Pinnacle West Capital", sector: "Utilities", type: "stock" },
  { ticker: "VST", name: "Vistra Corp", sector: "Utilities", type: "stock" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities", type: "stock" },

  // === Additional Crypto ===
  { ticker: "NEAR-USD", name: "NEAR Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FTM-USD", name: "Fantom", sector: "Crypto", type: "crypto" },
  { ticker: "FLOW-USD", name: "Flow", sector: "Crypto", type: "crypto" },
  { ticker: "EGLD-USD", name: "MultiversX", sector: "Crypto", type: "crypto" },
  { ticker: "KAVA-USD", name: "Kava", sector: "Crypto", type: "crypto" },
  { ticker: "ROSE-USD", name: "Oasis Network", sector: "Crypto", type: "crypto" },
  { ticker: "ZIL-USD", name: "Zilliqa", sector: "Crypto", type: "crypto" },
  { ticker: "CELO-USD", name: "Celo", sector: "Crypto", type: "crypto" },
  { ticker: "ONE-USD", name: "Harmony", sector: "Crypto", type: "crypto" },
  { ticker: "AUDIO-USD", name: "Audius", sector: "Crypto", type: "crypto" },
  { ticker: "ANKR-USD", name: "Ankr", sector: "Crypto", type: "crypto" },
  { ticker: "STORJ-USD", name: "Storj", sector: "Crypto", type: "crypto" },
  { ticker: "CELR-USD", name: "Celer Network", sector: "Crypto", type: "crypto" },
  { ticker: "CTSI-USD", name: "Cartesi", sector: "Crypto", type: "crypto" },
  { ticker: "BICO-USD", name: "Biconomy", sector: "Crypto", type: "crypto" },

  // === Additional Global ETFs ===
  { ticker: "ACWI", name: "iShares MSCI ACWI ETF", sector: "Global Equity", type: "etf" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets", sector: "International Equity", type: "etf" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets", sector: "Emerging Markets", type: "etf" },
  { ticker: "VXUS", name: "Vanguard Total International Stock", sector: "International Equity", type: "etf" },
  { ticker: "SCHF", name: "Schwab International Equity", sector: "International Equity", type: "etf" },
  { ticker: "IXUS", name: "iShares Core MSCI Total International", sector: "International Equity", type: "etf" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets", sector: "Emerging Markets", type: "etf" },
  { ticker: "SPDW", name: "SPDR Portfolio Developed World ex-US", sector: "International Equity", type: "etf" },
  { ticker: "SPEM", name: "SPDR Portfolio Emerging Markets", sector: "Emerging Markets", type: "etf" },
  { ticker: "DGS", name: "WisdomTree Emerging Markets SmallCap Dividends", sector: "Emerging Markets", type: "etf" },
];
