import type { AssetEntry } from "./types";


export const expansionInternational: AssetEntry[] = [
  { ticker: "RR.L", name: "Rolls-Royce Holdings", sector: "Industrials", type: "stock" },
  { ticker: "BARC.L", name: "Barclays", sector: "Finance", type: "stock" },
  { ticker: "LLOY.L", name: "Lloyds Banking Group", sector: "Finance", type: "stock" },
  { ticker: "AAL.L", name: "Anglo American", sector: "Mining", type: "stock" },
  { ticker: "ANTO.L", name: "Antofagasta", sector: "Mining", type: "stock" },
  { ticker: "BHP.L", name: "BHP Group", sector: "Mining", type: "stock" },
  { ticker: "RIO.L", name: "Rio Tinto", sector: "Mining", type: "stock" },
  { ticker: "GLEN.L", name: "Glencore", sector: "Mining", type: "stock" },
  { ticker: "STAN.L", name: "Standard Chartered", sector: "Finance", type: "stock" },
  { ticker: "LSEG.L", name: "London Stock Exchange", sector: "Finance", type: "stock" },
  { ticker: "PSON.L", name: "Pearson", sector: "Media", type: "stock" },
  { ticker: "WPP.L", name: "WPP", sector: "Media", type: "stock" },
  { ticker: "ITV.L", name: "ITV", sector: "Media", type: "stock" },
  { ticker: "INF.L", name: "Informa", sector: "Media", type: "stock" },
  { ticker: "REL.L", name: "RELX", sector: "Media", type: "stock" },
  { ticker: "AUTO.L", name: "Auto Trader", sector: "Technology", type: "stock" },
  { ticker: "DARK.L", name: "Darktrace", sector: "Technology", type: "stock" },
  { ticker: "SGE.L", name: "Sage Group", sector: "Technology", type: "stock" },
  { ticker: "SMDS.L", name: "DS Smith", sector: "Materials", type: "stock" },
  { ticker: "CRH.L", name: "CRH", sector: "Materials", type: "stock" },
  { ticker: "PSN.L", name: "Persimmon", sector: "Real Estate", type: "stock" },
  { ticker: "BWY.L", name: "Bellway", sector: "Real Estate", type: "stock" },
  { ticker: "TW.L", name: "Taylor Wimpey", sector: "Real Estate", type: "stock" },
  { ticker: "BDEV.L", name: "Barratt Developments", sector: "Real Estate", type: "stock" },
  { ticker: "HL.L", name: "Hargreaves Lansdown", sector: "Finance", type: "stock" },
  { ticker: "III.L", name: "3i Group", sector: "Finance", type: "stock" },
  { ticker: "MNDI.L", name: "Mondi", sector: "Materials", type: "stock" },
  { ticker: "FRES.L", name: "Fresnillo", sector: "Mining", type: "stock" },
  { ticker: "EVR.L", name: "Evraz", sector: "Mining", type: "stock" },
  { ticker: "WEIR.L", name: "Weir Group", sector: "Industrials", type: "stock" },
  { ticker: "IMB.L", name: "Imperial Brands", sector: "Consumer", type: "stock" },
  { ticker: "BATS.L", name: "British American Tobacco", sector: "Consumer", type: "stock" },
  { ticker: "DGE.L", name: "Diageo", sector: "Consumer", type: "stock" },
  { ticker: "ULVR.L", name: "Unilever", sector: "Consumer", type: "stock" },
  { ticker: "RKT.L", name: "Reckitt Benckiser", sector: "Consumer", type: "stock" },
  { ticker: "SBRY.L", name: "Sainsbury's", sector: "Consumer", type: "stock" },
  { ticker: "TSCO.L", name: "Tesco", sector: "Consumer", type: "stock" },
  { ticker: "MKS.L", name: "Marks & Spencer", sector: "Consumer", type: "stock" },
  { ticker: "ABF.L", name: "Associated British Foods", sector: "Consumer", type: "stock" },
  { ticker: "OCDO.L", name: "Ocado Group", sector: "Technology", type: "stock" },
  { ticker: "JD.L", name: "JD Sports", sector: "Consumer", type: "stock" },
  { ticker: "NXT.L", name: "Next", sector: "Consumer", type: "stock" },
  { ticker: "BRBY.L", name: "Burberry Group", sector: "Consumer", type: "stock" },
  { ticker: "KGF.L", name: "Kingfisher", sector: "Consumer", type: "stock" },
  { ticker: "SN.L", name: "Smith & Nephew", sector: "Healthcare", type: "stock" },
  { ticker: "AZN.L", name: "AstraZeneca", sector: "Healthcare", type: "stock" },
  { ticker: "GSK.L", name: "GSK", sector: "Healthcare", type: "stock" },
  { ticker: "HIK.L", name: "Hikma Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "DPLM.L", name: "Diploma", sector: "Industrials", type: "stock" },
  { ticker: "EXPN.L", name: "Experian", sector: "Technology", type: "stock" },
  { ticker: "CPG.L", name: "Compass Group", sector: "Consumer", type: "stock" },
  { ticker: "IHG.L", name: "InterContinental Hotels", sector: "Consumer", type: "stock" },
  { ticker: "WTB.L", name: "Whitbread", sector: "Consumer", type: "stock" },
  { ticker: "JMAT.L", name: "Johnson Matthey", sector: "Materials", type: "stock" },
  { ticker: "VOW3.DE", name: "Volkswagen", sector: "Automotive", type: "stock" },
  { ticker: "BMW.DE", name: "BMW", sector: "Automotive", type: "stock" },
  { ticker: "MBG.DE", name: "Mercedes-Benz", sector: "Automotive", type: "stock" },
  { ticker: "PAH3.DE", name: "Porsche SE", sector: "Automotive", type: "stock" },
  { ticker: "P911.DE", name: "Porsche AG", sector: "Automotive", type: "stock" },
  { ticker: "CON.DE", name: "Continental", sector: "Automotive", type: "stock" },
  { ticker: "BAS.DE", name: "BASF", sector: "Chemicals", type: "stock" },
  { ticker: "HEN3.DE", name: "Henkel", sector: "Consumer", type: "stock" },
  { ticker: "BEI.DE", name: "Beiersdorf", sector: "Consumer", type: "stock" },
  { ticker: "FRE.DE", name: "Fresenius", sector: "Healthcare", type: "stock" },
  { ticker: "FME.DE", name: "Fresenius Medical", sector: "Healthcare", type: "stock" },
  { ticker: "MRK.DE", name: "Merck KGaA", sector: "Healthcare", type: "stock" },
  { ticker: "RWE.DE", name: "RWE", sector: "Energy", type: "stock" },
  { ticker: "EOAN.DE", name: "E.ON", sector: "Energy", type: "stock" },
  { ticker: "HEI.DE", name: "HeidelbergCement", sector: "Materials", type: "stock" },
  { ticker: "SHL.DE", name: "Siemens Healthineers", sector: "Healthcare", type: "stock" },
  { ticker: "ENR.DE", name: "Siemens Energy", sector: "Energy", type: "stock" },
  { ticker: "DB1.DE", name: "Deutsche Boerse", sector: "Finance", type: "stock" },
  { ticker: "ALV.DE", name: "Allianz", sector: "Finance", type: "stock" },
  { ticker: "MUV2.DE", name: "Munich Re", sector: "Finance", type: "stock" },
  { ticker: "HNR1.DE", name: "Hannover Re", sector: "Finance", type: "stock" },
  { ticker: "TKA.DE", name: "ThyssenKrupp", sector: "Industrials", type: "stock" },
  { ticker: "SIE.DE", name: "Siemens", sector: "Industrials", type: "stock" },
  { ticker: "AIR.DE", name: "Airbus", sector: "Industrials", type: "stock" },
  { ticker: "IFX.DE", name: "Infineon", sector: "Technology", type: "stock" },
  { ticker: "SAP.DE", name: "SAP SE", sector: "Technology", type: "stock" },
  { ticker: "DTE.DE", name: "Deutsche Telekom", sector: "Telecom", type: "stock" },
  { ticker: "DPW.DE", name: "Deutsche Post", sector: "Logistics", type: "stock" },
  { ticker: "ADS.DE", name: "adidas", sector: "Consumer", type: "stock" },
  { ticker: "PUM.DE", name: "Puma", sector: "Consumer", type: "stock" },
  { ticker: "ZAL.DE", name: "Zalando", sector: "Consumer", type: "stock" },
  { ticker: "HFG.DE", name: "HelloFresh", sector: "Consumer", type: "stock" },
  { ticker: "QIA.DE", name: "QIAGEN", sector: "Healthcare", type: "stock" },
  { ticker: "SRT3.DE", name: "Sartorius", sector: "Healthcare", type: "stock" },
  { ticker: "MTX.DE", name: "MTU Aero Engines", sector: "Industrials", type: "stock" },
  { ticker: "LEG.DE", name: "LEG Immobilien", sector: "Real Estate", type: "stock" },
  { ticker: "VNA.DE", name: "Vonovia", sector: "Real Estate", type: "stock" },
  { ticker: "OR.PA", name: "L'Oreal", sector: "Consumer", type: "stock" },
  { ticker: "MC.PA", name: "LVMH", sector: "Consumer", type: "stock" },
  { ticker: "KER.PA", name: "Kering", sector: "Consumer", type: "stock" },
  { ticker: "RMS.PA", name: "Hermes", sector: "Consumer", type: "stock" },
  { ticker: "AIR.PA", name: "Airbus", sector: "Industrials", type: "stock" },
  { ticker: "SAF.PA", name: "Safran", sector: "Industrials", type: "stock" },
  { ticker: "BNP.PA", name: "BNP Paribas", sector: "Finance", type: "stock" },
  { ticker: "GLE.PA", name: "Societe Generale", sector: "Finance", type: "stock" },
  { ticker: "ACA.PA", name: "Credit Agricole", sector: "Finance", type: "stock" },
  { ticker: "CS.PA", name: "AXA", sector: "Finance", type: "stock" },
  { ticker: "SAN.PA", name: "Sanofi", sector: "Healthcare", type: "stock" },
  { ticker: "VIV.PA", name: "Vivendi", sector: "Media", type: "stock" },
  { ticker: "PUB.PA", name: "Publicis", sector: "Media", type: "stock" },
  { ticker: "ORA.PA", name: "Orange", sector: "Telecom", type: "stock" },
  { ticker: "DSY.PA", name: "Dassault Systemes", sector: "Technology", type: "stock" },
  { ticker: "CAP.PA", name: "Capgemini", sector: "Technology", type: "stock" },
  { ticker: "SU.PA", name: "Schneider Electric", sector: "Industrials", type: "stock" },
  { ticker: "AI.PA", name: "Air Liquide", sector: "Chemicals", type: "stock" },
  { ticker: "RI.PA", name: "Pernod Ricard", sector: "Consumer", type: "stock" },
  { ticker: "DG.PA", name: "Vinci", sector: "Industrials", type: "stock" },
  { ticker: "SGO.PA", name: "Saint-Gobain", sector: "Materials", type: "stock" },
  { ticker: "EN.PA", name: "Bouygues", sector: "Industrials", type: "stock" },
  { ticker: "STM.PA", name: "STMicroelectronics", sector: "Technology", type: "stock" },
  { ticker: "WLN.PA", name: "Worldline", sector: "Technology", type: "stock" },
  { ticker: "ERA.PA", name: "Eramet", sector: "Mining", type: "stock" },
  { ticker: "ML.PA", name: "Michelin", sector: "Automotive", type: "stock" },
  { ticker: "RNO.PA", name: "Renault", sector: "Automotive", type: "stock" },
  { ticker: "UG.PA", name: "Peugeot", sector: "Automotive", type: "stock" },
  { ticker: "ASML.AS", name: "ASML Holding", sector: "Technology", type: "stock" },
  { ticker: "PHIA.AS", name: "Philips", sector: "Healthcare", type: "stock" },
  { ticker: "AD.AS", name: "Ahold Delhaize", sector: "Consumer", type: "stock" },
  { ticker: "HEIA.AS", name: "Heineken", sector: "Consumer", type: "stock" },
  { ticker: "UNA.AS", name: "Unilever NV", sector: "Consumer", type: "stock" },
  { ticker: "INGA.AS", name: "ING Group", sector: "Finance", type: "stock" },
  { ticker: "ABN.AS", name: "ABN AMRO", sector: "Finance", type: "stock" },
  { ticker: "NN.AS", name: "NN Group", sector: "Finance", type: "stock" },
  { ticker: "WKL.AS", name: "Wolters Kluwer", sector: "Technology", type: "stock" },
  { ticker: "DSM.AS", name: "DSM", sector: "Chemicals", type: "stock" },
  { ticker: "AKZ.AS", name: "Akzo Nobel", sector: "Chemicals", type: "stock" },
  { ticker: "RAND.AS", name: "Randstad", sector: "Industrials", type: "stock" },
  { ticker: "LIGHT.AS", name: "Signify", sector: "Industrials", type: "stock" },
  { ticker: "BESI.AS", name: "BE Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ASM.AS", name: "ASM International", sector: "Technology", type: "stock" },
  { ticker: "UCG.MI", name: "UniCredit", sector: "Finance", type: "stock" },
  { ticker: "ISP.MI", name: "Intesa Sanpaolo", sector: "Finance", type: "stock" },
  { ticker: "ENI.MI", name: "ENI", sector: "Energy", type: "stock" },
  { ticker: "ENEL.MI", name: "Enel", sector: "Energy", type: "stock" },
  { ticker: "STM.MI", name: "STMicroelectronics", sector: "Technology", type: "stock" },
  { ticker: "TIT.MI", name: "Telecom Italia", sector: "Telecom", type: "stock" },
  { ticker: "RACE.MI", name: "Ferrari", sector: "Automotive", type: "stock" },
  { ticker: "CNHI.MI", name: "CNH Industrial", sector: "Industrials", type: "stock" },
  { ticker: "PRY.MI", name: "Prysmian", sector: "Industrials", type: "stock" },
  { ticker: "LDO.MI", name: "Leonardo", sector: "Industrials", type: "stock" },
  { ticker: "TEN.MI", name: "Tenaris", sector: "Energy", type: "stock" },
  { ticker: "G.MI", name: "Generali", sector: "Finance", type: "stock" },
  { ticker: "FBK.MI", name: "FinecoBank", sector: "Finance", type: "stock" },
  { ticker: "BAMI.MI", name: "Banco BPM", sector: "Finance", type: "stock" },
  { ticker: "SAN.MC", name: "Banco Santander", sector: "Finance", type: "stock" },
  { ticker: "BBVA.MC", name: "BBVA", sector: "Finance", type: "stock" },
  { ticker: "TEF.MC", name: "Telefonica", sector: "Telecom", type: "stock" },
  { ticker: "IBE.MC", name: "Iberdrola", sector: "Energy", type: "stock" },
  { ticker: "ITX.MC", name: "Inditex", sector: "Consumer", type: "stock" },
  { ticker: "REP.MC", name: "Repsol", sector: "Energy", type: "stock" },
  { ticker: "AMS.MC", name: "Amadeus IT", sector: "Technology", type: "stock" },
  { ticker: "FER.MC", name: "Ferrovial", sector: "Industrials", type: "stock" },
  { ticker: "CABK.MC", name: "CaixaBank", sector: "Finance", type: "stock" },
  { ticker: "ENG.MC", name: "Enagas", sector: "Energy", type: "stock" },
  { ticker: "MAP.MC", name: "MAPFRE", sector: "Finance", type: "stock" },
  { ticker: "GRF.MC", name: "Grifols", sector: "Healthcare", type: "stock" },
  { ticker: "CLNX.MC", name: "Cellnex", sector: "Telecom", type: "stock" },
  { ticker: "ACS.MC", name: "ACS", sector: "Industrials", type: "stock" },
  { ticker: "ERIC-B.ST", name: "Ericsson", sector: "Technology", type: "stock" },
  { ticker: "VOLV-B.ST", name: "Volvo", sector: "Automotive", type: "stock" },
  { ticker: "SAND.ST", name: "Sandvik", sector: "Industrials", type: "stock" },
  { ticker: "ATCO-A.ST", name: "Atlas Copco", sector: "Industrials", type: "stock" },
  { ticker: "HM-B.ST", name: "H&M", sector: "Consumer", type: "stock" },
  { ticker: "SEB-A.ST", name: "SEB", sector: "Finance", type: "stock" },
  { ticker: "SWED-A.ST", name: "Swedbank", sector: "Finance", type: "stock" },
  { ticker: "SINCH.ST", name: "Sinch", sector: "Technology", type: "stock" },
  { ticker: "HEXA-B.ST", name: "Hexagon", sector: "Technology", type: "stock" },
  { ticker: "ALFA.ST", name: "Alfa Laval", sector: "Industrials", type: "stock" },
  { ticker: "EQNR.OL", name: "Equinor", sector: "Energy", type: "stock" },
  { ticker: "DNB.OL", name: "DNB Bank", sector: "Finance", type: "stock" },
  { ticker: "TEL.OL", name: "Telenor", sector: "Telecom", type: "stock" },
  { ticker: "MOWI.OL", name: "Mowi", sector: "Consumer", type: "stock" },
  { ticker: "YAR.OL", name: "Yara International", sector: "Chemicals", type: "stock" },
  { ticker: "ORK.OL", name: "Orkla", sector: "Consumer", type: "stock" },
  { ticker: "SALM.OL", name: "SalMar", sector: "Consumer", type: "stock" },
  { ticker: "AKRBP.OL", name: "Aker BP", sector: "Energy", type: "stock" },
  { ticker: "NESTE.HE", name: "Neste", sector: "Energy", type: "stock" },
  { ticker: "NOKIA.HE", name: "Nokia", sector: "Technology", type: "stock" },
  { ticker: "UPM.HE", name: "UPM-Kymmene", sector: "Materials", type: "stock" },
  { ticker: "STERV.HE", name: "Stora Enso", sector: "Materials", type: "stock" },
  { ticker: "KNEBV.HE", name: "Kone", sector: "Industrials", type: "stock" },
  { ticker: "FORTUM.HE", name: "Fortum", sector: "Energy", type: "stock" },
  { ticker: "WRT1V.HE", name: "Wartsila", sector: "Industrials", type: "stock" },
  { ticker: "SAMPO.HE", name: "Sampo", sector: "Finance", type: "stock" },
  { ticker: "NOVO-B.CO", name: "Novo Nordisk", sector: "Healthcare", type: "stock" },
  { ticker: "MAERSK-B.CO", name: "Maersk", sector: "Logistics", type: "stock" },
  { ticker: "CARL-B.CO", name: "Carlsberg", sector: "Consumer", type: "stock" },
  { ticker: "VWS.CO", name: "Vestas", sector: "Energy", type: "stock" },
  { ticker: "DSV.CO", name: "DSV Panalpina", sector: "Logistics", type: "stock" },
  { ticker: "PNDORA.CO", name: "Pandora", sector: "Consumer", type: "stock" },
  { ticker: "GMAB.CO", name: "Genmab", sector: "Healthcare", type: "stock" },
  { ticker: "COLO-B.CO", name: "Coloplast", sector: "Healthcare", type: "stock" },
  { ticker: "NESN.SW", name: "Nestle", sector: "Consumer", type: "stock" },
  { ticker: "ROG.SW", name: "Roche", sector: "Healthcare", type: "stock" },
  { ticker: "NOVN.SW", name: "Novartis", sector: "Healthcare", type: "stock" },
  { ticker: "UBSG.SW", name: "UBS Group", sector: "Finance", type: "stock" },
  { ticker: "CSGN.SW", name: "Credit Suisse", sector: "Finance", type: "stock" },
  { ticker: "ZURN.SW", name: "Zurich Insurance", sector: "Finance", type: "stock" },
  { ticker: "ABBN.SW", name: "ABB", sector: "Industrials", type: "stock" },
  { ticker: "GEBN.SW", name: "Geberit", sector: "Industrials", type: "stock" },
  { ticker: "SIKA.SW", name: "Sika", sector: "Materials", type: "stock" },
  { ticker: "LONN.SW", name: "Lonza", sector: "Healthcare", type: "stock" },
  { ticker: "GIVN.SW", name: "Givaudan", sector: "Chemicals", type: "stock" },
  { ticker: "SCMN.SW", name: "Swisscom", sector: "Telecom", type: "stock" },
  { ticker: "SLHN.SW", name: "Swiss Life", sector: "Finance", type: "stock" },
  { ticker: "BAER.SW", name: "Julius Baer", sector: "Finance", type: "stock" },
  { ticker: "SREN.SW", name: "Swiss Re", sector: "Finance", type: "stock" },
  { ticker: "BARN.SW", name: "Barry Callebaut", sector: "Consumer", type: "stock" },
  { ticker: "TEMN.SW", name: "Temenos", sector: "Technology", type: "stock" },
  { ticker: "SOON.SW", name: "Sonova", sector: "Healthcare", type: "stock" },
  { ticker: "VACN.SW", name: "VAT Group", sector: "Industrials", type: "stock" },
  { ticker: "STMN.SW", name: "Straumann", sector: "Healthcare", type: "stock" },
  { ticker: "7203.T", name: "Toyota Motor", sector: "Automotive", type: "stock" },
  { ticker: "6758.T", name: "Sony Group", sector: "Technology", type: "stock" },
  { ticker: "6861.T", name: "Keyence", sector: "Technology", type: "stock" },
  { ticker: "9984.T", name: "SoftBank Group", sector: "Technology", type: "stock" },
  { ticker: "6098.T", name: "Recruit Holdings", sector: "Technology", type: "stock" },
  { ticker: "6367.T", name: "Daikin Industries", sector: "Industrials", type: "stock" },
  { ticker: "6902.T", name: "Denso", sector: "Automotive", type: "stock" },
  { ticker: "7267.T", name: "Honda Motor", sector: "Automotive", type: "stock" },
  { ticker: "7974.T", name: "Nintendo", sector: "Technology", type: "stock" },
  { ticker: "8035.T", name: "Tokyo Electron", sector: "Technology", type: "stock" },
  { ticker: "4063.T", name: "Shin-Etsu Chemical", sector: "Chemicals", type: "stock" },
  { ticker: "6501.T", name: "Hitachi", sector: "Technology", type: "stock" },
  { ticker: "6594.T", name: "Nidec", sector: "Technology", type: "stock" },
  { ticker: "6981.T", name: "Murata Manufacturing", sector: "Technology", type: "stock" },
  { ticker: "8306.T", name: "Mitsubishi UFJ", sector: "Finance", type: "stock" },
  { ticker: "8316.T", name: "Sumitomo Mitsui", sector: "Finance", type: "stock" },
  { ticker: "8411.T", name: "Mizuho Financial", sector: "Finance", type: "stock" },
  { ticker: "8766.T", name: "Tokio Marine", sector: "Finance", type: "stock" },
  { ticker: "9433.T", name: "KDDI", sector: "Telecom", type: "stock" },
  { ticker: "9432.T", name: "NTT", sector: "Telecom", type: "stock" },
  { ticker: "4502.T", name: "Takeda Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "4568.T", name: "Daiichi Sankyo", sector: "Healthcare", type: "stock" },
  { ticker: "4519.T", name: "Chugai Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "4507.T", name: "Shionogi", sector: "Healthcare", type: "stock" },
  { ticker: "2914.T", name: "Japan Tobacco", sector: "Consumer", type: "stock" },
  { ticker: "4901.T", name: "Fujifilm", sector: "Technology", type: "stock" },
  { ticker: "6273.T", name: "SMC Corporation", sector: "Industrials", type: "stock" },
  { ticker: "7751.T", name: "Canon", sector: "Technology", type: "stock" },
  { ticker: "6503.T", name: "Mitsubishi Electric", sector: "Technology", type: "stock" },
  { ticker: "6752.T", name: "Panasonic", sector: "Technology", type: "stock" },
  { ticker: "3382.T", name: "Seven & i Holdings", sector: "Consumer", type: "stock" },
  { ticker: "9983.T", name: "Fast Retailing", sector: "Consumer", type: "stock" },
  { ticker: "4911.T", name: "Shiseido", sector: "Consumer", type: "stock" },
  { ticker: "8001.T", name: "ITOCHU", sector: "Trading", type: "stock" },
  { ticker: "8058.T", name: "Mitsubishi Corp", sector: "Trading", type: "stock" },
  { ticker: "8031.T", name: "Mitsui & Co", sector: "Trading", type: "stock" },
  { ticker: "2802.T", name: "Ajinomoto", sector: "Consumer", type: "stock" },
  { ticker: "6971.T", name: "Kyocera", sector: "Technology", type: "stock" },
  { ticker: "6954.T", name: "Fanuc", sector: "Industrials", type: "stock" },
  { ticker: "6506.T", name: "Yaskawa Electric", sector: "Industrials", type: "stock" },
  { ticker: "9020.T", name: "JR East", sector: "Transport", type: "stock" },
  { ticker: "9021.T", name: "JR West", sector: "Transport", type: "stock" },
  { ticker: "9022.T", name: "JR Central", sector: "Transport", type: "stock" },
  { ticker: "4704.T", name: "Trend Micro", sector: "Technology", type: "stock" },
  { ticker: "7741.T", name: "HOYA", sector: "Healthcare", type: "stock" },
  { ticker: "7733.T", name: "Olympus", sector: "Healthcare", type: "stock" },
  { ticker: "3407.T", name: "Asahi Kasei", sector: "Chemicals", type: "stock" },
  { ticker: "5108.T", name: "Bridgestone", sector: "Automotive", type: "stock" },
  { ticker: "6702.T", name: "Fujitsu", sector: "Technology", type: "stock" },
  { ticker: "4543.T", name: "Terumo", sector: "Healthcare", type: "stock" },
  { ticker: "0700.HK", name: "Tencent", sector: "Technology", type: "stock" },
  { ticker: "9988.HK", name: "Alibaba Group", sector: "Technology", type: "stock" },
  { ticker: "3690.HK", name: "Meituan", sector: "Technology", type: "stock" },
  { ticker: "9618.HK", name: "JD.com", sector: "Technology", type: "stock" },
  { ticker: "9999.HK", name: "NetEase", sector: "Technology", type: "stock" },
  { ticker: "0981.HK", name: "SMIC", sector: "Technology", type: "stock" },
  { ticker: "1810.HK", name: "Xiaomi", sector: "Technology", type: "stock" },
  { ticker: "2382.HK", name: "Sunny Optical", sector: "Technology", type: "stock" },
  { ticker: "0388.HK", name: "HKEX", sector: "Finance", type: "stock" },
  { ticker: "1299.HK", name: "AIA Group", sector: "Finance", type: "stock" },
  { ticker: "2318.HK", name: "Ping An Insurance", sector: "Finance", type: "stock" },
  { ticker: "3988.HK", name: "Bank of China", sector: "Finance", type: "stock" },
  { ticker: "1398.HK", name: "ICBC", sector: "Finance", type: "stock" },
  { ticker: "0939.HK", name: "CCB", sector: "Finance", type: "stock" },
  { ticker: "0005.HK", name: "HSBC Holdings", sector: "Finance", type: "stock" },
  { ticker: "2628.HK", name: "China Life", sector: "Finance", type: "stock" },
  { ticker: "0941.HK", name: "China Mobile", sector: "Telecom", type: "stock" },
  { ticker: "0883.HK", name: "CNOOC", sector: "Energy", type: "stock" },
  { ticker: "0857.HK", name: "PetroChina", sector: "Energy", type: "stock" },
  { ticker: "0386.HK", name: "China Petroleum", sector: "Energy", type: "stock" },
  { ticker: "0027.HK", name: "Galaxy Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "1928.HK", name: "Sands China", sector: "Consumer", type: "stock" },
  { ticker: "2020.HK", name: "ANTA Sports", sector: "Consumer", type: "stock" },
  { ticker: "6862.HK", name: "Haidilao", sector: "Consumer", type: "stock" },
  { ticker: "9633.HK", name: "Nongfu Spring", sector: "Consumer", type: "stock" },
  { ticker: "6969.HK", name: "Smoore", sector: "Consumer", type: "stock" },
  { ticker: "2269.HK", name: "WuXi Biologics", sector: "Healthcare", type: "stock" },
  { ticker: "1177.HK", name: "Sino Biopharm", sector: "Healthcare", type: "stock" },
  { ticker: "0175.HK", name: "Geely Automobile", sector: "Automotive", type: "stock" },
  { ticker: "2333.HK", name: "Great Wall Motor", sector: "Automotive", type: "stock" },
  { ticker: "1211.HK", name: "BYD Company", sector: "Automotive", type: "stock" },
  { ticker: "9868.HK", name: "XPeng", sector: "Automotive", type: "stock" },
  { ticker: "2015.HK", name: "Li Auto", sector: "Automotive", type: "stock" },
  { ticker: "9866.HK", name: "NIO Inc", sector: "Automotive", type: "stock" },
  { ticker: "005930.KS", name: "Samsung Electronics", sector: "Technology", type: "stock" },
  { ticker: "000660.KS", name: "SK Hynix", sector: "Technology", type: "stock" },
  { ticker: "035420.KS", name: "NAVER", sector: "Technology", type: "stock" },
  { ticker: "035720.KS", name: "Kakao", sector: "Technology", type: "stock" },
  { ticker: "006400.KS", name: "Samsung SDI", sector: "Technology", type: "stock" },
  { ticker: "051910.KS", name: "LG Chem", sector: "Chemicals", type: "stock" },
  { ticker: "066570.KS", name: "LG Electronics", sector: "Technology", type: "stock" },
  { ticker: "003550.KS", name: "LG Corp", sector: "Conglomerate", type: "stock" },
  { ticker: "005380.KS", name: "Hyundai Motor", sector: "Automotive", type: "stock" },
  { ticker: "000270.KS", name: "Kia Corp", sector: "Automotive", type: "stock" },
  { ticker: "055550.KS", name: "Shinhan Financial", sector: "Finance", type: "stock" },
  { ticker: "105560.KS", name: "KB Financial", sector: "Finance", type: "stock" },
  { ticker: "032830.KS", name: "Samsung Life", sector: "Finance", type: "stock" },
  { ticker: "086790.KS", name: "Hana Financial", sector: "Finance", type: "stock" },
  { ticker: "012330.KS", name: "Hyundai Mobis", sector: "Automotive", type: "stock" },
  { ticker: "009150.KS", name: "Samsung Electro", sector: "Technology", type: "stock" },
  { ticker: "034730.KS", name: "SK Inc", sector: "Conglomerate", type: "stock" },
  { ticker: "010950.KS", name: "S-Oil", sector: "Energy", type: "stock" },
  { ticker: "096770.KS", name: "SK Innovation", sector: "Energy", type: "stock" },
  { ticker: "036570.KS", name: "NCsoft", sector: "Technology", type: "stock" },
  { ticker: "251270.KS", name: "Netmarble", sector: "Technology", type: "stock" },
  { ticker: "263750.KS", name: "Pearl Abyss", sector: "Technology", type: "stock" },
  { ticker: "028260.KS", name: "Samsung C&T", sector: "Industrials", type: "stock" },
  { ticker: "011170.KS", name: "Lotte Chemical", sector: "Chemicals", type: "stock" },
  { ticker: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", type: "stock" },
  { ticker: "TCS.NS", name: "Tata Consultancy", sector: "Technology", type: "stock" },
  { ticker: "INFY.NS", name: "Infosys", sector: "Technology", type: "stock" },
  { ticker: "HDFCBANK.NS", name: "HDFC Bank", sector: "Finance", type: "stock" },
  { ticker: "ICICIBANK.NS", name: "ICICI Bank", sector: "Finance", type: "stock" },
  { ticker: "KOTAKBANK.NS", name: "Kotak Mahindra", sector: "Finance", type: "stock" },
  { ticker: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "Consumer", type: "stock" },
  { ticker: "ITC.NS", name: "ITC Limited", sector: "Consumer", type: "stock" },
  { ticker: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", type: "stock" },
  { ticker: "SBIN.NS", name: "State Bank of India", sector: "Finance", type: "stock" },
  { ticker: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Finance", type: "stock" },
  { ticker: "WIPRO.NS", name: "Wipro", sector: "Technology", type: "stock" },
  { ticker: "HCLTECH.NS", name: "HCL Technologies", sector: "Technology", type: "stock" },
  { ticker: "LT.NS", name: "Larsen & Toubro", sector: "Industrials", type: "stock" },
  { ticker: "ASIANPAINT.NS", name: "Asian Paints", sector: "Materials", type: "stock" },
  { ticker: "MARUTI.NS", name: "Maruti Suzuki", sector: "Automotive", type: "stock" },
  { ticker: "TATAMOTORS.NS", name: "Tata Motors", sector: "Automotive", type: "stock" },
  { ticker: "M&M.NS", name: "Mahindra & Mahindra", sector: "Automotive", type: "stock" },
  { ticker: "SUNPHARMA.NS", name: "Sun Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "DRREDDY.NS", name: "Dr Reddy's Labs", sector: "Healthcare", type: "stock" },
  { ticker: "CIPLA.NS", name: "Cipla", sector: "Healthcare", type: "stock" },
  { ticker: "TITAN.NS", name: "Titan Company", sector: "Consumer", type: "stock" },
  { ticker: "NESTLEIND.NS", name: "Nestle India", sector: "Consumer", type: "stock" },
  { ticker: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Materials", type: "stock" },
  { ticker: "POWERGRID.NS", name: "Power Grid Corp", sector: "Energy", type: "stock" },
  { ticker: "NTPC.NS", name: "NTPC Limited", sector: "Energy", type: "stock" },
  { ticker: "ONGC.NS", name: "ONGC", sector: "Energy", type: "stock" },
  { ticker: "ADANIENT.NS", name: "Adani Enterprises", sector: "Conglomerate", type: "stock" },
  { ticker: "ADANIPORTS.NS", name: "Adani Ports", sector: "Logistics", type: "stock" },
  { ticker: "TECHM.NS", name: "Tech Mahindra", sector: "Technology", type: "stock" },
  { ticker: "JSWSTEEL.NS", name: "JSW Steel", sector: "Materials", type: "stock" },
  { ticker: "TATASTEEL.NS", name: "Tata Steel", sector: "Materials", type: "stock" },
  { ticker: "COALINDIA.NS", name: "Coal India", sector: "Mining", type: "stock" },
  { ticker: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Finance", type: "stock" },
  { ticker: "DIVISLAB.NS", name: "Divi's Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "EICHERMOT.NS", name: "Eicher Motors", sector: "Automotive", type: "stock" },
  { ticker: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Automotive", type: "stock" },
  { ticker: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare", type: "stock" },
  { ticker: "INDUSINDBK.NS", name: "IndusInd Bank", sector: "Finance", type: "stock" },
  { ticker: "AXISBANK.NS", name: "Axis Bank", sector: "Finance", type: "stock" },
  { ticker: "CBA.AX", name: "Commonwealth Bank", sector: "Finance", type: "stock" },
  { ticker: "BHP.AX", name: "BHP Group", sector: "Mining", type: "stock" },
  { ticker: "CSL.AX", name: "CSL Limited", sector: "Healthcare", type: "stock" },
  { ticker: "NAB.AX", name: "National Australia Bank", sector: "Finance", type: "stock" },
  { ticker: "WBC.AX", name: "Westpac", sector: "Finance", type: "stock" },
  { ticker: "ANZ.AX", name: "ANZ Banking", sector: "Finance", type: "stock" },
  { ticker: "MQG.AX", name: "Macquarie Group", sector: "Finance", type: "stock" },
  { ticker: "WES.AX", name: "Wesfarmers", sector: "Consumer", type: "stock" },
  { ticker: "WOW.AX", name: "Woolworths", sector: "Consumer", type: "stock" },
  { ticker: "TLS.AX", name: "Telstra", sector: "Telecom", type: "stock" },
  { ticker: "RIO.AX", name: "Rio Tinto", sector: "Mining", type: "stock" },
  { ticker: "FMG.AX", name: "Fortescue Metals", sector: "Mining", type: "stock" },
  { ticker: "NCM.AX", name: "Newcrest Mining", sector: "Mining", type: "stock" },
  { ticker: "WDS.AX", name: "Woodside Energy", sector: "Energy", type: "stock" },
  { ticker: "STO.AX", name: "Santos", sector: "Energy", type: "stock" },
  { ticker: "ALL.AX", name: "Aristocrat Leisure", sector: "Technology", type: "stock" },
  { ticker: "REA.AX", name: "REA Group", sector: "Technology", type: "stock" },
  { ticker: "XRO.AX", name: "Xero", sector: "Technology", type: "stock" },
  { ticker: "WTC.AX", name: "WiseTech Global", sector: "Technology", type: "stock" },
  { ticker: "CPU.AX", name: "Computershare", sector: "Technology", type: "stock" },
  { ticker: "COL.AX", name: "Coles Group", sector: "Consumer", type: "stock" },
  { ticker: "TCL.AX", name: "Transurban", sector: "Infrastructure", type: "stock" },
  { ticker: "GMG.AX", name: "Goodman Group", sector: "Real Estate", type: "stock" },
  { ticker: "SCG.AX", name: "Scentre Group", sector: "Real Estate", type: "stock" },
  { ticker: "AMC.AX", name: "Amcor", sector: "Materials", type: "stock" },
  { ticker: "JHX.AX", name: "James Hardie", sector: "Materials", type: "stock" },
  { ticker: "SHL.AX", name: "Sonic Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "RHC.AX", name: "Ramsay Health", sector: "Healthcare", type: "stock" },
  { ticker: "COH.AX", name: "Cochlear", sector: "Healthcare", type: "stock" },
  { ticker: "QAN.AX", name: "Qantas", sector: "Transport", type: "stock" },
  { ticker: "D05.SI", name: "DBS Group", sector: "Finance", type: "stock" },
  { ticker: "O39.SI", name: "OCBC Bank", sector: "Finance", type: "stock" },
  { ticker: "U11.SI", name: "UOB", sector: "Finance", type: "stock" },
  { ticker: "Z74.SI", name: "SingTel", sector: "Telecom", type: "stock" },
  { ticker: "BN4.SI", name: "Keppel Corp", sector: "Industrials", type: "stock" },
  { ticker: "C6L.SI", name: "Singapore Airlines", sector: "Transport", type: "stock" },
  { ticker: "A17U.SI", name: "CapitaLand Ascendas", sector: "Real Estate", type: "stock" },
  { ticker: "C38U.SI", name: "CapitaLand Integrated", sector: "Real Estate", type: "stock" },
  { ticker: "S58.SI", name: "SATS", sector: "Transport", type: "stock" },
  { ticker: "BS6.SI", name: "Yangzijiang Shipbuilding", sector: "Industrials", type: "stock" },
  { ticker: "2330.TW", name: "TSMC", sector: "Technology", type: "stock" },
  { ticker: "2317.TW", name: "Hon Hai Precision", sector: "Technology", type: "stock" },
  { ticker: "2454.TW", name: "MediaTek", sector: "Technology", type: "stock" },
  { ticker: "2412.TW", name: "Chunghwa Telecom", sector: "Telecom", type: "stock" },
  { ticker: "2308.TW", name: "Delta Electronics", sector: "Technology", type: "stock" },
  { ticker: "2881.TW", name: "Fubon Financial", sector: "Finance", type: "stock" },
  { ticker: "2882.TW", name: "Cathay Financial", sector: "Finance", type: "stock" },
  { ticker: "2886.TW", name: "Mega Financial", sector: "Finance", type: "stock" },
  { ticker: "1301.TW", name: "Formosa Plastics", sector: "Chemicals", type: "stock" },
  { ticker: "1303.TW", name: "Nan Ya Plastics", sector: "Chemicals", type: "stock" },
  { ticker: "2002.TW", name: "China Steel", sector: "Materials", type: "stock" },
  { ticker: "3711.TW", name: "ASE Technology", sector: "Technology", type: "stock" },
  { ticker: "2891.TW", name: "CTBC Financial", sector: "Finance", type: "stock" },
  { ticker: "5880.TW", name: "Taiwan Cooperative", sector: "Finance", type: "stock" },
  { ticker: "PETR4.SA", name: "Petrobras", sector: "Energy", type: "stock" },
  { ticker: "VALE3.SA", name: "Vale", sector: "Mining", type: "stock" },
  { ticker: "ITUB4.SA", name: "Itau Unibanco", sector: "Finance", type: "stock" },
  { ticker: "BBDC4.SA", name: "Bradesco", sector: "Finance", type: "stock" },
  { ticker: "ABEV3.SA", name: "Ambev", sector: "Consumer", type: "stock" },
  { ticker: "B3SA3.SA", name: "B3 SA", sector: "Finance", type: "stock" },
  { ticker: "WEGE3.SA", name: "WEG", sector: "Industrials", type: "stock" },
  { ticker: "RENT3.SA", name: "Localiza", sector: "Consumer", type: "stock" },
  { ticker: "JBSS3.SA", name: "JBS SA", sector: "Consumer", type: "stock" },
  { ticker: "SUZB3.SA", name: "Suzano", sector: "Materials", type: "stock" },
  { ticker: "LREN3.SA", name: "Lojas Renner", sector: "Consumer", type: "stock" },
  { ticker: "EQTL3.SA", name: "Equatorial Energia", sector: "Energy", type: "stock" },
  { ticker: "ELET3.SA", name: "Eletrobras", sector: "Energy", type: "stock" },
  { ticker: "BBAS3.SA", name: "Banco do Brasil", sector: "Finance", type: "stock" },
  { ticker: "CSAN3.SA", name: "Cosan", sector: "Energy", type: "stock" },
  { ticker: "RAIL3.SA", name: "Rumo", sector: "Logistics", type: "stock" },
  { ticker: "MGLU3.SA", name: "Magazine Luiza", sector: "Consumer", type: "stock" },
  { ticker: "PRIO3.SA", name: "PetroRio", sector: "Energy", type: "stock" },
  { ticker: "HAPV3.SA", name: "Hapvida", sector: "Healthcare", type: "stock" },
  { ticker: "RADL3.SA", name: "Raia Drogasil", sector: "Healthcare", type: "stock" },
  { ticker: "TOTS3.SA", name: "TOTVS", sector: "Technology", type: "stock" },
  { ticker: "VIVT3.SA", name: "Telefonica Brasil", sector: "Telecom", type: "stock" },
  { ticker: "CMIG4.SA", name: "CEMIG", sector: "Energy", type: "stock" },
  { ticker: "SBSP3.SA", name: "Sabesp", sector: "Utilities", type: "stock" },
  { ticker: "CCRO3.SA", name: "CCR", sector: "Infrastructure", type: "stock" },
  { ticker: "ENGI11.SA", name: "Energisa", sector: "Energy", type: "stock" },
  { ticker: "RY.TO", name: "Royal Bank of Canada", sector: "Finance", type: "stock" },
  { ticker: "TD.TO", name: "Toronto-Dominion Bank", sector: "Finance", type: "stock" },
  { ticker: "BNS.TO", name: "Bank of Nova Scotia", sector: "Finance", type: "stock" },
  { ticker: "BMO.TO", name: "Bank of Montreal", sector: "Finance", type: "stock" },
  { ticker: "CNR.TO", name: "CN Railway", sector: "Transport", type: "stock" },
  { ticker: "CP.TO", name: "CP Railway", sector: "Transport", type: "stock" },
  { ticker: "ENB.TO", name: "Enbridge", sector: "Energy", type: "stock" },
  { ticker: "TRP.TO", name: "TC Energy", sector: "Energy", type: "stock" },
  { ticker: "SU.TO", name: "Suncor Energy", sector: "Energy", type: "stock" },
  { ticker: "CNQ.TO", name: "Canadian Natural", sector: "Energy", type: "stock" },
  { ticker: "BCE.TO", name: "BCE Inc", sector: "Telecom", type: "stock" },
  { ticker: "T.TO", name: "Telus", sector: "Telecom", type: "stock" },
  { ticker: "MFC.TO", name: "Manulife Financial", sector: "Finance", type: "stock" },
  { ticker: "SLF.TO", name: "Sun Life Financial", sector: "Finance", type: "stock" },
  { ticker: "ATD.TO", name: "Alimentation Couche-Tard", sector: "Consumer", type: "stock" },
  { ticker: "L.TO", name: "Loblaw", sector: "Consumer", type: "stock" },
  { ticker: "WCN.TO", name: "Waste Connections", sector: "Industrials", type: "stock" },
  { ticker: "BAM.TO", name: "Brookfield Asset", sector: "Finance", type: "stock" },
  { ticker: "BN.TO", name: "Brookfield Corp", sector: "Finance", type: "stock" },
  { ticker: "IFC.TO", name: "Intact Financial", sector: "Finance", type: "stock" },
  { ticker: "CSU.TO", name: "Constellation Software", sector: "Technology", type: "stock" },
  { ticker: "SHOP.TO", name: "Shopify", sector: "Technology", type: "stock" },
  { ticker: "GIB-A.TO", name: "CGI Group", sector: "Technology", type: "stock" },
  { ticker: "DOL.TO", name: "Dollarama", sector: "Consumer", type: "stock" },
  { ticker: "QSR.TO", name: "Restaurant Brands", sector: "Consumer", type: "stock" },
  { ticker: "GFL.TO", name: "GFL Environmental", sector: "Industrials", type: "stock" },
  { ticker: "FNV.TO", name: "Franco-Nevada", sector: "Mining", type: "stock" },
  { ticker: "AEM.TO", name: "Agnico Eagle", sector: "Mining", type: "stock" },
  { ticker: "ABX.TO", name: "Barrick Gold", sector: "Mining", type: "stock" },
  { ticker: "WPM.TO", name: "Wheaton Precious", sector: "Mining", type: "stock" },
  { ticker: "AMXL.MX", name: "America Movil", sector: "Telecom", type: "stock" },
  { ticker: "WALMEX.MX", name: "Walmart Mexico", sector: "Consumer", type: "stock" },
  { ticker: "FEMSAUBD.MX", name: "FEMSA", sector: "Consumer", type: "stock" },
  { ticker: "GFNORTEO.MX", name: "Grupo Financiero Norte", sector: "Finance", type: "stock" },
  { ticker: "CEMEXCPO.MX", name: "Cemex", sector: "Materials", type: "stock" },
  { ticker: "GMEXICOB.MX", name: "Grupo Mexico", sector: "Mining", type: "stock" },
  { ticker: "TLEVISACPO.MX", name: "Televisa", sector: "Media", type: "stock" },
  { ticker: "BIMBOA.MX", name: "Grupo Bimbo", sector: "Consumer", type: "stock" },
  { ticker: "KIMBERA.MX", name: "Kimberly-Clark Mexico", sector: "Consumer", type: "stock" },
  { ticker: "ALSEA.MX", name: "Alsea", sector: "Consumer", type: "stock" },
  { ticker: "GRUMAB.MX", name: "Gruma", sector: "Consumer", type: "stock" },
  { ticker: "AC.MX", name: "Arca Continental", sector: "Consumer", type: "stock" },
  { ticker: "LIVEPOLC-1.MX", name: "Liverpool", sector: "Consumer", type: "stock" },
  { ticker: "GCARSOA1.MX", name: "Grupo Carso", sector: "Conglomerate", type: "stock" },
  { ticker: "ELEKTRA.MX", name: "Grupo Elektra", sector: "Consumer", type: "stock" },
  { ticker: "PINFRA.MX", name: "Pinfra", sector: "Infrastructure", type: "stock" },
  { ticker: "SQM-B.SN", name: "SQM", sector: "Chemicals", type: "stock" },
  { ticker: "FALABELLA.SN", name: "Falabella", sector: "Consumer", type: "stock" },
  { ticker: "BSANTANDER.SN", name: "Banco Santander Chile", sector: "Finance", type: "stock" },
  { ticker: "CENCOSUD.SN", name: "Cencosud", sector: "Consumer", type: "stock" },
  { ticker: "COPEC.SN", name: "Empresas Copec", sector: "Energy", type: "stock" },
  { ticker: "ENELAM.SN", name: "Enel Americas", sector: "Energy", type: "stock" },
  { ticker: "NPN.JO", name: "Naspers", sector: "Technology", type: "stock" },
  { ticker: "PRX.JO", name: "Prosus", sector: "Technology", type: "stock" },
  { ticker: "BTI.JO", name: "British American Tobacco", sector: "Consumer", type: "stock" },
  { ticker: "AGL.JO", name: "Anglo American Platinum", sector: "Mining", type: "stock" },
  { ticker: "SOL.JO", name: "Sasol", sector: "Energy", type: "stock" },
  { ticker: "SBK.JO", name: "Standard Bank", sector: "Finance", type: "stock" },
  { ticker: "FSR.JO", name: "FirstRand", sector: "Finance", type: "stock" },
  { ticker: "ABG.JO", name: "Absa Group", sector: "Finance", type: "stock" },
  { ticker: "NED.JO", name: "Nedbank", sector: "Finance", type: "stock" },
  { ticker: "INP.JO", name: "Investec", sector: "Finance", type: "stock" },
  { ticker: "MTN.JO", name: "MTN Group", sector: "Telecom", type: "stock" },
  { ticker: "VOD.JO", name: "Vodacom", sector: "Telecom", type: "stock" },
  { ticker: "SHP.JO", name: "Shoprite", sector: "Consumer", type: "stock" },
  { ticker: "CFR.JO", name: "Richemont", sector: "Consumer", type: "stock" },
  { ticker: "AMS.JO", name: "Anglo American", sector: "Mining", type: "stock" },
  { ticker: "IMP.JO", name: "Impala Platinum", sector: "Mining", type: "stock" },
  { ticker: "GFI.JO", name: "Gold Fields", sector: "Mining", type: "stock" },
  { ticker: "HAR.JO", name: "Harmony Gold", sector: "Mining", type: "stock" },
  { ticker: "BID.JO", name: "Bid Corp", sector: "Consumer", type: "stock" },
  { ticker: "MNP.JO", name: "Mondi", sector: "Materials", type: "stock" },
  { ticker: "DSY.JO", name: "Discovery", sector: "Finance", type: "stock" },
  { ticker: "SLM.JO", name: "Sanlam", sector: "Finance", type: "stock" },
  { ticker: "REM.JO", name: "Remgro", sector: "Conglomerate", type: "stock" },
  { ticker: "CPI.JO", name: "Capitec", sector: "Finance", type: "stock" },
  { ticker: "2222.SR", name: "Saudi Aramco", sector: "Energy", type: "stock" },
  { ticker: "1180.SR", name: "Al Rajhi Bank", sector: "Finance", type: "stock" },
  { ticker: "2010.SR", name: "SABIC", sector: "Chemicals", type: "stock" },
  { ticker: "1150.SR", name: "Alinma Bank", sector: "Finance", type: "stock" },
  { ticker: "2350.SR", name: "Saudi Kayan", sector: "Chemicals", type: "stock" },
  { ticker: "2380.SR", name: "SABIC Agri", sector: "Chemicals", type: "stock" },
  { ticker: "7010.SR", name: "STC", sector: "Telecom", type: "stock" },
  { ticker: "2020.SR", name: "SARCO", sector: "Industrials", type: "stock" },
  { ticker: "1010.SR", name: "Riyad Bank", sector: "Finance", type: "stock" },
  { ticker: "1020.SR", name: "Bank AlJazira", sector: "Finance", type: "stock" },
  { ticker: "1030.SR", name: "SABB", sector: "Finance", type: "stock" },
  { ticker: "1050.SR", name: "BSF", sector: "Finance", type: "stock" },
  { ticker: "1060.SR", name: "Saudi Investment Bank", sector: "Finance", type: "stock" },
  { ticker: "2050.SR", name: "Savola", sector: "Consumer", type: "stock" },
  { ticker: "FAB.AE", name: "First Abu Dhabi Bank", sector: "Finance", type: "stock" },
  { ticker: "ETISALAT.AE", name: "Etisalat", sector: "Telecom", type: "stock" },
  { ticker: "EMAAR.AE", name: "Emaar Properties", sector: "Real Estate", type: "stock" },
  { ticker: "DIB.AE", name: "Dubai Islamic Bank", sector: "Finance", type: "stock" },
  { ticker: "DFM.AE", name: "Dubai Financial Market", sector: "Finance", type: "stock" },
  { ticker: "ADNOC.AE", name: "ADNOC Distribution", sector: "Energy", type: "stock" },
];


export const expansionUS: AssetEntry[] = [
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology", type: "stock" },
  { ticker: "SNOW", name: "Snowflake", sector: "Technology", type: "stock" },
  { ticker: "DDOG", name: "Datadog", sector: "Technology", type: "stock" },
  { ticker: "ZS", name: "Zscaler", sector: "Technology", type: "stock" },
  { ticker: "CRWD", name: "CrowdStrike", sector: "Technology", type: "stock" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology", type: "stock" },
  { ticker: "FTNT", name: "Fortinet", sector: "Technology", type: "stock" },
  { ticker: "WDAY", name: "Workday", sector: "Technology", type: "stock" },
  { ticker: "VEEV", name: "Veeva Systems", sector: "Healthcare", type: "stock" },
  { ticker: "TWLO", name: "Twilio", sector: "Technology", type: "stock" },
  { ticker: "TTD", name: "The Trade Desk", sector: "Technology", type: "stock" },
  { ticker: "MELI", name: "MercadoLibre", sector: "Technology", type: "stock" },
  { ticker: "SE", name: "Sea Limited", sector: "Technology", type: "stock" },
  { ticker: "GRAB", name: "Grab Holdings", sector: "Technology", type: "stock" },
  { ticker: "BILI", name: "Bilibili", sector: "Technology", type: "stock" },
  { ticker: "BIDU", name: "Baidu", sector: "Technology", type: "stock" },
  { ticker: "JD", name: "JD.com", sector: "Technology", type: "stock" },
  { ticker: "PDD", name: "PDD Holdings", sector: "Technology", type: "stock" },
  { ticker: "LI", name: "Li Auto", sector: "Automotive", type: "stock" },
  { ticker: "XPEV", name: "XPeng", sector: "Automotive", type: "stock" },
  { ticker: "NIO", name: "NIO Inc", sector: "Automotive", type: "stock" },
  { ticker: "RIVN", name: "Rivian", sector: "Automotive", type: "stock" },
  { ticker: "LCID", name: "Lucid Group", sector: "Automotive", type: "stock" },
  { ticker: "FSR", name: "Fisker", sector: "Automotive", type: "stock" },
  { ticker: "CHPT", name: "ChargePoint", sector: "Energy", type: "stock" },
  { ticker: "BLNK", name: "Blink Charging", sector: "Energy", type: "stock" },
  { ticker: "FSLR", name: "First Solar", sector: "Energy", type: "stock" },
  { ticker: "ENPH", name: "Enphase Energy", sector: "Energy", type: "stock" },
  { ticker: "SEDG", name: "SolarEdge", sector: "Energy", type: "stock" },
  { ticker: "RUN", name: "Sunrun", sector: "Energy", type: "stock" },
  { ticker: "PLUG", name: "Plug Power", sector: "Energy", type: "stock" },
  { ticker: "BE", name: "Bloom Energy", sector: "Energy", type: "stock" },
  { ticker: "STEM", name: "Stem Inc", sector: "Energy", type: "stock" },
  { ticker: "ARRY", name: "Array Technologies", sector: "Energy", type: "stock" },
  { ticker: "NOVA", name: "Sunnova Energy", sector: "Energy", type: "stock" },
  { ticker: "SHLS", name: "Shoals Technologies", sector: "Energy", type: "stock" },
  { ticker: "RKLB", name: "Rocket Lab USA", sector: "Industrials", type: "stock" },
  { ticker: "SPCE", name: "Virgin Galactic", sector: "Industrials", type: "stock" },
  { ticker: "ASTS", name: "AST SpaceMobile", sector: "Technology", type: "stock" },
  { ticker: "IRDM", name: "Iridium Communications", sector: "Technology", type: "stock" },
  { ticker: "PATH", name: "UiPath", sector: "Technology", type: "stock" },
  { ticker: "AI", name: "C3.ai", sector: "Technology", type: "stock" },
  { ticker: "UPST", name: "Upstart Holdings", sector: "Finance", type: "stock" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Finance", type: "stock" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Finance", type: "stock" },
  { ticker: "COIN", name: "Coinbase", sector: "Finance", type: "stock" },
  { ticker: "AFRM", name: "Affirm Holdings", sector: "Finance", type: "stock" },
  { ticker: "BILL", name: "Bill Holdings", sector: "Technology", type: "stock" },
  { ticker: "HUBS", name: "HubSpot", sector: "Technology", type: "stock" },
  { ticker: "ZI", name: "ZoomInfo", sector: "Technology", type: "stock" },
  { ticker: "CFLT", name: "Confluent", sector: "Technology", type: "stock" },
  { ticker: "MDB", name: "MongoDB", sector: "Technology", type: "stock" },
  { ticker: "ESTC", name: "Elastic NV", sector: "Technology", type: "stock" },
  { ticker: "GTLB", name: "GitLab", sector: "Technology", type: "stock" },
  { ticker: "NET", name: "Cloudflare", sector: "Technology", type: "stock" },
  { ticker: "DOCN", name: "DigitalOcean", sector: "Technology", type: "stock" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "Technology", type: "stock" },
  { ticker: "VRT", name: "Vertiv Holdings", sector: "Technology", type: "stock" },
  { ticker: "DELL", name: "Dell Technologies", sector: "Technology", type: "stock" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", type: "stock" },
  { ticker: "WDC", name: "Western Digital", sector: "Technology", type: "stock" },
  { ticker: "STX", name: "Seagate Technology", sector: "Technology", type: "stock" },
  { ticker: "NTAP", name: "NetApp", sector: "Technology", type: "stock" },
  { ticker: "PSTG", name: "Pure Storage", sector: "Technology", type: "stock" },
  { ticker: "IONQ", name: "IonQ", sector: "Technology", type: "stock" },
  { ticker: "RGTI", name: "Rigetti Computing", sector: "Technology", type: "stock" },
  { ticker: "QBTS", name: "D-Wave Quantum", sector: "Technology", type: "stock" },
  { ticker: "QUBT", name: "Quantum Computing", sector: "Technology", type: "stock" },
  { ticker: "SOUN", name: "SoundHound AI", sector: "Technology", type: "stock" },
  { ticker: "BBAI", name: "BigBear.ai", sector: "Technology", type: "stock" },
  { ticker: "CAVA", name: "CAVA Group", sector: "Consumer", type: "stock" },
  { ticker: "BROS", name: "Dutch Bros", sector: "Consumer", type: "stock" },
  { ticker: "SHAK", name: "Shake Shack", sector: "Consumer", type: "stock" },
  { ticker: "WING", name: "Wingstop", sector: "Consumer", type: "stock" },
  { ticker: "TXRH", name: "Texas Roadhouse", sector: "Consumer", type: "stock" },
  { ticker: "EAT", name: "Brinker International", sector: "Consumer", type: "stock" },
  { ticker: "DRI", name: "Darden Restaurants", sector: "Consumer", type: "stock" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer", type: "stock" },
  { ticker: "QSR", name: "Restaurant Brands", sector: "Consumer", type: "stock" },
  { ticker: "WEN", name: "Wendys", sector: "Consumer", type: "stock" },
  { ticker: "JACK", name: "Jack in the Box", sector: "Consumer", type: "stock" },
  { ticker: "CAKE", name: "Cheesecake Factory", sector: "Consumer", type: "stock" },
  { ticker: "PLAY", name: "Dave & Busters", sector: "Consumer", type: "stock" },
  { ticker: "DIN", name: "Dine Brands", sector: "Consumer", type: "stock" },
  { ticker: "LULU", name: "Lululemon", sector: "Consumer", type: "stock" },
  { ticker: "NKE", name: "Nike", sector: "Consumer", type: "stock" },
  { ticker: "UAA", name: "Under Armour", sector: "Consumer", type: "stock" },
  { ticker: "DECK", name: "Deckers Outdoor", sector: "Consumer", type: "stock" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "CRSR", name: "Corsair Gaming", sector: "Technology", type: "stock" },
  { ticker: "U", name: "Unity Software", sector: "Technology", type: "stock" },
  { ticker: "RBLX", name: "Roblox", sector: "Technology", type: "stock" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Technology", type: "stock" },
  { ticker: "EA", name: "Electronic Arts", sector: "Technology", type: "stock" },
  { ticker: "ATVI", name: "Activision Blizzard", sector: "Technology", type: "stock" },
  { ticker: "DIS", name: "Walt Disney", sector: "Media", type: "stock" },
  { ticker: "CMCSA", name: "Comcast", sector: "Media", type: "stock" },
  { ticker: "NFLX", name: "Netflix", sector: "Media", type: "stock" },
  { ticker: "WBD", name: "Warner Bros Discovery", sector: "Media", type: "stock" },
  { ticker: "PARA", name: "Paramount Global", sector: "Media", type: "stock" },
  { ticker: "LYV", name: "Live Nation", sector: "Media", type: "stock" },
  { ticker: "SPOT", name: "Spotify", sector: "Technology", type: "stock" },
  { ticker: "ROKU", name: "Roku", sector: "Technology", type: "stock" },
  { ticker: "SNAP", name: "Snap Inc", sector: "Technology", type: "stock" },
  { ticker: "PINS", name: "Pinterest", sector: "Technology", type: "stock" },
  { ticker: "MTCH", name: "Match Group", sector: "Technology", type: "stock" },
  { ticker: "BMBL", name: "Bumble", sector: "Technology", type: "stock" },
  { ticker: "ABNB", name: "Airbnb", sector: "Consumer", type: "stock" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer", type: "stock" },
  { ticker: "EXPE", name: "Expedia", sector: "Consumer", type: "stock" },
  { ticker: "TRIP", name: "TripAdvisor", sector: "Consumer", type: "stock" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer", type: "stock" },
  { ticker: "HLT", name: "Hilton Worldwide", sector: "Consumer", type: "stock" },
  { ticker: "H", name: "Hyatt Hotels", sector: "Consumer", type: "stock" },
  { ticker: "WYNN", name: "Wynn Resorts", sector: "Consumer", type: "stock" },
  { ticker: "LVS", name: "Las Vegas Sands", sector: "Consumer", type: "stock" },
  { ticker: "MGM", name: "MGM Resorts", sector: "Consumer", type: "stock" },
  { ticker: "CZR", name: "Caesars Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "CVS", name: "CVS Health", sector: "Healthcare", type: "stock" },
  { ticker: "WBA", name: "Walgreens", sector: "Healthcare", type: "stock" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare", type: "stock" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare", type: "stock" },
  { ticker: "HUM", name: "Humana", sector: "Healthcare", type: "stock" },
  { ticker: "CNC", name: "Centene", sector: "Healthcare", type: "stock" },
  { ticker: "MOH", name: "Molina Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "DXCM", name: "DexCom", sector: "Healthcare", type: "stock" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "stock" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "SYK", name: "Stryker", sector: "Healthcare", type: "stock" },
  { ticker: "ZBH", name: "Zimmer Biomet", sector: "Healthcare", type: "stock" },
  { ticker: "MDT", name: "Medtronic", sector: "Healthcare", type: "stock" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Healthcare", type: "stock" },
  { ticker: "BDX", name: "Becton Dickinson", sector: "Healthcare", type: "stock" },
  { ticker: "BAX", name: "Baxter International", sector: "Healthcare", type: "stock" },
  { ticker: "ILMN", name: "Illumina", sector: "Healthcare", type: "stock" },
  { ticker: "TMO", name: "Thermo Fisher", sector: "Healthcare", type: "stock" },
  { ticker: "DHR", name: "Danaher", sector: "Healthcare", type: "stock" },
  { ticker: "A", name: "Agilent Technologies", sector: "Healthcare", type: "stock" },
  { ticker: "WAT", name: "Waters Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "MTD", name: "Mettler-Toledo", sector: "Healthcare", type: "stock" },
  { ticker: "PKI", name: "PerkinElmer", sector: "Healthcare", type: "stock" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials", type: "stock" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrials", type: "stock" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrials", type: "stock" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrials", type: "stock" },
  { ticker: "LHX", name: "L3Harris Technologies", sector: "Industrials", type: "stock" },
  { ticker: "HII", name: "Huntington Ingalls", sector: "Industrials", type: "stock" },
  { ticker: "TDG", name: "TransDigm", sector: "Industrials", type: "stock" },
  { ticker: "HWM", name: "Howmet Aerospace", sector: "Industrials", type: "stock" },
  { ticker: "TXT", name: "Textron", sector: "Industrials", type: "stock" },
  { ticker: "UNP", name: "Union Pacific", sector: "Transport", type: "stock" },
  { ticker: "CSX", name: "CSX Corporation", sector: "Transport", type: "stock" },
  { ticker: "NSC", name: "Norfolk Southern", sector: "Transport", type: "stock" },
  { ticker: "FDX", name: "FedEx", sector: "Logistics", type: "stock" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Logistics", type: "stock" },
  { ticker: "XOM", name: "Exxon Mobil", sector: "Energy", type: "stock" },
  { ticker: "CVX", name: "Chevron", sector: "Energy", type: "stock" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", type: "stock" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy", type: "stock" },
  { ticker: "PXD", name: "Pioneer Natural Resources", sector: "Energy", type: "stock" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", type: "stock" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", type: "stock" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", type: "stock" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", type: "stock" },
  { ticker: "SLB", name: "Schlumberger", sector: "Energy", type: "stock" },
  { ticker: "HAL", name: "Halliburton", sector: "Energy", type: "stock" },
  { ticker: "BKR", name: "Baker Hughes", sector: "Energy", type: "stock" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy", type: "stock" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", type: "stock" },
  { ticker: "APA", name: "APA Corporation", sector: "Energy", type: "stock" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities", type: "stock" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities", type: "stock" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", type: "stock" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", type: "stock" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", type: "stock" },
  { ticker: "EXC", name: "Exelon", sector: "Utilities", type: "stock" },
  { ticker: "SRE", name: "Sempra", sector: "Utilities", type: "stock" },
  { ticker: "WEC", name: "WEC Energy", sector: "Utilities", type: "stock" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities", type: "stock" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities", type: "stock" },
  { ticker: "PEG", name: "PSEG", sector: "Utilities", type: "stock" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", type: "stock" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities", type: "stock" },
  { ticker: "CMS", name: "CMS Energy", sector: "Utilities", type: "stock" },
  { ticker: "AMT", name: "American Tower", sector: "Real Estate", type: "stock" },
  { ticker: "PLD", name: "Prologis", sector: "Real Estate", type: "stock" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate", type: "stock" },
  { ticker: "EQIX", name: "Equinix", sector: "Real Estate", type: "stock" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate", type: "stock" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate", type: "stock" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate", type: "stock" },
  { ticker: "DLR", name: "Digital Realty", sector: "Real Estate", type: "stock" },
  { ticker: "WELL", name: "Welltower", sector: "Real Estate", type: "stock" },
  { ticker: "AVB", name: "AvalonBay", sector: "Real Estate", type: "stock" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate", type: "stock" },
  { ticker: "VTR", name: "Ventas", sector: "Real Estate", type: "stock" },
  { ticker: "ARE", name: "Alexandria Real Estate", sector: "Real Estate", type: "stock" },
  { ticker: "MAA", name: "Mid-America Apartment", sector: "Real Estate", type: "stock" },
  { ticker: "KIM", name: "Kimco Realty", sector: "Real Estate", type: "stock" },
  { ticker: "REG", name: "Regency Centers", sector: "Real Estate", type: "stock" },
];


export const expansionETFs: AssetEntry[] = [
  { ticker: "EWJ", name: "iShares MSCI Japan ETF", sector: "Japan", type: "etf" },
  { ticker: "EWZ", name: "iShares MSCI Brazil ETF", sector: "Brazil", type: "etf" },
  { ticker: "EWY", name: "iShares MSCI South Korea ETF", sector: "South Korea", type: "etf" },
  { ticker: "EWT", name: "iShares MSCI Taiwan ETF", sector: "Taiwan", type: "etf" },
  { ticker: "EWH", name: "iShares MSCI Hong Kong ETF", sector: "Hong Kong", type: "etf" },
  { ticker: "EWS", name: "iShares MSCI Singapore ETF", sector: "Singapore", type: "etf" },
  { ticker: "EWA", name: "iShares MSCI Australia ETF", sector: "Australia", type: "etf" },
  { ticker: "EWC", name: "iShares MSCI Canada ETF", sector: "Canada", type: "etf" },
  { ticker: "EWG", name: "iShares MSCI Germany ETF", sector: "Germany", type: "etf" },
  { ticker: "EWU", name: "iShares MSCI United Kingdom ETF", sector: "UK", type: "etf" },
  { ticker: "EWP", name: "iShares MSCI Spain ETF", sector: "Spain", type: "etf" },
  { ticker: "EWI", name: "iShares MSCI Italy ETF", sector: "Italy", type: "etf" },
  { ticker: "EWQ", name: "iShares MSCI France ETF", sector: "France", type: "etf" },
  { ticker: "EWL", name: "iShares MSCI Switzerland ETF", sector: "Switzerland", type: "etf" },
  { ticker: "EWD", name: "iShares MSCI Sweden ETF", sector: "Sweden", type: "etf" },
  { ticker: "EWN", name: "iShares MSCI Netherlands ETF", sector: "Netherlands", type: "etf" },
  { ticker: "EWK", name: "iShares MSCI Belgium ETF", sector: "Belgium", type: "etf" },
  { ticker: "EWO", name: "iShares MSCI Austria ETF", sector: "Austria", type: "etf" },
  { ticker: "THD", name: "iShares MSCI Thailand ETF", sector: "Thailand", type: "etf" },
  { ticker: "INDA", name: "iShares MSCI India ETF", sector: "India", type: "etf" },
  { ticker: "MCHI", name: "iShares MSCI China ETF", sector: "China", type: "etf" },
  { ticker: "FXI", name: "iShares China Large-Cap ETF", sector: "China", type: "etf" },
  { ticker: "KWEB", name: "KraneShares CSI China Internet ETF", sector: "China", type: "etf" },
  { ticker: "VGK", name: "Vanguard FTSE Europe ETF", sector: "Europe", type: "etf" },
  { ticker: "IEUR", name: "iShares Core MSCI Europe ETF", sector: "Europe", type: "etf" },
  { ticker: "VPL", name: "Vanguard FTSE Pacific ETF", sector: "Pacific", type: "etf" },
  { ticker: "AAXJ", name: "iShares MSCI All Country Asia ex Japan ETF", sector: "Asia", type: "etf" },
  { ticker: "FM", name: "iShares MSCI Frontier Multifactor ETF", sector: "Frontier", type: "etf" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF", sector: "Emerging", type: "etf" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", sector: "Emerging", type: "etf" },
  { ticker: "EEMA", name: "iShares MSCI Emerging Markets Asia ETF", sector: "Asia", type: "etf" },
  { ticker: "GXC", name: "SPDR S&P China ETF", sector: "China", type: "etf" },
  { ticker: "ASHR", name: "Xtrackers Harvest CSI 300 ETF", sector: "China", type: "etf" },
  { ticker: "ARGT", name: "Global X MSCI Argentina ETF", sector: "Argentina", type: "etf" },
  { ticker: "ECH", name: "iShares MSCI Chile ETF", sector: "Chile", type: "etf" },
  { ticker: "EPU", name: "iShares MSCI Peru ETF", sector: "Peru", type: "etf" },
  { ticker: "GXG", name: "Global X MSCI Colombia ETF", sector: "Colombia", type: "etf" },
  { ticker: "TUR", name: "iShares MSCI Turkey ETF", sector: "Turkey", type: "etf" },
  { ticker: "EIDO", name: "iShares MSCI Indonesia ETF", sector: "Indonesia", type: "etf" },
  { ticker: "EPHE", name: "iShares MSCI Philippines ETF", sector: "Philippines", type: "etf" },
  { ticker: "VNM", name: "VanEck Vietnam ETF", sector: "Vietnam", type: "etf" },
  { ticker: "EZA", name: "iShares MSCI South Africa ETF", sector: "South Africa", type: "etf" },
  { ticker: "AFK", name: "VanEck Africa Index ETF", sector: "Africa", type: "etf" },
  { ticker: "NGE", name: "Global X MSCI Nigeria ETF", sector: "Nigeria", type: "etf" },
  { ticker: "KSA", name: "iShares MSCI Saudi Arabia ETF", sector: "Saudi Arabia", type: "etf" },
  { ticker: "UAE", name: "iShares MSCI UAE ETF", sector: "UAE", type: "etf" },
  { ticker: "QAT", name: "iShares MSCI Qatar ETF", sector: "Qatar", type: "etf" },
  { ticker: "ENZL", name: "iShares MSCI New Zealand ETF", sector: "New Zealand", type: "etf" },
  { ticker: "NORW", name: "Global X MSCI Norway ETF", sector: "Norway", type: "etf" },
  { ticker: "EFNL", name: "iShares MSCI Finland ETF", sector: "Finland", type: "etf" },
  { ticker: "EDEN", name: "iShares MSCI Denmark ETF", sector: "Denmark", type: "etf" },
  { ticker: "EPOL", name: "iShares MSCI Poland ETF", sector: "Poland", type: "etf" },
  { ticker: "GREK", name: "Global X MSCI Greece ETF", sector: "Greece", type: "etf" },
  { ticker: "PGAL", name: "Global X MSCI Portugal ETF", sector: "Portugal", type: "etf" },
  { ticker: "EIRL", name: "iShares MSCI Ireland ETF", sector: "Ireland", type: "etf" },
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "Innovation", type: "etf" },
  { ticker: "ARKW", name: "ARK Next Gen Internet ETF", sector: "Technology", type: "etf" },
  { ticker: "ARKG", name: "ARK Genomic Revolution ETF", sector: "Healthcare", type: "etf" },
  { ticker: "ARKF", name: "ARK Fintech Innovation ETF", sector: "Finance", type: "etf" },
  { ticker: "ARKQ", name: "ARK Autonomous Tech & Robotics ETF", sector: "Technology", type: "etf" },
  { ticker: "BOTZ", name: "Global X Robotics & AI ETF", sector: "Technology", type: "etf" },
  { ticker: "ROBO", name: "ROBO Global Robotics & Automation ETF", sector: "Technology", type: "etf" },
  { ticker: "HACK", name: "ETFMG Prime Cyber Security ETF", sector: "Technology", type: "etf" },
  { ticker: "BUG", name: "Global X Cybersecurity ETF", sector: "Technology", type: "etf" },
  { ticker: "CLOU", name: "Global X Cloud Computing ETF", sector: "Technology", type: "etf" },
  { ticker: "SKYY", name: "First Trust Cloud Computing ETF", sector: "Technology", type: "etf" },
  { ticker: "FINX", name: "Global X FinTech ETF", sector: "Finance", type: "etf" },
  { ticker: "DRIV", name: "Global X Autonomous & Electric Vehicles ETF", sector: "Automotive", type: "etf" },
  { ticker: "LIT", name: "Global X Lithium & Battery Tech ETF", sector: "Materials", type: "etf" },
  { ticker: "URA", name: "Global X Uranium ETF", sector: "Energy", type: "etf" },
  { ticker: "ICLN", name: "iShares Global Clean Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "TAN", name: "Invesco Solar ETF", sector: "Energy", type: "etf" },
  { ticker: "PBW", name: "Invesco WilderHill Clean Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "QCLN", name: "First Trust NASDAQ Clean Edge Green Energy ETF", sector: "Energy", type: "etf" },
  { ticker: "ESPO", name: "VanEck Video Gaming & eSports ETF", sector: "Technology", type: "etf" },
  { ticker: "HERO", name: "Global X Video Games & Esports ETF", sector: "Technology", type: "etf" },
  { ticker: "BETZ", name: "Roundhill Sports Betting & iGaming ETF", sector: "Consumer", type: "etf" },
  { ticker: "SOCL", name: "Global X Social Media ETF", sector: "Technology", type: "etf" },
  { ticker: "OGIG", name: "O'Shares Global Internet Giants ETF", sector: "Technology", type: "etf" },
  { ticker: "CIBR", name: "First Trust NASDAQ Cybersecurity ETF", sector: "Technology", type: "etf" },
  { ticker: "AIQ", name: "Global X Artificial Intelligence & Technology ETF", sector: "Technology", type: "etf" },
  { ticker: "IRBO", name: "iShares Robotics and Artificial Intelligence ETF", sector: "Technology", type: "etf" },
  { ticker: "MOON", name: "Direxion Moonshot Innovators ETF", sector: "Technology", type: "etf" },
  { ticker: "JETS", name: "US Global Jets ETF", sector: "Transport", type: "etf" },
  { ticker: "AWAY", name: "ETFMG Travel Tech ETF", sector: "Consumer", type: "etf" },
  { ticker: "BLOK", name: "Amplify Transformational Data Sharing ETF", sector: "Technology", type: "etf" },
  { ticker: "BITQ", name: "Bitwise Crypto Industry Innovators ETF", sector: "Technology", type: "etf" },
  { ticker: "WGMI", name: "Valkyrie Bitcoin Miners ETF", sector: "Technology", type: "etf" },
  { ticker: "COPX", name: "Global X Copper Miners ETF", sector: "Mining", type: "etf" },
  { ticker: "SIL", name: "Global X Silver Miners ETF", sector: "Mining", type: "etf" },
  { ticker: "GDXJ", name: "VanEck Junior Gold Miners ETF", sector: "Mining", type: "etf" },
  { ticker: "XME", name: "SPDR S&P Metals & Mining ETF", sector: "Mining", type: "etf" },
  { ticker: "REMX", name: "VanEck Rare Earth/Strategic Metals ETF", sector: "Mining", type: "etf" },
  { ticker: "MOO", name: "VanEck Agribusiness ETF", sector: "Agriculture", type: "etf" },
  { ticker: "VEGI", name: "iShares MSCI Agriculture Producers ETF", sector: "Agriculture", type: "etf" },
  { ticker: "WOOD", name: "iShares Global Timber & Forestry ETF", sector: "Materials", type: "etf" },
  { ticker: "PHO", name: "Invesco Water Resources ETF", sector: "Utilities", type: "etf" },
  { ticker: "CGW", name: "Invesco S&P Global Water Index ETF", sector: "Utilities", type: "etf" },
  { ticker: "PAVE", name: "Global X US Infrastructure Development ETF", sector: "Industrials", type: "etf" },
  { ticker: "IFRA", name: "iShares US Infrastructure ETF", sector: "Industrials", type: "etf" },
  { ticker: "NFRA", name: "FlexShares STOXX Global Broad Infrastructure ETF", sector: "Industrials", type: "etf" },
];
