import type { AssetEntry } from "./types";


export const expansion3: AssetEntry[] = [
  { ticker: "2801.T", name: "Kikkoman", sector: "Consumer", type: "stock" },
  { ticker: "2502.T", name: "Asahi Group", sector: "Consumer", type: "stock" },
  { ticker: "2503.T", name: "Kirin Holdings", sector: "Consumer", type: "stock" },
  { ticker: "4452.T", name: "Kao Corporation", sector: "Consumer", type: "stock" },
  { ticker: "4661.T", name: "Oriental Land", sector: "Consumer", type: "stock" },
  { ticker: "9202.T", name: "ANA Holdings", sector: "Transport", type: "stock" },
  { ticker: "9201.T", name: "Japan Airlines", sector: "Transport", type: "stock" },
  { ticker: "4689.T", name: "LY Corporation", sector: "Technology", type: "stock" },
  { ticker: "4755.T", name: "Rakuten Group", sector: "Technology", type: "stock" },
  { ticker: "6857.T", name: "Advantest", sector: "Technology", type: "stock" },
  { ticker: "6723.T", name: "Renesas Electronics", sector: "Technology", type: "stock" },
  { ticker: "6146.T", name: "Disco Corporation", sector: "Technology", type: "stock" },
  { ticker: "6920.T", name: "Lasertec", sector: "Technology", type: "stock" },
  { ticker: "7735.T", name: "Screen Holdings", sector: "Technology", type: "stock" },
  { ticker: "4307.T", name: "Nomura Research", sector: "Technology", type: "stock" },
  { ticker: "9613.T", name: "NTT Data", sector: "Technology", type: "stock" },
  { ticker: "6504.T", name: "Fuji Electric", sector: "Technology", type: "stock" },
  { ticker: "6645.T", name: "Omron", sector: "Technology", type: "stock" },
  { ticker: "6479.T", name: "Minebea Mitsumi", sector: "Technology", type: "stock" },
  { ticker: "6770.T", name: "Alps Alpine", sector: "Technology", type: "stock" },
  { ticker: "7269.T", name: "Suzuki Motor", sector: "Automotive", type: "stock" },
  { ticker: "7201.T", name: "Nissan Motor", sector: "Automotive", type: "stock" },
  { ticker: "7261.T", name: "Mazda Motor", sector: "Automotive", type: "stock" },
  { ticker: "7270.T", name: "Subaru", sector: "Automotive", type: "stock" },
  { ticker: "7202.T", name: "Isuzu Motors", sector: "Automotive", type: "stock" },
  { ticker: "3086.T", name: "J.Front Retailing", sector: "Consumer", type: "stock" },
  { ticker: "3099.T", name: "Isetan Mitsukoshi", sector: "Consumer", type: "stock" },
  { ticker: "8267.T", name: "Aeon", sector: "Consumer", type: "stock" },
  { ticker: "2651.T", name: "Lawson", sector: "Consumer", type: "stock" },
  { ticker: "3088.T", name: "Matsumotokiyoshi", sector: "Consumer", type: "stock" },
  { ticker: "6762.T", name: "TDK Corporation", sector: "Technology", type: "stock" },
  { ticker: "6963.T", name: "Rohm", sector: "Technology", type: "stock" },
  { ticker: "7752.T", name: "Ricoh", sector: "Technology", type: "stock" },
  { ticker: "7762.T", name: "Citizen Watch", sector: "Consumer", type: "stock" },
  { ticker: "5401.T", name: "Nippon Steel", sector: "Materials", type: "stock" },
  { ticker: "5411.T", name: "JFE Holdings", sector: "Materials", type: "stock" },
  { ticker: "3405.T", name: "Kureha", sector: "Chemicals", type: "stock" },
  { ticker: "4042.T", name: "Tosoh", sector: "Chemicals", type: "stock" },
  { ticker: "4043.T", name: "Tokuyama", sector: "Chemicals", type: "stock" },
  { ticker: "4021.T", name: "Nissan Chemical", sector: "Chemicals", type: "stock" },
  { ticker: "4004.T", name: "Showa Denko", sector: "Chemicals", type: "stock" },
  { ticker: "4005.T", name: "Sumitomo Chemical", sector: "Chemicals", type: "stock" },
  { ticker: "4183.T", name: "Mitsui Chemicals", sector: "Chemicals", type: "stock" },
  { ticker: "4188.T", name: "Mitsubishi Chemical", sector: "Chemicals", type: "stock" },
  { ticker: "6301.T", name: "Komatsu", sector: "Industrials", type: "stock" },
  { ticker: "6305.T", name: "Hitachi Construction", sector: "Industrials", type: "stock" },
  { ticker: "5332.T", name: "TOTO", sector: "Industrials", type: "stock" },
  { ticker: "6326.T", name: "Kubota", sector: "Industrials", type: "stock" },
  { ticker: "7013.T", name: "IHI Corporation", sector: "Industrials", type: "stock" },
  { ticker: "7011.T", name: "Mitsubishi Heavy", sector: "Industrials", type: "stock" },
  { ticker: "017670.KS", name: "SK Telecom", sector: "Telecom", type: "stock" },
  { ticker: "030200.KS", name: "KT Corporation", sector: "Telecom", type: "stock" },
  { ticker: "018260.KS", name: "Samsung SDS", sector: "Technology", type: "stock" },
  { ticker: "000810.KS", name: "Samsung Fire", sector: "Finance", type: "stock" },
  { ticker: "010130.KS", name: "Korea Zinc", sector: "Materials", type: "stock" },
  { ticker: "034220.KS", name: "LG Display", sector: "Technology", type: "stock" },
  { ticker: "003490.KS", name: "Korean Air", sector: "Transport", type: "stock" },
  { ticker: "028670.KS", name: "Pan Ocean", sector: "Transport", type: "stock" },
  { ticker: "068270.KS", name: "Celltrion", sector: "Healthcare", type: "stock" },
  { ticker: "207940.KS", name: "Samsung Biologics", sector: "Healthcare", type: "stock" },
  { ticker: "326030.KS", name: "SK Biopharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "128940.KS", name: "Hanmi Pharm", sector: "Healthcare", type: "stock" },
  { ticker: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Automotive", type: "stock" },
  { ticker: "BPCL.NS", name: "Bharat Petroleum", sector: "Energy", type: "stock" },
  { ticker: "GRASIM.NS", name: "Grasim Industries", sector: "Materials", type: "stock" },
  { ticker: "SHREECEM.NS", name: "Shree Cement", sector: "Materials", type: "stock" },
  { ticker: "HAVELLS.NS", name: "Havells India", sector: "Industrials", type: "stock" },
  { ticker: "GODREJCP.NS", name: "Godrej Consumer", sector: "Consumer", type: "stock" },
  { ticker: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Chemicals", type: "stock" },
  { ticker: "DABUR.NS", name: "Dabur India", sector: "Consumer", type: "stock" },
  { ticker: "MARICO.NS", name: "Marico", sector: "Consumer", type: "stock" },
  { ticker: "COLPAL.NS", name: "Colgate-Palmolive India", sector: "Consumer", type: "stock" },
  { ticker: "PAGEIND.NS", name: "Page Industries", sector: "Consumer", type: "stock" },
  { ticker: "TRENT.NS", name: "Trent", sector: "Consumer", type: "stock" },
  { ticker: "DMART.NS", name: "Avenue Supermarts", sector: "Consumer", type: "stock" },
  { ticker: "NAUKRI.NS", name: "Info Edge India", sector: "Technology", type: "stock" },
  { ticker: "ZOMATO.NS", name: "Zomato", sector: "Technology", type: "stock" },
  { ticker: "PAYTM.NS", name: "One97 Communications", sector: "Technology", type: "stock" },
  { ticker: "PERSISTENT.NS", name: "Persistent Systems", sector: "Technology", type: "stock" },
  { ticker: "LTIM.NS", name: "LTIMindtree", sector: "Technology", type: "stock" },
  { ticker: "MPHASIS.NS", name: "Mphasis", sector: "Technology", type: "stock" },
  { ticker: "COFORGE.NS", name: "Coforge", sector: "Technology", type: "stock" },
  { ticker: "TATAPOWER.NS", name: "Tata Power", sector: "Energy", type: "stock" },
  { ticker: "TORNTPHARM.NS", name: "Torrent Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "LUPIN.NS", name: "Lupin", sector: "Healthcare", type: "stock" },
  { ticker: "AUROPHARMA.NS", name: "Aurobindo Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "BIOCON.NS", name: "Biocon", sector: "Healthcare", type: "stock" },
  { ticker: "SBILIFE.NS", name: "SBI Life Insurance", sector: "Finance", type: "stock" },
  { ticker: "HDFCLIFE.NS", name: "HDFC Life Insurance", sector: "Finance", type: "stock" },
  { ticker: "ICICIPRULI.NS", name: "ICICI Prudential Life", sector: "Finance", type: "stock" },
  { ticker: "BANDHANBNK.NS", name: "Bandhan Bank", sector: "Finance", type: "stock" },
  { ticker: "IDFCFIRSTB.NS", name: "IDFC First Bank", sector: "Finance", type: "stock" },
  { ticker: "PNB.NS", name: "Punjab National Bank", sector: "Finance", type: "stock" },
  { ticker: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Finance", type: "stock" },
  { ticker: "CANBK.NS", name: "Canara Bank", sector: "Finance", type: "stock" },
  { ticker: "FEDERALBNK.NS", name: "Federal Bank", sector: "Finance", type: "stock" },
  { ticker: "0001.HK", name: "CK Hutchison", sector: "Conglomerate", type: "stock" },
  { ticker: "0002.HK", name: "CLP Holdings", sector: "Energy", type: "stock" },
  { ticker: "0003.HK", name: "HK & China Gas", sector: "Energy", type: "stock" },
  { ticker: "0006.HK", name: "Power Assets", sector: "Energy", type: "stock" },
  { ticker: "0011.HK", name: "Hang Seng Bank", sector: "Finance", type: "stock" },
  { ticker: "0012.HK", name: "Henderson Land", sector: "Real Estate", type: "stock" },
  { ticker: "0016.HK", name: "Sun Hung Kai Properties", sector: "Real Estate", type: "stock" },
  { ticker: "0017.HK", name: "New World Development", sector: "Real Estate", type: "stock" },
  { ticker: "0019.HK", name: "Swire Pacific", sector: "Conglomerate", type: "stock" },
  { ticker: "0066.HK", name: "MTR Corporation", sector: "Transport", type: "stock" },
  { ticker: "0083.HK", name: "Sino Land", sector: "Real Estate", type: "stock" },
  { ticker: "0101.HK", name: "Hang Lung Properties", sector: "Real Estate", type: "stock" },
  { ticker: "0267.HK", name: "CITIC", sector: "Finance", type: "stock" },
  { ticker: "0288.HK", name: "WH Group", sector: "Consumer", type: "stock" },
  { ticker: "0291.HK", name: "China Resources Beer", sector: "Consumer", type: "stock" },
  { ticker: "0322.HK", name: "Tingyi", sector: "Consumer", type: "stock" },
  { ticker: "0669.HK", name: "Techtronic Industries", sector: "Industrials", type: "stock" },
  { ticker: "0762.HK", name: "China Unicom", sector: "Telecom", type: "stock" },
  { ticker: "0823.HK", name: "Link REIT", sector: "Real Estate", type: "stock" },
  { ticker: "0960.HK", name: "Longfor Group", sector: "Real Estate", type: "stock" },
  { ticker: "0968.HK", name: "Xinyi Solar", sector: "Energy", type: "stock" },
  { ticker: "1038.HK", name: "CK Infrastructure", sector: "Infrastructure", type: "stock" },
  { ticker: "1044.HK", name: "Hengan International", sector: "Consumer", type: "stock" },
  { ticker: "1088.HK", name: "China Shenhua", sector: "Energy", type: "stock" },
  { ticker: "1109.HK", name: "China Resources Land", sector: "Real Estate", type: "stock" },
  { ticker: "1113.HK", name: "CK Asset Holdings", sector: "Real Estate", type: "stock" },
  { ticker: "1288.HK", name: "Agricultural Bank of China", sector: "Finance", type: "stock" },
  { ticker: "1336.HK", name: "New China Life", sector: "Finance", type: "stock" },
  { ticker: "1658.HK", name: "Postal Savings Bank", sector: "Finance", type: "stock" },
  { ticker: "1776.HK", name: "GF Securities", sector: "Finance", type: "stock" },
  { ticker: "1818.HK", name: "Zhaojin Mining", sector: "Mining", type: "stock" },
  { ticker: "1876.HK", name: "Budweiser APAC", sector: "Consumer", type: "stock" },
  { ticker: "1997.HK", name: "Wharf Real Estate", sector: "Real Estate", type: "stock" },
  { ticker: "2007.HK", name: "Country Garden", sector: "Real Estate", type: "stock" },
  { ticker: "2018.HK", name: "AAC Technologies", sector: "Technology", type: "stock" },
  { ticker: "2388.HK", name: "BOC Hong Kong", sector: "Finance", type: "stock" },
  { ticker: "2688.HK", name: "ENN Energy", sector: "Energy", type: "stock" },
  { ticker: "3328.HK", name: "Bank of Communications", sector: "Finance", type: "stock" },
  { ticker: "3968.HK", name: "China Merchants Bank", sector: "Finance", type: "stock" },
  { ticker: "6098.HK", name: "Country Garden Services", sector: "Consumer", type: "stock" },
  { ticker: "6618.HK", name: "JD Health", sector: "Healthcare", type: "stock" },
  { ticker: "9626.HK", name: "Bilibili", sector: "Technology", type: "stock" },
  { ticker: "9698.HK", name: "GDS Holdings", sector: "Technology", type: "stock" },
  { ticker: "9888.HK", name: "Baidu", sector: "Technology", type: "stock" },
  { ticker: "9961.HK", name: "Trip.com Group", sector: "Consumer", type: "stock" },
  { ticker: "9901.HK", name: "New Oriental Education", sector: "Consumer", type: "stock" },
  { ticker: "BKNG.AS", name: "Booking Holdings NV", sector: "Consumer", type: "stock" },
  { ticker: "PROSUS.AS", name: "Prosus NV", sector: "Technology", type: "stock" },
  { ticker: "SHOP.DE", name: "Shopify DE", sector: "Technology", type: "stock" },
  { ticker: "ADYEN.AS", name: "Adyen", sector: "Technology", type: "stock" },
  { ticker: "TKWY.AS", name: "Just Eat Takeaway", sector: "Technology", type: "stock" },
  { ticker: "URW.AS", name: "Unibail-Rodamco", sector: "Real Estate", type: "stock" },
  { ticker: "REN.LS", name: "REN", sector: "Energy", type: "stock" },
  { ticker: "GALP.LS", name: "Galp Energia", sector: "Energy", type: "stock" },
  { ticker: "EDP.LS", name: "EDP", sector: "Energy", type: "stock" },
  { ticker: "EDPR.LS", name: "EDP Renovaveis", sector: "Energy", type: "stock" },
  { ticker: "JMT.LS", name: "Jeronimo Martins", sector: "Consumer", type: "stock" },
  { ticker: "SON.LS", name: "Sonae", sector: "Consumer", type: "stock" },
  { ticker: "NZYM-B.CO", name: "Novozymes", sector: "Healthcare", type: "stock" },
  { ticker: "DEMANT.CO", name: "Demant", sector: "Healthcare", type: "stock" },
  { ticker: "GN.CO", name: "GN Store Nord", sector: "Technology", type: "stock" },
  { ticker: "TRYG.CO", name: "Tryg", sector: "Finance", type: "stock" },
  { ticker: "FLS.CO", name: "FLSmidth", sector: "Industrials", type: "stock" },
  { ticker: "ROCK-B.CO", name: "Rockwool", sector: "Materials", type: "stock" },
  { ticker: "BAVA.CO", name: "Bavarian Nordic", sector: "Healthcare", type: "stock" },
  { ticker: "AMBU-B.CO", name: "Ambu", sector: "Healthcare", type: "stock" },
  { ticker: "ELUX-B.ST", name: "Electrolux", sector: "Consumer", type: "stock" },
  { ticker: "BOL.ST", name: "Boliden", sector: "Mining", type: "stock" },
  { ticker: "SSAB-A.ST", name: "SSAB", sector: "Materials", type: "stock" },
  { ticker: "SKA-B.ST", name: "Skanska", sector: "Industrials", type: "stock" },
  { ticker: "SWMA.ST", name: "Swedish Match", sector: "Consumer", type: "stock" },
  { ticker: "KINV-B.ST", name: "Kinnevik", sector: "Finance", type: "stock" },
  { ticker: "TELIA.ST", name: "Telia Company", sector: "Telecom", type: "stock" },
  { ticker: "INVE-B.ST", name: "Investor AB", sector: "Finance", type: "stock" },
  { ticker: "ASSA-B.ST", name: "ASSA ABLOY", sector: "Industrials", type: "stock" },
  { ticker: "GETI-B.ST", name: "Getinge", sector: "Healthcare", type: "stock" },
  { ticker: "NIBE-B.ST", name: "NIBE Industrier", sector: "Industrials", type: "stock" },
  { ticker: "SAAB-B.ST", name: "Saab", sector: "Industrials", type: "stock" },
  { ticker: "EVO.ST", name: "Evolution Gaming", sector: "Technology", type: "stock" },
  { ticker: "EKTA-B.ST", name: "Elekta", sector: "Healthcare", type: "stock" },
  { ticker: "KEA.IR", name: "Kerry Group", sector: "Consumer", type: "stock" },
  { ticker: "SKG.IR", name: "Smurfit Kappa", sector: "Materials", type: "stock" },
  { ticker: "CRG.IR", name: "Cairn Homes", sector: "Real Estate", type: "stock" },
  { ticker: "KRZ.IR", name: "Kingspan", sector: "Materials", type: "stock" },
  { ticker: "RYAAY.IR", name: "Ryanair", sector: "Transport", type: "stock" },
  { ticker: "CFR.SW", name: "Richemont", sector: "Consumer", type: "stock" },
  { ticker: "ADEN.SW", name: "Adecco", sector: "Industrials", type: "stock" },
  { ticker: "CLN.SW", name: "Clariant", sector: "Chemicals", type: "stock" },
  { ticker: "PGHN.SW", name: "Partners Group", sector: "Finance", type: "stock" },
  { ticker: "SGSN.SW", name: "SGS", sector: "Industrials", type: "stock" },
  { ticker: "SIGN.SW", name: "SIG Group", sector: "Materials", type: "stock" },
  { ticker: "DKSH.SW", name: "DKSH Holding", sector: "Industrials", type: "stock" },
  { ticker: "GALN.SW", name: "Galena Mining", sector: "Mining", type: "stock" },
  { ticker: "LHN.SW", name: "LafargeHolcim", sector: "Materials", type: "stock" },
  { ticker: "ALCC.SW", name: "Alcon", sector: "Healthcare", type: "stock" },
  { ticker: "TWE.AX", name: "Treasury Wine", sector: "Consumer", type: "stock" },
  { ticker: "APT.AX", name: "Afterpay", sector: "Technology", type: "stock" },
  { ticker: "SQ2.AX", name: "Block Inc", sector: "Technology", type: "stock" },
  { ticker: "MIN.AX", name: "Mineral Resources", sector: "Mining", type: "stock" },
  { ticker: "PLS.AX", name: "Pilbara Minerals", sector: "Mining", type: "stock" },
  { ticker: "LYC.AX", name: "Lynas Rare Earths", sector: "Mining", type: "stock" },
  { ticker: "IGO.AX", name: "IGO Limited", sector: "Mining", type: "stock" },
  { ticker: "OZL.AX", name: "OZ Minerals", sector: "Mining", type: "stock" },
  { ticker: "NST.AX", name: "Northern Star", sector: "Mining", type: "stock" },
  { ticker: "EVN.AX", name: "Evolution Mining", sector: "Mining", type: "stock" },
  { ticker: "GOR.AX", name: "Gold Road Resources", sector: "Mining", type: "stock" },
  { ticker: "S32.AX", name: "South32", sector: "Mining", type: "stock" },
  { ticker: "ILU.AX", name: "Iluka Resources", sector: "Mining", type: "stock" },
  { ticker: "BPT.AX", name: "Beach Energy", sector: "Energy", type: "stock" },
  { ticker: "ORG.AX", name: "Origin Energy", sector: "Energy", type: "stock" },
  { ticker: "AGL.AX", name: "AGL Energy", sector: "Energy", type: "stock" },
  { ticker: "VCX.AX", name: "Vicinity Centres", sector: "Real Estate", type: "stock" },
  { ticker: "GPT.AX", name: "GPT Group", sector: "Real Estate", type: "stock" },
  { ticker: "DXS.AX", name: "Dexus", sector: "Real Estate", type: "stock" },
  { ticker: "MGR.AX", name: "Mirvac Group", sector: "Real Estate", type: "stock" },
  { ticker: "LLC.AX", name: "Lendlease", sector: "Real Estate", type: "stock" },
  { ticker: "SGP.AX", name: "Stockland", sector: "Real Estate", type: "stock" },
  { ticker: "ALX.AX", name: "Atlas Arteria", sector: "Infrastructure", type: "stock" },
  { ticker: "TCL.AX", name: "Transurban", sector: "Infrastructure", type: "stock" },
  { ticker: "SEK.AX", name: "SEEK", sector: "Technology", type: "stock" },
  { ticker: "CAR.AX", name: "CAR Group", sector: "Technology", type: "stock" },
  { ticker: "NWS.AX", name: "News Corp", sector: "Media", type: "stock" },
  { ticker: "DMP.AX", name: "Dominos Pizza", sector: "Consumer", type: "stock" },
  { ticker: "SUL.AX", name: "Super Retail", sector: "Consumer", type: "stock" },
  { ticker: "JBH.AX", name: "JB Hi-Fi", sector: "Consumer", type: "stock" },
  { ticker: "HVN.AX", name: "Harvey Norman", sector: "Consumer", type: "stock" },
  { ticker: "WES.AX", name: "Wesfarmers", sector: "Consumer", type: "stock" },
  { ticker: "CCL.AX", name: "Coca-Cola Amatil", sector: "Consumer", type: "stock" },
  { ticker: "A2M.AX", name: "a2 Milk", sector: "Consumer", type: "stock" },
  { ticker: "BXB.AX", name: "Brambles", sector: "Logistics", type: "stock" },
  { ticker: "AZJ.AX", name: "Aurizon", sector: "Transport", type: "stock" },
  { ticker: "MG.TO", name: "Magna International", sector: "Automotive", type: "stock" },
  { ticker: "DOO.TO", name: "BRP Inc", sector: "Consumer", type: "stock" },
  { ticker: "OTEX.TO", name: "Open Text", sector: "Technology", type: "stock" },
  { ticker: "BB.TO", name: "BlackBerry", sector: "Technology", type: "stock" },
  { ticker: "LSPD.TO", name: "Lightspeed Commerce", sector: "Technology", type: "stock" },
  { ticker: "DCBO.TO", name: "Docebo", sector: "Technology", type: "stock" },
  { ticker: "KXS.TO", name: "Kinaxis", sector: "Technology", type: "stock" },
  { ticker: "DSG.TO", name: "Descartes Systems", sector: "Technology", type: "stock" },
  { ticker: "AC.TO", name: "Air Canada", sector: "Transport", type: "stock" },
  { ticker: "EMA.TO", name: "Emera", sector: "Utilities", type: "stock" },
  { ticker: "FTS.TO", name: "Fortis", sector: "Utilities", type: "stock" },
  { ticker: "H.TO", name: "Hydro One", sector: "Utilities", type: "stock" },
  { ticker: "AQN.TO", name: "Algonquin Power", sector: "Utilities", type: "stock" },
  { ticker: "BEP-UN.TO", name: "Brookfield Renewable", sector: "Energy", type: "stock" },
  { ticker: "TRI.TO", name: "Thomson Reuters", sector: "Technology", type: "stock" },
  { ticker: "WSP.TO", name: "WSP Global", sector: "Industrials", type: "stock" },
  { ticker: "SNC.TO", name: "SNC-Lavalin", sector: "Industrials", type: "stock" },
  { ticker: "STN.TO", name: "Stantec", sector: "Industrials", type: "stock" },
  { ticker: "CCL-B.TO", name: "CCL Industries", sector: "Materials", type: "stock" },
  { ticker: "WFG.TO", name: "West Fraser Timber", sector: "Materials", type: "stock" },
  { ticker: "IFP.TO", name: "Interfor", sector: "Materials", type: "stock" },
  { ticker: "CFP.TO", name: "Canfor", sector: "Materials", type: "stock" },
  { ticker: "PKI.TO", name: "Parkland", sector: "Energy", type: "stock" },
  { ticker: "KEY.TO", name: "Keyera", sector: "Energy", type: "stock" },
  { ticker: "PPL.TO", name: "Pembina Pipeline", sector: "Energy", type: "stock" },
  { ticker: "IPL.TO", name: "Inter Pipeline", sector: "Energy", type: "stock" },
  { ticker: "ARX.TO", name: "ARC Resources", sector: "Energy", type: "stock" },
  { ticker: "WCP.TO", name: "Whitecap Resources", sector: "Energy", type: "stock" },
  { ticker: "TVE.TO", name: "Tamarack Valley", sector: "Energy", type: "stock" },
  { ticker: "BTE.TO", name: "Baytex Energy", sector: "Energy", type: "stock" },
  { ticker: "ERF.TO", name: "Enerplus", sector: "Energy", type: "stock" },
  { ticker: "VET.TO", name: "Vermilion Energy", sector: "Energy", type: "stock" },
  { ticker: "MEG.TO", name: "MEG Energy", sector: "Energy", type: "stock" },
  { ticker: "CPG.TO", name: "Crescent Point", sector: "Energy", type: "stock" },
  { ticker: "IMO.TO", name: "Imperial Oil", sector: "Energy", type: "stock" },
  { ticker: "HSE.TO", name: "Husky Energy", sector: "Energy", type: "stock" },
  { ticker: "ITSA4.SA", name: "Itausa", sector: "Finance", type: "stock" },
  { ticker: "BBSE3.SA", name: "BB Seguridade", sector: "Finance", type: "stock" },
  { ticker: "ENBR3.SA", name: "Energias do Brasil", sector: "Energy", type: "stock" },
  { ticker: "TAEE11.SA", name: "Taesa", sector: "Energy", type: "stock" },
  { ticker: "CPFE3.SA", name: "CPFL Energia", sector: "Energy", type: "stock" },
  { ticker: "TIMS3.SA", name: "TIM SA", sector: "Telecom", type: "stock" },
  { ticker: "BRFS3.SA", name: "BRF SA", sector: "Consumer", type: "stock" },
  { ticker: "MRFG3.SA", name: "Marfrig", sector: "Consumer", type: "stock" },
  { ticker: "BEEF3.SA", name: "Minerva Foods", sector: "Consumer", type: "stock" },
  { ticker: "NTCO3.SA", name: "Natura & Co", sector: "Consumer", type: "stock" },
  { ticker: "COGN3.SA", name: "Cogna Educacao", sector: "Consumer", type: "stock" },
  { ticker: "YDUQ3.SA", name: "Yduqs", sector: "Consumer", type: "stock" },
  { ticker: "CYRE3.SA", name: "Cyrela", sector: "Real Estate", type: "stock" },
  { ticker: "MRVE3.SA", name: "MRV Engenharia", sector: "Real Estate", type: "stock" },
  { ticker: "EVEN3.SA", name: "Even Construtora", sector: "Real Estate", type: "stock" },
  { ticker: "DIRR3.SA", name: "Direcional", sector: "Real Estate", type: "stock" },
  { ticker: "FLRY3.SA", name: "Fleury", sector: "Healthcare", type: "stock" },
  { ticker: "QUAL3.SA", name: "Qualicorp", sector: "Healthcare", type: "stock" },
  { ticker: "RDOR3.SA", name: "Rede D'Or", sector: "Healthcare", type: "stock" },
  { ticker: "PCAR3.SA", name: "GPA SA", sector: "Consumer", type: "stock" },
  { ticker: "CRFB3.SA", name: "Carrefour Brasil", sector: "Consumer", type: "stock" },
  { ticker: "ASAI3.SA", name: "Assai", sector: "Consumer", type: "stock" },
  { ticker: "ARZZ3.SA", name: "Arezzo", sector: "Consumer", type: "stock" },
  { ticker: "SOMA3.SA", name: "Soma", sector: "Consumer", type: "stock" },
  { ticker: "VIIA3.SA", name: "Via SA", sector: "Consumer", type: "stock" },
  { ticker: "ALPA4.SA", name: "Alpargatas", sector: "Consumer", type: "stock" },
  { ticker: "Y92.SI", name: "Thai Beverage", sector: "Consumer", type: "stock" },
  { ticker: "F34.SI", name: "Wilmar International", sector: "Consumer", type: "stock" },
  { ticker: "U96.SI", name: "Sembcorp Industries", sector: "Industrials", type: "stock" },
  { ticker: "S68.SI", name: "Singapore Exchange", sector: "Finance", type: "stock" },
  { ticker: "M44U.SI", name: "Mapletree Logistics", sector: "Real Estate", type: "stock" },
  { ticker: "N2IU.SI", name: "Mapletree Pan Asia", sector: "Real Estate", type: "stock" },
  { ticker: "ME8U.SI", name: "Mapletree Industrial", sector: "Real Estate", type: "stock" },
  { ticker: "H78.SI", name: "Hongkong Land", sector: "Real Estate", type: "stock" },
  { ticker: "2303.TW", name: "United Microelectronics", sector: "Technology", type: "stock" },
  { ticker: "3034.TW", name: "Novatek Microelectronics", sector: "Technology", type: "stock" },
  { ticker: "2345.TW", name: "Acer", sector: "Technology", type: "stock" },
  { ticker: "2357.TW", name: "ASUSTeK", sector: "Technology", type: "stock" },
  { ticker: "2382.TW", name: "Quanta Computer", sector: "Technology", type: "stock" },
  { ticker: "2353.TW", name: "Acer Inc", sector: "Technology", type: "stock" },
  { ticker: "3231.TW", name: "Wistron", sector: "Technology", type: "stock" },
  { ticker: "2301.TW", name: "Lite-On Technology", sector: "Technology", type: "stock" },
  { ticker: "6505.TW", name: "Formosa Petrochemical", sector: "Energy", type: "stock" },
  { ticker: "2327.TW", name: "Yageo", sector: "Technology", type: "stock" },
  { ticker: "5871.TW", name: "Chailease Holding", sector: "Finance", type: "stock" },
  { ticker: "2884.TW", name: "E.SUN Financial", sector: "Finance", type: "stock" },
  { ticker: "2880.TW", name: "Hua Nan Financial", sector: "Finance", type: "stock" },
  { ticker: "2883.TW", name: "China Development", sector: "Finance", type: "stock" },
  { ticker: "ORBIA.MX", name: "Orbia Advance", sector: "Chemicals", type: "stock" },
  { ticker: "LABB.MX", name: "Genomma Lab", sector: "Healthcare", type: "stock" },
  { ticker: "OMAB.MX", name: "OMA", sector: "Infrastructure", type: "stock" },
  { ticker: "GAPB.MX", name: "Grupo Aeroportuario", sector: "Infrastructure", type: "stock" },
  { ticker: "ASURB.MX", name: "ASUR", sector: "Infrastructure", type: "stock" },
  { ticker: "VOLARA.MX", name: "Volaris", sector: "Transport", type: "stock" },
  { ticker: "PE&OLES.MX", name: "Penoles", sector: "Mining", type: "stock" },
  { ticker: "MEGACPO.MX", name: "Megacable", sector: "Telecom", type: "stock" },
  { ticker: "LACOMER.MX", name: "La Comer", sector: "Consumer", type: "stock" },
  { ticker: "CUERVO.MX", name: "Becle", sector: "Consumer", type: "stock" },
  { ticker: "ANG.JO", name: "AngloGold Ashanti", sector: "Mining", type: "stock" },
  { ticker: "SSW.JO", name: "Sibanye-Stillwater", sector: "Mining", type: "stock" },
  { ticker: "EXX.JO", name: "Exxaro Resources", sector: "Mining", type: "stock" },
  { ticker: "KIO.JO", name: "Kumba Iron Ore", sector: "Mining", type: "stock" },
  { ticker: "TFG.JO", name: "TFG", sector: "Consumer", type: "stock" },
  { ticker: "MRP.JO", name: "Mr Price", sector: "Consumer", type: "stock" },
  { ticker: "WHL.JO", name: "Woolworths Holdings", sector: "Consumer", type: "stock" },
  { ticker: "PIK.JO", name: "Pick n Pay", sector: "Consumer", type: "stock" },
  { ticker: "CLH.JO", name: "City Lodge", sector: "Consumer", type: "stock" },
  { ticker: "TBS.JO", name: "Tiger Brands", sector: "Consumer", type: "stock" },
  { ticker: "AVI.JO", name: "AVI Limited", sector: "Consumer", type: "stock" },
  { ticker: "ITU.JO", name: "Italtile", sector: "Consumer", type: "stock" },
  { ticker: "RBP.JO", name: "Royal Bafokeng", sector: "Mining", type: "stock" },
  { ticker: "OMU.JO", name: "Old Mutual", sector: "Finance", type: "stock" },
  { ticker: "LBH.JO", name: "Liberty Holdings", sector: "Finance", type: "stock" },
  { ticker: "PPH.JO", name: "Pepkor Holdings", sector: "Consumer", type: "stock" },
  { ticker: "RNI.JO", name: "Reinet Investments", sector: "Finance", type: "stock" },
  { ticker: "NRP.JO", name: "NEPI Rockcastle", sector: "Real Estate", type: "stock" },
  { ticker: "2060.SR", name: "National Shipping", sector: "Transport", type: "stock" },
  { ticker: "2170.SR", name: "Almarai", sector: "Consumer", type: "stock" },
  { ticker: "2280.SR", name: "Almarai", sector: "Consumer", type: "stock" },
  { ticker: "3010.SR", name: "Jarir Marketing", sector: "Consumer", type: "stock" },
  { ticker: "4001.SR", name: "Abdullah Al Othaim", sector: "Consumer", type: "stock" },
  { ticker: "4002.SR", name: "Mouwasat Medical", sector: "Healthcare", type: "stock" },
  { ticker: "4003.SR", name: "Extra", sector: "Consumer", type: "stock" },
  { ticker: "4030.SR", name: "Al Babtain", sector: "Industrials", type: "stock" },
  { ticker: "4200.SR", name: "Saudi Airlines Catering", sector: "Consumer", type: "stock" },
  { ticker: "8010.SR", name: "Bupa Arabia", sector: "Healthcare", type: "stock" },
  { ticker: "8020.SR", name: "Malath Insurance", sector: "Finance", type: "stock" },
  { ticker: "8030.SR", name: "Medgulf", sector: "Finance", type: "stock" },
  { ticker: "8040.SR", name: "Al-Ahli Takaful", sector: "Finance", type: "stock" },
  { ticker: "8050.SR", name: "Salama Insurance", sector: "Finance", type: "stock" },
  { ticker: "ALDAR.AE", name: "Aldar Properties", sector: "Real Estate", type: "stock" },
  { ticker: "DAMAC.AE", name: "Damac Properties", sector: "Real Estate", type: "stock" },
  { ticker: "DU.AE", name: "du (EITC)", sector: "Telecom", type: "stock" },
  { ticker: "AIRARABIA.AE", name: "Air Arabia", sector: "Transport", type: "stock" },
  { ticker: "ARAMEX.AE", name: "Aramex", sector: "Logistics", type: "stock" },
  { ticker: "DANA.AE", name: "Dana Gas", sector: "Energy", type: "stock" },
  { ticker: "ABNB", name: "Airbnb", sector: "Consumer", type: "stock" },
  { ticker: "DASH", name: "DoorDash", sector: "Technology", type: "stock" },
  { ticker: "UBER", name: "Uber Technologies", sector: "Technology", type: "stock" },
  { ticker: "LYFT", name: "Lyft", sector: "Technology", type: "stock" },
  { ticker: "DKNG", name: "DraftKings", sector: "Consumer", type: "stock" },
  { ticker: "PENN", name: "Penn Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "RSI", name: "Rush Street Interactive", sector: "Consumer", type: "stock" },
  { ticker: "GENI", name: "Genius Sports", sector: "Technology", type: "stock" },
  { ticker: "STNE", name: "StoneCo", sector: "Finance", type: "stock" },
  { ticker: "PAGS", name: "PagSeguro", sector: "Finance", type: "stock" },
  { ticker: "NU", name: "Nu Holdings", sector: "Finance", type: "stock" },
  { ticker: "XP", name: "XP Inc", sector: "Finance", type: "stock" },
  { ticker: "OPEN", name: "Opendoor", sector: "Real Estate", type: "stock" },
  { ticker: "RDFN", name: "Redfin", sector: "Real Estate", type: "stock" },
  { ticker: "Z", name: "Zillow Group", sector: "Real Estate", type: "stock" },
  { ticker: "COMP", name: "Compass Inc", sector: "Real Estate", type: "stock" },
  { ticker: "CVNA", name: "Carvana", sector: "Consumer", type: "stock" },
  { ticker: "VRM", name: "Vroom", sector: "Consumer", type: "stock" },
  { ticker: "CPNG", name: "Coupang", sector: "Consumer", type: "stock" },
  { ticker: "GLBE", name: "Global-e Online", sector: "Technology", type: "stock" },
  { ticker: "SHOP", name: "Shopify", sector: "Technology", type: "stock" },
  { ticker: "BIGC", name: "BigCommerce", sector: "Technology", type: "stock" },
  { ticker: "VTEX", name: "VTEX", sector: "Technology", type: "stock" },
  { ticker: "MNDY", name: "monday.com", sector: "Technology", type: "stock" },
  { ticker: "CWAN", name: "Clearwater Analytics", sector: "Technology", type: "stock" },
  { ticker: "BRZE", name: "Braze", sector: "Technology", type: "stock" },
  { ticker: "AMPL", name: "Amplitude", sector: "Technology", type: "stock" },
  { ticker: "PCOR", name: "Procore Technologies", sector: "Technology", type: "stock" },
  { ticker: "FROG", name: "JFrog", sector: "Technology", type: "stock" },
  { ticker: "ESTC", name: "Elastic", sector: "Technology", type: "stock" },
  { ticker: "NEWR", name: "New Relic", sector: "Technology", type: "stock" },
  { ticker: "DT", name: "Dynatrace", sector: "Technology", type: "stock" },
  { ticker: "SUMO", name: "Sumo Logic", sector: "Technology", type: "stock" },
  { ticker: "CLDR", name: "Cloudera", sector: "Technology", type: "stock" },
  { ticker: "ZUO", name: "Zuora", sector: "Technology", type: "stock" },
  { ticker: "AVLR", name: "Avalara", sector: "Technology", type: "stock" },
  { ticker: "COUP", name: "Coupa Software", sector: "Technology", type: "stock" },
  { ticker: "JAMF", name: "Jamf Holding", sector: "Technology", type: "stock" },
  { ticker: "SMAR", name: "Smartsheet", sector: "Technology", type: "stock" },
  { ticker: "AYX", name: "Alteryx", sector: "Technology", type: "stock" },
  { ticker: "SPLK", name: "Splunk", sector: "Technology", type: "stock" },
  { ticker: "PLAN", name: "Anaplan", sector: "Technology", type: "stock" },
  { ticker: "GWRE", name: "Guidewire Software", sector: "Technology", type: "stock" },
  { ticker: "BLZE", name: "Backblaze", sector: "Technology", type: "stock" },
  { ticker: "DUOL", name: "Duolingo", sector: "Technology", type: "stock" },
  { ticker: "UDMY", name: "Udemy", sector: "Technology", type: "stock" },
  { ticker: "COUR", name: "Coursera", sector: "Technology", type: "stock" },
  { ticker: "SKIL", name: "Skillful Craftsmen", sector: "Technology", type: "stock" },
  { ticker: "CHGG", name: "Chegg", sector: "Technology", type: "stock" },
  { ticker: "LMND", name: "Lemonade", sector: "Finance", type: "stock" },
  { ticker: "ROOT", name: "Root Inc", sector: "Finance", type: "stock" },
  { ticker: "HIPO", name: "Hippo Holdings", sector: "Finance", type: "stock" },
  { ticker: "KSPI", name: "Kaspi.kz", sector: "Finance", type: "stock" },
  { ticker: "GRAB", name: "Grab Holdings", sector: "Technology", type: "stock" },
  { ticker: "GOTU", name: "Gaotu Techedu", sector: "Technology", type: "stock" },
  { ticker: "TAL", name: "TAL Education", sector: "Technology", type: "stock" },
  { ticker: "EDU", name: "New Oriental", sector: "Technology", type: "stock" },
  { ticker: "VNET", name: "VNET Group", sector: "Technology", type: "stock" },
  { ticker: "KC", name: "Kingsoft Cloud", sector: "Technology", type: "stock" },
  { ticker: "BABA", name: "Alibaba ADR", sector: "Technology", type: "stock" },
  { ticker: "TCOM", name: "Trip.com ADR", sector: "Consumer", type: "stock" },
  { ticker: "MNSO", name: "Miniso Group", sector: "Consumer", type: "stock" },
  { ticker: "YMM", name: "Full Truck Alliance", sector: "Technology", type: "stock" },
  { ticker: "FUTU", name: "Futu Holdings", sector: "Finance", type: "stock" },
  { ticker: "TIGR", name: "UP Fintech", sector: "Finance", type: "stock" },
  { ticker: "FINV", name: "FinVolution", sector: "Finance", type: "stock" },
  { ticker: "LX", name: "LexinFintech", sector: "Finance", type: "stock" },
  { ticker: "QFIN", name: "360 DigiTech", sector: "Finance", type: "stock" },
  { ticker: "DDL", name: "Dingdong Maicai", sector: "Consumer", type: "stock" },
  { ticker: "MF", name: "Missfresh", sector: "Consumer", type: "stock" },
  { ticker: "XNET", name: "Xunlei", sector: "Technology", type: "stock" },
  { ticker: "WB", name: "Weibo", sector: "Technology", type: "stock" },
  { ticker: "IQ", name: "iQIYI", sector: "Technology", type: "stock" },
  { ticker: "HUYA", name: "HUYA", sector: "Technology", type: "stock" },
  { ticker: "DOYU", name: "DouYu", sector: "Technology", type: "stock" },
  { ticker: "TME", name: "Tencent Music", sector: "Technology", type: "stock" },
  { ticker: "YMM", name: "Full Truck Alliance", sector: "Technology", type: "stock" },
  { ticker: "ZTO", name: "ZTO Express", sector: "Logistics", type: "stock" },
  { ticker: "BEST", name: "BEST Inc", sector: "Logistics", type: "stock" },
  { ticker: "GDS", name: "GDS Holdings", sector: "Technology", type: "stock" },
  { ticker: "VIPS", name: "Vipshop", sector: "Consumer", type: "stock" },
  { ticker: "BZUN", name: "Baozun", sector: "Technology", type: "stock" },
  { ticker: "ATHM", name: "Autohome", sector: "Technology", type: "stock" },
  { ticker: "TUYA", name: "Tuya", sector: "Technology", type: "stock" },
  { ticker: "API", name: "Agora", sector: "Technology", type: "stock" },
  { ticker: "RLX", name: "RLX Technology", sector: "Consumer", type: "stock" },
  { ticker: "ZEPP", name: "Zepp Health", sector: "Technology", type: "stock" },
  { ticker: "NIU", name: "Niu Technologies", sector: "Automotive", type: "stock" },
  { ticker: "XPEV", name: "XPeng", sector: "Automotive", type: "stock" },
  { ticker: "LI", name: "Li Auto", sector: "Automotive", type: "stock" },
];
