import { AssetEntry } from "./types";

export const extraEtfs: AssetEntry[] = [
  { ticker: "IEFA", name: "iShares IEFA", sector: "ETF", type: "etf" },
  { ticker: "IEMG", name: "iShares IEMG", sector: "ETF", type: "etf" },
  { ticker: "IWR", name: "iShares IWR", sector: "ETF", type: "etf" },
  { ticker: "IWS", name: "iShares IWS", sector: "ETF", type: "etf" },
  { ticker: "IWN", name: "iShares IWN", sector: "ETF", type: "etf" },
  { ticker: "IWO", name: "iShares IWO", sector: "ETF", type: "etf" },
  { ticker: "IWP", name: "iShares IWP", sector: "ETF", type: "etf" },
  { ticker: "IWC", name: "iShares IWC", sector: "ETF", type: "etf" },
  { ticker: "IDV", name: "iShares IDV", sector: "ETF", type: "etf" },
  { ticker: "IGOV", name: "iShares IGOV", sector: "ETF", type: "etf" },
  { ticker: "IAGG", name: "iShares IAGG", sector: "ETF", type: "etf" },
  { ticker: "IGSB", name: "iShares IGSB", sector: "ETF", type: "etf" },
  { ticker: "IGIB", name: "iShares IGIB", sector: "ETF", type: "etf" },
  { ticker: "IGLB", name: "iShares IGLB", sector: "ETF", type: "etf" },
  { ticker: "IEI", name: "iShares IEI", sector: "ETF", type: "etf" },
  { ticker: "SHY", name: "iShares SHY", sector: "ETF", type: "etf" },
  { ticker: "IEF", name: "iShares IEF", sector: "ETF", type: "etf" },
  { ticker: "TLT", name: "iShares TLT", sector: "ETF", type: "etf" },
  { ticker: "TIP", name: "iShares TIP", sector: "ETF", type: "etf" },
  { ticker: "STIP", name: "iShares STIP", sector: "ETF", type: "etf" },
  { ticker: "MBB", name: "iShares MBB", sector: "ETF", type: "etf" },
  { ticker: "MUB", name: "iShares MUB", sector: "ETF", type: "etf" },
  { ticker: "HYG", name: "iShares HYG", sector: "ETF", type: "etf" },
  { ticker: "LQD", name: "iShares LQD", sector: "ETF", type: "etf" },
  { ticker: "USIG", name: "iShares USIG", sector: "ETF", type: "etf" },
  { ticker: "EMB", name: "iShares EMB", sector: "ETF", type: "etf" },
  { ticker: "LEMB", name: "iShares LEMB", sector: "ETF", type: "etf" },
  { ticker: "AGG", name: "iShares AGG", sector: "ETF", type: "etf" },
  { ticker: "GOVT", name: "iShares GOVT", sector: "ETF", type: "etf" },
  { ticker: "FLOT", name: "iShares FLOT", sector: "ETF", type: "etf" },
  { ticker: "NEAR", name: "iShares NEAR", sector: "ETF", type: "etf" },
  { ticker: "ICSH", name: "iShares ICSH", sector: "ETF", type: "etf" },
  { ticker: "SHV", name: "iShares SHV", sector: "ETF", type: "etf" },
  { ticker: "SGOV", name: "iShares SGOV", sector: "ETF", type: "etf" },
  { ticker: "TFLO", name: "iShares TFLO", sector: "ETF", type: "etf" },
  { ticker: "COMT", name: "iShares COMT", sector: "ETF", type: "etf" },
  { ticker: "GSG", name: "iShares GSG", sector: "ETF", type: "etf" },
  { ticker: "PICK", name: "iShares PICK", sector: "ETF", type: "etf" },
  { ticker: "RING", name: "iShares RING", sector: "ETF", type: "etf" },
  { ticker: "SLVP", name: "iShares SLVP", sector: "ETF", type: "etf" },
  { ticker: "IYW", name: "iShares IYW", sector: "ETF", type: "etf" },
  { ticker: "IYH", name: "iShares IYH", sector: "ETF", type: "etf" },
  { ticker: "IYC", name: "iShares IYC", sector: "ETF", type: "etf" },
  { ticker: "IYF", name: "iShares IYF", sector: "ETF", type: "etf" },
  { ticker: "IYJ", name: "iShares IYJ", sector: "ETF", type: "etf" },
  { ticker: "IYR", name: "iShares IYR", sector: "ETF", type: "etf" },
  { ticker: "IYE", name: "iShares IYE", sector: "ETF", type: "etf" },
  { ticker: "IYM", name: "iShares IYM", sector: "ETF", type: "etf" },
  { ticker: "IYK", name: "iShares IYK", sector: "ETF", type: "etf" },
  { ticker: "IYG", name: "iShares IYG", sector: "ETF", type: "etf" },
  { ticker: "IYZ", name: "iShares IYZ", sector: "ETF", type: "etf" },
  { ticker: "IHI", name: "iShares IHI", sector: "ETF", type: "etf" },
  { ticker: "IHF", name: "iShares IHF", sector: "ETF", type: "etf" },
  { ticker: "IHE", name: "iShares IHE", sector: "ETF", type: "etf" },
  { ticker: "IBB", name: "iShares IBB", sector: "ETF", type: "etf" },
  { ticker: "IGV", name: "iShares IGV", sector: "ETF", type: "etf" },
  { ticker: "IGM", name: "iShares IGM", sector: "ETF", type: "etf" },
  { ticker: "IGN", name: "iShares IGN", sector: "ETF", type: "etf" },
  { ticker: "ITA", name: "iShares ITA", sector: "ETF", type: "etf" },
  { ticker: "IEO", name: "iShares IEO", sector: "ETF", type: "etf" },
  { ticker: "ITB", name: "iShares ITB", sector: "ETF", type: "etf" },
  { ticker: "IEZ", name: "iShares IEZ", sector: "ETF", type: "etf" },
  { ticker: "SOXX", name: "iShares SOXX", sector: "ETF", type: "etf" },
  { ticker: "XSW", name: "iShares XSW", sector: "ETF", type: "etf" },
  { ticker: "SUSA", name: "iShares SUSA", sector: "ETF", type: "etf" },
  { ticker: "ESGU", name: "iShares ESGU", sector: "ETF", type: "etf" },
  { ticker: "ESGD", name: "iShares ESGD", sector: "ETF", type: "etf" },
  { ticker: "ESGE", name: "iShares ESGE", sector: "ETF", type: "etf" },
  { ticker: "ICLN", name: "iShares ICLN", sector: "ETF", type: "etf" },
  { ticker: "IFRA", name: "iShares IFRA", sector: "ETF", type: "etf" },
  { ticker: "IQLT", name: "iShares IQLT", sector: "ETF", type: "etf" },
  { ticker: "QUAL", name: "iShares QUAL", sector: "ETF", type: "etf" },
  { ticker: "SIZE", name: "iShares SIZE", sector: "ETF", type: "etf" },
  { ticker: "MTUM", name: "iShares MTUM", sector: "ETF", type: "etf" },
  { ticker: "VLUE", name: "iShares VLUE", sector: "ETF", type: "etf" },
  { ticker: "USMV", name: "iShares USMV", sector: "ETF", type: "etf" },
  { ticker: "EUFN", name: "iShares EUFN", sector: "ETF", type: "etf" },
  { ticker: "EDEN", name: "iShares EDEN", sector: "ETF", type: "etf" },
  { ticker: "EWA", name: "iShares EWA", sector: "ETF", type: "etf" },
  { ticker: "EWC", name: "iShares EWC", sector: "ETF", type: "etf" },
  { ticker: "EWG", name: "iShares EWG", sector: "ETF", type: "etf" },
  { ticker: "EWH", name: "iShares EWH", sector: "ETF", type: "etf" },
  { ticker: "EWI", name: "iShares EWI", sector: "ETF", type: "etf" },
  { ticker: "EWJ", name: "iShares EWJ", sector: "ETF", type: "etf" },
  { ticker: "EWK", name: "iShares EWK", sector: "ETF", type: "etf" },
  { ticker: "EWL", name: "iShares EWL", sector: "ETF", type: "etf" },
  { ticker: "EWM", name: "iShares EWM", sector: "ETF", type: "etf" },
  { ticker: "EWN", name: "iShares EWN", sector: "ETF", type: "etf" },
  { ticker: "EWO", name: "iShares EWO", sector: "ETF", type: "etf" },
  { ticker: "EWP", name: "iShares EWP", sector: "ETF", type: "etf" },
  { ticker: "EWQ", name: "iShares EWQ", sector: "ETF", type: "etf" },
  { ticker: "EWS", name: "iShares EWS", sector: "ETF", type: "etf" },
  { ticker: "EWT", name: "iShares EWT", sector: "ETF", type: "etf" },
  { ticker: "EWU", name: "iShares EWU", sector: "ETF", type: "etf" },
  { ticker: "EWW", name: "iShares EWW", sector: "ETF", type: "etf" },
  { ticker: "EWY", name: "iShares EWY", sector: "ETF", type: "etf" },
  { ticker: "EWZ", name: "iShares EWZ", sector: "ETF", type: "etf" },
  { ticker: "EIDO", name: "iShares EIDO", sector: "ETF", type: "etf" },
  { ticker: "EPOL", name: "iShares EPOL", sector: "ETF", type: "etf" },
  { ticker: "ECH", name: "iShares ECH", sector: "ETF", type: "etf" },
  { ticker: "ENZL", name: "iShares ENZL", sector: "ETF", type: "etf" },
  { ticker: "EPP", name: "iShares EPP", sector: "ETF", type: "etf" },
  { ticker: "AAXJ", name: "iShares AAXJ", sector: "ETF", type: "etf" },
  { ticker: "MCHI", name: "iShares MCHI", sector: "ETF", type: "etf" },
  { ticker: "INDA", name: "iShares INDA", sector: "ETF", type: "etf" },
  { ticker: "KSA", name: "iShares KSA", sector: "ETF", type: "etf" },
  { ticker: "UAE", name: "iShares UAE", sector: "ETF", type: "etf" },
  { ticker: "QAT", name: "iShares QAT", sector: "ETF", type: "etf" },
  { ticker: "EFAV", name: "iShares EFAV", sector: "ETF", type: "etf" },
  { ticker: "ACWV", name: "iShares ACWV", sector: "ETF", type: "etf" },
  { ticker: "ACWI", name: "iShares ACWI", sector: "ETF", type: "etf" },
  { ticker: "ACWX", name: "iShares ACWX", sector: "ETF", type: "etf" },
  { ticker: "URTH", name: "iShares URTH", sector: "ETF", type: "etf" },
  { ticker: "WFH", name: "iShares WFH", sector: "ETF", type: "etf" },
  { ticker: "IBUY", name: "iShares IBUY", sector: "ETF", type: "etf" },
  { ticker: "IRBO", name: "iShares IRBO", sector: "ETF", type: "etf" },
  { ticker: "IDRV", name: "iShares IDRV", sector: "ETF", type: "etf" },
  { ticker: "IXN", name: "iShares IXN", sector: "ETF", type: "etf" },
  { ticker: "IXJ", name: "iShares IXJ", sector: "ETF", type: "etf" },
  { ticker: "IXC", name: "iShares IXC", sector: "ETF", type: "etf" },
  { ticker: "IXP", name: "iShares IXP", sector: "ETF", type: "etf" },
  { ticker: "IXG", name: "iShares IXG", sector: "ETF", type: "etf" },
  { ticker: "HEWG", name: "iShares HEWG", sector: "ETF", type: "etf" },
  { ticker: "HEWJ", name: "iShares HEWJ", sector: "ETF", type: "etf" },
  { ticker: "HEWI", name: "iShares HEWI", sector: "ETF", type: "etf" },
  { ticker: "HEZU", name: "iShares HEZU", sector: "ETF", type: "etf" },
  { ticker: "HDV", name: "iShares HDV", sector: "ETF", type: "etf" },
  { ticker: "DVY", name: "iShares DVY", sector: "ETF", type: "etf" },
  { ticker: "DGRO", name: "iShares DGRO", sector: "ETF", type: "etf" },
  { ticker: "DIVB", name: "iShares DIVB", sector: "ETF", type: "etf" },
  { ticker: "PFF", name: "iShares PFF", sector: "ETF", type: "etf" },
  { ticker: "XYLD", name: "iShares XYLD", sector: "ETF", type: "etf" },
  { ticker: "QYLD", name: "iShares QYLD", sector: "ETF", type: "etf" },
  { ticker: "VTI", name: "Vanguard VTI", sector: "ETF", type: "etf" },
  { ticker: "VOO", name: "Vanguard VOO", sector: "ETF", type: "etf" },
  { ticker: "VUG", name: "Vanguard VUG", sector: "ETF", type: "etf" },
  { ticker: "VTV", name: "Vanguard VTV", sector: "ETF", type: "etf" },
  { ticker: "VB", name: "Vanguard VB", sector: "ETF", type: "etf" },
  { ticker: "VBK", name: "Vanguard VBK", sector: "ETF", type: "etf" },
  { ticker: "VBR", name: "Vanguard VBR", sector: "ETF", type: "etf" },
  { ticker: "VO", name: "Vanguard VO", sector: "ETF", type: "etf" },
  { ticker: "VOE", name: "Vanguard VOE", sector: "ETF", type: "etf" },
  { ticker: "VOT", name: "Vanguard VOT", sector: "ETF", type: "etf" },
  { ticker: "VIG", name: "Vanguard VIG", sector: "ETF", type: "etf" },
  { ticker: "VYM", name: "Vanguard VYM", sector: "ETF", type: "etf" },
  { ticker: "VYMI", name: "Vanguard VYMI", sector: "ETF", type: "etf" },
  { ticker: "VGK", name: "Vanguard VGK", sector: "ETF", type: "etf" },
  { ticker: "VPL", name: "Vanguard VPL", sector: "ETF", type: "etf" },
  { ticker: "VWO", name: "Vanguard VWO", sector: "ETF", type: "etf" },
  { ticker: "VXUS", name: "Vanguard VXUS", sector: "ETF", type: "etf" },
  { ticker: "VEA", name: "Vanguard VEA", sector: "ETF", type: "etf" },
  { ticker: "VSS", name: "Vanguard VSS", sector: "ETF", type: "etf" },
  { ticker: "VT", name: "Vanguard VT", sector: "ETF", type: "etf" },
  { ticker: "VNQ", name: "Vanguard VNQ", sector: "ETF", type: "etf" },
  { ticker: "VNQI", name: "Vanguard VNQI", sector: "ETF", type: "etf" },
  { ticker: "VCIT", name: "Vanguard VCIT", sector: "ETF", type: "etf" },
  { ticker: "VCSH", name: "Vanguard VCSH", sector: "ETF", type: "etf" },
  { ticker: "VCLT", name: "Vanguard VCLT", sector: "ETF", type: "etf" },
  { ticker: "VGIT", name: "Vanguard VGIT", sector: "ETF", type: "etf" },
  { ticker: "VGSH", name: "Vanguard VGSH", sector: "ETF", type: "etf" },
  { ticker: "VGLT", name: "Vanguard VGLT", sector: "ETF", type: "etf" },
  { ticker: "BND", name: "Vanguard BND", sector: "ETF", type: "etf" },
  { ticker: "BNDX", name: "Vanguard BNDX", sector: "ETF", type: "etf" },
  { ticker: "BNDW", name: "Vanguard BNDW", sector: "ETF", type: "etf" },
  { ticker: "BSV", name: "Vanguard BSV", sector: "ETF", type: "etf" },
  { ticker: "BIV", name: "Vanguard BIV", sector: "ETF", type: "etf" },
  { ticker: "BLV", name: "Vanguard BLV", sector: "ETF", type: "etf" },
  { ticker: "VTIP", name: "Vanguard VTIP", sector: "ETF", type: "etf" },
  { ticker: "VMBS", name: "Vanguard VMBS", sector: "ETF", type: "etf" },
  { ticker: "VTEB", name: "Vanguard VTEB", sector: "ETF", type: "etf" },
  { ticker: "EDV", name: "Vanguard EDV", sector: "ETF", type: "etf" },
  { ticker: "VDE", name: "Vanguard VDE", sector: "ETF", type: "etf" },
  { ticker: "VFH", name: "Vanguard VFH", sector: "ETF", type: "etf" },
  { ticker: "VGT", name: "Vanguard VGT", sector: "ETF", type: "etf" },
  { ticker: "VHT", name: "Vanguard VHT", sector: "ETF", type: "etf" },
  { ticker: "VIS", name: "Vanguard VIS", sector: "ETF", type: "etf" },
  { ticker: "VAW", name: "Vanguard VAW", sector: "ETF", type: "etf" },
  { ticker: "VCR", name: "Vanguard VCR", sector: "ETF", type: "etf" },
  { ticker: "VDC", name: "Vanguard VDC", sector: "ETF", type: "etf" },
  { ticker: "VOX", name: "Vanguard VOX", sector: "ETF", type: "etf" },
  { ticker: "VPU", name: "Vanguard VPU", sector: "ETF", type: "etf" },
  { ticker: "VONE", name: "Vanguard VONE", sector: "ETF", type: "etf" },
  { ticker: "VTWO", name: "Vanguard VTWO", sector: "ETF", type: "etf" },
  { ticker: "VONG", name: "Vanguard VONG", sector: "ETF", type: "etf" },
  { ticker: "VONV", name: "Vanguard VONV", sector: "ETF", type: "etf" },
  { ticker: "VTHR", name: "Vanguard VTHR", sector: "ETF", type: "etf" },
  { ticker: "VXF", name: "Vanguard VXF", sector: "ETF", type: "etf" },
  { ticker: "MGK", name: "Vanguard MGK", sector: "ETF", type: "etf" },
  { ticker: "MGV", name: "Vanguard MGV", sector: "ETF", type: "etf" },
  { ticker: "VOOG", name: "Vanguard VOOG", sector: "ETF", type: "etf" },
  { ticker: "VOOV", name: "Vanguard VOOV", sector: "ETF", type: "etf" },
  { ticker: "IVOG", name: "Vanguard IVOG", sector: "ETF", type: "etf" },
  { ticker: "IVOV", name: "Vanguard IVOV", sector: "ETF", type: "etf" },
  { ticker: "VTWG", name: "Vanguard VTWG", sector: "ETF", type: "etf" },
  { ticker: "VTWV", name: "Vanguard VTWV", sector: "ETF", type: "etf" },
  { ticker: "SPY", name: "SPDR SPY", sector: "ETF", type: "etf" },
  { ticker: "SPYD", name: "SPDR SPYD", sector: "ETF", type: "etf" },
  { ticker: "SPDW", name: "SPDR SPDW", sector: "ETF", type: "etf" },
  { ticker: "SPEM", name: "SPDR SPEM", sector: "ETF", type: "etf" },
  { ticker: "SPTL", name: "SPDR SPTL", sector: "ETF", type: "etf" },
  { ticker: "SPTS", name: "SPDR SPTS", sector: "ETF", type: "etf" },
  { ticker: "SPIB", name: "SPDR SPIB", sector: "ETF", type: "etf" },
  { ticker: "SPSB", name: "SPDR SPSB", sector: "ETF", type: "etf" },
  { ticker: "SPLB", name: "SPDR SPLB", sector: "ETF", type: "etf" },
  { ticker: "SPAB", name: "SPDR SPAB", sector: "ETF", type: "etf" },
  { ticker: "SPHY", name: "SPDR SPHY", sector: "ETF", type: "etf" },
  { ticker: "SPIP", name: "SPDR SPIP", sector: "ETF", type: "etf" },
  { ticker: "SPTM", name: "SPDR SPTM", sector: "ETF", type: "etf" },
  { ticker: "SPLG", name: "SPDR SPLG", sector: "ETF", type: "etf" },
  { ticker: "SPYG", name: "SPDR SPYG", sector: "ETF", type: "etf" },
  { ticker: "SPYV", name: "SPDR SPYV", sector: "ETF", type: "etf" },
  { ticker: "SPMD", name: "SPDR SPMD", sector: "ETF", type: "etf" },
  { ticker: "SPMB", name: "SPDR SPMB", sector: "ETF", type: "etf" },
  { ticker: "SPSM", name: "SPDR SPSM", sector: "ETF", type: "etf" },
  { ticker: "XLE", name: "SPDR XLE", sector: "ETF", type: "etf" },
  { ticker: "XLF", name: "SPDR XLF", sector: "ETF", type: "etf" },
  { ticker: "XLK", name: "SPDR XLK", sector: "ETF", type: "etf" },
  { ticker: "XLV", name: "SPDR XLV", sector: "ETF", type: "etf" },
  { ticker: "XLI", name: "SPDR XLI", sector: "ETF", type: "etf" },
  { ticker: "XLB", name: "SPDR XLB", sector: "ETF", type: "etf" },
  { ticker: "XLY", name: "SPDR XLY", sector: "ETF", type: "etf" },
  { ticker: "XLP", name: "SPDR XLP", sector: "ETF", type: "etf" },
  { ticker: "XLU", name: "SPDR XLU", sector: "ETF", type: "etf" },
  { ticker: "XLRE", name: "SPDR XLRE", sector: "ETF", type: "etf" },
  { ticker: "XLC", name: "SPDR XLC", sector: "ETF", type: "etf" },
  { ticker: "XBI", name: "SPDR XBI", sector: "ETF", type: "etf" },
  { ticker: "XHE", name: "SPDR XHE", sector: "ETF", type: "etf" },
  { ticker: "XHS", name: "SPDR XHS", sector: "ETF", type: "etf" },
  { ticker: "XHB", name: "SPDR XHB", sector: "ETF", type: "etf" },
  { ticker: "XRT", name: "SPDR XRT", sector: "ETF", type: "etf" },
  { ticker: "XME", name: "SPDR XME", sector: "ETF", type: "etf" },
  { ticker: "XAR", name: "SPDR XAR", sector: "ETF", type: "etf" },
  { ticker: "XTN", name: "SPDR XTN", sector: "ETF", type: "etf" },
  { ticker: "XNTK", name: "SPDR XNTK", sector: "ETF", type: "etf" },
  { ticker: "XSD", name: "SPDR XSD", sector: "ETF", type: "etf" },
  { ticker: "XWEB", name: "SPDR XWEB", sector: "ETF", type: "etf" },
  { ticker: "KBE", name: "SPDR KBE", sector: "ETF", type: "etf" },
  { ticker: "KRE", name: "SPDR KRE", sector: "ETF", type: "etf" },
  { ticker: "KCE", name: "SPDR KCE", sector: "ETF", type: "etf" },
  { ticker: "KIE", name: "SPDR KIE", sector: "ETF", type: "etf" },
  { ticker: "KBWB", name: "SPDR KBWB", sector: "ETF", type: "etf" },
  { ticker: "KBWP", name: "SPDR KBWP", sector: "ETF", type: "etf" },
  { ticker: "GLD", name: "SPDR GLD", sector: "ETF", type: "etf" },
  { ticker: "GLDM", name: "SPDR GLDM", sector: "ETF", type: "etf" },
  { ticker: "GDMA", name: "SPDR GDMA", sector: "ETF", type: "etf" },
  { ticker: "LAB", name: "SPDR LAB", sector: "ETF", type: "etf" },
  { ticker: "RWR", name: "SPDR RWR", sector: "ETF", type: "etf" },
  { ticker: "RSPM", name: "SPDR RSPM", sector: "ETF", type: "etf" },
  { ticker: "MDY", name: "SPDR MDY", sector: "ETF", type: "etf" },
  { ticker: "MDYG", name: "SPDR MDYG", sector: "ETF", type: "etf" },
  { ticker: "MDYV", name: "SPDR MDYV", sector: "ETF", type: "etf" },
  { ticker: "SLY", name: "SPDR SLY", sector: "ETF", type: "etf" },
  { ticker: "SLYG", name: "SPDR SLYG", sector: "ETF", type: "etf" },
  { ticker: "SLYV", name: "SPDR SLYV", sector: "ETF", type: "etf" },
  { ticker: "QQQ", name: "Invesco QQQ", sector: "ETF", type: "etf" },
  { ticker: "QQQM", name: "Invesco QQQM", sector: "ETF", type: "etf" },
  { ticker: "RSP", name: "Invesco RSP", sector: "ETF", type: "etf" },
  { ticker: "SPLV", name: "Invesco SPLV", sector: "ETF", type: "etf" },
  { ticker: "SPHD", name: "Invesco SPHD", sector: "ETF", type: "etf" },
  { ticker: "SPHB", name: "Invesco SPHB", sector: "ETF", type: "etf" },
  { ticker: "PRFZ", name: "Invesco PRFZ", sector: "ETF", type: "etf" },
  { ticker: "PBW", name: "Invesco PBW", sector: "ETF", type: "etf" },
  { ticker: "PHO", name: "Invesco PHO", sector: "ETF", type: "etf" },
  { ticker: "PNQI", name: "Invesco PNQI", sector: "ETF", type: "etf" },
  { ticker: "PKW", name: "Invesco PKW", sector: "ETF", type: "etf" },
  { ticker: "PDBC", name: "Invesco PDBC", sector: "ETF", type: "etf" },
  { ticker: "DBA", name: "Invesco DBA", sector: "ETF", type: "etf" },
  { ticker: "DBB", name: "Invesco DBB", sector: "ETF", type: "etf" },
  { ticker: "DBC", name: "Invesco DBC", sector: "ETF", type: "etf" },
  { ticker: "DBE", name: "Invesco DBE", sector: "ETF", type: "etf" },
  { ticker: "DBO", name: "Invesco DBO", sector: "ETF", type: "etf" },
  { ticker: "DBP", name: "Invesco DBP", sector: "ETF", type: "etf" },
  { ticker: "DBS", name: "Invesco DBS", sector: "ETF", type: "etf" },
  { ticker: "KBWD", name: "Invesco KBWD", sector: "ETF", type: "etf" },
  { ticker: "KBWY", name: "Invesco KBWY", sector: "ETF", type: "etf" },
  { ticker: "KBWB2", name: "Invesco KBWB2", sector: "ETF", type: "etf" },
  { ticker: "PGX", name: "Invesco PGX", sector: "ETF", type: "etf" },
  { ticker: "VRP", name: "Invesco VRP", sector: "ETF", type: "etf" },
  { ticker: "BKLN", name: "Invesco BKLN", sector: "ETF", type: "etf" },
  { ticker: "PCEF", name: "Invesco PCEF", sector: "ETF", type: "etf" },
  { ticker: "CSD", name: "Invesco CSD", sector: "ETF", type: "etf" },
  { ticker: "PSP", name: "Invesco PSP", sector: "ETF", type: "etf" },
  { ticker: "RCD", name: "Invesco RCD", sector: "ETF", type: "etf" },
  { ticker: "RTM", name: "Invesco RTM", sector: "ETF", type: "etf" },
  { ticker: "RYT", name: "Invesco RYT", sector: "ETF", type: "etf" },
  { ticker: "RYH", name: "Invesco RYH", sector: "ETF", type: "etf" },
  { ticker: "RYF", name: "Invesco RYF", sector: "ETF", type: "etf" },
  { ticker: "RYE", name: "Invesco RYE", sector: "ETF", type: "etf" },
  { ticker: "RGI", name: "Invesco RGI", sector: "ETF", type: "etf" },
  { ticker: "PWV", name: "Invesco PWV", sector: "ETF", type: "etf" },
  { ticker: "PRF", name: "Invesco PRF", sector: "ETF", type: "etf" },
  { ticker: "PID", name: "Invesco PID", sector: "ETF", type: "etf" },
  { ticker: "PFM", name: "Invesco PFM", sector: "ETF", type: "etf" },
  { ticker: "PKG2", name: "Invesco PKG2", sector: "ETF", type: "etf" },
  { ticker: "PEY", name: "Invesco PEY", sector: "ETF", type: "etf" },
  { ticker: "PEZ", name: "Invesco PEZ", sector: "ETF", type: "etf" },
  { ticker: "PSJ", name: "Invesco PSJ", sector: "ETF", type: "etf" },
  { ticker: "PSI", name: "Invesco PSI", sector: "ETF", type: "etf" },
  { ticker: "PTF", name: "Invesco PTF", sector: "ETF", type: "etf" },
  { ticker: "PTH", name: "Invesco PTH", sector: "ETF", type: "etf" },
  { ticker: "PXI", name: "Invesco PXI", sector: "ETF", type: "etf" },
  { ticker: "PYZ", name: "Invesco PYZ", sector: "ETF", type: "etf" },
  { ticker: "EWS2", name: "Invesco EWS2", sector: "ETF", type: "etf" },
  { ticker: "EELV", name: "Invesco EELV", sector: "ETF", type: "etf" },
  { ticker: "EEMA", name: "Invesco EEMA", sector: "ETF", type: "etf" },
  { ticker: "EEB", name: "Invesco EEB", sector: "ETF", type: "etf" },
  { ticker: "PXH", name: "Invesco PXH", sector: "ETF", type: "etf" },
  { ticker: "IDLV", name: "Invesco IDLV", sector: "ETF", type: "etf" },
  { ticker: "ACWV2", name: "Invesco ACWV2", sector: "ETF", type: "etf" },
  { ticker: "PBJ", name: "Invesco PBJ", sector: "ETF", type: "etf" },
  { ticker: "PBE", name: "Invesco PBE", sector: "ETF", type: "etf" },
  { ticker: "PBS", name: "Invesco PBS", sector: "ETF", type: "etf" },
  { ticker: "PPA", name: "Invesco PPA", sector: "ETF", type: "etf" },
  { ticker: "PSCE", name: "Invesco PSCE", sector: "ETF", type: "etf" },
  { ticker: "PSCI", name: "Invesco PSCI", sector: "ETF", type: "etf" },
  { ticker: "PSCT", name: "Invesco PSCT", sector: "ETF", type: "etf" },
  { ticker: "PSCM", name: "Invesco PSCM", sector: "ETF", type: "etf" },
  { ticker: "SCHB", name: "Schwab SCHB", sector: "ETF", type: "etf" },
  { ticker: "SCHX", name: "Schwab SCHX", sector: "ETF", type: "etf" },
  { ticker: "SCHA", name: "Schwab SCHA", sector: "ETF", type: "etf" },
  { ticker: "SCHG", name: "Schwab SCHG", sector: "ETF", type: "etf" },
  { ticker: "SCHV", name: "Schwab SCHV", sector: "ETF", type: "etf" },
  { ticker: "SCHD", name: "Schwab SCHD", sector: "ETF", type: "etf" },
  { ticker: "SCHF", name: "Schwab SCHF", sector: "ETF", type: "etf" },
  { ticker: "SCHE", name: "Schwab SCHE", sector: "ETF", type: "etf" },
  { ticker: "SCHZ", name: "Schwab SCHZ", sector: "ETF", type: "etf" },
  { ticker: "SCHJ", name: "Schwab SCHJ", sector: "ETF", type: "etf" },
  { ticker: "SCHO", name: "Schwab SCHO", sector: "ETF", type: "etf" },
  { ticker: "SCHR", name: "Schwab SCHR", sector: "ETF", type: "etf" },
  { ticker: "SCHQ", name: "Schwab SCHQ", sector: "ETF", type: "etf" },
  { ticker: "SCHP", name: "Schwab SCHP", sector: "ETF", type: "etf" },
  { ticker: "SCHM", name: "Schwab SCHM", sector: "ETF", type: "etf" },
  { ticker: "SWGSX", name: "Schwab SWGSX", sector: "ETF", type: "etf" },
  { ticker: "FNDA", name: "Schwab FNDA", sector: "ETF", type: "etf" },
  { ticker: "FNDB", name: "Schwab FNDB", sector: "ETF", type: "etf" },
  { ticker: "FNDC", name: "Schwab FNDC", sector: "ETF", type: "etf" },
  { ticker: "FNDE", name: "Schwab FNDE", sector: "ETF", type: "etf" },
  { ticker: "FNDF", name: "Schwab FNDF", sector: "ETF", type: "etf" },
  { ticker: "FNDX", name: "Schwab FNDX", sector: "ETF", type: "etf" },
  { ticker: "ARKK", name: "ARK ARKK", sector: "ETF", type: "etf" },
  { ticker: "ARKW", name: "ARK ARKW", sector: "ETF", type: "etf" },
  { ticker: "ARKG", name: "ARK ARKG", sector: "ETF", type: "etf" },
  { ticker: "ARKF", name: "ARK ARKF", sector: "ETF", type: "etf" },
  { ticker: "ARKQ", name: "ARK ARKQ", sector: "ETF", type: "etf" },
  { ticker: "ARKX", name: "ARK ARKX", sector: "ETF", type: "etf" },
  { ticker: "IZRL", name: "ARK IZRL", sector: "ETF", type: "etf" },
  { ticker: "PRNT", name: "ARK PRNT", sector: "ETF", type: "etf" },
  { ticker: "CTRU", name: "ARK CTRU", sector: "ETF", type: "etf" },
  { ticker: "GDX", name: "VanEck GDX", sector: "ETF", type: "etf" },
  { ticker: "GDXJ", name: "VanEck GDXJ", sector: "ETF", type: "etf" },
  { ticker: "MOTI", name: "VanEck MOTI", sector: "ETF", type: "etf" },
  { ticker: "MOAT", name: "VanEck MOAT", sector: "ETF", type: "etf" },
  { ticker: "SMOG", name: "VanEck SMOG", sector: "ETF", type: "etf" },
  { ticker: "REMX", name: "VanEck REMX", sector: "ETF", type: "etf" },
  { ticker: "ESPO", name: "VanEck ESPO", sector: "ETF", type: "etf" },
  { ticker: "CLOU", name: "VanEck CLOU", sector: "ETF", type: "etf" },
  { ticker: "SKYY", name: "VanEck SKYY", sector: "ETF", type: "etf" },
  { ticker: "PPH", name: "VanEck PPH", sector: "ETF", type: "etf" },
  { ticker: "XBI2", name: "VanEck XBI2", sector: "ETF", type: "etf" },
  { ticker: "ANGL", name: "VanEck ANGL", sector: "ETF", type: "etf" },
  { ticker: "HYD", name: "VanEck HYD", sector: "ETF", type: "etf" },
  { ticker: "HYEM", name: "VanEck HYEM", sector: "ETF", type: "etf" },
  { ticker: "BNDW2", name: "VanEck BNDW2", sector: "ETF", type: "etf" },
  { ticker: "EMLC", name: "VanEck EMLC", sector: "ETF", type: "etf" },
  { ticker: "IGOV2", name: "VanEck IGOV2", sector: "ETF", type: "etf" },
  { ticker: "FLRN", name: "VanEck FLRN", sector: "ETF", type: "etf" },
  { ticker: "OPER", name: "VanEck OPER", sector: "ETF", type: "etf" },
  { ticker: "CNBS", name: "VanEck CNBS", sector: "ETF", type: "etf" },
  { ticker: "MJ", name: "VanEck MJ", sector: "ETF", type: "etf" },
  { ticker: "DLN", name: "WisdomTree DLN", sector: "ETF", type: "etf" },
  { ticker: "DON", name: "WisdomTree DON", sector: "ETF", type: "etf" },
  { ticker: "DES", name: "WisdomTree DES", sector: "ETF", type: "etf" },
  { ticker: "DLS", name: "WisdomTree DLS", sector: "ETF", type: "etf" },
  { ticker: "DGS", name: "WisdomTree DGS", sector: "ETF", type: "etf" },
  { ticker: "DFJ", name: "WisdomTree DFJ", sector: "ETF", type: "etf" },
  { ticker: "DXJ", name: "WisdomTree DXJ", sector: "ETF", type: "etf" },
  { ticker: "WTV", name: "WisdomTree WTV", sector: "ETF", type: "etf" },
  { ticker: "DGRW", name: "WisdomTree DGRW", sector: "ETF", type: "etf" },
  { ticker: "DGRS", name: "WisdomTree DGRS", sector: "ETF", type: "etf" },
  { ticker: "DTD", name: "WisdomTree DTD", sector: "ETF", type: "etf" },
  { ticker: "WTMF", name: "WisdomTree WTMF", sector: "ETF", type: "etf" },
  { ticker: "HYZD", name: "WisdomTree HYZD", sector: "ETF", type: "etf" },
  { ticker: "HYND", name: "WisdomTree HYND", sector: "ETF", type: "etf" },
  { ticker: "AGZD", name: "WisdomTree AGZD", sector: "ETF", type: "etf" },
  { ticker: "GCC", name: "WisdomTree GCC", sector: "ETF", type: "etf" },
  { ticker: "WDTI", name: "WisdomTree WDTI", sector: "ETF", type: "etf" },
  { ticker: "EPI", name: "WisdomTree EPI", sector: "ETF", type: "etf" },
  { ticker: "EMCB", name: "WisdomTree EMCB", sector: "ETF", type: "etf" },
  { ticker: "CEW", name: "WisdomTree CEW", sector: "ETF", type: "etf" },
  { ticker: "ICN", name: "WisdomTree ICN", sector: "ETF", type: "etf" },
  { ticker: "BZF", name: "WisdomTree BZF", sector: "ETF", type: "etf" },
  { ticker: "CYB", name: "WisdomTree CYB", sector: "ETF", type: "etf" },
  { ticker: "CCX", name: "WisdomTree CCX", sector: "ETF", type: "etf" },
  { ticker: "FDN", name: "First Trust FDN", sector: "ETF", type: "etf" },
  { ticker: "FXH", name: "First Trust FXH", sector: "ETF", type: "etf" },
  { ticker: "FXR", name: "First Trust FXR", sector: "ETF", type: "etf" },
  { ticker: "FXL", name: "First Trust FXL", sector: "ETF", type: "etf" },
  { ticker: "FXD", name: "First Trust FXD", sector: "ETF", type: "etf" },
  { ticker: "FXU", name: "First Trust FXU", sector: "ETF", type: "etf" },
  { ticker: "FXG", name: "First Trust FXG", sector: "ETF", type: "etf" },
  { ticker: "FXN", name: "First Trust FXN", sector: "ETF", type: "etf" },
  { ticker: "FXZ", name: "First Trust FXZ", sector: "ETF", type: "etf" },
  { ticker: "FXO", name: "First Trust FXO", sector: "ETF", type: "etf" },
  { ticker: "FTHI", name: "First Trust FTHI", sector: "ETF", type: "etf" },
  { ticker: "FTQI", name: "First Trust FTQI", sector: "ETF", type: "etf" },
  { ticker: "SKYY2", name: "First Trust SKYY2", sector: "ETF", type: "etf" },
  { ticker: "LMBS", name: "First Trust LMBS", sector: "ETF", type: "etf" },
  { ticker: "FPE", name: "First Trust FPE", sector: "ETF", type: "etf" },
  { ticker: "HYLS", name: "First Trust HYLS", sector: "ETF", type: "etf" },
  { ticker: "FTGC", name: "First Trust FTGC", sector: "ETF", type: "etf" },
  { ticker: "FTSL", name: "First Trust FTSL", sector: "ETF", type: "etf" },
  { ticker: "FCVT", name: "First Trust FCVT", sector: "ETF", type: "etf" },
  { ticker: "FV", name: "First Trust FV", sector: "ETF", type: "etf" },
  { ticker: "FDNI", name: "First Trust FDNI", sector: "ETF", type: "etf" },
  { ticker: "IPAY", name: "First Trust IPAY", sector: "ETF", type: "etf" },
  { ticker: "FINX", name: "First Trust FINX", sector: "ETF", type: "etf" },
  { ticker: "LEGR", name: "First Trust LEGR", sector: "ETF", type: "etf" },
  { ticker: "CIBR", name: "First Trust CIBR", sector: "ETF", type: "etf" },
  { ticker: "ROBO", name: "First Trust ROBO", sector: "ETF", type: "etf" },
  { ticker: "TDIV", name: "First Trust TDIV", sector: "ETF", type: "etf" },
  { ticker: "RDVY", name: "First Trust RDVY", sector: "ETF", type: "etf" },
  { ticker: "FTA", name: "First Trust FTA", sector: "ETF", type: "etf" },
  { ticker: "FYX", name: "First Trust FYX", sector: "ETF", type: "etf" },
  { ticker: "FYT", name: "First Trust FYT", sector: "ETF", type: "etf" },
  { ticker: "FDIS", name: "First Trust FDIS", sector: "ETF", type: "etf" },
  { ticker: "FXB", name: "First Trust FXB", sector: "ETF", type: "etf" },
  { ticker: "FDRR", name: "First Trust FDRR", sector: "ETF", type: "etf" },
  { ticker: "FEX", name: "First Trust FEX", sector: "ETF", type: "etf" },
  { ticker: "FNX", name: "First Trust FNX", sector: "ETF", type: "etf" },
  { ticker: "FNY", name: "First Trust FNY", sector: "ETF", type: "etf" },
  { ticker: "BOTZ", name: "Global X BOTZ", sector: "ETF", type: "etf" },
  { ticker: "DRIV", name: "Global X DRIV", sector: "ETF", type: "etf" },
  { ticker: "CLOU2", name: "Global X CLOU2", sector: "ETF", type: "etf" },
  { ticker: "FINX2", name: "Global X FINX2", sector: "ETF", type: "etf" },
  { ticker: "GNOM", name: "Global X GNOM", sector: "ETF", type: "etf" },
  { ticker: "LIT", name: "Global X LIT", sector: "ETF", type: "etf" },
  { ticker: "POTX", name: "Global X POTX", sector: "ETF", type: "etf" },
  { ticker: "RNRG", name: "Global X RNRG", sector: "ETF", type: "etf" },
  { ticker: "SOCL", name: "Global X SOCL", sector: "ETF", type: "etf" },
  { ticker: "SNSR", name: "Global X SNSR", sector: "ETF", type: "etf" },
  { ticker: "AIQ", name: "Global X AIQ", sector: "ETF", type: "etf" },
  { ticker: "BUG", name: "Global X BUG", sector: "ETF", type: "etf" },
  { ticker: "CTEC", name: "Global X CTEC", sector: "ETF", type: "etf" },
  { ticker: "DAX", name: "Global X DAX", sector: "ETF", type: "etf" },
  { ticker: "DIV2", name: "Global X DIV2", sector: "ETF", type: "etf" },
  { ticker: "EDOC", name: "Global X EDOC", sector: "ETF", type: "etf" },
  { ticker: "EDUT", name: "Global X EDUT", sector: "ETF", type: "etf" },
  { ticker: "EBIZ", name: "Global X EBIZ", sector: "ETF", type: "etf" },
  { ticker: "EWEB", name: "Global X EWEB", sector: "ETF", type: "etf" },
  { ticker: "HERO", name: "Global X HERO", sector: "ETF", type: "etf" },
  { ticker: "KEJI", name: "Global X KEJI", sector: "ETF", type: "etf" },
  { ticker: "KROP", name: "Global X KROP", sector: "ETF", type: "etf" },
  { ticker: "MLPA", name: "Global X MLPA", sector: "ETF", type: "etf" },
  { ticker: "MILN", name: "Global X MILN", sector: "ETF", type: "etf" },
  { ticker: "PAVE", name: "Global X PAVE", sector: "ETF", type: "etf" },
  { ticker: "QYLD2", name: "Global X QYLD2", sector: "ETF", type: "etf" },
  { ticker: "RYLD", name: "Global X RYLD", sector: "ETF", type: "etf" },
  { ticker: "XYLD2", name: "Global X XYLD2", sector: "ETF", type: "etf" },
  { ticker: "SDIV", name: "Global X SDIV", sector: "ETF", type: "etf" },
  { ticker: "SEA", name: "Global X SEA", sector: "ETF", type: "etf" },
  { ticker: "SRET", name: "Global X SRET", sector: "ETF", type: "etf" },
  { ticker: "ALTY", name: "Global X ALTY", sector: "ETF", type: "etf" },
  { ticker: "REVS", name: "Global X REVS", sector: "ETF", type: "etf" },
  { ticker: "DRIV2", name: "Global X DRIV2", sector: "ETF", type: "etf" },
  { ticker: "TQQQ", name: "ProShares TQQQ", sector: "ETF", type: "etf" },
  { ticker: "SQQQ", name: "ProShares SQQQ", sector: "ETF", type: "etf" },
  { ticker: "UPRO", name: "ProShares UPRO", sector: "ETF", type: "etf" },
  { ticker: "SPXU", name: "ProShares SPXU", sector: "ETF", type: "etf" },
  { ticker: "UDOW", name: "ProShares UDOW", sector: "ETF", type: "etf" },
  { ticker: "SDOW", name: "ProShares SDOW", sector: "ETF", type: "etf" },
  { ticker: "QLD", name: "ProShares QLD", sector: "ETF", type: "etf" },
  { ticker: "QID", name: "ProShares QID", sector: "ETF", type: "etf" },
  { ticker: "SSO", name: "ProShares SSO", sector: "ETF", type: "etf" },
  { ticker: "SDS", name: "ProShares SDS", sector: "ETF", type: "etf" },
  { ticker: "UWM", name: "ProShares UWM", sector: "ETF", type: "etf" },
  { ticker: "TWM", name: "ProShares TWM", sector: "ETF", type: "etf" },
  { ticker: "DDM", name: "ProShares DDM", sector: "ETF", type: "etf" },
  { ticker: "DXD", name: "ProShares DXD", sector: "ETF", type: "etf" },
  { ticker: "SAA", name: "ProShares SAA", sector: "ETF", type: "etf" },
  { ticker: "SDD", name: "ProShares SDD", sector: "ETF", type: "etf" },
  { ticker: "MVV", name: "ProShares MVV", sector: "ETF", type: "etf" },
  { ticker: "MZZ", name: "ProShares MZZ", sector: "ETF", type: "etf" },
  { ticker: "UYG", name: "ProShares UYG", sector: "ETF", type: "etf" },
  { ticker: "SKF", name: "ProShares SKF", sector: "ETF", type: "etf" },
  { ticker: "ROM", name: "ProShares ROM", sector: "ETF", type: "etf" },
  { ticker: "REK", name: "ProShares REK", sector: "ETF", type: "etf" },
  { ticker: "DIG", name: "ProShares DIG", sector: "ETF", type: "etf" },
  { ticker: "DUG", name: "ProShares DUG", sector: "ETF", type: "etf" },
  { ticker: "UGE", name: "ProShares UGE", sector: "ETF", type: "etf" },
  { ticker: "SZK", name: "ProShares SZK", sector: "ETF", type: "etf" },
  { ticker: "UBT", name: "ProShares UBT", sector: "ETF", type: "etf" },
  { ticker: "TBT", name: "ProShares TBT", sector: "ETF", type: "etf" },
  { ticker: "TBF", name: "ProShares TBF", sector: "ETF", type: "etf" },
  { ticker: "PST", name: "ProShares PST", sector: "ETF", type: "etf" },
  { ticker: "UGL", name: "ProShares UGL", sector: "ETF", type: "etf" },
  { ticker: "GLL", name: "ProShares GLL", sector: "ETF", type: "etf" },
  { ticker: "AGQ", name: "ProShares AGQ", sector: "ETF", type: "etf" },
  { ticker: "ZSL", name: "ProShares ZSL", sector: "ETF", type: "etf" },
  { ticker: "NOBL", name: "ProShares NOBL", sector: "ETF", type: "etf" },
  { ticker: "BTAL", name: "ProShares BTAL", sector: "ETF", type: "etf" },
  { ticker: "HDG", name: "ProShares HDG", sector: "ETF", type: "etf" },
  { ticker: "SPXL", name: "Direxion SPXL", sector: "ETF", type: "etf" },
  { ticker: "SPXS", name: "Direxion SPXS", sector: "ETF", type: "etf" },
  { ticker: "TECL", name: "Direxion TECL", sector: "ETF", type: "etf" },
  { ticker: "TECS", name: "Direxion TECS", sector: "ETF", type: "etf" },
  { ticker: "SOXL", name: "Direxion SOXL", sector: "ETF", type: "etf" },
  { ticker: "SOXS", name: "Direxion SOXS", sector: "ETF", type: "etf" },
  { ticker: "FAS", name: "Direxion FAS", sector: "ETF", type: "etf" },
  { ticker: "FAZ", name: "Direxion FAZ", sector: "ETF", type: "etf" },
  { ticker: "LABU", name: "Direxion LABU", sector: "ETF", type: "etf" },
  { ticker: "LABD", name: "Direxion LABD", sector: "ETF", type: "etf" },
  { ticker: "NUGT", name: "Direxion NUGT", sector: "ETF", type: "etf" },
  { ticker: "DUST", name: "Direxion DUST", sector: "ETF", type: "etf" },
  { ticker: "TNA", name: "Direxion TNA", sector: "ETF", type: "etf" },
  { ticker: "TZA", name: "Direxion TZA", sector: "ETF", type: "etf" },
  { ticker: "BRZU", name: "Direxion BRZU", sector: "ETF", type: "etf" },
  { ticker: "ERX", name: "Direxion ERX", sector: "ETF", type: "etf" },
  { ticker: "ERY", name: "Direxion ERY", sector: "ETF", type: "etf" },
  { ticker: "JNUG", name: "Direxion JNUG", sector: "ETF", type: "etf" },
  { ticker: "JDST", name: "Direxion JDST", sector: "ETF", type: "etf" },
  { ticker: "DPST", name: "Direxion DPST", sector: "ETF", type: "etf" },
  { ticker: "DRN", name: "Direxion DRN", sector: "ETF", type: "etf" },
  { ticker: "DRV", name: "Direxion DRV", sector: "ETF", type: "etf" },
  { ticker: "CURE", name: "Direxion CURE", sector: "ETF", type: "etf" },
  { ticker: "PILL", name: "Direxion PILL", sector: "ETF", type: "etf" },
  { ticker: "FNGU", name: "Direxion FNGU", sector: "ETF", type: "etf" },
  { ticker: "FNGD", name: "Direxion FNGD", sector: "ETF", type: "etf" },
  { ticker: "DFAC", name: "Dimensional DFAC", sector: "ETF", type: "etf" },
  { ticker: "DFAS", name: "Dimensional DFAS", sector: "ETF", type: "etf" },
  { ticker: "DFAT", name: "Dimensional DFAT", sector: "ETF", type: "etf" },
  { ticker: "DFAU", name: "Dimensional DFAU", sector: "ETF", type: "etf" },
  { ticker: "DFAX", name: "Dimensional DFAX", sector: "ETF", type: "etf" },
  { ticker: "DFCF", name: "Dimensional DFCF", sector: "ETF", type: "etf" },
  { ticker: "DFLV", name: "Dimensional DFLV", sector: "ETF", type: "etf" },
  { ticker: "DFSV", name: "Dimensional DFSV", sector: "ETF", type: "etf" },
  { ticker: "DFIV", name: "Dimensional DFIV", sector: "ETF", type: "etf" },
  { ticker: "DFEM", name: "Dimensional DFEM", sector: "ETF", type: "etf" },
  { ticker: "DFEV", name: "Dimensional DFEV", sector: "ETF", type: "etf" },
  { ticker: "DFAI", name: "Dimensional DFAI", sector: "ETF", type: "etf" },
  { ticker: "DFIC", name: "Dimensional DFIC", sector: "ETF", type: "etf" },
  { ticker: "DFIP", name: "Dimensional DFIP", sector: "ETF", type: "etf" },
  { ticker: "DFIX", name: "Dimensional DFIX", sector: "ETF", type: "etf" },
  { ticker: "DFNM", name: "Dimensional DFNM", sector: "ETF", type: "etf" },
  { ticker: "DFSD", name: "Dimensional DFSD", sector: "ETF", type: "etf" },
  { ticker: "DFUS", name: "Dimensional DFUS", sector: "ETF", type: "etf" },
  { ticker: "DISV", name: "Dimensional DISV", sector: "ETF", type: "etf" },
  { ticker: "DGRS2", name: "Dimensional DGRS2", sector: "ETF", type: "etf" },
  { ticker: "DUHP", name: "Dimensional DUHP", sector: "ETF", type: "etf" },
  { ticker: "DUSL", name: "Dimensional DUSL", sector: "ETF", type: "etf" },
  { ticker: "DEED", name: "Dimensional DEED", sector: "ETF", type: "etf" },
  { ticker: "JEPI", name: "JPMorgan JEPI", sector: "ETF", type: "etf" },
  { ticker: "JEPQ", name: "JPMorgan JEPQ", sector: "ETF", type: "etf" },
  { ticker: "JPST", name: "JPMorgan JPST", sector: "ETF", type: "etf" },
  { ticker: "JPIB", name: "JPMorgan JPIB", sector: "ETF", type: "etf" },
  { ticker: "JMBS", name: "JPMorgan JMBS", sector: "ETF", type: "etf" },
  { ticker: "JPIN", name: "JPMorgan JPIN", sector: "ETF", type: "etf" },
  { ticker: "JPEM", name: "JPMorgan JPEM", sector: "ETF", type: "etf" },
  { ticker: "JPIE", name: "JPMorgan JPIE", sector: "ETF", type: "etf" },
  { ticker: "JPSE", name: "JPMorgan JPSE", sector: "ETF", type: "etf" },
  { ticker: "JMOM", name: "JPMorgan JMOM", sector: "ETF", type: "etf" },
  { ticker: "JVAL", name: "JPMorgan JVAL", sector: "ETF", type: "etf" },
  { ticker: "JQUA", name: "JPMorgan JQUA", sector: "ETF", type: "etf" },
  { ticker: "JGRO", name: "JPMorgan JGRO", sector: "ETF", type: "etf" },
  { ticker: "JMIN", name: "JPMorgan JMIN", sector: "ETF", type: "etf" },
  { ticker: "JIRE", name: "JPMorgan JIRE", sector: "ETF", type: "etf" },
  { ticker: "JMEE", name: "JPMorgan JMEE", sector: "ETF", type: "etf" },
  { ticker: "JAVA", name: "JPMorgan JAVA", sector: "ETF", type: "etf" },
  { ticker: "BBIG", name: "JPMorgan BBIG", sector: "ETF", type: "etf" },
  { ticker: "JCPB", name: "JPMorgan JCPB", sector: "ETF", type: "etf" },
  { ticker: "JCHI", name: "JPMorgan JCHI", sector: "ETF", type: "etf" },
  { ticker: "JPXN", name: "JPMorgan JPXN", sector: "ETF", type: "etf" },
  { ticker: "FIVG", name: "Fidelity FIVG", sector: "ETF", type: "etf" },
  { ticker: "FHLC", name: "Fidelity FHLC", sector: "ETF", type: "etf" },
  { ticker: "FREL", name: "Fidelity FREL", sector: "ETF", type: "etf" },
  { ticker: "FENY", name: "Fidelity FENY", sector: "ETF", type: "etf" },
  { ticker: "FSTA", name: "Fidelity FSTA", sector: "ETF", type: "etf" },
  { ticker: "FMAT", name: "Fidelity FMAT", sector: "ETF", type: "etf" },
  { ticker: "FIDU", name: "Fidelity FIDU", sector: "ETF", type: "etf" },
  { ticker: "FUTY", name: "Fidelity FUTY", sector: "ETF", type: "etf" },
  { ticker: "FNCL", name: "Fidelity FNCL", sector: "ETF", type: "etf" },
  { ticker: "FTEC", name: "Fidelity FTEC", sector: "ETF", type: "etf" },
  { ticker: "FDIS2", name: "Fidelity FDIS2", sector: "ETF", type: "etf" },
  { ticker: "FCOM", name: "Fidelity FCOM", sector: "ETF", type: "etf" },
  { ticker: "ONEQ", name: "Fidelity ONEQ", sector: "ETF", type: "etf" },
  { ticker: "FBND", name: "Fidelity FBND", sector: "ETF", type: "etf" },
  { ticker: "FMHI", name: "Fidelity FMHI", sector: "ETF", type: "etf" },
  { ticker: "FLTB", name: "Fidelity FLTB", sector: "ETF", type: "etf" },
  { ticker: "FTSM", name: "Fidelity FTSM", sector: "ETF", type: "etf" },
  { ticker: "FLDR", name: "Fidelity FLDR", sector: "ETF", type: "etf" },
  { ticker: "FNDF2", name: "Fidelity FNDF2", sector: "ETF", type: "etf" },
  { ticker: "FDEV", name: "Fidelity FDEV", sector: "ETF", type: "etf" },
  { ticker: "FEMR", name: "Fidelity FEMR", sector: "ETF", type: "etf" },
  { ticker: "HACK", name: "ETFMG Prime Cyber Security", sector: "ETF", type: "etf" },
  { ticker: "TAN", name: "Invesco Solar", sector: "ETF", type: "etf" },
  { ticker: "FAN", name: "First Trust Wind Energy", sector: "ETF", type: "etf" },
  { ticker: "ACES", name: "ALPS Clean Energy", sector: "ETF", type: "etf" },
  { ticker: "QCLN", name: "First Trust NASDAQ Clean Edge", sector: "ETF", type: "etf" },
  { ticker: "PBD", name: "Invesco Global Clean Energy", sector: "ETF", type: "etf" },
  { ticker: "CNRG", name: "SPDR S&P Kensho Clean Power", sector: "ETF", type: "etf" },
  { ticker: "SMOG2", name: "VanEck Low Carbon Energy", sector: "ETF", type: "etf" },
  { ticker: "JETS", name: "US Global Jets", sector: "ETF", type: "etf" },
  { ticker: "AWAY", name: "ETFMG Travel Tech", sector: "ETF", type: "etf" },
  { ticker: "BOAT", name: "SonicShares Airlines Hotels Cruise", sector: "ETF", type: "etf" },
  { ticker: "BETZ", name: "Roundhill Sports Betting", sector: "ETF", type: "etf" },
  { ticker: "NERD", name: "Roundhill Video Games", sector: "ETF", type: "etf" },
  { ticker: "WEED", name: "Roundhill Cannabis", sector: "ETF", type: "etf" },
  { ticker: "BITQ", name: "Bitwise Crypto Industry", sector: "ETF", type: "etf" },
  { ticker: "BKCH", name: "Global X Blockchain", sector: "ETF", type: "etf" },
  { ticker: "BLOK", name: "Amplify Blockchain", sector: "ETF", type: "etf" },
  { ticker: "DAPP", name: "VanEck Digital Assets", sector: "ETF", type: "etf" },
  { ticker: "BTCR", name: "Volt Crypto Industry", sector: "ETF", type: "etf" },
  { ticker: "IBIT", name: "iShares Bitcoin Trust", sector: "ETF", type: "etf" },
  { ticker: "FBTC", name: "Fidelity Bitcoin", sector: "ETF", type: "etf" },
  { ticker: "GBTC", name: "Grayscale Bitcoin", sector: "ETF", type: "etf" },
  { ticker: "ETHE", name: "Grayscale Ethereum", sector: "ETF", type: "etf" },
  { ticker: "BITO", name: "ProShares Bitcoin Strategy", sector: "ETF", type: "etf" },
  { ticker: "BTF", name: "Valkyrie Bitcoin Strategy", sector: "ETF", type: "etf" },
  { ticker: "ARKB", name: "ARK Bitcoin", sector: "ETF", type: "etf" },
  { ticker: "BITW", name: "Bitwise 10 Crypto", sector: "ETF", type: "etf" },
  { ticker: "HODL", name: "VanEck Bitcoin", sector: "ETF", type: "etf" },
  { ticker: "IBLC", name: "iShares Blockchain", sector: "ETF", type: "etf" },
  { ticker: "SPGP", name: "Invesco S&P 500 GARP", sector: "ETF", type: "etf" },
  { ticker: "COWZ", name: "Pacer US Cash Cows 100", sector: "ETF", type: "etf" },
  { ticker: "CALF", name: "Pacer US Small Cap Cash Cows", sector: "ETF", type: "etf" },
  { ticker: "DIVO", name: "Amplify CWP Enhanced Div", sector: "ETF", type: "etf" },
  { ticker: "NUSI", name: "Nationwide Nasdaq-100 Risk", sector: "ETF", type: "etf" },
  { ticker: "SWAN", name: "Amplify BlackSwan Growth", sector: "ETF", type: "etf" },
  { ticker: "DBMF", name: "iMGP DBi Managed Futures", sector: "ETF", type: "etf" },
  { ticker: "KMLM", name: "KFA Mount Lucas Managed Futures", sector: "ETF", type: "etf" },
  { ticker: "CTA", name: "Simplify Managed Futures", sector: "ETF", type: "etf" },
  { ticker: "TAIL", name: "Cambria Tail Risk", sector: "ETF", type: "etf" },
  { ticker: "RPAR", name: "RPAR Risk Parity", sector: "ETF", type: "etf" },
  { ticker: "AOR", name: "iShares Core Growth Allocation", sector: "ETF", type: "etf" },
  { ticker: "AOK", name: "iShares Core Conservative", sector: "ETF", type: "etf" },
  { ticker: "AOA", name: "iShares Core Aggressive", sector: "ETF", type: "etf" },
  { ticker: "AOM", name: "iShares Core Moderate", sector: "ETF", type: "etf" },
  { ticker: "GAA", name: "Cambria Global Asset Allocation", sector: "ETF", type: "etf" },
  { ticker: "TRTY", name: "Cambria Trinity", sector: "ETF", type: "etf" },
  { ticker: "GYLD", name: "Arrow Dow Jones Global Yield", sector: "ETF", type: "etf" },
  { ticker: "GAL", name: "SPDR SSgA Global Allocation", sector: "ETF", type: "etf" },
  { ticker: "REET", name: "iShares Global REIT", sector: "ETF", type: "etf" },
  { ticker: "VNQI2", name: "Vanguard Global ex-US REIT", sector: "ETF", type: "etf" },
  { ticker: "SRET2", name: "Global X SuperDividend REIT", sector: "ETF", type: "etf" },
  { ticker: "KBWY2", name: "Invesco KBW Premium Yield REIT", sector: "ETF", type: "etf" },
  { ticker: "RWO", name: "SPDR Dow Jones Global Real Est", sector: "ETF", type: "etf" },
  { ticker: "IFGL", name: "iShares International Dev Real Est", sector: "ETF", type: "etf" },
  { ticker: "HAUZ", name: "Xtrackers International Real Est", sector: "ETF", type: "etf" },
  { ticker: "WPS", name: "iShares International Dev Prop", sector: "ETF", type: "etf" },
  { ticker: "CHIR", name: "Global X MSCI China Real Estate", sector: "ETF", type: "etf" },
  { ticker: "INDS", name: "Pacer Industrial Real Estate", sector: "ETF", type: "etf" },
  { ticker: "HOMZ", name: "Hoya Capital Housing", sector: "ETF", type: "etf" },
  { ticker: "STOR2", name: "Columbia Space Shuttle", sector: "ETF", type: "etf" },
  { ticker: "XLSR", name: "SPDR SSGA US Sector Rotation", sector: "ETF", type: "etf" },
  { ticker: "SECT", name: "Main Sector Rotation", sector: "ETF", type: "etf" },
  { ticker: "ESGV", name: "Vanguard ESG US Stock", sector: "ETF", type: "etf" },
  { ticker: "VSGX", name: "Vanguard ESG International", sector: "ETF", type: "etf" },
  { ticker: "EAGG", name: "iShares ESG Aware US Aggregate", sector: "ETF", type: "etf" },
  { ticker: "NUSC", name: "Nuveen ESG Small-Cap", sector: "ETF", type: "etf" },
  { ticker: "NULG", name: "Nuveen ESG Large-Cap Growth", sector: "ETF", type: "etf" },
  { ticker: "NULV", name: "Nuveen ESG Large-Cap Value", sector: "ETF", type: "etf" },
  { ticker: "KRMA", name: "Global X Conscious Companies", sector: "ETF", type: "etf" },
  { ticker: "SNPE", name: "Xtrackers S&P 500 ESG", sector: "ETF", type: "etf" },
  { ticker: "DSI", name: "iShares MSCI KLD 400 Social", sector: "ETF", type: "etf" },
  { ticker: "VFMO", name: "Vanguard US Momentum Factor", sector: "ETF", type: "etf" },
  { ticker: "VFQY", name: "Vanguard US Quality Factor", sector: "ETF", type: "etf" },
  { ticker: "VFVA", name: "Vanguard US Value Factor", sector: "ETF", type: "etf" },
  { ticker: "VFMF", name: "Vanguard US Multifactor", sector: "ETF", type: "etf" },
];
