import { AssetEntry } from "./types";

export const extraCrypto: AssetEntry[] = [
  { ticker: "APTOUSD", name: "Aptos Token", sector: "Crypto", type: "crypto" },
  { ticker: "ARBIUMD", name: "Arbitrum One", sector: "Crypto", type: "crypto" },
  { ticker: "STARKUSD", name: "StarkNet Token", sector: "Crypto", type: "crypto" },
  { ticker: "ZKEVMUSD", name: "zkEVM Token", sector: "Crypto", type: "crypto" },
  { ticker: "SCROLLUSD2", name: "Scroll Token", sector: "Crypto", type: "crypto" },
  { ticker: "MANTLEUSD", name: "Mantle Network", sector: "Crypto", type: "crypto" },
  { ticker: "BASEUSD2", name: "Base Chain", sector: "Crypto", type: "crypto" },
  { ticker: "LINEAUSD2", name: "Linea Chain", sector: "Crypto", type: "crypto" },
  { ticker: "TAIKOUSD", name: "Taiko", sector: "Crypto", type: "crypto" },
  { ticker: "FUSEUSD", name: "Fuse Network", sector: "Crypto", type: "crypto" },
  { ticker: "HARMONYUSD", name: "Harmony ONE", sector: "Crypto", type: "crypto" },
  { ticker: "ELRDUSD", name: "Elrond", sector: "Crypto", type: "crypto" },
  { ticker: "WAVESUSD", name: "Waves", sector: "Crypto", type: "crypto" },
  { ticker: "KAVAUSD", name: "Kava", sector: "Crypto", type: "crypto" },
  { ticker: "CELOUSD2", name: "Celo Network", sector: "Crypto", type: "crypto" },
  { ticker: "MOVRSD", name: "Moonriver", sector: "Crypto", type: "crypto" },
  { ticker: "MOVRUSD", name: "Moonbeam", sector: "Crypto", type: "crypto" },
  { ticker: "AURORAUSD", name: "Aurora", sector: "Crypto", type: "crypto" },
  { ticker: "BOBAUSD2", name: "Boba Chain", sector: "Crypto", type: "crypto" },
  { ticker: "EVMUSD", name: "Evmos", sector: "Crypto", type: "crypto" },
  { ticker: "CANTUSD", name: "Canto", sector: "Crypto", type: "crypto" },
  { ticker: "CRONUSD2", name: "Cronos Chain", sector: "Crypto", type: "crypto" },
  { ticker: "PULSESD", name: "PulseChain", sector: "Crypto", type: "crypto" },
  { ticker: "KADENUSD", name: "Kadena", sector: "Crypto", type: "crypto" },
  { ticker: "ERGUSD", name: "Ergo", sector: "Crypto", type: "crypto" },
  { ticker: "RVSTUSD", name: "Ravencoin 2", sector: "Crypto", type: "crypto" },
  { ticker: "FLUXUSD", name: "Flux", sector: "Crypto", type: "crypto" },
  { ticker: "ALEPHUSD", name: "Aleph Zero", sector: "Crypto", type: "crypto" },
  { ticker: "MULTIVUSD", name: "MultiversX Token", sector: "Crypto", type: "crypto" },
  { ticker: "ZELDUSD", name: "Zelcash", sector: "Crypto", type: "crypto" },
  { ticker: "QTUMUSD", name: "Qtum", sector: "Crypto", type: "crypto" },
  { ticker: "ICXUSD", name: "ICON", sector: "Crypto", type: "crypto" },
  { ticker: "ONTUSD", name: "Ontology", sector: "Crypto", type: "crypto" },
  { ticker: "WANUSD", name: "Wanchain", sector: "Crypto", type: "crypto" },
  { ticker: "ZENUSD", name: "Horizen", sector: "Crypto", type: "crypto" },
  { ticker: "DCRUSD", name: "Decred", sector: "Crypto", type: "crypto" },
  { ticker: "SCUSD2", name: "Siacoin 2", sector: "Crypto", type: "crypto" },
  { ticker: "DGBUSD", name: "DigiByte", sector: "Crypto", type: "crypto" },
  { ticker: "CKBUSD2", name: "Nervos CKB", sector: "Crypto", type: "crypto" },
  { ticker: "NEROUSD", name: "Nero", sector: "Crypto", type: "crypto" },
  { ticker: "SYSCOINUSD", name: "Syscoin", sector: "Crypto", type: "crypto" },
  { ticker: "KOMOUSD", name: "Komodo", sector: "Crypto", type: "crypto" },
  { ticker: "VERGUSD", name: "Verge", sector: "Crypto", type: "crypto" },
  { ticker: "PIVRSD", name: "PIVX", sector: "Crypto", type: "crypto" },
  { ticker: "NAVUSD", name: "Navcoin", sector: "Crypto", type: "crypto" },
  { ticker: "PARTICLUSD", name: "Particl", sector: "Crypto", type: "crypto" },
  { ticker: "FEATHERCUSD", name: "Feathercoin", sector: "Crypto", type: "crypto" },
  { ticker: "VIACOINUSD", name: "Viacoin", sector: "Crypto", type: "crypto" },
  { ticker: "GRSCUSD", name: "Groestlcoin", sector: "Crypto", type: "crypto" },
  { ticker: "VTCUSD", name: "Vertcoin", sector: "Crypto", type: "crypto" },
  { ticker: "COMPUSD2", name: "Compound V3", sector: "Crypto", type: "crypto" },
  { ticker: "LIDOUSD2", name: "Lido Finance", sector: "Crypto", type: "crypto" },
  { ticker: "ROCKETUSD", name: "Rocket Pool Token", sector: "Crypto", type: "crypto" },
  { ticker: "FRAXSHAREUSD", name: "Frax Share", sector: "Crypto", type: "crypto" },
  { ticker: "CONVEXUSD", name: "Convex Finance", sector: "Crypto", type: "crypto" },
  { ticker: "YEARNUSD", name: "Yearn Finance V3", sector: "Crypto", type: "crypto" },
  { ticker: "RIBBONUSD", name: "Ribbon Finance", sector: "Crypto", type: "crypto" },
  { ticker: "DOPEXUSD", name: "Dopex", sector: "Crypto", type: "crypto" },
  { ticker: "JONESDUSD", name: "Jones DAO", sector: "Crypto", type: "crypto" },
  { ticker: "PLUTUSD", name: "PlutusDAO", sector: "Crypto", type: "crypto" },
  { ticker: "RADIANTUSD", name: "Radiant Capital", sector: "Crypto", type: "crypto" },
  { ticker: "TRABORDUSD", name: "Trader Joe", sector: "Crypto", type: "crypto" },
  { ticker: "SPOOKYUSD", name: "SpookySwap", sector: "Crypto", type: "crypto" },
  { ticker: "SPIRITSD", name: "SpiritSwap", sector: "Crypto", type: "crypto" },
  { ticker: "BEETSSD", name: "Beethoven X", sector: "Crypto", type: "crypto" },
  { ticker: "CURVEUSD2", name: "Curve V2", sector: "Crypto", type: "crypto" },
  { ticker: "SOLIDLYUSD", name: "Solidly", sector: "Crypto", type: "crypto" },
  { ticker: "THENUSD", name: "Thena", sector: "Crypto", type: "crypto" },
  { ticker: "RETRUSD", name: "Retro Finance", sector: "Crypto", type: "crypto" },
  { ticker: "CAMELOTSD", name: "Camelot DEX", sector: "Crypto", type: "crypto" },
  { ticker: "SUSHIUSD2", name: "SushiSwap V2", sector: "Crypto", type: "crypto" },
  { ticker: "QUICKUSD", name: "QuickSwap", sector: "Crypto", type: "crypto" },
  { ticker: "DFYNUSD", name: "Dfyn Network", sector: "Crypto", type: "crypto" },
  { ticker: "COMETHSD", name: "Cometh", sector: "Crypto", type: "crypto" },
  { ticker: "HONEYUSD", name: "HoneySwap", sector: "Crypto", type: "crypto" },
  { ticker: "SYMMETRICUSD", name: "Symmetric", sector: "Crypto", type: "crypto" },
  { ticker: "COWUSD", name: "CoW Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "PARASWAPUSD", name: "ParaSwap", sector: "Crypto", type: "crypto" },
  { ticker: "MATCHAUSD", name: "Matcha", sector: "Crypto", type: "crypto" },
  { ticker: "ZABORUSD", name: "Zapper", sector: "Crypto", type: "crypto" },
  { ticker: "DEBANKLAD", name: "DeBank", sector: "Crypto", type: "crypto" },
  { ticker: "ZERIONUSD", name: "Zerion", sector: "Crypto", type: "crypto" },
  { ticker: "INSTADPPUSD", name: "InstaDapp", sector: "Crypto", type: "crypto" },
  { ticker: "DEFISAVERUSD", name: "DeFi Saver", sector: "Crypto", type: "crypto" },
  { ticker: "SUMMERUSD", name: "Summer.fi", sector: "Crypto", type: "crypto" },
  { ticker: "FURUCOMBUSD", name: "Furucombo", sector: "Crypto", type: "crypto" },
  { ticker: "LOOKSRAREUSD", name: "LooksRare Token", sector: "Crypto", type: "crypto" },
  { ticker: "X2Y2USD2", name: "X2Y2 Token", sector: "Crypto", type: "crypto" },
  { ticker: "SUDOSWPUSD", name: "Sudoswap", sector: "Crypto", type: "crypto" },
  { ticker: "NFTXUSD", name: "NFTX", sector: "Crypto", type: "crypto" },
  { ticker: "BENDDAOUSD", name: "BendDAO", sector: "Crypto", type: "crypto" },
  { ticker: "JPEGUSD", name: "JPEG'd", sector: "Crypto", type: "crypto" },
  { ticker: "PUNKSSD", name: "CryptoPunks Index", sector: "Crypto", type: "crypto" },
  { ticker: "BAYCOSD", name: "BAYC Index", sector: "Crypto", type: "crypto" },
  { ticker: "ARTBLOCKUSD", name: "Art Blocks", sector: "Crypto", type: "crypto" },
  { ticker: "ASYNCARTUSD", name: "Async Art", sector: "Crypto", type: "crypto" },
  { ticker: "FOUNDATUSD", name: "Foundation", sector: "Crypto", type: "crypto" },
  { ticker: "ZORA", name: "Zora", sector: "Crypto", type: "crypto" },
  { ticker: "STEPNUSD", name: "STEPN", sector: "Crypto", type: "crypto" },
  { ticker: "GENOPETSD", name: "Genopets", sector: "Crypto", type: "crypto" },
  { ticker: "AURYUSD", name: "Aurory", sector: "Crypto", type: "crypto" },
  { ticker: "STARATLASUSD", name: "Star Atlas", sector: "Crypto", type: "crypto" },
  { ticker: "DEFKINUSD", name: "DeFi Kingdoms", sector: "Crypto", type: "crypto" },
  { ticker: "ILLUSD", name: "Illuvium", sector: "Crypto", type: "crypto" },
  { ticker: "VULCANUSD", name: "Vulcan Forged", sector: "Crypto", type: "crypto" },
  { ticker: "MYRIAUSD", name: "Myria", sector: "Crypto", type: "crypto" },
  { ticker: "PHANTOMUSD", name: "Phantom Galaxies", sector: "Crypto", type: "crypto" },
  { ticker: "BIGSTUSD", name: "BigTime", sector: "Crypto", type: "crypto" },
  { ticker: "SHRAPNELUSD", name: "Shrapnel", sector: "Crypto", type: "crypto" },
  { ticker: "PARALLELUSD", name: "Parallel", sector: "Crypto", type: "crypto" },
  { ticker: "EMBRSD", name: "Ember Sword", sector: "Crypto", type: "crypto" },
  { ticker: "BLANKOSUSD", name: "Blankos", sector: "Crypto", type: "crypto" },
  { ticker: "THETANUSD", name: "Theta Arena", sector: "Crypto", type: "crypto" },
  { ticker: "SIGGAMEUSD", name: "Sigma Gaming", sector: "Crypto", type: "crypto" },
  { ticker: "STETHUSD", name: "stETH", sector: "Crypto", type: "crypto" },
  { ticker: "RETHUSD", name: "rETH", sector: "Crypto", type: "crypto" },
  { ticker: "CBETHUSD", name: "cbETH", sector: "Crypto", type: "crypto" },
  { ticker: "FRETHUSD", name: "frxETH", sector: "Crypto", type: "crypto" },
  { ticker: "SWETHUSD", name: "swETH", sector: "Crypto", type: "crypto" },
  { ticker: "ANKRETHSD", name: "ankrETH", sector: "Crypto", type: "crypto" },
  { ticker: "OETHUSD2", name: "oETH", sector: "Crypto", type: "crypto" },
  { ticker: "METHUSD", name: "mETH", sector: "Crypto", type: "crypto" },
  { ticker: "BNSOLUSD", name: "bSOL", sector: "Crypto", type: "crypto" },
  { ticker: "MSOLUSD", name: "mSOL", sector: "Crypto", type: "crypto" },
  { ticker: "JITOSOLUSD", name: "jitoSOL", sector: "Crypto", type: "crypto" },
  { ticker: "LSTSOLUSD", name: "lstSOL", sector: "Crypto", type: "crypto" },
  { ticker: "SAVAXXUSD", name: "sAVAX", sector: "Crypto", type: "crypto" },
  { ticker: "STMATICUSD", name: "stMATIC", sector: "Crypto", type: "crypto" },
  { ticker: "MATIXUSD", name: "MaticX", sector: "Crypto", type: "crypto" },
  { ticker: "STBNBUSD", name: "stkBNB", sector: "Crypto", type: "crypto" },
  { ticker: "DYDXUSD2", name: "dYdX V4", sector: "Crypto", type: "crypto" },
  { ticker: "GMXUSD2", name: "GMX V2", sector: "Crypto", type: "crypto" },
  { ticker: "GAINSUSD", name: "Gains Network", sector: "Crypto", type: "crypto" },
  { ticker: "MUXUSD", name: "MUX Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "HMXUSD", name: "HMX", sector: "Crypto", type: "crypto" },
  { ticker: "LEVLUSD", name: "Level Finance", sector: "Crypto", type: "crypto" },
  { ticker: "PRLPUSD", name: "Perpetual Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SYNTHETIXUSD", name: "Synthetix V3", sector: "Crypto", type: "crypto" },
  { ticker: "DRIFTSD", name: "Drift Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "MANGOUSD", name: "Mango Markets", sector: "Crypto", type: "crypto" },
  { ticker: "SERUMSD", name: "Serum", sector: "Crypto", type: "crypto" },
  { ticker: "ZETAUSD2", name: "Zeta Markets", sector: "Crypto", type: "crypto" },
  { ticker: "WORMHOLEUSD", name: "Wormhole Token", sector: "Crypto", type: "crypto" },
  { ticker: "LAYERZEROD", name: "LayerZero Token", sector: "Crypto", type: "crypto" },
  { ticker: "AXELARUSD", name: "Axelar", sector: "Crypto", type: "crypto" },
  { ticker: "CELERUSD", name: "Celer Bridge", sector: "Crypto", type: "crypto" },
  { ticker: "MULTICHAINUSD", name: "Multichain", sector: "Crypto", type: "crypto" },
  { ticker: "SYNAPSEUSD", name: "Synapse", sector: "Crypto", type: "crypto" },
  { ticker: "HOPUSD", name: "Hop Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ACROSSUSD", name: "Across Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "STARGATED", name: "Stargate V2", sector: "Crypto", type: "crypto" },
  { ticker: "ORBITERUSD", name: "Orbiter Finance", sector: "Crypto", type: "crypto" },
  { ticker: "DEBRIDGEUSD", name: "deBridge", sector: "Crypto", type: "crypto" },
  { ticker: "CHAINLKD", name: "Chainlink V2", sector: "Crypto", type: "crypto" },
  { ticker: "BANDSD2", name: "Band Protocol V2", sector: "Crypto", type: "crypto" },
  { ticker: "API3USD2", name: "API3 Token", sector: "Crypto", type: "crypto" },
  { ticker: "PYTH2SD", name: "Pyth V2", sector: "Crypto", type: "crypto" },
  { ticker: "SUPRASD", name: "Supra Oracles", sector: "Crypto", type: "crypto" },
  { ticker: "SWITCHBUSD", name: "Switchboard", sector: "Crypto", type: "crypto" },
  { ticker: "UMBRELLASD", name: "Umbrella Network", sector: "Crypto", type: "crypto" },
  { ticker: "RAZORSD", name: "Razor Network", sector: "Crypto", type: "crypto" },
  { ticker: "ARAGUSD", name: "Aragon", sector: "Crypto", type: "crypto" },
  { ticker: "SNAPSHOTUSD", name: "Snapshot", sector: "Crypto", type: "crypto" },
  { ticker: "TALLYMSD", name: "Tally", sector: "Crypto", type: "crypto" },
  { ticker: "BOARDRMUSD", name: "Boardroom", sector: "Crypto", type: "crypto" },
  { ticker: "PALXUSD", name: "Paladin", sector: "Crypto", type: "crypto" },
  { ticker: "LOBBFYUSD", name: "Lobby Finance", sector: "Crypto", type: "crypto" },
  { ticker: "CONVEXUSD2", name: "Convex Locker", sector: "Crypto", type: "crypto" },
  { ticker: "NEXUSMTUSD", name: "Nexus Mutual", sector: "Crypto", type: "crypto" },
  { ticker: "INSURACEUSD", name: "InsurAce", sector: "Crypto", type: "crypto" },
  { ticker: "BRIDGEMTSD", name: "Bridge Mutual", sector: "Crypto", type: "crypto" },
  { ticker: "UNSLASHDUSD", name: "Unslashed", sector: "Crypto", type: "crypto" },
  { ticker: "ENSUSD", name: "Ethereum Name Service", sector: "Crypto", type: "crypto" },
  { ticker: "SPACEIDUSD", name: "SpaceID", sector: "Crypto", type: "crypto" },
  { ticker: "UNSTAOPUSD", name: "Unstoppable Domains", sector: "Crypto", type: "crypto" },
  { ticker: "HANDSHAKUSD", name: "Handshake", sector: "Crypto", type: "crypto" },
  { ticker: "TORNADOUSD", name: "Tornado Cash", sector: "Crypto", type: "crypto" },
  { ticker: "SECRETUSD", name: "Secret Network", sector: "Crypto", type: "crypto" },
  { ticker: "AABORUSD", name: "Aave Borg", sector: "Crypto", type: "crypto" },
  { ticker: "IRONFSHUSD", name: "Iron Fish", sector: "Crypto", type: "crypto" },
  { ticker: "DUSKUSD", name: "Dusk Network", sector: "Crypto", type: "crypto" },
  { ticker: "MABORUSD", name: "Manta Network", sector: "Crypto", type: "crypto" },
  { ticker: "NOCTURNUSD", name: "Nocturne", sector: "Crypto", type: "crypto" },
  { ticker: "RAILGUNUSD", name: "Railgun", sector: "Crypto", type: "crypto" },
  { ticker: "FRIENUSD", name: "friend.tech", sector: "Crypto", type: "crypto" },
  { ticker: "LENSUSD2", name: "Lens V2", sector: "Crypto", type: "crypto" },
  { ticker: "FARCASTERUSD", name: "Farcaster", sector: "Crypto", type: "crypto" },
  { ticker: "CYBERCONUSD", name: "CyberConnect", sector: "Crypto", type: "crypto" },
  { ticker: "ORBSD", name: "Orb", sector: "Crypto", type: "crypto" },
  { ticker: "DESIUSD", name: "DeSo Token", sector: "Crypto", type: "crypto" },
  { ticker: "MIRRORUSD", name: "Mirror Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "PARAGRAPHUSD", name: "Paragraph", sector: "Crypto", type: "crypto" },
  { ticker: "AUDIUSD2", name: "Audius V2", sector: "Crypto", type: "crypto" },
  { ticker: "SOUNDXYZUSD", name: "Sound.xyz", sector: "Crypto", type: "crypto" },
  { ticker: "ROYALUSD", name: "Royal", sector: "Crypto", type: "crypto" },
  { ticker: "OPULOUSSD", name: "Opulous", sector: "Crypto", type: "crypto" },
  { ticker: "DITTOMUSD", name: "Ditto Music", sector: "Crypto", type: "crypto" },
  { ticker: "EMANATESD", name: "Emanate", sector: "Crypto", type: "crypto" },
  { ticker: "MIXERUSD", name: "Mixer Token", sector: "Crypto", type: "crypto" },
  { ticker: "POLYMARKUSD", name: "Polymarket", sector: "Crypto", type: "crypto" },
  { ticker: "AUGURURSD", name: "Augur V2", sector: "Crypto", type: "crypto" },
  { ticker: "AZURUSD", name: "Azuro", sector: "Crypto", type: "crypto" },
  { ticker: "OVERTIMEUSD", name: "Overtime Markets", sector: "Crypto", type: "crypto" },
  { ticker: "HEDGEHOGSD", name: "Hedgehog Markets", sector: "Crypto", type: "crypto" },
  { ticker: "KALSHISD", name: "Kalshi Token", sector: "Crypto", type: "crypto" },
  { ticker: "DUNESD", name: "Dune Analytics", sector: "Crypto", type: "crypto" },
  { ticker: "NANSENSD", name: "Nansen", sector: "Crypto", type: "crypto" },
  { ticker: "MESSARISD", name: "Messari", sector: "Crypto", type: "crypto" },
  { ticker: "FLIPSIDUSD", name: "Flipside", sector: "Crypto", type: "crypto" },
  { ticker: "FOOTPRINUSD", name: "Footprint", sector: "Crypto", type: "crypto" },
  { ticker: "TOKENRMSD", name: "Token Terminal", sector: "Crypto", type: "crypto" },
  { ticker: "COSMOSHUBSD", name: "Cosmos Hub", sector: "Crypto", type: "crypto" },
  { ticker: "POLKARELAYSD", name: "Polkadot Relay", sector: "Crypto", type: "crypto" },
  { ticker: "AVALANCHESD", name: "Avalanche C-Chain", sector: "Crypto", type: "crypto" },
  { ticker: "POLYGONZKSD", name: "Polygon zkEVM Token", sector: "Crypto", type: "crypto" },
  { ticker: "GNOSISSD", name: "Gnosis Chain", sector: "Crypto", type: "crypto" },
  { ticker: "MOVERSD", name: "Movement", sector: "Crypto", type: "crypto" },
  { ticker: "APTOSUSD2", name: "Aptos Ecosystem", sector: "Crypto", type: "crypto" },
  { ticker: "SUITEKNSD", name: "Sui Ecosystem", sector: "Crypto", type: "crypto" },
  { ticker: "SEIECOSYSD", name: "Sei Ecosystem", sector: "Crypto", type: "crypto" },
  { ticker: "MONADUSD", name: "Monad", sector: "Crypto", type: "crypto" },
  { ticker: "SONICUSD", name: "Sonic", sector: "Crypto", type: "crypto" },
  { ticker: "ECLIPSESD", name: "Eclipse", sector: "Crypto", type: "crypto" },
  { ticker: "BERACHAIND", name: "Berachain", sector: "Crypto", type: "crypto" },
  { ticker: "INITIASD", name: "Initia", sector: "Crypto", type: "crypto" },
  { ticker: "CELESTIASD", name: "Celestia Ecosystem", sector: "Crypto", type: "crypto" },
  { ticker: "FETCHSD", name: "Fetch.ai V2", sector: "Crypto", type: "crypto" },
  { ticker: "OCEANASD", name: "Ocean V2", sector: "Crypto", type: "crypto" },
  { ticker: "SINGULARSD", name: "SingularityNET V2", sector: "Crypto", type: "crypto" },
  { ticker: "RENDERSD", name: "Render Network V2", sector: "Crypto", type: "crypto" },
  { ticker: "AKASHSD", name: "Akash V2", sector: "Crypto", type: "crypto" },
  { ticker: "BITTENSORSD", name: "Bittensor V2", sector: "Crypto", type: "crypto" },
  { ticker: "GRASSUSD", name: "Grass", sector: "Crypto", type: "crypto" },
  { ticker: "VANAD", name: "Vana", sector: "Crypto", type: "crypto" },
  { ticker: "MORPHEUSD", name: "Morpheus AI", sector: "Crypto", type: "crypto" },
  { ticker: "DOGELOUSD", name: "Dogecoin Lore", sector: "Crypto", type: "crypto" },
  { ticker: "CATGIRLUSD", name: "Catgirl", sector: "Crypto", type: "crypto" },
  { ticker: "SAMOYEDUSD", name: "Samoyed", sector: "Crypto", type: "crypto" },
  { ticker: "AKITAUSD", name: "Akita Inu", sector: "Crypto", type: "crypto" },
  { ticker: "HOKKADUSD", name: "Hokkaidu Inu", sector: "Crypto", type: "crypto" },
  { ticker: "HARPUSD", name: "Harper", sector: "Crypto", type: "crypto" },
  { ticker: "BABYUSD", name: "BabyDoge", sector: "Crypto", type: "crypto" },
  { ticker: "SHIBARIUSD", name: "Shibarium Token", sector: "Crypto", type: "crypto" },
  { ticker: "LEASHSD", name: "Leash", sector: "Crypto", type: "crypto" },
  { ticker: "BONEUSD", name: "Bone ShibaSwap", sector: "Crypto", type: "crypto" },
  { ticker: "DOGEBONKSD", name: "DogeBonk", sector: "Crypto", type: "crypto" },
  { ticker: "KISHUSD", name: "Kishu Inu", sector: "Crypto", type: "crypto" },
  { ticker: "SAITUSD", name: "Saitama", sector: "Crypto", type: "crypto" },
  { ticker: "TSUKAUSD", name: "Tsuka", sector: "Crypto", type: "crypto" },
  { ticker: "PITASD", name: "PitBull", sector: "Crypto", type: "crypto" },
  { ticker: "SAFEMOONSD", name: "SafeMoon", sector: "Crypto", type: "crypto" },
  { ticker: "EVERGROWSD", name: "EverGrow Coin", sector: "Crypto", type: "crypto" },
  { ticker: "WBTCUSD", name: "Wrapped Bitcoin", sector: "Crypto", type: "crypto" },
  { ticker: "WETHSD", name: "Wrapped Ether", sector: "Crypto", type: "crypto" },
  { ticker: "RENBTCSD", name: "renBTC", sector: "Crypto", type: "crypto" },
  { ticker: "TBTCUSD", name: "tBTC", sector: "Crypto", type: "crypto" },
  { ticker: "SUSDEUSD", name: "sUSD", sector: "Crypto", type: "crypto" },
  { ticker: "EURDSD", name: "EURD", sector: "Crypto", type: "crypto" },
  { ticker: "EURTUSD", name: "EURT", sector: "Crypto", type: "crypto" },
  { ticker: "JPYCUSD", name: "JPYC", sector: "Crypto", type: "crypto" },
  { ticker: "XSGDSD", name: "XSGD", sector: "Crypto", type: "crypto" },
  { ticker: "TRYBSD", name: "BiLira TRY", sector: "Crypto", type: "crypto" },
  { ticker: "BRLUSD", name: "BRZ", sector: "Crypto", type: "crypto" },
  { ticker: "MXNBUSD", name: "Mexican Peso Stable", sector: "Crypto", type: "crypto" },
  { ticker: "EIGENLSD", name: "EigenLayer Token", sector: "Crypto", type: "crypto" },
  { ticker: "ETHFISD", name: "Ether.fi V2", sector: "Crypto", type: "crypto" },
  { ticker: "KELPUSD", name: "Kelp DAO", sector: "Crypto", type: "crypto" },
  { ticker: "RENZOUSD", name: "Renzo", sector: "Crypto", type: "crypto" },
  { ticker: "PUFFERUSD", name: "Puffer Finance", sector: "Crypto", type: "crypto" },
  { ticker: "SWELLUSD", name: "Swell Network", sector: "Crypto", type: "crypto" },
  { ticker: "EIGENPIED", name: "EigenPie", sector: "Crypto", type: "crypto" },
  { ticker: "STXUSD2", name: "Stacks V2", sector: "Crypto", type: "crypto" },
  { ticker: "RSKOVSD", name: "RSK", sector: "Crypto", type: "crypto" },
  { ticker: "LIQUIDSD", name: "Liquid Network", sector: "Crypto", type: "crypto" },
  { ticker: "LIGHTSD", name: "Lightning Token", sector: "Crypto", type: "crypto" },
  { ticker: "BOBUSD", name: "BOB", sector: "Crypto", type: "crypto" },
  { ticker: "MERIZOUSD", name: "Merizo", sector: "Crypto", type: "crypto" },
  { ticker: "CITREASD", name: "Citrea", sector: "Crypto", type: "crypto" },
  { ticker: "BITLAYESD", name: "BitLayer", sector: "Crypto", type: "crypto" },
  { ticker: "OSMOSD2", name: "Osmosis V2", sector: "Crypto", type: "crypto" },
  { ticker: "JUNOUSD", name: "Juno", sector: "Crypto", type: "crypto" },
  { ticker: "STARUSD", name: "Stargaze", sector: "Crypto", type: "crypto" },
  { ticker: "AKASHCOSD", name: "Akash Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "SECRETCOSD", name: "Secret Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "INJCOSMUSD", name: "Injective Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "FETCHCOSD", name: "Fetch Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "CRESCENUSD", name: "Crescent", sector: "Crypto", type: "crypto" },
  { ticker: "SOMMELIESD", name: "Sommelier", sector: "Crypto", type: "crypto" },
  { ticker: "STRIDEUSD", name: "Stride", sector: "Crypto", type: "crypto" },
  { ticker: "DEVAUSD", name: "DEVA", sector: "Crypto", type: "crypto" },
  { ticker: "MARSUSD", name: "Mars Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "KUJIRAUSD", name: "Kujira", sector: "Crypto", type: "crypto" },
  { ticker: "NEUTRONSD", name: "Neutron", sector: "Crypto", type: "crypto" },
  { ticker: "NOLUSUSD", name: "Nolus", sector: "Crypto", type: "crypto" },
  { ticker: "ARCHWAYD", name: "Archway", sector: "Crypto", type: "crypto" },
  { ticker: "AXELACOSD", name: "Axelar Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "NOBLUSD", name: "Noble", sector: "Crypto", type: "crypto" },
  { ticker: "DYMENSIONSD", name: "Dymension", sector: "Crypto", type: "crypto" },
  { ticker: "SAGAUSD", name: "Saga", sector: "Crypto", type: "crypto" },
  { ticker: "CELESTCOSD", name: "Celestia Token", sector: "Crypto", type: "crypto" },
  { ticker: "ACALAUSD", name: "Acala", sector: "Crypto", type: "crypto" },
  { ticker: "MOONBUSD", name: "Moonbeam Token", sector: "Crypto", type: "crypto" },
  { ticker: "ASTUSD", name: "Astar", sector: "Crypto", type: "crypto" },
  { ticker: "BIFROSTUSD", name: "Bifrost", sector: "Crypto", type: "crypto" },
  { ticker: "PHALASD", name: "Phala Token", sector: "Crypto", type: "crypto" },
  { ticker: "CENTRIFGSD", name: "Centrifuge DOT", sector: "Crypto", type: "crypto" },
  { ticker: "INTERLAYD", name: "Interlay", sector: "Crypto", type: "crypto" },
  { ticker: "HYDRADXSD", name: "HydraDX", sector: "Crypto", type: "crypto" },
  { ticker: "PENDULUMSD", name: "Pendulum", sector: "Crypto", type: "crypto" },
  { ticker: "NODDLESD", name: "Nodle", sector: "Crypto", type: "crypto" },
  { ticker: "UNIQUESD", name: "Unique Network", sector: "Crypto", type: "crypto" },
  { ticker: "ZEITGSTSD", name: "Zeitgeist", sector: "Crypto", type: "crypto" },
  { ticker: "ORIGINTRSD", name: "OriginTrail", sector: "Crypto", type: "crypto" },
  { ticker: "KUSAMASD", name: "Kusama", sector: "Crypto", type: "crypto" },
  { ticker: "ROBONOMICSD", name: "Robonomics", sector: "Crypto", type: "crypto" },
  { ticker: "LITENTRYSD", name: "Litentry", sector: "Crypto", type: "crypto" },
  { ticker: "MANTANETSD", name: "Manta Network Token", sector: "Crypto", type: "crypto" },
  { ticker: "CLOVERUSD", name: "Clover Finance", sector: "Crypto", type: "crypto" },
  { ticker: "RAYDIUMSD", name: "Raydium V2", sector: "Crypto", type: "crypto" },
  { ticker: "ORCASD", name: "Orca V2", sector: "Crypto", type: "crypto" },
  { ticker: "MARINESD", name: "Marinade", sector: "Crypto", type: "crypto" },
  { ticker: "JUPITERSD", name: "Jupiter V2", sector: "Crypto", type: "crypto" },
  { ticker: "DRIFTUSD", name: "Drift V2", sector: "Crypto", type: "crypto" },
  { ticker: "TENSORSD", name: "Tensor", sector: "Crypto", type: "crypto" },
  { ticker: "MAGICEDSD", name: "Magic Eden Token", sector: "Crypto", type: "crypto" },
  { ticker: "JITOSD", name: "Jito V2", sector: "Crypto", type: "crypto" },
  { ticker: "HELIUMSOLD", name: "Helium SOL", sector: "Crypto", type: "crypto" },
  { ticker: "BONKSD", name: "Bonk V2", sector: "Crypto", type: "crypto" },
  { ticker: "WIFSOLD", name: "dogwifhat V2", sector: "Crypto", type: "crypto" },
  { ticker: "SAMSOLD", name: "Samoyedcoin", sector: "Crypto", type: "crypto" },
  { ticker: "POPCSOLD", name: "Popcat SOL", sector: "Crypto", type: "crypto" },
  { ticker: "BOKYSOLD", name: "Bonk SOL", sector: "Crypto", type: "crypto" },
  { ticker: "MEWSOLD", name: "MEW SOL", sector: "Crypto", type: "crypto" },
  { ticker: "WENSOLD", name: "WEN SOL", sector: "Crypto", type: "crypto" },
  { ticker: "CHAINSFUSD", name: "Chainstack", sector: "Crypto", type: "crypto" },
  { ticker: "ALCHEMYUSD", name: "Alchemy", sector: "Crypto", type: "crypto" },
  { ticker: "INFURAUSD", name: "Infura", sector: "Crypto", type: "crypto" },
  { ticker: "MORALISUSD", name: "Moralis", sector: "Crypto", type: "crypto" },
  { ticker: "QUICKNDUSD", name: "QuickNode", sector: "Crypto", type: "crypto" },
  { ticker: "TENDERLYD", name: "Tenderly", sector: "Crypto", type: "crypto" },
  { ticker: "HARDHATUSD", name: "Hardhat", sector: "Crypto", type: "crypto" },
  { ticker: "FOUNDRTUSD", name: "Foundry", sector: "Crypto", type: "crypto" },
  { ticker: "YEARNSD2", name: "Yearn V3", sector: "Crypto", type: "crypto" },
  { ticker: "BEEFY USD", name: "Beefy Finance", sector: "Crypto", type: "crypto" },
  { ticker: "AUTOFARMSD", name: "AutoFarm", sector: "Crypto", type: "crypto" },
  { ticker: "HARVESTSD", name: "Harvest Finance", sector: "Crypto", type: "crypto" },
  { ticker: "ALPACAFSD", name: "Alpaca Finance", sector: "Crypto", type: "crypto" },
  { ticker: "PANCAKSD", name: "PancakeSwap V3", sector: "Crypto", type: "crypto" },
  { ticker: "BISWAPUSD", name: "Biswap", sector: "Crypto", type: "crypto" },
  { ticker: "MDEXUSD", name: "MDEX", sector: "Crypto", type: "crypto" },
  { ticker: "BABYSWPSD", name: "BabySwap", sector: "Crypto", type: "crypto" },
  { ticker: "ELLUSD", name: "Ellipsis Finance", sector: "Crypto", type: "crypto" },
  { ticker: "SOLLENDUSD", name: "Solana Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLSWAPUSD", name: "Solana Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLYIELUSD", name: "Solana Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLVAULUSD", name: "Solana Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLBRIDUSD", name: "Solana Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLPERPUSD", name: "Solana Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLOPTIUSD", name: "Solana Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLINSUUSD", name: "Solana Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLNFTUSD", name: "Solana NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLSTAKUSD", name: "Solana Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLGOVEUSD", name: "Solana Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLINDEUSD", name: "Solana Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLAGGRUSD", name: "Solana Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLORACUSD", name: "Solana Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLANALUSD", name: "Solana Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLGAMIUSD", name: "Solana Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLSOCIUSD", name: "Solana Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLMUSIUSD", name: "Solana Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLSPORUSD", name: "Solana Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "SOLPREDUSD", name: "Solana Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHLENDUSD", name: "Ethereum Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHSWAPUSD", name: "Ethereum Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHYIELUSD", name: "Ethereum Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHVAULUSD", name: "Ethereum Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHBRIDUSD", name: "Ethereum Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHPERPUSD", name: "Ethereum Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHOPTIUSD", name: "Ethereum Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHINSUUSD", name: "Ethereum Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHNFTUSD", name: "Ethereum NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHSTAKUSD", name: "Ethereum Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHGOVEUSD", name: "Ethereum Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHINDEUSD", name: "Ethereum Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHAGGRUSD", name: "Ethereum Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHORACUSD", name: "Ethereum Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHANALUSD", name: "Ethereum Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHGAMIUSD", name: "Ethereum Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHSOCIUSD", name: "Ethereum Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHMUSIUSD", name: "Ethereum Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHSPORUSD", name: "Ethereum Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ETHPREDUSD", name: "Ethereum Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLLENDUSD", name: "Polygon Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLSWAPUSD", name: "Polygon Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLYIELUSD", name: "Polygon Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLVAULUSD", name: "Polygon Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLBRIDUSD", name: "Polygon Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLPERPUSD", name: "Polygon Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLOPTIUSD", name: "Polygon Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLINSUUSD", name: "Polygon Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLNFTUSD", name: "Polygon NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLSTAKUSD", name: "Polygon Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLGOVEUSD", name: "Polygon Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLINDEUSD", name: "Polygon Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLAGGRUSD", name: "Polygon Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLORACUSD", name: "Polygon Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLANALUSD", name: "Polygon Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLGAMIUSD", name: "Polygon Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLSOCIUSD", name: "Polygon Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLMUSIUSD", name: "Polygon Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLSPORUSD", name: "Polygon Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "POLPREDUSD", name: "Polygon Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBLENDUSD", name: "Arbitrum Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBSWAPUSD", name: "Arbitrum Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBYIELUSD", name: "Arbitrum Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBVAULUSD", name: "Arbitrum Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBBRIDUSD", name: "Arbitrum Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBPERPUSD", name: "Arbitrum Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBOPTIUSD", name: "Arbitrum Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBINSUUSD", name: "Arbitrum Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBNFTUSD", name: "Arbitrum NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBSTAKUSD", name: "Arbitrum Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBGOVEUSD", name: "Arbitrum Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBINDEUSD", name: "Arbitrum Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBAGGRUSD", name: "Arbitrum Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBORACUSD", name: "Arbitrum Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBANALUSD", name: "Arbitrum Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBGAMIUSD", name: "Arbitrum Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBSOCIUSD", name: "Arbitrum Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBMUSIUSD", name: "Arbitrum Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBSPORUSD", name: "Arbitrum Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "ARBPREDUSD", name: "Arbitrum Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTLENDUSD", name: "Optimism Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTSWAPUSD", name: "Optimism Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTYIELUSD", name: "Optimism Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTVAULUSD", name: "Optimism Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTBRIDUSD", name: "Optimism Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTPERPUSD", name: "Optimism Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTOPTIUSD", name: "Optimism Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTINSUUSD", name: "Optimism Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTNFTUSD", name: "Optimism NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTSTAKUSD", name: "Optimism Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTGOVEUSD", name: "Optimism Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTINDEUSD", name: "Optimism Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTAGGRUSD", name: "Optimism Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTORACUSD", name: "Optimism Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTANALUSD", name: "Optimism Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTGAMIUSD", name: "Optimism Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTSOCIUSD", name: "Optimism Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTMUSIUSD", name: "Optimism Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTSPORUSD", name: "Optimism Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "OPTPREDUSD", name: "Optimism Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASLENDUSD", name: "Base Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASSWAPUSD", name: "Base Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASYIELUSD", name: "Base Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASVAULUSD", name: "Base Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASBRIDUSD", name: "Base Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASPERPUSD", name: "Base Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASOPTIUSD", name: "Base Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASINSUUSD", name: "Base Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASNFTUSD", name: "Base NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASSTAKUSD", name: "Base Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASGOVEUSD", name: "Base Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASINDEUSD", name: "Base Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASAGGRUSD", name: "Base Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASORACUSD", name: "Base Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASANALUSD", name: "Base Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASGAMIUSD", name: "Base Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASSOCIUSD", name: "Base Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASMUSIUSD", name: "Base Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASSPORUSD", name: "Base Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BASPREDUSD", name: "Base Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVALENDUSD", name: "Avalanche Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVASWAPUSD", name: "Avalanche Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAYIELUSD", name: "Avalanche Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAVAULUSD", name: "Avalanche Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVABRIDUSD", name: "Avalanche Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAPERPUSD", name: "Avalanche Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAOPTIUSD", name: "Avalanche Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAINSUUSD", name: "Avalanche Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVANFTUSD", name: "Avalanche NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVASTAKUSD", name: "Avalanche Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAGOVEUSD", name: "Avalanche Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAINDEUSD", name: "Avalanche Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAAGGRUSD", name: "Avalanche Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAORACUSD", name: "Avalanche Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAANALUSD", name: "Avalanche Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAGAMIUSD", name: "Avalanche Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVASOCIUSD", name: "Avalanche Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAMUSIUSD", name: "Avalanche Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVASPORUSD", name: "Avalanche Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "AVAPREDUSD", name: "Avalanche Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCLENDUSD", name: "BSC Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCSWAPUSD", name: "BSC Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCYIELUSD", name: "BSC Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCVAULUSD", name: "BSC Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCBRIDUSD", name: "BSC Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCPERPUSD", name: "BSC Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCOPTIUSD", name: "BSC Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCINSUUSD", name: "BSC Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCNFTUSD", name: "BSC NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCSTAKUSD", name: "BSC Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCGOVEUSD", name: "BSC Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCINDEUSD", name: "BSC Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCAGGRUSD", name: "BSC Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCORACUSD", name: "BSC Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCANALUSD", name: "BSC Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCGAMIUSD", name: "BSC Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCSOCIUSD", name: "BSC Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCMUSIUSD", name: "BSC Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCSPORUSD", name: "BSC Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "BSCPREDUSD", name: "BSC Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANLENDUSD", name: "Fantom Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANSWAPUSD", name: "Fantom Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANYIELUSD", name: "Fantom Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANVAULUSD", name: "Fantom Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANBRIDUSD", name: "Fantom Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANPERPUSD", name: "Fantom Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANOPTIUSD", name: "Fantom Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANINSUUSD", name: "Fantom Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANNFTUSD", name: "Fantom NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANSTAKUSD", name: "Fantom Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANGOVEUSD", name: "Fantom Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANINDEUSD", name: "Fantom Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANAGGRUSD", name: "Fantom Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANORACUSD", name: "Fantom Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANANALUSD", name: "Fantom Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANGAMIUSD", name: "Fantom Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANSOCIUSD", name: "Fantom Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANMUSIUSD", name: "Fantom Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANSPORUSD", name: "Fantom Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "FANPREDUSD", name: "Fantom Prediction Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROLENDUSD", name: "Cronos Lending Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROSWAPUSD", name: "Cronos Swap Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROYIELUSD", name: "Cronos Yield Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROVAULUSD", name: "Cronos Vault Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROBRIDUSD", name: "Cronos Bridge Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROPERPUSD", name: "Cronos Perp Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROOPTIUSD", name: "Cronos Options Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROINSUUSD", name: "Cronos Insurance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CRONFTUSD", name: "Cronos NFT Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROSTAKUSD", name: "Cronos Staking Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROGOVEUSD", name: "Cronos Governance Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROINDEUSD", name: "Cronos Index Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROAGGRUSD", name: "Cronos Aggregator Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROORACUSD", name: "Cronos Oracle Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROANALUSD", name: "Cronos Analytics Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROGAMIUSD", name: "Cronos Gaming Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROSOCIUSD", name: "Cronos Social Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROMUSIUSD", name: "Cronos Music Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROSPORUSD", name: "Cronos Sports Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "CROPREDUSD", name: "Cronos Prediction Protocol", sector: "Crypto", type: "crypto" },
];
