import { AssetEntry } from "./types";

export const globalETFs: AssetEntry[] = [
  { ticker: "EWJ", name: "iShares MSCI Japan", sector: "Japan", type: "etf" },
  { ticker: "EWG", name: "iShares MSCI Germany", sector: "Europe", type: "etf" },
  { ticker: "EWU", name: "iShares MSCI UK", sector: "Europe", type: "etf" },
  { ticker: "EWC", name: "iShares MSCI Canada", sector: "Americas", type: "etf" },
  { ticker: "EWA", name: "iShares MSCI Australia", sector: "Oceania", type: "etf" },
  { ticker: "EWH", name: "iShares MSCI Hong Kong", sector: "Asia", type: "etf" },
  { ticker: "EWS", name: "iShares MSCI Singapore", sector: "Asia", type: "etf" },
  { ticker: "EWM", name: "iShares MSCI Malaysia", sector: "Asia", type: "etf" },
  { ticker: "EWT", name: "iShares MSCI Taiwan", sector: "Asia", type: "etf" },
  { ticker: "EWY", name: "iShares MSCI South Korea", sector: "Asia", type: "etf" },
  { ticker: "EWZ", name: "iShares MSCI Brazil", sector: "Americas", type: "etf" },
  { ticker: "EWW", name: "iShares MSCI Mexico", sector: "Americas", type: "etf" },
  { ticker: "EZA", name: "iShares MSCI South Africa", sector: "Africa", type: "etf" },
  { ticker: "THD", name: "iShares MSCI Thailand", sector: "Asia", type: "etf" },
  { ticker: "EIDO", name: "iShares MSCI Indonesia", sector: "Asia", type: "etf" },
  { ticker: "EPHE", name: "iShares MSCI Philippines", sector: "Asia", type: "etf" },
  { ticker: "VNM", name: "VanEck Vietnam ETF", sector: "Asia", type: "etf" },
  { ticker: "TUR", name: "iShares MSCI Turkey", sector: "Europe", type: "etf" },
  { ticker: "EPOL", name: "iShares MSCI Poland", sector: "Europe", type: "etf" },
  { ticker: "KSA", name: "iShares MSCI Saudi Arabia", sector: "Middle East", type: "etf" },
  { ticker: "UAE", name: "iShares MSCI UAE", sector: "Middle East", type: "etf" },
  { ticker: "ECH", name: "iShares MSCI Chile", sector: "Americas", type: "etf" },
  { ticker: "GXG", name: "Global X MSCI Colombia", sector: "Americas", type: "etf" },
  { ticker: "EGPT", name: "VanEck Egypt Index", sector: "Africa", type: "etf" },
  { ticker: "NGE", name: "Global X MSCI Nigeria", sector: "Africa", type: "etf" },
  { ticker: "FM", name: "iShares MSCI Frontier", sector: "Global", type: "etf" },
  { ticker: "IEMG", name: "iShares Core MSCI EM", sector: "Global", type: "etf" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging", sector: "Global", type: "etf" },
  { ticker: "SCHE", name: "Schwab Emerging Markets", sector: "Global", type: "etf" },
  { ticker: "SPEM", name: "SPDR Portfolio Emerging", sector: "Global", type: "etf" },
  { ticker: "DEM", name: "WisdomTree Emerging Markets", sector: "Global", type: "etf" },
  { ticker: "DGRE", name: "WisdomTree EM Quality", sector: "Global", type: "etf" },
  { ticker: "FNDE", name: "Schwab Fundamental EM", sector: "Global", type: "etf" },
  { ticker: "XSOE", name: "WisdomTree EM ex-State", sector: "Global", type: "etf" },
  { ticker: "EMXC", name: "iShares MSCI EM ex China", sector: "Global", type: "etf" },
  { ticker: "KWEB", name: "KraneShares CSI China", sector: "Asia", type: "etf" },
  { ticker: "MCHI", name: "iShares MSCI China", sector: "Asia", type: "etf" },
  { ticker: "FXI", name: "iShares China Large-Cap", sector: "Asia", type: "etf" },
  { ticker: "ASHR", name: "Xtrackers Harvest CSI", sector: "Asia", type: "etf" },
  { ticker: "CNYA", name: "iShares MSCI China A", sector: "Asia", type: "etf" },
  { ticker: "GXC", name: "SPDR S&P China", sector: "Asia", type: "etf" },
  { ticker: "FLCH", name: "Franklin FTSE China", sector: "Asia", type: "etf" },
  { ticker: "INDA", name: "iShares MSCI India", sector: "Asia", type: "etf" },
  { ticker: "SMIN", name: "iShares MSCI India SC", sector: "Asia", type: "etf" },
  { ticker: "INDY", name: "iShares India 50", sector: "Asia", type: "etf" },
  { ticker: "EPI", name: "WisdomTree India", sector: "Asia", type: "etf" },
  { ticker: "PIN", name: "Invesco India", sector: "Asia", type: "etf" },
  { ticker: "DXJS", name: "WisdomTree Japan Hedged SC", sector: "Asia", type: "etf" },
  { ticker: "DXJ", name: "WisdomTree Japan Hedged", sector: "Asia", type: "etf" },
  { ticker: "HEWJ", name: "iShares Currency Hedged Japan", sector: "Asia", type: "etf" },
  { ticker: "BBJP", name: "JPMorgan BetaBuilders Japan", sector: "Asia", type: "etf" },
  { ticker: "FLJP", name: "Franklin FTSE Japan", sector: "Asia", type: "etf" },
  { ticker: "FLKR", name: "Franklin FTSE South Korea", sector: "Asia", type: "etf" },
  { ticker: "FLTW", name: "Franklin FTSE Taiwan", sector: "Asia", type: "etf" },
  { ticker: "FLBR", name: "Franklin FTSE Brazil", sector: "Americas", type: "etf" },
  { ticker: "FLMX", name: "Franklin FTSE Mexico", sector: "Americas", type: "etf" },
  { ticker: "FLZA", name: "Franklin FTSE South Africa", sector: "Africa", type: "etf" },
  { ticker: "FLIA", name: "Franklin FTSE Asia ex Japan", sector: "Asia", type: "etf" },
  { ticker: "FLEU", name: "Franklin FTSE Europe", sector: "Europe", type: "etf" },
  { ticker: "VGK", name: "Vanguard FTSE Europe", sector: "Europe", type: "etf" },
  { ticker: "IEUR", name: "iShares Core MSCI Europe", sector: "Europe", type: "etf" },
  { ticker: "FEZ", name: "SPDR EURO STOXX 50", sector: "Europe", type: "etf" },
  { ticker: "EZU", name: "iShares MSCI Eurozone", sector: "Europe", type: "etf" },
  { ticker: "HEDJ", name: "WisdomTree Europe Hedged", sector: "Europe", type: "etf" },
  { ticker: "VPL", name: "Vanguard FTSE Pacific", sector: "Asia", type: "etf" },
  { ticker: "IPAC", name: "iShares Core MSCI Pacific", sector: "Asia", type: "etf" },
  { ticker: "AAXJ", name: "iShares MSCI All Country Asia", sector: "Asia", type: "etf" },
  { ticker: "AIA", name: "iShares Asia 50", sector: "Asia", type: "etf" },
  { ticker: "GMF", name: "SPDR S&P Emerging Asia", sector: "Asia", type: "etf" },
  { ticker: "ADRE", name: "Invesco BLDRS Emerging", sector: "Global", type: "etf" },
  { ticker: "EEM", name: "iShares MSCI Emerging", sector: "Global", type: "etf" },
  { ticker: "DFAE", name: "Dimensional Emerging Core", sector: "Global", type: "etf" },
  { ticker: "AVEM", name: "Avantis International EM", sector: "Global", type: "etf" },
  { ticker: "AVES", name: "Avantis International SCV", sector: "Global", type: "etf" },
  { ticker: "DFEV", name: "Dimensional Emerging Value", sector: "Global", type: "etf" },
  { ticker: "EEMS", name: "iShares MSCI EM SmallCap", sector: "Global", type: "etf" },
  { ticker: "ESGE", name: "iShares ESG Aware EM", sector: "Global", type: "etf" },
  { ticker: "LDEM", name: "iShares ESG EM Leaders", sector: "Global", type: "etf" },
  { ticker: "VXUS", name: "Vanguard Total International", sector: "Global", type: "etf" },
  { ticker: "IXUS", name: "iShares Core MSCI Total Intl", sector: "Global", type: "etf" },
  { ticker: "SPDW", name: "SPDR Portfolio Developed", sector: "Global", type: "etf" },
  { ticker: "CWI", name: "SPDR MSCI ACWI ex-US", sector: "Global", type: "etf" },
  { ticker: "ACWX", name: "iShares MSCI ACWI ex US", sector: "Global", type: "etf" },
  { ticker: "VSS", name: "Vanguard FTSE All-World ex-US SC", sector: "Global", type: "etf" },
  { ticker: "SCZ", name: "iShares MSCI EAFE SC", sector: "Global", type: "etf" },
  { ticker: "GWX", name: "SPDR S&P International SC", sector: "Global", type: "etf" },
  { ticker: "DLS", name: "WisdomTree International SC", sector: "Global", type: "etf" },
  { ticker: "PDN", name: "Invesco FTSE RAFI DM ex-US SC", sector: "Global", type: "etf" },
  { ticker: "IDEV", name: "iShares Core MSCI Intl Dev", sector: "Global", type: "etf" },
  { ticker: "DFAI", name: "Dimensional International Core", sector: "Global", type: "etf" },
  { ticker: "AVDV", name: "Avantis International SCV", sector: "Global", type: "etf" },
  { ticker: "DISV", name: "Dimensional International SC Value", sector: "Global", type: "etf" },
  { ticker: "FNDF", name: "Schwab Fundamental International", sector: "Global", type: "etf" },
  { ticker: "PXF", name: "Invesco FTSE RAFI DM ex-US", sector: "Global", type: "etf" },
  { ticker: "DOL", name: "WisdomTree International LargeCap", sector: "Global", type: "etf" },
  { ticker: "DTH", name: "WisdomTree International HC", sector: "Global", type: "etf" },
  { ticker: "HEFA", name: "iShares Currency Hedged EAFE", sector: "Global", type: "etf" },
  { ticker: "DBEF", name: "Xtrackers MSCI EAFE Hedged", sector: "Global", type: "etf" },
  { ticker: "IEFA", name: "iShares Core MSCI EAFE", sector: "Global", type: "etf" },
  { ticker: "EFA", name: "iShares MSCI EAFE", sector: "Global", type: "etf" },
  { ticker: "SCHF", name: "Schwab International Equity", sector: "Global", type: "etf" },
  { ticker: "VEA", name: "Vanguard FTSE Developed", sector: "Global", type: "etf" },
];

export const moreThematicETFs: AssetEntry[] = [
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "Technology", type: "etf" },
  { ticker: "ARKW", name: "ARK Next Generation Internet", sector: "Technology", type: "etf" },
  { ticker: "ARKG", name: "ARK Genomic Revolution", sector: "Healthcare", type: "etf" },
  { ticker: "ARKF", name: "ARK Fintech Innovation", sector: "Finance", type: "etf" },
  { ticker: "ARKQ", name: "ARK Autonomous Tech & Robotics", sector: "Technology", type: "etf" },
  { ticker: "ARKX", name: "ARK Space Exploration", sector: "Technology", type: "etf" },
  { ticker: "IZRL", name: "ARK Israel Innovative", sector: "Technology", type: "etf" },
  { ticker: "PRNT", name: "3D Printing ETF", sector: "Technology", type: "etf" },
  { ticker: "DRIV", name: "Global X Autonomous & EV", sector: "Technology", type: "etf" },
  { ticker: "LIT", name: "Global X Lithium & Battery", sector: "Materials", type: "etf" },
  { ticker: "BOTZ", name: "Global X Robotics & AI", sector: "Technology", type: "etf" },
  { ticker: "AIQ", name: "Global X AI & Technology", sector: "Technology", type: "etf" },
  { ticker: "SOCL", name: "Global X Social Media", sector: "Communication", type: "etf" },
  { ticker: "EDOC", name: "Global X Telemedicine", sector: "Healthcare", type: "etf" },
  { ticker: "GNOM", name: "Global X Genomics", sector: "Healthcare", type: "etf" },
  { ticker: "CLOU", name: "Global X Cloud Computing", sector: "Technology", type: "etf" },
  { ticker: "HERO", name: "Global X Video Games", sector: "Technology", type: "etf" },
  { ticker: "BFIT", name: "Global X Health & Wellness", sector: "Healthcare", type: "etf" },
  { ticker: "POTX", name: "Global X Cannabis", sector: "Healthcare", type: "etf" },
  { ticker: "BUG", name: "Global X Cybersecurity", sector: "Technology", type: "etf" },
  { ticker: "FINX", name: "Global X FinTech", sector: "Finance", type: "etf" },
  { ticker: "SNSR", name: "Global X Internet of Things", sector: "Technology", type: "etf" },
  { ticker: "EBIZ", name: "Global X E-commerce", sector: "Consumer", type: "etf" },
  { ticker: "CTEC", name: "Global X CleanTech", sector: "Technology", type: "etf" },
  { ticker: "URNM", name: "Sprott Uranium Miners", sector: "Energy", type: "etf" },
  { ticker: "URA", name: "Global X Uranium", sector: "Energy", type: "etf" },
  { ticker: "COPX", name: "Global X Copper Miners", sector: "Materials", type: "etf" },
  { ticker: "SIL", name: "Global X Silver Miners", sector: "Materials", type: "etf" },
  { ticker: "GOAU", name: "US Global GO GOLD", sector: "Materials", type: "etf" },
  { ticker: "REMX", name: "VanEck Rare Earth", sector: "Materials", type: "etf" },
  { ticker: "JETS", name: "US Global Jets ETF", sector: "Industrials", type: "etf" },
  { ticker: "PAVE", name: "Global X US Infrastructure", sector: "Industrials", type: "etf" },
  { ticker: "NFRA", name: "FlexShares STOXX Global Infra", sector: "Industrials", type: "etf" },
  { ticker: "IFRA", name: "iShares US Infrastructure", sector: "Industrials", type: "etf" },
  { ticker: "CIBR", name: "First Trust Nasdaq Cybersecurity", sector: "Technology", type: "etf" },
  { ticker: "HACK", name: "ETFMG Prime Cyber Security", sector: "Technology", type: "etf" },
  { ticker: "WCLD", name: "WisdomTree Cloud Computing", sector: "Technology", type: "etf" },
  { ticker: "SKYY", name: "First Trust Cloud Computing", sector: "Technology", type: "etf" },
  { ticker: "IGV", name: "iShares Expanded Tech-Software", sector: "Technology", type: "etf" },
  { ticker: "SOXX", name: "iShares Semiconductor", sector: "Technology", type: "etf" },
  { ticker: "SMH", name: "VanEck Semiconductor", sector: "Technology", type: "etf" },
  { ticker: "PSI", name: "Invesco Dynamic Semiconductors", sector: "Technology", type: "etf" },
  { ticker: "SOXQ", name: "Invesco PHLX Semiconductor", sector: "Technology", type: "etf" },
  { ticker: "XBI", name: "SPDR S&P Biotech", sector: "Healthcare", type: "etf" },
  { ticker: "IBB", name: "iShares Biotechnology", sector: "Healthcare", type: "etf" },
  { ticker: "BBH", name: "VanEck Biotech", sector: "Healthcare", type: "etf" },
  { ticker: "LABU", name: "Direxion Daily S&P Biotech Bull", sector: "Healthcare", type: "etf" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR", sector: "Healthcare", type: "etf" },
  { ticker: "VHT", name: "Vanguard Health Care", sector: "Healthcare", type: "etf" },
  { ticker: "IHI", name: "iShares US Medical Devices", sector: "Healthcare", type: "etf" },
  { ticker: "XLE", name: "Energy Select Sector SPDR", sector: "Energy", type: "etf" },
  { ticker: "VDE", name: "Vanguard Energy", sector: "Energy", type: "etf" },
  { ticker: "XOP", name: "SPDR S&P Oil & Gas Exploration", sector: "Energy", type: "etf" },
  { ticker: "OIH", name: "VanEck Oil Services", sector: "Energy", type: "etf" },
  { ticker: "AMLP", name: "Alerian MLP", sector: "Energy", type: "etf" },
  { ticker: "MLPA", name: "Global X MLP", sector: "Energy", type: "etf" },
  { ticker: "XLF", name: "Financial Select Sector SPDR", sector: "Finance", type: "etf" },
  { ticker: "VFH", name: "Vanguard Financials", sector: "Finance", type: "etf" },
  { ticker: "KBE", name: "SPDR S&P Bank", sector: "Finance", type: "etf" },
  { ticker: "KRE", name: "SPDR S&P Regional Banking", sector: "Finance", type: "etf" },
  { ticker: "IAI", name: "iShares US Broker-Dealers", sector: "Finance", type: "etf" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR", sector: "Industrials", type: "etf" },
  { ticker: "VIS", name: "Vanguard Industrials", sector: "Industrials", type: "etf" },
  { ticker: "ITA", name: "iShares US Aerospace & Defense", sector: "Industrials", type: "etf" },
  { ticker: "PPA", name: "Invesco Aerospace & Defense", sector: "Industrials", type: "etf" },
  { ticker: "XLY", name: "Consumer Discretionary Select", sector: "Consumer", type: "etf" },
  { ticker: "VCR", name: "Vanguard Consumer Discretionary", sector: "Consumer", type: "etf" },
  { ticker: "XLP", name: "Consumer Staples Select SPDR", sector: "Consumer", type: "etf" },
  { ticker: "VDC", name: "Vanguard Consumer Staples", sector: "Consumer", type: "etf" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR", sector: "Utilities", type: "etf" },
  { ticker: "VPU", name: "Vanguard Utilities", sector: "Utilities", type: "etf" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR", sector: "Real Estate", type: "etf" },
  { ticker: "VNQ", name: "Vanguard Real Estate", sector: "Real Estate", type: "etf" },
  { ticker: "IYR", name: "iShares US Real Estate", sector: "Real Estate", type: "etf" },
  { ticker: "XLB", name: "Materials Select Sector SPDR", sector: "Materials", type: "etf" },
  { ticker: "VAW", name: "Vanguard Materials", sector: "Materials", type: "etf" },
  { ticker: "XLC", name: "Communication Services Select", sector: "Communication", type: "etf" },
  { ticker: "VOX", name: "Vanguard Communication Services", sector: "Communication", type: "etf" },
  { ticker: "XLK", name: "Technology Select Sector SPDR", sector: "Technology", type: "etf" },
  { ticker: "VGT", name: "Vanguard Information Technology", sector: "Technology", type: "etf" },
  { ticker: "QQQM", name: "Invesco NASDAQ 100 ETF", sector: "Technology", type: "etf" },
  { ticker: "QQQJ", name: "Invesco NASDAQ Next Gen 100", sector: "Technology", type: "etf" },
  { ticker: "ONEQ", name: "Fidelity NASDAQ Composite", sector: "Technology", type: "etf" },
  { ticker: "FTEC", name: "Fidelity MSCI IT", sector: "Technology", type: "etf" },
  { ticker: "FDIS", name: "Fidelity MSCI Consumer Disc", sector: "Consumer", type: "etf" },
  { ticker: "FSTA", name: "Fidelity MSCI Consumer Staples", sector: "Consumer", type: "etf" },
  { ticker: "FHLC", name: "Fidelity MSCI Health Care", sector: "Healthcare", type: "etf" },
  { ticker: "FIDU", name: "Fidelity MSCI Industrials", sector: "Industrials", type: "etf" },
  { ticker: "FMAT", name: "Fidelity MSCI Materials", sector: "Materials", type: "etf" },
  { ticker: "FENY", name: "Fidelity MSCI Energy", sector: "Energy", type: "etf" },
  { ticker: "FREL", name: "Fidelity MSCI Real Estate", sector: "Real Estate", type: "etf" },
  { ticker: "FUTY", name: "Fidelity MSCI Utilities", sector: "Utilities", type: "etf" },
  { ticker: "FCOM", name: "Fidelity MSCI Comm Services", sector: "Communication", type: "etf" },
];
