import { AssetEntry } from "./types";

export const indexFunds: AssetEntry[] = [
  // MSCI Indices
  { ticker: "ACWI", name: "iShares MSCI ACWI ETF", sector: "Global Index", type: "index" },
  { ticker: "URTH", name: "iShares MSCI World ETF", sector: "Global Index", type: "index" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF", sector: "International Index", type: "index" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", sector: "Emerging Markets", type: "index" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF", sector: "Emerging Markets", type: "index" },
  { ticker: "SCZ", name: "iShares MSCI EAFE Small-Cap ETF", sector: "International Index", type: "index" },
  { ticker: "ACWX", name: "iShares MSCI ACWI ex U.S. ETF", sector: "International Index", type: "index" },
  { ticker: "IXUS", name: "iShares Core MSCI Total International Stock ETF", sector: "International Index", type: "index" },
  { ticker: "IEFA", name: "iShares Core MSCI EAFE ETF", sector: "International Index", type: "index" },
  { ticker: "MCHI", name: "iShares MSCI China ETF", sector: "China Index", type: "index" },
  { ticker: "EWJ", name: "iShares MSCI Japan ETF", sector: "Japan Index", type: "index" },
  { ticker: "EWG", name: "iShares MSCI Germany ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWU", name: "iShares MSCI United Kingdom ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWQ", name: "iShares MSCI France ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWI", name: "iShares MSCI Italy ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWP", name: "iShares MSCI Spain ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWN", name: "iShares MSCI Netherlands ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWL", name: "iShares MSCI Switzerland ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWD", name: "iShares MSCI Sweden ETF", sector: "Europe Index", type: "index" },
  { ticker: "ENOR", name: "iShares MSCI Norway ETF", sector: "Europe Index", type: "index" },
  { ticker: "EDEN", name: "iShares MSCI Denmark ETF", sector: "Europe Index", type: "index" },
  { ticker: "EFNL", name: "iShares MSCI Finland ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWK", name: "iShares MSCI Belgium ETF", sector: "Europe Index", type: "index" },
  { ticker: "EPOL", name: "iShares MSCI Poland ETF", sector: "Europe Index", type: "index" },
  { ticker: "EWA", name: "iShares MSCI Australia ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EWH", name: "iShares MSCI Hong Kong ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EWS", name: "iShares MSCI Singapore ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EWY", name: "iShares MSCI South Korea ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EWT", name: "iShares MSCI Taiwan ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EWM", name: "iShares MSCI Malaysia ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "THD", name: "iShares MSCI Thailand ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EIDO", name: "iShares MSCI Indonesia ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "EPHE", name: "iShares MSCI Philippines ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "INDA", name: "iShares MSCI India ETF", sector: "India Index", type: "index" },
  { ticker: "INDY", name: "iShares India 50 ETF", sector: "India Index", type: "index" },
  { ticker: "EWZ", name: "iShares MSCI Brazil ETF", sector: "LATAM Index", type: "index" },
  { ticker: "EWW", name: "iShares MSCI Mexico ETF", sector: "LATAM Index", type: "index" },
  { ticker: "ECH", name: "iShares MSCI Chile ETF", sector: "LATAM Index", type: "index" },
  { ticker: "ICOL", name: "iShares MSCI Colombia ETF", sector: "LATAM Index", type: "index" },
  { ticker: "ARGT", name: "Global X MSCI Argentina ETF", sector: "LATAM Index", type: "index" },
  { ticker: "EPU", name: "iShares MSCI Peru ETF", sector: "LATAM Index", type: "index" },
  { ticker: "EZA", name: "iShares MSCI South Africa ETF", sector: "Africa Index", type: "index" },
  { ticker: "NGE", name: "Global X MSCI Nigeria ETF", sector: "Africa Index", type: "index" },
  { ticker: "AFK", name: "VanEck Africa Index ETF", sector: "Africa Index", type: "index" },
  { ticker: "TUR", name: "iShares MSCI Turkey ETF", sector: "Middle East Index", type: "index" },
  { ticker: "KSA", name: "iShares MSCI Saudi Arabia ETF", sector: "Middle East Index", type: "index" },
  { ticker: "UAE", name: "iShares MSCI UAE ETF", sector: "Middle East Index", type: "index" },
  { ticker: "QAT", name: "iShares MSCI Qatar ETF", sector: "Middle East Index", type: "index" },
  { ticker: "ERUS", name: "iShares MSCI Russia ETF", sector: "Russia Index", type: "index" },
  { ticker: "VNM", name: "VanEck Vietnam ETF", sector: "Asia Pacific Index", type: "index" },

  // FTSE Indices
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF", sector: "International Index", type: "index" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", sector: "International Index", type: "index" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", sector: "Emerging Markets", type: "index" },
  { ticker: "VSS", name: "Vanguard FTSE All-World ex-US Small-Cap ETF", sector: "International Index", type: "index" },
  { ticker: "VGK", name: "Vanguard FTSE Europe ETF", sector: "Europe Index", type: "index" },
  { ticker: "VPL", name: "Vanguard FTSE Pacific ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "VYMI", name: "Vanguard International High Dividend Yield ETF", sector: "International Index", type: "index" },
  { ticker: "VNQI", name: "Vanguard Global ex-U.S. Real Estate ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "FLGR", name: "Franklin FTSE Germany ETF", sector: "Europe Index", type: "index" },
  { ticker: "FLJP", name: "Franklin FTSE Japan ETF", sector: "Japan Index", type: "index" },
  { ticker: "FLCH", name: "Franklin FTSE China ETF", sector: "China Index", type: "index" },
  { ticker: "FLIN", name: "Franklin FTSE India ETF", sector: "India Index", type: "index" },
  { ticker: "FLBR", name: "Franklin FTSE Brazil ETF", sector: "LATAM Index", type: "index" },
  { ticker: "FLKR", name: "Franklin FTSE South Korea ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "FLTW", name: "Franklin FTSE Taiwan ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "FLMX", name: "Franklin FTSE Mexico ETF", sector: "LATAM Index", type: "index" },
  { ticker: "FLSA", name: "Franklin FTSE South Africa ETF", sector: "Africa Index", type: "index" },
  { ticker: "FLFR", name: "Franklin FTSE France ETF", sector: "Europe Index", type: "index" },
  { ticker: "FLGB", name: "Franklin FTSE United Kingdom ETF", sector: "Europe Index", type: "index" },
  { ticker: "FLIT", name: "Franklin FTSE Italy ETF", sector: "Europe Index", type: "index" },
  { ticker: "FLAU", name: "Franklin FTSE Australia ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "FLHK", name: "Franklin FTSE Hong Kong ETF", sector: "Asia Pacific Index", type: "index" },
  { ticker: "FLCA", name: "Franklin FTSE Canada ETF", sector: "North America Index", type: "index" },
  { ticker: "FLSW", name: "Franklin FTSE Switzerland ETF", sector: "Europe Index", type: "index" },
  { ticker: "FLSP", name: "Franklin FTSE Spain ETF", sector: "Europe Index", type: "index" },
  { ticker: "ISF.L", name: "iShares Core FTSE 100 UCITS ETF", sector: "UK Index", type: "index" },
  { ticker: "MIDD.L", name: "iShares FTSE 250 UCITS ETF", sector: "UK Index", type: "index" },
  { ticker: "VUKE.L", name: "Vanguard FTSE 100 UCITS ETF", sector: "UK Index", type: "index" },
  { ticker: "VMID.L", name: "Vanguard FTSE 250 UCITS ETF", sector: "UK Index", type: "index" },
  { ticker: "VWRL.L", name: "Vanguard FTSE All-World UCITS ETF", sector: "Global Index", type: "index" },
  { ticker: "VDEV.L", name: "Vanguard FTSE Developed World UCITS ETF", sector: "International Index", type: "index" },
  { ticker: "VFEM.L", name: "Vanguard FTSE Emerging Markets UCITS ETF", sector: "Emerging Markets", type: "index" },

  // S&P Indices (beyond basic S&P 500)
  { ticker: "SPLG", name: "SPDR Portfolio S&P 500 ETF", sector: "US Index", type: "index" },
  { ticker: "SPMD", name: "SPDR Portfolio S&P 400 Mid Cap ETF", sector: "US Index", type: "index" },
  { ticker: "SPSM", name: "SPDR Portfolio S&P 600 Small Cap ETF", sector: "US Index", type: "index" },
  { ticker: "SPTM", name: "SPDR Portfolio S&P 1500 Composite Stock Market ETF", sector: "US Index", type: "index" },
  { ticker: "SPYG", name: "SPDR Portfolio S&P 500 Growth ETF", sector: "US Index", type: "index" },
  { ticker: "SPYV", name: "SPDR Portfolio S&P 500 Value ETF", sector: "US Index", type: "index" },
  { ticker: "XBI", name: "SPDR S&P Biotech ETF", sector: "Healthcare Index", type: "index" },
  { ticker: "KBE", name: "SPDR S&P Bank ETF", sector: "Financial Index", type: "index" },
  { ticker: "KRE", name: "SPDR S&P Regional Banking ETF", sector: "Financial Index", type: "index" },
  { ticker: "XHB", name: "SPDR S&P Homebuilders ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "XME", name: "SPDR S&P Metals & Mining ETF", sector: "Materials Index", type: "index" },
  { ticker: "XOP", name: "SPDR S&P Oil & Gas Exploration & Production ETF", sector: "Energy Index", type: "index" },
  { ticker: "XAR", name: "SPDR S&P Aerospace & Defense ETF", sector: "Industrial Index", type: "index" },
  { ticker: "XNTK", name: "SPDR NYSE Technology ETF", sector: "Technology Index", type: "index" },

  // Russell Indices
  { ticker: "IWB", name: "iShares Russell 1000 ETF", sector: "US Index", type: "index" },
  { ticker: "IWR", name: "iShares Russell Mid-Cap ETF", sector: "US Index", type: "index" },
  { ticker: "IWO", name: "iShares Russell 2000 Growth ETF", sector: "US Index", type: "index" },
  { ticker: "IWN", name: "iShares Russell 2000 Value ETF", sector: "US Index", type: "index" },
  { ticker: "IWV", name: "iShares Russell 3000 ETF", sector: "US Index", type: "index" },
  { ticker: "IWP", name: "iShares Russell Mid-Cap Growth ETF", sector: "US Index", type: "index" },
  { ticker: "IWS", name: "iShares Russell Mid-Cap Value ETF", sector: "US Index", type: "index" },
  { ticker: "VTWO", name: "Vanguard Russell 2000 ETF", sector: "US Index", type: "index" },
  { ticker: "VONG", name: "Vanguard Russell 1000 Growth ETF", sector: "US Index", type: "index" },
  { ticker: "VONV", name: "Vanguard Russell 1000 Value ETF", sector: "US Index", type: "index" },

  // Nasdaq Indices
  { ticker: "QQQM", name: "Invesco NASDAQ 100 ETF", sector: "Technology Index", type: "index" },
  { ticker: "QQEW", name: "First Trust NASDAQ-100 Equal Weighted ETF", sector: "Technology Index", type: "index" },
  { ticker: "QQQJ", name: "Invesco NASDAQ Next Gen 100 ETF", sector: "Technology Index", type: "index" },
  { ticker: "QTEC", name: "First Trust NASDAQ-100 Technology ETF", sector: "Technology Index", type: "index" },
  { ticker: "ONEQ", name: "Fidelity Nasdaq Composite Index ETF", sector: "Technology Index", type: "index" },

  // Dow Jones Indices
  { ticker: "DJIA", name: "Global X Dow 30 Covered Call ETF", sector: "US Index", type: "index" },
  { ticker: "DON", name: "WisdomTree U.S. MidCap Dividend Fund", sector: "US Index", type: "index" },
  { ticker: "DES", name: "WisdomTree U.S. SmallCap Dividend Fund", sector: "US Index", type: "index" },
  { ticker: "DLN", name: "WisdomTree U.S. LargeCap Dividend Fund", sector: "US Index", type: "index" },
  { ticker: "DTD", name: "WisdomTree U.S. Total Dividend Fund", sector: "US Index", type: "index" },

  // Euro STOXX / European Indices
  { ticker: "FEZ", name: "SPDR EURO STOXX 50 ETF", sector: "Europe Index", type: "index" },
  { ticker: "IEV", name: "iShares Europe ETF", sector: "Europe Index", type: "index" },
  { ticker: "HEDJ", name: "WisdomTree Europe Hedged Equity Fund", sector: "Europe Index", type: "index" },
  { ticker: "EZU", name: "iShares MSCI Eurozone ETF", sector: "Europe Index", type: "index" },
  { ticker: "IEUR", name: "iShares Core MSCI Europe ETF", sector: "Europe Index", type: "index" },
  { ticker: "BBEU", name: "JPMorgan BetaBuilders Europe ETF", sector: "Europe Index", type: "index" },
  { ticker: "SPEU", name: "SPDR Portfolio Europe ETF", sector: "Europe Index", type: "index" },
  { ticker: "ESGV", name: "Vanguard ESG U.S. Stock ETF", sector: "ESG Index", type: "index" },
  { ticker: "VSGX", name: "Vanguard ESG International Stock ETF", sector: "ESG Index", type: "index" },
  { ticker: "ESGU", name: "iShares ESG Aware MSCI USA ETF", sector: "ESG Index", type: "index" },
  { ticker: "ESGD", name: "iShares ESG Aware MSCI EAFE ETF", sector: "ESG Index", type: "index" },
  { ticker: "ESGE", name: "iShares ESG Aware MSCI EM ETF", sector: "ESG Index", type: "index" },
  { ticker: "SUSA", name: "iShares MSCI USA ESG Select ETF", sector: "ESG Index", type: "index" },
  { ticker: "SUSL", name: "iShares ESG MSCI USA Leaders ETF", sector: "ESG Index", type: "index" },

  // DAX / German Indices
  { ticker: "DAX.DE", name: "iShares Core DAX UCITS ETF", sector: "Germany Index", type: "index" },
  { ticker: "EXS1.DE", name: "iShares Core DAX UCITS ETF (DE)", sector: "Germany Index", type: "index" },
  { ticker: "MDAX.DE", name: "iShares MDAX UCITS ETF", sector: "Germany Index", type: "index" },

  // CAC 40 / French Indices
  { ticker: "CAC.PA", name: "Lyxor CAC 40 UCITS ETF", sector: "France Index", type: "index" },
  { ticker: "C40.PA", name: "Amundi CAC 40 UCITS ETF", sector: "France Index", type: "index" },

  // Nikkei / Japanese Indices
  { ticker: "DXJ", name: "WisdomTree Japan Hedged Equity Fund", sector: "Japan Index", type: "index" },
  { ticker: "BBJP", name: "JPMorgan BetaBuilders Japan ETF", sector: "Japan Index", type: "index" },
  { ticker: "DBJP", name: "Xtrackers MSCI Japan Hedged Equity ETF", sector: "Japan Index", type: "index" },
  { ticker: "HEWJ", name: "iShares Currency Hedged MSCI Japan ETF", sector: "Japan Index", type: "index" },
  { ticker: "SCJ", name: "iShares MSCI Japan Small-Cap ETF", sector: "Japan Index", type: "index" },

  // China / Hong Kong Indices
  { ticker: "FXI", name: "iShares China Large-Cap ETF", sector: "China Index", type: "index" },
  { ticker: "KWEB", name: "KraneShares CSI China Internet ETF", sector: "China Index", type: "index" },
  { ticker: "GXC", name: "SPDR S&P China ETF", sector: "China Index", type: "index" },
  { ticker: "ASHR", name: "Xtrackers Harvest CSI 300 China A-Shares ETF", sector: "China Index", type: "index" },
  { ticker: "CNYA", name: "iShares MSCI China A ETF", sector: "China Index", type: "index" },
  { ticker: "FLHK", name: "Franklin FTSE Hong Kong ETF", sector: "Hong Kong Index", type: "index" },
  { ticker: "KBA", name: "KraneShares Bosera MSCI China A 50 Connect ETF", sector: "China Index", type: "index" },
  { ticker: "CXSE", name: "WisdomTree China ex-State-Owned Enterprises Fund", sector: "China Index", type: "index" },

  // India Indices
  { ticker: "SMIN", name: "iShares MSCI India Small-Cap ETF", sector: "India Index", type: "index" },
  { ticker: "EPI", name: "WisdomTree India Earnings Fund", sector: "India Index", type: "index" },
  { ticker: "PIN", name: "Invesco India ETF", sector: "India Index", type: "index" },
  { ticker: "NFTY", name: "First Trust India NIFTY 50 Equal Weight ETF", sector: "India Index", type: "index" },
  { ticker: "DGIN", name: "VanEck Digital India ETF", sector: "India Index", type: "index" },

  // Bond Indices
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", sector: "Bond Index", type: "index" },
  { ticker: "LQD", name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "HYG", name: "iShares iBoxx $ High Yield Corporate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "TIP", name: "iShares TIPS Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "BNDX", name: "Vanguard Total International Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "EMB", name: "iShares J.P. Morgan USD Emerging Markets Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "VCSH", name: "Vanguard Short-Term Corporate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "VGIT", name: "Vanguard Intermediate-Term Treasury ETF", sector: "Bond Index", type: "index" },
  { ticker: "VGSH", name: "Vanguard Short-Term Treasury ETF", sector: "Bond Index", type: "index" },
  { ticker: "VGLT", name: "Vanguard Long-Term Treasury ETF", sector: "Bond Index", type: "index" },
  { ticker: "MUB", name: "iShares National Muni Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "VTEB", name: "Vanguard Tax-Exempt Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "JNK", name: "SPDR Bloomberg High Yield Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "SJNK", name: "SPDR Bloomberg Short Term High Yield Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "FLOT", name: "iShares Floating Rate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "IGIB", name: "iShares 5-10 Year Investment Grade Corporate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "IGSB", name: "iShares 1-5 Year Investment Grade Corporate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "GOVT", name: "iShares U.S. Treasury Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "SCHO", name: "Schwab Short-Term U.S. Treasury ETF", sector: "Bond Index", type: "index" },
  { ticker: "SCHR", name: "Schwab Intermediate-Term U.S. Treasury ETF", sector: "Bond Index", type: "index" },
  { ticker: "SCHZ", name: "Schwab U.S. Aggregate Bond ETF", sector: "Bond Index", type: "index" },
  { ticker: "SPAB", name: "SPDR Portfolio Aggregate Bond ETF", sector: "Bond Index", type: "index" },

  // Commodity Indices
  { ticker: "GLD", name: "SPDR Gold Shares", sector: "Commodity Index", type: "index" },
  { ticker: "IAU", name: "iShares Gold Trust", sector: "Commodity Index", type: "index" },
  { ticker: "SLV", name: "iShares Silver Trust", sector: "Commodity Index", type: "index" },
  { ticker: "GDX", name: "VanEck Gold Miners ETF", sector: "Commodity Index", type: "index" },
  { ticker: "GDXJ", name: "VanEck Junior Gold Miners ETF", sector: "Commodity Index", type: "index" },
  { ticker: "USO", name: "United States Oil Fund", sector: "Commodity Index", type: "index" },
  { ticker: "UNG", name: "United States Natural Gas Fund", sector: "Commodity Index", type: "index" },
  { ticker: "DBA", name: "Invesco DB Agriculture Fund", sector: "Commodity Index", type: "index" },
  { ticker: "DBC", name: "Invesco DB Commodity Index Tracking Fund", sector: "Commodity Index", type: "index" },
  { ticker: "GSG", name: "iShares S&P GSCI Commodity-Indexed Trust", sector: "Commodity Index", type: "index" },
  { ticker: "PDBC", name: "Invesco Optimum Yield Diversified Commodity Strategy ETF", sector: "Commodity Index", type: "index" },
  { ticker: "PPLT", name: "abrdn Physical Platinum Shares ETF", sector: "Commodity Index", type: "index" },
  { ticker: "PALL", name: "abrdn Physical Palladium Shares ETF", sector: "Commodity Index", type: "index" },
  { ticker: "CPER", name: "United States Copper Index Fund", sector: "Commodity Index", type: "index" },
  { ticker: "WEAT", name: "Teucrium Wheat Fund", sector: "Commodity Index", type: "index" },
  { ticker: "CORN", name: "Teucrium Corn Fund", sector: "Commodity Index", type: "index" },
  { ticker: "SOYB", name: "Teucrium Soybean Fund", sector: "Commodity Index", type: "index" },
  { ticker: "GLDM", name: "SPDR Gold MiniShares Trust", sector: "Commodity Index", type: "index" },
  { ticker: "SGOL", name: "abrdn Physical Gold Shares ETF", sector: "Commodity Index", type: "index" },
  { ticker: "OUNZ", name: "VanEck Merk Gold Trust", sector: "Commodity Index", type: "index" },

  // Real Estate Indices
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "IYR", name: "iShares U.S. Real Estate ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR Fund", sector: "Real Estate Index", type: "index" },
  { ticker: "RWR", name: "SPDR Dow Jones REIT ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "SCHH", name: "Schwab U.S. REIT ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "REM", name: "iShares Mortgage Real Estate ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "RWX", name: "SPDR Dow Jones International Real Estate ETF", sector: "Real Estate Index", type: "index" },
  { ticker: "IFGL", name: "iShares International Developed Real Estate ETF", sector: "Real Estate Index", type: "index" },

  // Thematic / Factor Indices
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "Thematic Index", type: "index" },
  { ticker: "ARKG", name: "ARK Genomic Revolution ETF", sector: "Thematic Index", type: "index" },
  { ticker: "ARKW", name: "ARK Next Generation Internet ETF", sector: "Thematic Index", type: "index" },
  { ticker: "ARKF", name: "ARK Fintech Innovation ETF", sector: "Thematic Index", type: "index" },
  { ticker: "ARKQ", name: "ARK Autonomous Technology & Robotics ETF", sector: "Thematic Index", type: "index" },
  { ticker: "BOTZ", name: "Global X Robotics & Artificial Intelligence ETF", sector: "Thematic Index", type: "index" },
  { ticker: "AIQ", name: "Global X Artificial Intelligence & Technology ETF", sector: "Thematic Index", type: "index" },
  { ticker: "DRIV", name: "Global X Autonomous & Electric Vehicles ETF", sector: "Thematic Index", type: "index" },
  { ticker: "LIT", name: "Global X Lithium & Battery Tech ETF", sector: "Thematic Index", type: "index" },
  { ticker: "HACK", name: "ETFMG Prime Cyber Security ETF", sector: "Thematic Index", type: "index" },
  { ticker: "CIBR", name: "First Trust Nasdaq Cybersecurity ETF", sector: "Thematic Index", type: "index" },
  { ticker: "BUG", name: "Global X Cybersecurity ETF", sector: "Thematic Index", type: "index" },
  { ticker: "CLOU", name: "Global X Cloud Computing ETF", sector: "Thematic Index", type: "index" },
  { ticker: "SKYY", name: "First Trust Cloud Computing ETF", sector: "Thematic Index", type: "index" },
  { ticker: "WCLD", name: "WisdomTree Cloud Computing Fund", sector: "Thematic Index", type: "index" },
  { ticker: "FINX", name: "Global X FinTech ETF", sector: "Thematic Index", type: "index" },
  { ticker: "SNSR", name: "Global X Internet of Things ETF", sector: "Thematic Index", type: "index" },
  { ticker: "HERO", name: "Global X Video Games & Esports ETF", sector: "Thematic Index", type: "index" },
  { ticker: "SOCL", name: "Global X Social Media ETF", sector: "Thematic Index", type: "index" },
  { ticker: "EBIZ", name: "Global X E-commerce ETF", sector: "Thematic Index", type: "index" },
  { ticker: "EDOC", name: "Global X Telemedicine & Digital Health ETF", sector: "Thematic Index", type: "index" },
  { ticker: "GNOM", name: "Global X Genomics & Biotechnology ETF", sector: "Thematic Index", type: "index" },
  { ticker: "PAVE", name: "Global X U.S. Infrastructure Development ETF", sector: "Thematic Index", type: "index" },
  { ticker: "JETS", name: "U.S. Global Jets ETF", sector: "Thematic Index", type: "index" },
  { ticker: "BLOK", name: "Amplify Transformational Data Sharing ETF", sector: "Thematic Index", type: "index" },
  { ticker: "BATT", name: "Amplify Lithium & Battery Technology ETF", sector: "Thematic Index", type: "index" },
  { ticker: "MOON", name: "Direxion Moonshot Innovators ETF", sector: "Thematic Index", type: "index" },
  { ticker: "BUZZ", name: "VanEck Social Sentiment ETF", sector: "Thematic Index", type: "index" },
  { ticker: "IBIT", name: "iShares Bitcoin Trust ETF", sector: "Crypto Index", type: "index" },
  { ticker: "BITO", name: "ProShares Bitcoin Strategy ETF", sector: "Crypto Index", type: "index" },
  { ticker: "ETHE", name: "Grayscale Ethereum Trust ETF", sector: "Crypto Index", type: "index" },
  { ticker: "GBTC", name: "Grayscale Bitcoin Trust ETF", sector: "Crypto Index", type: "index" },
  { ticker: "FBTC", name: "Fidelity Wise Origin Bitcoin Fund", sector: "Crypto Index", type: "index" },
  { ticker: "BITB", name: "Bitwise Bitcoin ETF", sector: "Crypto Index", type: "index" },

  // Clean Energy / Climate Indices
  { ticker: "ICLN", name: "iShares Global Clean Energy ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "TAN", name: "Invesco Solar ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "FAN", name: "First Trust Global Wind Energy ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "QCLN", name: "First Trust NASDAQ Clean Edge Green Energy ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "PBW", name: "Invesco WilderHill Clean Energy ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "ACES", name: "ALPS Clean Energy ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "CNRG", name: "SPDR S&P Kensho Clean Power ETF", sector: "Clean Energy Index", type: "index" },
  { ticker: "SMOG", name: "VanEck Low Carbon Energy ETF", sector: "Clean Energy Index", type: "index" },

  // Volatility / Strategy Indices
  { ticker: "VIXY", name: "ProShares VIX Short-Term Futures ETF", sector: "Volatility Index", type: "index" },
  { ticker: "UVXY", name: "ProShares Ultra VIX Short-Term Futures ETF", sector: "Volatility Index", type: "index" },
  { ticker: "SVXY", name: "ProShares Short VIX Short-Term Futures ETF", sector: "Volatility Index", type: "index" },
  { ticker: "TAIL", name: "Cambria Tail Risk ETF", sector: "Volatility Index", type: "index" },

  // Multi-Asset / Balanced Indices
  { ticker: "AOR", name: "iShares Core Growth Allocation ETF", sector: "Multi-Asset Index", type: "index" },
  { ticker: "AOM", name: "iShares Core Moderate Allocation ETF", sector: "Multi-Asset Index", type: "index" },
  { ticker: "AOA", name: "iShares Core Aggressive Allocation ETF", sector: "Multi-Asset Index", type: "index" },
  { ticker: "AOK", name: "iShares Core Conservative Allocation ETF", sector: "Multi-Asset Index", type: "index" },
  { ticker: "GAL", name: "SPDR SSgA Global Allocation ETF", sector: "Multi-Asset Index", type: "index" },

  // Frontier / Exotic Indices
  { ticker: "FM", name: "iShares MSCI Frontier and Select EM ETF", sector: "Frontier Markets", type: "index" },
  { ticker: "FRN", name: "Invesco Frontier Markets ETF", sector: "Frontier Markets", type: "index" },
  { ticker: "GUR", name: "SPDR S&P Emerging Europe ETF", sector: "Emerging Markets", type: "index" },
  { ticker: "GMF", name: "SPDR S&P Emerging Asia Pacific ETF", sector: "Emerging Markets", type: "index" },
  { ticker: "GML", name: "SPDR S&P Emerging Latin America ETF", sector: "LATAM Index", type: "index" },
  { ticker: "MES", name: "iShares MSCI Emerging Markets Small-Cap ETF", sector: "Emerging Markets", type: "index" },

  // Dividend / Income Indices
  { ticker: "HDV", name: "iShares Core High Dividend ETF", sector: "Dividend Index", type: "index" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF", sector: "Dividend Index", type: "index" },
  { ticker: "SPYD", name: "SPDR Portfolio S&P 500 High Dividend ETF", sector: "Dividend Index", type: "index" },
  { ticker: "SPHD", name: "Invesco S&P 500 High Dividend Low Volatility ETF", sector: "Dividend Index", type: "index" },
  { ticker: "FVD", name: "First Trust Value Line Dividend Index Fund", sector: "Dividend Index", type: "index" },
  { ticker: "DGRO", name: "iShares Core Dividend Growth ETF", sector: "Dividend Index", type: "index" },
  { ticker: "DGRW", name: "WisdomTree U.S. Quality Dividend Growth Fund", sector: "Dividend Index", type: "index" },
  { ticker: "RDVY", name: "First Trust Rising Dividend Achievers ETF", sector: "Dividend Index", type: "index" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", sector: "Income Index", type: "index" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", sector: "Income Index", type: "index" },
  { ticker: "XYLD", name: "Global X S&P 500 Covered Call ETF", sector: "Income Index", type: "index" },
  { ticker: "QYLD", name: "Global X NASDAQ 100 Covered Call ETF", sector: "Income Index", type: "index" },
  { ticker: "DIVO", name: "Amplify CWP Enhanced Dividend Income ETF", sector: "Income Index", type: "index" },
  { ticker: "NUSI", name: "Nationwide Nasdaq-100 Risk-Managed Income ETF", sector: "Income Index", type: "index" },

  // Canadian Indices
  { ticker: "EWC", name: "iShares MSCI Canada ETF", sector: "North America Index", type: "index" },
  { ticker: "BBCA", name: "JPMorgan BetaBuilders Canada ETF", sector: "North America Index", type: "index" },

  // Leveraged Indices
  { ticker: "SSO", name: "ProShares Ultra S&P 500", sector: "Leveraged Index", type: "index" },
  { ticker: "QLD", name: "ProShares Ultra QQQ", sector: "Leveraged Index", type: "index" },
  { ticker: "TQQQ", name: "ProShares UltraPro QQQ", sector: "Leveraged Index", type: "index" },
  { ticker: "UPRO", name: "ProShares UltraPro S&P 500", sector: "Leveraged Index", type: "index" },
  { ticker: "SQQQ", name: "ProShares UltraPro Short QQQ", sector: "Leveraged Index", type: "index" },
  { ticker: "SPXU", name: "ProShares UltraPro Short S&P 500", sector: "Leveraged Index", type: "index" },
  { ticker: "SDS", name: "ProShares UltraShort S&P 500", sector: "Leveraged Index", type: "index" },
  { ticker: "SH", name: "ProShares Short S&P 500", sector: "Inverse Index", type: "index" },
  { ticker: "PSQ", name: "ProShares Short QQQ", sector: "Inverse Index", type: "index" },
  { ticker: "DOG", name: "ProShares Short Dow 30", sector: "Inverse Index", type: "index" },
  { ticker: "RWM", name: "ProShares Short Russell 2000", sector: "Inverse Index", type: "index" },
];
