import { AssetEntry } from "./types";

// UK — London Stock Exchange (.L)
const ukStocks: AssetEntry[] = [
  { ticker: "SHEL.L", name: "Shell plc", sector: "Energy", type: "stock" },
  { ticker: "AZN.L", name: "AstraZeneca plc", sector: "Healthcare", type: "stock" },
  { ticker: "HSBA.L", name: "HSBC Holdings", sector: "Finance", type: "stock" },
  { ticker: "ULVR.L", name: "Unilever plc", sector: "Consumer", type: "stock" },
  { ticker: "BP.L", name: "BP plc", sector: "Energy", type: "stock" },
  { ticker: "GSK.L", name: "GSK plc", sector: "Healthcare", type: "stock" },
  { ticker: "RIO.L", name: "Rio Tinto plc", sector: "Materials", type: "stock" },
  { ticker: "BATS.L", name: "British American Tobacco", sector: "Consumer", type: "stock" },
  { ticker: "DGE.L", name: "Diageo plc", sector: "Consumer", type: "stock" },
  { ticker: "LSEG.L", name: "London Stock Exchange Group", sector: "Finance", type: "stock" },
  { ticker: "REL.L", name: "RELX plc", sector: "Industrials", type: "stock" },
  { ticker: "AAL.L", name: "Anglo American plc", sector: "Materials", type: "stock" },
  { ticker: "GLEN.L", name: "Glencore plc", sector: "Materials", type: "stock" },
  { ticker: "VOD.L", name: "Vodafone Group", sector: "Telecom", type: "stock" },
  { ticker: "BT-A.L", name: "BT Group plc", sector: "Telecom", type: "stock" },
  { ticker: "NG.L", name: "National Grid plc", sector: "Utilities", type: "stock" },
  { ticker: "BA.L", name: "BAE Systems plc", sector: "Industrials", type: "stock" },
  { ticker: "RR.L", name: "Rolls-Royce Holdings", sector: "Industrials", type: "stock" },
  { ticker: "LLOY.L", name: "Lloyds Banking Group", sector: "Finance", type: "stock" },
  { ticker: "BARC.L", name: "Barclays plc", sector: "Finance", type: "stock" },
  { ticker: "NWG.L", name: "NatWest Group", sector: "Finance", type: "stock" },
  { ticker: "STAN.L", name: "Standard Chartered", sector: "Finance", type: "stock" },
  { ticker: "PRU.L", name: "Prudential plc", sector: "Finance", type: "stock" },
  { ticker: "LGEN.L", name: "Legal & General Group", sector: "Finance", type: "stock" },
  { ticker: "AV.L", name: "Aviva plc", sector: "Finance", type: "stock" },
  { ticker: "IMB.L", name: "Imperial Brands", sector: "Consumer", type: "stock" },
  { ticker: "ANTO.L", name: "Antofagasta plc", sector: "Materials", type: "stock" },
  { ticker: "WPP.L", name: "WPP plc", sector: "Communication", type: "stock" },
  { ticker: "CRH.L", name: "CRH plc", sector: "Materials", type: "stock" },
  { ticker: "EXPN.L", name: "Experian plc", sector: "Technology", type: "stock" },
  { ticker: "SMT.L", name: "Scottish Mortgage Trust", sector: "Finance", type: "stock" },
  { ticker: "SGE.L", name: "Sage Group", sector: "Technology", type: "stock" },
  { ticker: "ABF.L", name: "Associated British Foods", sector: "Consumer", type: "stock" },
  { ticker: "CPG.L", name: "Compass Group", sector: "Consumer", type: "stock" },
  { ticker: "IHG.L", name: "InterContinental Hotels", sector: "Consumer", type: "stock" },
  { ticker: "TSCO.L", name: "Tesco plc", sector: "Consumer", type: "stock" },
  { ticker: "SBRY.L", name: "Sainsbury's", sector: "Consumer", type: "stock" },
  { ticker: "MKS.L", name: "Marks & Spencer", sector: "Consumer", type: "stock" },
  { ticker: "OCDO.L", name: "Ocado Group", sector: "Technology", type: "stock" },
  { ticker: "JD.L", name: "JD Sports Fashion", sector: "Consumer", type: "stock" },
  { ticker: "FRAS.L", name: "Frasers Group", sector: "Consumer", type: "stock" },
  { ticker: "AHT.L", name: "Ashtead Group", sector: "Industrials", type: "stock" },
  { ticker: "RKT.L", name: "Reckitt Benckiser", sector: "Consumer", type: "stock" },
  { ticker: "MNDI.L", name: "Mondi plc", sector: "Materials", type: "stock" },
  { ticker: "PSON.L", name: "Pearson plc", sector: "Communication", type: "stock" },
  { ticker: "III.L", name: "3i Group", sector: "Finance", type: "stock" },
  { ticker: "SVT.L", name: "Severn Trent", sector: "Utilities", type: "stock" },
  { ticker: "UU.L", name: "United Utilities", sector: "Utilities", type: "stock" },
  { ticker: "SSE.L", name: "SSE plc", sector: "Utilities", type: "stock" },
  { ticker: "DARK.L", name: "Darktrace plc", sector: "Technology", type: "stock" },
];

// Germany — Frankfurt (.DE)
const deStocks: AssetEntry[] = [
  { ticker: "SAP.DE", name: "SAP SE", sector: "Technology", type: "stock" },
  { ticker: "SIE.DE", name: "Siemens AG", sector: "Industrials", type: "stock" },
  { ticker: "ALV.DE", name: "Allianz SE", sector: "Finance", type: "stock" },
  { ticker: "DTE.DE", name: "Deutsche Telekom AG", sector: "Telecom", type: "stock" },
  { ticker: "BAS.DE", name: "BASF SE", sector: "Materials", type: "stock" },
  { ticker: "MBG.DE", name: "Mercedes-Benz Group", sector: "Automotive", type: "stock" },
  { ticker: "BMW.DE", name: "BMW AG", sector: "Automotive", type: "stock" },
  { ticker: "VOW3.DE", name: "Volkswagen AG", sector: "Automotive", type: "stock" },
  { ticker: "MRK.DE", name: "Merck KGaA", sector: "Healthcare", type: "stock" },
  { ticker: "IFX.DE", name: "Infineon Technologies", sector: "Technology", type: "stock" },
  { ticker: "ADS.DE", name: "adidas AG", sector: "Consumer", type: "stock" },
  { ticker: "DBK.DE", name: "Deutsche Bank AG", sector: "Finance", type: "stock" },
  { ticker: "MUV2.DE", name: "Munich Re", sector: "Finance", type: "stock" },
  { ticker: "RWE.DE", name: "RWE AG", sector: "Utilities", type: "stock" },
  { ticker: "DHL.DE", name: "DHL Group", sector: "Industrials", type: "stock" },
  { ticker: "HEN3.DE", name: "Henkel AG", sector: "Consumer", type: "stock" },
  { ticker: "BEI.DE", name: "Beiersdorf AG", sector: "Consumer", type: "stock" },
  { ticker: "FRE.DE", name: "Fresenius SE", sector: "Healthcare", type: "stock" },
  { ticker: "CON.DE", name: "Continental AG", sector: "Automotive", type: "stock" },
  { ticker: "HNR1.DE", name: "Hannover Rück SE", sector: "Finance", type: "stock" },
  { ticker: "PAH3.DE", name: "Porsche Automobil Holding", sector: "Automotive", type: "stock" },
  { ticker: "ZAL.DE", name: "Zalando SE", sector: "Consumer", type: "stock" },
  { ticker: "1COV.DE", name: "Covestro AG", sector: "Materials", type: "stock" },
  { ticker: "ENR.DE", name: "Siemens Energy AG", sector: "Energy", type: "stock" },
  { ticker: "MTX.DE", name: "MTU Aero Engines", sector: "Industrials", type: "stock" },
  { ticker: "SHL.DE", name: "Siemens Healthineers", sector: "Healthcare", type: "stock" },
  { ticker: "DTG.DE", name: "Daimler Truck Holding", sector: "Industrials", type: "stock" },
  { ticker: "QIA.DE", name: "QIAGEN N.V.", sector: "Healthcare", type: "stock" },
  { ticker: "SY1.DE", name: "Symrise AG", sector: "Materials", type: "stock" },
  { ticker: "PUM.DE", name: "Puma SE", sector: "Consumer", type: "stock" },
];

// France — Euronext Paris (.PA)
const frStocks: AssetEntry[] = [
  { ticker: "MC.PA", name: "LVMH Moët Hennessy", sector: "Consumer", type: "stock" },
  { ticker: "OR.PA", name: "L'Oréal SA", sector: "Consumer", type: "stock" },
  { ticker: "TTE.PA", name: "TotalEnergies SE", sector: "Energy", type: "stock" },
  { ticker: "SAN.PA", name: "Sanofi SA", sector: "Healthcare", type: "stock" },
  { ticker: "AI.PA", name: "Air Liquide SA", sector: "Materials", type: "stock" },
  { ticker: "BNP.PA", name: "BNP Paribas SA", sector: "Finance", type: "stock" },
  { ticker: "SU.PA", name: "Schneider Electric", sector: "Industrials", type: "stock" },
  { ticker: "AIR.PA", name: "Airbus SE", sector: "Industrials", type: "stock" },
  { ticker: "KER.PA", name: "Kering SA", sector: "Consumer", type: "stock" },
  { ticker: "DG.PA", name: "Vinci SA", sector: "Industrials", type: "stock" },
  { ticker: "RI.PA", name: "Pernod Ricard SA", sector: "Consumer", type: "stock" },
  { ticker: "BN.PA", name: "Danone SA", sector: "Consumer", type: "stock" },
  { ticker: "CS.PA", name: "AXA SA", sector: "Finance", type: "stock" },
  { ticker: "CAP.PA", name: "Capgemini SE", sector: "Technology", type: "stock" },
  { ticker: "HO.PA", name: "Thales SA", sector: "Industrials", type: "stock" },
  { ticker: "ORA.PA", name: "Orange SA", sector: "Telecom", type: "stock" },
  { ticker: "SGO.PA", name: "Saint-Gobain SA", sector: "Materials", type: "stock" },
  { ticker: "GLE.PA", name: "Société Générale", sector: "Finance", type: "stock" },
  { ticker: "CA.PA", name: "Carrefour SA", sector: "Consumer", type: "stock" },
  { ticker: "EN.PA", name: "Bouygues SA", sector: "Industrials", type: "stock" },
  { ticker: "ML.PA", name: "Michelin SA", sector: "Consumer", type: "stock" },
  { ticker: "RNO.PA", name: "Renault SA", sector: "Automotive", type: "stock" },
  { ticker: "PUB.PA", name: "Publicis Groupe", sector: "Communication", type: "stock" },
  { ticker: "VIV.PA", name: "Vivendi SE", sector: "Communication", type: "stock" },
  { ticker: "SAF.PA", name: "Safran SA", sector: "Industrials", type: "stock" },
  { ticker: "DSY.PA", name: "Dassault Systèmes", sector: "Technology", type: "stock" },
  { ticker: "RMS.PA", name: "Hermès International", sector: "Consumer", type: "stock" },
  { ticker: "EL.PA", name: "EssilorLuxottica", sector: "Healthcare", type: "stock" },
  { ticker: "LR.PA", name: "Legrand SA", sector: "Industrials", type: "stock" },
  { ticker: "STM.PA", name: "STMicroelectronics", sector: "Technology", type: "stock" },
];

// Spain — Madrid (.MC)
const esStocks: AssetEntry[] = [
  { ticker: "SAN.MC", name: "Banco Santander", sector: "Finance", type: "stock" },
  { ticker: "BBVA.MC", name: "BBVA SA", sector: "Finance", type: "stock" },
  { ticker: "ITX.MC", name: "Inditex SA", sector: "Consumer", type: "stock" },
  { ticker: "IBE.MC", name: "Iberdrola SA", sector: "Utilities", type: "stock" },
  { ticker: "TEF.MC", name: "Telefónica SA", sector: "Telecom", type: "stock" },
  { ticker: "REP.MC", name: "Repsol SA", sector: "Energy", type: "stock" },
  { ticker: "FER.MC", name: "Ferrovial SE", sector: "Industrials", type: "stock" },
  { ticker: "AMS.MC", name: "Amadeus IT Group", sector: "Technology", type: "stock" },
  { ticker: "CLNX.MC", name: "Cellnex Telecom", sector: "Telecom", type: "stock" },
  { ticker: "ENG.MC", name: "Enagás SA", sector: "Utilities", type: "stock" },
  { ticker: "ACS.MC", name: "ACS Group", sector: "Industrials", type: "stock" },
  { ticker: "MAP.MC", name: "MAPFRE SA", sector: "Finance", type: "stock" },
  { ticker: "CABK.MC", name: "CaixaBank SA", sector: "Finance", type: "stock" },
  { ticker: "GRF.MC", name: "Grifols SA", sector: "Healthcare", type: "stock" },
  { ticker: "RED.MC", name: "Redeia Corporación", sector: "Utilities", type: "stock" },
  { ticker: "MRL.MC", name: "Merlin Properties", sector: "Finance", type: "stock" },
  { ticker: "AENA.MC", name: "Aena SME SA", sector: "Industrials", type: "stock" },
  { ticker: "LOG.MC", name: "Logista SA", sector: "Industrials", type: "stock" },
  { ticker: "BKT.MC", name: "Bankinter SA", sector: "Finance", type: "stock" },
  { ticker: "SAB.MC", name: "Banco Sabadell", sector: "Finance", type: "stock" },
];

// Italy — Milan (.MI)
const itStocks: AssetEntry[] = [
  { ticker: "ENI.MI", name: "Eni SpA", sector: "Energy", type: "stock" },
  { ticker: "ENEL.MI", name: "Enel SpA", sector: "Utilities", type: "stock" },
  { ticker: "ISP.MI", name: "Intesa Sanpaolo", sector: "Finance", type: "stock" },
  { ticker: "UCG.MI", name: "UniCredit SpA", sector: "Finance", type: "stock" },
  { ticker: "RACE.MI", name: "Ferrari N.V.", sector: "Automotive", type: "stock" },
  { ticker: "G.MI", name: "Assicurazioni Generali", sector: "Finance", type: "stock" },
  { ticker: "STLA.MI", name: "Stellantis N.V.", sector: "Automotive", type: "stock" },
  { ticker: "TIT.MI", name: "Telecom Italia", sector: "Telecom", type: "stock" },
  { ticker: "PRY.MI", name: "Prysmian SpA", sector: "Industrials", type: "stock" },
  { ticker: "LDO.MI", name: "Leonardo SpA", sector: "Industrials", type: "stock" },
  { ticker: "SPM.MI", name: "Saipem SpA", sector: "Energy", type: "stock" },
  { ticker: "BAMI.MI", name: "Banco BPM SpA", sector: "Finance", type: "stock" },
  { ticker: "MB.MI", name: "Mediobanca SpA", sector: "Finance", type: "stock" },
  { ticker: "CPR.MI", name: "Campari Group", sector: "Consumer", type: "stock" },
  { ticker: "TEN.MI", name: "Tenaris SA", sector: "Energy", type: "stock" },
  { ticker: "AMP.MI", name: "Amplifon SpA", sector: "Healthcare", type: "stock" },
  { ticker: "REC.MI", name: "Recordati SpA", sector: "Healthcare", type: "stock" },
  { ticker: "MONC.MI", name: "Moncler SpA", sector: "Consumer", type: "stock" },
  { ticker: "FBK.MI", name: "FinecoBank SpA", sector: "Finance", type: "stock" },
  { ticker: "HER.MI", name: "Hera SpA", sector: "Utilities", type: "stock" },
];

// Netherlands — Amsterdam (.AS)
const nlStocks: AssetEntry[] = [
  { ticker: "ASML.AS", name: "ASML Holding", sector: "Technology", type: "stock" },
  { ticker: "PHIA.AS", name: "Koninklijke Philips", sector: "Healthcare", type: "stock" },
  { ticker: "INGA.AS", name: "ING Group N.V.", sector: "Finance", type: "stock" },
  { ticker: "AD.AS", name: "Ahold Delhaize", sector: "Consumer", type: "stock" },
  { ticker: "UNA.AS", name: "Unilever N.V.", sector: "Consumer", type: "stock" },
  { ticker: "HEIA.AS", name: "Heineken N.V.", sector: "Consumer", type: "stock" },
  { ticker: "WKL.AS", name: "Wolters Kluwer", sector: "Technology", type: "stock" },
  { ticker: "DSM.AS", name: "DSM-Firmenich AG", sector: "Materials", type: "stock" },
  { ticker: "KPN.AS", name: "KPN N.V.", sector: "Telecom", type: "stock" },
  { ticker: "AGN.AS", name: "Aegon N.V.", sector: "Finance", type: "stock" },
  { ticker: "RAND.AS", name: "Randstad N.V.", sector: "Industrials", type: "stock" },
  { ticker: "NN.AS", name: "NN Group N.V.", sector: "Finance", type: "stock" },
  { ticker: "ASM.AS", name: "ASM International", sector: "Technology", type: "stock" },
  { ticker: "BESI.AS", name: "BE Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "AKZA.AS", name: "Akzo Nobel N.V.", sector: "Materials", type: "stock" },
];

// Switzerland — SIX (.SW)
const chStocks: AssetEntry[] = [
  { ticker: "NESN.SW", name: "Nestlé SA", sector: "Consumer", type: "stock" },
  { ticker: "ROG.SW", name: "Roche Holding AG", sector: "Healthcare", type: "stock" },
  { ticker: "NOVN.SW", name: "Novartis AG", sector: "Healthcare", type: "stock" },
  { ticker: "ZURN.SW", name: "Zurich Insurance", sector: "Finance", type: "stock" },
  { ticker: "UBSG.SW", name: "UBS Group AG", sector: "Finance", type: "stock" },
  { ticker: "ABBN.SW", name: "ABB Ltd", sector: "Industrials", type: "stock" },
  { ticker: "CSGN.SW", name: "Holcim Group", sector: "Materials", type: "stock" },
  { ticker: "SREN.SW", name: "Swiss Re AG", sector: "Finance", type: "stock" },
  { ticker: "LONN.SW", name: "Lonza Group AG", sector: "Healthcare", type: "stock" },
  { ticker: "GIVN.SW", name: "Givaudan SA", sector: "Materials", type: "stock" },
  { ticker: "SIKA.SW", name: "Sika AG", sector: "Materials", type: "stock" },
  { ticker: "GEBN.SW", name: "Geberit AG", sector: "Industrials", type: "stock" },
  { ticker: "SCMN.SW", name: "Swisscom AG", sector: "Telecom", type: "stock" },
  { ticker: "SLHN.SW", name: "Swiss Life Holding", sector: "Finance", type: "stock" },
  { ticker: "BAER.SW", name: "Julius Bär Group", sector: "Finance", type: "stock" },
];

// Japan — Tokyo (.T)
const jpStocks: AssetEntry[] = [
  { ticker: "7203.T", name: "Toyota Motor Corp", sector: "Automotive", type: "stock" },
  { ticker: "6758.T", name: "Sony Group Corp", sector: "Technology", type: "stock" },
  { ticker: "6861.T", name: "Keyence Corp", sector: "Technology", type: "stock" },
  { ticker: "9984.T", name: "SoftBank Group", sector: "Technology", type: "stock" },
  { ticker: "6902.T", name: "DENSO Corp", sector: "Automotive", type: "stock" },
  { ticker: "8306.T", name: "Mitsubishi UFJ Financial", sector: "Finance", type: "stock" },
  { ticker: "9433.T", name: "KDDI Corp", sector: "Telecom", type: "stock" },
  { ticker: "6501.T", name: "Hitachi Ltd", sector: "Technology", type: "stock" },
  { ticker: "7974.T", name: "Nintendo Co Ltd", sector: "Technology", type: "stock" },
  { ticker: "6098.T", name: "Recruit Holdings", sector: "Industrials", type: "stock" },
  { ticker: "4502.T", name: "Takeda Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "8035.T", name: "Tokyo Electron Ltd", sector: "Technology", type: "stock" },
  { ticker: "6367.T", name: "Daikin Industries", sector: "Industrials", type: "stock" },
  { ticker: "9432.T", name: "NTT Corp", sector: "Telecom", type: "stock" },
  { ticker: "7267.T", name: "Honda Motor Co", sector: "Automotive", type: "stock" },
  { ticker: "4063.T", name: "Shin-Etsu Chemical", sector: "Materials", type: "stock" },
  { ticker: "6594.T", name: "Nidec Corp", sector: "Industrials", type: "stock" },
  { ticker: "8058.T", name: "Mitsubishi Corp", sector: "Diversified", type: "stock" },
  { ticker: "8001.T", name: "ITOCHU Corp", sector: "Diversified", type: "stock" },
  { ticker: "8031.T", name: "Mitsui & Co", sector: "Diversified", type: "stock" },
  { ticker: "6954.T", name: "FANUC Corp", sector: "Industrials", type: "stock" },
  { ticker: "4519.T", name: "Chugai Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "6857.T", name: "Advantest Corp", sector: "Technology", type: "stock" },
  { ticker: "7741.T", name: "HOYA Corp", sector: "Healthcare", type: "stock" },
  { ticker: "9983.T", name: "Fast Retailing", sector: "Consumer", type: "stock" },
  { ticker: "4568.T", name: "Daiichi Sankyo", sector: "Healthcare", type: "stock" },
  { ticker: "6981.T", name: "Murata Manufacturing", sector: "Technology", type: "stock" },
  { ticker: "6971.T", name: "Kyocera Corp", sector: "Technology", type: "stock" },
  { ticker: "8766.T", name: "Tokio Marine Holdings", sector: "Finance", type: "stock" },
  { ticker: "3382.T", name: "Seven & i Holdings", sector: "Consumer", type: "stock" },
  { ticker: "2914.T", name: "Japan Tobacco Inc", sector: "Consumer", type: "stock" },
  { ticker: "6503.T", name: "Mitsubishi Electric", sector: "Technology", type: "stock" },
  { ticker: "7733.T", name: "Olympus Corp", sector: "Healthcare", type: "stock" },
  { ticker: "6301.T", name: "Komatsu Ltd", sector: "Industrials", type: "stock" },
  { ticker: "7751.T", name: "Canon Inc", sector: "Technology", type: "stock" },
];

// Hong Kong (.HK)
const hkStocks: AssetEntry[] = [
  { ticker: "0700.HK", name: "Tencent Holdings", sector: "Technology", type: "stock" },
  { ticker: "9988.HK", name: "Alibaba Group", sector: "Technology", type: "stock" },
  { ticker: "1299.HK", name: "AIA Group Ltd", sector: "Finance", type: "stock" },
  { ticker: "0005.HK", name: "HSBC Holdings", sector: "Finance", type: "stock" },
  { ticker: "0941.HK", name: "China Mobile", sector: "Telecom", type: "stock" },
  { ticker: "3690.HK", name: "Meituan", sector: "Technology", type: "stock" },
  { ticker: "2318.HK", name: "Ping An Insurance", sector: "Finance", type: "stock" },
  { ticker: "1810.HK", name: "Xiaomi Corp", sector: "Technology", type: "stock" },
  { ticker: "0388.HK", name: "Hong Kong Exchanges", sector: "Finance", type: "stock" },
  { ticker: "0002.HK", name: "CLP Holdings", sector: "Utilities", type: "stock" },
  { ticker: "9618.HK", name: "JD.com Inc", sector: "Technology", type: "stock" },
  { ticker: "9999.HK", name: "NetEase Inc", sector: "Technology", type: "stock" },
  { ticker: "0883.HK", name: "CNOOC Ltd", sector: "Energy", type: "stock" },
  { ticker: "1038.HK", name: "CK Infrastructure", sector: "Utilities", type: "stock" },
  { ticker: "0027.HK", name: "Galaxy Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "0016.HK", name: "Sun Hung Kai Properties", sector: "Finance", type: "stock" },
  { ticker: "2269.HK", name: "WuXi Biologics", sector: "Healthcare", type: "stock" },
  { ticker: "0066.HK", name: "MTR Corp", sector: "Industrials", type: "stock" },
  { ticker: "1928.HK", name: "Sands China Ltd", sector: "Consumer", type: "stock" },
  { ticker: "2382.HK", name: "Sunny Optical", sector: "Technology", type: "stock" },
];

// Canada — Toronto (.TO)
const caStocks: AssetEntry[] = [
  { ticker: "RY.TO", name: "Royal Bank of Canada", sector: "Finance", type: "stock" },
  { ticker: "TD.TO", name: "Toronto-Dominion Bank", sector: "Finance", type: "stock" },
  { ticker: "CNR.TO", name: "Canadian National Railway", sector: "Industrials", type: "stock" },
  { ticker: "ENB.TO", name: "Enbridge Inc", sector: "Energy", type: "stock" },
  { ticker: "BN.TO", name: "Brookfield Corp", sector: "Finance", type: "stock" },
  { ticker: "CP.TO", name: "Canadian Pacific Kansas City", sector: "Industrials", type: "stock" },
  { ticker: "BMO.TO", name: "Bank of Montreal", sector: "Finance", type: "stock" },
  { ticker: "BNS.TO", name: "Bank of Nova Scotia", sector: "Finance", type: "stock" },
  { ticker: "SU.TO", name: "Suncor Energy", sector: "Energy", type: "stock" },
  { ticker: "TRI.TO", name: "Thomson Reuters", sector: "Technology", type: "stock" },
  { ticker: "MFC.TO", name: "Manulife Financial", sector: "Finance", type: "stock" },
  { ticker: "ATD.TO", name: "Alimentation Couche-Tard", sector: "Consumer", type: "stock" },
  { ticker: "CSU.TO", name: "Constellation Software", sector: "Technology", type: "stock" },
  { ticker: "ABX.TO", name: "Barrick Gold Corp", sector: "Materials", type: "stock" },
  { ticker: "NTR.TO", name: "Nutrien Ltd", sector: "Materials", type: "stock" },
  { ticker: "WCN.TO", name: "Waste Connections", sector: "Industrials", type: "stock" },
  { ticker: "L.TO", name: "Loblaw Companies", sector: "Consumer", type: "stock" },
  { ticker: "FNV.TO", name: "Franco-Nevada Corp", sector: "Materials", type: "stock" },
  { ticker: "QSR.TO", name: "Restaurant Brands Intl", sector: "Consumer", type: "stock" },
  { ticker: "SHOP.TO", name: "Shopify Inc", sector: "Technology", type: "stock" },
];

// Australia — ASX (.AX)
const auStocks: AssetEntry[] = [
  { ticker: "BHP.AX", name: "BHP Group Ltd", sector: "Materials", type: "stock" },
  { ticker: "CBA.AX", name: "Commonwealth Bank", sector: "Finance", type: "stock" },
  { ticker: "CSL.AX", name: "CSL Limited", sector: "Healthcare", type: "stock" },
  { ticker: "NAB.AX", name: "National Australia Bank", sector: "Finance", type: "stock" },
  { ticker: "WBC.AX", name: "Westpac Banking", sector: "Finance", type: "stock" },
  { ticker: "ANZ.AX", name: "ANZ Group Holdings", sector: "Finance", type: "stock" },
  { ticker: "FMG.AX", name: "Fortescue Metals", sector: "Materials", type: "stock" },
  { ticker: "WES.AX", name: "Wesfarmers Ltd", sector: "Consumer", type: "stock" },
  { ticker: "MQG.AX", name: "Macquarie Group", sector: "Finance", type: "stock" },
  { ticker: "TLS.AX", name: "Telstra Group", sector: "Telecom", type: "stock" },
  { ticker: "WOW.AX", name: "Woolworths Group", sector: "Consumer", type: "stock" },
  { ticker: "RIO.AX", name: "Rio Tinto Ltd", sector: "Materials", type: "stock" },
  { ticker: "GMG.AX", name: "Goodman Group", sector: "Finance", type: "stock" },
  { ticker: "TCL.AX", name: "Transurban Group", sector: "Industrials", type: "stock" },
  { ticker: "ALL.AX", name: "Aristocrat Leisure", sector: "Technology", type: "stock" },
  { ticker: "STO.AX", name: "Santos Ltd", sector: "Energy", type: "stock" },
  { ticker: "WDS.AX", name: "Woodside Energy", sector: "Energy", type: "stock" },
  { ticker: "COL.AX", name: "Coles Group", sector: "Consumer", type: "stock" },
  { ticker: "REA.AX", name: "REA Group Ltd", sector: "Technology", type: "stock" },
  { ticker: "NCM.AX", name: "Newcrest Mining", sector: "Materials", type: "stock" },
];

// South Korea — KRX (.KS)
const krStocks: AssetEntry[] = [
  { ticker: "005930.KS", name: "Samsung Electronics", sector: "Technology", type: "stock" },
  { ticker: "000660.KS", name: "SK Hynix Inc", sector: "Technology", type: "stock" },
  { ticker: "373220.KS", name: "LG Energy Solution", sector: "Industrials", type: "stock" },
  { ticker: "207940.KS", name: "Samsung Biologics", sector: "Healthcare", type: "stock" },
  { ticker: "005380.KS", name: "Hyundai Motor Co", sector: "Automotive", type: "stock" },
  { ticker: "006400.KS", name: "Samsung SDI", sector: "Technology", type: "stock" },
  { ticker: "035420.KS", name: "Naver Corp", sector: "Technology", type: "stock" },
  { ticker: "051910.KS", name: "LG Chem Ltd", sector: "Materials", type: "stock" },
  { ticker: "068270.KS", name: "Celltrion Inc", sector: "Healthcare", type: "stock" },
  { ticker: "035720.KS", name: "Kakao Corp", sector: "Technology", type: "stock" },
  { ticker: "105560.KS", name: "KB Financial Group", sector: "Finance", type: "stock" },
  { ticker: "055550.KS", name: "Shinhan Financial", sector: "Finance", type: "stock" },
  { ticker: "000270.KS", name: "Kia Corp", sector: "Automotive", type: "stock" },
  { ticker: "012330.KS", name: "Hyundai Mobis", sector: "Automotive", type: "stock" },
  { ticker: "028260.KS", name: "Samsung C&T", sector: "Diversified", type: "stock" },
];

// Nordic — Stockholm (.ST), Oslo (.OL), Copenhagen (.CO), Helsinki (.HE)
const nordicStocks: AssetEntry[] = [
  { ticker: "VOLV-B.ST", name: "Volvo AB", sector: "Industrials", type: "stock" },
  { ticker: "ERIC-B.ST", name: "Ericsson AB", sector: "Technology", type: "stock" },
  { ticker: "ATCO-A.ST", name: "Atlas Copco AB", sector: "Industrials", type: "stock" },
  { ticker: "INVE-B.ST", name: "Investor AB", sector: "Finance", type: "stock" },
  { ticker: "SEB-A.ST", name: "SEB AB", sector: "Finance", type: "stock" },
  { ticker: "SAND.ST", name: "Sandvik AB", sector: "Industrials", type: "stock" },
  { ticker: "HM-B.ST", name: "H&M Hennes & Mauritz", sector: "Consumer", type: "stock" },
  { ticker: "ABB.ST", name: "ABB Ltd (Stockholm)", sector: "Industrials", type: "stock" },
  { ticker: "HEXA-B.ST", name: "Hexagon AB", sector: "Technology", type: "stock" },
  { ticker: "SWED-A.ST", name: "Swedbank AB", sector: "Finance", type: "stock" },
  { ticker: "EQNR.OL", name: "Equinor ASA", sector: "Energy", type: "stock" },
  { ticker: "DNB.OL", name: "DNB Bank ASA", sector: "Finance", type: "stock" },
  { ticker: "TEL.OL", name: "Telenor ASA", sector: "Telecom", type: "stock" },
  { ticker: "MOWI.OL", name: "Mowi ASA", sector: "Consumer", type: "stock" },
  { ticker: "ORK.OL", name: "Orkla ASA", sector: "Consumer", type: "stock" },
  { ticker: "YAR.OL", name: "Yara International", sector: "Materials", type: "stock" },
  { ticker: "SALM.OL", name: "SalMar ASA", sector: "Consumer", type: "stock" },
  { ticker: "NOVO-B.CO", name: "Novo Nordisk A/S", sector: "Healthcare", type: "stock" },
  { ticker: "MAERSK-B.CO", name: "A.P. Møller-Mærsk", sector: "Industrials", type: "stock" },
  { ticker: "CARL-B.CO", name: "Carlsberg A/S", sector: "Consumer", type: "stock" },
  { ticker: "VWS.CO", name: "Vestas Wind Systems", sector: "Energy", type: "stock" },
  { ticker: "DSV.CO", name: "DSV A/S", sector: "Industrials", type: "stock" },
  { ticker: "ORSTED.CO", name: "Ørsted A/S", sector: "Energy", type: "stock" },
  { ticker: "DEMANT.CO", name: "Demant A/S", sector: "Healthcare", type: "stock" },
  { ticker: "NESTE.HE", name: "Neste Oyj", sector: "Energy", type: "stock" },
  { ticker: "NOKIA.HE", name: "Nokia Oyj", sector: "Technology", type: "stock" },
  { ticker: "SAMPO.HE", name: "Sampo Oyj", sector: "Finance", type: "stock" },
  { ticker: "UPM.HE", name: "UPM-Kymmene Oyj", sector: "Materials", type: "stock" },
  { ticker: "FORTUM.HE", name: "Fortum Oyj", sector: "Utilities", type: "stock" },
  { ticker: "STERV.HE", name: "Stora Enso Oyj", sector: "Materials", type: "stock" },
];

// Brazil — B3 (.SA)
const brStocks: AssetEntry[] = [
  { ticker: "PETR4.SA", name: "Petrobras SA", sector: "Energy", type: "stock" },
  { ticker: "VALE3.SA", name: "Vale SA", sector: "Materials", type: "stock" },
  { ticker: "ITUB4.SA", name: "Itaú Unibanco", sector: "Finance", type: "stock" },
  { ticker: "BBDC4.SA", name: "Bradesco SA", sector: "Finance", type: "stock" },
  { ticker: "ABEV3.SA", name: "Ambev SA", sector: "Consumer", type: "stock" },
  { ticker: "WEGE3.SA", name: "WEG SA", sector: "Industrials", type: "stock" },
  { ticker: "B3SA3.SA", name: "B3 SA", sector: "Finance", type: "stock" },
  { ticker: "RENT3.SA", name: "Localiza Rent a Car", sector: "Consumer", type: "stock" },
  { ticker: "SUZB3.SA", name: "Suzano SA", sector: "Materials", type: "stock" },
  { ticker: "BBAS3.SA", name: "Banco do Brasil", sector: "Finance", type: "stock" },
  { ticker: "JBSS3.SA", name: "JBS SA", sector: "Consumer", type: "stock" },
  { ticker: "RADL3.SA", name: "Raia Drogasil", sector: "Healthcare", type: "stock" },
  { ticker: "RAIL3.SA", name: "Rumo SA", sector: "Industrials", type: "stock" },
  { ticker: "ELET3.SA", name: "Eletrobras", sector: "Utilities", type: "stock" },
  { ticker: "MGLU3.SA", name: "Magazine Luiza", sector: "Consumer", type: "stock" },
];

// India — BSE (.BO) and NSE (.NS)
const inStocks: AssetEntry[] = [
  { ticker: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", type: "stock" },
  { ticker: "TCS.NS", name: "Tata Consultancy Services", sector: "Technology", type: "stock" },
  { ticker: "INFY.NS", name: "Infosys Ltd", sector: "Technology", type: "stock" },
  { ticker: "HDFCBANK.NS", name: "HDFC Bank Ltd", sector: "Finance", type: "stock" },
  { ticker: "ICICIBANK.NS", name: "ICICI Bank Ltd", sector: "Finance", type: "stock" },
  { ticker: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "Consumer", type: "stock" },
  { ticker: "ITC.NS", name: "ITC Ltd", sector: "Consumer", type: "stock" },
  { ticker: "SBIN.NS", name: "State Bank of India", sector: "Finance", type: "stock" },
  { ticker: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", type: "stock" },
  { ticker: "WIPRO.NS", name: "Wipro Ltd", sector: "Technology", type: "stock" },
  { ticker: "AXISBANK.NS", name: "Axis Bank Ltd", sector: "Finance", type: "stock" },
  { ticker: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Finance", type: "stock" },
  { ticker: "LT.NS", name: "Larsen & Toubro", sector: "Industrials", type: "stock" },
  { ticker: "TATAMOTORS.NS", name: "Tata Motors Ltd", sector: "Automotive", type: "stock" },
  { ticker: "MARUTI.NS", name: "Maruti Suzuki India", sector: "Automotive", type: "stock" },
  { ticker: "SUNPHARMA.NS", name: "Sun Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "TITAN.NS", name: "Titan Company Ltd", sector: "Consumer", type: "stock" },
  { ticker: "ADANIENT.NS", name: "Adani Enterprises", sector: "Diversified", type: "stock" },
  { ticker: "BAJFINANCE.NS", name: "Bajaj Finance Ltd", sector: "Finance", type: "stock" },
  { ticker: "HCLTECH.NS", name: "HCL Technologies", sector: "Technology", type: "stock" },
];

// Taiwan (.TW)
const twStocks: AssetEntry[] = [
  { ticker: "2330.TW", name: "TSMC", sector: "Technology", type: "stock" },
  { ticker: "2317.TW", name: "Hon Hai Precision (Foxconn)", sector: "Technology", type: "stock" },
  { ticker: "2454.TW", name: "MediaTek Inc", sector: "Technology", type: "stock" },
  { ticker: "2881.TW", name: "Fubon Financial", sector: "Finance", type: "stock" },
  { ticker: "2882.TW", name: "Cathay Financial", sector: "Finance", type: "stock" },
  { ticker: "2303.TW", name: "United Microelectronics", sector: "Technology", type: "stock" },
  { ticker: "2412.TW", name: "Chunghwa Telecom", sector: "Telecom", type: "stock" },
  { ticker: "1301.TW", name: "Formosa Plastics", sector: "Materials", type: "stock" },
  { ticker: "2308.TW", name: "Delta Electronics", sector: "Technology", type: "stock" },
  { ticker: "3711.TW", name: "ASE Technology", sector: "Technology", type: "stock" },
];

// Singapore (.SI)
const sgStocks: AssetEntry[] = [
  { ticker: "D05.SI", name: "DBS Group Holdings", sector: "Finance", type: "stock" },
  { ticker: "O39.SI", name: "OCBC Bank", sector: "Finance", type: "stock" },
  { ticker: "U11.SI", name: "United Overseas Bank", sector: "Finance", type: "stock" },
  { ticker: "Z74.SI", name: "Singtel", sector: "Telecom", type: "stock" },
  { ticker: "BN4.SI", name: "Keppel Corp", sector: "Industrials", type: "stock" },
  { ticker: "C6L.SI", name: "Singapore Airlines", sector: "Industrials", type: "stock" },
  { ticker: "A17U.SI", name: "CapitaLand Ascendas REIT", sector: "Finance", type: "stock" },
  { ticker: "C38U.SI", name: "CapitaLand Integrated", sector: "Finance", type: "stock" },
  { ticker: "S68.SI", name: "Singapore Exchange", sector: "Finance", type: "stock" },
  { ticker: "Y92.SI", name: "Thai Beverage PCL", sector: "Consumer", type: "stock" },
];

// International ETFs (various exchanges)
const internationalEtfs: AssetEntry[] = [
  { ticker: "VWRL.L", name: "Vanguard FTSE All-World ETF", sector: "Diversified", type: "etf" },
  { ticker: "ISF.L", name: "iShares Core FTSE 100 ETF", sector: "Diversified", type: "etf" },
  { ticker: "VUSA.L", name: "Vanguard S&P 500 ETF (UK)", sector: "Diversified", type: "etf" },
  { ticker: "CSPX.L", name: "iShares Core S&P 500 (UK)", sector: "Diversified", type: "etf" },
  { ticker: "SWDA.L", name: "iShares Core MSCI World", sector: "Diversified", type: "etf" },
  { ticker: "EQQQ.L", name: "Invesco NASDAQ-100 ETF (UK)", sector: "Technology", type: "etf" },
  { ticker: "VMID.L", name: "Vanguard FTSE 250 ETF", sector: "Diversified", type: "etf" },
  { ticker: "IUIT.L", name: "iShares S&P 500 IT Sector", sector: "Technology", type: "etf" },
  { ticker: "XDEW.DE", name: "Xtrackers MSCI World ETF", sector: "Diversified", type: "etf" },
  { ticker: "SXR8.DE", name: "iShares Core S&P 500 (DE)", sector: "Diversified", type: "etf" },
  { ticker: "EUNL.DE", name: "iShares Core MSCI World (DE)", sector: "Diversified", type: "etf" },
  { ticker: "LYP6.DE", name: "Amundi MSCI World ETF", sector: "Diversified", type: "etf" },
  { ticker: "EXS1.DE", name: "iShares Core DAX ETF", sector: "Diversified", type: "etf" },
  { ticker: "LYPS.DE", name: "Amundi S&P 500 ETF", sector: "Diversified", type: "etf" },
  { ticker: "MEUD.PA", name: "Amundi Euro Stoxx 50 ETF", sector: "Diversified", type: "etf" },
  { ticker: "CW8.PA", name: "Amundi MSCI World ETF (PA)", sector: "Diversified", type: "etf" },
  { ticker: "500.PA", name: "Amundi PEA S&P 500 ETF", sector: "Diversified", type: "etf" },
  { ticker: "TNO.PA", name: "Amundi MSCI Emerging Markets", sector: "Diversified", type: "etf" },
  { ticker: "VAS.AX", name: "Vanguard Australian Shares", sector: "Diversified", type: "etf" },
  { ticker: "IOZ.AX", name: "iShares Core S&P/ASX 200", sector: "Diversified", type: "etf" },
  { ticker: "VGS.AX", name: "Vanguard MSCI Intl Shares", sector: "Diversified", type: "etf" },
  { ticker: "XIU.TO", name: "iShares S&P/TSX 60 ETF", sector: "Diversified", type: "etf" },
  { ticker: "VFV.TO", name: "Vanguard S&P 500 ETF (CA)", sector: "Diversified", type: "etf" },
  { ticker: "ZSP.TO", name: "BMO S&P 500 ETF", sector: "Diversified", type: "etf" },
  { ticker: "BOVA11.SA", name: "iShares Ibovespa ETF", sector: "Diversified", type: "etf" },
];

export const internationalStocks: AssetEntry[] = [
  ...ukStocks,
  ...deStocks,
  ...frStocks,
  ...esStocks,
  ...itStocks,
  ...nlStocks,
  ...chStocks,
  ...jpStocks,
  ...hkStocks,
  ...caStocks,
  ...auStocks,
  ...krStocks,
  ...nordicStocks,
  ...brStocks,
  ...inStocks,
  ...twStocks,
  ...sgStocks,
  ...internationalEtfs,
];
