import { AssetEntry } from "./types";

export const megaUSStocks: AssetEntry[] = [
  { ticker: "ACAD", name: "ACADIA Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "AGEN", name: "Agenus", sector: "Healthcare", type: "stock" },
  { ticker: "AKAM", name: "Akamai Technologies", sector: "Technology", type: "stock" },
  { ticker: "ALGM", name: "Allegro MicroSystems", sector: "Technology", type: "stock" },
  { ticker: "AMKR", name: "Amkor Technology", sector: "Technology", type: "stock" },
  { ticker: "AMPS", name: "Altus Power", sector: "Utilities", type: "stock" },
  { ticker: "APLS", name: "Apellis Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "APPF", name: "AppFolio", sector: "Technology", type: "stock" },
  { ticker: "ARCB", name: "ArcBest", sector: "Industrials", type: "stock" },
  { ticker: "AROC", name: "Archrock", sector: "Energy", type: "stock" },
  { ticker: "ASTE", name: "Astec Industries", sector: "Industrials", type: "stock" },
  { ticker: "ATMU", name: "Atmus Filtration", sector: "Industrials", type: "stock" },
  { ticker: "AVNT", name: "Avient", sector: "Materials", type: "stock" },
  { ticker: "AXNX", name: "Axonics", sector: "Healthcare", type: "stock" },
  { ticker: "AYI", name: "Acuity Brands", sector: "Industrials", type: "stock" },
  { ticker: "AZTA", name: "Azenta", sector: "Healthcare", type: "stock" },
  { ticker: "BALL", name: "Ball Corporation", sector: "Materials", type: "stock" },
  { ticker: "BBIO", name: "BridgeBio Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "BDC", name: "Belden", sector: "Industrials", type: "stock" },
  { ticker: "BECN", name: "Beacon Roofing", sector: "Industrials", type: "stock" },
  { ticker: "BFH", name: "Bread Financial", sector: "Finance", type: "stock" },
  { ticker: "BGS", name: "B&G Foods", sector: "Consumer", type: "stock" },
  { ticker: "BJRI", name: "BJ's Restaurants", sector: "Consumer", type: "stock" },
  { ticker: "BLDP", name: "Ballard Power", sector: "Industrials", type: "stock" },
  { ticker: "BLKB", name: "Blackbaud", sector: "Technology", type: "stock" },
  { ticker: "BNR", name: "Burning Rock Biotech", sector: "Healthcare", type: "stock" },
  { ticker: "BPMC", name: "Blueprint Medicines", sector: "Healthcare", type: "stock" },
  { ticker: "BRBR", name: "BellRing Brands", sector: "Consumer", type: "stock" },
  { ticker: "BRSP", name: "BrightSpire Capital", sector: "Real Estate", type: "stock" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "BWA", name: "BorgWarner", sector: "Consumer", type: "stock" },
  { ticker: "BWXT", name: "BWX Technologies", sector: "Industrials", type: "stock" },
  { ticker: "CALM", name: "Cal-Maine Foods", sector: "Consumer", type: "stock" },
  { ticker: "CBRL", name: "Cracker Barrel", sector: "Consumer", type: "stock" },
  { ticker: "CBT", name: "Cabot", sector: "Materials", type: "stock" },
  { ticker: "CCS", name: "Century Communities", sector: "Consumer", type: "stock" },
  { ticker: "CDNS", name: "Cadence Design", sector: "Technology", type: "stock" },
  { ticker: "CEIX", name: "CONSOL Energy", sector: "Energy", type: "stock" },
  { ticker: "CENTA", name: "Central Garden & Pet", sector: "Consumer", type: "stock" },
  { ticker: "CFFS", name: "CF Acquisition", sector: "Finance", type: "stock" },
  { ticker: "CHEF", name: "Chefs' Warehouse", sector: "Consumer", type: "stock" },
  { ticker: "CIEN", name: "Ciena", sector: "Technology", type: "stock" },
  { ticker: "CMPO", name: "CompoSecure", sector: "Technology", type: "stock" },
  { ticker: "CNM", name: "Core Molding", sector: "Materials", type: "stock" },
  { ticker: "CNS", name: "Cohen & Steers", sector: "Finance", type: "stock" },
  { ticker: "COHR", name: "Coherent", sector: "Technology", type: "stock" },
  { ticker: "COKE", name: "Coca-Cola Consolidated", sector: "Consumer", type: "stock" },
  { ticker: "CORT", name: "Corcept", sector: "Healthcare", type: "stock" },
  { ticker: "CPK", name: "Chesapeake Utilities", sector: "Utilities", type: "stock" },
  { ticker: "CPRX", name: "Catalyst Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "CRC", name: "California Resources", sector: "Energy", type: "stock" },
  { ticker: "CRI", name: "Carter's", sector: "Consumer", type: "stock" },
  { ticker: "CRVL", name: "CorVel", sector: "Technology", type: "stock" },
  { ticker: "CSWI", name: "CSW Industrials", sector: "Industrials", type: "stock" },
  { ticker: "CW", name: "Curtiss-Wright", sector: "Industrials", type: "stock" },
  { ticker: "CXT", name: "Crane NXT", sector: "Industrials", type: "stock" },
  { ticker: "DAR", name: "Darling Ingredients", sector: "Consumer", type: "stock" },
  { ticker: "DCI", name: "Donaldson", sector: "Industrials", type: "stock" },
  { ticker: "DFIN", name: "Donnelley Financial", sector: "Technology", type: "stock" },
  { ticker: "DIOD", name: "Diodes", sector: "Technology", type: "stock" },
  { ticker: "DLB", name: "Dolby Laboratories", sector: "Technology", type: "stock" },
  { ticker: "DORM", name: "Dorman Products", sector: "Consumer", type: "stock" },
  { ticker: "DSGR", name: "Distribution Solutions", sector: "Industrials", type: "stock" },
  { ticker: "DUOL", name: "Duolingo", sector: "Technology", type: "stock" },
  { ticker: "DVAX", name: "Dynavax Technologies", sector: "Healthcare", type: "stock" },
  { ticker: "DXC", name: "DXC Technology", sector: "Technology", type: "stock" },
  { ticker: "DXPE", name: "DXP Enterprises", sector: "Industrials", type: "stock" },
  { ticker: "DY", name: "Dycom Industries", sector: "Industrials", type: "stock" },
  { ticker: "EAT", name: "Brinker International", sector: "Consumer", type: "stock" },
  { ticker: "EEFT", name: "Euronet Worldwide", sector: "Finance", type: "stock" },
  { ticker: "EHC", name: "Encompass Health", sector: "Healthcare", type: "stock" },
  { ticker: " ELFV", name: "e.l.f. Beauty", sector: "Consumer", type: "stock" },
  { ticker: "ENVX", name: "Enovis", sector: "Healthcare", type: "stock" },
  { ticker: "EPAM", name: "EPAM Systems", sector: "Technology", type: "stock" },
  { ticker: "EVCM", name: "EverCommerce", sector: "Technology", type: "stock" },
  { ticker: "EVRI", name: "Everi Holdings", sector: "Technology", type: "stock" },
  { ticker: "EXEL", name: "Exelixis", sector: "Healthcare", type: "stock" },
  { ticker: "EXPO", name: "Exponent", sector: "Industrials", type: "stock" },
  { ticker: "FBIN", name: "Fortune Brands", sector: "Industrials", type: "stock" },
  { ticker: "FCNCA", name: "First Citizens", sector: "Finance", type: "stock" },
  { ticker: "FDP", name: "Fresh Del Monte", sector: "Consumer", type: "stock" },
  { ticker: "FHI", name: "Federated Hermes", sector: "Finance", type: "stock" },
  { ticker: "FIX", name: "Comfort Systems", sector: "Industrials", type: "stock" },
  { ticker: "FORM", name: "FormFactor", sector: "Technology", type: "stock" },
  { ticker: "FOXF", name: "Fox Factory", sector: "Consumer", type: "stock" },
  { ticker: "FRPT", name: "Freshpet", sector: "Consumer", type: "stock" },
  { ticker: "FTNT", name: "Fortinet", sector: "Technology", type: "stock" },
  { ticker: "FWRD", name: "Forward Air", sector: "Industrials", type: "stock" },
  { ticker: "G", name: "Genpact", sector: "Technology", type: "stock" },
  { ticker: "GATX", name: "GATX", sector: "Industrials", type: "stock" },
  { ticker: "GEF", name: "Greif", sector: "Materials", type: "stock" },
  { ticker: "GFL", name: "GFL Environmental", sector: "Industrials", type: "stock" },
  { ticker: "GKOS", name: "Glaukos", sector: "Healthcare", type: "stock" },
  { ticker: "GLOB", name: "Globant", sector: "Technology", type: "stock" },
  { ticker: "GMS", name: "GMS Inc", sector: "Materials", type: "stock" },
  { ticker: "GNTX", name: "Gentex", sector: "Consumer", type: "stock" },
  { ticker: "GPOR", name: "Gulfport Energy", sector: "Energy", type: "stock" },
  { ticker: "GWW", name: "W.W. Grainger", sector: "Industrials", type: "stock" },
  { ticker: "HAE", name: "Haemonetics", sector: "Healthcare", type: "stock" },
  { ticker: "HAIN", name: "Hain Celestial", sector: "Consumer", type: "stock" },
  { ticker: "HALO", name: "Halozyme", sector: "Healthcare", type: "stock" },
  { ticker: "HAS", name: "Hasbro", sector: "Consumer", type: "stock" },
  { ticker: "HELE", name: "Helen of Troy", sector: "Consumer", type: "stock" },
  { ticker: "HI", name: "Hillenbrand", sector: "Industrials", type: "stock" },
  { ticker: "HIW", name: "Highwoods Properties", sector: "Real Estate", type: "stock" },
  { ticker: "HLF", name: "Herbalife", sector: "Consumer", type: "stock" },
  { ticker: "HLI", name: "Houlihan Lokey", sector: "Finance", type: "stock" },
  { ticker: "HLNE", name: "Hamilton Lane", sector: "Finance", type: "stock" },
  { ticker: "HQY", name: "HealthEquity", sector: "Healthcare", type: "stock" },
  { ticker: "HRMY", name: "Harmony Biosciences", sector: "Healthcare", type: "stock" },
  { ticker: "HUN", name: "Huntsman", sector: "Materials", type: "stock" },
  { ticker: "IART", name: "Integra LifeSciences", sector: "Healthcare", type: "stock" },
  { ticker: "IBOC", name: "International Bancshares", sector: "Finance", type: "stock" },
  { ticker: "ICL", name: "ICL Group", sector: "Materials", type: "stock" },
  { ticker: "ICLR", name: "ICON", sector: "Healthcare", type: "stock" },
  { ticker: "IDA", name: "IDACORP", sector: "Utilities", type: "stock" },
  { ticker: "IIPR", name: "Innovative Industrial", sector: "Real Estate", type: "stock" },
  { ticker: "INCY", name: "Incyte", sector: "Healthcare", type: "stock" },
  { ticker: "INGR", name: "Ingredion", sector: "Consumer", type: "stock" },
  { ticker: "INSP", name: "Inspire Medical", sector: "Healthcare", type: "stock" },
  { ticker: "INST", name: "Instructure", sector: "Technology", type: "stock" },
  { ticker: "IOSP", name: "Innospec", sector: "Materials", type: "stock" },
  { ticker: "ITGR", name: "Integer Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "ITRI", name: "Itron", sector: "Technology", type: "stock" },
  { ticker: "IVT", name: "InvenTrust Properties", sector: "Real Estate", type: "stock" },
  { ticker: "JACK", name: "Jack in the Box", sector: "Consumer", type: "stock" },
  { ticker: "JAMF", name: "Jamf Holding", sector: "Technology", type: "stock" },
  { ticker: "JBT", name: "JBT Corporation", sector: "Industrials", type: "stock" },
  { ticker: "JNPR", name: "Juniper Networks", sector: "Technology", type: "stock" },
  { ticker: "KALU", name: "Kaiser Aluminum", sector: "Materials", type: "stock" },
  { ticker: "KBR", name: "KBR Inc", sector: "Industrials", type: "stock" },
  { ticker: "KD", name: "Kyndryl Holdings", sector: "Technology", type: "stock" },
  { ticker: "KFY", name: "Kforce", sector: "Industrials", type: "stock" },
  { ticker: "KLIC", name: "Kulicke & Soffa", sector: "Technology", type: "stock" },
  { ticker: "KNX", name: "Knight-Swift", sector: "Industrials", type: "stock" },
  { ticker: "KRC", name: "Kilroy Realty", sector: "Real Estate", type: "stock" },
  { ticker: "KRG", name: "Kite Realty", sector: "Real Estate", type: "stock" },
  { ticker: "KWR", name: "Quaker Chemical", sector: "Materials", type: "stock" },
  { ticker: "LANC", name: "Lancaster Colony", sector: "Consumer", type: "stock" },
  { ticker: "LAUR", name: "Laureate Education", sector: "Consumer", type: "stock" },
  { ticker: "LBRT", name: "Liberty Oilfield", sector: "Energy", type: "stock" },
  { ticker: "LCII", name: "LCI Industries", sector: "Consumer", type: "stock" },
  { ticker: "LFST", name: "LifeStance Health", sector: "Healthcare", type: "stock" },
  { ticker: "LGIH", name: "LGI Homes", sector: "Consumer", type: "stock" },
  { ticker: "LILA", name: "Liberty Latin America", sector: "Communication", type: "stock" },
  { ticker: "LIVN", name: "LivaNova", sector: "Healthcare", type: "stock" },
  { ticker: "LKFN", name: "Lakeland Financial", sector: "Finance", type: "stock" },
  { ticker: "LMAT", name: "LeMaitre Vascular", sector: "Healthcare", type: "stock" },
  { ticker: "LNW", name: "Light & Wonder", sector: "Consumer", type: "stock" },
  { ticker: "LPRO", name: "Open Lending", sector: "Finance", type: "stock" },
  { ticker: "LSCC", name: "Lattice Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "LUNG", name: "Pulmonx", sector: "Healthcare", type: "stock" },
  { ticker: "LW", name: "Lamb Weston", sector: "Consumer", type: "stock" },
  { ticker: "LXP", name: "LXP Industrial", sector: "Real Estate", type: "stock" },
  { ticker: "MAG", name: "MAG Silver", sector: "Materials", type: "stock" },
  { ticker: "MATV", name: "Mativ Holdings", sector: "Materials", type: "stock" },
  { ticker: "MAT", name: "Mattel", sector: "Consumer", type: "stock" },
  { ticker: "MAXR", name: "Maxar Technologies", sector: "Technology", type: "stock" },
  { ticker: "MBIN", name: "Merchants Financial", sector: "Finance", type: "stock" },
  { ticker: "MCRI", name: "Monarch Casino", sector: "Consumer", type: "stock" },
  { ticker: "MDGL", name: "Madrigal Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "MDU", name: "MDU Resources", sector: "Utilities", type: "stock" },
  { ticker: "MEDP", name: "Medpace Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "MEI", name: "Methode Electronics", sector: "Technology", type: "stock" },
  { ticker: "MGM", name: "MGM Resorts", sector: "Consumer", type: "stock" },
  { ticker: "MHO", name: "M/I Homes", sector: "Consumer", type: "stock" },
  { ticker: "MIDD", name: "Middleby", sector: "Industrials", type: "stock" },
  { ticker: "MKSI", name: "MKS Instruments", sector: "Technology", type: "stock" },
  { ticker: "MMSI", name: "Merit Medical", sector: "Healthcare", type: "stock" },
  { ticker: "MNKD", name: "MannKind", sector: "Healthcare", type: "stock" },
  { ticker: "MOD", name: "Modine Manufacturing", sector: "Industrials", type: "stock" },
  { ticker: "MOG-A", name: "Moog", sector: "Industrials", type: "stock" },
  { ticker: "MORN", name: "Morningstar", sector: "Finance", type: "stock" },
  { ticker: "MRUS", name: "Merus", sector: "Healthcare", type: "stock" },
  { ticker: "MSA", name: "MSA Safety", sector: "Industrials", type: "stock" },
  { ticker: "MSM", name: "MSC Industrial", sector: "Industrials", type: "stock" },
  { ticker: "MTSI", name: "MACOM Technology", sector: "Technology", type: "stock" },
  { ticker: "MUR", name: "Murphy Oil", sector: "Energy", type: "stock" },
  { ticker: "MUSA", name: "Murphy USA", sector: "Consumer", type: "stock" },
  { ticker: "NABL", name: "N-able", sector: "Technology", type: "stock" },
  { ticker: "NBR", name: "Nabors Industries", sector: "Energy", type: "stock" },
  { ticker: "NCMI", name: "National CineMedia", sector: "Communication", type: "stock" },
  { ticker: "NEO", name: "NeoGenomics", sector: "Healthcare", type: "stock" },
  { ticker: "NEOG", name: "Neogen", sector: "Healthcare", type: "stock" },
  { ticker: "NGVT", name: "Ingevity", sector: "Materials", type: "stock" },
  { ticker: "NHC", name: "National HealthCare", sector: "Healthcare", type: "stock" },
  { ticker: "NJR", name: "New Jersey Resources", sector: "Utilities", type: "stock" },
  { ticker: "NNI", name: "Nelnet", sector: "Finance", type: "stock" },
  { ticker: "NOG", name: "Northern Oil & Gas", sector: "Energy", type: "stock" },
  { ticker: "NPO", name: "EnPro Industries", sector: "Industrials", type: "stock" },
  { ticker: "NR", name: "Newpark Resources", sector: "Energy", type: "stock" },
  { ticker: "NSP", name: "Insperity", sector: "Industrials", type: "stock" },
  { ticker: "NSIT", name: "Insight Enterprises", sector: "Technology", type: "stock" },
  { ticker: "NVR", name: "NVR Inc", sector: "Consumer", type: "stock" },
  { ticker: "NWL", name: "Newell Brands", sector: "Consumer", type: "stock" },
  { ticker: "NXRT", name: "NexPoint Residential", sector: "Real Estate", type: "stock" },
  { ticker: "NYT", name: "New York Times", sector: "Communication", type: "stock" },
  { ticker: "OLED", name: "Universal Display", sector: "Technology", type: "stock" },
  { ticker: "OLPX", name: "Olaplex Holdings", sector: "Consumer", type: "stock" },
  { ticker: "OMF", name: "OneMain Financial", sector: "Finance", type: "stock" },
  { ticker: "OMP", name: "Oasis Midstream", sector: "Energy", type: "stock" },
  { ticker: "ORA", name: "Ormat Technologies", sector: "Utilities", type: "stock" },
  { ticker: "OSCR", name: "Oscar Health", sector: "Healthcare", type: "stock" },
  { ticker: "OZK", name: "Bank OZK", sector: "Finance", type: "stock" },
  { ticker: "PATK", name: "Patrick Industries", sector: "Consumer", type: "stock" },
  { ticker: "PAYO", name: "Payoneer", sector: "Finance", type: "stock" },
  { ticker: "PBF", name: "PBF Energy", sector: "Energy", type: "stock" },
  { ticker: "PCH", name: "PotlatchDeltic", sector: "Real Estate", type: "stock" },
  { ticker: "PEB", name: "Pebblebrook Hotel", sector: "Real Estate", type: "stock" },
  { ticker: "PEN", name: "Penumbra", sector: "Healthcare", type: "stock" },
  { ticker: "PGNY", name: "Progyny", sector: "Healthcare", type: "stock" },
  { ticker: "PHM", name: "PulteGroup", sector: "Consumer", type: "stock" },
  { ticker: "PINC", name: "Premier", sector: "Healthcare", type: "stock" },
  { ticker: "PIPR", name: "Piper Sandler", sector: "Finance", type: "stock" },
  { ticker: "PLMR", name: "Palomar Holdings", sector: "Finance", type: "stock" },
  { ticker: "PLUS", name: "ePlus", sector: "Technology", type: "stock" },
  { ticker: "POWI", name: "Power Integrations", sector: "Technology", type: "stock" },
  { ticker: "POWL", name: "Powell Industries", sector: "Industrials", type: "stock" },
  { ticker: "PRMW", name: "Primo Water", sector: "Consumer", type: "stock" },
  { ticker: "PRO", name: "PROS Holdings", sector: "Technology", type: "stock" },
  { ticker: "PRFT", name: "Perficient", sector: "Technology", type: "stock" },
  { ticker: "PRI", name: "Primerica", sector: "Finance", type: "stock" },
  { ticker: "PRLB", name: "Proto Labs", sector: "Industrials", type: "stock" },
  { ticker: "PSN", name: "Parsons", sector: "Industrials", type: "stock" },
  { ticker: "PTC", name: "PTC Inc", sector: "Technology", type: "stock" },
  { ticker: "PTGX", name: "Protagonist Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "PVH", name: "PVH Corp", sector: "Consumer", type: "stock" },
  { ticker: "QLYS", name: "Qualys", sector: "Technology", type: "stock" },
  { ticker: "QTWO", name: "Q2 Holdings", sector: "Technology", type: "stock" },
  { ticker: "RBC", name: "RBC Bearings", sector: "Industrials", type: "stock" },
  { ticker: "RCM", name: "R1 RCM", sector: "Healthcare", type: "stock" },
  { ticker: "RDNT", name: "RadNet", sector: "Healthcare", type: "stock" },
  { ticker: "RGEN", name: "Repligen", sector: "Healthcare", type: "stock" },
  { ticker: "RGP", name: "Resources Connection", sector: "Industrials", type: "stock" },
  { ticker: "RHI", name: "Robert Half", sector: "Industrials", type: "stock" },
  { ticker: "RIG", name: "Transocean", sector: "Energy", type: "stock" },
  { ticker: "RLI", name: "RLI Corp", sector: "Finance", type: "stock" },
  { ticker: "RMBS", name: "Rambus", sector: "Technology", type: "stock" },
  { ticker: "RNG", name: "RingCentral", sector: "Technology", type: "stock" },
  { ticker: "ROAD", name: "Construction Partners", sector: "Industrials", type: "stock" },
  { ticker: "ROG", name: "Rogers Corporation", sector: "Technology", type: "stock" },
  { ticker: "RPM", name: "RPM International", sector: "Materials", type: "stock" },
  { ticker: "RPRX", name: "Royalty Pharma", sector: "Healthcare", type: "stock" },
  { ticker: "RUN", name: "Sunrun", sector: "Technology", type: "stock" },
  { ticker: "RXO", name: "RXO Inc", sector: "Industrials", type: "stock" },
  { ticker: "RYAAY", name: "Ryanair", sector: "Industrials", type: "stock" },
  { ticker: "SAM", name: "Boston Beer", sector: "Consumer", type: "stock" },
  { ticker: "SATS", name: "EchoStar", sector: "Communication", type: "stock" },
  { ticker: "SCI", name: "Service Corporation", sector: "Consumer", type: "stock" },
  { ticker: "SCSC", name: "ScanSource", sector: "Technology", type: "stock" },
  { ticker: "SDGR", name: "Schrodinger", sector: "Healthcare", type: "stock" },
  { ticker: "SGRY", name: "Surgery Partners", sector: "Healthcare", type: "stock" },
  { ticker: "SHOO", name: "Steven Madden", sector: "Consumer", type: "stock" },
  { ticker: "SKY", name: "Skyline Champion", sector: "Consumer", type: "stock" },
  { ticker: "SLGN", name: "Silgan Holdings", sector: "Materials", type: "stock" },
  { ticker: "SLM", name: "SLM Corp", sector: "Finance", type: "stock" },
  { ticker: "SMPL", name: "Simply Good Foods", sector: "Consumer", type: "stock" },
  { ticker: "SN", name: "SharkNinja", sector: "Consumer", type: "stock" },
  { ticker: "SNDR", name: "Schneider National", sector: "Industrials", type: "stock" },
  { ticker: "SNX", name: "TD SYNNEX", sector: "Technology", type: "stock" },
  { ticker: "SON", name: "Sonoco Products", sector: "Materials", type: "stock" },
  { ticker: "SPB", name: "Spectrum Brands", sector: "Consumer", type: "stock" },
  { ticker: "SPSC", name: "SPS Commerce", sector: "Technology", type: "stock" },
  { ticker: "SPXC", name: "SPX Technologies", sector: "Industrials", type: "stock" },
  { ticker: "SSD", name: "Simpson Manufacturing", sector: "Industrials", type: "stock" },
  { ticker: "SSNC", name: "SS&C Technologies", sector: "Technology", type: "stock" },
  { ticker: "SSTK", name: "Shutterstock", sector: "Technology", type: "stock" },
  { ticker: "STAG", name: "STAG Industrial", sector: "Real Estate", type: "stock" },
  { ticker: "STNG", name: "Scorpio Tankers", sector: "Energy", type: "stock" },
  { ticker: "STRA", name: "Stride", sector: "Consumer", type: "stock" },
  { ticker: "STRL", name: "Sterling Infrastructure", sector: "Industrials", type: "stock" },
  { ticker: "SWBI", name: "Smith & Wesson", sector: "Consumer", type: "stock" },
  { ticker: "SWI", name: "SolarWinds", sector: "Technology", type: "stock" },
  { ticker: "SXI", name: "Standex International", sector: "Industrials", type: "stock" },
  { ticker: "SYNA", name: "Synaptics", sector: "Technology", type: "stock" },
  { ticker: "TBBK", name: "Bancorp", sector: "Finance", type: "stock" },
  { ticker: "TDC", name: "Teradata", sector: "Technology", type: "stock" },
  { ticker: "TGNA", name: "TEGNA", sector: "Communication", type: "stock" },
  { ticker: "THC", name: "Tenet Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "THG", name: "Hanover Insurance", sector: "Finance", type: "stock" },
  { ticker: "THS", name: "TreeHouse Foods", sector: "Consumer", type: "stock" },
  { ticker: "TKR", name: "Timken", sector: "Industrials", type: "stock" },
  { ticker: "TMHC", name: "Taylor Morrison", sector: "Consumer", type: "stock" },
  { ticker: "TNET", name: "TriNet Group", sector: "Technology", type: "stock" },
  { ticker: "TOST", name: "Toast", sector: "Technology", type: "stock" },
  { ticker: "TREX", name: "Trex Company", sector: "Industrials", type: "stock" },
  { ticker: "TRN", name: "Trinity Industries", sector: "Industrials", type: "stock" },
  { ticker: "TRUP", name: "Trupanion", sector: "Finance", type: "stock" },
  { ticker: "TTMI", name: "TTM Technologies", sector: "Technology", type: "stock" },
  { ticker: "TXG", name: "10x Genomics", sector: "Healthcare", type: "stock" },
  { ticker: "TXT", name: "Textron", sector: "Industrials", type: "stock" },
  { ticker: "UDMY", name: "Udemy", sector: "Technology", type: "stock" },
  { ticker: "UFI", name: "Unifi", sector: "Materials", type: "stock" },
  { ticker: "UFPT", name: "UFP Technologies", sector: "Healthcare", type: "stock" },
  { ticker: "UGI", name: "UGI Corporation", sector: "Utilities", type: "stock" },
  { ticker: "ULTA", name: "Ulta Beauty", sector: "Consumer", type: "stock" },
  { ticker: "UMBF", name: "UMB Financial", sector: "Finance", type: "stock" },
  { ticker: "UMPQ", name: "Umpqua Holdings", sector: "Finance", type: "stock" },
  { ticker: "UNF", name: "UniFirst", sector: "Industrials", type: "stock" },
  { ticker: "UNFI", name: "United Natural Foods", sector: "Consumer", type: "stock" },
  { ticker: "UPBD", name: "Upbound Group", sector: "Consumer", type: "stock" },
  { ticker: "URBN", name: "Urban Outfitters", sector: "Consumer", type: "stock" },
  { ticker: "USPH", name: "US Physical Therapy", sector: "Healthcare", type: "stock" },
  { ticker: "UTZ", name: "Utz Brands", sector: "Consumer", type: "stock" },
  { ticker: "VAC", name: "Marriott Vacations", sector: "Consumer", type: "stock" },
  { ticker: "VCEL", name: "Vericel", sector: "Healthcare", type: "stock" },
  { ticker: "VCTR", name: "Victory Capital", sector: "Finance", type: "stock" },
  { ticker: "VERX", name: "Vertex", sector: "Technology", type: "stock" },
  { ticker: "VIRT", name: "Virtu Financial", sector: "Finance", type: "stock" },
  { ticker: "VITL", name: "Vital Farms", sector: "Consumer", type: "stock" },
  { ticker: "VLTO", name: "Veralto", sector: "Industrials", type: "stock" },
  { ticker: "VRNT", name: "Verint Systems", sector: "Technology", type: "stock" },
  { ticker: "VRTS", name: "Virtus Investment", sector: "Finance", type: "stock" },
  { ticker: "VSH", name: "Vishay Intertechnology", sector: "Technology", type: "stock" },
  { ticker: "VSTO", name: "Vista Outdoor", sector: "Consumer", type: "stock" },
  { ticker: "WDFC", name: "WD-40", sector: "Consumer", type: "stock" },
  { ticker: "WERN", name: "Werner Enterprises", sector: "Industrials", type: "stock" },
  { ticker: "WGO", name: "Winnebago", sector: "Consumer", type: "stock" },
  { ticker: "WHD", name: "Cactus", sector: "Energy", type: "stock" },
  { ticker: "WK", name: "Workiva", sector: "Technology", type: "stock" },
  { ticker: "WLFC", name: "Willis Lease", sector: "Industrials", type: "stock" },
  { ticker: "WOR", name: "Worthington", sector: "Industrials", type: "stock" },
  { ticker: "WSC", name: "WillScot Mobile", sector: "Industrials", type: "stock" },
  { ticker: "WST", name: "West Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "XNCR", name: "Xencor", sector: "Healthcare", type: "stock" },
  { ticker: "XRAY", name: "DENTSPLY SIRONA", sector: "Healthcare", type: "stock" },
  { ticker: "YEXT", name: "Yext", sector: "Technology", type: "stock" },
  { ticker: "YOU", name: "Clear Secure", sector: "Technology", type: "stock" },
  { ticker: "ZD", name: "Ziff Davis", sector: "Technology", type: "stock" },
  { ticker: "ZWS", name: "Zurn Elkay", sector: "Industrials", type: "stock" },
];

export const moreEUStocks: AssetEntry[] = [
  { ticker: "ABI.BR", name: "AB InBev", sector: "Consumer", type: "stock" },
  { ticker: "UCB.BR", name: "UCB", sector: "Healthcare", type: "stock" },
  { ticker: "SOLB.BR", name: "Solvay", sector: "Materials", type: "stock" },
  { ticker: "AGS.BR", name: "Ageas", sector: "Finance", type: "stock" },
  { ticker: "COLR.BR", name: "Colruyt", sector: "Consumer", type: "stock" },
  { ticker: "PROX.BR", name: "Proximus", sector: "Telecom", type: "stock" },
  { ticker: "BEKB.BR", name: "Bekaert", sector: "Materials", type: "stock" },
  { ticker: "ACKB.BR", name: "Ackermans & van Haaren", sector: "Industrials", type: "stock" },
  { ticker: "KBC.BR", name: "KBC Group", sector: "Finance", type: "stock" },
  { ticker: "GBLB.BR", name: "GBL", sector: "Finance", type: "stock" },
  { ticker: "VOE.VI", name: "voestalpine", sector: "Materials", type: "stock" },
  { ticker: "EBS.VI", name: "Erste Group", sector: "Finance", type: "stock" },
  { ticker: "OMV.VI", name: "OMV", sector: "Energy", type: "stock" },
  { ticker: "WIE.VI", name: "Wienerberger", sector: "Materials", type: "stock" },
  { ticker: "VER.VI", name: "Verbund", sector: "Utilities", type: "stock" },
  { ticker: "RBI.VI", name: "Raiffeisen Bank", sector: "Finance", type: "stock" },
  { ticker: "TKA.VI", name: "Telekom Austria", sector: "Telecom", type: "stock" },
  { ticker: "AMS.VI", name: "ams-OSRAM", sector: "Technology", type: "stock" },
  { ticker: "GALP.LS", name: "Galp Energia", sector: "Energy", type: "stock" },
  { ticker: "EDP.LS", name: "EDP", sector: "Utilities", type: "stock" },
  { ticker: "JMT.LS", name: "Jerónimo Martins", sector: "Consumer", type: "stock" },
  { ticker: "BCP.LS", name: "Banco Comercial", sector: "Finance", type: "stock" },
  { ticker: "SON.LS", name: "Sonae", sector: "Consumer", type: "stock" },
  { ticker: "EDPR.LS", name: "EDP Renováveis", sector: "Utilities", type: "stock" },
  { ticker: "CRH.IR", name: "CRH plc", sector: "Materials", type: "stock" },
  { ticker: "AIB.IR", name: "AIB Group", sector: "Finance", type: "stock" },
  { ticker: "BIRG.IR", name: "Bank of Ireland", sector: "Finance", type: "stock" },
  { ticker: "KRX.IR", name: "Kingspan", sector: "Materials", type: "stock" },
  { ticker: "FLT.IR", name: "Flutter Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "SKG.IR", name: "Smurfit Kappa", sector: "Materials", type: "stock" },
  { ticker: "HTO.AT", name: "Hellenic Telecom", sector: "Telecom", type: "stock" },
  { ticker: "OPAP.AT", name: "OPAP", sector: "Consumer", type: "stock" },
  { ticker: "EUROB.AT", name: "Eurobank Ergasias", sector: "Finance", type: "stock" },
  { ticker: "ALPHA.AT", name: "Alpha Bank", sector: "Finance", type: "stock" },
  { ticker: "MYTIL.AT", name: "Mytilineos", sector: "Industrials", type: "stock" },
  { ticker: "PPC.AT", name: "Public Power", sector: "Utilities", type: "stock" },
];

export const latamStocks: AssetEntry[] = [
  { ticker: "GGAL", name: "Grupo Financiero Galicia", sector: "Finance", type: "stock" },
  { ticker: "YPF", name: "YPF", sector: "Energy", type: "stock" },
  { ticker: "PAM", name: "Pampa Energía", sector: "Utilities", type: "stock" },
  { ticker: "BMA", name: "Banco Macro", sector: "Finance", type: "stock" },
  { ticker: "SUPV", name: "Grupo Supervielle", sector: "Finance", type: "stock" },
  { ticker: "TEO", name: "Telecom Argentina", sector: "Telecom", type: "stock" },
  { ticker: "IRCP", name: "IRSA Commercial", sector: "Real Estate", type: "stock" },
  { ticker: "CEPU", name: "Central Puerto", sector: "Utilities", type: "stock" },
  { ticker: "TGS", name: "Transportadora de Gas", sector: "Energy", type: "stock" },
  { ticker: "LOMA", name: "Loma Negra", sector: "Materials", type: "stock" },
  { ticker: "BVN", name: "Buenaventura Mining", sector: "Materials", type: "stock" },
  { ticker: "BAP", name: "Credicorp", sector: "Finance", type: "stock" },
  { ticker: "SCCO", name: "Southern Copper", sector: "Materials", type: "stock" },
  { ticker: "IFS", name: "Intercorp Financial", sector: "Finance", type: "stock" },
];
