import { AssetEntry } from "./types";

export const moreAsiaStocks: AssetEntry[] = [
  { ticker: "9988.HK", name: "Alibaba Group", sector: "Technology", type: "stock" },
  { ticker: "0700.HK", name: "Tencent Holdings", sector: "Technology", type: "stock" },
  { ticker: "3690.HK", name: "Meituan", sector: "Technology", type: "stock" },
  { ticker: "9618.HK", name: "JD.com", sector: "Technology", type: "stock" },
  { ticker: "9999.HK", name: "NetEase", sector: "Technology", type: "stock" },
  { ticker: "1810.HK", name: "Xiaomi", sector: "Technology", type: "stock" },
  { ticker: "2318.HK", name: "Ping An Insurance", sector: "Finance", type: "stock" },
  { ticker: "0941.HK", name: "China Mobile", sector: "Telecom", type: "stock" },
  { ticker: "0005.HK", name: "HSBC Holdings", sector: "Finance", type: "stock" },
  { ticker: "1299.HK", name: "AIA Group", sector: "Finance", type: "stock" },
  { ticker: "0388.HK", name: "Hong Kong Exchanges", sector: "Finance", type: "stock" },
  { ticker: "2628.HK", name: "China Life", sector: "Finance", type: "stock" },
  { ticker: "0883.HK", name: "CNOOC", sector: "Energy", type: "stock" },
  { ticker: "0857.HK", name: "PetroChina", sector: "Energy", type: "stock" },
  { ticker: "0386.HK", name: "China Petroleum", sector: "Energy", type: "stock" },
  { ticker: "1398.HK", name: "ICBC", sector: "Finance", type: "stock" },
  { ticker: "3988.HK", name: "Bank of China", sector: "Finance", type: "stock" },
  { ticker: "0939.HK", name: "CCB", sector: "Finance", type: "stock" },
  { ticker: "1288.HK", name: "Agricultural Bank", sector: "Finance", type: "stock" },
  { ticker: "3328.HK", name: "Bank of Communications", sector: "Finance", type: "stock" },
  { ticker: "2269.HK", name: "WuXi Biologics", sector: "Healthcare", type: "stock" },
  { ticker: "0175.HK", name: "Geely Automobile", sector: "Consumer", type: "stock" },
  { ticker: "2020.HK", name: "ANTA Sports", sector: "Consumer", type: "stock" },
  { ticker: "0027.HK", name: "Galaxy Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "1928.HK", name: "Sands China", sector: "Consumer", type: "stock" },
  { ticker: "0011.HK", name: "Hang Seng Bank", sector: "Finance", type: "stock" },
  { ticker: "0016.HK", name: "Sun Hung Kai Properties", sector: "Real Estate", type: "stock" },
  { ticker: "0012.HK", name: "Henderson Land", sector: "Real Estate", type: "stock" },
  { ticker: "0017.HK", name: "New World Development", sector: "Real Estate", type: "stock" },
  { ticker: "0101.HK", name: "Hang Lung Properties", sector: "Real Estate", type: "stock" },
  { ticker: "0002.HK", name: "CLP Holdings", sector: "Utilities", type: "stock" },
  { ticker: "0003.HK", name: "HK & China Gas", sector: "Utilities", type: "stock" },
  { ticker: "0006.HK", name: "Power Assets", sector: "Utilities", type: "stock" },
  { ticker: "0066.HK", name: "MTR Corporation", sector: "Industrials", type: "stock" },
  { ticker: "0823.HK", name: "Link REIT", sector: "Real Estate", type: "stock" },
  { ticker: "2313.HK", name: "Shenzhou International", sector: "Consumer", type: "stock" },
  { ticker: "0981.HK", name: "SMIC", sector: "Technology", type: "stock" },
  { ticker: "0268.HK", name: "Kingdee International", sector: "Technology", type: "stock" },
  { ticker: "9961.HK", name: "Trip.com Group", sector: "Consumer", type: "stock" },
  { ticker: "6098.HK", name: "Country Garden Services", sector: "Real Estate", type: "stock" },
  { ticker: "7203.T", name: "Toyota Motor", sector: "Consumer", type: "stock" },
  { ticker: "6758.T", name: "Sony Group", sector: "Technology", type: "stock" },
  { ticker: "6861.T", name: "Keyence", sector: "Technology", type: "stock" },
  { ticker: "9984.T", name: "SoftBank Group", sector: "Technology", type: "stock" },
  { ticker: "8306.T", name: "MUFG", sector: "Finance", type: "stock" },
  { ticker: "8316.T", name: "Sumitomo Mitsui", sector: "Finance", type: "stock" },
  { ticker: "9433.T", name: "KDDI", sector: "Telecom", type: "stock" },
  { ticker: "9432.T", name: "NTT", sector: "Telecom", type: "stock" },
  { ticker: "6501.T", name: "Hitachi", sector: "Technology", type: "stock" },
  { ticker: "6902.T", name: "Denso", sector: "Consumer", type: "stock" },
  { ticker: "7741.T", name: "HOYA", sector: "Healthcare", type: "stock" },
  { ticker: "4519.T", name: "Chugai Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "4568.T", name: "Daiichi Sankyo", sector: "Healthcare", type: "stock" },
  { ticker: "4502.T", name: "Takeda Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "4063.T", name: "Shin-Etsu Chemical", sector: "Materials", type: "stock" },
  { ticker: "6098.T", name: "Recruit Holdings", sector: "Industrials", type: "stock" },
  { ticker: "6367.T", name: "Daikin Industries", sector: "Industrials", type: "stock" },
  { ticker: "7974.T", name: "Nintendo", sector: "Technology", type: "stock" },
  { ticker: "4661.T", name: "Oriental Land", sector: "Consumer", type: "stock" },
  { ticker: "8035.T", name: "Tokyo Electron", sector: "Technology", type: "stock" },
  { ticker: "6594.T", name: "Nidec", sector: "Industrials", type: "stock" },
  { ticker: "7267.T", name: "Honda Motor", sector: "Consumer", type: "stock" },
  { ticker: "6981.T", name: "Murata Manufacturing", sector: "Technology", type: "stock" },
  { ticker: "8001.T", name: "ITOCHU", sector: "Industrials", type: "stock" },
  { ticker: "8058.T", name: "Mitsubishi Corporation", sector: "Industrials", type: "stock" },
  { ticker: "8031.T", name: "Mitsui & Co", sector: "Industrials", type: "stock" },
  { ticker: "8053.T", name: "Sumitomo Corporation", sector: "Industrials", type: "stock" },
  { ticker: "8002.T", name: "Marubeni", sector: "Industrials", type: "stock" },
  { ticker: "9983.T", name: "Fast Retailing", sector: "Consumer", type: "stock" },
  { ticker: "4901.T", name: "Fujifilm", sector: "Technology", type: "stock" },
  { ticker: "6954.T", name: "Fanuc", sector: "Industrials", type: "stock" },
  { ticker: "6273.T", name: "SMC Corporation", sector: "Industrials", type: "stock" },
  { ticker: "6971.T", name: "Kyocera", sector: "Technology", type: "stock" },
  { ticker: "6702.T", name: "Fujitsu", sector: "Technology", type: "stock" },
  { ticker: "7751.T", name: "Canon", sector: "Technology", type: "stock" },
  { ticker: "4543.T", name: "Terumo", sector: "Healthcare", type: "stock" },
  { ticker: "6301.T", name: "Komatsu", sector: "Industrials", type: "stock" },
  { ticker: "7011.T", name: "Mitsubishi Heavy", sector: "Industrials", type: "stock" },
  { ticker: "2914.T", name: "Japan Tobacco", sector: "Consumer", type: "stock" },
  { ticker: "2802.T", name: "Ajinomoto", sector: "Consumer", type: "stock" },
  { ticker: "005930.KS", name: "Samsung Electronics", sector: "Technology", type: "stock" },
  { ticker: "000660.KS", name: "SK Hynix", sector: "Technology", type: "stock" },
  { ticker: "035420.KS", name: "NAVER", sector: "Technology", type: "stock" },
  { ticker: "035720.KS", name: "Kakao", sector: "Technology", type: "stock" },
  { ticker: "051910.KS", name: "LG Chem", sector: "Materials", type: "stock" },
  { ticker: "006400.KS", name: "Samsung SDI", sector: "Technology", type: "stock" },
  { ticker: "373220.KS", name: "LG Energy Solution", sector: "Technology", type: "stock" },
  { ticker: "207940.KS", name: "Samsung Biologics", sector: "Healthcare", type: "stock" },
  { ticker: "005380.KS", name: "Hyundai Motor", sector: "Consumer", type: "stock" },
  { ticker: "000270.KS", name: "Kia", sector: "Consumer", type: "stock" },
  { ticker: "068270.KS", name: "Celltrion", sector: "Healthcare", type: "stock" },
  { ticker: "055550.KS", name: "Shinhan Financial", sector: "Finance", type: "stock" },
  { ticker: "105560.KS", name: "KB Financial", sector: "Finance", type: "stock" },
  { ticker: "086790.KS", name: "Hana Financial", sector: "Finance", type: "stock" },
  { ticker: "316140.KS", name: "Woori Financial", sector: "Finance", type: "stock" },
  { ticker: "012330.KS", name: "Hyundai Mobis", sector: "Consumer", type: "stock" },
  { ticker: "034730.KS", name: "SK", sector: "Industrials", type: "stock" },
  { ticker: "010130.KS", name: "Korea Zinc", sector: "Materials", type: "stock" },
  { ticker: "009150.KS", name: "Samsung Electro-Mechanics", sector: "Technology", type: "stock" },
  { ticker: "066570.KS", name: "LG Electronics", sector: "Technology", type: "stock" },
  { ticker: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", type: "stock" },
  { ticker: "TCS.NS", name: "Tata Consultancy", sector: "Technology", type: "stock" },
  { ticker: "INFY.NS", name: "Infosys", sector: "Technology", type: "stock" },
  { ticker: "HDFCBANK.NS", name: "HDFC Bank", sector: "Finance", type: "stock" },
  { ticker: "ICICIBANK.NS", name: "ICICI Bank", sector: "Finance", type: "stock" },
  { ticker: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "Consumer", type: "stock" },
  { ticker: "SBIN.NS", name: "State Bank of India", sector: "Finance", type: "stock" },
  { ticker: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Finance", type: "stock" },
  { ticker: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", type: "stock" },
  { ticker: "ITC.NS", name: "ITC Limited", sector: "Consumer", type: "stock" },
  { ticker: "KOTAKBANK.NS", name: "Kotak Mahindra", sector: "Finance", type: "stock" },
  { ticker: "LT.NS", name: "Larsen & Toubro", sector: "Industrials", type: "stock" },
  { ticker: "AXISBANK.NS", name: "Axis Bank", sector: "Finance", type: "stock" },
  { ticker: "ASIANPAINT.NS", name: "Asian Paints", sector: "Materials", type: "stock" },
  { ticker: "MARUTI.NS", name: "Maruti Suzuki", sector: "Consumer", type: "stock" },
  { ticker: "SUNPHARMA.NS", name: "Sun Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "TITAN.NS", name: "Titan Company", sector: "Consumer", type: "stock" },
  { ticker: "WIPRO.NS", name: "Wipro", sector: "Technology", type: "stock" },
  { ticker: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Materials", type: "stock" },
  { ticker: "HCLTECH.NS", name: "HCL Technologies", sector: "Technology", type: "stock" },
  { ticker: "NESTLEIND.NS", name: "Nestlé India", sector: "Consumer", type: "stock" },
  { ticker: "TATASTEEL.NS", name: "Tata Steel", sector: "Materials", type: "stock" },
  { ticker: "POWERGRID.NS", name: "Power Grid Corp", sector: "Utilities", type: "stock" },
  { ticker: "NTPC.NS", name: "NTPC", sector: "Utilities", type: "stock" },
  { ticker: "ONGC.NS", name: "ONGC", sector: "Energy", type: "stock" },
  { ticker: "JSWSTEEL.NS", name: "JSW Steel", sector: "Materials", type: "stock" },
  { ticker: "TATAMOTORS.NS", name: "Tata Motors", sector: "Consumer", type: "stock" },
  { ticker: "ADANIENT.NS", name: "Adani Enterprises", sector: "Industrials", type: "stock" },
  { ticker: "ADANIPORTS.NS", name: "Adani Ports", sector: "Industrials", type: "stock" },
  { ticker: "TECHM.NS", name: "Tech Mahindra", sector: "Technology", type: "stock" },
  { ticker: "D05.SI", name: "DBS Group", sector: "Finance", type: "stock" },
  { ticker: "O39.SI", name: "OCBC Bank", sector: "Finance", type: "stock" },
  { ticker: "U11.SI", name: "UOB", sector: "Finance", type: "stock" },
  { ticker: "Z74.SI", name: "Singtel", sector: "Telecom", type: "stock" },
  { ticker: "BN4.SI", name: "Keppel", sector: "Industrials", type: "stock" },
  { ticker: "C38U.SI", name: "CapitaLand Integrated", sector: "Real Estate", type: "stock" },
  { ticker: "A17U.SI", name: "Ascendas REIT", sector: "Real Estate", type: "stock" },
  { ticker: "S63.SI", name: "ST Engineering", sector: "Industrials", type: "stock" },
  { ticker: "U96.SI", name: "Sembcorp Industries", sector: "Utilities", type: "stock" },
  { ticker: "BS6.SI", name: "YZJ Shipbuilding", sector: "Industrials", type: "stock" },
  { ticker: "C6L.SI", name: "Singapore Airlines", sector: "Industrials", type: "stock" },
  { ticker: "S58.SI", name: "SATS", sector: "Industrials", type: "stock" },
  { ticker: "V03.SI", name: "Venture Corporation", sector: "Technology", type: "stock" },
  { ticker: "S68.SI", name: "SGX", sector: "Finance", type: "stock" },
  { ticker: "N2IU.SI", name: "Mapletree Pan Asia", sector: "Real Estate", type: "stock" },
  { ticker: "H78.SI", name: "HongKong Land", sector: "Real Estate", type: "stock" },
];
