import { AssetEntry } from "./types";

export const moreEuropeanStocks: AssetEntry[] = [
  { ticker: "SAN.MC", name: "Banco Santander", sector: "Finance", type: "stock" },
  { ticker: "BBVA.MC", name: "BBVA", sector: "Finance", type: "stock" },
  { ticker: "TEF.MC", name: "Telefónica", sector: "Telecom", type: "stock" },
  { ticker: "ITX.MC", name: "Inditex", sector: "Consumer", type: "stock" },
  { ticker: "IBE.MC", name: "Iberdrola", sector: "Utilities", type: "stock" },
  { ticker: "REP.MC", name: "Repsol", sector: "Energy", type: "stock" },
  { ticker: "FER.MC", name: "Ferrovial", sector: "Industrials", type: "stock" },
  { ticker: "AMS.MC", name: "Amadeus IT", sector: "Technology", type: "stock" },
  { ticker: "CABK.MC", name: "CaixaBank", sector: "Finance", type: "stock" },
  { ticker: "MAP.MC", name: "MAPFRE", sector: "Finance", type: "stock" },
  { ticker: "ACS.MC", name: "ACS Group", sector: "Industrials", type: "stock" },
  { ticker: "GRF.MC", name: "Grifols", sector: "Healthcare", type: "stock" },
  { ticker: "CLNX.MC", name: "Cellnex Telecom", sector: "Communication", type: "stock" },
  { ticker: "ENG.MC", name: "Enagás", sector: "Utilities", type: "stock" },
  { ticker: "RED.MC", name: "Red Eléctrica", sector: "Utilities", type: "stock" },
  { ticker: "MRL.MC", name: "Merlin Properties", sector: "Real Estate", type: "stock" },
  { ticker: "COL.MC", name: "Inmobiliaria Colonial", sector: "Real Estate", type: "stock" },
  { ticker: "AENA.MC", name: "Aena", sector: "Industrials", type: "stock" },
  { ticker: "VIS.MC", name: "Viscofan", sector: "Consumer", type: "stock" },
  { ticker: "CIE.MC", name: "CIE Automotive", sector: "Industrials", type: "stock" },
  { ticker: "ENEL.MI", name: "Enel", sector: "Utilities", type: "stock" },
  { ticker: "ISP.MI", name: "Intesa Sanpaolo", sector: "Finance", type: "stock" },
  { ticker: "UCG.MI", name: "UniCredit", sector: "Finance", type: "stock" },
  { ticker: "ENI.MI", name: "ENI", sector: "Energy", type: "stock" },
  { ticker: "STM.MI", name: "STMicroelectronics", sector: "Technology", type: "stock" },
  { ticker: "G.MI", name: "Generali", sector: "Finance", type: "stock" },
  { ticker: "RACE.MI", name: "Ferrari", sector: "Consumer", type: "stock" },
  { ticker: "TIT.MI", name: "Telecom Italia", sector: "Telecom", type: "stock" },
  { ticker: "PST.MI", name: "Poste Italiane", sector: "Finance", type: "stock" },
  { ticker: "TEN.MI", name: "Tenaris", sector: "Energy", type: "stock" },
  { ticker: "PIRC.MI", name: "Pirelli", sector: "Consumer", type: "stock" },
  { ticker: "BAMI.MI", name: "Banco BPM", sector: "Finance", type: "stock" },
  { ticker: "MB.MI", name: "Mediobanca", sector: "Finance", type: "stock" },
  { ticker: "MONC.MI", name: "Moncler", sector: "Consumer", type: "stock" },
  { ticker: "CPR.MI", name: "Campari", sector: "Consumer", type: "stock" },
  { ticker: "PRY.MI", name: "Prysmian", sector: "Industrials", type: "stock" },
  { ticker: "SRG.MI", name: "Snam", sector: "Utilities", type: "stock" },
  { ticker: "REC.MI", name: "Recordati", sector: "Healthcare", type: "stock" },
  { ticker: "INWT.MI", name: "Inwit", sector: "Communication", type: "stock" },
  { ticker: "LDO.MI", name: "Leonardo", sector: "Industrials", type: "stock" },
  { ticker: "ASML.AS", name: "ASML Holding", sector: "Technology", type: "stock" },
  { ticker: "SHELL.AS", name: "Shell", sector: "Energy", type: "stock" },
  { ticker: "UNA.AS", name: "Unilever", sector: "Consumer", type: "stock" },
  { ticker: "PHIA.AS", name: "Philips", sector: "Healthcare", type: "stock" },
  { ticker: "INGA.AS", name: "ING Group", sector: "Finance", type: "stock" },
  { ticker: "ABN.AS", name: "ABN AMRO", sector: "Finance", type: "stock" },
  { ticker: "ADYEN.AS", name: "Adyen", sector: "Technology", type: "stock" },
  { ticker: "WKL.AS", name: "Wolters Kluwer", sector: "Technology", type: "stock" },
  { ticker: "ASM.AS", name: "ASM International", sector: "Technology", type: "stock" },
  { ticker: "AKZA.AS", name: "Akzo Nobel", sector: "Materials", type: "stock" },
  { ticker: "DSM.AS", name: "DSM", sector: "Materials", type: "stock" },
  { ticker: "NN.AS", name: "NN Group", sector: "Finance", type: "stock" },
  { ticker: "HEIA.AS", name: "Heineken", sector: "Consumer", type: "stock" },
  { ticker: "KPN.AS", name: "KPN", sector: "Telecom", type: "stock" },
  { ticker: "REN.AS", name: "RELX", sector: "Technology", type: "stock" },
  { ticker: "RAND.AS", name: "Randstad", sector: "Industrials", type: "stock" },
  { ticker: "AGN.AS", name: "Aegon", sector: "Finance", type: "stock" },
  { ticker: "BESI.AS", name: "BE Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "IMCD.AS", name: "IMCD", sector: "Materials", type: "stock" },
  { ticker: "LIGHT.AS", name: "Signify", sector: "Industrials", type: "stock" },
  { ticker: "NESN.SW", name: "Nestlé", sector: "Consumer", type: "stock" },
  { ticker: "ROG.SW", name: "Roche", sector: "Healthcare", type: "stock" },
  { ticker: "NOVN.SW", name: "Novartis", sector: "Healthcare", type: "stock" },
  { ticker: "UBSG.SW", name: "UBS Group", sector: "Finance", type: "stock" },
  { ticker: "CSGN.SW", name: "Credit Suisse", sector: "Finance", type: "stock" },
  { ticker: "ZURN.SW", name: "Zurich Insurance", sector: "Finance", type: "stock" },
  { ticker: "ABBN.SW", name: "ABB", sector: "Industrials", type: "stock" },
  { ticker: "SREN.SW", name: "Swiss Re", sector: "Finance", type: "stock" },
  { ticker: "GIVN.SW", name: "Givaudan", sector: "Materials", type: "stock" },
  { ticker: "SIKA.SW", name: "Sika", sector: "Materials", type: "stock" },
  { ticker: "LONN.SW", name: "Lonza Group", sector: "Healthcare", type: "stock" },
  { ticker: "GEBN.SW", name: "Geberit", sector: "Industrials", type: "stock" },
  { ticker: "SCMN.SW", name: "Swisscom", sector: "Telecom", type: "stock" },
  { ticker: "SLHN.SW", name: "Swiss Life", sector: "Finance", type: "stock" },
  { ticker: "BALN.SW", name: "Bâloise", sector: "Finance", type: "stock" },
  { ticker: "STMN.SW", name: "Straumann", sector: "Healthcare", type: "stock" },
  { ticker: "BARN.SW", name: "Barry Callebaut", sector: "Consumer", type: "stock" },
  { ticker: "SGSN.SW", name: "SGS", sector: "Industrials", type: "stock" },
  { ticker: "TEMN.SW", name: "Temenos", sector: "Technology", type: "stock" },
  { ticker: "VACN.SW", name: "VAT Group", sector: "Technology", type: "stock" },
  { ticker: "ERIC-B.ST", name: "Ericsson", sector: "Technology", type: "stock" },
  { ticker: "VOLV-B.ST", name: "Volvo", sector: "Industrials", type: "stock" },
  { ticker: "ATCO-A.ST", name: "Atlas Copco", sector: "Industrials", type: "stock" },
  { ticker: "SEB-A.ST", name: "SEB", sector: "Finance", type: "stock" },
  { ticker: "SWED-A.ST", name: "Swedbank", sector: "Finance", type: "stock" },
  { ticker: "SHB-A.ST", name: "Handelsbanken", sector: "Finance", type: "stock" },
  { ticker: "HEXA-B.ST", name: "Hexagon", sector: "Technology", type: "stock" },
  { ticker: "SAND.ST", name: "Sandvik", sector: "Industrials", type: "stock" },
  { ticker: "SKF-B.ST", name: "SKF", sector: "Industrials", type: "stock" },
  { ticker: "INVE-B.ST", name: "Investor AB", sector: "Finance", type: "stock" },
  { ticker: "HM-B.ST", name: "H&M", sector: "Consumer", type: "stock" },
  { ticker: "ASSA-B.ST", name: "ASSA ABLOY", sector: "Industrials", type: "stock" },
  { ticker: "TEL2-B.ST", name: "Tele2", sector: "Telecom", type: "stock" },
  { ticker: "TELIA.ST", name: "Telia Company", sector: "Telecom", type: "stock" },
  { ticker: "ESSITY-B.ST", name: "Essity", sector: "Consumer", type: "stock" },
  { ticker: "ALFA.ST", name: "Alfa Laval", sector: "Industrials", type: "stock" },
  { ticker: "ELUX-B.ST", name: "Electrolux", sector: "Consumer", type: "stock" },
  { ticker: "KINV-B.ST", name: "Kinnevik", sector: "Finance", type: "stock" },
  { ticker: "GETI-B.ST", name: "Getinge", sector: "Healthcare", type: "stock" },
  { ticker: "SCA-B.ST", name: "SCA", sector: "Materials", type: "stock" },
  { ticker: "NOVO-B.CO", name: "Novo Nordisk", sector: "Healthcare", type: "stock" },
  { ticker: "MAERSK-B.CO", name: "Maersk", sector: "Industrials", type: "stock" },
  { ticker: "CARL-B.CO", name: "Carlsberg", sector: "Consumer", type: "stock" },
  { ticker: "VWS.CO", name: "Vestas Wind", sector: "Energy", type: "stock" },
  { ticker: "ORSTED.CO", name: "Ørsted", sector: "Utilities", type: "stock" },
  { ticker: "DSV.CO", name: "DSV", sector: "Industrials", type: "stock" },
  { ticker: "COLO-B.CO", name: "Coloplast", sector: "Healthcare", type: "stock" },
  { ticker: "PNDORA.CO", name: "Pandora", sector: "Consumer", type: "stock" },
  { ticker: "DEMANT.CO", name: "Demant", sector: "Healthcare", type: "stock" },
  { ticker: "GN.CO", name: "GN Store Nord", sector: "Healthcare", type: "stock" },
  { ticker: "GMAB.CO", name: "Genmab", sector: "Healthcare", type: "stock" },
  { ticker: "TRYG.CO", name: "Tryg", sector: "Finance", type: "stock" },
  { ticker: "DNORD.CO", name: "D/S Norden", sector: "Industrials", type: "stock" },
  { ticker: "JYSK.CO", name: "Jyske Bank", sector: "Finance", type: "stock" },
  { ticker: "AMBU-B.CO", name: "Ambu", sector: "Healthcare", type: "stock" },
  { ticker: "ROCK-B.CO", name: "Rockwool", sector: "Materials", type: "stock" },
  { ticker: "EQNR.OL", name: "Equinor", sector: "Energy", type: "stock" },
  { ticker: "DNB.OL", name: "DNB Bank", sector: "Finance", type: "stock" },
  { ticker: "TEL.OL", name: "Telenor", sector: "Telecom", type: "stock" },
  { ticker: "MOWI.OL", name: "Mowi", sector: "Consumer", type: "stock" },
  { ticker: "YAR.OL", name: "Yara International", sector: "Materials", type: "stock" },
  { ticker: "ORK.OL", name: "Orkla", sector: "Consumer", type: "stock" },
  { ticker: "SALM.OL", name: "SalMar", sector: "Consumer", type: "stock" },
  { ticker: "SUBC.OL", name: "Subsea 7", sector: "Energy", type: "stock" },
  { ticker: "AKERBP.OL", name: "Aker BP", sector: "Energy", type: "stock" },
  { ticker: "BAKKA.OL", name: "Bakkafrost", sector: "Consumer", type: "stock" },
  { ticker: "AKER.OL", name: "Aker", sector: "Industrials", type: "stock" },
  { ticker: "SCATC.OL", name: "Scatec", sector: "Energy", type: "stock" },
  { ticker: "TGS.OL", name: "TGS", sector: "Energy", type: "stock" },
  { ticker: "KAHOT.OL", name: "Kahoot!", sector: "Technology", type: "stock" },
  { ticker: "NOKIA.HE", name: "Nokia", sector: "Technology", type: "stock" },
  { ticker: "NESTE.HE", name: "Neste", sector: "Energy", type: "stock" },
  { ticker: "SAMPO.HE", name: "Sampo", sector: "Finance", type: "stock" },
  { ticker: "UPM.HE", name: "UPM-Kymmene", sector: "Materials", type: "stock" },
  { ticker: "STERV.HE", name: "Stora Enso", sector: "Materials", type: "stock" },
  { ticker: "FORTUM.HE", name: "Fortum", sector: "Utilities", type: "stock" },
  { ticker: "WRT1V.HE", name: "Wärtsilä", sector: "Industrials", type: "stock" },
  { ticker: "KNEBV.HE", name: "Kone", sector: "Industrials", type: "stock" },
  { ticker: "METSO.HE", name: "Metso", sector: "Industrials", type: "stock" },
  { ticker: "ELISA.HE", name: "Elisa", sector: "Telecom", type: "stock" },
  { ticker: "OUT1V.HE", name: "Outokumpu", sector: "Materials", type: "stock" },
  { ticker: "METSB.HE", name: "Metsä Board", sector: "Materials", type: "stock" },
  { ticker: "ORNBV.HE", name: "Orion", sector: "Healthcare", type: "stock" },
  { ticker: "CGCBV.HE", name: "Cargotec", sector: "Industrials", type: "stock" },
];
