import { AssetEntry } from "./types";

// Additional US stocks to boost total count — all real, tradeable on NYSE/NASDAQ
export const moreUSStocks: AssetEntry[] = [
  // Large-cap
  { ticker: "ABBV", name: "AbbVie Inc", sector: "Healthcare", type: "stock" },
  { ticker: "ACN", name: "Accenture plc", sector: "Technology", type: "stock" },
  { ticker: "ADSK", name: "Autodesk Inc", sector: "Technology", type: "stock" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", type: "stock" },
  { ticker: "AFL", name: "Aflac Inc", sector: "Finance", type: "stock" },
  { ticker: "AIG", name: "American Intl Group", sector: "Finance", type: "stock" },
  { ticker: "AIZ", name: "Assurant Inc", sector: "Finance", type: "stock" },
  { ticker: "AJG", name: "Arthur J. Gallagher", sector: "Finance", type: "stock" },
  { ticker: "ALB", name: "Albemarle Corp", sector: "Materials", type: "stock" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare", type: "stock" },
  { ticker: "ALL", name: "Allstate Corp", sector: "Finance", type: "stock" },
  { ticker: "ALLE", name: "Allegion plc", sector: "Industrials", type: "stock" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology", type: "stock" },
  { ticker: "ANSS", name: "ANSYS Inc", sector: "Technology", type: "stock" },
  { ticker: "AON", name: "Aon plc", sector: "Finance", type: "stock" },
  { ticker: "APA", name: "APA Corp", sector: "Energy", type: "stock" },
  { ticker: "APD", name: "Air Products & Chemicals", sector: "Materials", type: "stock" },
  { ticker: "APH", name: "Amphenol Corp", sector: "Technology", type: "stock" },
  { ticker: "ARE", name: "Alexandria Real Estate", sector: "Finance", type: "stock" },
  { ticker: "ATO", name: "Atmos Energy Corp", sector: "Utilities", type: "stock" },
  { ticker: "ATVI", name: "Activision Blizzard", sector: "Technology", type: "stock" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities", type: "stock" },
  { ticker: "AXP", name: "American Express", sector: "Finance", type: "stock" },
  { ticker: "AZO", name: "AutoZone Inc", sector: "Consumer", type: "stock" },
  { ticker: "BAX", name: "Baxter International", sector: "Healthcare", type: "stock" },
  { ticker: "BBWI", name: "Bath & Body Works", sector: "Consumer", type: "stock" },
  { ticker: "BDX", name: "Becton Dickinson", sector: "Healthcare", type: "stock" },
  { ticker: "BEN", name: "Franklin Resources", sector: "Finance", type: "stock" },
  { ticker: "BIIB", name: "Biogen Inc", sector: "Healthcare", type: "stock" },
  { ticker: "BIO", name: "Bio-Rad Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "BKR", name: "Baker Hughes Co", sector: "Energy", type: "stock" },
  { ticker: "BLK", name: "BlackRock Inc", sector: "Finance", type: "stock" },
  { ticker: "BR", name: "Broadridge Financial", sector: "Technology", type: "stock" },
  { ticker: "BRO", name: "Brown & Brown Inc", sector: "Finance", type: "stock" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "BWA", name: "BorgWarner Inc", sector: "Automotive", type: "stock" },
  { ticker: "CAG", name: "Conagra Brands", sector: "Consumer", type: "stock" },
  { ticker: "CAH", name: "Cardinal Health", sector: "Healthcare", type: "stock" },
  { ticker: "CARR", name: "Carrier Global", sector: "Industrials", type: "stock" },
  { ticker: "CAT", name: "Caterpillar Inc", sector: "Industrials", type: "stock" },
  { ticker: "CB", name: "Chubb Limited", sector: "Finance", type: "stock" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Finance", type: "stock" },
  { ticker: "CBRE", name: "CBRE Group Inc", sector: "Finance", type: "stock" },
  { ticker: "CCI", name: "Crown Castle Inc", sector: "Finance", type: "stock" },
  { ticker: "CCL", name: "Carnival Corp", sector: "Consumer", type: "stock" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology", type: "stock" },
  { ticker: "CDW", name: "CDW Corp", sector: "Technology", type: "stock" },
  { ticker: "CE", name: "Celanese Corp", sector: "Materials", type: "stock" },
  { ticker: "CEG", name: "Constellation Energy", sector: "Utilities", type: "stock" },
  { ticker: "CF", name: "CF Industries Holdings", sector: "Materials", type: "stock" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer", type: "stock" },
  { ticker: "CHRW", name: "C.H. Robinson", sector: "Industrials", type: "stock" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication", type: "stock" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare", type: "stock" },
  { ticker: "CINF", name: "Cincinnati Financial", sector: "Finance", type: "stock" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer", type: "stock" },
  { ticker: "CLX", name: "Clorox Co", sector: "Consumer", type: "stock" },
  { ticker: "CMA", name: "Comerica Inc", sector: "Finance", type: "stock" },
  { ticker: "CMCSA", name: "Comcast Corp", sector: "Communication", type: "stock" },
  { ticker: "CME", name: "CME Group Inc", sector: "Finance", type: "stock" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer", type: "stock" },
  { ticker: "CMI", name: "Cummins Inc", sector: "Industrials", type: "stock" },
  { ticker: "CMS", name: "CMS Energy Corp", sector: "Utilities", type: "stock" },
  { ticker: "CNC", name: "Centene Corp", sector: "Healthcare", type: "stock" },
  { ticker: "CNP", name: "CenterPoint Energy", sector: "Utilities", type: "stock" },
  { ticker: "COF", name: "Capital One Financial", sector: "Finance", type: "stock" },
  { ticker: "COO", name: "CooperCompanies", sector: "Healthcare", type: "stock" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", type: "stock" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer", type: "stock" },
  { ticker: "CPAY", name: "Corpay Inc", sector: "Technology", type: "stock" },
  { ticker: "CPB", name: "Campbell Soup", sector: "Consumer", type: "stock" },
  { ticker: "CPRT", name: "Copart Inc", sector: "Industrials", type: "stock" },
  { ticker: "CRL", name: "Charles River Labs", sector: "Healthcare", type: "stock" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", type: "stock" },
  { ticker: "CSGP", name: "CoStar Group", sector: "Technology", type: "stock" },
  { ticker: "CSX", name: "CSX Corp", sector: "Industrials", type: "stock" },
  { ticker: "CTAS", name: "Cintas Corp", sector: "Industrials", type: "stock" },
  { ticker: "CTLT", name: "Catalent Inc", sector: "Healthcare", type: "stock" },
  { ticker: "CTRA", name: "Coterra Energy", sector: "Energy", type: "stock" },
  { ticker: "CTSH", name: "Cognizant Technology", sector: "Technology", type: "stock" },
  { ticker: "CTVA", name: "Corteva Inc", sector: "Materials", type: "stock" },
  { ticker: "CVS", name: "CVS Health Corp", sector: "Healthcare", type: "stock" },
  { ticker: "CVX", name: "Chevron Corp", sector: "Energy", type: "stock" },
  { ticker: "CZR", name: "Caesars Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", type: "stock" },
  { ticker: "DAL", name: "Delta Air Lines", sector: "Industrials", type: "stock" },
  { ticker: "DD", name: "DuPont de Nemours", sector: "Materials", type: "stock" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials", type: "stock" },
  { ticker: "DFS", name: "Discover Financial", sector: "Finance", type: "stock" },
  { ticker: "DGX", name: "Quest Diagnostics", sector: "Healthcare", type: "stock" },
  { ticker: "DHI", name: "D.R. Horton Inc", sector: "Consumer", type: "stock" },
  { ticker: "DHR", name: "Danaher Corp", sector: "Healthcare", type: "stock" },
  { ticker: "DIS", name: "Walt Disney Co", sector: "Communication", type: "stock" },
  { ticker: "DISH", name: "EchoStar Corp", sector: "Communication", type: "stock" },
  { ticker: "DLR", name: "Digital Realty Trust", sector: "Finance", type: "stock" },
  { ticker: "DLTR", name: "Dollar Tree Inc", sector: "Consumer", type: "stock" },
  { ticker: "DOV", name: "Dover Corp", sector: "Industrials", type: "stock" },
  { ticker: "DOW", name: "Dow Inc", sector: "Materials", type: "stock" },
  { ticker: "DPZ", name: "Domino's Pizza", sector: "Consumer", type: "stock" },
  { ticker: "DRI", name: "Darden Restaurants", sector: "Consumer", type: "stock" },
  { ticker: "DTE", name: "DTE Energy Co", sector: "Utilities", type: "stock" },
  { ticker: "DUK", name: "Duke Energy Corp", sector: "Utilities", type: "stock" },
  { ticker: "DVA", name: "DaVita Inc", sector: "Healthcare", type: "stock" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy", type: "stock" },
  { ticker: "DXCM", name: "DexCom Inc", sector: "Healthcare", type: "stock" },
  { ticker: "EA", name: "Electronic Arts", sector: "Technology", type: "stock" },
  { ticker: "EBAY", name: "eBay Inc", sector: "Consumer", type: "stock" },
  { ticker: "ECL", name: "Ecolab Inc", sector: "Materials", type: "stock" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities", type: "stock" },
  { ticker: "EFX", name: "Equifax Inc", sector: "Industrials", type: "stock" },
  { ticker: "EIX", name: "Edison International", sector: "Utilities", type: "stock" },
  { ticker: "EL", name: "Estée Lauder", sector: "Consumer", type: "stock" },
  { ticker: "EMN", name: "Eastman Chemical", sector: "Materials", type: "stock" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials", type: "stock" },
  { ticker: "ENPH", name: "Enphase Energy", sector: "Energy", type: "stock" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy", type: "stock" },
  { ticker: "EPAM", name: "EPAM Systems", sector: "Technology", type: "stock" },
  { ticker: "EQIX", name: "Equinix Inc", sector: "Finance", type: "stock" },
  { ticker: "EQR", name: "Equity Residential", sector: "Finance", type: "stock" },
  { ticker: "EQT", name: "EQT Corp", sector: "Energy", type: "stock" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities", type: "stock" },
  { ticker: "ESS", name: "Essex Property Trust", sector: "Finance", type: "stock" },
  { ticker: "ETN", name: "Eaton Corp", sector: "Industrials", type: "stock" },
  { ticker: "ETR", name: "Entergy Corp", sector: "Utilities", type: "stock" },
  { ticker: "EVRG", name: "Evergy Inc", sector: "Utilities", type: "stock" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Healthcare", type: "stock" },
  { ticker: "EXC", name: "Exelon Corp", sector: "Utilities", type: "stock" },
  { ticker: "EXPD", name: "Expeditors International", sector: "Industrials", type: "stock" },
  { ticker: "EXPE", name: "Expedia Group", sector: "Consumer", type: "stock" },
  { ticker: "EXR", name: "Extra Space Storage", sector: "Finance", type: "stock" },
  { ticker: "F", name: "Ford Motor Co", sector: "Automotive", type: "stock" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", type: "stock" },
  { ticker: "FAST", name: "Fastenal Co", sector: "Industrials", type: "stock" },
  { ticker: "FBHS", name: "Fortune Brands Home", sector: "Industrials", type: "stock" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", type: "stock" },
  { ticker: "FDS", name: "FactSet Research", sector: "Finance", type: "stock" },
  { ticker: "FDX", name: "FedEx Corp", sector: "Industrials", type: "stock" },
  { ticker: "FE", name: "FirstEnergy Corp", sector: "Utilities", type: "stock" },
  { ticker: "FFIV", name: "F5 Inc", sector: "Technology", type: "stock" },
  { ticker: "FIS", name: "Fidelity National Info", sector: "Technology", type: "stock" },
  { ticker: "FISV", name: "Fiserv Inc", sector: "Technology", type: "stock" },
  { ticker: "FITB", name: "Fifth Third Bancorp", sector: "Finance", type: "stock" },
  { ticker: "FLT", name: "FLEETCOR Technologies", sector: "Technology", type: "stock" },
  { ticker: "FMC", name: "FMC Corp", sector: "Materials", type: "stock" },
  { ticker: "FOX", name: "Fox Corp", sector: "Communication", type: "stock" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrials", type: "stock" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials", type: "stock" },
  { ticker: "GEHC", name: "GE HealthCare", sector: "Healthcare", type: "stock" },
  { ticker: "GEN", name: "Gen Digital Inc", sector: "Technology", type: "stock" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer", type: "stock" },
  { ticker: "GL", name: "Globe Life Inc", sector: "Finance", type: "stock" },
  { ticker: "GLW", name: "Corning Inc", sector: "Technology", type: "stock" },
  { ticker: "GM", name: "General Motors", sector: "Automotive", type: "stock" },
  { ticker: "GNRC", name: "Generac Holdings", sector: "Industrials", type: "stock" },
  { ticker: "GOOG", name: "Alphabet Inc Class C", sector: "Technology", type: "stock" },
  { ticker: "GPC", name: "Genuine Parts Co", sector: "Consumer", type: "stock" },
  { ticker: "GPN", name: "Global Payments", sector: "Technology", type: "stock" },
  { ticker: "GRMN", name: "Garmin Ltd", sector: "Technology", type: "stock" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Finance", type: "stock" },
  { ticker: "GWW", name: "W.W. Grainger", sector: "Industrials", type: "stock" },
  { ticker: "HAL", name: "Halliburton Co", sector: "Energy", type: "stock" },
  { ticker: "HAS", name: "Hasbro Inc", sector: "Consumer", type: "stock" },
  { ticker: "HBAN", name: "Huntington Bancshares", sector: "Finance", type: "stock" },
  { ticker: "HCA", name: "HCA Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer", type: "stock" },
  { ticker: "HOLX", name: "Hologic Inc", sector: "Healthcare", type: "stock" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials", type: "stock" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", type: "stock" },
  { ticker: "HPQ", name: "HP Inc", sector: "Technology", type: "stock" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer", type: "stock" },
  { ticker: "HSIC", name: "Henry Schein Inc", sector: "Healthcare", type: "stock" },
  { ticker: "HST", name: "Host Hotels & Resorts", sector: "Finance", type: "stock" },
  { ticker: "HSY", name: "Hershey Co", sector: "Consumer", type: "stock" },
  { ticker: "HUBB", name: "Hubbell Inc", sector: "Industrials", type: "stock" },
  { ticker: "HUM", name: "Humana Inc", sector: "Healthcare", type: "stock" },
  { ticker: "HWM", name: "Howmet Aerospace", sector: "Industrials", type: "stock" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Finance", type: "stock" },
  { ticker: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "IEX", name: "IDEX Corp", sector: "Industrials", type: "stock" },
  { ticker: "IFF", name: "International Flavors", sector: "Materials", type: "stock" },
  { ticker: "ILMN", name: "Illumina Inc", sector: "Healthcare", type: "stock" },
  { ticker: "INCY", name: "Incyte Corp", sector: "Healthcare", type: "stock" },
  { ticker: "IP", name: "International Paper", sector: "Materials", type: "stock" },
  { ticker: "IPG", name: "Interpublic Group", sector: "Communication", type: "stock" },
  { ticker: "IQV", name: "IQVIA Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "IR", name: "Ingersoll Rand", sector: "Industrials", type: "stock" },
  { ticker: "IRM", name: "Iron Mountain", sector: "Finance", type: "stock" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "stock" },
  { ticker: "IT", name: "Gartner Inc", sector: "Technology", type: "stock" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials", type: "stock" },
  { ticker: "IVZ", name: "Invesco Ltd", sector: "Finance", type: "stock" },
  { ticker: "J", name: "Jacobs Solutions", sector: "Industrials", type: "stock" },
  { ticker: "JBHT", name: "J.B. Hunt Transport", sector: "Industrials", type: "stock" },
  { ticker: "JCI", name: "Johnson Controls", sector: "Industrials", type: "stock" },
  { ticker: "JKHY", name: "Jack Henry & Associates", sector: "Technology", type: "stock" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", type: "stock" },
  { ticker: "JNPR", name: "Juniper Networks", sector: "Technology", type: "stock" },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Finance", type: "stock" },
  { ticker: "K", name: "Kellanova", sector: "Consumer", type: "stock" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer", type: "stock" },
  { ticker: "KEY", name: "KeyCorp", sector: "Finance", type: "stock" },
  { ticker: "KEYS", name: "Keysight Technologies", sector: "Technology", type: "stock" },
  { ticker: "KHC", name: "Kraft Heinz Co", sector: "Consumer", type: "stock" },
  { ticker: "KIM", name: "Kimco Realty", sector: "Finance", type: "stock" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer", type: "stock" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy", type: "stock" },
  { ticker: "KMX", name: "CarMax Inc", sector: "Consumer", type: "stock" },
  { ticker: "KO", name: "Coca-Cola Co", sector: "Consumer", type: "stock" },
  { ticker: "KR", name: "Kroger Co", sector: "Consumer", type: "stock" },
  { ticker: "L", name: "Loews Corp", sector: "Finance", type: "stock" },
  { ticker: "LDOS", name: "Leidos Holdings", sector: "Industrials", type: "stock" },
  { ticker: "LEN", name: "Lennar Corp", sector: "Consumer", type: "stock" },
  { ticker: "LH", name: "Labcorp Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "LHX", name: "L3Harris Technologies", sector: "Industrials", type: "stock" },
  { ticker: "LIN", name: "Linde plc", sector: "Materials", type: "stock" },
  { ticker: "LKQ", name: "LKQ Corp", sector: "Consumer", type: "stock" },
  { ticker: "LLY", name: "Eli Lilly", sector: "Healthcare", type: "stock" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials", type: "stock" },
  { ticker: "LNT", name: "Alliant Energy", sector: "Utilities", type: "stock" },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer", type: "stock" },
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer", type: "stock" },
  { ticker: "LUV", name: "Southwest Airlines", sector: "Industrials", type: "stock" },
  { ticker: "LVS", name: "Las Vegas Sands", sector: "Consumer", type: "stock" },
  { ticker: "LW", name: "Lamb Weston", sector: "Consumer", type: "stock" },
  { ticker: "LYB", name: "LyondellBasell", sector: "Materials", type: "stock" },
  { ticker: "LYV", name: "Live Nation Entertainment", sector: "Communication", type: "stock" },
  { ticker: "MA", name: "Mastercard Inc", sector: "Finance", type: "stock" },
  { ticker: "MAA", name: "Mid-America Apartment", sector: "Finance", type: "stock" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer", type: "stock" },
  { ticker: "MAS", name: "Masco Corp", sector: "Industrials", type: "stock" },
  { ticker: "MCD", name: "McDonald's Corp", sector: "Consumer", type: "stock" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology", type: "stock" },
  { ticker: "MCK", name: "McKesson Corp", sector: "Healthcare", type: "stock" },
  { ticker: "MCO", name: "Moody's Corp", sector: "Finance", type: "stock" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer", type: "stock" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare", type: "stock" },
  { ticker: "MET", name: "MetLife Inc", sector: "Finance", type: "stock" },
  { ticker: "MGM", name: "MGM Resorts", sector: "Consumer", type: "stock" },
  { ticker: "MHK", name: "Mohawk Industries", sector: "Industrials", type: "stock" },
  { ticker: "MKC", name: "McCormick & Company", sector: "Consumer", type: "stock" },
  { ticker: "MKTX", name: "MarketAxess Holdings", sector: "Finance", type: "stock" },
  { ticker: "MLM", name: "Martin Marietta Materials", sector: "Materials", type: "stock" },
  { ticker: "MMC", name: "Marsh & McLennan", sector: "Finance", type: "stock" },
  { ticker: "MMM", name: "3M Company", sector: "Industrials", type: "stock" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer", type: "stock" },
  { ticker: "MO", name: "Altria Group", sector: "Consumer", type: "stock" },
  { ticker: "MOH", name: "Molina Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "MOS", name: "Mosaic Co", sector: "Materials", type: "stock" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", type: "stock" },
  { ticker: "MPWR", name: "Monolithic Power Systems", sector: "Technology", type: "stock" },
  { ticker: "MRK", name: "Merck & Co", sector: "Healthcare", type: "stock" },
  { ticker: "MRNA", name: "Moderna Inc", sector: "Healthcare", type: "stock" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Finance", type: "stock" },
  { ticker: "MSCI", name: "MSCI Inc", sector: "Finance", type: "stock" },
  { ticker: "MSI", name: "Motorola Solutions", sector: "Technology", type: "stock" },
  { ticker: "MTB", name: "M&T Bank Corp", sector: "Finance", type: "stock" },
  { ticker: "MTCH", name: "Match Group", sector: "Communication", type: "stock" },
  { ticker: "MTD", name: "Mettler-Toledo Intl", sector: "Healthcare", type: "stock" },
  { ticker: "NDAQ", name: "Nasdaq Inc", sector: "Finance", type: "stock" },
  { ticker: "NDSN", name: "Nordson Corp", sector: "Industrials", type: "stock" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities", type: "stock" },
  { ticker: "NEM", name: "Newmont Corp", sector: "Materials", type: "stock" },
  { ticker: "NI", name: "NiSource Inc", sector: "Utilities", type: "stock" },
  { ticker: "NKE", name: "Nike Inc", sector: "Consumer", type: "stock" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrials", type: "stock" },
  { ticker: "NRG", name: "NRG Energy", sector: "Utilities", type: "stock" },
  { ticker: "NSC", name: "Norfolk Southern", sector: "Industrials", type: "stock" },
  { ticker: "NTAP", name: "NetApp Inc", sector: "Technology", type: "stock" },
  { ticker: "NTRS", name: "Northern Trust", sector: "Finance", type: "stock" },
  { ticker: "NUE", name: "Nucor Corp", sector: "Materials", type: "stock" },
  { ticker: "NWSA", name: "News Corp", sector: "Communication", type: "stock" },
  { ticker: "O", name: "Realty Income Corp", sector: "Finance", type: "stock" },
  { ticker: "ODFL", name: "Old Dominion Freight", sector: "Industrials", type: "stock" },
  { ticker: "OKE", name: "ONEOK Inc", sector: "Energy", type: "stock" },
  { ticker: "OMC", name: "Omnicom Group", sector: "Communication", type: "stock" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ORCL", name: "Oracle Corp", sector: "Technology", type: "stock" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer", type: "stock" },
  { ticker: "OTIS", name: "Otis Worldwide", sector: "Industrials", type: "stock" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", type: "stock" },
  { ticker: "PARA", name: "Paramount Global", sector: "Communication", type: "stock" },
  { ticker: "PAYC", name: "Paycom Software", sector: "Technology", type: "stock" },
  { ticker: "PAYX", name: "Paychex Inc", sector: "Technology", type: "stock" },
  { ticker: "PCAR", name: "PACCAR Inc", sector: "Industrials", type: "stock" },
  { ticker: "PCG", name: "PG&E Corp", sector: "Utilities", type: "stock" },
  { ticker: "PEAK", name: "Healthpeak Properties", sector: "Finance", type: "stock" },
  { ticker: "PEG", name: "Public Service Enterprise", sector: "Utilities", type: "stock" },
  { ticker: "PEP", name: "PepsiCo Inc", sector: "Consumer", type: "stock" },
  { ticker: "PFE", name: "Pfizer Inc", sector: "Healthcare", type: "stock" },
  { ticker: "PFG", name: "Principal Financial", sector: "Finance", type: "stock" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer", type: "stock" },
  { ticker: "PGR", name: "Progressive Corp", sector: "Finance", type: "stock" },
  { ticker: "PH", name: "Parker-Hannifin", sector: "Industrials", type: "stock" },
  { ticker: "PHM", name: "PulteGroup Inc", sector: "Consumer", type: "stock" },
  { ticker: "PKG", name: "Packaging Corp of America", sector: "Materials", type: "stock" },
  { ticker: "PLD", name: "Prologis Inc", sector: "Finance", type: "stock" },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer", type: "stock" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Finance", type: "stock" },
  { ticker: "PNR", name: "Pentair plc", sector: "Industrials", type: "stock" },
  { ticker: "PNW", name: "Pinnacle West Capital", sector: "Utilities", type: "stock" },
  { ticker: "POOL", name: "Pool Corp", sector: "Consumer", type: "stock" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials", type: "stock" },
  { ticker: "PPL", name: "PPL Corp", sector: "Utilities", type: "stock" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Finance", type: "stock" },
  { ticker: "PSA", name: "Public Storage", sector: "Finance", type: "stock" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", type: "stock" },
  { ticker: "PTC", name: "PTC Inc", sector: "Technology", type: "stock" },
  { ticker: "PVH", name: "PVH Corp", sector: "Consumer", type: "stock" },
  { ticker: "PWR", name: "Quanta Services", sector: "Industrials", type: "stock" },
  { ticker: "PYPL", name: "PayPal Holdings", sector: "Technology", type: "stock" },
  { ticker: "QRVO", name: "Qorvo Inc", sector: "Technology", type: "stock" },
  { ticker: "RCL", name: "Royal Caribbean Group", sector: "Consumer", type: "stock" },
  { ticker: "RE", name: "Everest Group", sector: "Finance", type: "stock" },
  { ticker: "REG", name: "Regency Centers", sector: "Finance", type: "stock" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "RF", name: "Regions Financial", sector: "Finance", type: "stock" },
  { ticker: "RHI", name: "Robert Half International", sector: "Industrials", type: "stock" },
  { ticker: "RJF", name: "Raymond James Financial", sector: "Finance", type: "stock" },
  { ticker: "RL", name: "Ralph Lauren", sector: "Consumer", type: "stock" },
  { ticker: "RMD", name: "ResMed Inc", sector: "Healthcare", type: "stock" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrials", type: "stock" },
  { ticker: "ROL", name: "Rollins Inc", sector: "Industrials", type: "stock" },
  { ticker: "ROP", name: "Roper Technologies", sector: "Technology", type: "stock" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer", type: "stock" },
  { ticker: "RSG", name: "Republic Services", sector: "Industrials", type: "stock" },
  { ticker: "RTX", name: "RTX Corp", sector: "Industrials", type: "stock" },
  { ticker: "SBAC", name: "SBA Communications", sector: "Finance", type: "stock" },
  { ticker: "SBUX", name: "Starbucks Corp", sector: "Consumer", type: "stock" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Finance", type: "stock" },
  { ticker: "SEE", name: "Sealed Air Corp", sector: "Materials", type: "stock" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", type: "stock" },
  { ticker: "SIVB", name: "SVB Financial Group", sector: "Finance", type: "stock" },
  { ticker: "SJM", name: "J.M. Smucker", sector: "Consumer", type: "stock" },
  { ticker: "SLB", name: "Schlumberger Ltd", sector: "Energy", type: "stock" },
  { ticker: "SNA", name: "Snap-on Inc", sector: "Industrials", type: "stock" },
  { ticker: "SNPS", name: "Synopsys Inc", sector: "Technology", type: "stock" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", type: "stock" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Finance", type: "stock" },
  { ticker: "SPGI", name: "S&P Global", sector: "Finance", type: "stock" },
  { ticker: "SRE", name: "Sempra Energy", sector: "Utilities", type: "stock" },
  { ticker: "STE", name: "STERIS plc", sector: "Healthcare", type: "stock" },
  { ticker: "STT", name: "State Street Corp", sector: "Finance", type: "stock" },
  { ticker: "STX", name: "Seagate Technology", sector: "Technology", type: "stock" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer", type: "stock" },
  { ticker: "SWK", name: "Stanley Black & Decker", sector: "Industrials", type: "stock" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology", type: "stock" },
  { ticker: "SYF", name: "Synchrony Financial", sector: "Finance", type: "stock" },
  { ticker: "SYK", name: "Stryker Corp", sector: "Healthcare", type: "stock" },
  { ticker: "SYY", name: "Sysco Corp", sector: "Consumer", type: "stock" },
  { ticker: "T", name: "AT&T Inc", sector: "Telecom", type: "stock" },
  { ticker: "TAP", name: "Molson Coors Beverage", sector: "Consumer", type: "stock" },
  { ticker: "TDG", name: "TransDigm Group", sector: "Industrials", type: "stock" },
  { ticker: "TDY", name: "Teledyne Technologies", sector: "Technology", type: "stock" },
  { ticker: "TECH", name: "Bio-Techne Corp", sector: "Healthcare", type: "stock" },
  { ticker: "TEL", name: "TE Connectivity", sector: "Technology", type: "stock" },
  { ticker: "TER", name: "Teradyne Inc", sector: "Technology", type: "stock" },
  { ticker: "TFC", name: "Truist Financial", sector: "Finance", type: "stock" },
  { ticker: "TFX", name: "Teleflex Inc", sector: "Healthcare", type: "stock" },
  { ticker: "TGT", name: "Target Corp", sector: "Consumer", type: "stock" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer", type: "stock" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Telecom", type: "stock" },
  { ticker: "TPR", name: "Tapestry Inc", sector: "Consumer", type: "stock" },
  { ticker: "TRGP", name: "Targa Resources", sector: "Energy", type: "stock" },
  { ticker: "TRMB", name: "Trimble Inc", sector: "Technology", type: "stock" },
  { ticker: "TRV", name: "Travelers Companies", sector: "Finance", type: "stock" },
  { ticker: "TSCO", name: "Tractor Supply", sector: "Consumer", type: "stock" },
  { ticker: "TSLA", name: "Tesla Inc", sector: "Automotive", type: "stock" },
  { ticker: "TSN", name: "Tyson Foods", sector: "Consumer", type: "stock" },
  { ticker: "TT", name: "Trane Technologies", sector: "Industrials", type: "stock" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Technology", type: "stock" },
  { ticker: "TXT", name: "Textron Inc", sector: "Industrials", type: "stock" },
  { ticker: "TYL", name: "Tyler Technologies", sector: "Technology", type: "stock" },
  { ticker: "UAL", name: "United Airlines", sector: "Industrials", type: "stock" },
  { ticker: "UDR", name: "UDR Inc", sector: "Finance", type: "stock" },
  { ticker: "UHS", name: "Universal Health Services", sector: "Healthcare", type: "stock" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare", type: "stock" },
  { ticker: "UNP", name: "Union Pacific", sector: "Industrials", type: "stock" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials", type: "stock" },
  { ticker: "URI", name: "United Rentals", sector: "Industrials", type: "stock" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Finance", type: "stock" },
  { ticker: "V", name: "Visa Inc", sector: "Finance", type: "stock" },
  { ticker: "VFC", name: "VF Corp", sector: "Consumer", type: "stock" },
  { ticker: "VICI", name: "VICI Properties", sector: "Finance", type: "stock" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", type: "stock" },
  { ticker: "VMC", name: "Vulcan Materials", sector: "Materials", type: "stock" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Technology", type: "stock" },
  { ticker: "VRSN", name: "VeriSign Inc", sector: "Technology", type: "stock" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "VTR", name: "Ventas Inc", sector: "Finance", type: "stock" },
  { ticker: "VTRS", name: "Viatris Inc", sector: "Healthcare", type: "stock" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Telecom", type: "stock" },
  { ticker: "WAB", name: "Westinghouse Air Brake", sector: "Industrials", type: "stock" },
  { ticker: "WAT", name: "Waters Corp", sector: "Healthcare", type: "stock" },
  { ticker: "WBA", name: "Walgreens Boots Alliance", sector: "Healthcare", type: "stock" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Communication", type: "stock" },
  { ticker: "WDC", name: "Western Digital", sector: "Technology", type: "stock" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities", type: "stock" },
  { ticker: "WELL", name: "Welltower Inc", sector: "Finance", type: "stock" },
  { ticker: "WFC", name: "Wells Fargo & Co", sector: "Finance", type: "stock" },
  { ticker: "WHR", name: "Whirlpool Corp", sector: "Consumer", type: "stock" },
  { ticker: "WM", name: "Waste Management", sector: "Industrials", type: "stock" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy", type: "stock" },
  { ticker: "WMT", name: "Walmart Inc", sector: "Consumer", type: "stock" },
  { ticker: "WRB", name: "W.R. Berkley Corp", sector: "Finance", type: "stock" },
  { ticker: "WRK", name: "WestRock Co", sector: "Materials", type: "stock" },
  { ticker: "WST", name: "West Pharmaceutical", sector: "Healthcare", type: "stock" },
  { ticker: "WTW", name: "Willis Towers Watson", sector: "Finance", type: "stock" },
  { ticker: "WY", name: "Weyerhaeuser Co", sector: "Finance", type: "stock" },
  { ticker: "WYNN", name: "Wynn Resorts", sector: "Consumer", type: "stock" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", type: "stock" },
  { ticker: "XOM", name: "Exxon Mobil", sector: "Energy", type: "stock" },
  { ticker: "XRAY", name: "DENTSPLY SIRONA", sector: "Healthcare", type: "stock" },
  { ticker: "XYL", name: "Xylem Inc", sector: "Industrials", type: "stock" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer", type: "stock" },
  { ticker: "ZBH", name: "Zimmer Biomet", sector: "Healthcare", type: "stock" },
  { ticker: "ZBRA", name: "Zebra Technologies", sector: "Technology", type: "stock" },
  { ticker: "ZTS", name: "Zoetis Inc", sector: "Healthcare", type: "stock" },
];
