import { AssetEntry } from "./types";

export const moreInternationalStocks: AssetEntry[] = [
  { ticker: "CBA.AX", name: "Commonwealth Bank", sector: "Finance", type: "stock" },
  { ticker: "BHP.AX", name: "BHP Group", sector: "Materials", type: "stock" },
  { ticker: "CSL.AX", name: "CSL Limited", sector: "Healthcare", type: "stock" },
  { ticker: "NAB.AX", name: "National Australia Bank", sector: "Finance", type: "stock" },
  { ticker: "WBC.AX", name: "Westpac Banking", sector: "Finance", type: "stock" },
  { ticker: "ANZ.AX", name: "ANZ Group", sector: "Finance", type: "stock" },
  { ticker: "MQG.AX", name: "Macquarie Group", sector: "Finance", type: "stock" },
  { ticker: "WDS.AX", name: "Woodside Energy", sector: "Energy", type: "stock" },
  { ticker: "WES.AX", name: "Wesfarmers", sector: "Consumer", type: "stock" },
  { ticker: "WOW.AX", name: "Woolworths Group", sector: "Consumer", type: "stock" },
  { ticker: "TLS.AX", name: "Telstra Group", sector: "Telecom", type: "stock" },
  { ticker: "FMG.AX", name: "Fortescue", sector: "Materials", type: "stock" },
  { ticker: "RIO.AX", name: "Rio Tinto AU", sector: "Materials", type: "stock" },
  { ticker: "ALL.AX", name: "Aristocrat Leisure", sector: "Technology", type: "stock" },
  { ticker: "REA.AX", name: "REA Group", sector: "Technology", type: "stock" },
  { ticker: "TCL.AX", name: "Transurban", sector: "Industrials", type: "stock" },
  { ticker: "GMG.AX", name: "Goodman Group", sector: "Real Estate", type: "stock" },
  { ticker: "COL.AX", name: "Coles Group", sector: "Consumer", type: "stock" },
  { ticker: "SHL.AX", name: "Sonic Healthcare", sector: "Healthcare", type: "stock" },
  { ticker: "RMD.AX", name: "ResMed", sector: "Healthcare", type: "stock" },
  { ticker: "QBE.AX", name: "QBE Insurance", sector: "Finance", type: "stock" },
  { ticker: "SUN.AX", name: "Suncorp", sector: "Finance", type: "stock" },
  { ticker: "IAG.AX", name: "Insurance Australia", sector: "Finance", type: "stock" },
  { ticker: "ORG.AX", name: "Origin Energy", sector: "Energy", type: "stock" },
  { ticker: "STO.AX", name: "Santos", sector: "Energy", type: "stock" },
  { ticker: "MIN.AX", name: "Mineral Resources", sector: "Materials", type: "stock" },
  { ticker: "NCM.AX", name: "Newcrest Mining", sector: "Materials", type: "stock" },
  { ticker: "S32.AX", name: "South32", sector: "Materials", type: "stock" },
  { ticker: "AGL.AX", name: "AGL Energy", sector: "Utilities", type: "stock" },
  { ticker: "JHX.AX", name: "James Hardie", sector: "Materials", type: "stock" },
  { ticker: "RY.TO", name: "Royal Bank of Canada", sector: "Finance", type: "stock" },
  { ticker: "TD.TO", name: "Toronto-Dominion", sector: "Finance", type: "stock" },
  { ticker: "BNS.TO", name: "Bank of Nova Scotia", sector: "Finance", type: "stock" },
  { ticker: "BMO.TO", name: "Bank of Montreal", sector: "Finance", type: "stock" },
  { ticker: "CM.TO", name: "CIBC", sector: "Finance", type: "stock" },
  { ticker: "ENB.TO", name: "Enbridge", sector: "Energy", type: "stock" },
  { ticker: "TRP.TO", name: "TC Energy", sector: "Energy", type: "stock" },
  { ticker: "CNQ.TO", name: "Canadian Natural", sector: "Energy", type: "stock" },
  { ticker: "SU.TO", name: "Suncor Energy", sector: "Energy", type: "stock" },
  { ticker: "CVE.TO", name: "Cenovus Energy", sector: "Energy", type: "stock" },
  { ticker: "CP.TO", name: "Canadian Pacific Kansas City", sector: "Industrials", type: "stock" },
  { ticker: "CNR.TO", name: "CN Rail", sector: "Industrials", type: "stock" },
  { ticker: "MFC.TO", name: "Manulife Financial", sector: "Finance", type: "stock" },
  { ticker: "SLF.TO", name: "Sun Life Financial", sector: "Finance", type: "stock" },
  { ticker: "GWO.TO", name: "Great-West Lifeco", sector: "Finance", type: "stock" },
  { ticker: "IAG.TO", name: "iA Financial", sector: "Finance", type: "stock" },
  { ticker: "RCI-B.TO", name: "Rogers Communications", sector: "Telecom", type: "stock" },
  { ticker: "T.TO", name: "Telus", sector: "Telecom", type: "stock" },
  { ticker: "BCE.TO", name: "BCE", sector: "Telecom", type: "stock" },
  { ticker: "QSR.TO", name: "Restaurant Brands", sector: "Consumer", type: "stock" },
  { ticker: "ATD.TO", name: "Alimentation Couche-Tard", sector: "Consumer", type: "stock" },
  { ticker: "L.TO", name: "Loblaw", sector: "Consumer", type: "stock" },
  { ticker: "WFG.TO", name: "West Fraser Timber", sector: "Materials", type: "stock" },
  { ticker: "NTR.TO", name: "Nutrien", sector: "Materials", type: "stock" },
  { ticker: "ABX.TO", name: "Barrick Gold", sector: "Materials", type: "stock" },
  { ticker: "FNV.TO", name: "Franco-Nevada", sector: "Materials", type: "stock" },
  { ticker: "WPM.TO", name: "Wheaton Precious", sector: "Materials", type: "stock" },
  { ticker: "K.TO", name: "Kinross Gold", sector: "Materials", type: "stock" },
  { ticker: "SHOP.TO", name: "Shopify", sector: "Technology", type: "stock" },
  { ticker: "CSU.TO", name: "Constellation Software", sector: "Technology", type: "stock" },
  { ticker: "OTEX.TO", name: "Open Text", sector: "Technology", type: "stock" },
  { ticker: "BB.TO", name: "BlackBerry", sector: "Technology", type: "stock" },
  { ticker: "SAP.DE", name: "SAP", sector: "Technology", type: "stock" },
  { ticker: "SIE.DE", name: "Siemens", sector: "Industrials", type: "stock" },
  { ticker: "ALV.DE", name: "Allianz", sector: "Finance", type: "stock" },
  { ticker: "DTE.DE", name: "Deutsche Telekom", sector: "Telecom", type: "stock" },
  { ticker: "BAS.DE", name: "BASF", sector: "Materials", type: "stock" },
  { ticker: "BAYN.DE", name: "Bayer", sector: "Healthcare", type: "stock" },
  { ticker: "BMW.DE", name: "BMW", sector: "Consumer", type: "stock" },
  { ticker: "VOW3.DE", name: "Volkswagen", sector: "Consumer", type: "stock" },
  { ticker: "MBG.DE", name: "Mercedes-Benz", sector: "Consumer", type: "stock" },
  { ticker: "DPW.DE", name: "Deutsche Post", sector: "Industrials", type: "stock" },
  { ticker: "MUV2.DE", name: "Munich Re", sector: "Finance", type: "stock" },
  { ticker: "DB1.DE", name: "Deutsche Börse", sector: "Finance", type: "stock" },
  { ticker: "DBK.DE", name: "Deutsche Bank", sector: "Finance", type: "stock" },
  { ticker: "CBK.DE", name: "Commerzbank", sector: "Finance", type: "stock" },
  { ticker: "HEN3.DE", name: "Henkel", sector: "Consumer", type: "stock" },
  { ticker: "BEI.DE", name: "Beiersdorf", sector: "Consumer", type: "stock" },
  { ticker: "ADS.DE", name: "Adidas", sector: "Consumer", type: "stock" },
  { ticker: "IFX.DE", name: "Infineon Technologies", sector: "Technology", type: "stock" },
  { ticker: "RWE.DE", name: "RWE", sector: "Utilities", type: "stock" },
  { ticker: "EOAN.DE", name: "E.ON", sector: "Utilities", type: "stock" },
  { ticker: "FRE.DE", name: "Fresenius", sector: "Healthcare", type: "stock" },
  { ticker: "FME.DE", name: "Fresenius Medical", sector: "Healthcare", type: "stock" },
  { ticker: "MRK.DE", name: "Merck KGaA", sector: "Healthcare", type: "stock" },
  { ticker: "HEI.DE", name: "HeidelbergCement", sector: "Materials", type: "stock" },
  { ticker: "CON.DE", name: "Continental", sector: "Consumer", type: "stock" },
  { ticker: "ZAL.DE", name: "Zalando", sector: "Consumer", type: "stock" },
  { ticker: "HFG.DE", name: "HelloFresh", sector: "Consumer", type: "stock" },
  { ticker: "MTX.DE", name: "MTU Aero Engines", sector: "Industrials", type: "stock" },
  { ticker: "AIR.DE", name: "Airbus", sector: "Industrials", type: "stock" },
  { ticker: "SY1.DE", name: "Symrise", sector: "Materials", type: "stock" },
  { ticker: "MC.PA", name: "LVMH", sector: "Consumer", type: "stock" },
  { ticker: "OR.PA", name: "L'Oréal", sector: "Consumer", type: "stock" },
  { ticker: "TTE.PA", name: "TotalEnergies", sector: "Energy", type: "stock" },
  { ticker: "SAN.PA", name: "Sanofi", sector: "Healthcare", type: "stock" },
  { ticker: "AI.PA", name: "Air Liquide", sector: "Materials", type: "stock" },
  { ticker: "SU.PA", name: "Schneider Electric", sector: "Industrials", type: "stock" },
  { ticker: "BN.PA", name: "Danone", sector: "Consumer", type: "stock" },
  { ticker: "RI.PA", name: "Pernod Ricard", sector: "Consumer", type: "stock" },
  { ticker: "CAP.PA", name: "Capgemini", sector: "Technology", type: "stock" },
  { ticker: "DSY.PA", name: "Dassault Systèmes", sector: "Technology", type: "stock" },
  { ticker: "SGO.PA", name: "Saint-Gobain", sector: "Materials", type: "stock" },
  { ticker: "VIE.PA", name: "Veolia", sector: "Utilities", type: "stock" },
  { ticker: "CS.PA", name: "AXA", sector: "Finance", type: "stock" },
  { ticker: "BNP.PA", name: "BNP Paribas", sector: "Finance", type: "stock" },
  { ticker: "GLE.PA", name: "Société Générale", sector: "Finance", type: "stock" },
  { ticker: "ACA.PA", name: "Crédit Agricole", sector: "Finance", type: "stock" },
  { ticker: "ORA.PA", name: "Orange", sector: "Telecom", type: "stock" },
  { ticker: "DG.PA", name: "Vinci", sector: "Industrials", type: "stock" },
  { ticker: "SAF.PA", name: "Safran", sector: "Industrials", type: "stock" },
  { ticker: "HO.PA", name: "Thales", sector: "Industrials", type: "stock" },
  { ticker: "EN.PA", name: "Bouygues", sector: "Industrials", type: "stock" },
  { ticker: "VIV.PA", name: "Vivendi", sector: "Communication", type: "stock" },
  { ticker: "KER.PA", name: "Kering", sector: "Consumer", type: "stock" },
  { ticker: "RMS.PA", name: "Hermès", sector: "Consumer", type: "stock" },
  { ticker: "EL.PA", name: "EssilorLuxottica", sector: "Healthcare", type: "stock" },
  { ticker: "STMPA.PA", name: "STMicroelectronics", sector: "Technology", type: "stock" },
  { ticker: "ERF.PA", name: "Eurofins Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "WLN.PA", name: "Worldline", sector: "Technology", type: "stock" },
  { ticker: "PUB.PA", name: "Publicis Groupe", sector: "Communication", type: "stock" },
  { ticker: "ATO.PA", name: "Atos", sector: "Technology", type: "stock" },
];
