import { AssetEntry } from "./types";

export const moreCrypto: AssetEntry[] = [
  { ticker: "BNB-USD", name: "Binance Coin", sector: "Crypto", type: "crypto" },
  { ticker: "ADA-USD", name: "Cardano", sector: "Crypto", type: "crypto" },
  { ticker: "DOT-USD", name: "Polkadot", sector: "Crypto", type: "crypto" },
  { ticker: "MATIC-USD", name: "Polygon", sector: "Crypto", type: "crypto" },
  { ticker: "LINK-USD", name: "Chainlink", sector: "Crypto", type: "crypto" },
  { ticker: "UNI-USD", name: "Uniswap", sector: "Crypto", type: "crypto" },
  { ticker: "ATOM-USD", name: "Cosmos", sector: "Crypto", type: "crypto" },
  { ticker: "FIL-USD", name: "Filecoin", sector: "Crypto", type: "crypto" },
  { ticker: "NEAR-USD", name: "NEAR Protocol", sector: "Crypto", type: "crypto" },
  { ticker: "APT-USD", name: "Aptos", sector: "Crypto", type: "crypto" },
  { ticker: "ARB-USD", name: "Arbitrum", sector: "Crypto", type: "crypto" },
  { ticker: "OP-USD", name: "Optimism", sector: "Crypto", type: "crypto" },
  { ticker: "IMX-USD", name: "Immutable X", sector: "Crypto", type: "crypto" },
  { ticker: "INJ-USD", name: "Injective", sector: "Crypto", type: "crypto" },
  { ticker: "RUNE-USD", name: "THORChain", sector: "Crypto", type: "crypto" },
  { ticker: "FTM-USD", name: "Fantom", sector: "Crypto", type: "crypto" },
  { ticker: "SAND-USD", name: "The Sandbox", sector: "Crypto", type: "crypto" },
  { ticker: "MANA-USD", name: "Decentraland", sector: "Crypto", type: "crypto" },
  { ticker: "AXS-USD", name: "Axie Infinity", sector: "Crypto", type: "crypto" },
  { ticker: "GALA-USD", name: "Gala", sector: "Crypto", type: "crypto" },
  { ticker: "FLOW-USD", name: "Flow", sector: "Crypto", type: "crypto" },
  { ticker: "ICP-USD", name: "Internet Computer", sector: "Crypto", type: "crypto" },
  { ticker: "EGLD-USD", name: "MultiversX", sector: "Crypto", type: "crypto" },
  { ticker: "HBAR-USD", name: "Hedera", sector: "Crypto", type: "crypto" },
  { ticker: "VET-USD", name: "VeChain", sector: "Crypto", type: "crypto" },
  { ticker: "THETA-USD", name: "Theta Network", sector: "Crypto", type: "crypto" },
  { ticker: "FET-USD", name: "Fetch.ai", sector: "Crypto", type: "crypto" },
  { ticker: "RNDR-USD", name: "Render", sector: "Crypto", type: "crypto" },
  { ticker: "GRT-USD", name: "The Graph", sector: "Crypto", type: "crypto" },
  { ticker: "SNX-USD", name: "Synthetix", sector: "Crypto", type: "crypto" },
  { ticker: "MKR-USD", name: "Maker", sector: "Crypto", type: "crypto" },
  { ticker: "COMP-USD", name: "Compound", sector: "Crypto", type: "crypto" },
  { ticker: "CRV-USD", name: "Curve DAO", sector: "Crypto", type: "crypto" },
  { ticker: "SUSHI-USD", name: "SushiSwap", sector: "Crypto", type: "crypto" },
  { ticker: "YFI-USD", name: "yearn.finance", sector: "Crypto", type: "crypto" },
  { ticker: "1INCH-USD", name: "1inch Network", sector: "Crypto", type: "crypto" },
  { ticker: "ENS-USD", name: "ENS", sector: "Crypto", type: "crypto" },
  { ticker: "LDO-USD", name: "Lido DAO", sector: "Crypto", type: "crypto" },
  { ticker: "RPL-USD", name: "Rocket Pool", sector: "Crypto", type: "crypto" },
  { ticker: "AAVE-USD", name: "Aave", sector: "Crypto", type: "crypto" },
  { ticker: "KCS-USD", name: "KuCoin Token", sector: "Crypto", type: "crypto" },
  { ticker: "CRO-USD", name: "Cronos", sector: "Crypto", type: "crypto" },
  { ticker: "LEO-USD", name: "UNUS SED LEO", sector: "Crypto", type: "crypto" },
  { ticker: "OKB-USD", name: "OKB", sector: "Crypto", type: "crypto" },
  { ticker: "HT-USD", name: "Huobi Token", sector: "Crypto", type: "crypto" },
  { ticker: "KLAY-USD", name: "Klaytn", sector: "Crypto", type: "crypto" },
  { ticker: "QNT-USD", name: "Quant", sector: "Crypto", type: "crypto" },
  { ticker: "ALGO-USD", name: "Algorand", sector: "Crypto", type: "crypto" },
  { ticker: "XTZ-USD", name: "Tezos", sector: "Crypto", type: "crypto" },
  { ticker: "EOS-USD", name: "EOS", sector: "Crypto", type: "crypto" },
  { ticker: "ZEC-USD", name: "Zcash", sector: "Crypto", type: "crypto" },
  { ticker: "DASH-USD", name: "Dash", sector: "Crypto", type: "crypto" },
  { ticker: "XMR-USD", name: "Monero", sector: "Crypto", type: "crypto" },
  { ticker: "NEO-USD", name: "NEO", sector: "Crypto", type: "crypto" },
  { ticker: "WAVES-USD", name: "Waves", sector: "Crypto", type: "crypto" },
  { ticker: "IOTA-USD", name: "IOTA", sector: "Crypto", type: "crypto" },
  { ticker: "ZIL-USD", name: "Zilliqa", sector: "Crypto", type: "crypto" },
  { ticker: "ONT-USD", name: "Ontology", sector: "Crypto", type: "crypto" },
  { ticker: "ICX-USD", name: "ICON", sector: "Crypto", type: "crypto" },
  { ticker: "QTUM-USD", name: "Qtum", sector: "Crypto", type: "crypto" },
  { ticker: "XEM-USD", name: "NEM", sector: "Crypto", type: "crypto" },
  { ticker: "DCR-USD", name: "Decred", sector: "Crypto", type: "crypto" },
  { ticker: "SC-USD", name: "Siacoin", sector: "Crypto", type: "crypto" },
  { ticker: "ZEN-USD", name: "Horizen", sector: "Crypto", type: "crypto" },
  { ticker: "BTG-USD", name: "Bitcoin Gold", sector: "Crypto", type: "crypto" },
  { ticker: "RVN-USD", name: "Ravencoin", sector: "Crypto", type: "crypto" },
  { ticker: "CELO-USD", name: "Celo", sector: "Crypto", type: "crypto" },
  { ticker: "ROSE-USD", name: "Oasis Network", sector: "Crypto", type: "crypto" },
  { ticker: "MINA-USD", name: "Mina", sector: "Crypto", type: "crypto" },
  { ticker: "KDA-USD", name: "Kadena", sector: "Crypto", type: "crypto" },
  { ticker: "CFX-USD", name: "Conflux", sector: "Crypto", type: "crypto" },
  { ticker: "AGIX-USD", name: "SingularityNET", sector: "Crypto", type: "crypto" },
  { ticker: "WLD-USD", name: "Worldcoin", sector: "Crypto", type: "crypto" },
  { ticker: "SEI-USD", name: "Sei", sector: "Crypto", type: "crypto" },
  { ticker: "SUI-USD", name: "Sui", sector: "Crypto", type: "crypto" },
  { ticker: "TIA-USD", name: "Celestia", sector: "Crypto", type: "crypto" },
  { ticker: "JUP-USD", name: "Jupiter", sector: "Crypto", type: "crypto" },
  { ticker: "PYTH-USD", name: "Pyth Network", sector: "Crypto", type: "crypto" },
  { ticker: "STX-USD", name: "Stacks", sector: "Crypto", type: "crypto" },
  { ticker: "ORDI-USD", name: "ORDI", sector: "Crypto", type: "crypto" },
  { ticker: "PEPE-USD", name: "Pepe", sector: "Crypto", type: "crypto" },
  { ticker: "WIF-USD", name: "dogwifhat", sector: "Crypto", type: "crypto" },
  { ticker: "BONK-USD", name: "Bonk", sector: "Crypto", type: "crypto" },
  { ticker: "FLOKI-USD", name: "FLOKI", sector: "Crypto", type: "crypto" },
  { ticker: "SHIB-USD", name: "Shiba Inu", sector: "Crypto", type: "crypto" },
  { ticker: "DOGE-USD", name: "Dogecoin", sector: "Crypto", type: "crypto" },
];
