import { AssetEntry } from "./types";

export const stocks: AssetEntry[] = [
  // Technology
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", type: "stock" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology", type: "stock" },
  { ticker: "GOOGL", name: "Alphabet Inc.", sector: "Technology", type: "stock" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Technology", type: "stock" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Technology", type: "stock" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Technology", type: "stock" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Technology", type: "stock" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology", type: "stock" },
  { ticker: "INTC", name: "Intel Corporation", sector: "Technology", type: "stock" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", type: "stock" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology", type: "stock" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology", type: "stock" },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", type: "stock" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology", type: "stock" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", type: "stock" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", type: "stock" },
  { ticker: "IBM", name: "IBM Corporation", sector: "Technology", type: "stock" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", type: "stock" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology", type: "stock" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology", type: "stock" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology", type: "stock" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology", type: "stock" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology", type: "stock" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology", type: "stock" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology", type: "stock" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology", type: "stock" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Technology", type: "stock" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology", type: "stock" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology", type: "stock" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology", type: "stock" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Technology", type: "stock" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology", type: "stock" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology", type: "stock" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", type: "stock" },
  { ticker: "SQ", name: "Block Inc.", sector: "Technology", type: "stock" },
  { ticker: "UBER", name: "Uber Technologies", sector: "Technology", type: "stock" },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Technology", type: "stock" },
  { ticker: "SPOT", name: "Spotify Technology", sector: "Technology", type: "stock" },
  { ticker: "COIN", name: "Coinbase Global", sector: "Technology", type: "stock" },
  { ticker: "RBLX", name: "Roblox Corporation", sector: "Technology", type: "stock" },
  { ticker: "U", name: "Unity Software", sector: "Technology", type: "stock" },
  { ticker: "TWLO", name: "Twilio Inc.", sector: "Technology", type: "stock" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", type: "stock" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ARM", name: "Arm Holdings", sector: "Technology", type: "stock" },
  { ticker: "DELL", name: "Dell Technologies", sector: "Technology", type: "stock" },
  { ticker: "HPQ", name: "HP Inc.", sector: "Technology", type: "stock" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", type: "stock" },
  { ticker: "WDAY", name: "Workday Inc.", sector: "Technology", type: "stock" },
  { ticker: "ZM", name: "Zoom Video Communications", sector: "Technology", type: "stock" },
  { ticker: "DOCU", name: "DocuSign Inc.", sector: "Technology", type: "stock" },
  { ticker: "OKTA", name: "Okta Inc.", sector: "Technology", type: "stock" },
  { ticker: "MDB", name: "MongoDB Inc.", sector: "Technology", type: "stock" },
  { ticker: "ESTC", name: "Elastic N.V.", sector: "Technology", type: "stock" },
  { ticker: "CFLT", name: "Confluent Inc.", sector: "Technology", type: "stock" },
  { ticker: "PATH", name: "UiPath Inc.", sector: "Technology", type: "stock" },
  { ticker: "HUBS", name: "HubSpot Inc.", sector: "Technology", type: "stock" },
  { ticker: "VEEV", name: "Veeva Systems", sector: "Technology", type: "stock" },
  { ticker: "TEAM", name: "Atlassian Corporation", sector: "Technology", type: "stock" },
  { ticker: "SPLK", name: "Splunk Inc.", sector: "Technology", type: "stock" },
  { ticker: "AKAM", name: "Akamai Technologies", sector: "Technology", type: "stock" },
  { ticker: "FFIV", name: "F5 Inc.", sector: "Technology", type: "stock" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "Technology", type: "stock" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology", type: "stock" },
  { ticker: "KEYS", name: "Keysight Technologies", sector: "Technology", type: "stock" },
  { ticker: "ANSS", name: "Ansys Inc.", sector: "Technology", type: "stock" },
  { ticker: "MPWR", name: "Monolithic Power Systems", sector: "Technology", type: "stock" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology", type: "stock" },
  { ticker: "QRVO", name: "Qorvo Inc.", sector: "Technology", type: "stock" },
  { ticker: "ENPH", name: "Enphase Energy", sector: "Technology", type: "stock" },
  { ticker: "SEDG", name: "SolarEdge Technologies", sector: "Technology", type: "stock" },
  { ticker: "FSLR", name: "First Solar Inc.", sector: "Technology", type: "stock" },
  { ticker: "RIVN", name: "Rivian Automotive", sector: "Technology", type: "stock" },
  { ticker: "LCID", name: "Lucid Group", sector: "Technology", type: "stock" },
  { ticker: "GRAB", name: "Grab Holdings", sector: "Technology", type: "stock" },
  { ticker: "SE", name: "Sea Limited", sector: "Technology", type: "stock" },
  { ticker: "BIDU", name: "Baidu Inc.", sector: "Technology", type: "stock" },
  { ticker: "JD", name: "JD.com Inc.", sector: "Technology", type: "stock" },
  { ticker: "PDD", name: "PDD Holdings", sector: "Technology", type: "stock" },
  { ticker: "BABA", name: "Alibaba Group", sector: "Technology", type: "stock" },
  { ticker: "TCEHY", name: "Tencent Holdings", sector: "Technology", type: "stock" },
  { ticker: "TSM", name: "Taiwan Semiconductor", sector: "Technology", type: "stock" },
  { ticker: "ASML", name: "ASML Holding", sector: "Technology", type: "stock" },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", type: "stock" },
  { ticker: "SONY", name: "Sony Group", sector: "Technology", type: "stock" },
  { ticker: "NTDOY", name: "Nintendo Co.", sector: "Technology", type: "stock" },
  // Consumer
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer", type: "stock" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer", type: "stock" },
  { ticker: "KO", name: "The Coca-Cola Company", sector: "Consumer", type: "stock" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer", type: "stock" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer", type: "stock" },
  { ticker: "DIS", name: "Walt Disney Company", sector: "Consumer", type: "stock" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer", type: "stock" },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer", type: "stock" },
  { ticker: "MCD", name: "McDonald's Corporation", sector: "Consumer", type: "stock" },
  { ticker: "SBUX", name: "Starbucks Corporation", sector: "Consumer", type: "stock" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer", type: "stock" },
  { ticker: "HD", name: "The Home Depot", sector: "Consumer", type: "stock" },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer", type: "stock" },
  { ticker: "EL", name: "Estée Lauder Companies", sector: "Consumer", type: "stock" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer", type: "stock" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer", type: "stock" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer", type: "stock" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer", type: "stock" },
  { ticker: "KHC", name: "Kraft Heinz Company", sector: "Consumer", type: "stock" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer", type: "stock" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer", type: "stock" },
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer", type: "stock" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer", type: "stock" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer", type: "stock" },
  { ticker: "DKNG", name: "DraftKings Inc.", sector: "Consumer", type: "stock" },
  { ticker: "DASH", name: "DoorDash Inc.", sector: "Consumer", type: "stock" },
  { ticker: "CPNG", name: "Coupang Inc.", sector: "Consumer", type: "stock" },
  { ticker: "ETSY", name: "Etsy Inc.", sector: "Consumer", type: "stock" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer", type: "stock" },
  { ticker: "EXPE", name: "Expedia Group", sector: "Consumer", type: "stock" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer", type: "stock" },
  { ticker: "HLT", name: "Hilton Worldwide", sector: "Consumer", type: "stock" },
  { ticker: "WYNN", name: "Wynn Resorts", sector: "Consumer", type: "stock" },
  { ticker: "LVS", name: "Las Vegas Sands", sector: "Consumer", type: "stock" },
  { ticker: "MGM", name: "MGM Resorts", sector: "Consumer", type: "stock" },
  { ticker: "F", name: "Ford Motor Company", sector: "Consumer", type: "stock" },
  { ticker: "GM", name: "General Motors", sector: "Consumer", type: "stock" },
  { ticker: "RACE", name: "Ferrari N.V.", sector: "Consumer", type: "stock" },
  { ticker: "APTV", name: "Aptiv PLC", sector: "Consumer", type: "stock" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer", type: "stock" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer", type: "stock" },
  { ticker: "DEO", name: "Diageo plc", sector: "Consumer", type: "stock" },
  { ticker: "BUD", name: "Anheuser-Busch InBev", sector: "Consumer", type: "stock" },
  { ticker: "TAP", name: "Molson Coors", sector: "Consumer", type: "stock" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer", type: "stock" },
  { ticker: "HSY", name: "The Hershey Company", sector: "Consumer", type: "stock" },
  { ticker: "SJM", name: "J.M. Smucker", sector: "Consumer", type: "stock" },
  { ticker: "CPB", name: "Campbell Soup", sector: "Consumer", type: "stock" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer", type: "stock" },
  { ticker: "MKC", name: "McCormick & Company", sector: "Consumer", type: "stock" },
  { ticker: "CLX", name: "Clorox Company", sector: "Consumer", type: "stock" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer", type: "stock" },
  { ticker: "WBA", name: "Walgreens Boots Alliance", sector: "Consumer", type: "stock" },
  { ticker: "DG", name: "Dollar General", sector: "Consumer", type: "stock" },
  { ticker: "DLTR", name: "Dollar Tree", sector: "Consumer", type: "stock" },
  { ticker: "BBY", name: "Best Buy Co.", sector: "Consumer", type: "stock" },
  { ticker: "ULTA", name: "Ulta Beauty", sector: "Consumer", type: "stock" },
  { ticker: "GPS", name: "Gap Inc.", sector: "Consumer", type: "stock" },
  { ticker: "RL", name: "Ralph Lauren", sector: "Consumer", type: "stock" },
  { ticker: "TPR", name: "Tapestry Inc.", sector: "Consumer", type: "stock" },
  { ticker: "CPRI", name: "Capri Holdings", sector: "Consumer", type: "stock" },
  // Finance
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc.", sector: "Finance", type: "stock" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Finance", type: "stock" },
  { ticker: "V", name: "Visa Inc.", sector: "Finance", type: "stock" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Finance", type: "stock" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Finance", type: "stock" },
  { ticker: "BAC", name: "Bank of America", sector: "Finance", type: "stock" },
  { ticker: "WFC", name: "Wells Fargo & Co.", sector: "Finance", type: "stock" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Finance", type: "stock" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Finance", type: "stock" },
  { ticker: "AXP", name: "American Express", sector: "Finance", type: "stock" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Finance", type: "stock" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Finance", type: "stock" },
  { ticker: "SPGI", name: "S&P Global", sector: "Finance", type: "stock" },
  { ticker: "CME", name: "CME Group", sector: "Finance", type: "stock" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Finance", type: "stock" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Finance", type: "stock" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Finance", type: "stock" },
  { ticker: "PYPL", name: "PayPal Holdings", sector: "Finance", type: "stock" },
  { ticker: "TFC", name: "Truist Financial", sector: "Finance", type: "stock" },
  { ticker: "COF", name: "Capital One Financial", sector: "Finance", type: "stock" },
  { ticker: "DFS", name: "Discover Financial", sector: "Finance", type: "stock" },
  { ticker: "FIS", name: "Fidelity National Info", sector: "Finance", type: "stock" },
  { ticker: "FISV", name: "Fiserv Inc.", sector: "Finance", type: "stock" },
  { ticker: "AIG", name: "American International Group", sector: "Finance", type: "stock" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Finance", type: "stock" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Finance", type: "stock" },
  { ticker: "ALL", name: "Allstate Corporation", sector: "Finance", type: "stock" },
  { ticker: "TRV", name: "Travelers Companies", sector: "Finance", type: "stock" },
  { ticker: "PGR", name: "Progressive Corporation", sector: "Finance", type: "stock" },
  { ticker: "CB", name: "Chubb Limited", sector: "Finance", type: "stock" },
  { ticker: "AFL", name: "Aflac Inc.", sector: "Finance", type: "stock" },
  { ticker: "MMC", name: "Marsh & McLennan", sector: "Finance", type: "stock" },
  { ticker: "AON", name: "Aon plc", sector: "Finance", type: "stock" },
  { ticker: "MCO", name: "Moody's Corporation", sector: "Finance", type: "stock" },
  { ticker: "MSCI", name: "MSCI Inc.", sector: "Finance", type: "stock" },
  { ticker: "NDAQ", name: "Nasdaq Inc.", sector: "Finance", type: "stock" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Finance", type: "stock" },
  { ticker: "RJF", name: "Raymond James Financial", sector: "Finance", type: "stock" },
  { ticker: "IBKR", name: "Interactive Brokers", sector: "Finance", type: "stock" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Finance", type: "stock" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Finance", type: "stock" },
  { ticker: "NU", name: "Nu Holdings", sector: "Finance", type: "stock" },
  // Healthcare
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", type: "stock" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare", type: "stock" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "LLY", name: "Eli Lilly & Co.", sector: "Healthcare", type: "stock" },
  { ticker: "MRK", name: "Merck & Co.", sector: "Healthcare", type: "stock" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", type: "stock" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", type: "stock" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "stock" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "ZTS", name: "Zoetis Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Healthcare", type: "stock" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare", type: "stock" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare", type: "stock" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare", type: "stock" },
  { ticker: "HUM", name: "Humana Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare", type: "stock" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Healthcare", type: "stock" },
  { ticker: "BDX", name: "Becton Dickinson", sector: "Healthcare", type: "stock" },
  { ticker: "A", name: "Agilent Technologies", sector: "Healthcare", type: "stock" },
  { ticker: "IQV", name: "IQVIA Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "DXCM", name: "DexCom Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare", type: "stock" },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Healthcare", type: "stock" },
  { ticker: "SGEN", name: "Seagen Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "BAX", name: "Baxter International", sector: "Healthcare", type: "stock" },
  { ticker: "MTD", name: "Mettler-Toledo", sector: "Healthcare", type: "stock" },
  { ticker: "HOLX", name: "Hologic Inc.", sector: "Healthcare", type: "stock" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare", type: "stock" },
  { ticker: "NVO", name: "Novo Nordisk", sector: "Healthcare", type: "stock" },
  { ticker: "AZN", name: "AstraZeneca", sector: "Healthcare", type: "stock" },
  { ticker: "GSK", name: "GSK plc", sector: "Healthcare", type: "stock" },
  { ticker: "SNY", name: "Sanofi", sector: "Healthcare", type: "stock" },
  // Energy
  { ticker: "XOM", name: "Exxon Mobil Corporation", sector: "Energy", type: "stock" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy", type: "stock" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Energy", type: "stock" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", type: "stock" },
  { ticker: "SLB", name: "Schlumberger Limited", sector: "Energy", type: "stock" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy", type: "stock" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", type: "stock" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", type: "stock" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", type: "stock" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", type: "stock" },
  { ticker: "ENB", name: "Enbridge Inc.", sector: "Energy", type: "stock" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy", type: "stock" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy", type: "stock" },
  { ticker: "HAL", name: "Halliburton Company", sector: "Energy", type: "stock" },
  { ticker: "BKR", name: "Baker Hughes", sector: "Energy", type: "stock" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", type: "stock" },
  { ticker: "OKE", name: "ONEOK Inc.", sector: "Energy", type: "stock" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy", type: "stock" },
  { ticker: "TRGP", name: "Targa Resources", sector: "Energy", type: "stock" },
  { ticker: "PXD", name: "Pioneer Natural Resources", sector: "Energy", type: "stock" },
  // Industrial
  { ticker: "BA", name: "Boeing Company", sector: "Industrial", type: "stock" },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrial", type: "stock" },
  { ticker: "GE", name: "General Electric", sector: "Industrial", type: "stock" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrial", type: "stock" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrial", type: "stock" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrial", type: "stock" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrial", type: "stock" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrial", type: "stock" },
  { ticker: "MMM", name: "3M Company", sector: "Industrial", type: "stock" },
  { ticker: "FDX", name: "FedEx Corporation", sector: "Industrial", type: "stock" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrial", type: "stock" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrial", type: "stock" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrial", type: "stock" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrial", type: "stock" },
  { ticker: "ETN", name: "Eaton Corporation", sector: "Industrial", type: "stock" },
  { ticker: "WM", name: "Waste Management", sector: "Industrial", type: "stock" },
  { ticker: "RSG", name: "Republic Services", sector: "Industrial", type: "stock" },
  { ticker: "DAL", name: "Delta Air Lines", sector: "Industrial", type: "stock" },
  { ticker: "UAL", name: "United Airlines", sector: "Industrial", type: "stock" },
  { ticker: "LUV", name: "Southwest Airlines", sector: "Industrial", type: "stock" },
  { ticker: "AAL", name: "American Airlines", sector: "Industrial", type: "stock" },
  { ticker: "CSX", name: "CSX Corporation", sector: "Industrial", type: "stock" },
  { ticker: "UNP", name: "Union Pacific", sector: "Industrial", type: "stock" },
  { ticker: "NSC", name: "Norfolk Southern", sector: "Industrial", type: "stock" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrial", type: "stock" },
  { ticker: "CMI", name: "Cummins Inc.", sector: "Industrial", type: "stock" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrial", type: "stock" },
  { ticker: "AME", name: "AMETEK Inc.", sector: "Industrial", type: "stock" },
  { ticker: "IR", name: "Ingersoll Rand", sector: "Industrial", type: "stock" },
  { ticker: "GWW", name: "W.W. Grainger", sector: "Industrial", type: "stock" },
  { ticker: "FAST", name: "Fastenal Company", sector: "Industrial", type: "stock" },
  // Telecom & Utilities
  { ticker: "T", name: "AT&T Inc.", sector: "Telecom", type: "stock" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Telecom", type: "stock" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Telecom", type: "stock" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities", type: "stock" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", type: "stock" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", type: "stock" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", type: "stock" },
  { ticker: "EXC", name: "Exelon Corporation", sector: "Utilities", type: "stock" },
  { ticker: "SRE", name: "Sempra Energy", sector: "Utilities", type: "stock" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", type: "stock" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities", type: "stock" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities", type: "stock" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities", type: "stock" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities", type: "stock" },
  { ticker: "PCG", name: "PG&E Corporation", sector: "Utilities", type: "stock" },
  // Real Estate
  { ticker: "AMT", name: "American Tower", sector: "Real Estate", type: "stock" },
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate", type: "stock" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate", type: "stock" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate", type: "stock" },
  { ticker: "DLR", name: "Digital Realty Trust", sector: "Real Estate", type: "stock" },
  { ticker: "WELL", name: "Welltower Inc.", sector: "Real Estate", type: "stock" },
  { ticker: "AVB", name: "AvalonBay Communities", sector: "Real Estate", type: "stock" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate", type: "stock" },
  { ticker: "VICI", name: "VICI Properties", sector: "Real Estate", type: "stock" },
  { ticker: "ARE", name: "Alexandria Real Estate", sector: "Real Estate", type: "stock" },
  // Materials
  { ticker: "LIN", name: "Linde plc", sector: "Materials", type: "stock" },
  { ticker: "APD", name: "Air Products & Chemicals", sector: "Materials", type: "stock" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", type: "stock" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", type: "stock" },
  { ticker: "NEM", name: "Newmont Corporation", sector: "Materials", type: "stock" },
  { ticker: "NUE", name: "Nucor Corporation", sector: "Materials", type: "stock" },
  { ticker: "ECL", name: "Ecolab Inc.", sector: "Materials", type: "stock" },
  { ticker: "DD", name: "DuPont de Nemours", sector: "Materials", type: "stock" },
  { ticker: "DOW", name: "Dow Inc.", sector: "Materials", type: "stock" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials", type: "stock" },
  { ticker: "VMC", name: "Vulcan Materials", sector: "Materials", type: "stock" },
  { ticker: "MLM", name: "Martin Marietta Materials", sector: "Materials", type: "stock" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials", type: "stock" },
  { ticker: "CF", name: "CF Industries", sector: "Materials", type: "stock" },
  { ticker: "MOS", name: "Mosaic Company", sector: "Materials", type: "stock" },
  { ticker: "ALB", name: "Albemarle Corporation", sector: "Materials", type: "stock" },
  { ticker: "GOLD", name: "Barrick Gold", sector: "Materials", type: "stock" },
  { ticker: "RIO", name: "Rio Tinto", sector: "Materials", type: "stock" },
  { ticker: "BHP", name: "BHP Group", sector: "Materials", type: "stock" },
  { ticker: "VALE", name: "Vale S.A.", sector: "Materials", type: "stock" },
];
