import { AssetEntry } from "./types";

export const usMidCapStocks: AssetEntry[] = [
  { ticker: "DKNG", name: "DraftKings", sector: "Consumer", type: "stock" },
  { ticker: "ROKU", name: "Roku", sector: "Technology", type: "stock" },
  { ticker: "SNAP", name: "Snap Inc", sector: "Technology", type: "stock" },
  { ticker: "PINS", name: "Pinterest", sector: "Technology", type: "stock" },
  { ticker: "LYFT", name: "Lyft", sector: "Technology", type: "stock" },
  { ticker: "DASH", name: "DoorDash", sector: "Technology", type: "stock" },
  { ticker: "COIN", name: "Coinbase Global", sector: "Finance", type: "stock" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Finance", type: "stock" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Finance", type: "stock" },
  { ticker: "AFRM", name: "Affirm Holdings", sector: "Finance", type: "stock" },
  { ticker: "RBLX", name: "Roblox", sector: "Technology", type: "stock" },
  { ticker: "U", name: "Unity Software", sector: "Technology", type: "stock" },
  { ticker: "PATH", name: "UiPath", sector: "Technology", type: "stock" },
  { ticker: "DDOG", name: "Datadog", sector: "Technology", type: "stock" },
  { ticker: "ZS", name: "Zscaler", sector: "Technology", type: "stock" },
  { ticker: "OKTA", name: "Okta", sector: "Technology", type: "stock" },
  { ticker: "HUBS", name: "HubSpot", sector: "Technology", type: "stock" },
  { ticker: "BILL", name: "Bill Holdings", sector: "Technology", type: "stock" },
  { ticker: "CFLT", name: "Confluent", sector: "Technology", type: "stock" },
  { ticker: "MDB", name: "MongoDB", sector: "Technology", type: "stock" },
  { ticker: "GTLB", name: "GitLab", sector: "Technology", type: "stock" },
  { ticker: "S", name: "SentinelOne", sector: "Technology", type: "stock" },
  { ticker: "ESTC", name: "Elastic NV", sector: "Technology", type: "stock" },
  { ticker: "DOCN", name: "DigitalOcean", sector: "Technology", type: "stock" },
  { ticker: "NET", name: "Cloudflare", sector: "Technology", type: "stock" },
  { ticker: "FSLY", name: "Fastly", sector: "Technology", type: "stock" },
  { ticker: "TWLO", name: "Twilio", sector: "Technology", type: "stock" },
  { ticker: "TTD", name: "The Trade Desk", sector: "Technology", type: "stock" },
  { ticker: "APPS", name: "Digital Turbine", sector: "Technology", type: "stock" },
  { ticker: "DT", name: "Dynatrace", sector: "Technology", type: "stock" },
  { ticker: "FIVN", name: "Five9", sector: "Technology", type: "stock" },
  { ticker: "MTTR", name: "Matterport", sector: "Technology", type: "stock" },
  { ticker: "ASAN", name: "Asana", sector: "Technology", type: "stock" },
  { ticker: "MNDY", name: "monday.com", sector: "Technology", type: "stock" },
  { ticker: "PCOR", name: "Procore Technologies", sector: "Technology", type: "stock" },
  { ticker: "CELH", name: "Celsius Holdings", sector: "Consumer", type: "stock" },
  { ticker: "TOST", name: "Toast", sector: "Technology", type: "stock" },
  { ticker: "GLBE", name: "Global-e Online", sector: "Technology", type: "stock" },
  { ticker: "RYAN", name: "Ryan Specialty", sector: "Finance", type: "stock" },
  { ticker: "HLI", name: "Houlihan Lokey", sector: "Finance", type: "stock" },
  { ticker: "STEP", name: "StepStone Group", sector: "Finance", type: "stock" },
  { ticker: "EVR", name: "Evercore", sector: "Finance", type: "stock" },
  { ticker: "PJT", name: "PJT Partners", sector: "Finance", type: "stock" },
  { ticker: "PIPR", name: "Piper Sandler", sector: "Finance", type: "stock" },
  { ticker: "LBRDK", name: "Liberty Broadband", sector: "Communication", type: "stock" },
  { ticker: "SIRI", name: "Sirius XM", sector: "Communication", type: "stock" },
  { ticker: "WMG", name: "Warner Music", sector: "Communication", type: "stock" },
  { ticker: "IAC", name: "IAC Inc", sector: "Communication", type: "stock" },
  { ticker: "MTCH", name: "Match Group", sector: "Communication", type: "stock" },
  { ticker: "ZI", name: "ZoomInfo", sector: "Technology", type: "stock" },
  { ticker: "NTNX", name: "Nutanix", sector: "Technology", type: "stock" },
  { ticker: "TENB", name: "Tenable", sector: "Technology", type: "stock" },
  { ticker: "RPD", name: "Rapid7", sector: "Technology", type: "stock" },
  { ticker: "VRNS", name: "Varonis Systems", sector: "Technology", type: "stock" },
  { ticker: "QLYS", name: "Qualys", sector: "Technology", type: "stock" },
  { ticker: "CYBR", name: "CyberArk Software", sector: "Technology", type: "stock" },
  { ticker: "CHKP", name: "Check Point Software", sector: "Technology", type: "stock" },
  { ticker: "WIX", name: "Wix.com", sector: "Technology", type: "stock" },
  { ticker: "FROG", name: "JFrog", sector: "Technology", type: "stock" },
  { ticker: "APPN", name: "Appian", sector: "Technology", type: "stock" },
  { ticker: "BRZE", name: "Braze", sector: "Technology", type: "stock" },
  { ticker: "CWAN", name: "Clearwater Analytics", sector: "Technology", type: "stock" },
  { ticker: "ALTR", name: "Altair Engineering", sector: "Technology", type: "stock" },
  { ticker: "PTC", name: "PTC Inc", sector: "Technology", type: "stock" },
  { ticker: "AZPN", name: "Aspen Technology", sector: "Technology", type: "stock" },
  { ticker: "BSY", name: "Bentley Systems", sector: "Technology", type: "stock" },
  { ticker: "SMAR", name: "Smartsheet", sector: "Technology", type: "stock" },
  { ticker: "BL", name: "BlackLine", sector: "Technology", type: "stock" },
  { ticker: "QTWO", name: "Q2 Holdings", sector: "Technology", type: "stock" },
  { ticker: "NCNO", name: "nCino", sector: "Technology", type: "stock" },
  { ticker: "AVLR", name: "Avalara", sector: "Technology", type: "stock" },
  { ticker: "DLO", name: "DLocal", sector: "Finance", type: "stock" },
  { ticker: "PAYO", name: "Payoneer", sector: "Finance", type: "stock" },
  { ticker: "FLYW", name: "Flywire", sector: "Finance", type: "stock" },
  { ticker: "RELY", name: "Remitly Global", sector: "Finance", type: "stock" },
  { ticker: "FOUR", name: "Shift4 Payments", sector: "Finance", type: "stock" },
  { ticker: "GPN", name: "Global Payments", sector: "Finance", type: "stock" },
  { ticker: "FLT", name: "Corpay", sector: "Finance", type: "stock" },
  { ticker: "WEX", name: "WEX Inc", sector: "Finance", type: "stock" },
  { ticker: "SQ", name: "Block Inc", sector: "Finance", type: "stock" },
  { ticker: "OPEN", name: "Opendoor", sector: "Real Estate", type: "stock" },
  { ticker: "RDFN", name: "Redfin", sector: "Real Estate", type: "stock" },
  { ticker: "COMP", name: "Compass Inc", sector: "Real Estate", type: "stock" },
  { ticker: "EXPI", name: "eXp World", sector: "Real Estate", type: "stock" },
  { ticker: "INVH", name: "Invitation Homes", sector: "Real Estate", type: "stock" },
  { ticker: "AMH", name: "American Homes", sector: "Real Estate", type: "stock" },
  { ticker: "TREX", name: "Trex Company", sector: "Industrials", type: "stock" },
  { ticker: "AZEK", name: "AZEK Company", sector: "Industrials", type: "stock" },
  { ticker: "SITE", name: "SiteOne Landscape", sector: "Industrials", type: "stock" },
  { ticker: "BLDR", name: "Builders FirstSource", sector: "Industrials", type: "stock" },
  { ticker: "POOL", name: "Pool Corporation", sector: "Consumer", type: "stock" },
  { ticker: "TECH", name: "Bio-Techne", sector: "Healthcare", type: "stock" },
  { ticker: "NTRA", name: "Natera", sector: "Healthcare", type: "stock" },
  { ticker: "TXG", name: "10x Genomics", sector: "Healthcare", type: "stock" },
  { ticker: "TWST", name: "Twist Bioscience", sector: "Healthcare", type: "stock" },
  { ticker: "BEAM", name: "Beam Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "CRSP", name: "CRISPR Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "EDIT", name: "Editas Medicine", sector: "Healthcare", type: "stock" },
  { ticker: "NTLA", name: "Intellia Therapeutics", sector: "Healthcare", type: "stock" },
  { ticker: "VCYT", name: "Veracyte", sector: "Healthcare", type: "stock" },
  { ticker: "GKOS", name: "Glaukos", sector: "Healthcare", type: "stock" },
  { ticker: "NVST", name: "Envista Holdings", sector: "Healthcare", type: "stock" },
  { ticker: "ALGN", name: "Align Technology", sector: "Healthcare", type: "stock" },
  { ticker: "INSP", name: "Inspire Medical", sector: "Healthcare", type: "stock" },
  { ticker: "SHAK", name: "Shake Shack", sector: "Consumer", type: "stock" },
  { ticker: "WING", name: "Wingstop", sector: "Consumer", type: "stock" },
  { ticker: "CAVA", name: "CAVA Group", sector: "Consumer", type: "stock" },
  { ticker: "BROS", name: "Dutch Bros", sector: "Consumer", type: "stock" },
  { ticker: "SG", name: "Sweetgreen", sector: "Consumer", type: "stock" },
  { ticker: "DPZ", name: "Domino's Pizza", sector: "Consumer", type: "stock" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer", type: "stock" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer", type: "stock" },
  { ticker: "QSR", name: "Restaurant Brands", sector: "Consumer", type: "stock" },
  { ticker: "TXRH", name: "Texas Roadhouse", sector: "Consumer", type: "stock" },
  { ticker: "CAKE", name: "Cheesecake Factory", sector: "Consumer", type: "stock" },
  { ticker: "DRI", name: "Darden Restaurants", sector: "Consumer", type: "stock" },
  { ticker: "EAT", name: "Brinker International", sector: "Consumer", type: "stock" },
  { ticker: "PLAY", name: "Dave & Buster's", sector: "Consumer", type: "stock" },
  { ticker: "FUN", name: "Six Flags Entertainment", sector: "Consumer", type: "stock" },
  { ticker: "SEAS", name: "SeaWorld", sector: "Consumer", type: "stock" },
  { ticker: "LYV", name: "Live Nation", sector: "Communication", type: "stock" },
  { ticker: "SPOT", name: "Spotify", sector: "Communication", type: "stock" },
  { ticker: "DUOL", name: "Duolingo", sector: "Technology", type: "stock" },
  { ticker: "CHGG", name: "Chegg", sector: "Consumer", type: "stock" },
  { ticker: "STRA", name: "Stride", sector: "Consumer", type: "stock" },
  { ticker: "LULU", name: "Lululemon", sector: "Consumer", type: "stock" },
  { ticker: "DECK", name: "Deckers Outdoor", sector: "Consumer", type: "stock" },
  { ticker: "ONON", name: "On Holding", sector: "Consumer", type: "stock" },
  { ticker: "BIRK", name: "Birkenstock", sector: "Consumer", type: "stock" },
  { ticker: "CROX", name: "Crocs", sector: "Consumer", type: "stock" },
  { ticker: "SKX", name: "Skechers", sector: "Consumer", type: "stock" },
  { ticker: "TPX", name: "Tempur Sealy", sector: "Consumer", type: "stock" },
  { ticker: "WSM", name: "Williams-Sonoma", sector: "Consumer", type: "stock" },
  { ticker: "RH", name: "RH", sector: "Consumer", type: "stock" },
  { ticker: "ETSY", name: "Etsy", sector: "Consumer", type: "stock" },
  { ticker: "W", name: "Wayfair", sector: "Consumer", type: "stock" },
  { ticker: "CHWY", name: "Chewy", sector: "Consumer", type: "stock" },
  { ticker: "WOOF", name: "Petco Health", sector: "Consumer", type: "stock" },
  { ticker: "RVLV", name: "Revolve Group", sector: "Consumer", type: "stock" },
  { ticker: "RENT", name: "Rent the Runway", sector: "Consumer", type: "stock" },
  { ticker: "PLTK", name: "Playtika", sector: "Technology", type: "stock" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Technology", type: "stock" },
  { ticker: "EA", name: "Electronic Arts", sector: "Technology", type: "stock" },
  { ticker: "ZNGA", name: "Zynga", sector: "Technology", type: "stock" },
  { ticker: "SE", name: "Sea Limited", sector: "Technology", type: "stock" },
  { ticker: "GRAB", name: "Grab Holdings", sector: "Technology", type: "stock" },
  { ticker: "GOTO", name: "GoTo Group", sector: "Technology", type: "stock" },
  { ticker: "BABA", name: "Alibaba Group", sector: "Technology", type: "stock" },
  { ticker: "JD", name: "JD.com", sector: "Technology", type: "stock" },
  { ticker: "PDD", name: "PDD Holdings", sector: "Technology", type: "stock" },
  { ticker: "BIDU", name: "Baidu", sector: "Technology", type: "stock" },
  { ticker: "NTES", name: "NetEase", sector: "Technology", type: "stock" },
  { ticker: "BILI", name: "Bilibili", sector: "Communication", type: "stock" },
  { ticker: "TME", name: "Tencent Music", sector: "Communication", type: "stock" },
  { ticker: "IQ", name: "iQIYI", sector: "Communication", type: "stock" },
  { ticker: "WB", name: "Weibo", sector: "Communication", type: "stock" },
  { ticker: "FUTU", name: "Futu Holdings", sector: "Finance", type: "stock" },
  { ticker: "TIGR", name: "UP Fintech", sector: "Finance", type: "stock" },
  { ticker: "LI", name: "Li Auto", sector: "Consumer", type: "stock" },
  { ticker: "NIO", name: "NIO Inc", sector: "Consumer", type: "stock" },
  { ticker: "XPEV", name: "XPeng", sector: "Consumer", type: "stock" },
  { ticker: "ZK", name: "ZEEKR", sector: "Consumer", type: "stock" },
  { ticker: "RIVN", name: "Rivian Automotive", sector: "Consumer", type: "stock" },
  { ticker: "LCID", name: "Lucid Group", sector: "Consumer", type: "stock" },
  { ticker: "FSR", name: "Fisker", sector: "Consumer", type: "stock" },
  { ticker: "PSNY", name: "Polestar", sector: "Consumer", type: "stock" },
  { ticker: "BYDDF", name: "BYD Company", sector: "Consumer", type: "stock" },
  { ticker: "VWAGY", name: "Volkswagen", sector: "Consumer", type: "stock" },
  { ticker: "STLA", name: "Stellantis", sector: "Consumer", type: "stock" },
  { ticker: "HMC", name: "Honda Motor", sector: "Consumer", type: "stock" },
  { ticker: "TM", name: "Toyota Motor", sector: "Consumer", type: "stock" },
  { ticker: "RACE", name: "Ferrari", sector: "Consumer", type: "stock" },
  { ticker: "POAHY", name: "Porsche", sector: "Consumer", type: "stock" },
  { ticker: "BMWYY", name: "BMW", sector: "Consumer", type: "stock" },
  { ticker: "MZDAY", name: "Mazda", sector: "Consumer", type: "stock" },
  { ticker: "NSANY", name: "Nissan Motor", sector: "Consumer", type: "stock" },
  { ticker: "SMFG", name: "Sumitomo Mitsui", sector: "Finance", type: "stock" },
  { ticker: "MUFG", name: "Mitsubishi UFJ", sector: "Finance", type: "stock" },
  { ticker: "MFG", name: "Mizuho Financial", sector: "Finance", type: "stock" },
  { ticker: "NMR", name: "Nomura Holdings", sector: "Finance", type: "stock" },
  { ticker: "IX", name: "ORIX Corporation", sector: "Finance", type: "stock" },
  { ticker: "SHG", name: "Shinhan Financial", sector: "Finance", type: "stock" },
  { ticker: "KB", name: "KB Financial", sector: "Finance", type: "stock" },
  { ticker: "WF", name: "Woori Financial", sector: "Finance", type: "stock" },
  { ticker: "HBAN", name: "Huntington Bancshares", sector: "Finance", type: "stock" },
  { ticker: "KEY", name: "KeyCorp", sector: "Finance", type: "stock" },
  { ticker: "CFG", name: "Citizens Financial", sector: "Finance", type: "stock" },
  { ticker: "RF", name: "Regions Financial", sector: "Finance", type: "stock" },
  { ticker: "ZION", name: "Zions Bancorp", sector: "Finance", type: "stock" },
  { ticker: "CMA", name: "Comerica", sector: "Finance", type: "stock" },
  { ticker: "FHN", name: "First Horizon", sector: "Finance", type: "stock" },
  { ticker: "SNV", name: "Synovus", sector: "Finance", type: "stock" },
  { ticker: "WAL", name: "Western Alliance", sector: "Finance", type: "stock" },
  { ticker: "EWBC", name: "East West Bancorp", sector: "Finance", type: "stock" },
  { ticker: "PACW", name: "PacWest Bancorp", sector: "Finance", type: "stock" },
  { ticker: "FRC", name: "First Republic Bank", sector: "Finance", type: "stock" },
  { ticker: "COLB", name: "Columbia Banking", sector: "Finance", type: "stock" },
  { ticker: "GBCI", name: "Glacier Bancorp", sector: "Finance", type: "stock" },
  { ticker: "UMBF", name: "UMB Financial", sector: "Finance", type: "stock" },
  { ticker: "PNFP", name: "Pinnacle Financial", sector: "Finance", type: "stock" },
  { ticker: "SIVB", name: "SVB Financial Group", sector: "Finance", type: "stock" },
  { ticker: "SBNY", name: "Signature Bank", sector: "Finance", type: "stock" },
  { ticker: "FNB", name: "FNB Corporation", sector: "Finance", type: "stock" },
  { ticker: "VLY", name: "Valley National", sector: "Finance", type: "stock" },
  { ticker: "WSFS", name: "WSFS Financial", sector: "Finance", type: "stock" },
  { ticker: "NWBI", name: "Northwest Bancshares", sector: "Finance", type: "stock" },
  { ticker: "OZK", name: "Bank OZK", sector: "Finance", type: "stock" },
  { ticker: "ABCB", name: "Ameris Bancorp", sector: "Finance", type: "stock" },
  { ticker: "HWC", name: "Hancock Whitney", sector: "Finance", type: "stock" },
  { ticker: "ASB", name: "Associated Banc-Corp", sector: "Finance", type: "stock" },
  { ticker: "BOKF", name: "BOK Financial", sector: "Finance", type: "stock" },
  { ticker: "WTFC", name: "Wintrust Financial", sector: "Finance", type: "stock" },
  { ticker: "CBU", name: "Community Bank System", sector: "Finance", type: "stock" },
  { ticker: "FFIN", name: "First Financial", sector: "Finance", type: "stock" },
  { ticker: "SBCF", name: "Seacoast Banking", sector: "Finance", type: "stock" },
  { ticker: "TOWN", name: "TowneBank", sector: "Finance", type: "stock" },
  { ticker: "TRMK", name: "Trustmark", sector: "Finance", type: "stock" },
  { ticker: "BANR", name: "Banner Financial", sector: "Finance", type: "stock" },
  { ticker: "IBTX", name: "Independent Bank TX", sector: "Finance", type: "stock" },
  { ticker: "BHLB", name: "Berkshire Hills", sector: "Finance", type: "stock" },
  { ticker: "CATY", name: "Cathay General", sector: "Finance", type: "stock" },
  { ticker: "HOPE", name: "Hope Bancorp", sector: "Finance", type: "stock" },
  { ticker: "HAFC", name: "Hanmi Financial", sector: "Finance", type: "stock" },
  { ticker: "PPBI", name: "Pacific Premier", sector: "Finance", type: "stock" },
  { ticker: "WAFD", name: "WaFd Inc", sector: "Finance", type: "stock" },
  { ticker: "DCOM", name: "Dime Financial", sector: "Finance", type: "stock" },
  { ticker: "BUSE", name: "First Busey", sector: "Finance", type: "stock" },
  { ticker: "BY", name: "Byline Bancorp", sector: "Finance", type: "stock" },
  { ticker: "NAVI", name: "Navient", sector: "Finance", type: "stock" },
  { ticker: "SLM", name: "SLM Corporation", sector: "Finance", type: "stock" },
  { ticker: "ESNT", name: "Essent Group", sector: "Finance", type: "stock" },
  { ticker: "RDN", name: "Radian Group", sector: "Finance", type: "stock" },
  { ticker: "MTG", name: "MGIC Investment", sector: "Finance", type: "stock" },
  { ticker: "NMIH", name: "NMI Holdings", sector: "Finance", type: "stock" },
  { ticker: "AGO", name: "Assured Guaranty", sector: "Finance", type: "stock" },
  { ticker: "AXS", name: "AXIS Capital", sector: "Finance", type: "stock" },
  { ticker: "RNR", name: "RenaissanceRe", sector: "Finance", type: "stock" },
  { ticker: "ESGR", name: "Enstar Group", sector: "Finance", type: "stock" },
  { ticker: "ORI", name: "Old Republic", sector: "Finance", type: "stock" },
  { ticker: "AFG", name: "American Financial", sector: "Finance", type: "stock" },
  { ticker: "WRB", name: "W.R. Berkley", sector: "Finance", type: "stock" },
  { ticker: "KMPR", name: "Kemper", sector: "Finance", type: "stock" },
  { ticker: "HIG", name: "Hartford Financial", sector: "Finance", type: "stock" },
  { ticker: "SIGI", name: "Selective Insurance", sector: "Finance", type: "stock" },
  { ticker: "PLNT", name: "Planet Fitness", sector: "Consumer", type: "stock" },
  { ticker: "XPOF", name: "Xponential Fitness", sector: "Consumer", type: "stock" },
];
