// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/listWatchlists.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var listWatchlists_default = defineTool({
  name: "list_watchlists",
  title: "List watchlists",
  description: "List all watchlists owned by the signed-in PortAI user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { isError: true, content: [{ type: "text", text: "Not authenticated" }] };
    }
    const { data, error } = await db(ctx).from("watchlists").select("id, name, description, created_at").order("created_at", { ascending: false });
    if (error) return { isError: true, content: [{ type: "text", text: error.message }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { watchlists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/listWatchlistStocks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var listWatchlistStocks_default = defineTool2({
  name: "list_watchlist_stocks",
  title: "List stocks in a watchlist",
  description: "Return the tickers, names, sectors, and signals held in one of the user's watchlists.",
  inputSchema: {
    watchlist_id: z.string().uuid().describe("The watchlist's UUID (from list_watchlists).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ watchlist_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { isError: true, content: [{ type: "text", text: "Not authenticated" }] };
    }
    const { data, error } = await db2(ctx).from("watchlist_stocks").select("id, ticker, name, sector, signal, created_at").eq("watchlist_id", watchlist_id).order("created_at", { ascending: false });
    if (error) return { isError: true, content: [{ type: "text", text: error.message }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { stocks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/addStockToWatchlist.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var addStockToWatchlist_default = defineTool3({
  name: "add_stock_to_watchlist",
  title: "Add stock to watchlist",
  description: "Add a ticker to one of the signed-in user's watchlists.",
  inputSchema: {
    watchlist_id: z2.string().uuid(),
    ticker: z2.string().trim().min(1).max(20),
    name: z2.string().trim().min(1).max(200),
    sector: z2.string().trim().max(100).optional(),
    signal: z2.string().trim().max(50).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ watchlist_id, ticker, name, sector, signal }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { isError: true, content: [{ type: "text", text: "Not authenticated" }] };
    }
    const { data, error } = await db3(ctx).from("watchlist_stocks").insert({
      watchlist_id,
      ticker: ticker.toUpperCase(),
      name,
      sector: sector ?? "",
      signal: signal ?? "hold"
    }).select().single();
    if (error) return { isError: true, content: [{ type: "text", text: error.message }] };
    return {
      content: [{ type: "text", text: `Added ${data.ticker} to watchlist.` }],
      structuredContent: { stock: data }
    };
  }
});

// src/lib/mcp/tools/listPriceAlerts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var listPriceAlerts_default = defineTool4({
  name: "list_price_alerts",
  title: "List price alerts",
  description: "List the signed-in user's price alerts, optionally filtered to active (not-yet-triggered) alerts.",
  inputSchema: {
    only_active: z3.boolean().optional().describe("If true, exclude alerts that already fired.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { isError: true, content: [{ type: "text", text: "Not authenticated" }] };
    }
    let q = db4(ctx).from("price_alerts").select("id, ticker, asset_name, asset_type, direction, target_price, triggered, triggered_at, created_at").order("created_at", { ascending: false });
    if (only_active) q = q.eq("triggered", false);
    const { data, error } = await q;
    if (error) return { isError: true, content: [{ type: "text", text: error.message }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/createPriceAlert.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var createPriceAlert_default = defineTool5({
  name: "create_price_alert",
  title: "Create price alert",
  description: "Create a price alert for the signed-in user that fires when the ticker crosses the target.",
  inputSchema: {
    ticker: z4.string().trim().min(1).max(20),
    asset_name: z4.string().trim().min(1).max(200),
    asset_type: z4.enum(["stock", "crypto", "etf", "index"]).default("stock"),
    direction: z4.enum(["above", "below"]),
    target_price: z4.number().positive()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ ticker, asset_name, asset_type, direction, target_price }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { isError: true, content: [{ type: "text", text: "Not authenticated" }] };
    }
    const { data, error } = await db5(ctx).from("price_alerts").insert({
      user_id: ctx.getUserId(),
      ticker: ticker.toUpperCase(),
      asset_name,
      asset_type,
      direction,
      target_price
    }).select().single();
    if (error) return { isError: true, content: [{ type: "text", text: error.message }] };
    return {
      content: [{ type: "text", text: `Alert created for ${data.ticker} ${direction} ${target_price}.` }],
      structuredContent: { alert: data }
    };
  }
});

// src/lib/mcp/tools/getQuote.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var getQuote_default = defineTool6({
  name: "get_quote",
  title: "Get live quote",
  description: "Fetch the latest price, day change, and change percent for a ticker via PortAI's fetch-quotes function.",
  inputSchema: {
    ticker: z5.string().trim().min(1).max(20).describe("Ticker symbol, e.g. AAPL or BTC-USD.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ ticker }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { isError: true, content: [{ type: "text", text: "Not authenticated" }] };
    }
    const url = `${process.env.SUPABASE_URL}/functions/v1/fetch-quotes`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({ tickers: [ticker.toUpperCase()] })
    });
    if (!res.ok) {
      return { isError: true, content: [{ type: "text", text: `fetch-quotes ${res.status}` }] };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vejlgkyydezrnqrzwodp";
var mcp_default = defineMcp({
  name: "portai-mcp",
  title: "PortAI",
  version: "0.1.0",
  instructions: "Tools for the PortAI stock analysis app. Read the signed-in user's watchlists, add tickers, list and create price alerts, and fetch live quotes. All tools act as the authenticated user under Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    listWatchlists_default,
    listWatchlistStocks_default,
    addStockToWatchlist_default,
    listPriceAlerts_default,
    createPriceAlert_default,
    getQuote_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
