// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-watchlists.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_watchlists_default = defineTool({
  name: "list_watchlists",
  title: "List watchlists",
  description: "List the signed-in user's PortAI watchlists with their tickers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client(ctx);
    const { data: watchlists, error } = await sb.from("watchlists").select("id, name, description, created_at, watchlist_stocks(ticker, name, sector, signal)").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(watchlists ?? [], null, 2) }],
      structuredContent: { watchlists: watchlists ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-watchlist.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_watchlist_default = defineTool2({
  name: "create_watchlist",
  title: "Create watchlist",
  description: "Create a new PortAI watchlist for the signed-in user.",
  inputSchema: {
    name: z.string().trim().min(1).max(80).describe("Name of the watchlist."),
    description: z.string().trim().max(500).optional().describe("Optional description.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async ({ name, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client2(ctx).from("watchlists").insert({ user_id: ctx.getUserId(), name, description: description ?? "" }).select("id, name, description").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created watchlist "${data.name}" (${data.id})` }],
      structuredContent: { watchlist: data }
    };
  }
});

// src/lib/mcp/tools/add-stock-to-watchlist.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_stock_to_watchlist_default = defineTool3({
  name: "add_stock_to_watchlist",
  title: "Add stock to watchlist",
  description: "Add a ticker to one of the signed-in user's PortAI watchlists.",
  inputSchema: {
    watchlist_id: z2.string().uuid().describe("Target watchlist ID (from list_watchlists)."),
    ticker: z2.string().trim().min(1).max(20).describe("Ticker symbol, e.g. AAPL."),
    name: z2.string().trim().min(1).max(120).describe("Company/asset name."),
    sector: z2.string().trim().max(80).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async ({ watchlist_id, ticker, name, sector }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client3(ctx).from("watchlist_stocks").insert({ watchlist_id, ticker: ticker.toUpperCase(), name, sector: sector ?? "" }).select("id, ticker, name").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${data.ticker} to watchlist.` }],
      structuredContent: { stock: data }
    };
  }
});

// src/lib/mcp/tools/list-price-alerts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_price_alerts_default = defineTool4({
  name: "list_price_alerts",
  title: "List price alerts",
  description: "List the signed-in user's active PortAI price alerts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client4(ctx).from("price_alerts").select("id, ticker, asset_name, asset_type, direction, target_price, triggered, triggered_at, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-price-alert.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_price_alert_default = defineTool5({
  name: "create_price_alert",
  title: "Create price alert",
  description: "Create a new PortAI price alert for the signed-in user.",
  inputSchema: {
    ticker: z3.string().trim().min(1).max(20),
    asset_name: z3.string().trim().min(1).max(120),
    asset_type: z3.enum(["stock", "crypto", "etf", "index"]).describe("Asset category."),
    direction: z3.enum(["above", "below"]).describe("Trigger when price crosses above or below the target."),
    target_price: z3.number().positive()
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client5(ctx).from("price_alerts").insert({
      user_id: ctx.getUserId(),
      ticker: input.ticker.toUpperCase(),
      asset_name: input.asset_name,
      asset_type: input.asset_type,
      direction: input.direction,
      target_price: input.target_price
    }).select("id, ticker, direction, target_price").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Alert set: ${data.ticker} ${data.direction} ${data.target_price}` }],
      structuredContent: { alert: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vejlgkyydezrnqrzwodp";
var mcp_default = defineMcp({
  name: "portai-mcp",
  title: "PortAI",
  version: "0.1.0",
  instructions: "Tools for PortAI, an AI investing assistant. Manage the signed-in user's watchlists and price alerts. All actions act as the connected PortAI user and respect their tier and RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_watchlists_default, create_watchlist_default, add_stock_to_watchlist_default, list_price_alerts_default, create_price_alert_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
